### ISSUE TITLE
@lingui/conf on npm has no main file

### ISSUE THREAD

**Issue by capaj** [lingui/js-lingui#1001]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1305378/110821878-cc55ab00-8290-11eb-8be6-e79fb57035bc.png)
these are all the files that get installed from npm, so the main
```
  "main": "index.js",
```
in package.json is pointing to a file that does not exist.

**To Reproduce**

install from npm

**Expected behavior**

main file is present

**Additional context**
This is causing me issues getting lingui work with vite

**Comment by semoal** [comment]
Hm, did you tried to reinstall @lingui/conf? I've installed the package on a empty project and loooks fine to me.

<img width="404" alt="Screenshot 2021-03-14 at 19 20 28" src="https://user-images.githubusercontent.com/22656541/111079465-6a987980-84fa-11eb-8dda-2c03846e0806.png">

**Comment by capaj** [comment]
indeed it has the file. Not sure what happened on my system. Might have been some NPM glitch. Sorry for the trouble.
