### ISSUE TITLE
Plural component requires extract string on each update

### ISSUE THREAD

**Issue by AlexSCorey** [lingui/js-lingui#1003]
**Describe the bug**
In development, when I update strings inside a `<Plural>` I have to run extract-strings to render those updated strings properly. I do not have to do that for strings marked for translation inside `i18n.()`.  Is this expected.

**To Reproduce**
Create <Plural count={jobs} one= "job" other="jobs"/>

replacing the Plural component with the raw I18n function also does not render the proper string until I extract the the strings.  
`i18n._(
                    '{numItemsToDelete, plural, one {The inventory will be in a pending status until the final delete is processed.} other {The inventories will be in a pending status until the final delete is processed.}}',
                    { numItemsToDelete: selected.length }
                  )`

refresh the screen.
**Expected behavior**
Expect that when count is 1 string = job and when count is >1 string  = jobs
**Additional context**
Something like "{0, plural, one {You do not have permission to cancel the following job:} other {You do not have permission to cancel the following jobs:}}" is rendered.  Notice both strings are rendered inside of the {}

My concern here is that if I extract the strings each time they change in order to get them to render properly while in dev. mode I will have a lot of noise in my PRs with these changes, and also that when I ship the compiled strings out to the translation contractors, that actually do the translations, there will be all sorts of merge conflicts when they come back.  

- jsLingui version ``3.7.1``
- Babel version ``7.0.0``
- Create React App

**Comment by semoal** [comment]
Hey Alex, sorry for the late response. 
Are you compiling the catalogs? If i can reproduce this issue someway, i accept some guidance

**Comment by AlexSCorey** [comment]
@semoal I saw that you left some feedback on my PR.  Thanks for doing that.  We do compile the strings when we start the dev server.  

Here is an example of what I see.  The first 2 screen shots are generating the strings 'second' and 'seconds' by using the `<Plural/>` component.  
![Screen Shot 2021-04-06 at 5 18 36 PM](https://user-images.githubusercontent.com/39280967/113780022-945d4e80-96fc-11eb-8408-6c0f9bcb69a2.png)
![Screen Shot 2021-04-06 at 5 18 47 PM](https://user-images.githubusercontent.com/39280967/113780024-945d4e80-96fc-11eb-80c3-35ae9a87852f.png)

The next screen shot is what we see after updating those strings. In order to get these updating strings to render properly I have to run extract-strings, which isn't an instantaneous task.  Is there some way to avoid this?
![Screen Shot 2021-04-06 at 5 20 56 PM](https://user-images.githubusercontent.com/39280967/113780127-c1116600-96fc-11eb-9f4e-04357d2f6920.png)

**Comment by semoal** [comment]
Yes, Lingui offers some plugins for auto-compiling the catalogs when you import them.
https://lingui.js.org/ref/loader.html

In some cases when Webpack isn't used you can use --watch via the cli args of lingui compile which runs a Chokidar instance and auto-refresh the catalogs (but this feature is really new and could have some bugs)

The recommended approach always it's to use dynamic imports() and the @lingui/loader 👍🏻

**Comment by AlexSCorey** [comment]
@semoal I have installed that loader, and implemented the dynamic imports, and it still renders the strings incorrectly.

**Comment by semoal** [comment]
Does it happen on the pull request i've reviewed? I can download it and give it a try, sorry for not being as helpful as i want. But we'll resolve this issue for sure

**Comment by AlexSCorey** [comment]
@semoal first, my team has commented at how helpful you have been so no worries, we are appreciative.  The issue does happen on the PR you have reviewed so that might be a good place to start.  Let me know if you need help getting it running.

**Comment by iStefo** [comment]
Thank so you much, that's great to hear. Don't worry about the release, next week is absolutely fine!
