### ISSUE TITLE
Eslint plugin to enforce usage

### ISSUE THREAD

**Issue by darkowic** [lingui/js-lingui#1006]
**Is your feature request related to a problem? Please describe.**
There are different ways of defining messages. It can be by using id only, message only, or message and id.

**Describe proposed solution**
There is some plugin for lingui but looks like its not open source (?) https://www.npmjs.com/package/eslint-plugin-string-to-lingui

Do you have propositions for API? I can try to implement it.

**Comment by semoal** [comment]
That could be an amazing idea. https://github.com/lingui/codemods
In this repo we introduced practically all the migrations from v2 standard to the new standard.

Every transform has a little description of the behaviour, so probably could be helpful. 
https://github.com/lingui/codemods/blob/main/transforms/v2-to-v3.ts

**Comment by joshhunt** [comment]
It would be neat for a linter to pick up on trying to do silly things like

```jsx
const icon = <DeleteIcon />
<Trans>{icon} Delete</Trans>
```

This would probably rely on (typescript) type information, which I'm unsure can be used in an eslint plugin...

**Comment by semoal** [comment]
Once I cleanup my backlog with Rematch, I'll give priority to this since v3 it's pretty stable.
I want to create a little roadmap for the next version (not major, just minor)

- Refactor some libraries which are "deprecated" like messageformat-parser
- Performance benchmarking and optimizations.
- Eslint-lingui
- Bug fixes, bug fixes and more bug fixes :)

**Comment by taozhou-glean** [comment]
I just saw this issue and found https://www.npmjs.com/package/eslint-plugin-string-to-lingui which seems to be a pretty good eslint plugin out there, tho the project seems not on github or not public, owner seems to be @igorDolzh , but could not find any contact to reach out.
