### ISSUE TITLE
Trouble with Ionic + TypeScript

### ISSUE THREAD

**Issue by ptmkenny** [lingui/js-lingui#1008]
**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

I'm using Ionic version 5 with React.  My whole project is in TypeScript.  I just installed lingui according to the [create-react-app instructions](https://lingui.js.org/tutorials/setup-cra.html) (Ionic uses create-react-app).

***App.js**

 ```
i18n.load('en', messages);
i18n.activate('en');

const App: React.FC = () => (
  <IonApp>
    <I18nProvider i18n={i18n}>
      <MyAppStuff />
    </I18nProvider>
  </IonApp>
);
```

**loginForm.tsx**

```
import { Trans } from '@lingui/react';

  if (mutateLogin.isSuccess) {
    return (
      <>
        <p><Trans>Login successful!</Trans></p>
        <p><Trans id="message.wait">Please wait a moment...</Trans></p>
      </>
    );
  }
```

With code like this, I get two errors:

For the first `<Trans>`:

`TS2741: Property 'id' is missing in type '{ children: string; }' but required in type 'Pick<TransProps, "id" | "message" | "formats" | "component" | "render">'.`

And for the second `<Trans>`:

`<html>TS2322: Type '{ children: string; id: string; }' is not assignable to type 'IntrinsicAttributes &amp; Pick&lt;TransProps, &quot;id&quot; | &quot;message&quot; | &quot;formats&quot; | &quot;component&quot; | &quot;render&quot;&gt; &amp; Partial&lt;Pick&lt;TransProps, &quot;values&quot; | &quot;components&quot;&gt;&gt; &amp; Partial&lt;...&gt;'.<br/>Property 'children' does not exist on type 'IntrinsicAttributes &amp; Pick&lt;TransProps, &quot;id&quot; | &quot;message&quot; | &quot;formats&quot; | &quot;component&quot; | &quot;render&quot;&gt; &amp; Partial&lt;Pick&lt;TransProps, &quot;values&quot; | &quot;components&quot;&gt;&gt; &amp; Partial&lt;...&gt;'.`

**Expected behavior**

**Additional context**

- jsLingui version ``lingui --version``
 3.7.2

- Babel version ``npm list @babel/core`` 
```
└─┬ react-scripts@4.0.3
  ├── @babel/core@7.12.3 
  ├─┬ @svgr/webpack@5.5.0
  │ ├── @babel/core@7.12.3  deduped
  │ └─┬ @svgr/plugin-jsx@5.5.0
  │   └── @babel/core@7.12.3  deduped
  ├─┬ babel-jest@26.6.3
  │ ├─┬ @jest/transform@26.6.2
  │ │ └── @babel/core@7.12.3  deduped
  │ └─┬ babel-plugin-istanbul@6.0.0
  │   └─┬ istanbul-lib-instrument@4.0.3
  │     └── @babel/core@7.12.3  deduped
  ├─┬ babel-preset-react-app@10.0.0
  │ └── @babel/core@7.12.3  deduped
  ├─┬ jest@26.6.0
  │ └─┬ @jest/core@26.6.3
  │   └─┬ jest-config@26.6.3
  │     └── @babel/core@7.12.3  deduped
  └─┬ workbox-webpack-plugin@5.1.4
    └─┬ workbox-build@5.1.4
      └── @babel/core@7.12.3  deduped
```

-Typescript 4.2.3

[Similar issue](https://github.com/lingui/js-lingui/issues/628) that was closed as "cannot reproduce"

**Comment by semoal** [comment]
Could you provide us a little repo with this code to analyse this issue? I'll be glad to help

**Comment by ptmkenny** [comment]
Thanks, please check this repo: https://github.com/ptmkenny/lingui-js-debug

`npm install`

`ionic serve`

will fail to compile with this error:

```
lingui-js-debug/debug-react-app/src/pages/Tab1.tsx
TypeScript error in /home/pk/d/lingui-js-debug/debug-react-app/src/pages/Tab1.tsx(19,35):
Property 'id' is missing in type '{ children: string; }' but required in type 'Pick<TransProps, "id" | "message" | "formats" | "component" | "render">'.  TS2741

    17 |       <IonHeader collapse="condense">
    18 |         <IonToolbar>
  > 19 |           <IonTitle size="large"><Trans>Tab 1</Trans></IonTitle>
       |                                   ^
    20 |         </IonToolbar>
    21 |       </IonHeader>
    22 |       <ExploreContainer name="Tab 1 page" />
```

**Comment by semoal** [comment]
Found, the problem is that you're importing Trans from Lingui react package, import always Trans from macro package and date() and number() from core. 

In v3.0.0 we simplified core to avoid future issues of people importing Trans from react but then not running the macro.

**Comment by ptmkenny** [comment]
Ok thanks.  I'll also add that for anyone using PHPStorm, after setting up Lingui, if you have Eslint support enabled, you have to close and re-open the IDE or there will be a bunch of mysterious errors.
