### ISSUE TITLE
Where has the documentation gone?

### ISSUE THREAD

**Issue by Kernle32DLL** [lingui/js-lingui#101]
Hi,

while I am aware that the documentation is currently being reworked (as in pretty much every project ;-) ), at the moment no documentation is publicly available, making it very hard to work with js-lingui.

We have...
https://lingui.gitbooks.io/js/
https://www.gitbook.com/book/lingui/js/details
https://lingui.github.io/js-lingui/ (did work ~2 or 3 days ago)

... and none of them work.

**Comment by tricoder42** [comment]
Hi @Kernle32DLL,
I'm sorry for this inconvenience. For some reason GitHub doesn't serve documentation under some (for now unknown) circumstances.

The official documentation is https://lingui.github.io/js-lingui/. It works now.

**Followup:**
- I've setup ping monitor to periodically check, that documentation works.
- I'm gonna ask support what's going on and how can I debug it. Simply sending empty commit to `gh-pages` branch solves the problem sometimes, which is weird.
