### ISSUE TITLE
How do I use a variable in t()?

### ISSUE THREAD

**Issue by ptmkenny** [lingui/js-lingui#1011]
**Describe the bug**

I don't understand how I need to wrap my JSX to use variables within strings with t().

I'm trying to translate the local notifications for my Ionic app with code like this:

```
const getNotificationBodyReview = (totalCount) => {
  if (totalCount >= 1) {
    const messageTranslated = t({ id: 'notification.count_today', message: `You have ${totalCount}.` });
    console.log('messageTranslated', messageTranslated);
    const messagePlain = `You have ${totalCount}.`;
    console.log('messagePlain', messagePlain);
  }
};
```

And here is the output:

```
[Log] messageTranslated – "You have {totalCount}." (user-script:2, line 78)
[Log] messagePlain – "You have 1." (user-script:2, line 78)

```

So when I use t(), the variable does not get used.

Is there a way to insert the value of the variable with t() without breaking it up into several strings?

**Comment by iffjey** [comment]
I believe you should use it like this

```
  const totalCount = 100;
  const message = t({
    id: 'notification.count_today',
    message: 'You have {totalCount}',
    values: { totalCount }
   });
  ```

Look at MessageDescriptor type [here](https://github.com/lingui/js-lingui/blob/ecf83c37e177cb10f157fb8913d73e18662e3ca4/packages/core/src/i18n.ts#L31)

**Comment by semoal** [comment]
message property it's also interporlated this behaviour should work as expected:
```js
import { t } from '@lingui/macro'
const value = 'hello'
const msg = t({ id: 'msgId', message: `Some ${value}` })
```
It's extracted by lingui to:
```js
import { i18n } from "@lingui/core";
const value = 'hello'
const msg = i18n._(/*i18n*/
        {
          id: "msgId",
          message: "Some {value}",
          values: {
            value: value,
          },
        });
      
```

I've added a test to corroborate https://github.com/lingui/js-lingui/commit/38ccf3a8abe5bbc0ef296a1135be789ebd864e99 👍🏻 

I think the problem of your code @ptmkenny is that you need to run extract & compile, if you expect to console log a macro and see something, you're wrong. Feel free to check all our examples and our test suite :)

**Comment by ptmkenny** [comment]
Ok thanks, I didn't realize I couldn't debug using console.log.  I've got it working now, thanks again!

**Comment by qinhua** [comment]
Why doesn't it work when used this way? the '$' is missing
```html
import { msg } from '@lingui/macro'
import { useLingui } from '@lingui/react'

export const Demo = () => {
 const { _ } = useLingui()

// The field "name" is dynamic content retrieved from the backend API.
 return <Typography>{_(msg`Congratulations! You have redeemed ${name} successfully!`)}</Typography>
}
```
**after extract**
```text
#: src/pages/Shop/module/component/product-detail/OrderPlacedContent.tsx
#: src/pages/Shop/module/component/product-detail/OrderPlacedContent.tsx
msgid "Congratulations! You have redeemed {name} successfully!"
msgstr "Congratulations! You have redeemed {name} successfully!"
```
**final render**
```html
<Typography>Congratulations! You have redeemed {name} successfully!</Typography>
```

**Comment by thekip** [comment]
All looks fine, please console.log what ``  msg`Congratulations! You have redeemed ${name} successfully!`  `` returned and post it here.

**Comment by qinhua** [comment]
> All looks fine, please console.log what `` msg`Congratulations! You have redeemed ${name} successfully!` `` returned and post it here.

I have tried many times, but still in vain.

However, when I tried again today, I found the key point.
I found that when the variable in the template string comes from a reference type, it works fine. If it is a single variable or constant, the problem I encountered will occur (displaying the original text)，just as follow：

### 1. My current situation

```ts
import { msg } from '@lingui/macro'
import { useLingui } from '@lingui/react'

const  LIMIT_COUNT =  3
const LIMIT_SIZE = 3145728

export const Demo = () => {
 const { _ } = useLingui()

 return <Typography>{_(msg`No more than ${LIMIT_COUNT} images can be uploaded`)}</Typography>
}
```

**extracted**
```bash
#: src/pages/Games/module/GameDetail/module/reviews/component/ReviewPostModal/ImageUploadList.tsx
msgid "No more than {LIMIT_COUNT} images can be uploaded"
msgstr "最多只能上传 {LIMIT_COUNT} 张图片"
```

**rendered**
```html
<Typography>最多只能上传 {LIMIT_COUNT} 张图片</Typography>
```

### 2. When i changed the variable to a reference type，it worked fine

```ts
import { msg } from '@lingui/macro'
import { useLingui } from '@lingui/react'

// here, I put these variables in an object
const FileConfig = {
  LIMIT_COUNT: 3,
  LIMIT_SIZE: 3145728
}

export const Demo = () => {
 const { _ } = useLingui()

 return <Typography>{_(msg`No more than ${FileConfig.LIMIT_COUNT} images can be uploaded`)}</Typography>
}
```

**extracted**
```bash
#: src/pages/Games/module/GameDetail/module/reviews/component/ReviewPostModal/ImageUploadList.tsx
msgid "No more than {0} images can be uploaded"
msgstr "最多只能上传 {0} 张图片"
```

**rendered**
```html
<Typography>最多只能上传 3 张图片</Typography>
```

**Comment by thekip** [comment]
There was a similar issue somewhere in the past, try to use camelCase instead of UPPER_CASE 

```ts
import { msg } from '@lingui/macro'
import { useLingui } from '@lingui/react'

const limitCount =  3

export const Demo = () => {
 const { _ } = useLingui()

 return <Typography>{_(msg`No more than ${limitCount} images can be uploaded`)}</Typography>
}
```

and post here a result

**Comment by thekip** [comment]
Just checked that issue i mentioned and it seems it's not related. But still try to rename also copy and post here compiled code (which is actually executed by browser) 

BTW

```tsx
// this could be written using <Trans> 
import { Trans } from "@lingui/macro";
 
export const Demo = () => {
 const { _ } = useLingui()

 return <Typography><Trans>No more than {limitCount} images can be uploaded</Trans></Typography>
}
```
