### ISSUE TITLE
fallbackLocales CLDR Parent Confusion

### ISSUE THREAD

**Issue by nathanforce** [lingui/js-lingui#1014]
**Describe the bug**

We are getting the following warning when building our app using the webpack loader.

```
        Catalog "es" isn't present in locales config parameter
        Add "es" to your lingui.config.js:
        {
          locales: ["en-US", "es-US", "es"]
        }
```

.linguirc
```
{
  "catalogs": [
    {
      "path": "<rootDir>/src/locales/{locale}/messages",
      "include": [
        "<rootDir>/src/"
      ],
      "exclude": [
        "**/node_modules/**"
      ]
    }
  ],
  "fallbackLocales": {
    "default": "en-US"
  },
  "format": "po",
  "formatOptions": {
    "origins": false
  },
  "locales": [
    "en-US",
    "es-US"
  ],
  "orderBy": "origin",
  "runtimeConfigModule": [
    "@packages/localization",
    "i18n"
  ],
  "sourceLocale": "en-US"
}

```

None of our code references the parent locale, `es`, at all.  My best guess is that in trying to resolve a translation the loader is eventually reading the resolved config's fallbackLocales which are a combination of our actual config + CLDR parents. For example.

```
{ 
    default: 'en-US, // ours, from .linguirc
    en-US: ['en'],  // added by Lingui
    es-US: ['es'],  // added by Lingui
}
```

My question is..how do we resolve the warning? We want all locales to fallback to English (en-US) in the case of a missing translation, as we think for our production users an untranslated string is better than nothing/placeholder.

**Expected behavior**

Since we've provided a `default` fallbackLocale I'd expect to be opted-out of the CLDR parent logic.

**Additional context**

```
    "@lingui/core": "3.7.2",
    "@lingui/cli": "3.7.2",
    "@lingui/loader": "3.7.2",
```

**Comment by semoal** [comment]
I think we have a little bug in this situation, re-reading the code.
https://github.com/lingui/js-lingui/blob/main/packages/conf/src/index.ts#L308
We're still searching on config.locales the cldr fallbacks, instead of just using the default one.

If you want to patch it on your node_modules and give it a try if it works, i'll release a fix at the end of today.

```diff
function fallbackLanguageMigration(config) {
  var fallbackLocale = config.fallbackLocale,
      fallbackLocales = config.fallbackLocales;
  if (fallbackLocales === false) return _objectSpread(_objectSpread({}, config), {}, {
    fallbackLocales: null
  });
-   config.locales.forEach(function (locale) {
-     var fl = getCldrParentLocale(locale.toLowerCase());
- 
-     if (fl && !config.fallbackLocales[locale]) {
-       config.fallbackLocales = _objectSpread(_objectSpread({}, config.fallbackLocales), {}, (0, _defineProperty2.default)({}, locale, fl));
-     }
-   });
  var DEFAULT_FALLBACK = (fallbackLocales === null || fallbackLocales === void 0 ? void 0 : fallbackLocales.default) || fallbackLocale;

  if (DEFAULT_FALLBACK) {
    if (!config.fallbackLocales) config.fallbackLocales = {};
    config.fallbackLocales.default = DEFAULT_FALLBACK;
  }

+ if (!config.fallbackLocales.default) {
+   config.locales.forEach(function (locale) {
+     var fl = getCldrParentLocale(locale.toLowerCase());
+ 
+     if (fl && !config.fallbackLocales[locale]) {
+       config.fallbackLocales = _objectSpread(_objectSpread({}, config.fallbackLocales), {}, (0, _defineProperty2.default)({}, locale, fl));
+     }
+   });
+ }

  return config;
}
```

This should be the fix, just moving that .forEach behind the fallbackLocale logic and checking that default is null,

**Comment by nathanforce** [comment]
Thank you @semoal. I just confirmed that the patch resolves the warning.

**Comment by semoal** [comment]
Great, I'll release the fix in a few hours IM out home right now

**Comment by semoal** [comment]
The release workflow have just started, we'll be released in a few minutes. 3.8.1 👍🏻 

thanks for the reporting mate!
