### ISSUE TITLE
Failure in calculation of multiple variables

### ISSUE THREAD

**Issue by zuiidea** [lingui/js-lingui#1018]
**Describe the bug**
Failure in calculation of multiple variables.

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```
import { Trans } from "@lingui/react"

export default function App() {
   const [count, setCount] = useState(0);
   const message = "message"
   return <Trans>Hello, {message + count}</Trans>
}
```

code demo ：https://github.com/zuiidea/js-lingui/commit/87f8be5298f806ffe0b89534484d42baff99023c

**Expected behavior**

- I get message ID `Hello, {0}` by run `lingui extract`.
- I modified and compiled the messages in `Česky` language.
- **Should be displayed as `Česky message0` instead of `Hello, {0}` in `Česky` language.**

- English is correct：

![截屏2021-03-31 上午10 35 41](https://user-images.githubusercontent.com/16070518/113082340-dffb8e00-920c-11eb-884b-7978d6cb9f02.png)

- Česky is wrong：

![截屏2021-03-31 上午10 35 33](https://user-images.githubusercontent.com/16070518/113082331-db36da00-920c-11eb-9944-68d85c18a7d0.png)

- jsLingui version : 3.8.1
- Babel version : latest
- Your Babel config : Create React App

**Comment by zuiidea** [comment]
I found the cause of this problem：
It may be a problem with ESM packaging，I used CJS to temporarily solve my problem.

example:
```
import { setupI18n } from '@lingui/core';
```
change to 

```
import { setupI18n } from '@lingui/core/index';
```

You may need to set loadLocaleData to avoid console errors:

```
const i18n = setupI18n()
i18nBase.loadLocaleData('en', {
  plurals: () => {},
})
```

**Comment by semoal** [comment]
you don't need setupI18n just use the singleton instance, and loadLocaleData you must load the plurals. 
After the issue don't have so much sense to me that the issue is related to esm, anyways i'll try to take a look asap

**Comment by semoal** [comment]
You only need to translate the translation file of cz. As you can check the en.po file is automatic translated, but the po file of cz is:
```
#: src/App.tsx:21
msgid "Increment {0}"
msgstr ""
```

If you change it to:

```
#: src/App.tsx:21
msgid "Increment {0}"
msgstr "Přírůstek {0}"
```
Will work as expected

**Comment by zuiidea** [comment]
I understand！sorry, I found that `@lingui/loader` is not used to process`message.json` files in my project.
Thank you very much for your reply.
