### ISSUE TITLE
Cannot pass "values" directly to <Trans /> component

### ISSUE THREAD

**Issue by whytspace** [lingui/js-lingui#1019]
I updated to version 3 (3.8.1) from version 2 (2.9.1). Had to make a few adaptions but nothing too serious. I like the new version 👍 

**Describe the bug**
The is one problem after upgrading that I need help with: I have been using the `<Trans />` component from `@lingui/macro` heavily throughout the code, mostly like this:

```jsx
<Trans
  id="some.message.id"
  values={{ /* values passed in directly */ }}
  comment="Variables: describing all the values passed in"  
>
    English placeholder text
</Trans>
```

Now, it seems that `values` is not part of the type definition of `Trans` anymore, even though the **actual translation works perfectly fine** when `values` is specified.
**Is that a bug in the type definition or am I using it wrong?**

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```jsx
import { Trans } from "@lingui/macro"

export default function App() {
  const values = { foo: "bar" }
   return (<Trans id="my.test.message" values={values} comment="Variables: foo (test string)">
      This should be translated and variables should be available!
   </Trans>);
}
```

message catalogue:
```po
msgid "my.test.message"
msgstr "Translated message for foo: {foo}"
```

**Expected behavior**
`values` can be supplied directly to `Trans` as a prop. Or a different strategy to achieve the same goal.

**Alternatives I tried**

I tried adding the `values` prop ty the type definition myself locally, but I cannot manage to make it work. Maybe I am doing it wrong?

```ts
import { TransProps } from "@lingui/macro";
import { ComponentType } from "react";

declare module "@lingui/macro" {
  /**
   * allow passing values to <Trans /> component directly
   */
  export const Trans: ComponentType<TransProps & { values: {} }>;
}
```

**Additional context**

- jsLingui version ``3.8.1``
- Babel version ``@babel/core@7.10.1``
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)  
  I am using **create-react-app** with `@rescripts/cli` in order to change some config without extracting

This is my `lingui.config.js`:

```js
module.exports = {
  catalogs: [
    {
      path: "src/locales/{locale}/messages",
      include: ["src/"],
      exclude: ["**/node_modules/**"],
    }
  ],
  locales: [
    "en",
    "de",
    "it",
    // ... some more
    "pseudo-LOCALE",
  ],
  format: "po",
  sourceLocale: "en",
  pseudoLocale: "pseudo-LOCALE",
  compileNamespace: "ts",
  fallbackLocales: {
    it: "en",
    // ... some more
  },
};
```

**Comment by semoal** [comment]
Try to import the Trans component from the macro package instead of the react one.

**Comment by semoal** [comment]
> Try to import the Trans component from the macro package instead of the react one.

To explain this a bit more for future users, since Lingui.js internally was replacing @lingui/react imports to @macro imports, we decided in v3 to recommend use directly the macro import to avoid that extra computations steps. 

I'm assess of adding some warning to Trans import from the React package suggesting the usage of macro package

**Comment by whytspace** [comment]
@semoal Thanks for the reply. I just double checked my code: I am importing `Trans` from `@lingui/macro` in my code. Seems I wrote `@lingui/ react` only here in my example.

The only thing I import from `@lingui/react` are `useLingui` and `I18nProvider`

**Comment by semoal** [comment]
Ah damn, you're right the type is wrong.
https://github.com/lingui/js-lingui/blob/main/packages/macro/index.d.ts#L31

Let me fix this and I'll release it in a few minutes

**Comment by semoal** [comment]
There we go, released mate v3.8.2. Give it a try and feel to close if we resolved the issue.
Thanks for reporting this out! 🥇

**Comment by whytspace** [comment]
@semoal Thanks for fixing this so quickly! Works perfectly fine now.

---

Just as a note for others that might also stumble upon this problem:

Whenever I defined a type for the `values` property I now had to explicitly cast it to `{}`, otherwise compiler would complain about missing index structures of my type.

```
Type 'ICustomObjectType' is not assignable to type 'Record<string, unknown>'.
  Index signature is missing in type 'ICustomObjectType'.
```

Example:

```tsx
type ICustomObjectType {
  foo: number;
  bar: number;
}


export default function App() {
   const values: ICustomObjectType = { foo: 1, bar: 2 }
   // this would not work!
   // return <Trans id="my.test.message" values={values} />;
   // need to cast values to `{}`
   return <Trans id="my.test.message" values={values as {}} />;
}
```

**Comment by whytspace** [comment]
> What version of Typescript are you using mate?

3.9.3

4.2.3 is the latest now. I guess it's about time that I upgrade. :)
