### ISSUE TITLE
Programatically compiling languages / catalog

### ISSUE THREAD

**Issue by Kernle32DLL** [lingui/js-lingui#102]
Hi,

I'm not sure if this is the right place to ask, but as I suppose that the feature I require is missing, I am opening an issue here.

Details here:
https://stackoverflow.com/questions/46619062/programatically-compile-languages-with-js-lingui

In short:
I'm looking for a way, to programmatically compile my languages / catalog. Pretty much what `lingui-cli compile` does, but in-code.

My use-case is that I have my messages / translations already extracted into a different format (properties files for server-side-rendering), and want to write a gulp-task or webpack-loader, which allows me to read in the translations, and compile them to lingui js files.

As mentioned on SO, I toyed around with require'ing `lingui-cli`, but that did not work as expected. In an ideal case, I would be looking for an exported function in `lingui-i18n`, which takes in an array of objects (in a specified format, of the available ones), and returns the compiled content.

With some guidance, I could probably cook up a PR if desired.

**Comment by tricoder42** [comment]
Hi @Kernle32DLL,
that's a great idea! Let's do it.

lingui compile command is defined in [lingui-compile.js](https://github.com/lingui/js-lingui/blob/master/packages/lingui-cli/src/lingui-compile.js). Basically we need to extract everything from [line 75](https://github.com/lingui/js-lingui/blob/master/packages/lingui-cli/src/lingui-compile.js#L74) plus loading plural rules on [lines 38-43](https://github.com/lingui/js-lingui/blob/master/packages/lingui-cli/src/lingui-compile.js#L38) to public API method.

Compilation of single message is handled in [api/compile.js](https://github.com/lingui/js-lingui/blob/master/packages/lingui-cli/src/api/compile.js), but it's not exported publicly.

We could do following:
- add a new method `compileMessages(locale: string, messages: {[ msgId: string ]: string })` to `api/compile.js`
- export all modules in `api` folder so we can import them as `import { compileMessages } from 'lingui-cli/api/compile`

If you have a spare time and are willing to send a PR, I'm more than happy to help!

**Comment by Kernle32DLL** [comment]
@tricoder42 great, I will look into it :)

**Comment by tricoder42** [comment]
@Kernle32DLL Are you still working on this? May I help with anything? I'm gonna spend some time on this project in next few days, so I might fix it as well.

**Comment by Kernle32DLL** [comment]
@tricoder42 Ah, I didn't get to look into it :S I will give it a spin tomorrow (monday), and get back to you.

**Comment by Kernle32DLL** [comment]
I didn't have time to look at it - again. It seems I cannot develop with my windows machine (well, most of the tests fail, although they shouldn't from eye balling them - I suspect line feed incompatibility). I will look into that tomorrow, when I have access to my Ubuntu laptop.

**Comment by tricoder42** [comment]
No problem, I’m off until Wednesday, I can help you or do it then :)

13. 11. 2017 v 22:53, Björn Gerdau <notifications@github.com>:

**Comment by tricoder42** [comment]
I did a bit research yesterday. The easiest way is copy package.json to `dist` dir and run `npm publish` from there. This makes *flat* module, and we can import `lingui-cli/api/compile`. However, it's not possible, because we use lerna to publish packages and lerna publishes always from package root. There's open feature for it https://github.com/lerna/lerna/issues/901

For now, it's possible to import low-level api from `lingui-cli/dist/api`. I know it's suboptiomal, but works good for temporary workaround.

**Comment by tricoder42** [comment]
Fixed in `@lingui/cli@2.0.0`. Scripts can be imported from `@lingui/cli/api`
