### ISSUE TITLE
export PluralProps from lingui

### ISSUE THREAD

**Issue by kopax-polyconseil** [lingui/js-lingui#1020]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I use `@types/lingui__core` because my IDE and typescript shows a typing error dispate `select.d.ts` being defined.

**Describe proposed solution**

I propose to export PluralProps from @lingui/core` as a named param.

**Describe alternatives you've considered**

Copy and past the typing in my code, that's not the best alternative

**Additional context**

Currently, it is not possible to use `PluralsProps` without typing error:

```ruby
ESLint: Unable to resolve path to module '@lingui/core/select'.(import/no-unresolved)
```

or

```ruby
ESLint: Unable to resolve path to module '@lingui/macri/select'.(import/no-unresolved)
```

**Comment by semoal** [comment]
Since version 3 @types/lingui aren't required because are bundled already on the package

**Comment by kopax-polyconseil** [comment]
How do you import `PluralsProps` to use it in our application?
