### ISSUE TITLE
Cannot extract using i18n.plural : undefined is not iterable!

### ISSUE THREAD

**Issue by kopax-polyconseil** [lingui/js-lingui#1022]
Hello, we use lingui v2.9.2 and we got issue extracting using `i18n.plural`:

This works:

```tsx
export function _(
  id: MessageDescriptor | string,
  values?: Record<string, unknown>,
  messageOptions?: MessageOptions
): string {
  if (typeof id === 'string') {
    return i18n._(id, values, messageOptions)
  }
  return i18n._(id)
}
```

This fail:

```tsx
export function _(id: MessageDescriptor | PluralProps): string {
  return !Object.prototype.hasOwnProperty.call(id, 'one')
    ? i18n._(id as MessageDescriptor)
    : i18n.plural(id as PluralProps)
}
```

It fails when we run `lingui extract --clean`, with the following error:

```ruby
TypeError: src/libs/i18n.ts: undefined is not iterable!
    at module.exports.require.getIterator (/home/dka/workspace/github.com/pass-culture/pass-culture-app-native/node_modules/babel-runtime/node_modules/core-js/library/modules/core.get-iterator.js:5:42)
    at Transformer.transformChoiceMethod (/home/dka/workspace/github.com/pass-culture/pass-culture-app-native/node_modules/@lingui/babel-plugin-transform-js/transformer.js:199:56)
    at Transformer.transformMethod (/home/dka/workspace/github.com/pass-culture/pass-culture-app-native/node_modules/@lingui/babel-plugin-transform-js/transformer.js:393:21)
    at PluginPass.Transformer.transform (/home/dka/workspace/github.com/pass-culture/pass-culture-app-native/node_modules/@lingui/babel-plugin-transform-js/transformer.js:69:25)
    at newFn (/home/dka/workspace/github.com/pass-culture/pass-culture-app-native/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/home/dka/workspace/github.com/pass-culture/pass-culture-app-native/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/dka/workspace/github.com/pass-culture/pass-culture-app-native/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/dka/workspace/github.com/pass-culture/pass-culture-app-native/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/home/dka/workspace/github.com/pass-culture/pass-culture-app-native/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/dka/workspace/github.com/pass-culture/pass-culture-app-native/node_modules/babel-traverse/lib/context.js:108:19) {
  _babel: true
}
```

We rather use the synthax of `i18n.plural` instead of `i18n._`, how can this be fixed ?

### Reproduction

- [`package.json`](https://github.com/pass-culture/pass-culture-app-native/blob/master/package.json#L107)

```bash
git clone https://github.com/pass-culture/pass-culture-app-native.git
cd pass-culture-app-native
nvm use
yarn
yarn run translations:extract
```
### Related issues

- https://github.com/lingui/js-lingui/issues/1020

**Comment by semoal** [comment]
Hey mate, i could take a look to the issue. But... what do you think if you give some days and i migrate your entire codebase to Lingui v3 with the best practices?
Is it possible for your side?

**Comment by kopax** [comment]
HI @semoal , I am quite surprise of your proposition and of course, I can only accept if that solve the problem. I have tried to migrate the whole today but the upgrade step was not straightforward so I rolled back.

You can fork and create a repo, I'll reproduce the PR when needed.

**Comment by semoal** [comment]
I took a look and looks there's no much to change and I'm sure that for the future will be easier for you, with all the power of Lingui with plurals, select and other cool methods. 

(Of course will be a good real example how a migration to v3 can be done and useful for documenting or fixing any that is wrong on v3)

I'll create a fork this weekend and probably in a few days I'll create a pr! 👍🏻

**Comment by semoal** [comment]
> I took a look and looks there's no much to change and I'm sure that for the future will be easier for you, with all the power of Lingui with plurals, select and other cool methods.
> 
> (Of course will be a good real example how a migration to v3 can be done and useful for documenting or fixing any that is wrong on v3)
> 
> I'll create a fork this weekend and probably in a few days I'll create a pr! 👍🏻

Along today or tomorrow I'll create the pull request mate, I'm polishing some details :)

I'm already green our your entire suite =)
```bash
Test Suites: 222 passed, 222 total
Tests:       4 skipped, 1271 passed, 1275 total
Snapshots:   88 passed, 88 total
Time:        75.51s
Ran all test suites.
✨  Done in 76.80s.
```

**Comment by kopax-polyconseil** [comment]
Thanks @semoal that's great, did you manage to use `i18n.plural` API? May I have a check on your branch?

**Comment by semoal** [comment]
> Thanks @semoal that's great, did you manage to use `i18n.plural` API? May I have a check on your branch?

Yes, just tried to use the <Plural /> macro and the plural() macro and both works nicely :)

.tsx file somehwere there:
```tsx
      <Plural value={0} one="# prueba" other="# pruebas" />
      {plural(0, {
        one: '# message',
        other: '# messages',
      })}
```

.po extracted:

```
#: src/features/bookings/components/BookingPropertiesSection.tsx:20
msgid "{0, plural, one {# message} other {# messages}}"
msgstr "{0, plural, one {# message} other {# messages}}"

#: src/features/bookings/components/BookingPropertiesSection.tsx:19
msgid "{0, plural, one {# prueba} other {# pruebas}}"
msgstr "{0, plural, one {# prueba} other {# pruebas}}"

```

**Comment by kopax-polyconseil** [comment]
@semoal, I just rebased and tested your PR: and it seems the syntax in `i18n.ts` is not valid:  

```tsx
import { i18n } from '@lingui/core'
import { fr } from 'make-plural/plurals'

i18n.loadLocaleData({
  fr: { plurals: fr },
})

export const activate = async (locale: string) => {
  const { messages } = await import(`../locales/${locale}/messages`)
  i18n.load(locale, messages)
  i18n.activate(locale)
}
```

Result on startup error:

```
error: src/libs/i18n.ts: src/libs/i18n.ts:Invalid call at line 9: import("../locales/" + locale + "/messages")
```

Do you have a clue? I am now investigating.

**Comment by semoal** [comment]
> @semoal, I just rebased and tested your PR: and it seems the syntax in `i18n.ts` is not valid:
> 
> ```tsx
> import { i18n } from '@lingui/core'
> import { fr } from 'make-plural/plurals'
> 
> i18n.loadLocaleData({
>   fr: { plurals: fr },
> })
> 
> export const activate = async (locale: string) => {
>   const { messages } = await import(`../locales/${locale}/messages`)
>   i18n.load(locale, messages)
>   i18n.activate(locale)
> }
> ```
> 
> Result on startup error:
> 
> ```
> error: src/libs/i18n.ts: src/libs/i18n.ts:Invalid call at line 9: import("../locales/" + locale + "/messages")
> ```
> 
> Do you have a clue? I am now investigating.

Yes, that's my bad (not an expert react-native developer, just web ^^) looks metro/native/expo i don't know how it's called doesn't support dynamic imports 
https://github.com/facebook/metro/issues/52#issuecomment-496322379

you reimplement this to:
```tsx
export async function activate(locale: string) {
   let catalog: {messages: Messages}

   switch (locale) {
     case 'en':
       catalog = await import('./locales/en/messages.po')
       break
     case 'fr':
     default:
       catalog = await import('./locales/fr/messages.po')
       break;
   }

   i18n.load(locale, catalog.messages)
   i18n.activate(locale)
}
```

**Comment by kopax-polyconseil** [comment]
@semoal thanks again for your support, so far, I have removed the import the dynamic import part and there's an issue with `make-plurals`:

```yarn
error: Error: Unable to resolve module `make-plural/plurals` from `src/libs/i18n.ts`: make-plural/plurals could not be found within the project.
```

I've checked and followed the recommendation to clean the projet, despite the module is existing in `node_modules`, I can't get my app to start, if you have a clue, thanks, otherwise I'll keep digging.

**Comment by semoal** [comment]
> @semoal thanks again for your support, so far, I have removed the import the dynamic import part and there's an issue with `make-plurals`:
> 
> ```
> error: Error: Unable to resolve module `make-plural/plurals` from `src/libs/i18n.ts`: make-plural/plurals could not be found within the project.
> ```
> 
> I've checked and followed the recommendation to clean the projet, despite the module is existing in `node_modules`, I can't get my app to start, if you have a clue, thanks, otherwise I'll keep digging.

https://github.com/eemeli/make-plural/issues/15
Looks like you have to accept your metro config to accept .mjs files, since make-plural resolves to browser instead (also make sure that is installed, i'm not sure about that haha)

**Comment by kopax-polyconseil** [comment]
OK, so far I also disabled the import for plurals and now we got this: 

![image](https://user-images.githubusercontent.com/77674046/113869970-9fbe8180-97b1-11eb-981c-8d2a5fff5a0c.png)

**Comment by semoal** [comment]
Actually loading the plurals is required, so the loadLocaleData is mandatory :/

**Comment by kopax-polyconseil** [comment]
Yes, I just succeded to load the plural editing my `metro.config.js` with : 

```diff
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

module.exports = {
+  resolver: {
+    sourceExts: ['js', 'ts', 'tsx', 'mjs'],
+  },
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
  maxWorkers: 2,
}
```

I still have the error from the screenshot.

**Comment by kopax-polyconseil** [comment]
I figured the cause, it seems that now undefined cannot be `trimed()`, so we cannot use undefined variable in template literrals, this cause most of the page of our application to crash. Is there a soft mode or something we can use ?

**Comment by semoal** [comment]
Let me hotfix this 👍🏻

**Comment by kopax-polyconseil** [comment]
![image](https://user-images.githubusercontent.com/77674046/113872748-718e7100-97b4-11eb-9d59-aa2a4e5dd790.png)


I added some logging to see what value is result...

**Comment by kopax-polyconseil** [comment]
This seems to work: `    return result && result.trim && result.trim();`

**Comment by semoal** [comment]
> This seems to work: `return result && result.trim && result.trim();`,
> 
> Why is `result` sometimes a function? Why would you want to call `trim` on a function?

Result shouldn't be a function because are the messages interpolated, I'm checking if i can reproduce the issue in our test suite

**Comment by kopax-polyconseil** [comment]
> - Also i saw that you use a lot unicode chars to give spaces to things, in Lingui v3 we strip this characters so just use html entities or basic templating

I still see a lot of unicode chars displayed, I have tried to remove them, using some HTML code. Can you tell me how for example I can replace `\u00a0` ?

**Comment by kopax-polyconseil** [comment]
I've tried both and none of them work. Why would you strip the charactères? Perhaps you can add an option to toggle the feature for such cases?

**Comment by semoal** [comment]
> I've tried both and none of them work. Why would you strip the characters ? Perhaps you can add an option to toggle the feature for such cases?

I can't remember now why Tomas took that direction, we had issues with some bundlers and we decided to keep it like just html entities. 
What's the case that doesn't work?

```
t`Some translate `  + something appended?
```

In this case is recommended to use it like this:
```
t`Some translate ${something appended}`
```

**Comment by kopax-polyconseil** [comment]
We use syntax literal so it's a template literal that caused to be a `function` instead of a `string`:

```
[Wed Apr 07 2021 15:24:41.213]  LOG      [Function _]
[Wed Apr 07 2021 15:24:41.542]  LOG      [Function Version0]
[Wed Apr 07 2021 15:24:41.863]  LOG      [Function DSLe0]
[Wed Apr 07 2021 15:24:41.905]  LOG      [Function Version0]
[Wed Apr 07 2021 15:24:42.578]  LOG      [Function TuAs0SurTonPass]
[Wed Apr 07 2021 15:24:42.580]  LOG      [Function Bonjour0]
[Wed Apr 07 2021 15:24:42.582]  LOG      [Function DSLe0]
[Wed Apr 07 2021 15:24:42.623]  LOG      [Function Version0]
[Wed Apr 07 2021 15:24:42.852]  LOG      [Function TuAs0SurTonPass]
[Wed Apr 07 2021 15:24:42.873]  LOG      [Function Bonjour0]
[Wed Apr 07 2021 15:24:42.875]  LOG      [Function DSLe0]
[Wed Apr 07 2021 15:24:43.480]  LOG      [Function _]
[Wed Apr 07 2021 15:24:43.187]  LOG      [Function TuAs0SurTonPass]
[Wed Apr 07 2021 15:24:43.189]  LOG      [Function Bonjour0]
```

I've updated the `interpolate` and it work with the updated snippet.

> I can't remember now why Tomas took that direction, we had issues with some bundlers and we decided to keep it like just html entities.

We use a lot of unicode charactères to add unbreakable spaces, etc... Can this feature be restored?

**Comment by semoal** [comment]
Let me review the unicode topic

**Comment by semoal** [comment]
Give me tonight to analyse how can we solve the unicode part and tomorrow we conclude this ;)

**Comment by kopax-polyconseil** [comment]
Alright, thanks again for helping us in the migration process ! Good luck,

**Comment by semoal** [comment]
We're going to unlock this @kopax :shipit: I've just opened a pull request fixing the unicode part 👍🏻

**Comment by kopax-polyconseil** [comment]
Allright, let me know when it's released so I can follow with another try.

**Comment by semoal** [comment]
https://github.com/lingui/js-lingui/releases/tag/v3.8.4
Released 3.8.4

**Comment by kopax-polyconseil** [comment]
```
[Thu Apr 08 2021 11:46:46.302]  ERROR    Error: Objects are not valid as a React child (found: object with keys {id}). If you meant to render a collection of children, use an array instead.
    in RCTText (at Text.js:159)
    in TouchableText (at Text.js:283)
    in Text (created by Context.Consumer)
    in StyledNativeComponent (created by Styled(Styled(Styled(Text))))
    in Styled(Styled(Styled(Text))) (at AppButton.tsx:62)
```

**Comment by semoal** [comment]
Strange right? in Appbutton there's any lingui translation :/

**Comment by kopax-polyconseil** [comment]
I've just clear all the cache and tried once more and now the app start but the issue with unicode chars remains:

![image](https://user-images.githubusercontent.com/77674046/114007258-7826f200-9861-11eb-9e54-27589fa1bb5a.png)

**Comment by semoal** [comment]
Did you extracted and compiled other time?

**Comment by kopax-polyconseil** [comment]
> Did you extracted and compiled other time?

I just did and the error remain.

**Comment by semoal** [comment]
> > Did you extracted and compiled other time?
> 
> I just did and the error remain.
Ah fuck, i'm stupid

I'm checking your unicode characters ann don't have two slashes :/

\u00a0

And i've introduced the check with \\u LMAO

**Comment by kopax-polyconseil** [comment]
I forgot to upgrade macro and cli, just a sec I try again

**Comment by semoal** [comment]
Give a moment and i release a hotfix for this!... fucking rush (but easy fix at least)

**Comment by kopax-polyconseil** [comment]
OK so we have a bunch of other issue, I will list them here

**Comment by semoal** [comment]
No, you're right, i checked the double because babel adds a new one, so the regex is correct.

**Comment by kopax-polyconseil** [comment]
###  Unicode chars present and titles are missing

![image](https://user-images.githubusercontent.com/77674046/114011254-52035100-9865-11eb-8b2d-466dd438ee6a.png)

![image](https://user-images.githubusercontent.com/77674046/114011371-6e06f280-9865-11eb-99f6-665382de1054.png)

**Comment by semoal** [comment]
The unicode chars to the descriptions it's strange. No exists `\u00a06` this unicode char. 

In the code we have this:
```js
      ? t`À retirer avant le ${formatToCompleteFrenchDate(expirationDatetime)}`
```
Check if there's none strange syntax in the space between `le` and ${}, or try to extract to:
```js
      ? t`À retirer avant le \u00a0` + formatToCompleteFrenchDate(expirationDatetime)
```

About the other one, if you give me where it's situated that string i could check hehe ^^

**Comment by kopax-polyconseil** [comment]
> The unicode chars to the descriptions it's strange. No exists \u00a06 this unicode char.

We use an unbreakable space between `Le` and the day: `Le\u00a06 mai 2021` should display `Le 06 mai 2021` 

> About the other one, if you give me where it's situated that string i could check hehe ^^

For example, thoses titles doesn't get displayed : 

- https://github.com/pass-culture/pass-culture-app-native/blob/semoal-refactor-to-lingui-v3/src/features/home/pages/Home.tsx#L100

**Comment by kopax-polyconseil** [comment]
>       ? t`À retirer avant le \u00a0` + formatToCompleteFrenchDate(expirationDatetime)

Fix the unicode issue in our page, we still try to understand why title in our application disappeared

**Comment by kopax-polyconseil** [comment]
v3 seems to be less stable, for example, to fix the title:

```jsx
<StyledTitle1 color={ColorsEnum.WHITE} numberOfLines={2}>
  {userInfos?.firstName ? t`Bonjour` + ` ${userInfos?.firstName}` : t`Bienvenue !`}
</StyledTitle1>
```

After:

```jsx
<StyledTitle1 color={ColorsEnum.WHITE} numberOfLines={2}>
 {userInfos?.firstName ? t`Bonjour ${userInfos?.firstName}` : t`Bienvenue !`}
</StyledTitle1>
```

**Comment by semoal** [comment]
> v3 seems to be less stable, for example, to fix the title:
> 
> ```js
> <StyledTitle1 color={ColorsEnum.WHITE} numberOfLines={2}>
>   {userInfos?.firstName ? t`Bonjour` + ` ${userInfos?.firstName}` : t`Bienvenue !`}
> </StyledTitle1>
> ```
> 
> After:
> 
> ```js
> <StyledTitle1 color={ColorsEnum.WHITE} numberOfLines={2}>
>  {userInfos?.firstName ? t`Bonjour ${userInfos?.firstName}` : t`Bienvenue !`}
> </StyledTitle1>
> ```
> 


These were all bad practices from v2, and not recommended because weren't working as macros, that's why now all the imports come from macros packages and not the react one.


> This also fail:
> 
> ```js
> interface SvgPageHeaderProps {
>   title: string
> }
> 
> export default function SvgPageHeader(props: SvgPageHeaderProps) {
>   return (
>     <HeaderBackgroundWrapper>
>       <HeaderBackground width={ScreenWidth} />
>       <Title>{t`${props.title}`}</Title>
>     </HeaderBackgroundWrapper>
>   )
> }
> ```
> 
> But this works:
> 
> ```js
> export default function SvgPageHeader({ title }: SvgPageHeaderProps) {
>   return (
>     <HeaderBackgroundWrapper>
>       <HeaderBackground width={ScreenWidth} />
>       <Title>{t`${title}`}</Title>
>     </HeaderBackgroundWrapper>
>   )
> }
> ```

These has sense since how this code it's executed and interpreted by typescript. This in v2 was working because was not doing the macro correctly giving us a lot headhache to debug why something was translated or not (also the performance). 

When you have dynamic strings like that you have to use defineMessage() or use the t`` macro passed via props, and not the t`` with a dynamic string. (how does lingui know what it's ${title}?), Lingui can't now without being in the runtime if this will be X or Y, that's why the correct behaviour is:

```tsx
<SvgPageHeader title={t`Page temporaire`} />
```

and 
```tsx
export default function SvgPageHeader(props: SvgPageHeaderProps) {
  return (
    <HeaderBackgroundWrapper>
      <HeaderBackground width={ScreenWidth} />
      <Title>{props.title}</Title>
    </HeaderBackgroundWrapper>
  )
}
```

**Comment by semoal** [comment]
Probably the v3 version was a bit crazy in terms of strictness, but in this way we keep the code maintainable in our side and your side. 

I'll work this months in a eslint plugin to enforce the correct usage, also i've developed a [codemod](https://github.com/lingui/codemods) for automatic migration from v2 codebases to v3 :)

**Comment by kopax-polyconseil** [comment]
That's perfect enough for our requirements, thanks for giving us a bit of your road map, we'll update and may have some feedback in the next weeks if things goes wrong. Thanks à lot for fixing this for us. I hope your mate won't blame your for restoring the unicode feature :)

**Comment by semoal** [comment]
The unicode feature it's a great addition, i found why that code was here https://github.com/lingui/js-lingui/issues/897 and now has more sense the fixes we did for you guys =)

There are tons of new features to the v3 branch, while the v2 isn't maintained anymore:

- Automatic fallback locales with CLDR parent definitions
- Watch mode for compiling & extracting catalogs
- Shipped ESM (compatible with Vite & Snowpack)
- Compile catalog files to Typescript
- Accepts lingui.config.ts
- allow to disable lineNumbers and origins in .po files
- Extract messages from specific files (this is cool if you want to setup a husky hook to run extract to only changed files, for faster CI environments or something like that ;) )
- Pseudolocalization 🥳 

And much more will come ;)

**Comment by kopax-polyconseil** [comment]
@semoal , we got two test failing despite the usage of the custom render: 

![image](https://user-images.githubusercontent.com/77674046/114019192-63049000-986e-11eb-915e-57b195633c02.png)


Do you have a clue ?

**Comment by semoal** [comment]
Ugh that's the first time I see that. I'm out of home right now(lunch) give me 1 hour more or less and I take a look

**Comment by kopax-polyconseil** [comment]
No worries, it's not an emergency, it seems that plural format the number according to the local, while this is not what we use to have. I decided to keep the new behavior but I am interested also in disabling it.

**Comment by kopax-polyconseil** [comment]
It's all merged. I'll close it for now and re-open it if needed. Thanks again for helping us migrating the library, that's really cool.

**Comment by kopax-polyconseil** [comment]
We have another issue here: 

https://github.com/pass-culture/pass-culture-app-native/blob/4bc0d48d0d51cba8332e706eb1ffdd1a195ab602/src/features/firstTutorial/pages/FirstTutorial/components/SecondCard.tsx#L27

Despite `amount` value being `500€` here, it gives me the following logs when I check the value:

```
[Thu Apr 08 2021 14:50:17.425]  LOG      300€
[Thu Apr 08 2021 14:50:17.469]  ERROR    Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
    in RCTText (at Text.js:159)
    in TouchableText (at Text.js:283)
    in Text (created by Context.Consumer)
    in StyledNativeComponent (created by Styled(Styled(Styled(Text))))
    in Styled(Styled(Styled(Text))) (at GenericAchievementCard.tsx:102)
    in RCTView (at View.js:34)
    in View (created by Context.Consumer)
    in StyledNativeComponent (created by Styled(View))
    in Styled(View) (at GenericAchievementCard.tsx:88)
    in GenericAchievementCard (at SecondCard.tsx:26)
    in SecondCard (at FirstTutorial.tsx:19)
    in RCTView (at View.js:34)
    in View (created by Swiper)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (created by Swiper)
    in RCTView (at View.js:34)
    in View (created by Swiper)
    in RCTView (at View.js:34)
    in View (created by Swiper)
    in Swiper (at GenericAchievement.tsx:61)
    in RCTView (at View.js:34)
    in View (created by Context.Consumer)
    in StyledNativeComponent (created by Styled(View))
    in Styled(View) (at GenericAchievement.tsx:60)
    in RCTView (at View.js:34)
    in View (created by Context.Consumer)
    in StyledNativeComponent (created by Styled(View))
    in Styled(View) (at GenericAchievement.tsx:52)
    in RCTView (at View.js:34)
    in View (created by Context.Consumer)
    in StyledNativeComponent (created by Styled(View))
    in Styled(View) (at GenericAchievement.tsx:50)
    in GenericAchievement (at FirstTutorial.tsx:17)
    in FirstTutorial (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:221)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:220)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:563)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:545)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:539)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:535)
    in RCTView (at View.js:34)
    in View (at Card.tsx:529)
    in Card (at CardContainer.tsx:189)
    in CardContainer (at CardStack.tsx:558)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:69)
    in MaybeScreen (at CardStack.tsx:551)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:48)
    in MaybeScreenContainer (at CardStack.tsx:461)
    in CardStack (at StackView.tsx:458)
    in KeyboardManager (at StackView.tsx:456)
    in SafeAreaProviderCompat (at StackView.tsx:453)
    in GestureHandlerRootView (at GestureHandlerRootView.android.js:31)
    in GestureHandlerRootView (at StackView.tsx:452)
    in StackView (at createStackNavigator.tsx:84)
    in StackNavigator (at RootNavigator.tsx:35)
    in RootNavigator (at App.tsx:71)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:407)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at NavigationContainer.tsx:23)
    in AppNavigationContainer (at App.tsx:70)
    in SplashScreenProvider (at App.tsx:69)
    in SnackBarProvider (at App.tsx:68)
    in I18nProvider (at App.tsx:67)
    in SearchWrapper (at App.tsx:66)
    in FavoritesWrapper (at App.tsx:65)
    in AuthWrapper (at App.tsx:64)
    in GeolocationWrapper (at App.tsx:63)
    in ErrorBoundary (at App.tsx:62)
    in QueryClientProvider (at App.tsx:61)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:74)
    in SafeAreaProvider (at App.tsx:60)
    in ABTestingProvider (at App.tsx:59)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
[Thu Apr 08 2021 14:50:18.175]  LOG      300€
[Thu Apr 08 2021 14:50:18.471]  LOG      500€
```

The text is not displayed:

![image](https://user-images.githubusercontent.com/77674046/114029569-f0011680-9879-11eb-849d-00c0d36a56cc.png)


The following code:

```jsx
      text={
        t`dans l’année de tes 18 ans, obtiens l’aide financière pass Culture d’un montant de\u00a0` +
        deposit +
        `\u00a0à dépenser dans l’application.`
      }
```

cause the following: 

![image](https://user-images.githubusercontent.com/77674046/114030062-74ec3000-987a-11eb-99cb-404efb849ceb.png)



It seems that the macro is having issue when using string interpolation

**Comment by kopax-polyconseil** [comment]
This fix the error :  `text={t`dans l’année de tes 18 ans, obtiens l’aide financière pass Culture d’un montant de ${deposit.toString()} à dépenser dans l’application.`}`, I am now concerned of the risk to have a bunch of error like this unspotted. `deposit` is of type `string` so that shouldn't be an issue.

**Comment by semoal** [comment]
I've tried to replicate the issue on the example/create-react-app application which uses create-reac-app under the hood and couldn't reproduce it.
I'm going to TRY to launch your application (if it's possible and will be more efficient) :/ Looks something related to react-native because in web (even with strictmode) doesn't log any error

**Comment by kopax-polyconseil** [comment]
> I'm going to re-TRY to launch your application (if it's possible and will be more efficient) 

I don't think you can, as explained in our `README`, if you want to run iOS, you will need our `ios/GoogleService-Info.plist` , and for android, there's also `google-services.json` and `android/keystores/development.keystore.properties`. I am not allowed to share those.

How about bootstrapping a fresh react native application for such test?

>  Looks something related to react-native because in web (even with strictmode) doesn't log any error

Considering the role of lingui, I have doubt about it, the JS engine should be working the same as in the browser.

**Comment by semoal** [comment]
Yes, i'm going to bootstrap a react native application.

Give it a try if you can to reproduce it in a  create-react-app example, update lingui to latest (make sure installed is 3.8.4) and tell me if you can reproduce it

**Comment by kopax-polyconseil** [comment]
Yes, that's unfortunate, I am already on it.

**Comment by semoal** [comment]
![Screenshot 2021-04-08 at 17 06 51](https://user-images.githubusercontent.com/22656541/114050764-d6b59580-988c-11eb-9bbc-891830038e50.png)
Can't reproduce it on a practically copy of setup of your application (metro-typescript-react-styled-components)

**Comment by kopax-polyconseil** [comment]
Thanks, I was still working on my boilerplate, so I am giving up. I will try to see if there's a way to start the application without those keys to see if we can investigate further.

**Comment by semoal** [comment]
> Thanks, I was still working on my boilerplate, so I am giving up. I will try to see if there's a way to start the application without those keys to see if we can investigate further.

We could talk on a meeting if getting these keys are so risky for an external developer, I'm open to anything, just want to help :)

**Comment by kopax-polyconseil** [comment]
Perhaps a peer programming session over meet can help solve this?

**Comment by semoal** [comment]
I'm sure that worst can't go =) today i'm busy at work, so if you want to try to reproduce and  if not we speak tomorrow?

**Comment by kopax-polyconseil** [comment]
If you can't reproduce it I have doubt on how to reproduce it myself with a fresh native project. 

I've checked with our team and starting the app without those secrets is not possible. 

I am almost sure I can help you investigate if you want to dig to the root cause through a peer programming session, let me know if you want to schedule that tomorrow. 

So far, I warned the dev team that v3 now bring issue with unicode chars and string literals.  so far have found alternatives for every dubious case we got, the worst alternative was to call a `.toString()` on a string.

**Comment by semoal** [comment]
Yes, let's schedule tomorrow. I have already picked 9:30 and 14:00, i'm free all the afternon

**Comment by kopax-polyconseil** [comment]
OK, I've just scheduled on meet a 1h slot between 2pm and 3pm, you have the right to update the time, I am also free for the call the whole afternoon, looking forward with thanks !

**Comment by kopax-polyconseil** [comment]
We got another issue which is blocking for us. After releasing our application in app center with a real android build, it seems that the unicode chars are not replaced in every place, for exemple:

![image](https://user-images.githubusercontent.com/77674046/114061162-67dd3a00-9896-11eb-9c10-3b91079739ee.png)


2nd thing is that the bug with the text on `<SecondCard />` is not fixed (see https://github.com/pass-culture/pass-culture-app-native/pull/849) and we do not have the issue anymore. 

1. Development environment can have issue with translation string interpolation
2. Production environment still have the issue with unicode not beeing replaced

I think we may have to revert to v2 especially because of 2, we'll see tomorrow.

**Comment by kopax-polyconseil** [comment]
Hi @semoal , I've just tested a production build with lingui 3.8.6 and I still have unicode issue in production, now `messages.po` looks like this:

```
msgid "Tu as déjà un compte ?/u00a0"
msgstr "Tu as déjà un compte ?/u00a0"
```

And view is still showing invalid chars:

![image](https://user-images.githubusercontent.com/77674046/114146252-a49d4580-9917-11eb-892f-a35d18615821.png)

**Comment by semoal** [comment]
Quick update: 

One thing we can't fix without breaking others users, it's not stripping spaces at the end of strings.

# Not inmediately fix
For example this case:
```tsx
<Text>{t`EAN\u00a0`}</Text>
```
Should be like this if you want that space, or ``" "``:
```tsx
<Text>{t`EAN`}{\u00a0}</Text>
```

> A suggestion is to add a configuration property to lingui like trimTranslations: true/false, but i've need some time this weekend to develop this technique. 

# Inmediately fix

- The error about maximum exceeded was a refactor i've did to try something new related to event emitter but didn't worked well (as you could check). Already released 3.8.9 https://github.com/lingui/js-lingui/releases/tag/v3.8.9

# Pending for your side confirmation
- When you can tell me if we fixed the unicode chars in Production.

# Pending for my side
- I'm going to check asap if I can resolve the warning about can't use functions as child

**Comment by kopax-polyconseil** [comment]
![image](https://user-images.githubusercontent.com/77674046/114181117-60269f80-9941-11eb-9673-282a5472ddc3.png)

APO saw this in the production testing build, I am not sure with which version but it was this morning, so probably the one from yesterday.

I am now testing the latest.

**Comment by kopax-polyconseil** [comment]
https://github.com/pass-culture/pass-culture-app-native/pull/864/files

This is how we solve the unicode issue, but now our `messages.po` does not interpolate the value, it just concatenate part of sentences from message file, ex:

https://github.com/pass-culture/pass-culture-app-native/pull/864/files#diff-cb154b350261abe067422a25938a2b4ff16788f9319324330616d7c75583d6a7L1218-R1219

That's not blocking, however, we still have the issue in development with our string/function.

> trimTranslations: true/false

I am much interested in that feature, can you also please confirm that unicode does not work only if they are around the sentence ? Because we have:

    t`Confirme ton e\u2011mail`

And this seems to render correctly both in development and production

**Comment by kopax-polyconseil** [comment]
Hello @semoal , I'd like to know if action will be taken regarding the issue we have with string, we still find a lot of view displayed like follow after migration to v3:

![image](https://user-images.githubusercontent.com/77674046/114541519-1c8ca800-9c57-11eb-801e-15dd9a03880f.png)


Also, our test execution time has increased from 4 to 8 min because of : 

    Jest did not exit one second after the test run has completed.

    This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.

This started after merging the v3 migration: https://github.com/pass-culture/pass-culture-app-native/pull/845

Do you have a clue why the test are improperly configured with lingui v3 ?

**Comment by kopax-polyconseil** [comment]
I've created two separate issues and suggest that we close that one so newcomers can get the proper feed and have this one linked.
