### ISSUE TITLE
Whitespace doesn't get ignored in multiline strings

### ISSUE THREAD

**Issue by Peping** [lingui/js-lingui#103]
When I run `lingui extract` on a component like this, the string in my messages catalog is without whitespace. When I run with translated messages, the default value is shown instead of the translated one.

**Component.js**
```jsx
({name, item}) => (
    <Trans>
        User <strong>{name}</strong> is already has <strong>{item}</strong>. <br />
        Please, remove it first.
    <Trans>
)
```

**messages.json** and **cs.json**
```json
{
    "User <0>{name}</0> already has <1>{item}</1>. <2/>Please, remove it first.": "Uživatel <0>{name}</0> již má <1>{item}</1>. <2/>Nejprve ji odstraňte."
}
```

All one-line strings are translated correctly, but as soon as you include line breaks, the translation is broken.

**Comment by tricoder42** [comment]
Thanks, I'll take a look!

**Comment by tricoder42** [comment]
Hi @Peping,
I tried your example in [`example/webpack-react`](https://github.com/lingui/js-lingui/tree/master/examples/webpack-react) and the problem was in your message id.

In your example:

```js
({name, item}) => (
    <Trans>
        User <strong>{name}</strong> is already has <strong>{item}</strong>. <br />
        Please, remove it first.
    <Trans>
)

// Message is extracted as:
// User <0>{name}</0> is already has <1>{item}</1>. <2/>Please, remove it first.

// but you have:
// User <0>{name}</0> already has <1>{item}</1>. <2/>Please, remove it first.
```

There's an `is` missing in your message ID.

Feel free to reopen if it doesn't solve your problem with more info, but in `example/webpack-react` this fixes the problem.

**Comment by tricoder42** [comment]
Also please note that only insignificant whitespace is removed and it works exactly how React would process your whitespace.
