### ISSUE TITLE
Migrate `messageformat-parser` to new AST `@messageformat/parser`

### ISSUE THREAD

**Issue by semoal** [lingui/js-lingui#1034]
**Is your feature request related to a problem? Please describe.**
Since this issue  https://github.com/lingui/js-lingui/issues/1033 we saw that `messageformat-parser` won't work with ASCII characters, and probably is not maintained anymore.

**Describe proposed solution**
Migrate our process to match the new AST structure.

**Describe alternatives you've considered**
Any, but open to listen/read ;)

> I think this won't be a breaking change since it's something internal of our tooling not exposed to consumers (i hope so)

**Comment by thekip** [comment]
Closed by https://github.com/lingui/js-lingui/pull/1328
