### ISSUE TITLE
How to deal with static catalogs

### ISSUE THREAD

**Issue by NSLS** [lingui/js-lingui#104]
Hi! This is a great library and the best I could find for react so far. However, after integrating it into my project, I've faced a problem of translating strings which do not belong to components. A common example is messages from your API, e.g. error messages or validation errors.

Usually you either make a separate file describing these messages and then it is parsed along with the extraction process and then you translate these messages like everything else, or you simply make a catalog file with translations for these strings and then merge it with the main catalog.

Could you give me an example of a proper way to do this with lingui?

Thanks.

**Comment by tricoder42** [comment]
Hi @NSLS,
I see two ways how to achieve what you want. One is already supported and the other would have to be coded.

# 1. Translation of messages outside components

You can wrap messages with `i18n_mark` and then translate them from a variable:

```js
// validation.js
import { i18n_wrap } from 'lingui-react'

// i18n_wrap is an identity function, but it's searched for during extraction of messages
export const error_messages = {
   required: i18n_wrap('This field is required'),
   unique_email: i18n_wrap('Account with this email already exists')
}

// Component.js
import { Trans } from 'lingui-react'
import { error_messages } from './validation'

// Pass message from variable to `id` prop to translate it
const Field = ({ error, value }) => (
   <div>
      <input value={value} />
      {error && <Trans id={error_messages[error]} />}
   </div>
) 
```

You could generate such file automatically from your backend. Depends on your stack.

# 2. Merge catalogs

This isn't supported yet, but it's definitely useful feature to have. I think we could have option in `package.json` like:

```js
{
   "lingui": {
      "externalCatalogs": [
        "./server/locale",
        "./path/to/3rd/party/lib"
      ]
   }
}
```

`lingui extract` would merge `externalCatalogs` with extracted messages in `localeDir`. After translation, `lingui compile` would compile them as usual.

What do you think? Is 1) acceptable workaround before 2) is implemented? If you had a spare time to work on 2), I'm happy to help!

**Comment by NSLS** [comment]
Thanks for the quick reply!

I think that first solution is totally acceptable, I have used the same method in my other projects before.

The second solution would also be useful, but IMO in a different context, e.g. when a project grows larger and codebase has to be split across multiple repositories.

I will try to look inside the lingui's code and see if I can implement the merging method.

But for now the issue is solved, thanks!
