### ISSUE TITLE
React native development cause t`text ${interpolated} example`  to return function instead of string

### ISSUE THREAD

**Issue by kopax-polyconseil** [lingui/js-lingui#1042]
Following #1022, I have created two separate bug identified in v3.

**Describe the bug**

In a React Native application, we use metro and target iOS, Android and web.

> I am not sure this is specific to react native development environement but that would sound odd.

Within our development environment (this bug is not happening within our production build), we often have issue with template literral not interpolating string and returning function, this cause warning everywhere in our application and missing text.

![image](https://user-images.githubusercontent.com/77674046/114549258-16032e00-9c61-11eb-922f-9b20077adb0a.png)

**On Android Galaxy S9**

![image](https://user-images.githubusercontent.com/77674046/114549121-e81de980-9c60-11eb-9e5b-f262f121fecb.png)

**On iPhone 6, it cause application crash**

![image](https://user-images.githubusercontent.com/77674046/114718008-ea05ac80-9d35-11eb-81f1-056ff2179509.png)

**To Reproduce**

This is how we integrated the issue: https://github.com/pass-culture/pass-culture-app-native/pull/842

It's hard to tell since @semoal tried to bootstrap a clean react-native application to reproduce, while we migrated from v2 to v3 on an existing application

**Expected behavior**

We expect lingui to always translate the text as a string in the development and production build.

> It's not ideal, but it can be fixed while developing by calling `.toString()` on template variables 

**Additional context**

- jsLingui version `3.8.9`
- Babel version `7.8.4`
- Your Babel config : https://github.com/pass-culture/pass-culture-app-native/blob/master/babel.config.js
- Framework you use (Create React App, Meteor, etc.): https://github.com/pass-culture/pass-culture-app-native/blob/master/metro.config.js

**Comment by kopax-polyconseil** [comment]
Hi @semoal , I hope you add a good weekend. Did you had any tought on that one?  The v3 migration added some complexity to our devs, as in this commit https://github.com/pass-culture/pass-culture-app-native/pull/917/commits/dba46af21fb65e411075299cddd2fea55aa9bcf2  . I would love to know if you have a plan to work on it soon, as we may decide to revert to v2 to prevent mistakes. I myself, have no clue where and how to fix it.

**Comment by semoal** [comment]
Actually I'm really busy with my current job and other noise I have around me, once I find time I'll work on this issue and I'll create a pr on your repository doing it simple another time.

Sorry for the inconveniences but OSS doesn't give me enough to focus on every issue all my entire time

**Comment by kopax-polyconseil** [comment]
Hi @semoal , I hope you are good. Sorry I forgot to reply but I read you. I am glad that you are fixing this issue because it's kind of annoying having to explain those bugs to others. We are currently deploying the app to production, I presume we can take care of testing the next version  starting next week if you have solved it by then. 

Otherwise, let me know how we can help,

**Comment by semoal** [comment]
Released 3.9.0 give it a try when you can, but i'm pretty sure that will fixed :)

**Comment by kopax-polyconseil** [comment]
Hi @semoal , I was going to write to you a message. Thanks for meanwhile taking care of fixing the issue.

We were supposed to go prod today, unfortunately this is what we got in production (with the old version):  

![image](https://user-images.githubusercontent.com/77674046/118712163-be884d00-b820-11eb-87bc-12f3e582ef0a.png)


We're done for today, but we'll definitely try to upgrade to 3.9.0 and see if it fixes, otherwise we may have a long day reverting :), I'll keep you tuned.

**Comment by kopax-polyconseil** [comment]
Hi Semoal, I just tested 3.9.0, we still have the sames string not being displayed with the function error in development. Seems not fixed.
