### ISSUE TITLE
Extract sometimes ignores key when using backtics for id parameter.

### ISSUE THREAD

**Issue by macko911** [lingui/js-lingui#1044]
**Describe the bug**
When running `lingui extract --clean`, the result is different in 2 seemingly identical environments. Unfortunately I didn't find out what difference there is between the two computers that could lead me to the cause of the issue. Maybe you will know what is wrong with the extraction or with our usage of the `t` macro.

The problem is with using backtics `` instead of quotes '' for id field.

Obviously this can be simply fixed by replacing `` with '', but I thought it wouldn't hurt to bring up the issue.

**To Reproduce**

```typescript
import { t } from "@lingui/macro"

// this is not extracted on some environment
t({
  id: `some id`,
});

// always gets extracted
t({
  id: 'some id',
});

```

**Additional context**

lingui version `3.8.4`
babel/core `7.13.14`
.babelrc
```
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    [
      "styled-components",
      {
          "ssr": true,
          "displayName": true,
          "preprocess": false
      }
    ],
    "macros"
  ]
}
```

**Comment by semoal** [comment]
This feature is on this line: https://github.com/sultan99/js-lingui/blob/c8d32066c7ef340b5f221573db2ce665d9ab8e06/packages/babel-plugin-extract-messages/src/index.ts#L240

If you can add a `console.log(value)` to see if it's different between your environments, would be easier to debug.

If we can't see any difference we can meet up in a fast call and we debug it together :)
