### ISSUE TITLE
Duplicate extracted plurals

### ISSUE THREAD

**Issue by stovmascript** [lingui/js-lingui#1049]
**Describe the bug**
Identical `plural` macros with different value variable names result in duplicate extracted messages.

**To Reproduce**
```bash
$ git clone -b repro-plural-duplicates https://github.com/monitora-media/js-lingui.git
$ cd js-lingui/examples/js/
$ yarn
$ yarn lingui extract
$ git diff
```

Observe 3 missing translations instead of 1.

**Expected behavior**
All messages to be deduplicated regardless of the value variable name.

**Additional context**

- jsLingui version `3.8.10`
- Babel version `7.13.16`
- Your Babel config (e.g. `.babelrc`) - same as examples/js

**Comment by semoal** [comment]
Not sure if it's an issue itself. I don't know if how macros works is possible to "fix" this, since these variables are the same because you know are the same, but could not be the same on runtime.

I'll try to find time to focus a bit on Lingui

**Comment by stovmascript** [comment]
Not sure if it was obvious enough, but as you can see:

https://github.com/monitora-media/js-lingui/blob/8915b7e3bb2e163b9f5e61e83f60f207d2f1fdef/examples/js/src/messages.js#L98-L99

There is a workaround by passing the variable to `parseInt` or some other pass-through function, which makes Lingui merge the plurals correctly.
