### ISSUE TITLE
TypeError undefined is not a function

### ISSUE THREAD

**Issue by root-io** [lingui/js-lingui#1053]
**Describe the bug**
```
TypeError undefined is not a function 
    App.tsx:27:5 Object.push.344
    ../webpack/bootstrap:84:21 __webpack_require__
    ../webpack/bootstrap:45:14 checkDeferredModules
    ../webpack/bootstrap:32:10 Array.r [as push]
 ```

```
i18n.loadLocaleData('en', { plurals: en }); //  line 27
i18n.loadLocaleData('fr', { plurals: fr });
i18n.load('en', catalogEn);
i18n.load('fr', catalogFr);
```

See https://github.com/libreotp/webapp/blob/master/src/App.tsx

**To Reproduce**
Upgraded from 3.7.1 to 3.8.10

**Additional context**

- Babel version `@babel/core@7.12.3`
- Babel version and config from CRA 4.0.3
- Chrome 84.0.4147 (Android)

**Comment by semoal** [comment]
Yay, i'll take a look in a few hours

**Comment by root-io** [comment]
No, maybe due to some service worker/cache issue, let's close this, thanks :)
