### ISSUE TITLE
How to wrap component and function, and extract messages to separate chunks

### ISSUE THREAD

**Issue by SanichKotikov** [lingui/js-lingui#1064]
**Is your feature request related to a problem? Please describe.**
I have a large project with feature-folders, and wanna extract messages separately by these features, and load only needed messages chunk in runtime. For example I have the next project structure:

```
/app
 /some-feature
 /other-feature
```

From that structure I wanna get next files:

```
some-feature/en.json
other-feature/en.json
```

So, when a user routes to `/some-feature`, the app should load related messages only: `some-feature/%selected_lang%.js` chunk.

Also, I wanna use some namespaces, to provide components know what chunk need to load. Something like that:

```
const { i18n } = useI18n('some-feature');
```

**Describe proposed solution**
I've tried to make a demo and wrap libs' components and functions with my owns, but realased that extract function doesn't work if it doesn't see `@lingui` import in the same file where we define default messages.

Right now I thinking about adding some settings for extractor to provide not only component or function names, but import path(s) also. Any suggestions or restrictions on this?

But I still have no idea how to split messages by feature-folders, except to create some node script that will split single json to several files by first part of id (for example `some-feature.some-component.some-string-name` will be stored in `some-feature.json`). Any idea?

Thanks for any ideas.

**Comment by semoal** [comment]
Hello, this is a great question and somehow related to #503.
Right now, we don't have a plugin which extracts to chunks the messages, once I get some free time I want to work on that direction, I already have some ideas and improvements to that field.

Meanwhile, probably https://lingui.js.org/ref/conf.html#separate-catalogs-per-component-placed-inside-component-dir this should work for you.

You define in your catalogs where should be extracted the messages and where they should look, then you can just use a function:
```ts
export async function dynamicActivate(locale: string, catalogPath: string) {
  const { messages } = await import(`@lingui/loader!./${catalogPath}/${locale}/messages.po`)
  i18n.load(locale, messages)
  i18n.activate(locale)
}
```

Give it a try :)

**Comment by SanichKotikov** [comment]
@semoal thanks. Extracting works as needed for now with next config:

```
"catalogs": [
    {
      "path": "src/locales/messages/{name}/{locale}",
      "include": "src/{name}/",
      "exclude": [
        "src/components",
        "src/locales",
        "src/App.tsx",
        "src/index.css",
        "src/index.tsx",
        "src/react-app-env.d.ts"
      ]
    }
  ],
```

It only works when I use `import '@lingui/..'`, but I need use my own wrapper with custom path, for example:

```
import {useI18n} from '../../../locales/useI18n';

const { i18n } = useI18n('some-feature');
return <div>{i18n._({id: 'some_feature.simple', message: 'Simple'})}</div>
```

I've been playing around `runtimeConfigModule` but no luck. How does it work?
