### ISSUE TITLE
Lingui extract fails with orderBy 'origin'

### ISSUE THREAD

**Issue by timonbimon** [lingui/js-lingui#1067]
**Describe the bug**
lingui extract fails when orderBy is set to `origin`. Works if the default setting is used.

![image](https://user-images.githubusercontent.com/14793026/118704859-d8716200-b817-11eb-8c00-9d6975002207.png)

Any ideas what might be going on?

- jsLingui version 3.8.10
- Your Babel config: Create-React-App 4.0.0

**Comment by semoal** [comment]
Probably it's a bug and should be fixed 

packages/cli/src/api/catalog.ts
Line 650, you can try to debug your node modules code with some console.logs, and submit a pull request with the fix.

**Comment by timonbimon** [comment]
OK actually found the issue
I had a line like this at the bottom

```
#~ msgid "🚀 {0}- {1} von {numberOfRows}"
#~ msgstr
```

without a 
```#: src/...```
above it => since this is what orderBy sorts on it crashed
