### ISSUE TITLE
Built PO file contains each of the several references on a dedicated line

### ISSUE THREAD

**Issue by datafoo** [lingui/js-lingui#1072]
**Describe the bug**
Extracting messages that occurs in several places in the code results in an entry containing all references on a dedicated line:
```po
#: js/chart/HistoryChart.tsx:74
#: js/chart/LiveChart.tsx:77
msgid "Loading chart…"
msgstr ""
```

**Expected behavior**
Extracting messages that occurs in several places in the code should result in an entry containing all reference in a single line:
```po
#: js/chart/HistoryChart.tsx:74 js/chart/LiveChart.tsx:77
msgid "Loading chart…"
msgstr ""
```

**Additional context**

- jsLingui version ``lingui --version``: 3.9.0
- Babel version ``npm list @babel/core``: 7.14.3

All references in a single line seems to be the canonical way on generating PO files (http://pology.nedohodnik.net/doc/user/en_US/ch-poformat.html). But in my case, when I edit a PO file generated by lingui with Poedit, then Poedit rewrites all references on a single line and that complicates merging the translations with git.

**Comment by nakkamarra** [comment]
Hmm interesting, the `gettext` documentation seems to confirm this: https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html ,
but I'm not sure that I totally agree, I think for some common strings like `Submit` that are referenced in tens of files, this could result in some ridiculously long comments. Following the conventions of the original implementation is probably best though, and would condense some lengthy PO files. 🤷

**Comment by datafoo** [comment]
Above all, it would prevent back and forth fighting with different formats used by all tools involved (lingui, poedit, …) and would save a lot of time.

**Comment by semoal** [comment]
I'm happy to accept this if this is converted in an extra option to formatOptions https://lingui.js.org/ref/conf.html#formatoptions

For example, could be called `inlineReferences`, boolean. By default should be the current behaviour and if someone wants the references in one line, can enable it. 

Should pretty easy to implement it :)

**Comment by datafoo** [comment]
It seems the serialization is done with [pofile](https://github.com/rubenv/pofile) and here is a related issue: https://github.com/rubenv/pofile/issues/13.

**Comment by datafoo** [comment]
A maintainer of the PO file format recommended me (by email) to normalize the PO files before committing them in order to avoid merging problems.

> I recommend to normalize the PO files before commit. Normalizing means eliminating the possible variations. A reasonable normalization command is to pipe the PO file through
   `msgcat --width=80`

He also mentioned:
> When creating a PO file or POT file, a tool can emit one reference per line, or several references per line.

> When reading a PO file, a tool should treat both ways as equivalent.
One way to do so is to use the GNU libgettextpo library and in particular its file positions API
<https://www.gnu.org/software/gettext/manual/html_node/po_005ffilepos_005ft-API.html>.

The problem of normalization is not limited to this issue and therefore I will close it because it is best addressed by using a dedicated normalization tool.
