### ISSUE TITLE
Mark translation fuzzy when source string has changed

### ISSUE THREAD

**Issue by braineo** [lingui/js-lingui#1077]
**Is your feature request related to a problem? Please describe.**
I've been working with GNU gettext and Qt linguist, one thing I miss a lot from those 2 tool chains is 

 detecting source string has changed and mark translated language fuzzy when I'm using fix message ID

so that translator take a quick look, whether 
1. it is just a typo fix in source text and no need to touch translation, or 
2. translation need update due to semantic change

**Describe proposed solution**
1. compare source string during extraction for sourceLocale and remember changed text id
2. Mark translation changed accordingly

**Additional context**
Since I read the [comparison in document](https://lingui.js.org/ref/catalog-formats.html#json) between JSON and PO, and it mentioned

 > The drawback of this format is that all metadata about message are lost. That includes default message, origin of message and any message flags (obsolete, fuzzy, etc).

and I presumed fuzzy was extracted by cli.

Maybe I'm using the cli wrong. Would be great to have an official guide for this feature if exists.

**Comment by semoal** [comment]
I don't remember to see fuzzy messages on Lingui codebase. If you want to create a pull request, contributions are welcome =)
