### ISSUE TITLE
React app crashed when chrome auto translations is on

### ISSUE THREAD

**Issue by snih** [lingui/js-lingui#1079]
**Describe the bug**
Probably I figured out reason of #317 . 

First case. If I open my app with turned on chrome autotranslations, my app will crash with an error
```
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node
```

There are also second case, when translations not changed as expected. Second case relates to [this article](https://guoyunhe.me/en/2019/06/02/fix-react-issues-with-google-translate)

I can't figure out, why sometimes app is crashed and sometimes text is just not translated

**To Reproduce**
1. Open react app with lingui.
2. Right click on page, translate to English (or other)
3. Navigate between pages
4. App will crash

Code example for first case. selectedPair received asynchronous. During app open page is not crashed, but after navigations between pages it will fail. Maybe here is some kind of raice condition. But with turned off auto translations error is not append.
```
import { Trans } from "@lingui/react"

export const SomePage = () =>  {
  return (
    <div>
      {(!selectedPair) ? (
        <Trans id="product_selector.label.loading">Loading</Trans>
      ) : `${selectedPair.asset}(${selectedPair.metal})`}
    </div>
  );
}
```

**Additional context**
Secons case is simply fixed, when I wrap Trans tag in to span tag.

But to fix first case I need to wrap translation in to span tag
```
import { Trans } from "@lingui/react"

export const SomePage = () =>  {
  return (
    <div>
      {(!selectedPair) ? (
        <Trans id="product_selector.label.loading"><span>Loading</span></Trans>
      ) : `${selectedPair.asset}(${selectedPair.metal})`}
    </div>
  );
}
```

- jsLingui version ``3.9.0``
- Babel version ``7.14.3``
- Create React App based project

**Comment by semoal** [comment]
Could you create a reproduction repo please? 
Also, it's recommended to use Trans from the @lingui/macro package instead of the react one.

**Comment by renchap** [comment]
I think this might not be lingui-specific but a more general problem with Google Translate & React, see https://bugs.chromium.org/p/chromium/issues/detail?id=872770

Google Translate adds `<font>` elements to the page, which breaks React reconciliation as the React-managed DOM has been modified out of React.

**Comment by jalil1992** [comment]
There is a useful article [here](https://guoyunhe.me/en/2019/06/02/fix-react-issues-with-google-translate/) if anyone finds this problem annoying.

**Comment by alamenai** [comment]
Thank you @jalil1992 , you saved my life.
