### ISSUE TITLE
Load plural values dynamically

### ISSUE THREAD

**Issue by TriStarGod** [lingui/js-lingui#1095]
**Is your feature request related to a problem? Please describe.**
As per https://lingui.js.org/guides/dynamic-loading-catalogs.html#final-i18n-loader-helper , messages can be loaded dynamically using the example function. However, the same thing is not true for plural.

**Describe proposed solution**
Is a way to make plural dynamically load? If not, can such a possibility be implemented?

**Describe alternatives you've considered**
I initially had used `import * as plurals from "make-plural/plurals"` and `loadLocaleDate` for each supported language but that imports the entire library.

**Comment by semoal** [comment]
make-plural package it's side-effect free and tree-shakeable that means if you use:

```js

import en from "make-plural/plurals/en"

```
or 
```js
import { en } from "make-plural/plurals"

```

Will only import "en" plural.
