### ISSUE TITLE
Custom localization languages

### ISSUE THREAD

**Issue by reastyn** [lingui/js-lingui#1096]
**Is your feature request related to a problem? Please describe.**
When I try to compile with `lingui compile` I get an error with `Error: Invalid locale custom_locale (missing plural rules)!`. I need a way to specify custom_locale plurals in the config itself. The only thing I want is to bypass the if statement here
https://github.com/lingui/js-lingui/blob/ab68c06775c37bf5960536f274ed35fb2420f6a8/packages/cli/src/lingui-compile.ts#L42-L50

In the runtime I can specify the plurals using the code `i18n.loadLocaleData`.

**Describe proposed solution**
I want to add to config an option to specify plurals ie.
```
{
  locales: ['en, 'custom_locale'],
  plurals: {
    'custom_locale': 'en'
  }
}
```
or specify to not check on some locales at all. What do you think?

**Describe alternatives you've considered**
Alternative would be to specify plurals it in the locales, however it would complicate the API for some users.

**Additional context**
I will supply a merge request, but when it comes to adding things to the library API, I wanted to ask maintainers what they think about the proposed solution.

**Comment by ruscoder** [comment]
I'm also interested in how to add locales for languages that aren't presented in `make-plurals` package, e.g. Kinyarwanda language (rw). Also, get the same error.

**Comment by reastyn** [comment]
In that case the api could be more verbose - 
```js
module.exports = {
  locales: ['rw'],
  plurals: {
    'rw': require('./plurals/rw.plural.js')
  }
}
```

If it needs to be available in all config forms then
```json
{
  "locales": ["rw"],
  "plurals": {
    "rw": {
      "path": "./plurals/rw.plural.js"
    }
  }
}
```

**Comment by wangzi6224** [comment]
> 

Have you solved this problem yet?

**Comment by thekip** [comment]
Use v4 version (currently with `@next` keyword) it's already fixed there.
