### ISSUE TITLE
Unicode characters are removed from .po when they are in msgstr

### ISSUE THREAD

**Issue by JSteunou** [lingui/js-lingui#1098]
**Describe the bug**

When using po format and adding some unicode char like `\xA0` in `msgstr` it works at runtime, but running the CLI to extract messages remove all of those char

**To Reproduce**

```
msgid "Welcome!"
msgstr "Bienvenue\xA0!"
```

Save it, extract again, boom, `\xA0` is gone

**Expected behavior**

Should keep this char

**Additional context**

- jsLingui version ``lingui --version``  3.10.4
- Babel version ``npm list @babel/core`` 7.14.6
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)

I tried to play with jsesc configuration, all kind... no luck :(

**Comment by semoal** [comment]
https://github.com/lingui/js-lingui/pull/1032/files
We remove extra-scaped literals, probably we should add there. /x together with /u.

What do you think?

**Comment by JSteunou** [comment]
I m not sure, because my issue is not for char in the key or message extracted by the macro logic, but in po files `msgstr` section aka the final translation.

The issue here is that running the CLI to discover new translation keys corrupt the current dictionary which is kind of worse I guess?

**Comment by semoal** [comment]
Macro is the responsible of generating the final translation.

**Comment by JSteunou** [comment]
Ho ok I did not understand that. With that name I supposed it was only the part responsible for extraction from code (babel-macros / Macro). Also the tests from the commit you linked shows a test with extraction key, not value from dictionary.

Then yeah it might be linked, worth the shot
