### ISSUE TITLE
import { t as something } extracts {0} instead of text

### ISSUE THREAD

**Issue by himdel** [lingui/js-lingui#1113]
When trying to use a different name for `t`, extraction *almost* works, but not quite...

**Works:**

```js
import { t } from '@lingui/macro';
console.log(t`Not found`);
```

extracts

```po
#: src/components/typeahead/typeahead.tsx:84
msgid "Not found"
msgstr "Not found"
```

**Breaks:**

```js
import { t as _ } from '@lingui/macro';
console.log(_`Not found`);
```

extracts

```po
#: src/components/typeahead/typeahead.tsx:84
msgid "{0}"
msgstr "{0}"
```

It clearly finds the right place, line 84 is indeed where that `` _`string` `` can be found, but fails to extract anything meaningful.

(That behaviour is not limited to `_`, I'm getting the same result regardless of `_` vs `x`, jsx/ts/js.)

**Expected behavior**

I expect to be able to alias the `t` function to different names without extraction failing.
(Whether that's a reasonable expectation or not is up to you really :))

**Additional context**

```
$ `npm bin`/lingui --version
3.10.2

$ npm list @babel/core
├── @babel/core@7.15.0 
└─┬ stylelint@13.13.1
  └─┬ @stylelint/postcss-css-in-js@0.37.2
    └── @babel/core@7.15.0  deduped

$ cat .babelrc 
{
    "presets": [
        "@babel/preset-env",
        "@babel/preset-react",
        "@babel/preset-typescript",
    ],
    "plugins": [
        "@babel/plugin-syntax-dynamic-import",
        "@babel/plugin-transform-runtime",
        "babel-plugin-macros",
    ]
}
```

**Comment by semoal** [comment]
We use strict import names to know where and how to extract the values. Probably we could do something like identifying in the AST if you're using an alternative name and look for that instead, but not sure If I have the bandwidth to do that.
