### ISSUE TITLE
Issue when using different version of lingui + pnpm with typescript

### ISSUE THREAD

**Issue by aladinflux** [lingui/js-lingui#1114]
**Describe the bug**
When using `pnpm` as a package manager, you install different versions of lingui (even minor), typescript checks will fail. This is happening because of the latest update of `@lingui/core@3.10.4` and `@lingui/react@3.10.2`.

```
Type error: Type 'import("/path/to/node_modules/.pnpm/@lingui+core@3.10.4/node_modules/@lingui/core/cjs/i18n").I18n' is not assignable to type 'import("/path/to/node_modules/.pnpm/@lingui+core@3.10.2/node_modules/@lingui/core/cjs/i18n").I18n'.
Types have separate declarations of a private property '_events'.
...
<I18nProvider i18n={i18n}>
```

**To Reproduce**
Create a `nextjs` app and use `strict: true` in `tsconfig.json`.
Using pnpm as your package manager, Install the latest versions of lingui as such
```
...
"@lingui/core": "^3.10.4",
"@lingui/react": "^3.10.2",
...
```

In `_app.tsx`
```typescript
import { I18nProvider } from '@lingui/react'
import { i18n } from '@lingui/core'
const App: import('react').FC<import('next/app').AppProps> = ({ Component, pageProps }) => {
   return (
        <I18nProvider i18n={i18n}>
           <Component {...pageProps} />
        </I18nProvider>
    )
}

export default App
```

**Expected behavior**
No typing issues should happen.

**Additional context**
All `@lingui/*` releases should have the same exact version number when deployed in order to avoid such issues.

- jsLingui version `3.10.2 and 3.10.4`
- Babel version `7.15.0`
- NextJS

**Comment by semoal** [comment]
We had to release some internal modifications of EventEmitter and versions should be exact to avoid such issues.

We recommend always keep the @lingui/* packages at the same version, which would mean that are compatible.

**Comment by aladinflux** [comment]
The issue is still there, `@lingui/react` is at `3.10.2` but `@lingui/core` is at `3.10.4`. Can you release all `@lingui/*` at `3.10.4` so that we can update the rest of the packages?

**Comment by sanmont3drepo** [comment]
Having the same problem today with lingui 3.11.1

**Comment by semoal** [comment]
> Having the same problem today with lingui 3.11.1

Just update all the packages to the same version, it should be fixed since that version
