### ISSUE TITLE
short syntax of { t } from "@lingui/macro" is broken

### ISSUE THREAD

**Issue by axe312ger** [lingui/js-lingui#1115]
**Describe the bug**
In my GatsbyJS project, I am not able to use the short syntax of the macros t function. (`import { t } from "@lingui/macro"`). I am pretty sure I experienced similar issues when playing around with NextJS & linguiJS a few weeks ago.

As soon I pass an config object instead of a string, it works.

This seems to be related to #920, the fix in the comments resolves the issue for me as well.

I will for now work around with the longer syntax with the config object.

**To Reproduce**

```jsx
import { t } from "@lingui/macro"

/* This does not work:
 * Cannot process file ...: @lingui/macro: Cannot read property 'findIndex' of undefined Learn more: https://www.npmjs.com/package/@lingui/macro
 */
const short = () => <h1>{t('translationTest')}</h1>

// This works
const long = () => <h1>{t({ id: 'translationTest' })}</h1>
```

**Expected behavior**
The short syntax should work as described in the docs at https://lingui.js.org/ref/macro.html

**Additional context**

- jsLingui version `3.10.2`
- Babel version `@babel/core@7.15.0`
- Your Babel config:
```js
module.exports = {
  presets: ['babel-preset-gatsby'],
}
```

**Comment by ianatha** [comment]
@axe312ger You're supposed to use ``{t`translationTest`}`` (note backticks instead of quotes). See [tagged template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates) if you're curious about this syntax.

**Comment by axe312ger** [comment]
ahhhhhhh nice. lemme try that. thanks!

**Comment by axe312ger** [comment]
Yeah with template literals it does work. Sorry for overlooking this in the docs.
