### ISSUE TITLE
Lingui generate duplicated gettext msgid

### ISSUE THREAD

**Issue by truong-hua** [lingui/js-lingui#1116]
**Describe the bug**
I have 2 code that causes lingui generate duplicated msgid as follows:
```
plural(valueData?.monthNumber, {
  one: `/ # tháng`,
  other: `/ # tháng`,
})
```
and
```
plural(monthNumber, {
  one: `/ # tháng`,
  other: `/ # tháng`,
})
```

which all generates 
```
msgid "/ # tháng"
msgid_plural "/ # tháng"
msgstr[0] ""
msgstr[1] ""
```
but has different `#. js-lingui:icu` in the comment above which cause it can not be deduplicate through `msguniq`

**Expected behavior**
It should not causes duplicate gettext msgid because gettext does not support it

**Additional context**
I think lingui context in the comment should support multiple different icu format but same msgid

- jsLingui version: 3.10.2
- Babel version: `@babel/core@7.12.3`
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.): ReactJS

**Comment by truong-hua** [comment]
don't stale

**Comment by truong-hua** [comment]
don't stale

**Comment by yozi-developer** [comment]
it is not only gettext, simple json formatter affected as well. `<Trans>Date of birth</Trans>` and `t("Date of Birth")` generates 2 different translation keys and it becomes 2 different messages to translate.

**Comment by yozi-developer** [comment]
don't stale
