### ISSUE TITLE
@lingui/macro: Unknown macro default

### ISSUE THREAD

**Issue by nobiit** [lingui/js-lingui#1122]
**Describe the bug**
Unable to compile Typescript project with @lingui/macro.

**To Reproduce**
See demo project here: https://github.com/nobiit/lingui-macro-ts-bug

**Expected behavior**
I can use @lingui/macro with Typescript project.

**Additional context**
- jsLingui version ``3.10.2``
- Babel version ``7.15.0``
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)
```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    "@babel/preset-typescript",
    "@lingui/babel-preset-react"
  ],
  "plugins": [
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    "macros"
  ]
}

```
[result_of_npm_list_@babel_core.txt](https://github.com/lingui/js-lingui/files/7022768/result_of_npm_list_%40babel_core.txt)

**Comment by semoal** [comment]
.babelrc must be on root of the project, not inside src

**Comment by Patricknew** [comment]
I'm also getting `unknown macro default` error, but only in my test environment (jest).

I'm using Lingui 4.11.0. I've made sure the babel config for my jest setup to include "macros". Jest is failing at the first instance of the `msg` macro:

"SOME_STRING: (0, macro_1.msg)\`BLAH\`"

The error stack doesn't have much interesting info.

What am I missing?

**Comment by thekip** [comment]
ts-jest uses tsc to traspile your code, not a babel, hence babel-macro is not applied. Or hat is most likely you have both tsc and babel, and babel is processing after tsc and get reshaped symbols (as in your example) which macro static analysis doesn't understand. 

You need to setup jest exactly as you would setup your bundling process. Other option would be mocking out all macros from test and replacing them to simple function which returns whatever it called with.

**Comment by thekip** [comment]
Yes, lingui macro written for babel and SWC, ts-jest uses typescript hence is not supported. Just swap out ts-jest to swc, it is a drop-in replacement, including legacy decorators and metadata.

**Comment by Patricknew** [comment]
I'll look into SWC next.

For now I'm mocking the macros with ts-jest. For anyone else who might run into the same issue, here's my mock:

```
jest.mock("@lingui/macro", () => ({
  ...jest.requireActual("@lingui/macro"),
  msg: str => str,
  t: str => str,
  Trans: ({ children }) => children,
}));
```

**Comment by thekip** [comment]
You don't need to `...jest.requireActual("@lingui/macro")` there is nothing in that package what is meant to be used in runtime.
