### ISSUE TITLE
Add `sideEffects: false` to package.json so webpack can remove dev.esm.js on production

### ISSUE THREAD

**Issue by chuyik** [lingui/js-lingui#1124]
**Describe the bug**
dev.esm.js is packed into production bundle with webpack 5.

![image](https://user-images.githubusercontent.com/6262943/131652967-36e7df02-4b0c-451e-bb40-733551d451e1.png)

**To Reproduce**
use webpack 5 to pack bundle.

**Expected behavior**
dev.esm.js should not be packed.

**Additional context**

- jsLingui version `3.10.2`
- Babel version `7.15.0`

**Comment by semoal** [comment]
Happy to see that you're using Rematch and Lingui, two of my hobbies.

Adding sideEffects to false will automatically say to webpack that dev shouldn't be bundled? Or should we add exports: {} on package.json?

**Comment by chuyik** [comment]
Wow I didn't know that you are also the maintainer of Rematch.

Since webpack does not know that `dev.esm.js` is pure function and has not side effects, we need the to set sideEffects to false (see Sean's [answer](https://stackoverflow.com/questions/49160752/what-does-webpack-4-expect-from-a-package-with-sideeffects-false)), and `dev.esm.js` is gone in my test:

![image](https://user-images.githubusercontent.com/6262943/131660811-b3df9f5d-4abb-4898-b122-457897915387.png)

**Comment by semoal** [comment]
Great, I'll adjust the packages accordingly this afternoon and we release a new version the next Tuesday, since I want to include some more bug fixes :)

**Comment by chuyik** [comment]
Good to know, thanks!
