### ISSUE TITLE
Error "lingui: not found" if install lingui-cli locally 

### ISSUE THREAD

**Issue by shye0000** [lingui/js-lingui#113]
Hi, I installed lingui-cli the latest version 1.3.9 locally in my new project, and added the scripts 'add-locale', 'extract', 'compile' in my package.json like this (as documented here: https://lingui.github.io/js-lingui/ref/lingui-cli.html):

![selection_247](https://user-images.githubusercontent.com/6414361/32219644-32f4dc84-be2f-11e7-961c-e543901ffe85.png)

But I got an error "lingui: not found":

![selection_249](https://user-images.githubusercontent.com/6414361/32219715-799d8744-be2f-11e7-8c68-b450326a8f4f.png)

Thanks a lot in advance.

**Comment by shye0000** [comment]
Sorry its my bad actually, I got "%20" in my project root folder name, after remove it resolve de problem.

**Comment by tricoder42** [comment]
No problem, I'm glad it works!
