### ISSUE TITLE
I18nProvider remounts all the children, but not rerender

### ISSUE THREAD

**Issue by AlgoTrader** [lingui/js-lingui#1136]
**Describe the bug**
`I18nProvider` implementation has a very unpleasant effect of changing own key when locale changes. It declares, that forceRenderOnLocaleChange force rerender of all children. Sorry, but its not a rerender, it's full remount of it's children. As a result React.memo is killed and state of all the components is reset. I have google map inside and its remount is slow and flickering

**To Reproduce**

```
export default function App() {
   return <I18nProvider i18n={i18n}><PureComponentWithReactMemo></I18nProvider>
}
```

**Expected behavior**
It would be great to have all the components just rerendered, not remounted. It is usually done with a trick like having state with counter and incrementing it by one every time we need children to be rerendered. 

I cannot have a single global `I18nProvider` as it remounts everything inside, the heavy components like maps are remounted with unpleasant flicker. 

**Additional context**

- jsLingui version 3.11.1
- Babel version - not related

**Comment by AlgoTrader** [comment]
comments in code: `We can't use useMemo hook either, because we want to recalculate value manually. useMemo can be used like this`

```
const context = useMemo(() => {...}, [i18n.locale])
```

i18n is not changed, but dependency list can hold it's properties, then memo is recalculated on deep changes in i18n

There is another stuff in code: 

```
React.useState<I18nContext>(makeContext())
```

useState may be passed a function as a parameter, it is named initialState, but you use it like useMemo for tracking props. It's really bad practice to have initialState parameter recalculated on each render. I would write

```
const context = useMemo(makeContext, [i18n.locale])
```

BTW makeContext may be wrapped in useCallback

**Comment by semoal** [comment]
Hi mate, when we worked on the reimplementation of Lingui 3 we forgot a lot about the React side, also we lost a bit the north. I'll be happy to review a pull request from you making the React implementation much better than it is right now.

**Comment by JSteunou** [comment]
instead of using `key` a wrapper with the prop `lang` could be used or a state, to re-render on `lang` change

**Comment by JSteunou** [comment]
plzzz stale bot :)

**Comment by sakulstra** [comment]
Was just running into this as well.
I feel like having this behavior as a default is a weird choice.

probably just stupidity on my side:
Didn't realize the remount for quite some time and now have to refactor every use of `t` which is sad. Would have rather notices it earlier :sweat_smile:

**Comment by sakulstra** [comment]
not stale

**Comment by athammer** [comment]
A remount seems a bit heavy handed esp for larger apps and could lead to some really hard to debug apps. I probably won't have time to contribute to this in a form of a PR but if we can create a bounty I'll contribute. I'm not sure we currently can due to the stale bot closing this though.

**Comment by thekip** [comment]
@JSteunou we are going to release v4 soon, and it seems it's a good time to fix this as well. Would you want to participate and prepare a PR? Or at least code-review if i implement what you mentioned in the comment above?

**Comment by zackcarlson** [comment]
I'm experiencing an issue where my entire app re-mounts for non-US-english translations. I've described my issue in depth [here on StackOverflow](https://stackoverflow.com/questions/75726526/app-remounts-for-non-english-locales-lingui-react-lingui-core). Please let me know if you have any guidance. Thanks so much!

**Comment by JSteunou** [comment]
> @JSteunou we are going to release v4 soon, and it seems it's a good time to fix this as well. Would you want to participate and prepare a PR? Or at least code-review if i implement what you mentioned in the comment above?

I'm a bit late but kudos it works fine. The only issue now is that migration path is not that easy because of a limitation pointed out by @vonovak about the use of `t` macro and the absence of re-render.

@thekip you though about a new macro `useLingui` and I follow you. If really the `t` macro cannot be detected when it is in a react component, then having this hook from the macros would be a really nice feature. I could be then linked together with an ESLint  rule to prevent use of `t` from macro when inside a React component. (I'm thinking DX & team work here)
