### ISSUE TITLE
configPath is not set when calling getConfig in babel-plugin-extract-messages

### ISSUE THREAD

**Issue by mattdaly** [lingui/js-lingui#1137]
**Describe the bug**
When using a lingui config that is not located at the root, extraction fails because babel cannot find the config. The result is a `Cannot process file <filename>: Cannot find module <config>` error for each file being processed, and no translations being extracted.

**To Reproduce**
Place a lingui config in a nested directory and pass its path to the `--config` argument when calling extract - no translations are extracted and the error noted above is received for each file being parsed.

**Expected behavior**
That custom config paths are passed to the `configPath` property for all calls to `getConfig`, specifically in this case in `babel-plugin-extract-messages`.

Adding a default lingui config at the root that imports and re-exports the nested config is the only solution without changes to lingui itself.

Passing a `configPath` to [`getConfig` in babel-plugin-extract-messages](https://github.com/lingui/js-lingui/blob/8590c1a4c79a22483a28d8a041809340697e6a3f/packages/babel-plugin-extract-messages/src/index.ts#L255) fixes the issue. I have tested and verified this by setting `configPath: process.env.LINGUI_CONFIG` (and obviously setting the value of that env var) - I did not look at how to pass the initial `program.config` all the way down to the extractor.

https://github.com/lingui/js-lingui/blob/8590c1a4c79a22483a28d8a041809340697e6a3f/packages/babel-plugin-extract-messages/src/index.ts#L255

**Additional context**
We have an internal custom build tool that wraps webpack and configures module federation for use across our micro frontends. Part of that build tool is a wrapper around lingui that defines a default lingui config appropriate for our chosen micro frontend structure and provides a cli to extract translations as part of our ci process. It is very similar to create-react-app, with module federation, lingui and some others.

This means that in our micro frontends themselves, the lingui config is located within the `node_modules` directory, and not at the root. Without defining a lingui config at the root of each micro frontend that imports and re-exports the lingui config from our build tool, no translations are extracted.

**Comment by semoal** [comment]
Will look into it asap :)

**Comment by semoal** [comment]
Will look in to this tonight, for releasing a new version this week :)
