### ISSUE TITLE
No locales defined message when using remoteLoader

### ISSUE THREAD

**Issue by nmoinvaz** [lingui/js-lingui#1148]
**Describe the bug**
When using the `remoteLoader` I get an error when running `npm run build` that states `No locales defined`. This is expected in my use case as I am remotely loading all the localizations.

**Expected behavior**
No warning message when building. 

**Additional context**
May there could be a configuration option to turn it off.

**Comment by semoal** [comment]
It's remote but you need to specify on lingui config which locales are available in your application.

**Comment by nmoinvaz** [comment]
For our application, the list of locales that are supported are also loaded dynamically.
