### ISSUE TITLE
Examples don't work with extract

### ISSUE THREAD

**Issue by sanmont3drepo** [lingui/js-lingui#1149]
**Describe the bug**
The examples folder (I tried master and tag 3.12.1) dont work with extract. 
in examples/js extract dont work with i18n._(...) . And in create-react-app it just throws an error "TypeError: ext.match is not a function 
" and doesnt work at all. 

**To Reproduce**
for both examples run `yarn install` beforehand

- in examples/js add ``i18n._("extract doesnt work");`` in src/messages.js when you run extract it doesnt add it to the catalog
- in examples/create-react-app/package.json just run `yarn extract`

**Expected behavior**
Should extract definitions without errors.

**Additional context**
- yarn version 1.22.5 
- node v14.15.0 .
- jsLingui version 3.11.0
- Babel version @babel/core@7.12.3

**Comment by semoal** [comment]
Will update examples accordingly, sorry for the inconvenience.
