### ISSUE TITLE
Support for SWC

### ISSUE THREAD

**Issue by matthewlilley** [lingui/js-lingui#1158]
We just dropped bable in favor of SWC but it seems Lingui isn't yet compatible with this compiler.

**Comment by matthewlilley** [comment]
@semoal after speaking to the Next.js team this will not be available for some time, and they recommend against using it for something like this when it comes because of the perf hit.

**Comment by Hideman85** [comment]
I will add my vote to this topic, I'm also looking forward to not use babel nor webpack anymore...

**Comment by shouze** [comment]
@semoal looks like swc plugin 2.0 is on the way, stay tuned :hourglass_flowing_sand: to know if js api is kept or if it's mandatory to write a rust plugin or not at the end. So the best thing to do at the moment is to subscribe to https://github.com/swc-project/swc/issues/2635#issue-1043151813 :wink:

**Comment by armandabric** [comment]
This issue is not stale. The nextjs team have done some progress on the subject: https://github.com/vercel/next.js/discussions/30174

**Comment by MarkMurphy** [comment]
Still relevant.

**Comment by gynekolog** [comment]
It's not stale.

**Comment by armandabric** [comment]
Maybe I'm getting wrong but it seems that Vercel stop to try to port `@babel/macro` to SWC. Did anyone is aware of a port or a solution to use SWC with linguijs?

**Comment by Cielquan** [comment]
Not stale.

**Comment by belaczek** [comment]
There are already swc plugins for `styled-components` and `emotion` https://github.com/swc-project/plugins/tree/main/packages. Is that something that could be used as an inspiration/guideline for lingui plugin port?

**Comment by semoal** [comment]
We need someone to port the macros plugin and then Lingui could go next. I'm not an experienced programmer on Rust, but couldn't see anything yet on SWC to interact with the AST for doing the macro's magic thing.

I'll pin this issue for being updated about news from Next team or someone else that works in this field.

**Comment by gynekolog** [comment]
The #1224 has more activity about Lingui and SWC.

**Comment by thekip** [comment]
duplicate https://github.com/lingui/js-lingui/issues/1224
