### ISSUE TITLE
@lingui/cli dependancy cli-table when using 0.3.7 breaks extract

### ISSUE THREAD

**Issue by lukehowkins** [lingui/js-lingui#1169]
**Describe the bug**
getting error:
```
node_modules/cli-table/lib/utils.js:85
  var split = stripped.split("\n");

TypeError: stripped.split is not a function
```

**To Reproduce**
run `lingui extract`

**Expected behavior**
to extract without error

**Additional context**
https://github.com/Automattic/cli-table/issues/152

- jsLingui version 3.12.1
- Babel version  7.16.0

**Workaround** 
Have added `"cli-table": "0.3.6",` in my project dev-dependancy

**Comment by drod66** [comment]
The issue seems to be that `slicedToArray()` returns numbers instead of strings when the parsing finds number values. Later on, cli-table try to do a `split()` on a Number object (expecting a string, i.e. `"100"` instead of `100`).

**Comment by callms** [comment]
For those having this issue and using npm, you should pin the version 0.3.6 of `cli-table` in your `package-lock.json`

1. edit the file, and locate the section `@lingui/cli`
2. remove the `cli-table` key in `requires`
3. add the following object in `dependancies`:

```json
"cli-table": {
  "version": "0.3.6"
},
```

In the meantime I also submitted #1172 if the maintainers here would like to take a precautionary action (essentially preventing every new installations of `@lingui/cli` from being broken at this time)

**Comment by dmitryshelomanov** [comment]
same error

**Comment by semoal** [comment]
Hi guys, we'll take care of this (and the other issues/discussions) asap this week. Sorry for the inconveniences.

**Comment by semoal** [comment]
Fixed this on latest version. 3.13.0.
