### ISSUE TITLE
JSX macros aren't working inside JSX expressions in JSX macros

### ISSUE THREAD

**Issue by khmm12** [lingui/js-lingui#1175]
**Describe the bug**

Since v3 JSX macros aren't working inside JSX expressions in JSX macros. v2 macros are working as expected.

The issue is reproducible in any nesting level.

**To Reproduce**

```jsx
import { Trans } from '@lingui/macro'

export default function Component(props) {
  return <Trans>Hello, {props.world ? <Trans>world</Trans> : <Trans>guys</Trans>}</Trans>
}
```

**Expected behaviour**
```jsx
import { Trans } from '@lingui/react'

export default function Component(props) {
  return (
    <Trans
      id='Hello, {0}'
      values={{
        0: props.world ? <Trans id='world' /> : <Trans id='guys' />
      }}
    />
  )
}
```

**Actual behaviour**
```jsx
import { Trans } from '@lingui/react'

export default function Component(props) {
  return (
    <Trans
      id='Hello, {0}'
      values={{
        0: props.world ? <Trans>world</Trans> : <Trans>guys</Trans>
      }}
    />
  )
}
```

**Additional context**

- `lingui`: `3.13.0`
- `@babel/core`: `7.16.0`

**Comment by semoal** [comment]
Thx @khmm12  will take a look as soon as possible. Indeed looks a regression

**Comment by tulodzieckim-simplito** [comment]
Any news about this?

**Comment by khmm12** [comment]
No, still actual.

**Comment by khmm12** [comment]
Up

**Comment by thekip** [comment]
If some one takes this task, please, also check that in the SWC plugin. The test case should ported there.

**Comment by thekip** [comment]
Checked this in SWC, this also don't work. I made a quick fix for 1 level of nesting for js macro. But if there would be more levels, that would break again. To fix this, fundamental changes needed. Still think how to do that.

**Comment by thekip** [comment]
fixed by https://github.com/lingui/js-lingui/pull/1436 and would be released with v4
