### ISSUE TITLE
Lingui extract doesn't handle i18n._ strings

### ISSUE THREAD

**Issue by juanluispaz** [lingui/js-lingui#1178]
**Describe the bug**
Lingui extract ignores i18n._

**To Reproduce**

```
import { i18n } from "@lingui/core"

export default function App() {
   return i18n._('This should be translated!')
}
```

**Expected behavior**
The text should appear in the .po file

**Additional context**
I review the source code and I found the function [isI18nMethod](https://github.com/lingui/js-lingui/blob/5feb120e8c75d7b8c082d5c4b68185ef5dcc3ebc/packages/babel-plugin-extract-messages/src/index.ts#L124) defined at babel-plugin-extract-messages but it looks like is never used.

- jsLingui version `3.12.1`
- Babel version `7.16.0`
- Your Babel config (`.babelrc`):
`.babelrc
{ "presets": [ "@babel/preset-env", "@babel/preset-react", "@lingui/babel-preset-react", "@babel/preset-typescript" ] }
`
- Lingui config (`.linguirc`)
`.linguirc
{
"locales": ["en", "es", "de"],
"sourceLocale": "en",
"catalogs": [{
"path": "<rootDir>/src/app-react/locales/{locale}/translations",
"include": ["<rootDir>/src/app-react"],
"exclude": ["**/node_modules/**"]
}],
"format": "po-gettext",
"compileNamespace": "ts"
}
`

**Comment by semoal** [comment]
Hola Juan,

To get extracted you have to use the t`` macro. In that way the `babel-plugin-extract-messages` can know which value has to extract, the i18n it's used to interpolate between locales, plurals etc..

Since v3, you don't need to use i18n you can just use directly the macro.

For example:

```jsx
import { t } from "@lingui/macro"

export default function App() {
   return t`This should be translated!`
}

```

**Comment by juanluispaz** [comment]
Hi,

The macros are wonderful, but in the context where I'm using this it is not possible till we finish the migration and we can drop the restriction.

**Comment by tannerlyons** [comment]
@juanluispaz , you can use this workaround:

```
import { i18n } from "@lingui/core"

export default function App() {
   return i18n._(/*i18n*/ "This should be translated!");
}
```

The extractor uses `/*i18n*/` as a marker for things to extract.

**Comment by borjaMiralles** [comment]
I can confirm that this workaround works, thanks @tannerlyons
