### ISSUE TITLE
Webpack loader for message catalogs

### ISSUE THREAD

**Issue by lzurbriggen** [lingui/js-lingui#118]
My goal is to load my messages without manually compiling (`lingui compile`) them during development. I don't have a problem manually compiling them for a production build but having to do it manually after every change to the files is cumbersome.

I used create-react-app and ejected it to be able to add the lingui-react babel preset, which means I'm using webpack. I couldn't find a webpack loader to watch and compile the catalogs. 

I'm also a little confused about the lingui-i18n/dev package. I assumed I could use it to load my messages.json files and create catalogs from it on the fly, but from the tutorial it seems that I have to load the compiled .js catalogs anyway.

Is there an easy way to achieve what I want?

**Comment by tricoder42** [comment]
Not right now, but it's one of [planned features](https://github.com/lingui/js-lingui/blob/master/ROADMAP.md#webpack-loader--easy). I might take a look at it this weekend, but if you had experience with building webpack loaders, any help is appreciated 👍 

> I'm also a little confused about the lingui-i18n/dev package. I assumed I could use it to load my messages.json files and create catalogs from it on the fly, but from the tutorial it seems that I have to load the compiled .js catalogs anyway.

I'll check the docs. If you use dev package, it's enough to load .json catalogs.

**Comment by tricoder42** [comment]
I admit I'm using compiled message catalogs everywhere, but the reason of i18n/dev package is that you shouldn't compile/extract messages in development (as long as you don't need them translated). You only need to extract/compile for production and when you want to add translation for given language.

**Comment by lzurbriggen** [comment]
> if you had experience with building webpack loaders

Unfortunately not, but good to hear that it's on the roadmap.

> you shouldn't compile/extract messages in development

I guess there are different workflows. In my current I'd like to translate everything I'm working on step by step instead of passing all the strings to a translation agency when I'm done.

Thanks for your quick replies!

**Comment by tricoder42** [comment]
Yeah, I understand. I'll focus on this feature in next few days.

Cheers!

**Comment by tricoder42** [comment]
Just release **lingui-loader@0.1.0**. This is first release, please consider it experimental. I tried it with [webpack example](https://github.com/lingui/js-lingui/blob/master/examples/webpack-react/src/App.js#L25) and it works fine. I'm releasing it early to get feedback as soon as possible.

Quickstart
========

1. Install it

```
npm install --dev lingui-loader
```

2. Load JSON message catalog using this loader:

```
import catalog from 'lingui-loader!locale/en/messages.json'

// catalog must be unpacked before passing to I18nProvider
<I18nProvider catalog={{ en: unpackCatalog(catalog) }} language="en">
...
</I18nProvider>
```

or using dynamic import

```
import { unpackCatalog } from 'lingui-i18n'
const catalogs = await import(
      /* webpackMode: "lazy", webpackChunkName: "i18n-[index]" */
      `lingui-loader!../locale/${language}/messages.json`).then(unpackCatalog)
```

See [webpack example](https://github.com/lingui/js-lingui/blob/master/examples/webpack-react/src/App.js#L25).

I'll add more docs tomorrow.

**Comment by lzurbriggen** [comment]
This is very cool, thanks!

It works great so far (there's a problem changing languages, but that may be unrelated).

Just to describe how I'm using this in my react project:

I added it to my webpack config (dev _and_ prod in my case) the same way other loaders are configured
```
{
            test: /messages\.(json)$/,
            include: paths.locales,
            loader: require.resolve('lingui-loader'),
},
```

Now I can just import the json files without explicitly telling webpack how to load the files. This works great for prod as well as long as I don't need to load them dynamically.

```
import catalogDe from './locale/de/messages.json';
import catalogEn from './locale/en/messages.json';

const catalogs = {
    de: unpackCatalog(catalogDe),
    en: unpackCatalog(catalogEn),
};

...

<I18nProvider language="de" catalogs={catalogs}>
...
</I18nProvider>
```

I'll let you know if I encounter any problems.

**Comment by tricoder42** [comment]
Yes, this is great!

I was thinking that loader could also accept whole locale folder and return all catalogs, for cases like yours – when you don't need to load messages dynamically. Something like:

```js
import catalogs from 'lingui-loader!./locale'
```

I'm not 100% sure, if webpack supports loading folders and then I would have to update `unpackCatalog` function. I'll test it later.

**Comment by pybuche** [comment]
Hey ! 

I just started using `lingui` and indeed, having a loader for my dev env is very convenient.

But I don't get how I switch to prod "compile" mode with `@lingui/loader`...

Say I import my catalogs this way:
```javascript
import fr from '@lingui/loader!conf/locale/fr/messages.json';
import en from '@lingui/loader!conf/locale/en/messages.json';
```
Do `messages.js` files generated through `lingui compile` are useful here? 
I guess they are not loaded at all with this method, am I right?

In this case, is there a significant performance gap between loading full json catalog and minified ones?

Thanks!

**Comment by tricoder42** [comment]
Hey @pybuche,
if you use `@lingui/loader`, you don't have to run `lingui compile` manually. Loader actually creates production ready compiled catalogs.

These two import statements are identical:

```js
// importing source catalog through loader
import fr from '@lingui/loader!conf/locale/fr/messages.json'
// importing compiled catalog
import fr from 'conf/locale/fr/messages.js'
```
