### ISSUE TITLE
TypeScript guide is out of date

### ISSUE THREAD

**Issue by OliverJAsh** [lingui/js-lingui#1183]
https://lingui.js.org/guides/typescript.html

This guide mentions `babel-preset-react`, `babel-preset-env`, and `@lingui/babel-preset-react`, but as far as I can see these were only necessary for Lingui v2—not for v3. I'm new to Lingui so I could well be wrong!

**Comment by semoal** [comment]
Yep, they're not required anymore for Lingui v3. CRA setup should work out of the box, or at least the only one required should be `babel-plugin-macros` :)

**Comment by benbender** [comment]
Yes, it should be fixed. Original bug was this one: https://github.com/vercel/nft/issues/257
