### ISSUE TITLE
Suggestion: preserve names of dates and numbers inside ICU Message

### ISSUE THREAD

**Issue by OliverJAsh** [lingui/js-lingui#1185]
Given this source file:

```ts
import { i18n } from "@lingui/core";
import { t } from "@lingui/macro";

const name = "Bob";
const numberOfPhotos = 123;
const firstUploadDate = new Date();

t`Hello ${name}. Since ${i18n.date(
    firstUploadDate
)} you have uploaded: ${i18n.number(numberOfPhotos)}`;

```

This will extract the following ICU Message:

```
Hello {name}. Since {0} you have uploaded: {1}
```

Whilst the name of the `name` variable is preserved in the ICU Message, the names of the date (`firstUploadDate`) and number (`numberOfPhotos`) are lost and replaced with numbers (`0` and `1` respectively).

I was wondering if it would be possible to amend the macro so that it preserved these names, resulting in an ICU Message along the lines of:

```
Hello {name}. Since {firstUploadData} you have uploaded {numberOfPhotos}
```

I think this would be useful because it would provide more context to the translators.

I understand the macro is already doing something like this for plurals, e.g.

```ts
import { i18n } from "@lingui/core";
import { plural, t } from "@lingui/macro";

const name = "Bob";
const numberOfPhotos = 123;
const firstUploadDate = new Date();

t`Hello ${name}. Since ${i18n.date(firstUploadDate)} you have uploaded ${plural(
    numberOfPhotos,
    { one: "# photo", other: "# photos" }
)}`;

```

This will generate:

```
Hello {name}. Since {0} you have uploaded {numberOfPhotos, plural, one {# photo} other {# photos}}
```

**Comment by semoal** [comment]
Yeah, this is a good idea, I'm sure we can do this :)
