### ISSUE TITLE
Suggestion: option to flatten ICU Messages

### ISSUE THREAD

**Issue by OliverJAsh** [lingui/js-lingui#1186]
FormatJS's `extract` command has an option called `--flatten`. The documentation is self-explanatory so I'll paste it here:

> Whether to hoist selectors & flatten sentences as much as possible. E.g:
> `"I have {count, plural, one{a dog} other{many dogs}}"`
> becomes `"{count, plural, one{I have a dog} other{I have many dogs}}"`.
> The goal is to provide as many full sentences as possible since fragmented
> sentences are not translator-friendly.

Do you think it would make sense to have something similar in Lingui?

**Comment by semoal** [comment]
Will be an amazing feature for sure, but probably too big for our current bandwitdth. But open to review any contribution for sure :)
