### ISSUE TITLE
Allow named components in Trans in @lingui/macro

### ISSUE THREAD

**Issue by fdev** [lingui/js-lingui#1188]
The [documentation of `Trans`](https://lingui.js.org/ref/macro.html#trans) has the following example:

```jsx
<Trans id="Read the <0>docs</0>." components={{0: <a href="/docs" />}} />
```

Since the number tags don't provide much context to the translator I was hoping I could use named tags instead as such:

```jsx
<Trans id="Read the <link>docs</link>." components={{link: <a href="/docs" />}} />
```

Unfortunately, it seems only numbered tags are supported.

**Comment by semoal** [comment]
Yep, it's a nice addition. Also related to #1185

**Comment by fdev** [comment]
I'm replying to keep this issue from going stale. I would still like to see this implemented.

**Comment by fdev** [comment]
I'm replying (again) to keep this issue from going stale. I would still like to see this implemented.

**Comment by fdev** [comment]
I'm replying (again again) to keep this issue from going stale. I would still very much like to see this implemented.

**Comment by thekip** [comment]
According to the docs this should be already supported look at last line in the list https://lingui.js.org/releases/migration-3.html#lingui-react

**Comment by Martin005** [comment]
@thekip The `Trans` component in `@lingui/macro` doesn't currently support it.
On the other hand, the `Trans` component in `@lingui/react` should support it as mentioned in the Migration guide you posted, but it is not working there. I have [created an issue](https://github.com/lingui/js-lingui/issues/1400) which describes the issue in `@lingui/react`.

Let's leave this issue for implementing the "named components" in the `Trans` component in `@lingui/macro`.

**Comment by thekip** [comment]
@Martin005 it's unrelated to macro.

**Comment by andrii-bodnar** [comment]
> it's unrelated to macro.

@thekip could you please explain in more detail what you mean?

**Comment by thekip** [comment]
it was never asked for the Macro. The topic starter mentioned the doc of the macro because there are examples how macro transpiled to component, but the actual question was about component, not a macro.  

Macro doesn't pass thru itself `components` and `values` properties, they are populated automatically.

Implementing `named` components in macro it's a separate feature which should be carefully designed.

**Comment by mogelbrod** [comment]
I'm currently evaluating various i18n libraries and would have loved this functionality for the macro version of `<Trans>`. Does the decision to not support this still stand @timofei-iatsenko?

**Comment by timofei-iatsenko** [comment]
@mogelbrod technically it's easy change to the macro, but i struggled with syntax for that. Do you have any idea how that might look like? 

```ts
<Trans>Read the <a href="/docs">docs</a> /*<-- how to provide a name for that component? */</Trans>
```

**Comment by mogelbrod** [comment]
Great to hear! Here are a few ideas off the top of my head. I'd personally be happy with either of the first two alternatives. `tp` is just an abbreviation of translate placeholder, but in practice any short identifier would work.
```tsx
import { Trans, TP, tp } from '@lingui/react/macro'
const examples = [
  <Trans>Read the <a /*ph:docs*/ href="/docs">docs</a>.</Trans>, // magical comment with minimal extra syntax, albeit more magical.
  <Trans>Read the {tp.docs(<a href="/docs">docs</a>)}.</Trans>, // tp typed as a Record/proxy whose property denotes the name of the placeholder
  <Trans>Read the {tp('docs', <a href="/docs">docs</a>)}.</Trans>, // less magical but also more verbose due to extra delimeters
  <Trans>Read the <TP.docs as="a" href="/docs">docs</TP.docs>.</Trans>, // TP typed as a Record/proxy whose property denotes the name of the placeholder, `as` denotes which JSX element to actually render (which can be used to infer correct typing of the rest of the props.
]
```

If the macro `<Trans>` component got support for `components` that would also be a great enhancement, eg:
```tsx
<Trans
  components={{
    docs: <a href="/docs" />
  }}
  children="Read the <docs>docs</docs>."
/>
```

**Comment by timofei-iatsenko** [comment]
I'm thinking about something more sophisticated: 

```tsx
declare module 'react' {
  interface Attributes {
    linguiName?: string
  }
}

<Trans>Read the <a linguiName="docs-link" href="/docs">docs</a></Trans>
```

Not sure what corner cases might be here, but from Typescript point of view - that works. And it would work from runtime/macro point of view.

**Comment by mogelbrod** [comment]
I thought about that approach too but didn't think there was an easy fix for typescript, but if that works then it would definitely be nice.

**Comment by mogelbrod** [comment]
Hi again @timofei-iatsenko 👋 
is there anything I can help out with to land this feature? 🙏

**Comment by timofei-iatsenko** [comment]
@mogelbrod i just don't have to for that right now, you can open a PR with an implementation, i would happily review it.

**Comment by mogelbrod** [comment]
Good to know - if my org goes with LingUI I'll look into it for sure 👍 

Does a JSX prop sound good then (`<Trans>Read the <a linguiName="docs-link" href="/docs">docs</a></Trans>`)? We could make it opt-in to be backwards compatible, while also allowing the prop name to be customizable.

Appreciate the quick response!

**Comment by timofei-iatsenko** [comment]
Yes, the JSX prop is looks good.  I also thinking that we can define a list of default component with in it's names, for example: 

```
// somewhere in macro config
tagName: {
 "a": "link",
 "br": "br"
 "strong": "strong"
}
```

So some most often used tags inside translation would have names without manually passing the prop every time.

**Comment by mogelbrod** [comment]
I took a stab at this in the following PRs:
- https://github.com/lingui/js-lingui/pull/2505
- https://github.com/lingui/swc-plugin/pull/207
