### ISSUE TITLE
How to use named segments without using the extract?

### ISSUE THREAD

**Issue by zsolt-dev** [lingui/js-lingui#1189]
Our current workflow of translations is:

1. Add new **named** segments directly to webtranslateit.com, for example:
`"formNotValid": "Form validation failed. Please correct the items highlighted in red."`
2. Download the json file from webtranslateit.com into the codebase
3. Use translation as `t('formNotValid')`

I like it much more than automatic extracting from the codebase, since the source segments change a lot, and there is minimal duplication of segments.

The plurals are also much more elegant this way:
`t('minNumberOfChars', { count: minChars })`

Is there a way to do it like that in lingui?

Thank you

**Comment by semoal** [comment]
Hi! 
What do you mean by is there any way of do it with Lingui?

**Comment by zsolt-dev** [comment]
Hi @semoal,

Thank you for your reply.

I would like to use it the way the i18next works.

Examples:

```
const name = "Fred"
t`My name is ${ name }`
// becomes "Je m'appelle Fred"
```

I need to use it like this:
`t('myName', { name: 'Fred'});`


Plural example:
```
plural(count, {
  one: "# book",
  other: "# books"
})
```

I need to use it like this:
`t('numBooks', { count: count })`

**Comment by semoal** [comment]
If I understood you correctly, you could use the t macro directly with the id of your json file.

```
t({ id: 'myName', message: `My name is ${name}` })
```
And that will generate a key myName but the message will be the complete one.

Does it work? :)

**Comment by zsolt-dev** [comment]
Hi @semoal,

I do not think we understand each other :) 

Imagine 2 files:

segments.json (or whatever other format you support):
```
{
  "login": "Log in",
  "loginText": "To log in to {{siteName}} please enter  ...some long text...."
}
```

And now you want to use these segments in javascript like this:
```
<h1>{t('login')}</h1>
<p>{t(loginText, {siteName: 'example.com'})}</p>
```

So again, I do not have the full segment texts in the code, just the IDs. So I do not "extract" segments, but create them directly in webtranslateit.

If lingui supports this, please provide a code how to achieve this. Thank you
