### ISSUE TITLE
Macros not working with latest ViteJS(ICEJS)

### ISSUE THREAD

**Issue by usercao** [lingui/js-lingui#1193]
**Describe the bug**
The macro stopped working with ICEJS ^2.0.0.

**To Reproduce**
Simply start with a bank ICEJS project, follow Lingui's implementation details and add the macros. Import any macro into a component.

```ts
import { t } from '@lingui/macro';

export default function App() {
   return <p>{t`hello word`}</p>
}
```

**Expected behavior**
Macros should work correctly.

**Additional context**
ICEJS is unable to compile the page with error:

- jsLingui version `3.13.0`
- Babel version `7.16.7`

**The following error occurs when executing `yarn lingui extract`**
![image](https://user-images.githubusercontent.com/13760476/149126743-6dcbbe04-d0bc-481a-82fa-8bf243bcb5d0.png)

**Here's there repo: [https://github.com/usercao/ice-test](https://github.com/usercao/ice-test)**

**Comment by semoal** [comment]
Didn't know about ice framework. But I guess they migrated to SWC or something similar, and they don't use babel anymore.

Check it out, because Lingui needs babel and babel-plugin-macros. If you see the errors the TypeScript files are not even transformed.

**Comment by semoal** [comment]
If you create a `babel.config.js`:

```js
module.exports = (api) => {
  api.cache(true);
  return {
    plugins: ['macros'],
    presets: ['@babel/preset-typescript'],
  }
}
```

And you install these dev dependencies, will work as expected. For sure that they removed under the hood babel. :)

**Comment by semoal** [comment]
> 

I've tried creating the babel.config.js and works fine so far. Give it a try, instead of using the ice-js config.

**Comment by usercao** [comment]
Are you using the `ice-test` added by the repo I provided? I tried and it doesn't work.

**Comment by semoal** [comment]
> Are you using the `ice-test` added by the repo I provided? I tried and it doesn't work.

```bash
> mexo-web@0.1.0 i18n:extract /Users/sergio.moreno/OSS/ice-test
> lingui extract --clean

Catalog statistics for /Users/sergio.moreno/OSS/ice-test/src/locales/{locale}/messages:
┌────────────────┬─────────────┬─────────┐
│ Language       │ Total count │ Missing │
├────────────────┼─────────────┼─────────┤
│ en-US (source) │      1      │    -    │
│ es-ES          │      1      │    1    │
│ pt-BR          │      1      │    1    │
│ zh-CN          │      1      │    1    │
└────────────────┴─────────────┴─────────┘

(use "npm run i18n:extract" to update catalogs with new messages)
(use "npm run i18n:compile" to compile catalogs for production)
```

Add as dev dependency also babel-plugin-macros.

**Comment by usercao** [comment]
@semoal Thank you very much for your patient answer. After joining `babel.config.js`, you can run `yarn lingui extract --clean` but not `yarn start`. Now I understand that it should be the problem of `icejs`, thank you again.
