### ISSUE TITLE
unable to load resources with create-react-app v5

### ISSUE THREAD

**Issue by ggascoigne** [lingui/js-lingui#1195]
**Describe the bug**

I'm upgrading a working app from create-react-app v4 to v5, the largest change being the switch over to webpack 5.

When my app tries to load the resource bundle, the UI gets provided with a file containing this:

```js
"use strict";
(self["webpackChunkui"] = self["webpackChunkui"] || []).push([["node_modules_lingui_loader_index_js_src_locale_en_messages_po"],{

/***/ "./node_modules/@lingui/loader/index.js!./src/locale/en/messages.po":
/*!**************************************************************************!*\
  !*** ./node_modules/@lingui/loader/index.js!./src/locale/en/messages.po ***!
  \**************************************************************************/
/***/ (function(module, __unused_webpack_exports, __webpack_require__) {

module.exports = __webpack_require__.p + "static/media/messages.5e780017f58fa35eb312.po";

/***/ })

}]);
```

The equivalent file with webpack 4 used to have that embedded `__webpack_require__` replaced by a map of messages.

**To Reproduce**

The same bug is easily reproducible by upgrading the CRA example in this repo. Upgrade react-scripts from 4.0.0 to 5.0.0, it runs, but displays a 'Messages for locale "en" not loaded.' message and also fails to load the Czech message strings.

**Comment by ggascoigne** [comment]
FYI injecting

```
{
  test: /\.po/,
  use: [
    {
      loader: '@lingui/loader',
     },
  ],
},
```

into the webpack loaders fixes the problem. I'm using patch-package for this, but I expect that you could also use craco.

**Comment by tommie-lie** [comment]
I found another solution using webpack's [inline match-resource](https://webpack.js.org/api/loaders/#inline-matchresource) syntax. Unfortunately, webpack doesn't support this syntax in combination with variables, so you have to write out all different import paths explicitly, which may become unfeasible with many languages. But at least this does not require craco or patch-package.

```javascript
async function importMessages(locale: string) {
    switch (locale) {
        case "cs":
            // @ts-ignore
            // eslint-disable-next-line import/no-webpack-loader-syntax
            return await import("messages.js!=!@lingui/loader!./locales/cs/messages.po");
        case "en":
        default:
            // @ts-ignore
            // eslint-disable-next-line import/no-webpack-loader-syntax
            return await import("messages.js!=!@lingui/loader!./locales/en/messages.po");
    }
}

/**
 * We do a dynamic import of just the catalog that we need
 * @param locale any locale string
 */
export async function dynamicActivate(locale: string) {
    const {messages} = await importMessages(locale);
    i18n.load(locale, messages)
    i18n.activate(locale)
}
```
