### ISSUE TITLE
Message context (msgctxt) not working

### ISSUE THREAD

**Issue by tfhult** [lingui/js-lingui#1198]
**Describe the bug**
When providing context to a message, the context is treated like an ID in the generated `en.po` file.

**To Reproduce**
With the version `3.13.1` with `create-react-app`, and not specifying `orderBy` in `lingui.config.js`:

```js
import { Trans } from "@lingui/react"

export default function App() {
  return <div>
    <Trans context='ctxtA'>My string</Trans>
    <Trans context='ctxtB'>My string</Trans>
    <Trans>My string</Trans>
  </div>
}
```

**Expected behavior**
3 messages should be created in the generated `en.po` file, like this:
```po
#: src/App.tsx:11
msgid "My string"
msgstr "My string"

#: src/App.tsx:12
msgctxt "ctxtA"
msgid "My string"
msgstr "My string"

#: src/App.tsx:13
msgctxt "ctxtB"
msgid "My string"
msgstr "My string"
```

**Actual behavior**
This is created in the `en.po` file.
```po
#: src/App.tsx:11
msgid "My string"
msgstr "My string"

msgid "ctxtA"
msgstr "ctxtA"

msgid "ctxtB"
msgstr "ctxtB"
```

**Additional context**
If using `orderBy: 'origin'` in `lingui.config.js`, an exception is thrown in `getFirstOrigin()` when running `extract`.

- jsLingui version ``3.13.1``
- Using `create-react-app`

**Comment by semoal** [comment]
Thanks, I'll try to fix as soon as I can. Contributions are welcome =)

**Comment by JSteunou** [comment]
@semoal I started https://github.com/lingui/js-lingui/pull/1205

For now all I succeed to do is adding more tests to find out where the issue might be. With my little knowledge on lingui's internal, it seems the 1st implementation is wrong: context is used as message way to early in the chain. The *context* information does not arrive at the catalog build step. I added failing tests that shows this. Catalog to PO is fine according to other tests.

With extracted catalog in JS the issue does not pop-up, but for every intermediate or final format other than JS this is broken I think.

**Comment by JSteunou** [comment]
@nakkamarra if you have some time to put on this one I would appreciate ;)

**Comment by JSteunou** [comment]
Can anybody help me on this one plz?

**Comment by semoal** [comment]
Will find time this week Jérôme, sorry 4 the delay, been really busy

**Comment by JSteunou** [comment]
@semoal I will have a bit a free time next month but I still need help / guidance on this one 

This is a very nice and awaited feature, let's make it work :)

**Comment by JSteunou** [comment]
Do you have any time soon @semoal or @tricoder42  to help me on this one (at least re-open it, and the MR and prevent stale bot to close it again (about that, you might want to config the bot so it does not close qualified issues)

This is really painful when using PO files

**Comment by tfhult** [comment]
I've verified that the issue remains with version `3.14.0`. Would be great to get it working!

**Comment by semoal** [comment]
Yes, I do. I’ll take care of everything at the end of this week

**Comment by JSteunou** [comment]
Any news @semoal ?

**Comment by JSteunou** [comment]
@semoal or anyone managing this repository, please prevent stale bot to close this issue, the related PR took days of effort, and we really like to see it integrated into linguijs instead of going with a fork.

**Comment by JSteunou** [comment]
Seriously? Is this project that much dead?

**Comment by fdev** [comment]
> Seriously? Is this project that much dead?

I've been subscribed to this issue for a long time and I'm disappointed as well. If there is a working fix ready to be reviewed it should not take this long, and the issue should definitely not get autoclosed for being stale. Does stale mean a lack of interest from the community, or lack of response from the maintainers?

**Comment by yanndinendal** [comment]
Workaround in the mean time:

```jsx
import { Trans } from "@lingui/react"

export default function App() {
  // Workaround for translation context
  // until https://github.com/lingui/js-lingui/issues/1198
  // is fixed.
  const ctxtA = '';
  const ctxB = '';
  return <div>
      <Trans>{ctxtA}My string</Trans>
      <Trans>{ctxtB}My string</Trans>
      <Trans>My string</Trans>
  </div>
}
```
=>
```gettext
#: src/App.tsx:11
msgid "My string"
msgstr "My string"

#: src/App.tsx:12
msgid "{ctxtA}My string"
msgstr "{ctxtA}My string"

#: src/App.tsx:13
msgid "{ctxtB}My string"
msgstr "{ctxtB}My string"
```

for example, it could allow to have two keys for `Disabled` and `{keys}Disabled`:
`Désactivé` / `Désactivées`.

**Comment by JSteunou** [comment]
That is what we used to do before forking and publishing it as a PR, but it does not work well with plural and / or variables. Try using `[ctxtA]` instead.

**Comment by thekip** [comment]
😬 context implementation is almost ready, stay tuned )
