### ISSUE TITLE
Missing "beforeChange"-event

### ISSUE THREAD

**Issue by benbender** [lingui/js-lingui#1200]
I just want to start to dynamically load my translations. I thought I could simply hook into the "change" event and import my message-catalog from there. I was missing that this event is propagated **after** the locale is set. Therefor the messages are missing while setting the new locale in `i18n` and my plan failed miserably... ;) 

**Describe proposed solution**
I would love to have an event which fires on `i18n.activate(locale)`, but before the locale is internally actually set. This would enable dynamic message-loading inside the i18n-context without the need for custom methods or similar.

PS: Thanks for the work on `linguijs` - love it! <3

**Comment by semoal** [comment]
Hi! :)
What do you mean by dynamically? We already offer a plugin for Webpack that creates chunks on demand given a locale.

**Comment by benbender** [comment]
Hey :)

I want to import locales dynamically via `await import("../locales/$locale/messages.js")` for codesplitting. Building is done on pr by weblate.

**Comment by semoal** [comment]
https://github.com/lingui/js-lingui/blob/main/examples/create-react-app/src/i18n.ts#L20
https://lingui.js.org/guides/dynamic-loading-catalogs.html
Check this out, we offer a plugin that loads dynamically any catalog, even the .po ones are transformed on the fly.

I'm sure that you don't need the event, https://github.com/lingui/js-lingui/blob/main/examples/create-react-app/src/App.tsx#L17

**Comment by JSteunou** [comment]
clearly you do not need an event, just load & activate your locales when you need to. Here is an example from my code (way before the dynamic loads was introduce in linguijs, which is another solution)

```ts
export async function dynamicActivate(i18n: I18n, locale: SupportedLanguages) {
    const {messages} = await import(`../locales/${locale}/messages.po`)
    i18n.load(locale, messages)
    i18n.activate(locale)
}
```

**Comment by benbender** [comment]
Some more context: I'm using `LinguiJS` in a monorepo-setup and it generally works amazingly! I'm aware of the `build your own helper and drag it around`-solution, but its impractical in my case, as I would need to redefine it in every package as the paths are not stable. Additionally I liked the idea of simply calling `i18n.activate(locale)`and using a hook without any additional methods/functions/code.

**Comment by benbender** [comment]
yes, exactly. And thats why I could have the other parts (f.e.) in a common-package in a monorepo-setup and just relying on the event locally.

**Comment by JSteunou** [comment]
Then you can do this abstraction on your side. If your common base code is able to start the change logic on i18n object but is missing the catalog, you could make your own eventemitter from this base that would wait for a reponse from specific package that would return the loaded catalog to helper the common part activate the lang. 

2 keys, own i18n instance + dependencies injection

**Comment by benbender** [comment]
Sure. But may I ask why my suggestion doesn't seem to be even considered? I for one would think that some kind of more elaborated event-system could benefit the developer experience enormously and the event-system is already in place, so the increase in pkg-size would be negligible. Am I missing smth?

**Comment by JSteunou** [comment]
I'm no maintainer of linguijs so I was just trying to help you in case you were stuck, that's all :) And because I was also like @semoal quite sure you do not need this event. (You can go with an event oriented solution, but I'm pretty sure you can do without and with better and more readable code)

Feel free to post a MR without your solution and your use case, I'm very curious about this solution. If I'm wrong I would be the 1st to support it and use it because I think I have a similar use case (That I solved by doing the less copy / paste I could do, code quoted just above, and it's fine by me)

**Comment by benbender** [comment]
Basically: these two lines would enable:
````ts
diff --git a/packages/core/src/i18n.ts b/packages/core/src/i18n.ts
index 49538b62..e00e1378 100644
--- a/packages/core/src/i18n.ts
+++ b/packages/core/src/i18n.ts
@@ -53,6 +53,7 @@ type setupI18nProps = {

 type Events = {
   change: () => void
+  beforeActivate: (locale: string) => void
   missing: (event: MissingMessageEvent) => void
 }

@@ -148,6 +149,8 @@ export class I18n extends EventEmitter<Events> {
   }

   activate(locale: Locale, locales?: Locales) {
+    this.emit("beforeActivate", locale)
+
     if (process.env.NODE_ENV !== "production") {
       if (!this._messages[locale]) {
         console.warn(`Messages for locale "${locale}" not loaded.`)
````

something like:
````ts
import "lingui-example/styles.css"
import { useEffect } from "react"
import { I18nProvider } from "@lingui/react"
import { i18n } from "@lingui/core"
import { en, cs } from "make-plural/plurals"

i18n.loadLocaleData("en", { plurals: en })
i18n.loadLocaleData("cs", { plurals: cs })

i18n.on("beforeActivate", async (locale) => {
  const { messages } = await import(`../locale/${locale}/messages.po`)
  i18n.load(locale, messages)
})

export default function Page({ Component, pageProps }) {
  useEffect(() => {
    // Activate the default locale on page load
    i18n.activate("en")
  }, [])

  return (
    <I18nProvider i18n={i18n}>
      <Component {...pageProps} />
    </I18nProvider>
  )
}
````

It removes the need for the external function which is needed to bind `i18n.activate()` and `i18n.load()` together. Now you can simply import the global `18n`-object and call `.activate(locale)`

**Comment by JSteunou** [comment]
@benbender ok now I see, thank you for the example. 

But will it work? I mean `activate` is sync, event is sync, but your import + load part is async. That's why I'm using a helper to

1. await async import
2. load
3. activate

**Comment by vonovak** [comment]
Hello 👋 
so I read through the whole thing and here are my observations:

First, it's tempting to write a quick feature request for some issue that a developer encounters. However, if the feature request is not carefully written, and offers enough details on what problem it's trying to solve and how, and why something is a problem in the first place, then it's hard to have a discussion.

Here's why I don't think the proposal is a good way forward:

1) Seems like the whole problem can be solved with a function like this

```
export function loadAndActivate(i18n: I18n, locale: SupportedLanguages, messages: Record<string, string>) {
    i18n.load(locale, messages)
    i18n.activate(locale)
}
``

which is a variation from https://github.com/lingui/js-lingui/issues/1200#issuecomment-1020003814 but at the same time, it avoids the import because the OP will import messages from different places and therefore with different import paths.

it can be used like this:

```
const {messages} = await import(`../locales/${locale}/messages.po`)
loadAndActivate(...)
```

It's true that still means that the `const {messages} = ...` part needs to be duplicated across the monorepo packages which the OP wanted to avoid, but how many times does it need to be duplicated? In another words, how many packages are in the monorepo? Maybe 5 if not less? It's better to have a tiny bit of duplication in user land rather than introduce a new api to a library.

2) the proposed change https://github.com/lingui/js-lingui/issues/1200#issuecomment-1020387456 has an issue: it calls:

```
i18n.activate("en")
...
const { messages } = await import(`../locale/${locale}/messages.po`)
i18n.load(locale, messages)
```

the problem with this is that the `I18nProvider` will re-render both with activate() and load() calls which take place with a delay in between them because of the async import. Rather than re-rendering twice (the first re-render is useless because no new messages are present), we need to change the order to 

```
const { messages } = await import(`../locale/${locale}/messages.po`)

i18n.load(locale, messages)
i18n.activate("en")
```

which will result in one re-render only. Exactly as said in https://github.com/lingui/js-lingui/issues/1200#issuecomment-1021086930

3) The proposal wants to add a new api which is always a burden on maintenance while it (imho) doesn't provide strong reasons to do so. I believe the `load()` and `activate()` sequence is pretty straightforward, imperative way to do a locale change and doing this via some event listener is an unnecessary indirection. 

Thanks 🙂

**Comment by andrii-bodnar** [comment]
@vonovak thanks for the detailed analysis of the problem here! Totally agree with you and also don't see a good reason in introducing this new API. Moreover, in the case when it can be achieved in a pretty straightforward way on the user's side.
