### ISSUE TITLE
Variables within JS/JSX macros are not substituted

### ISSUE THREAD

**Issue by 0xJem** [lingui/js-lingui#1201]
**Describe the bug**

We have tried a few approaches to using the JS/JSX macros in a way that replaces variables, but have not found one that works. Instead, "{0}" is displayed in place of the variable in the production build.

**To Reproduce**

The following have been attempted:
```
{t`Your current Staked Balance is ${getSOhmBalance().toFixed(2)} sOHM`}
```
```
<Trans>Your current Staked Balance is ${getSOhmBalance().toFixed(2)} sOHM</Trans>
```
```
const sOhmBalance = getSOhmBalance().toFixed(2);
...
{t`Your current Staked Balance is ${sOhmBalance} sOHM`}
```

**Expected behavior**

According to the docs (https://lingui.js.org/tutorials/react-patterns.html), this should work!

**Additional context**

lingui versions:
```
    "@lingui/cli": "^3.13.0",
    "@lingui/core": "^3.13.0",
    "@lingui/macro": "^3.12.1",
```

If anyone would like to look at the configuration, this is the project: https://github.com/OlympusDAO/olympus-frontend

**Comment by djhojd** [comment]
I had the same issue, make sure you are loading the compiled message catalogs in production.

**Comment by 0xJem** [comment]
@djhojd Hi, thanks for the response! I read about passing catalogs as a parameter to `I18nProvider`, but we are using a different approach (the one documented here: https://lingui.js.org/guides/dynamic-loading-catalogs.html#final-i18n-loader-helper), and I don't see a way to achieve the same.

In the meantime, I've been able to reproduce the issue reliably and have documented this in our repo: https://github.com/OlympusDAO/olympus-frontend/issues/1430

**Comment by 0xJem** [comment]
So I think I've figured out the cause of this. We didn't run the lingui extract command, so the `.po` files did not contain the interpolated string. Doing the same (not running `extract`) with a non-interpolated string not containing a variable, it loads fine.
