### ISSUE TITLE
Inconsistent numbers localisation in different runtimes (node and chrome)

### ISSUE THREAD

**Issue by daryawood** [lingui/js-lingui#1203]
**Describe the bug**
 
`i18n.number(1)` with locale "ar" returns different results depending on runtime.

node@14.8.0

```javascript
> i18n.number(1)
> ١
```

Chrome console (96.0.4664.110)
```javascript
> i18n.number(1)
> 1
```

**To Reproduce**
You can run the following commands in a chrome's console and in node@14 runtime to see the difference

```
Intl.NumberFormat('ar').format(1) 
Intl.NumberFormat('ar-EG').format(1)
```

**Expected behavior**
Arabic numerals should be translated correctly everywhere

**Additional context**

- jsLingui version ``3.13.2``

The issue is with the locale format, the library uses (or at least it's seen everywhere through the docs) two symbols for locales. Under the hood the function `number` uses `Intl.NumberFormat` that works inconsistently with "ar" locale.

For example, if you run `Intl.NumberFormat('ar').format(1)` in a browser's console or in a node runtime, it'll show different results.

[MDN in examples uses `ar-EG` locale](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat#using_locales) that works consistently and returns a localised number.

**And a question :)**

Maybe it's expected behaviour and not a bug. Would you recommend switching to BCP 47 Language Tags (language and region)?

**Comment by dlcwalkoff** [comment]
Why it was closed? Proble still there, reopen issue!

**Comment by etx121** [comment]
Hello,

As @daryawood mentionned, I still got an issue with Arabic numbers in the locale `ar` as she described.
And also, `ar-EG` doesn't face this issue.
It has not been fixed unfortunately.
Can you check that?
I will for the moment change the locale to another regional arabic, as `ar` seems buggy.

Best regards,

**Comment by timofei-iatsenko** [comment]
it's inconsistency between node and browser implementation. Use full bcp-47 locale (eg ar-EG) to overcome the issue.

There is nothing to do on the lingui side. Thanks for understanding.

**Comment by etx121** [comment]
Hello @timofei-iatsenko ,

Thanks for the quick reply.
