### ISSUE TITLE
Problem with fallback locales

### ISSUE THREAD

**Issue by xelossan** [lingui/js-lingui#1207]
Hi, not sure if it's a bug, just the way it works or I'm using it wrong, but I have a problem with fallback locales (I'm using @lingui/react 3.13.2).

I have following config file:
```json
{
  "locales": [
    "pl",
    "en",
    "pseudo"
  ],
  "pseudoLocale": "pseudo",
  "sourceLocale": "pl",
  "fallbackLocales": {
    "default": "pl"
  },
  "catalogs": [
    {
      "path": "src/locales/{locale}",
      "include": [
        "src"
      ]
    }
  ],
  "format": "minimal"
}
```
and strings defined for pl and en locales.

My initialization code looks like this:
```js
import { messages as plMessages } from '../locales/pl';
import { messages as enMessages } from '../locales/en';
import { messages as pseudoMessages } from '../locales/pseudo';

i18n.load({
  'pl': plMessages,
  'en': enMessages,
  'pseudo': pseudoMessages
});
```

Now, when the user's locale is for example pl-pl, or en-us, I assumed that calling `i18n.activate('pl-pl')` will use strings defined for pl locale, and `i18n.activate('en-us')` will use en or default fallback language, so in my case: pl. Instead, message IDs are displayed instead of actual messages, and only passing pl or en to activate function works correctly.

That's how I'm displaying the text if that matters somehow:
```js
import { t } from '@lingui/macro';

t({ id: 'Verification.List.Status.Succeeded' })
```

Am I missing something?

**Comment by MichaelHoste** [comment]
Hi @xelossan 

Shouldn't your list of locales in your config file also include "pl-pl" and "en-us" for the `i18n.activate` to work?
