### ISSUE TITLE
Lingui extract all translations for files that are outside of the root of the rootDir

### ISSUE THREAD

**Issue by paales** [lingui/js-lingui#1211]
**Describe the bug**
When extracting translations, we're running into the issue that we're missing lots of translations

**To Reproduce**

I've got this in our configuration

```
    catalogs: [
      {
        path: 'locales/{locale}',
        include: ['<rootDir>/**/*.tsx', '<rootDir>/../../packages/**/*.tsx'],
      },
    ],

```

So we're also gathering translations from `'<rootDir>/../../packages/**/*.tsx'`. This however somewhat works, but there seems to be going something wrong while writing temporary files in the babel-plugin-extract-messages package.

**Expected behavior**
It supports collecting translations from outside the root directory.

**Additional context**

https://github.com/lingui/js-lingui/blob/main/packages/babel-plugin-extract-messages/src/index.ts#L358

The problem is that the relative baseDir resolves to the root, so if two files have the same name, it will overwrite the file.

If I just create a random string for the file, it does extract everything.

This doesn't completely solve the issue as the file path comments in .po files don't actually work (but I'm not using that functionality)

My patch that makes it work:

```patch
diff --git a/node_modules/@lingui/babel-plugin-extract-messages/index.js b/node_modules/@lingui/babel-plugin-extract-messages/index.js
index 86d76c8..90cbf8d 100644
--- a/node_modules/@lingui/babel-plugin-extract-messages/index.js
+++ b/node_modules/@lingui/babel-plugin-extract-messages/index.js
@@ -371,7 +371,7 @@ function _default(_ref2) {
       var messages = file.get(MESSAGES);
       var catalog = {};
 
-      var baseName = _path.default.basename(filename);
+      var baseName = Math.random().toString(36).slice(2);
 
       var catalogFilename = _path.default.join(targetDir, "".concat(baseName, ".json"));
 

```

**Comment by paales** [comment]
Not stale

**Comment by semoal** [comment]
Thanks for the issue @paales , will try to take a look this week

**Comment by thekip** [comment]
Fixed by https://github.com/lingui/js-lingui/pull/1358 would be released in v4.
