### ISSUE TITLE
Document lingui.config.js format

### ISSUE THREAD

**Issue by marcvangend** [lingui/js-lingui#1216]
**Situation**
I prefer `lingui.config.js` over `.linguirc` for configuration because my IDE knows the .js file extension. However I could not find the expected syntax in the documentation. 

**Proposed solution**
Document that a lingui.config.js file should look like this (at least: this worked for me!)

```js
module.exports = {
  locales: ['en', 'cs', fr],
  sourceLocale: 'en',
  catalogs: [
    {
      path: 'src/locales/{locale}/messages',
      include: ['src'],
    },
  ],
  format: 'po',
};
```

**Alternatives I've considered**
To solve the problem that IDE's do not interpret `.linguirc` as json, Lingui could also add support for a `lingui.config.json` filename. However this would not replace the need for `lingui.config.js` documentation.

**Comment by JSteunou** [comment]
You mean this  https://lingui.js.org/ref/conf.html ?

**Comment by marcvangend** [comment]
> You mean this https://lingui.js.org/ref/conf.html ?

I'm not quite sure what you're asking. Indeed I think that's the documentation page that could be improved. However, currently that page does not contain the documentation I was looking for. 

Specifically, in the example above the `module.exports =` part is crucial, but undocumented.

**Comment by semoal** [comment]
It's obvious that if is a javascript file you must export the configuration somehow, that happens on every configuration file from eslint to babel... Not necessary to document something when it's trivial and it's already in JSON which is the default/first try it does the compiler.

**Comment by marcvangend** [comment]
> you must export the configuration somehow

Somehow... well that's exactly the point, isn't it? You must export the configuration, but how **exactly**? It could be `module.exports = {}`, `module.exports.config = {}`, `const config = {}; export default config`, `export const config = {}`...

If it were obvious to me, I wouldn't have created this issue. But I understand that you cannot let the stupidity of the users dictate if something should be documented. After all, documentation is only intended for the maintainers. I'm happy it's all trivial and obvious to you, so congratulations: you must be a superior human being and I am not worthy to stand in your shadow.
