### ISSUE TITLE
V3 't' macro's still not seem to be working in 3.13.2

### ISSUE THREAD

**Issue by boy-incerta** [lingui/js-lingui#1218]
**Describe the bug**
As per [#707](https://github.com/lingui/js-lingui/issues/707) It still looks like V3 t macro's don't work anymore. I have used [this reproducible example](https://github.com/ojii/lingui-v3-t-macro-example) and tried what @tricoder42  suggested (move components to other file). This had no luck. I also tried changing the messages to local data to exclude async loading of locale files as the root cause of the issue.

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:
https://github.com/boy-incerta/lingui-v3-macro-issue

**Expected behavior**

After using the language switcher, I would expect both macro's to have changed. However, only Trans works.

**Additional context**

- jsLingui version 3.13.2
- Babel version 7.17.5
- Create React App, Vite

**Comment by creaux** [comment]
I can confirm exactly the same problem.

- jsLingui 3.13.2
- babel 7.12.13
- @nrwl/react 13.8.5
- react 17.0.2
- webpack 5.70.0

Did you try so far some other version working or some other workaround?

**Comment by JSteunou** [comment]
You might have an issue with your babel and / or lingui config because multiple project here, some with latest lingui / babel / webpack version, some others not very up to date, and all working fine.

**Comment by Hideman85** [comment]
I have a similar problem. The compiled code out of webpack fails with `ReferenceError: t is not defined`

With webpack should I use the old babel plugins from 2.9.2 or the use of babel-plugin-macros is enough? I'm bit confused here and the doc is also confusing on this point :(

<details>
<summary>Full .babelrc config for webpack babel-loader</summary>

```js
{
  test: /\.(js|mjs|jsx|ts|tsx)$/,
  include: paths.appSrc,
  loader: require.resolve('babel-loader'),
  options: {
    customize: require.resolve(
      'babel-preset-react-app/webpack-overrides'
    ),
    presets: [
      require.resolve('@babel/preset-env'),
      [
        require.resolve('babel-preset-react-app'),
        {
          runtime: 'classic'
        }
      ]
    ],
    plugins: [
      //  Required stuff
      [require.resolve('@babel/plugin-proposal-class-properties'), { loose: true }],
      [require.resolve('@babel/plugin-proposal-private-methods'), { loose: true }],
      [require.resolve('@babel/plugin-proposal-private-property-in-object'), { loose: true }],
      //  Ant Design
      [require.resolve('babel-plugin-import'), {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true
      }],
      //  Lingui
      require.resolve('babel-plugin-macros'),
      //  Bundleing
      require.resolve('babel-plugin-dynamic-import-node'),
      require.resolve('babel-plugin-remove-webpack'),
      isEnvDevelopment && useReactRefresh && require.resolve('react-refresh/babel')
    ].filter(Boolean),
    // This is a feature of `babel-loader` for webpack (not Babel itself).
    // It enables caching results in ./node_modules/.cache/babel-loader/
    // directory for faster rebuilds.
    cacheDirectory: true,
    // See #6846 for context on why cacheCompression is disabled
    cacheCompression: false
  }
},
```

</details>

Would appreciate to have some helps here and could be valuable to update the doc for this subject thanks :)
