### ISSUE TITLE
CLI: Ignore empty defaults

### ISSUE THREAD

**Issue by lzurbriggen** [lingui/js-lingui#122]
I use IDs for my phrases, but I get an error when I try to extract in situations like these:

```
<SomeElement title={i18n.t`shop.calculator.subtotal`}>
    <Trans id="shop.calculator.subtotal">Subtotal</Trans>
</SomeElement>
```
The error message is `Different defaults for the same message ID.` which makes sense, as the first phrase is provided without a default. As a workaround I just omit the default of the Trans component, but that doesn't seem ideal to me.

Would it be possible to basically ignore empty defaults and consider defaults even if the are not provided in the first occurence of the phrase?

**Comment by tricoder42** [comment]
@lzurbriggen Absolutely! I designed jsLingui for natural language as IDs and added custom IDs later. Missing support for defaults in `i18n.t` tag is one evidence of it.

Fix coming soon.

**Comment by tricoder42** [comment]
Fixed in:
 - babel-plugin-lingui-extract-messages@1.1.7
 - lingui-cli@1.3.14
