### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by ptmkenny** [lingui/js-lingui#1223]
**Is your feature request related to a problem? Please describe.**
React 18 was released on March 29, 2022 and is the latest release of React.  Details: https://reactjs.org/blog/2022/03/29/react-v18.html

**Describe proposed solution**
Add support for React 18.  This may be as simple as adding "18" as an option to the dependencies; I tried installing lingui with react 18 using `npm update --force` and it seems to work OK.

**Comment by nftgeek** [comment]
Does lingui officially support React 18 now?

**Comment by ericvera** [comment]
@nftgeek  I just ran into an issue with the type of I18nContext that #1231 seems to suggest may be due to changes in React 18 types.

**Comment by semoal** [comment]
Commited the fix for peer dependencies https://github.com/lingui/js-lingui/commit/2a235baa093d668a0a029ec6c683e9dc00f68f42 and merged the branch that fixes the TypeScript problem with children.

Will release a new version at the end of today, thanks everyone for the patience =)

**Comment by semoal** [comment]
Just released 3.13.3 with the according fix. Enjoy! 🥳
