### ISSUE TITLE
Built PO file generates wrong comments

### ISSUE THREAD

**Issue by niksauer** [lingui/js-lingui#1228]
**Describe the bug**
The output PO file has comments with a leading period:

```
#. Your free trial will end on August 6th and will not renew.
#: src/components/routes/billing/Status/Status.tsx:56
msgid "and will not renew."
msgstr ""
```

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```typescript
import { t } from "@lingui/macro"

const renewLabel = t({
        message: ` and will not renew.`,
        comment: 'Your free trial will end on August 6th and will not renew.',
})
```

**Expected behavior**
The output Po file should use standard comments:

```
# Your free trial will end on August 6th and will not renew.
#: src/components/routes/billing/Status/Status.tsx:56
msgid "and will not renew."
msgstr ""
```

**Additional context**

- jsLingui version ``3.13.2``
- react-scripts version `4.0.3`

**Comment by semoal** [comment]
Hm, that's strange yep, will take a look

**Comment by ScriptedAlchemy** [comment]
im also running into this issue with next.js based applications (Still using babel)

**Comment by Martin005** [comment]
Hello @niksauer 🙂
According to the [documentation of PO format](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html), a line starting with
`# `
is a translator comment which is `created and maintained exclusively by the translator`.

A line starting with
`#. `
is a comment `given by the programmer, directed at the translator`.

So our output conforms to the PO format specification.

However, the current behaviour is not consistent with our documentation. I have created a pull request #1337 that fixes the documentation 🙂
