### ISSUE TITLE
Any suggestions for unit-testing with Lingui?

### ISSUE THREAD

**Issue by delanni** [lingui/js-lingui#1229]
I'm rewriting a big chunk of our monorepo to use v3 instead of v2.
It's not been a blast changing many packages but it's gotten really bad when I started fixing unit tests.

In v2 the `Trans` tag was not working with hooks and didn't throw an error when there wasn't a provider around to get the lingui context from. Since v3, this is now a must.

```
    useLingui hook was used without I18nProvider.
```

Now you can imagine, there are component-level unit tests by the hundreds, and very few of them provide an i18n context (`I18nProvider`) because let's face it, we don't really care much about whether translations work or not on a unit level, it's a horizontal feature. 

Is there are recommendations as to how to deal with unit-testing, if we don't really want to go down the route of wrapping every shallow-rendered, mounted component into an `I18nProvider` in every test case?

Could we have a fallback to a context where the message ID is the rendered text, instead of an error?

**Comment by daniel-rodrigue** [comment]
For my project, I decided to mock lingui for the same reasons. So I created a few mock files:
`src/__mocks__/@lingui/core.js`, `src/__mocks__/@lingui/react.js` and `src/__mocks__/@lingui/detect-locale.js`.

You can add tests/asserts in these mocks if you also want to verify your usage of lingui. 

@lingui/core.js:
```
const
  i18n = {
    load: () => {},
    loadLocaleData: () => {},
    activate: () => {},
    _: ({ message, values }) => (message ? message.replace(/{([A-Za-z0-9]+)}/g, (str, prop) => values[prop]) : "")
  };
export { i18n };
```
@lingui/react.js:
```
const
  Trans = function ({ id }) {
    return id;
  },
  I18nProvider = function ({ children }) {
    return children;
  };
export { Trans, I18nProvider };
```

@lingui/detect-locale.js:
```
const
  detect = () => ("en"),
  fromUrl = () => (null),
  fromNavigator = () => (null);
export { detect, fromUrl, fromNavigator };
```

**Comment by semoal** [comment]
> Could we have a fallback to a context where the message ID is the rendered text, instead of an error?

This sound quite interesting, will think in the implications of this change as soon as possible and work on that direction.

**Comment by treshugart** [comment]
Was there any movement on this, or rationale for not doing? Seems fairly common to output strings as-is in tests, anyways, and would help ease migration pain in large codebases. If folks are worried about correct integration, a small suite that uses the provider would be easy to write. This should probably be done anyways, as there's a lot of setup involved.
