### ISSUE TITLE
'Trans' cannot be used as a JSX component. 

### ISSUE THREAD

**Issue by usercao** [lingui/js-lingui#1236]
**Describe the bug**
```txt
'Trans' cannot be used as a JSX component.
  Its return type '"symbol" | "object" | "hr" | "s" | Element | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | ... 158 more ... | FunctionComponent<...>' is not a valid JSX element.
    Type '"symbol"' is not assignable to type 'Element | null'.ts(2786)
```

**To Reproduce**
```ts
import { t, Trans } from '@lingui/macro';

<Trans>hello</Trans>
<p>{t`world`}</p>
```

**Expected behavior**
`<Trans/>` is supposed to be a component.

**Additional context**
[https://github.com/usercao/ice-test/blob/main/src/pages/Home/index.tsx#L22](https://github.com/usercao/ice-test/blob/main/src/pages/Home/index.tsx#L22)

- jsLingui version:
```txt
"@lingui/cli": "^3.13.3",
"@lingui/core": "^3.13.3",
"@lingui/macro": "^3.13.3",
```

**Here's there repo:**
[https://github.com/usercao/ice-test](https://github.com/usercao/ice-test)

**Relevance problem:** #801

**Comment by paales** [comment]
You are mixing the @types/react version in your project. 

This solved it for us:

```
  "resolutions": {
    "@types/react": "17.0.44"
  }
```
