### ISSUE TITLE
Module '"@lingui/macro"' has no exported member 'defineMessage'.

### ISSUE THREAD

**Issue by ThomasSalty** [lingui/js-lingui#1251]
**Describe the bug**
Wanted to try out the `defineMessage` macro in a React/Typescript project but received this error message from my IDE (vs code):
`Module '"@lingui/macro"' has no exported member 'defineMessage'.`

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```
import { defineMessage, Trans } from '@lingui/macro'
```

**Expected behavior**
Not receiving that error message. Please note that importing `t` or `Trans` does not produce this error message.

**Additional context**

- jsLingui version ``lingui --version``: 2.8.3
- Babel version ``npm list @babel/core``:
```
+-- @babel/core@7.5.5
+-- babel-jest@24.8.0
| `-- @jest/transform@24.9.0
|   `-- @babel/core@7.17.9
`-- jest@24.7.1
  `-- jest-cli@24.9.0
    `-- jest-config@24.9.0
      `-- @babel/core@7.17.9
```
- Your Babel config (e.g. `.babelrc`): this is my `babel.config.js`:
```
module.exports = {
  plugins: ['macros', '@babel/plugin-syntax-dynamic-import']
}
```

**Comment by jzsn2018** [comment]
I have meet same question too

**Comment by Martin005** [comment]
@ThomasSalty @jzsn2018
Hello, could you please tell me what version of the `@lingui/macro` package you used your projects?
If you used the version `2.8.3` as your initial comment suggest, then you will have to update the package to version `3.0.0` or later to use the `defineMessage` macro as previous versions didn't have this feature.
