### ISSUE TITLE
Major bundlesize increase with @lingui/core 3.14.0

### ISSUE THREAD

**Issue by paales** [lingui/js-lingui#1263]
**Describe the bug**

https://bundlephobia.com/package/@lingui/core@3.14.0

https://github.com/graphcommerce-org/graphcommerce/pull/1536#issuecomment-1168603211

<img width="822" alt="Schermafbeelding 2022-06-28 om 13 39 29" src="https://user-images.githubusercontent.com/1244416/176169729-fdaf4d09-6aa6-4083-9185-f84a1bc930a0.png">

**To Reproduce**

Use new version and measure the resulting bundle size

**Expected behavior**

Bundlesize is in the same ballpark als the older version

**Comment by ReinoutStevens** [comment]
Don't know if this is related, but for us `messageformat-parser` gets included in the production build, even though it should get filtered out when the NODE_ENV is set to production, which is +- 5kb.
I've fixed it by adding a custom webpack rule that uses the null-loader for that package, but it doesn't seem ideal.

**Comment by paales** [comment]
@semoal This one is kinda important, currently stil stuck on the old version :)

**Comment by paales** [comment]
Not stale

**Comment by sven-meyer-wetter-com** [comment]
We noticed this increase in bundle size too. Any change that this could be fixed?

**Comment by semoal** [comment]
Hi guys, sorry for this problem ;| I just checked and the commit that caused the problem was this: 
https://github.com/lingui/js-lingui/pull/1258
I'm open to suggestions about how to handle exports on package.json to bundlers omit automatically ESM/r CJS..

**Comment by thekip** [comment]
@semoal could you elaborate more on that? Do you think bundlers pull to the bundle both version cjs and esm at the same time?

**Comment by thekip** [comment]
Should be fixes by #1343

**Comment by paales** [comment]
@thekip Ohh yeahh! Will check this out soon to see if this resolves the issue :)
