### ISSUE TITLE
babel-plugin-lingui-transform-js@v1.0.5 needs to be published

### ISSUE THREAD

**Issue by thibautRe** [lingui/js-lingui#127]
Hey,

Following [this change](https://github.com/lingui/js-lingui/commit/44bf5289e0c8fd0f0b2d2fca43eca820b7d956ab#diff-1aa69097416b9d839428a77edb8ba12dR23), this package https://www.npmjs.com/package/babel-plugin-lingui-transform-js needs to be published to its new version (v1.0.5)

**Comment by tricoder42** [comment]
Ah, sorry, I accidentally messed up `lerna publish` process. Republished under new patch release:

 - babel-plugin-lingui-extract-messages@1.1.10
 - babel-plugin-lingui-transform-js@1.0.6
 - babel-preset-lingui-js@1.0.7
 - babel-preset-lingui-react@1.0.13
 - lingui-cli@1.4.2
 - lingui-loader@0.1.2
