### ISSUE TITLE
`ts-jest` support

### ISSUE THREAD

**Issue by kopax-polyconseil** [lingui/js-lingui#1272]
**Is your feature request related to a problem? Please describe.**

We use lingui since a while and despite it's cool to use, our app now gets bigger and the amount of unit tests too. For this reason, we wanted to switch to `ts-jest` instead of `babel-jest` to improve our tests perfs, but it is not possible as lingui does not support `ts-jest`.

With `ts-jest`, we got this error everywhere:

```ts
    TypeError: (0 , macro_1.t) is not a function
```

**Describe proposed solution**

Support for `ts-jest`

**Describe alternatives you've considered**

Removing lingui as we don't really need translation.

**Additional context**

```json
{
    "@lingui/core": "^3.13.2",
    "@lingui/react": "^3.13.2",
    "@lingui/cli": "^3.13.2",
    "@lingui/macro": "^3.13.2",
}
````

**Comment by kopax-polyconseil** [comment]
I started to use a mock for jest, unfortunately, this is what I did and it is not ready yet:

```tsx
export const t = (text: string | Array<string>) => {
  if (typeof text === text) {
    return text
  } else if (text instanceof Array) {
    return text.map((t) => t.trim()).join(' ')
  }
  return text
}

type Plural = {
  value: number
  one: string
  other: string
}

export const plural = (count: number | Plural, plural: Plural) => {
  if (isNaN(count as number)) {
    plural = count as Plural
    if (plural.value <= 1) {
      return plural.one.replace('#', `${plural.value}`)
    }
    return plural.other.replace('#', `${plural.value}`)
  }
  if (count <= 1) {
    return plural.one.replace('#', `${count}`)
  }
  return plural.other.replace('#', `${count}`)
}
```

If guys want to help get further :)

**Comment by thekip** [comment]
@andrii-bodnar @kopax-polyconseil supporting also typescript transformation in additional to SWC and babel plugin has no sense as it means complete rewrite the whole macro as typescrit transformation and supporting all 3 versions. Where typescript transformations has no advantages over SWC or babel. 

@kopax-polyconseil if you want to speedup your test it's better to try SWC, as it's dozen times faster than typescript and babel. Lingui plugin for SWC is almost ready. https://github.com/lingui/js-lingui/issues/1224
