### ISSUE TITLE
.pot extract-template command doesn't apply catalog {name} as filename 

### ISSUE THREAD

**Issue by RobinHeij** [lingui/js-lingui#1286]
**Describe the bug**
While having 2 catalogs with different paths, the .pot file that is generated does NOT give its file(s) the correct name. It defaults to messages.pot

**To Reproduce**
Have these catalogs
```
   "catalogs": [{
      "path": "src/locales/{locale}/{name}",
      "include": ["src/themes"]
   },
   {
      "path": "src/locales/{locale}/{name}",
      "include": ["src/utils/ui"]
   }],
```

run `lingui extract-template` and see a `messages.pot` generated .

**Expected behavior**
I'd like to have a `themes.pot` and a `ui.pot`

**Additional context**

jsLingui version 8.1.2
Babel version 7.19.3
I used the create-react-app as well as the create-next-app. Both with typescript support, both the same error.

**Comment by thekip** [comment]
Yes, the extract-template has a hardcoded name `template.pot`. Probably PR's are welcome in the "gettext template" land, because maintainers as it seems don't really use them and don't know about real-world use-cases

**Comment by andrii-bodnar** [comment]
@thekip is it still relevant for v4? Or maybe the experimental extractor is a better option in this case?

**Comment by thekip** [comment]
it still relevant for older extractor, but new extractor does not have this issue.
