### ISSUE TITLE
@lingui/macro 3.x slows down builds + tests and leaks memory

### ISSUE THREAD

**Issue by decafdennis** [lingui/js-lingui#1297]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@lingui/macro@3.14.0` for the project I'm working on.

When we upgraded from Lingui 2.x to 3.x, we noticed our builds (babel-loader) were up to 2x slower and our tests (babel-jest) became flaky in our CI environment. We found this was caused by a piece of global state in `@lingui/macro` that is ever-growing and leaks path objects over time, resulting in longer build times and high memory pressure in big test suites. 

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@lingui/macro/index.js b/node_modules/@lingui/macro/index.js
index 1384958..bc98648 100644
--- a/node_modules/@lingui/macro/index.js
+++ b/node_modules/@lingui/macro/index.js
@@ -134,13 +134,14 @@ function isRootPath(allPath) {
   };
 }
 
-var alreadyVisitedCache = [];
+// Used to mark path objects as visited without relying on global state or creating memory leaks.
+var alreadyVisitedKey = Symbol('@lingui/macro#alreadyVisited');
 
 function alreadyVisited(path) {
-  if (alreadyVisitedCache.includes(path)) {
+  if (path.hasOwnProperty(alreadyVisitedKey)) {
     return true;
   } else {
-    alreadyVisitedCache.push(path);
+    path[alreadyVisitedKey] = true;
     return false;
   }
 }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by semoal** [comment]
Could be better instead of using a Symbol, using a weakmap? Nice find mate, thanks for the contribution

**Comment by decafdennis** [comment]
Yes. For some reason I assumed `Weak[Anything]` is not widely supported, but it is. CPU and memory usage appears to be equivalent.

If this looks good to you, I'd be happy to open a PR!

```diff
diff --git a/node_modules/@lingui/macro/index.js b/node_modules/@lingui/macro/index.js
index 1384958..0b834c5 100644
--- a/node_modules/@lingui/macro/index.js
+++ b/node_modules/@lingui/macro/index.js
@@ -134,13 +134,13 @@ function isRootPath(allPath) {
   };
 }
 
-var alreadyVisitedCache = [];
+var alreadyVisitedCache = new WeakSet();
 
 function alreadyVisited(path) {
-  if (alreadyVisitedCache.includes(path)) {
+  if (alreadyVisitedCache.has(path)) {
     return true;
   } else {
-    alreadyVisitedCache.push(path);
+    alreadyVisitedCache.add(path);
     return false;
   }
 }
```

**Comment by semoal** [comment]
Yes, of course, I would love a pr of this
