### ISSUE TITLE
Extraction in 3.15 completely wipes all strings using the t macro

### ISSUE THREAD

**Issue by andrejcremoznik** [lingui/js-lingui#1301]
**Describe the bug**

When running extraction all strings using the `t` macro got wiped from my `.po` files.

**To Reproduce**

```
$ npx create-react-app ling
$ cd ling
$ npm i @lingui/macro @lingui/react @lingui/cli

add to package.json

"lingui": {
    "locales": [
      "en",
      "sl"
    ],
    "sourceLocale": "en",
    "format": "po",
    "rootDir": "./src",
    "catalogs": [
      {
        "path": "<rootDir>/locales/{locale}",
        "include": [
          "<rootDir>"
        ]
      }
    ]
  }

and to scripts: {
  "i18n:extract": "lingui extract --overwrite --verbose"
}
  
  
add to App.js

import { Trans, t } from '@lingui/macro'

<Trans>Test string using Trans macro</Trans>
{t`Test string using t macro`}


Run
npm run i18n:extract
```

This is the result:

```
#: App.js:21
msgid "Test string using Trans macro"
msgstr ""

#: App.js:22
msgid "{0}"
msgstr ""
```

**Expected behavior**

```
#: App.js:21
msgid "Test string using Trans macro"
msgstr ""

#: App.js:22
msgid "Test string using t macro"
msgstr ""
```

**Additional context**

Somehow the `t` string gets collapsed into the token `{0}`. It completely collapsed hundredths of strings in my project in the same way and I had to revert to 3.14.0

- jsLingui version `3.15.0`
- Babel version `@babel/core@7.20.2`
- Your Babel config: `create-react-app` - vanilla

**Comment by cravoley** [comment]
I got the same issue after upgrading from `3.13.3`

**Comment by ThaNico** [comment]
Hi, having the same issue and rolled back to 3.14

**Comment by doubleforte** [comment]
Same here. Downgrading to 3.14.0 works for me as well.

**Comment by srcereress** [comment]
Same same! Pinning to 3.14.0.
