### ISSUE TITLE
Bug: brackets in template literal results in macro compile failure

### ISSUE THREAD

**Issue by bright-wang** [lingui/js-lingui#1303]
**Describe the bug**
Just very similar to https://github.com/lingui/js-lingui/issues/1075, I also came up with compile failure error:
Error: Can't parse message. Please check correct syntax: "input variable: { ...... }" 
 
 Messageformat-parser trace: Expected identifier but "." found.
    at compile (....../node_modules/.pnpm/@lingui+cli@3.13.3_l57gh7u5ywadp5ivckxo6hsz4m/node_modules/@lingui/cli/api/compile.js:115:11)
    at compileSingleKey ....../node_modules/.pnpm/@lingui+cli@3.13.3_l57gh7u5ywadp5ivckxo6hsz4m/node_modules/@lingui/cli/api/compile.js:42:49)
    at ....../node_modules/.pnpm/@lingui+cli@3.13.3_l57gh7u5ywadp5ivckxo6hsz4m/node_modules/@lingui/cli/api/compile.js:70:12

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```
import { t } from '@lingui/macro';

export default function App() {
   return <input placeholder={t`input variable: { ...... }`} />
}
```

**Expected behavior**
Template should be compiled with no error...

**Additional context**
Package version info:
 '@lingui/cli': 3.13.3_l57gh7u5ywadp5ivckxo6hsz4m
  '@lingui/macro': 3.13.3_fxhud3nu6zrc5fvtlhahzizpp4

**Comment by thekip** [comment]
Fixed and would be published with next version. You probably need to escape brackets with `'` otherwise they would be treated as placeholder expansion (this is according of spec) 

```
```
