### ISSUE TITLE
Inconsistent `extractBabelOptions` handling

### ISSUE THREAD

**Issue by N1kto** [lingui/js-lingui#1305]
**Describe the bug**
Currently depending on which project type you are using lingui in, the `extractBabelOptions` will either work as expected or if you are using CRA and a built-in extractor (`babel`),  it will will not allow you to set `presets` option (your setting will be implicitly overwritten by `lingui`).

**To Reproduce**
In a CRA project try setting different `presets` option using [`extractBabelOptions`](https://lingui.js.org/ref/conf.html#extractbabeloptions) config option when default extractor (`babel`) is used.

**Expected behavior**
The  `presets` options from `extractBabelOptions` should be used.

**Additional context**
Expected behavior is not there due to the following code in the default `babel` extractor:

```
...
extract(filename, localeDir, options = {}) {
    const { babelOptions: _babelOptions = {}, configPath } = options
    const { plugins = [], ...babelOptions } = _babelOptions
    const frameworkOptions: BabelOptions = {}

    if (options.projectType === projectType.CRA) {
      frameworkOptions.presets = ["react-app"]
    }

    transformFileSync(filename, {
      ...babelOptions,
      ...frameworkOptions,
      // we override envName to avoid issues with NODE_ENV=production
      // https://github.com/lingui/js-lingui/issues/952
      envName: "development",
      plugins: ["macros", [linguiExtractMessages, { localeDir, configPath }], ...plugins],
    })
  },
  ```
As you can see, when there is CRA project detected, lingui will prepare `frameworkOptions` object (with opinionated `presets` param) and will spread it after `babelOptions` which come from config. So, if I set `presets` option in my `extractBabelOptions`, it gets effectively overwritten by `presets` option from `frameworkOptions`. This happens only in CRA projects and doesn't happen in others, which is inconsistent. I think it should either allow users to set any `babelConfig` option (including `presets`) disregarding which project lungui is being run in  (and for that `...babelOptions` and `...frameworkOptions` lines should be swapped) OR it should be documented somewhere in the docs that there is this special handling in case of CRA project. Otherwise it's really hard to find out why `lingui` is not working as expected (it took several hours for me to do that...).

For me that `presets` option was critical because in our app we use CRA + emotion-js + lingui. It means that we are forced (by emotion) to set `/** @jsxImportSource @emotion/core */` in every react component. In the default lungui setup I got following error when doing `lingui extract`: `importSource cannot be set when runtime is classic`. To "fix" it I had to force "automatic" runtime, so I added:
```
  "presets": [
    "@babel/preset-typescript",
    [
      "@babel/preset-react",
      {
        "runtime": "automatic",
        "importSource": "react"
      }
    ]
  ],
  ```
for `extractBabelOptions` option in my lingui config, but nothing changed. Only after studying the lingui sources did I see the issue.
My final workaround which made everything work was to prepare my "custom" extractor which is almost the same as lingui's default `babel` one except for different `presets` option (one quoted above).

- jsLingui version ``lingui --version``: 
`3.15.0`
- Babel version ``npm list @babel/core``
`7.20.2`
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)
Create React App (v.5.0.1)

**Comment by thekip** [comment]
@semoal I think extractor should be decoupled from user's babel config and all knowledge about what tool is used to perform AST work should be an internal implementation detail. So the babel inside should be configured with the "babelrc: false" and opinionated set of plugins provided, which should cover most of the react / react-like projects. 

The current problems mostly related to weird babel configs which appears as result of merging user provided config and some internal defaults. 

For sure for extractor and for babel itself should be no difference do you use emotion or not as long as syntax is valid (babel is not a typechecker and will not complain about `css` prop which exists only in build-time).

**Comment by thekip** [comment]
Fixed in https://github.com/lingui/js-lingui/pull/1367 would be released as part of v4
