### ISSUE TITLE
Macro docs lack of examples how to use plural() with custom i18n

### ISSUE THREAD

**Issue by timofei-iatsenko** [lingui/js-lingui#1312]
https://lingui.js.org/ref/macro.html#plural

Documentation on this page shows how to use `` t`msg` `` with custom i18n instance. But lacking an example how to use plural() with it. 

There is a note:

> Use plural inside [t](https://lingui.js.org/ref/macro.html#jsmacro-t) macro if you want to add custom id or comment for translators.

But still not clear how to use it, and this note is quite hard to spot when you're reading docs roughly.

Which one would work: 

```ts
import { plural } from "@lingui/macro"

const message = t(i18n)(plural(count, {
   one: `${name} has # friend`,
   other: `${name} has # friends`
}))
```

or 

```ts
import { plural } from "@lingui/macro"

const message = t(i18n)({
  message: plural(count, {
   one: `${name} has # friend`,
   other: `${name} has # friends`
  })
})
```

or 

```ts
import { plural } from "@lingui/macro"

const message = t(i18n)`${plural(count, {
   one: `${name} has # friend`,
   other: `${name} has # friends`
})}`
```

**Comment by maman** [comment]
just stumbled to this issue myself – the correct form to use is the last one:

```ts
const message = t(i18n)`${plural(count, {
   one: `${name} has # friend`,
   other: `${name} has # friends`
})}`
```

**Comment by thekip** [comment]
The way to provide custom i18n instance is correct, but example of produced code is not. Macro is flattening calls to other macros inside a "root" call, so there should be only one entry in catalog.

I'm pretty sure it works like that in both, swc and babel versions, so either you have something wrong in your code or you find a bug.

**Comment by LeonMueller-OneAndOnly** [comment]
> just stumbled to this issue myself – the correct form to use is the last one:
> 
> ```ts
> const message = t(i18n)`${plural(count, {
>    one: `${name} has # friend`,
>    other: `${name} has # friends`
> })}`
> ```
> 
> it did create two localization entries, and a "nested" custom i18n calls when compiled via babel macros:
> 
> **js**
> 
> ```js
> const message = i18n._({
> 	id: "xxx", // --> from `t`
> 	values: {
> 		0: i18n._({
> 			id: "yyy" // --> from `plural`
> 			values: {
> 				0: count,
> 				1: name,
> 				2: name,
> 			}
> 		})
> 	}
> })
> ```
> 
> **po**
> 
> ```po
> #: some-source:1
> msgid "{0}"
> msgstr ""
> 
> #: some-source:1
> msgid "{0, plural, one {{1} - has # friend} other {{2} - has # friends}}"
> msgstr ""
> ```

This format does not lead to the extraction of the message into the .po file. Following format works as a macro:

const message = t(i18n)({
  message: plural(count, {
   one: `${name} has # friend`,
   other: `${name} has # friends`
  })
})

**Comment by andrii-bodnar** [comment]
@timofei-iatsenko is it still relevant in the context of deprecating custom i18n instance?

**Comment by timofei-iatsenko** [comment]
No it's not. The actual way of doing so is (Lingui V5)

```js
import { plural, msg } from "@lingui/core/macro"

const message = i18n._(msg`${plural(count, {
   one: `${name} has # friend`,
   other: `${name} has # friends`
})}`)
```

**Comment by etx121** [comment]
Hi @timofei-iatsenko ,

I haven't found yet a working example to make plural work on v4. The examples shown in the documentation could be more explicit. Do you have an example with v4?

**Comment by timofei-iatsenko** [comment]
@etx121 there are plenty of examples in this thread which will work.

**Comment by etx121** [comment]
@timofei-iatsenko I tried the version of `maman` above:
```
const message = t(i18n)`${plural(count, {
    one: `${name} has # friend`,
    other: `${name} has # friends`
 })}`
```

I end up having that:
<img width="528" alt="Screenshot 2024-10-30 at 12 44 26" src="https://github.com/user-attachments/assets/1d60ca41-8c79-4d86-bfbc-a4663baa9380">

So I gave up on the usage of `plural` , and I just wrote the plain ICU message instead.

**Comment by timofei-iatsenko** [comment]
First, please use syntax highlighting for code blocks, it's easier to read then. 
Second, you should pass a `count` value here, and function will return a translated string to you.

**Comment by etx121** [comment]
First: ok sorry, I am not used to write comments on github 😬
Second: but we should define a `count` variable? I would like to have a message where i define later the translated message passing my values.
