### ISSUE TITLE
Macro docs lack examples of arg() macro

### ISSUE THREAD

**Issue by thekip** [lingui/js-lingui#1320]
While writing SWC Macro plugin and reading babel macro source code found this in tests: 

```ts
export default [
  {
    name: "Arg macro should be exluded from values",
    input: `
        import { t, arg } from '@lingui/macro';
        const a = t\`Hello $\{arg('name')\}\`;
    `,
    expected: `
        import { i18n } from "@lingui/core";
        const a = 
          /*i18n*/
          i18n._("Hello {name}")
    `,
  },
]
```

Which is not described anywhere. Or if it's outdated - should be removed from codebase.

**Comment by thekip** [comment]
Looks like it's something old and outdated because [typings](https://github.com/lingui/js-lingui/blob/main/packages/macro/index.d.ts) also not exporting it. So it's better to remove it from codebase to avoid confusion.

**Comment by thekip** [comment]
@Martin005 @andrii-bodnar i'm going to delete this from codebase, the value of this feature is not clear, and it was not public anyway.

**Comment by andrii-bodnar** [comment]
@thekip let's first ask @tricoder42, maybe there is some point here

**Comment by thekip** [comment]
It looks like an ad-hoc solution to avoid problems with escaping which we fixed recently.

**Comment by thekip** [comment]
i'm going to delete this from codebase.

**Comment by andrii-bodnar** [comment]
@thekip agree with you

**Comment by tricoder42** [comment]
Hey guys, sorry for late response. I honestly don't recall the reason behind this feature, so feel free to remove it. Especially if it's obsolete.
