### ISSUE TITLE
Select Macro Documentation Example is wrong

### ISSUE THREAD

**Issue by thekip** [lingui/js-lingui#1324]
Example from [documentation]( https://lingui.js.org/ref/macro.html#id3): 
```ts
import { Select } from "@lingui/macro"

// gender == "female"      -> Her book
// gender == "male"        -> His book
// gender == "unspecified" -> Their book
<Select
    value={gender}
    male="His book"
    female="Her book"
    other="Their book"
/>
```

Actually, it should be: 
```ts
import { Select } from "@lingui/macro"

<Select
    value={gender}
    _male="His book"
    _female="Her book"
    other="Their book"
/>
```

Proof: https://github.com/lingui/js-lingui/blob/main/packages/macro/test/jsx-select.ts#L3-L19

If you write code as in example, macro will produce: 

```diff
import { Trans } from "@lingui/react";
<Trans
+  male="He"
+  female={`She`}
  id={"{count, select, male {He} female {She} other {<0>Other</0>}}"}
  values={{
    count: count,
  }}
  components={{
    0: <strong />,
  }}
/>;

```

Which by the way will work, but unnecessary code would be produced.

So here we should either fix the macro to not produce this fields and add this to the test case. 
Or update docs and fix usage with `_{option}` which would be a breaking change. 

Anyway, action point needed here.

**Comment by thekip** [comment]
Looked at the code one more time, and looks like this work by mistake. The original author's intention was to have exact choices with underscore only.  Here is the regex:

`/(_[\d\w]+|zero|one|two|few|many|other)/`

**Comment by thekip** [comment]
Related https://github.com/lingui/js-lingui/issues/1288

**Comment by tricoder42** [comment]
> Looked at the code one more time, and looks like this work by mistake. The original author's intention was to have exact choices with underscore only. Here is the regex:
> 
> `/(_[\d\w]+|zero|one|two|few|many|other)/`

You're right. ICU MessageFormat uses `=` for exact numbers in plural-like formats (e.g. `=0`). I replaced `=` with `_` since you can't use `=` character in prop names. I believe I kept the same naming convention in select format a) to keep it consistent b) to avoid name clashes with macro props.
