### ISSUE TITLE
Local development not working on Windows

### ISSUE THREAD

**Issue by Martin005** [lingui/js-lingui#1326]
**Describe the bug**
The local development described in [CONTRIBUTING.md](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md#contributing-the-code) doesn't work on Windows as the mentioned script [verdaccio-release.js](https://github.com/lingui/js-lingui/blob/main/scripts/verdaccio-release.js) is heavily based on Linux platform.

**To Reproduce**
Clone repository and try to set-up local development environment as described in [CONTRIBUTING.md](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md#contributing-the-code) on a Windows platform.

**Expected behavior**
The local development environment should work on Windows platform.

**Comment by thekip** [comment]
Why not to use WSL on windows? My team gave up using native windows development a long time ago in favor of WSL (or mac). 

This is so less painful, just my suggestion
