### ISSUE TITLE
Docs typo: DateFormat

### ISSUE THREAD

**Issue by sebhiticas** [lingui/js-lingui#136]
In the docs, it says `numberic` and should be `numeric`.

Url: https://lingui.github.io/js-lingui/ref/lingui-react.html?highlight=date#component-DateFormat

<img width="814" alt="jslingui-dateformat" src="https://user-images.githubusercontent.com/675541/34065541-cebc4f34-e1d0-11e7-9195-048bcd022aa7.PNG">

**Comment by tricoder42** [comment]
Thank you @sebhiticas for reporting this and @thibautRe for fixing! Updated docs are deployed now.

**Comment by sebhiticas** [comment]
Thanks to you 👍 Awesome library BTW! Easy to use and gets the job done 💯
