### ISSUE TITLE
Suggestion: Copy message ID to translation for source locale

### ISSUE THREAD

**Issue by np-8** [lingui/js-lingui#141]
The [lingui extract](https://lingui.github.io/js-lingui/ref/lingui-cli.html#extract) --format minimal command makes pretty messages.json files, like this:

```
{
  "This is a test": "",
  "{messagesCount, plural, one {There's # message in your inbox} other {There're # messages in your inbox}}": ""
}
```

## Suggestion
A flag called `--default-translation` or similar, which could be used like `lingui extract --format minimal --default-translation en_US`, which would produce 

```
{
  "This is a test": "This is a test",
  "{messagesCount, plural, one {There's # message in your inbox} other {There're # messages in your inbox}}": "{messagesCount, plural, one {There's # message in your inbox} other {There're # messages in your inbox}}"
}
```
into locale/en_US/messages.json, to enhance translation experience. 

### Reasoning
(1) Some translation tools might give false alarms of missing translations, if there are empty fields.
(2) If someday there will be optimized message ID's  (#139), translating these

```
// locale/en_US/messages.json
{
  "1": "This is a test",
  "2": "{messagesCount, plural, one {There's # message in your inbox} other {There're # messages in your inbox}}"
}
```
```
// locale/fi_FI/messages.json
{
  "1": "",
  "2": ""
}
```
will be more pleasant than translating these:

```
// locale/en_US/messages.json
{
  "1": "",
  "2": ""
}
```
```
// locale/fi_FI/messages.json
{
  "1": "",
  "2": ""
}
```

**Comment by tricoder42** [comment]
I think we could use existing `sourceLocale` config, but instead of handling source locale in `lingui extract` and `lingui compile` commands as described [here](https://github.com/lingui/js-lingui/issues/138#issuecomment-352270361), we could copy message IDs in `lingui extract` command.

My original idea was that catalog for `sourceLocale` could be completely ignored, but you're right that it may still be requird for external tools.

As for (2), message ID optimization should be done in compilation step. `messages.json` should always have full message IDs. This way we can change message ID optimization anytime without breaking translations in 3rd party tools which rely on immutable message IDs.

What do you think?

**Comment by np-8** [comment]
Using `sourceLocale` seems clever, since it is an existing configuration option. Copying message IDs in the `lingui extract` command solves the problem, and to me feels the correct path. I don't know would it make someone upset to see their `sourceLocale` languages message IDs (untranslated text) to be copied into the translation by default?  If it would, then we could add just a `--no-copy` option (flag or config option). But otherwise, I think copying should be the default behaviour. (since messages.json is just used in development anyway)

> As for (2), message ID optimization should be done in compilation step. messages.json should always have full message IDs. This way we can change message ID optimization anytime without breaking translations in 3rd party tools which rely on immutable message IDs.

Thats exactly right. Better to keep message ID optimization in the compilation step! I don't know what I was thinking :)

**Comment by tricoder42** [comment]
> I don't know would it make someone upset to see their sourceLocale languages message IDs (untranslated text) to be copied into the translation by default?

In that case it's harder to check for missing translations. It make sense only for few locales and those usecases are covered by fallbackLocale (e.g. en_US could use translations from en_GB if missing).

**Comment by snegostup** [comment]
Is it unusable with custom message ids?
```javascript
...
<Trans id="page.title">Hello World!</Trans>
...
```
(with `"sourceLocale": "en"` set in config)

extracts:
`"page.title":"page.title"` instead of `"page.title": "Hello World!"`
