### ISSUE TITLE
different config loaded for `macro` and `cli` when use `extract --config` if config file is under `cwd/subfolder`

### ISSUE THREAD

**Issue by taozhou-glean** [lingui/js-lingui#1416]
**Describe the bug**

we saw `No locales found!` but message extracted successful:

```
No locales defined!

Add 'locales' to your configuration. See https://lingui.dev/ref/conf#locales
Catalog statistics for typescript/core/i18n/locales/{locale}/messages:
┌────────────────────┬─────────────┬─────────┐
│ Language           │ Total count │ Missing │
├────────────────────┼─────────────┼─────────┤
│ en (source)        │     102     │    -    │
│ pseudolocalization │     102     │   102   │
└────────────────────┴─────────────┴─────────┘
```

after debugging it, it looks both `cli/lingui-extract` and `macro` will try to load config separately:

```
    at getConfig (/xxx/node_modules/@lingui/conf/build/index.js:90:10)
    at Object.<anonymous> (/xxx/node_modules/@lingui/cli/build/lingui-extract.js:80:38)
```
vs
```
    at getConfig (/xxx/node_modules/@lingui/conf/build/index.js:90:10)
    at Object.<anonymous> (/xxx/node_modules/@lingui/macro/build/index.js:20:36)
```

from the [code](https://github.com/lingui/js-lingui/blob/8bc212d2846af5609d89f51efed952b089244e4e/packages/conf/src/index.ts#L132), it looks like the `macro` only tries to find the config file from cwd and up, and `cli` will consider the `--config` param.

The issue is that our set up is more like following:

```
- package.json
  - project
    - lingui.config.ts
```

so it won't find anything if starts from the level of `package.json`.

the workaround is to use `LINGUI_CONFIG=project/lingui.config.ts`, but it would be more ideal if `--config` also just works.

**Comment by thekip** [comment]
Yes, they not depend on each other. The simplest solution would be just set `process.env.LINGUI_CONFIG = argv. config` inside the CLI command. But good solution is upcoming with fundamental changes in v4

**Comment by taozhou-glean** [comment]
similar issue observed when using the loader, which is taking the config path from loader option or using the `resourcePath` as `cwd` to search for config file.. and it does not take `process.env. LINGUI_CONFIG` :( so have to pass the `config` with webpack config. Probably should at least honor `LINGUI_CONFIG`
