### ISSUE TITLE
unable to extract `i18n._({id: "id", message: "xxx"})`

### ISSUE THREAD

**Issue by taozhou-glean** [lingui/js-lingui#1417]
**Describe the bug**

[the method accepts `MessageDescriptor`](https://github.com/lingui/js-lingui/blob/8bc212d2846af5609d89f51efed952b089244e4e/packages/core/src/i18n.ts#L180), but using the object directly will fail the extraction:

```
i18n._({id: "xxx", message: "asd"})
```

**To Reproduce**

```
import { useLingui } from "@lingui/react"

export default function App() {
   const {i18n} = useLingui()
   const text = i18n._({id: 'test', message: 'test'})
   return <Trans>{text} should be translated!</Trans>
}
```

run `lingui extract` on above code will report `Missing message ID, skipping.`

**Expected behavior**

message should be extracted successfully.

**Additional context**

Looking at the code, it seems we always just take the id as the first argument's value, so it only works with string id there: https://github.com/lingui/js-lingui/blob/8bc212d2846af5609d89f51efed952b089244e4e/packages/babel-plugin-extract-messages/src/index.ts#L269

the workaround is either spread the object into multiple arguments or wrap it with `defineMessage`.

**Comment by thekip** [comment]
Your snippet is incorrect. See https://github.com/lingui/js-lingui/discussions/1381#discussioncomment-4815628

Also, please don't mix and match macro and non-macro usage, it's a straight way to shoot yourself in the foot.

**Comment by taozhou-glean** [comment]
Thanks! it would be great if we can enforce it somehow, since the type suggested that `MessageDescriptor` is also acceptable there (not the output from `defineMessage`) and from the code, it seems we also try to extract `i18n._`.

>  Also, please don't mix and match macro and non-macro usage, it's a straight way to shoot yourself in the foot.

just wondering what is the suggested way to write if we need the plain string translations also listen on locale change ? that's why I include `useLingui` hooks and then use the `i18n._` at the first place ;) should it always be used together with `defineMessage` macro then ?

**Comment by thekip** [comment]
> Thanks! it would be great if we can enforce it somehow, since the type suggested that MessageDescriptor is also acceptable there (not the output from defineMessage) and from the code, it seems we also try to extract i18n._.

This particular extracting was added recently, because people want to use library without macros. Mostly because nextjs advocating SWC as a replacement of babel. And people wanted to try it right here, right now. But since then we wrote a native SWC plugin and there is no necessity to use library without a macro anymore. 

It's comparable to React, you CAN use React without JSX, but no one probably do it. 
The same with lingui and macro. You can use it without, but we discourage from doing this. New awesome feature would be rolled only for usecases with macro.  

> just wondering what is the suggested way to write if we need the plain string translations also listen on locale change ? that's why I include useLingui hooks and then use the i18n._ at the first place ;) should it always be used together with defineMessage macro then ?

Did you try:
```js
t`My message`
```

**Comment by taozhou-glean** [comment]
> > Thanks! it would be great if we can enforce it somehow, since the type suggested that MessageDescriptor is also acceptable there (not the output from defineMessage) and from the code, it seems we also try to extract i18n._.
> 
> This particular extracting was added recently, because people want to use library without macros. Mostly because nextjs advocating SWC as a replacement of babel. And people wanted to try it right here, right now. But since then we wrote a native SWC plugin and there is no necessity to use library without a macro anymore.
> 
> It's comparable to React, you CAN use React without JSX, but no one probably do it. The same with lingui and macro. You can use it without, but we discourage from doing this. New awesome feature would be rolled only for usecases with macro.
> 
> > just wondering what is the suggested way to write if we need the plain string translations also listen on locale change ? that's why I include useLingui hooks and then use the i18n._ at the first place ;) should it always be used together with defineMessage macro then ?
> 
> Did you try:
> 
> ```js
> t`My message`
> ```

@thekip thanks for sharing the history on that! ya but we prefer custom id over the full message as id, IIUC, the tagged template does not allow custom id.The `t` also[ supports `MessageDescritor` for custom id](https://lingui.dev/ref/macro#t:~:text=It%27s%20also%20possible%20to%20pass%20custom%20id%20and%20comment%20for%20translators%20by%20calling%20t%20macro%20with%20a%20message%20descriptor%3A), but it seems to convert with `i18n` from `core`, which I assume won't listen for locale change right ?

so I guess my question is more like if we do want the plain strings (like used in attributes etc) to also listen on locale change, what is the recommended way here ?

```
function Component() {
  const someString = "some string to be translated"
  return <SomeComponent arial-label="label to be translated"><Trans>some other texts</Trans></SomeComponent>
}
```

IIUC, `Trans` listens on locale change automatically, but not the `arial-label` (outside of `Trans`) and the `someString` in above. Not sure if we can do this without mixing `macro` and `react` (through `withI18n` or `useLingui`).

**Comment by thekip** [comment]
If you use react, t() will work for attributes in your components. It will react on locale changes because of how react works

**Comment by taozhou-glean** [comment]
ah my bad, apparently functional component always works just fine, I was confused by the optimized component while did not really look what the definition on it ;) https://lingui.dev/guides/optimized-components#optimized-component-wrapped-in-withi18n

so we should use macro only within react component, I guess for strings outside of the react component, it would be recommend define with `defineMessage` and then use that within react component whenever needs it.

Thanks a lot!

**Comment by thekip** [comment]
`defineMessage` - is also a macro. We found even easier using <Trans> almost everywhere 

```tsx
const occupations = {
  ['traveller']: <Trans>Traveller</Trans>,
  ['blogger']: <Trans>Blogger</Trans>,
  ['chauffeur']: <Trans>Chauffeur</Trans>,
  ['travelExpert']: <Trans>Travel Expert</Trans>,
  ['brand']: <Trans>Brand</Trans>,
};

export const UserInfo = (props: Props) => { [...] } 
```

**Comment by taozhou-glean** [comment]
> `defineMessage` - is also a macro. We found even easier using `<Trans>` macro almost everywhere
> 
> ```tsx
> const occupations = {
>   ['traveller']: <Trans>Traveller</Trans>,
>   ['blogger']: <Trans>Blogger</Trans>,
>   ['chauffeur']: <Trans>Chauffeur</Trans>,
>   ['travelExpert']: <Trans>Travel Expert</Trans>,
>   ['brand']: <Trans>Brand</Trans>,
> };
> 
> export const UserInfo = (props: Props) => { [...] } 
> ```

ya except that I am converting an existing codebase, so there are some restriction like existing plain strings that can not be simply converted to JSX element :(
