### ISSUE TITLE
React Native integration docs is extremely outdated

### ISSUE THREAD

**Issue by thekip** [lingui/js-lingui#1426]
https://lingui.dev/tutorials/react-native

It's mentioned concepts from v2 version, such as: 

```ts
i18n._(t`mark messages as read`)
```
This would not work in v3 because it will return a translated string for i18n._ instead of string id.

Also this: 

```ts
        <I18n>
          {({ i18n }) => (
            <Button onPress={markAsRead} title={i18n._(t`mark messages as read`)} />
          )}
        </I18n>
```

There is no component with `i18n` name in the library on the current day. 

Also example mentioned here: 

> If you're looking for a working solution, check out the [demo on Expo](https://exp.host/@vonovak/js-lingui-demo). The source code is [available here](https://github.com/vonovak/js-lingui-demo).

Is also outdated and repo is archived. 

PS
I don't have experience with React Native at all.

**Comment by andrii-bodnar** [comment]
@vonovak I see you have contributed to the React Native article before, maybe you would be interested in actualizing the current RN docs? 🙂

**Comment by vonovak** [comment]
hello @andrii-bodnar 
yes, happy to do that! Also happy to see that the project appears to be in active development again.

If I have questions, what's the best time to reach you or another maintainer to get a timely response?
Thank you 🙂

**Comment by andrii-bodnar** [comment]
Hello @vonovak, awesome, sounds great, thank you! 🚀 

There are no strict time boundaries but probably the best time would be 9:00-18:00 CET, but feel free to ask questions anytime

You can also use the [Lingui Discord server](https://discord.gg/gFWwAYnMtA) for more convenient communication

**Comment by vonovak** [comment]
@andrii-bodnar thanks, sorry I didn't mean to ask what the best time is, but what the best _way_ to reach you is (in case you have GH notifications silences or so) 😄 

Okay, I'll use discord.

**Comment by andrii-bodnar** [comment]
@vonovak for me both Discord and GitHub would be ok, my GH notifications aren't muted 😄

**Comment by andrii-bodnar** [comment]
#442 - this issue still has a lot of traffic according to the repo insights. I think it should be taken into account while actualizing the RN article
