### ISSUE TITLE
lingui-react: Why does I18nProvider render a div?

### ISSUE THREAD

**Issue by Kernle32DLL** [lingui/js-lingui#143]
It took me some time to figure out why there was a simple `div`, without any class or anything else attached, at the root of my application. As it turned out, this `div `was rendered out by `I18nProvider`, [as a container for its children](https://github.com/lingui/js-lingui/blob/b904b9d430ae8922ab22b35889cd612b42322daf/packages/lingui-react/src/I18nProvider.js#L108).

I presume this is from pre React 16, where single objects had to be returned. As I didn't find any information for the baseline react version this project required, I presume this has to stay for compatibility reasons. However, might it be possible to make this behavior interchangeable, e.g. like it was done with `Trans`? What I have in mind would be passing `null`, for forcing not to render a container.

**Comment by tricoder42** [comment]
You could wrap your children into [<React.Fragment>](https://reactjs.org/docs/fragments.html). I18nProvider then receives only single child and doesn't render the wrapper div.

```js
function App() {
  return (
    <I18nProvider>
      <React.Fragment>
        // Content of your app
      </React.Fragment>
    </I18nProvider>
  )
}
```

I'm gonna change this default behavior in next major version which should be release soon after holidays.
