### ISSUE TITLE
`extract --watch` keeps crashing

### ISSUE THREAD

**Issue by taozhou-glean** [lingui/js-lingui#1434]
**Describe the bug**

Using `--watch` for incremental developing and the watch will crash after one round of extraction with following error:

```
node:fs:1437
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/var/folders/sq/hzfg58t16wb_xqyx2m6svx8c0000gn/T/lingui-89809'
    at Object.readdirSync (node:fs:1437:3)
    at traverse (/Users/taozhou/workspace/scio/node_modules/@lingui/cli/build/api/catalog.js:133:33)
    at Catalog.collect (/Users/taozhou/workspace/scio/node_modules/@lingui/cli/build/api/catalog.js:146:8)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Catalog.make (/Users/taozhou/workspace/scio/node_modules/@lingui/cli/build/api/catalog.js:66:25)
    at async command (/Users/taozhou/workspace/scio/node_modules/@lingui/cli/build/lingui-extract.js:47:28) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/var/folders/sq/hzfg58t16wb_xqyx2m6svx8c0000gn/T/lingui-89809'
}
```

**To Reproduce**

just run extract with `--watch` and modify files and save, repro on `example/js`.

**Expected behavior**

should not crash.

**Additional context**

Given the error and code I poked around, I think it's likely due to a racing issue when multiple files changed simultaneously, since it will try to remove the folder after every extract run: https://github.com/lingui/js-lingui/blob/3de08116bebe6da446ec6919a74d29937e95b5ab/packages/cli/src/api/catalog.ts#L205

- jsLingui version `3.17.1`
- Babel version `7.20.12`
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.): n/a

**Comment by thekip** [comment]
Have no idea what the flow should be to want to use watch there...

**Comment by taozhou-glean** [comment]
> Have no idea what the flow should be to want to use watch there...

just used the `example/js` as an example, for us, we are moving to use `@lingui` for our codebase, so it's an incremental process, it would be ideal to have the `--watch` open so changes can apply without requiring developers to run the extract manually every time (we also use `pseudo` for sanity check if the message is extracted correctly or not)

**Comment by thekip** [comment]
You don't need to extract after every single line changed in your application. Add it to pre-comiit hook or in CI/CD pipeline before build and forget
