### ISSUE TITLE
Feature request: DateFormat: time from now à la moment.js

### ISSUE THREAD

**Issue by sebhiticas** [lingui/js-lingui#144]
I didn't see any reference concerning this behavior, so here's my request: would it be possible to have something similar to moment.js with the time from now output?

Here's what I'm refering to: https://momentjs.com/docs/#/displaying/fromnow/

It looks like this:

Range | Key | Sample Output
-- | -- | --
0 to 44 seconds | s | a few seconds ago
44 to 44 seconds | ss | 44 seconds ago
45 to 89 seconds | m | a minute ago
90 seconds to 44 minutes | mm | 2 minutes ago ... 44 minutes ago
45 to 89 minutes | h | an hour ago
90 minutes to 21 hours | hh | 2 hours ago ... 21 hours ago
22 to 35 hours | d | a day ago
36 hours to 25 days | dd | 2 days ago ... 25 days ago
26 to 45 days | M | a month ago
45 to 319 days | MM | 2 months ago ... 10 months ago
320 to 547 days (1.5 years) | y | a year ago
548 days+ | yy | 2 years ago ... 20 years ago

Maybe it could be a new attribute passed to `<DateFormat />` component that would render this output. 

I really don't know what it means in terms of complexity, but it would be really useful!

Thanks again

**Comment by thibautRe** [comment]
You can have a look at [`date-fns`](https://date-fns.org/) if you want to Internationalize time difference. They provide locales and formatting, which seems to fit your needs.

**Comment by sebhiticas** [comment]
Ok thanks.

**Comment by tricoder42** [comment]
@sebhiticas Thank you for your request. It's already mentioned in #50, so I'm gonna close this as a duplicate. Please follow discussion there.

As mentioned there, before I start bundling translations with components, I need to solve a) local namespaces (related to lingui-i18n and lingui-react), b) how to package translations with components (related to lingui-cli)

For now, date-fns is the best alternative, as @thibautRe mentioned.

**Comment by sebhiticas** [comment]
Totally understand. Thanks for your help!
