### ISSUE TITLE
Consider using Intl.PluralRules instead of make-plurals

### ISSUE THREAD

**Issue by thekip** [lingui/js-lingui#1446]
This has decent browser support, including Node.js:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/PluralRules

https://caniuse.com/intl-pluralrules

So instead of: 
```ts
import { i18n } from '@lingui/core';
import { en, cs } from 'make-plural/plurals'

i18n.loadLocaleData({
  en: { plurals: en },
  cs: { plurals: cs },
})

export async function dynamicActivate(locale: string) {
  const { messages } = await import(`./locales/${locale}/messages`)
  i18n.load(locale, messages)
  i18n.activate(locale)
}
```

We can do: 

```ts
import { i18n } from '@lingui/core';

export async function dynamicActivate(locale: string) {
  const {messages} = await import(`./locales/${locale}/messages`)
  const pluralRules = new Intl.PluralRules(locale)

  i18n.loadLocaleData({
    [locale]: {plurals: (number) => pluralRules.select(number)}
  })
  i18n.load(locale, messages)
  i18n.activate(locale)
}
```

Things to consider:

1. Can we make this as a default behavior with optional fallback to 'make-plural/plurals' or polyfill for older runtimes? 
2. Does `Intl.PluralRules` supported in ReactNative (in both platforms?) https://formatjs.io/docs/guides/runtime-requirements#react-native
4. Nothing preventing us from updating docs right now with examples of usage  `Intl.PluralRules` instead of `make-plural/plurals`

Links:
- https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html#rules
- https://formatjs.io/docs/polyfills/intl-pluralrules/
- https://github.com/lingui/js-lingui/pull/1311

**Comment by Martin005** [comment]
For our current implementation, it would not be as easy as only instantiating new `Intl.PluralRules` object. We would need two because when you make a [new `Intl.PluralRules`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/PluralRules), you need to specify if you want either `cardinal` (default) or `ordinal` plural rules, you can't get both from one object.

**Comment by thekip** [comment]
Yes, i know. I'm going to make it a default behavior so users won't need to `i18n.loadLocaleData` at all. All this setup would happen inside of a lib.  We use `Intl` objects anyway, so it will not add additional requirements for runtime.

**Comment by crazyyi** [comment]
This doesn't seem to work with Korea, Chinese and Japanese.

I have followed the example and put this function in i18n.ts:

```
export function activateLocale(i18n: I18n, locale: string, messages: Messages) {
  if (locale === "pseudo") {
    locale = "en";
  }

  const cardinalRules = new Intl.PluralRules(locale, { type: "cardinal" });
  const ordinalRules = new Intl.PluralRules(locale, { type: "ordinal" });

  i18n.loadLocaleData(locale, {
    plurals: (n, ordinal) => {
      return (ordinal ? ordinalRules : cardinalRules).select(n);
    },
  });

  i18n.load(locale, messages);
  i18n.activate(locale);
}
```

I get these errors when doing a `lingui compile`:

```
Error: Invalid locale kr (missing plural rules)!

Error: Invalid locale zt (missing plural rules)!

Error: Invalid locale jp (missing plural rules)!
```
