### ISSUE TITLE
Define translatable messages with variables outside of React, use them inside component.

### ISSUE THREAD

**Issue by rovansteen** [lingui/js-lingui#145]
I have a validation function that returns an error if a field is missing and I'm trying to get that working with `js-lingui`. I have defined the field like this: 
```
i18n.t`The ${props => props.attribute} is required.`
```

Now I'm kind of stuck how I can render this message in React and pass the attribute variable to this translation? I can't find anything about it in the documentation. I've tried all kinds of things with `<Trans />` by passing in props etc. but without luck. I also tried to use `i18nMark` but it seems like template strings don't work there.

**Comment by tricoder42** [comment]
Hi @rovansteen,
unfortunately, this usecase isn't supported. You can't pass a function as a variable.

The template string above is transformed to this code:

```js
i18n._('The {0} is required', { values: { 0: props => props.attribute }})
```

You could call it manually, but you need to pass `0` variable:

```js
i18n._('The {0} is required', { values: {0: 'attribute' }})
```

I guess that's not what you want, because now the function (`props => props.attribute`) is lost completely.

How you validation function looks like? Maybe you could rewrite it to:

```js
const validate = props => i18n.t`The {props.attribute} is required`
// Message: The {0} is required

// or even better, pass `attribute` to get named argument in extracted message
const validate = ({ attribute }) => i18n.t`The {attribute} is required`
// Message: The {attribute} is required
```

**Comment by rovansteen** [comment]
Hi @tricoder42 thanks for the quick response! Thanks for the tip. My validation function now looks like this:
```
export const required = () => ({
  message: ({ attribute }) => i18n.t`The {attribute} is required.`,
  validate: value => Boolean(value),
});
```

But how do I get the attribute value to the string? It looks like the {attribute} is now hardcoded in the message.

**Comment by tricoder42** [comment]
Ah, sorry, my mistake! I'm missing `$` in template literal.

It should be:

```js
export const required = () => ({
  message: ({ attribute }) => i18n.t`The ${attribute} is required.`,
  validate: value => Boolean(value),
});
```

**Comment by rovansteen** [comment]
Okay that makes sense! However when I try to render it, I still get `The {attribute} is required`. I tried to render it plainly by like this:
```
<div>{error.message({ attribute: 'test' })}</div>
```
and in `<Trans />` component like this:
```
<Trans>{error.message({ attribute: 'test' })}</Trans>
```
but both don't work. How do I render this i18n message in to the React context with variables?

**Comment by tricoder42** [comment]
I think you also need to access `i18n` from props.

I've added example of validation using [redux-form](https://github.com/lingui/js-lingui/tree/master/examples/react-redux-form). [`validate`](https://github.com/lingui/js-lingui/blob/master/examples/react-redux-form/src/Form.js#L18) function in `redux-form` takes form values and component props as parameters, so you can wrap form with `withI18n` and use `props.i18n` for translation of validation messages. See the linked example.

You definitely need to do the same. One possible solution might be:

```js
export const required = () => ({
  message: (i18n, { attribute }) => i18n.t`The ${attribute} is required.`,
  validate: value => Boolean(value),
});
```

and then use it in your form:

```
import * as React from 'React'
import { withI18n } from 'lingui-react'

function Form({ i18n }) {
  return (
    <div>{error.message(i18n, { attribute: 'test' })}</div>
  )
}

export default withI18n()(Form)
```

Let me know if it works for you.

**Offtopic**: There's a bug with lingui-react and redux-form that after switching language, the error message stays the same. I'll take a look why it's happening.

**Comment by rovansteen** [comment]
Thanks, that works perfectly. The example certainly clarifies a lot. 👍
