### ISSUE TITLE
node_modules/@lingui/core/build/esm/index.js 161:10 Module parse failed: Unexpected token (161:10)

### ISSUE THREAD

**Issue by supasus** [lingui/js-lingui#1451]
Hi, guys ! I'm getting this error after upgrading from 3.7.1 to 3.17.1 when running my application locally:

```
Module parse failed: Unexpected token (161:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| class EventEmitter {
>   _events = {};
|   on(event, listener) {
|     if (!this._hasEvent(event)) this._events[event] = [];
```

It helps if I transpile @lingui/core using babel-loader in my config, but I'm not sure if that's the right way to approach this issue and if I'm even supposed to do that. What could be wrong here and what exactly causes this? I'm a bit confused.

@lingui/core 3.17.1
@babel/core@7.21.0
React
Node.js 16.8

**Comment by thekip** [comment]
Probably you need to update webpack if you're using it.

**Comment by supasus** [comment]
> 

Thanks ! Could you elaborate on why an older version of webpack would case that ?

**Comment by thekip** [comment]
It's because it's using very old parser which doesn't understand features which is already part of the language.

**Comment by thekip** [comment]
We use latest babel  (7.20) with `preset-env` to compile library.  The configuration is:

```js
  targets: {
          node: 14,
          browsers: "> 1%, last 2 versions, not dead",
        },
```

So according to preset-env these features should be supported by browsers by default, that't why they are not transpiled.
