### ISSUE TITLE
Extract doesn't work with "require" and "React.createElement"

### ISSUE THREAD

**Issue by lcordier42** [lingui/js-lingui#146]
Hi,
When I use 

```jsx
import { Trans } from "lingui-react";

const MyComponent = () => (
    <div>
        <Trans>Welcome</Trans>
    </div>
);
```

lingui extract works fine, but extract doesn't work with "require" and with "React.createElement".

- Extract doesn't work with "require" :
When I replace 
```jsx
import { Trans } from "lingui-react";
```
by pure JS 
```js
const { Trans } = require("lingui-react");
```
It doesn't works.

- Extract doesn't work with "React.createElement" :
When I replace
```jsx
const MyComponent1 = () => (
    <div>
        <Trans>Welcome</Trans>
    </div>
);
```
by
```js
const MyComponent2 = () =>
     React.createElement(
         "div",
         null,
         React.createElement(Trans, null, "WELCOME")
);
```
It doesn't work either.

If someone could tell me how I could make these two pure JS forms work.

Thank you !

**Comment by tricoder42** [comment]
Hello @lcordier42,
unfortunately, both babel plugins work only with JSX at the moment. It would require complete rewrite of both babel plugins.

Support for `const { Trans } = require('lingui-react')` is possible, but it won't be easy either. Right now, only files which import from `lingui-react` are transformed. This optimization prevents incorrect transforms, for example when you use `Select` component from other library. Looking for `require('lingui-react')` adds a bit of complexity. Unlike `import` statement which can be only at the top of the file, `require` can be everywhere so I need to check in every scope origin of i18n components.

I'll mark it as a feature and leave it open for later, but it won't be implemented anytime soon. The top priorities right now are documentation and release 2.0.

**Comment by tricoder42** [comment]
Hey @lcordier42, I'm not gonna fix this. In near future, all helpers (`Trans`, `i18n.t`) should be replaced with babel-macros (#193)
