### ISSUE TITLE
Translation not working in a compiled npm package (id is displayed instead of message)

### ISSUE THREAD

**Issue by alxArad** [lingui/js-lingui#1481]
I've created a npm module out of a CRA app (which is integrated in an app written using NextJs), but I have issues with lingui. The problem is that the macro texts are not translated using the default (en) translation and the ID is used instead.
One thing to mention is that I did not used any I18nProvider in this module, but instead is specified in the nextJs app.
If I use this CRA module as a git sub-repo, it works, the problem persists only if it packed as an NPM package

**My usage**

```
import { t } from '@lingui/macro'

<ToolbarButton model={{
                    text: t({ id: 'Generic.Back.Label', message: 'Back' }),
                    action: navigateBack
                }} />
```

**Compiled code:**

```
/*#__PURE__*/_jsxs("div", {
    className: styles.toolbar,
    children: [allowBackNavigation && /*#__PURE__*/_jsx("div", {
      className: styles.toolbarBackButtonContainer,
      children: /*#__PURE__*/_jsx(ToolbarButton, {
        model: {
          text: i18n._(
          /*i18n*/
          {
            id: 'Generic.Back.Label'
          }),
          action: navigateBack
        }
      })
    }), /*#__PURE__*/_jsx(ToolbarActions, {
      actions: toolbarActions
    })]
  }) : null;
````

**Babel config:**

```
"babel": {
    "presets": [
      [
        "@babel/preset-env",
        {
          "loose": true,
          "modules": false          
        }
      ],
      [
        "@babel/preset-react",
        {
          "runtime": "automatic"
        }
      ],
      "@babel/preset-typescript",
      "@lingui/babel-preset-react"
    ],
    "plugins": [
      "macros",
      "inline-react-svg"
    ],
    "ignore": [
      "src/App.css",
      "src/App.tsx",
      "src/logo.svg"
    ]
  }
```

**Scripts:**
```
"scripts": {
    "start": "set \"REACT_APP_ENVIRONMENT=local\" && react-scripts start",
    "generate-i18n": "lingui extract && lingui compile",
    "publish:build": "yarn generate-i18n && (if exist dist rmdir /s /q dist) && mkdir dist && set NODE_ENV=production&& babel ./src -d dist --copy-files --no-copy-ignored --extensions \".ts,.tsx\"&&tsc"    
  },
```

**Expected behavior**
Instead of "Back" text I see "Generic.Back.Label" (and this applies for all texts, this one is just an example)

**Additional context**

- jsLingui version 3.17.2
- @babel/cli@7.21.0, @babel/core@7.21.0,@babel/preset-env@7.20.2, @babel/preset-typescript@7.21.0
- @babel/preset-react@7.18.6 (installed by react-scripts 5.0.0)
- Nextjs: v13.0.7

**Comment by alxArad** [comment]
@thekip Thank you for your help! Now I wrapped base UI unit inside that module in a <I18nProvider> and works! That module is used in a nextJs and also in another CRA app (with monorepo); wondering about best practice here, should I use a I18nProvider inside (around) the base UI unit, or I should load module's messages in I18nProvider used by the client app (nextJs or CRA monorepo) ?

**Comment by thekip** [comment]
Actually, npm packages are a bit tricky. It depends on your configuration and how you're extracting and how your catalogs loaded and get merged. 

If you have a monorepo so all sources lay next to each other, you can setup an extracting from all this packages in your host aplication and than load one catalog per application. 

Other option would be to create a per-library catalogs, and then somehow asynchronously load them together with your library. 

Depending on that using of i18n provider would vary. 

I personally have a monorepo and just extract in each application from all dependent packages. Then load it once as one big catalog.  You can read about options here https://github.com/lingui/js-lingui/issues/1458
