### ISSUE TITLE
some <Trans> tag content are not being collected

### ISSUE THREAD

**Issue by mcku** [lingui/js-lingui#149]
Hi, 

In a project, I had started using lingui-react with <Trans> encapsulation for strings to be translated. This worked fine up until now, as some (1-2 out of 80) strings are just do not appear in the messages file. I believe they get lost in the way somehow, but have no idea where and why that has happened. 

The content within <Trans> tags, which disappears in message file, renders fine in the browser in the source language.

Could you recommend a strategy to debug this, or any suggest any ideas? 

Thanks.

**Comment by tricoder42** [comment]
Take a look at transformed source (without minification) and try to find location of these `<Trans>` tags.

Could you please share original line with `<Trans>` which is missing in extracted messages and if you manage to find it, also the transformed line?

**Comment by mcku** [comment]
The _build directory contains some json files named "undefined.json". This directory tree also resembles the original jsx source tree. But each subfolder contains one undefined.json. It appears that if there is more than one file in a particular jsx tree subfolder, <Trans> from one of those in the source tree found its way to the output, but not the others.

**Comment by tricoder42** [comment]
Yes, that's definitely bug. ~What environment you're in? Windows/Linux?~

Oh, I just realized: Do you use Babel 7? I'm migrating jsLingui to new build system and as part of it I had to migrate to Babel 7 as well. I encountered exactly the same problem as you did.

**Comment by mcku** [comment]
@tricoder42 I am using Linux. 
Does changing the approach help? As in the typescript plugin, concatenating output to a single file using 
`tsc --outFile dist/index.js --module system` and the output now has tags like `<lingui_react_1.Trans>Choose language</lingui_react_1.Trans>`
`<lingui_react_2.Trans>Messages</lingui_react_2.Trans>`
They look fine, and namespaced during concatenation I think. However, 
during extraction they do not get picked up.
```
Catalog statistics:
┌─────────────┬─────────────┬─────────┐
│ Language    │ Total count │ Missing │
├─────────────┼─────────────┼─────────┤
│ en (source) │      0      │    -    │
│ tr          │      0      │    0    │
└─────────────┴─────────────┴─────────┘
```
Maybe I am missing something...

**Comment by tricoder42** [comment]
Extract plugin looks for <Trans> component only. Actually, it looks on how Trans component is imported and looks for the imported name. It doesn't support member expression yet, so this example won't work either:

```js
import * as linguiReact from 'lingui-react'

<linguiReact.Trans>Messages</linguiReact.Trans>
```

This could be added to extract plugin, but it seems it doesn't fix our original problem. Extract plugin doesnt' work with Babel 7 because fix isn't released yet, but I could backport it.

You're using Typescript or Babel? How did you manage to combine jsLingui with typescript?

**Comment by mcku** [comment]
Part 1 -- as you know, `tsc` can generate output in two ways. One is the concatenated single file output, e.g., `dist/index.js`, and the other is the jsx output (when tsc is run, given the project's proper config). So the `dist/index.js` is a bundle structured in systemjs manner.. 

```
System.register("main/someComponent", [ "react", "lingui-react", .....], function (exports_35, context_35) {

<lingui_react_4.Trans>....</...>
``` 
Above, `lingui_react_4` was defined in `exports_35`. Is this supported? If so, that's what I saw in the typescript plugin.. Does it work and can it be made work in some manner, because it is a single file, output _build will not collide with multiple files...

Part 2. I am bundling typescript through webpack. I did not touch this pipeline at all.
I admit that I did not use any presets/plugins through .babelrc, instead, just used manual lingui cli command. The cli invokes `transformFileSync`, which invokes the babel plugins and generates the messages. Then the messages are already fed into the app because The app is wrapped with I18nProvider in tsx, and some <Trans> exist within some tsx files.
 
So I just run lingui extract and compile manually through bash such as
```
tsc && ./node_modules/.bin/lingui extract --verbose
``` 
This one creates a folder of jsx files, identical to the tsx source tree.
tsconfig.json:
```
{
    "compilerOptions": {
        "module": "esnext", 
        "target": "es6",
        "moduleResolution": "node",
        "baseUrl": "main",
        "allowSyntheticDefaultImports": true,
        "sourceMap": true,
        "outDir": "distJsx",
        "jsx": "preserve",
        "declaration": false,
        "noImplicitAny": false,
        "experimentalDecorators": true,
        "removeComments": false
    },
    "include": [
      "main/index.tsx"
    ],
   "exclude": [
      "distJsx",
      "dist"
      "node_modules"
  ],
    "awesomeTypescriptLoaderOptions": {
        "forkChecker": true,
        "useBabel": true,
        "useCache": true,
	"babelCore": "@babel/core"
    },
    "compileOnSave": true
}
```

You get distJsx populated with jsx files upon running tsc. 
If you think anything could be better, just let me know.

in package.json
```
"lingui": {
    "localeDir": "<rootDir>/main/locale",
    "srcPathDirs": [
      "<rootDir>/distJsx"
    ],
    "srcPathIgnorePatterns": [
      "/node_modules/"
    ],
    "format": "lingui",
    "sourceLocale": "en"
  }
```

(for the single file scenario, I deleted distJsx content, did not run bare tsc (which honors tsconfig) but with argument --outFile which ignored tsconfig.json)

**Comment by tricoder42** [comment]
> Above, lingui_react_4 was defined in exports_35. Is this supported? If so, that's what I saw in the typescript plugin.. Does it work and can it be made work in some manner, because it is a single file, output _build will not collide with multiple files...

No, at least not at the moment.

> Part 2

This should work (amazing workflow to be honest). I see you're using `@babel/core` (Babel 7), so I guess this is the same bug as I encountered. I'll backport patch to extract plugin asap.

**Comment by mcku** [comment]
> I'll backport patch to extract plugin asap.
Thanks. Does a patch exist somewhere already?

**Comment by tricoder42** [comment]
Yes, it's [this](https://github.com/lingui/js-lingui/blob/next-2/packages/babel-plugin-lingui-extract-messages/src/index.js#L218) line in `next-2` branch/

**Comment by tricoder42** [comment]
Released in:
 - babel-plugin-lingui-extract-messages@1.1.11
 - lingui-cli@1.4.3

Let me know if it helps

**Comment by tricoder42** [comment]
Ups, sorry, wrong branch (nothing new was released).

It's fixed in:
- babel-plugin-lingui-extract-messages@1.1.12
- lingui-cli@1.4.4

**Comment by mcku** [comment]
@tricoder42 It works perfectly!! Thanks so much.
