### ISSUE TITLE
Android Puffin TV browser unsupported since 3.17.1

### ISSUE THREAD

**Issue by Minishlink** [lingui/js-lingui#1509]
**Describe the bug**

We have some users who use our website on Puffin TV Browser, it's the only real browser that "works" on Android TV. We noticed that our website stopped working on this browser (white screen) after upgrading to 3.17.1. Downgrading to 3.17.0 works. 

Unfortunately, this browser doesn't provide developer logs (neither with adb logcat), so I don't have the precise error. I'm waiting for some information on their part about this. 

**To Reproduce**

We use lingui.js with macros (t).

**Additional context**

Tested with browserslist `since 2010` to be sure.

- jsLingui version ``lingui --version`` 3.17.1 or 3.17.2
- Babel version ``npm list @babel/core`` tested on Babel 7.18, 7.19, 7.20
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)

```js
module.exports = {
  presets: [
    ['react-app', { flow: false, typescript: true }]
  ],
  plugins: [
    'babel-plugin-styled-components',
    'lodash',
    'date-fns',
    'graphql-tag',
    'macros',
  ]
};
```

**Comment by thekip** [comment]
Probably it doesn't support latest ECMAScript features. You need to setup your build pipeline to transpile library code to the preferred version (to es5 for example)

**Comment by Minishlink** [comment]
Oops, looks like the lingui libraries were not transpiled during our build, yes, thanks
