### ISSUE TITLE
FEATURE REQUEST: V4 does not support extracting from code using legacy decorators

### ISSUE THREAD

**Issue by capaj** [lingui/js-lingui#1512]
**Describe the bug**
When I run this: lingui extract I am getting `SyntaxError: /home/capaj/work-repos/official/official-graphql2/graphql/src/models/love-buttons/LoveButtons.ts: Decorators cannot be used to decorate parameters. (63:4)`

**To Reproduce**
have a file like this:

```ts
import { Authorized, Ctx, Query, Resolver } from 'type-graphql'
import { IContext, IContextAuth } from '../makeAuthContext'
import {
  getActiveMembershipForUser,
  MembershipModel
} from '../models/MembershipModel'
import { i18n } from '@lingui/core'

@Resolver(MembershipModel)
export class MembershipResolver {
  @Authorized()
  @Query(() => MembershipModel, {
    nullable: true
  })
  activeMembership(@Ctx() ctx: IContextAuth) {
    const { user } = ctx
    return getActiveMembershipForUser(user?.aws_user_id)
  }
}

const message = i18n._('Hello worlkd')
```

**Expected behavior**
a message gets extracted

**Additional context**
When I remove all decorators from my files it works ok and extract my message as expected.

- jsLingui version ``lingui --version``: 4.0.0.next-1
- Babel version ``npm list @babel/core`` 7.21.0
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)

```
 {
    plugins: [
      '@babel/plugin-transform-typescript',
      ['@babel/plugin-proposal-decorators', { legacy: true }],
      ['@babel/plugin-proposal-class-properties', { loose: true }],
      'macros'
    ]
  }
```

**Comment by thekip** [comment]
try this: 

```ts
// lingui.config.js
extractorParserOptions: {
  decoratorsBeforeExport: true
}
```

**Comment by thekip** [comment]
Not very popular case for React projects. I will add a fix.

**Comment by capaj** [comment]
oh we cannot use linguijs with legacy decorators ATM, certainly not 4.0.0.next-1

because this array
https://github.com/lingui/js-lingui/blob/580e7027032044c927f3b77b0c414e3f7950670e/packages/cli/src/api/extractors/babel.ts#L81-L94

cannot be extended from `lingui.config.js`

and this https://github.com/lingui/js-lingui/blob/580e7027032044c927f3b77b0c414e3f7950670e/packages/cli/src/api/extractors/babel.ts#L33

initializes with the new decoratos always, but babel does not allow both legacy and new decorators at once. So you will end up with an error from babel.

**Comment by capaj** [comment]
@thekip time to use my GIF  <img src="https://media4.giphy.com/media/PER8oVobtMcus/giphy.gif"/>

**Comment by capaj** [comment]
also what is the point of `extractBabelOptions` if they don't get applied?

**Comment by thekip** [comment]
https://js-lingui-git-next-lingui.vercel.app/releases/migration-4#extractor-configuration-changes

**Comment by capaj** [comment]
In the migration change notes it's not obvious that the extractBabelOptions are not even used anymore. 
This can cause confusion for people who still use them. IMHO it would be better to throw error and terminate extraction process when `extractBabelOptions` is detected.

**Comment by thekip** [comment]
There is already a deprecation warning when you try to use this option. The current policy for deprecation warnings is not terminating the process.
