### ISSUE TITLE
minify named variables in production bundle

### ISSUE THREAD

**Issue by taozhou-glean** [lingui/js-lingui#1516]
I noticed that in the production code, even tho all extra fields (comment etc) are stripped, we do preserve named variables, like:

```
const formattedTeamSize = format(teamSize)
plural(teamSize, {one: '1 person', other: `${formattedTeamSize} people`})

// msgid "{teamSize, plural, one {1 person} other {{formattedTeamSize} people}}"

// in production this compiles to
x._({
    id: "F1A7YV",
    message: "{teamSize, plural, one {1 person} other {{formattedTeamSize} people}}",
    values: {
        teamSize: f,
        formattedTeamSize: j
    }
})
```

it seems to be doable to reformat them into minimized variables like 0...x, so we have minified code in production:

```
x._({
    id: "F1A7YV",
    message: "{0, plural, one {1 person} other {{1} people}}",
    values: {
        0: f,
        1: j
    }
})
```

**Comment by thekip** [comment]
This is not possible to do. The implementation would be fragile in most of the cases. Translators can move placeholders in the messages, so relaying on the index is not going to work. Because in English it might be one order and on the other language - another.

**Comment by taozhou-glean** [comment]
> This is not possible to do. The implementation would be fragile in most of the cases. Translators can move placeholders in the messages, so relaying on the index is not going to work. Because in English it might be one order and on the other language - another.

I am not saying we should rely on `index`, (0...x) is just an example to minify it, we can certainly minify it by with chars (a...z), since we still have the original name in the placeholders, so as long as we keep the reference used in `message` and `values` the same, it should still be doable right ?

**Comment by thekip** [comment]
You can try, don't forget about Rust implementation for SWC

**Comment by taozhou-glean** [comment]
I see your point now, what I was thinking is is to do it per message, so we don't need global counter:

1. collect variables from the message
2. sort them alphabetically (consistent)
3. then just replace with the either 0...9, or a...z

just some initial thoughts, I might miss something obviously here...

while I completely agree that it's likely not gonna save a lot bytes as variables are probably only a small percent of the total catalog.

**Comment by thekip** [comment]
that might work, but you missing that there are users who not using macro. This will break variables interpolation for them. 

And also this is going to affect 

- babel-macro
- swc-plugin
- extractor

Quite a big scope.
