### ISSUE TITLE
`invalid syntax` if choice keys contains `-`

### ISSUE THREAD

**Issue by taozhou-glean** [lingui/js-lingui#1528]
**Describe the bug**
```
invalid syntax at line 1 col 28:

1  {variant, select, other {t} d-1 {d-1}}
                              ^

Message: {variant, select, other {t} d-1 {d-1}}
```

tested on https://format-message.github.io/icu-message-format-for-translators/editor.html and seems valid:

<img width="684" alt="image" src="https://user-images.githubusercontent.com/121891361/225731052-63fa8980-8f64-404e-8050-a741bfc596c2.png">

**Comment by taozhou-glean** [comment]
looks like this is from the dependency and probably intended behavior: https://github.com/messageformat/messageformat/issues/195

**Comment by andrii-bodnar** [comment]
@taozhou-glean thanks for investigating this. Probably we can close this issue, what do you think?

**Comment by taozhou-glean** [comment]
ya let's close it. It's not really actionable on lingui's side
