### ISSUE TITLE
[v4] space missing within nested Trans (between elements)

### ISSUE THREAD

**Issue by taozhou-glean** [lingui/js-lingui#1529]
**Describe the bug**

probably related to this new change: https://js-lingui-qmrh9gqtf-lingui.vercel.app/releases/migration-4#change-in-generated-icu-messages-for-nested-jsx-macros

```
<Trans>
  Shared
  <Select yesterday="Yesterday" other="" value={when} />
</Trans>

#. js-lingui-id: hQLbA0
msgid "Shared{when, select, yesterday {Yesterday} other {}}"
msgstr "Shared{when, select, yesterday {Yesterday} other {}}"
```

expect it to be 
```
msgid "Shared {when, select, yesterday {Yesterday} other {}}"
msgstr "Shared {when, select, yesterday {Yesterday} other {}}"
```

to preserve the space between elements, especially for `Trans` i think we expect it to be an inline elements, so that also aligns how browser will treat the whitespaces: https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace

**Comment by taozhou-glean** [comment]
the workaround for now seems to be either adding `{' '}` after Shared or adding `&nbsp;` explicitly, both are not perfect as spaces may not make sense in some other languages, especially `&nbsp;` which is non-breaking.

**Comment by taozhou-glean** [comment]
well

```
<Trans>
  Shared  <Select yesterday="Yesterday" other="" value={when} />
</Trans>
```
produced expected result:
```
msgid "Shared {when, select, yesterday {Yesterday} other {}}"
msgstr "Shared {when, select, yesterday {Yesterday} other {}}"
```

and I just noticed that we also handle `{' '}` as forced whitespace. So this might be working as intended with linter like `prettier` which will add `{' '}` when wrap long lines

**Comment by thekip** [comment]
i think it's intended. There are unit tests which i wrote while working on SWC plugin, you can check them to understand corner cases. 

By the way, i think all this "whitespace normalization" should not exists, but we have what we have.

**Comment by vonovak** [comment]
> i think it's intended. There are unit tests which i wrote while working on SWC plugin, you can check them to understand corner cases.
> 
> By the way, i think all this "whitespace normalization" should not exists, but we have what we have.

@thekip quick question: is the whitespaces behavior documented somewhere? Regardless of what the behavior _is_ and what it _should be_ I feel like we should document the behavior explicitly so that users know how it behaves and so that we have a place to point them to in case of questions. Thanks ;)

**Comment by andrii-bodnar** [comment]
Guys, how can we address this issue? Adding docs clarifying the whitespaces behavior?
