### ISSUE TITLE
Deprecating Snowpack Plugin

### ISSUE THREAD

**Issue by thekip** [lingui/js-lingui#1530]
Snowpack plugin has only 15 downloads per week and not updated for a long time. Snowpack itself is deprecated as well. 

I'm proposing deprecating it in version 3.* and remove from codebase in version 4. 

Todo list: 

- [ ] Add deprecation / unmaintained notice in Readme of a package
- [ ] Push package with notice to NPM
- [ ] Remove package from repository

**Comment by thekip** [comment]
Whatever, just let's do it.

**Comment by andrii-bodnar** [comment]
I do not have enough permissions to deprecate the [@lingui/snowpack-plugin](https://www.npmjs.com/package/@lingui/snowpack-plugin). @semoal could you please take a look?
