### ISSUE TITLE
Use MESSAGE as default for ID when extracting messages from non-transpiled code

### ISSUE THREAD

**Issue by trygvea** [lingui/js-lingui#1559]
**Is your feature request related to a problem? Please describe.**
We sometimes use lingui for simple node apps with no transpilation. We create messages using this pattern: 
```js
  const message = i18n._(/*i18n*/{
    id: "app.greeting",
    message:"Hello {name}",
    values: {name}
  });
```
Today, the `id` attribute is required when running `extract` on messages using `i18n._`. 

But, it would be awesome if we could make the lingui experience for non-transpiled projects similar to that for transpiled projects, and we could just write:
```js
  const message = i18n._(/*i18n*/{
    message:"Hello {name}",
    values: {name}
  });
```
so it will look similar to when  using for instance the `defineMessage` macro:
```js
  defineMessage({
    message: `Hello ${name}`
  });
```

**Describe proposed solution**
The proposed solution is to use `message` as default for `id`, allowing for the construct above.

**Describe alternatives you've considered**
We know that if we let the `id` contain the message, the `message` will be set, like this:
```js
  const message = i18n._(/*i18n*/{
    id: "Hello {name}",
    values: {name}
  });
```
This will work, but it looks wrong to the developer. It would be more consistent if both `defineMessage` and `i18n._` would use the `message` parameter.

**Additional context**
We're currently testing on branch next on version 4.0.0.next.3.

**Comment by thekip** [comment]
```ts
 const message = i18n._(/*i18n*/{
    id: "Hello {name}",
    values: {name}
  });
```

This is exactly how it's intended to be. I'm not sure runtime will use message as key for resolving. I'm not really in for that change....

**Comment by trygvea** [comment]
Ok, I accept that 👍 
I didnt think about the runtime, and that might be a bigger change.
