### ISSUE TITLE
Lingui with vue project as vanilla js docs

### ISSUE THREAD

**Issue by wusaby-rush** [lingui/js-lingui#1567]
**Describe the bug**
I tried use lingui in vue project with vite, as vanilla js docs, but I have error `No known conditions for "./api" specifier in "@lingui/cli" package`, also I tried but t`message` inside template and inside script but `lingui extract` doesn't extract anything.

**To Reproduce**
I followed js docs page 

```json
// package.jsons
  "dependencies": {
    "@lingui/core": "^4.0.0-next.4",
    "vue": "^3.2.47"
  },
  "devDependencies": {
    "@babel/preset-env": "^7.20.2",
    "@lingui/cli": "^4.0.0-next.4",
    "@lingui/macro": "^4.0.0-next.4",
    "@lingui/vite-plugin": "^4.0.0-next.4",
    "@vitejs/plugin-vue": "^4.1.0",
    "typescript": "^4.9.3",
    "vite": "^4.2.0",
    "vite-plugin-babel-macros": "^1.0.6",
    "vue-tsc": "^1.2.0"
  }
```

```ts
// vite.config
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import { lingui } from "@lingui/vite-plugin";
import macros from "vite-plugin-babel-macros";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    lingui(),
    macros()
});
```

- jsLingui version `4.0.0-next.4`
- Babel version `7.21.3`

**Comment by thekip** [comment]
Please create a minimal repo

**Comment by wusaby-rush** [comment]
It is ready 

https://gitlab.com/wusaby-rush/linguijs-example/-/tree/vue?ref_type=heads

**Comment by thekip** [comment]
> 1. `npm run message:extract` doesnt extract any thing in `.vue` files, but work with ts files. see `main.ts` and `App.vue`

This works as expected. Extractor don't understand vue files, but can be easily extended to support them. Looks at [this page ](https://js-lingui-git-next-lingui.vercel.app/guides/custom-extractor)

**Comment by j4hr3n** [comment]
Following up here @thekip:

I'm trying to write a custom extractor for Vue. I noticed that the suggest import in the docs which is:

```
import babel  from '@lingui/cli/api/extractors/babel'; // 
```

Simply yields _Cannot find module '@lingui/cli/api/extractors/babel' or its corresponding type declarations._

**Comment by thekip** [comment]
@j4hr3n it's known issue, typings for `@lingui/cli/api` is not generated by build.

**Comment by thekip** [comment]
@wusaby-rush 

> lingui macro have error No known conditions for "./api" specifier in "@lingui/cli" package

The problem is that "vite-plugin-babel-macros" is not processing `.vue` files. I googled, but didn't find a clear solution how to post-process `.vue` files with babel.

**Comment by j4hr3n** [comment]
@thekip, @wusaby-rush 

I have a vue extractor working for script and script setups on my end already, only issue is that the typings are off.


```
import * as vueCompiler from 'vue/compiler-sfc';
import babel from '@lingui/cli/api/extractors/babel';
import { ExtractorCtx, ExtractorType } from '@lingui/conf';

export const extractor: ExtractorType = {
  match(filename: string) {
    return filename.endsWith('.vue');
  },
  extract(
    filename: string,
    code: string,
    onMessageExtracted,
    ctx: ExtractorCtx,
  ) {
    // transform to plain JS + Sourcemaps
    const {
      descriptor: { script, scriptSetup },
    } = vueCompiler.parse(code, { sourceMap: true, filename });

    const finalCode = `${script?.content} ${scriptSetup?.content}`;

    // reuse extractor from cli
    return babel.extract(filename, finalCode, onMessageExtracted, {
      sourcemaps: undefined,
      ...ctx,
    });
  },
};
```

Still very much a work in progress though. But was able to extract a string from a Vue component of mine.

**Comment by wusaby-rush** [comment]
> > 1. `npm run message:extract` doesnt extract any thing in `.vue` files, but work with ts files. see `main.ts` and `App.vue`
> 
> This works as expected. Extractor don't understand vue files, but can be easily extended to support them. Looks at [this page ](https://js-lingui-git-next-lingui.vercel.app/guides/custom-extractor)

`transformMyCustomFileToJs` what should I put instead of this function, function defination doesnt exist

**Comment by wusaby-rush** [comment]
> Following up here @thekip:
> 
> I'm trying to write a custom extractor for Vue. I noticed that the suggest import in the docs which is:
> 
> ```
> import babel  from '@lingui/cli/api/extractors/babel'; // 
> ```
> 
> Simply yields _Cannot find module '@lingui/cli/api/extractors/babel' or its corresponding type declarations._

code is running even with this error, I didint get this function `transformMyCustomFileToJs`

**Comment by thekip** [comment]
@wusaby-rush it's just an example. Replace this function with your **real** function which will transform your custom (say `.vue`) file to pure js which extractor could understand. Also @j4hr3n already posted a custom extractor for vue files. 

Anyway, linguijs is not officially support vue, and i don't have a capacity to make it work with vue and provide any help. So you would be on your own.

**Comment by wusaby-rush** [comment]
> @wusaby-rush it's just an example. Replace this function with your **real** function which will transform your custom (say `.vue`) file to pure js which extractor could understand. Also @j4hr3n already posted a custom extractor for vue files.
> 
> Anyway, linguijs is not officially support vue, and i don't have a capacity to make it work with vue and provide any help. So you would be on your own.

thank you I get it now, and for @j4hr3n I appreciate for your help

**Comment by andrii-bodnar** [comment]
@thekip is it possible to distribute extractors as NPM packages similar to custom formatters?

**Comment by thekip** [comment]
Yes, it's possible, why not?

**Comment by j4hr3n** [comment]
@andrii-bodnar, @thekip 

I've put up a draft PR for a new package with vue extractor.

https://github.com/lingui/js-lingui/pull/1578
