### ISSUE TITLE
Is it possible use @lingui/macro with webpack plugin?

### ISSUE THREAD

**Issue by yunsii** [lingui/js-lingui#1572]
**Is your feature request related to a problem? Please describe.**
I want to use https://github.com/antfu/unplugin-auto-import to auto import Trans and more components from @lingui/macro. But after I add @lingui/swc-plugin and unplugin-auto-import/webpack in Next.js project. It not work as expected.

After dive into bundle js source code, it look like swc-loader transform before webpack plugin, so the bundle code is still use @lingui/macro, not @lingui/react. So maybe webpack plugin is a better solution to replace @lingui/swc-plugin?

**Describe proposed solution**
Transformation through webpack plugin?

**Comment by thekip** [comment]
That case is not supported and would be never supported. `@lingui/swc-plugin` as well as `babel-macro-plugin` doing a lot of things in compile time and statically analyze your code including imports.
