### ISSUE TITLE
v4 .po files cannot be saved with POEdit

### ISSUE THREAD

**Issue by ptmkenny** [lingui/js-lingui#1573]
**Describe the bug**

I've been using POEdit as a GUI to translate my app.

My app uses explicit ids for all strings.

However, after updating to v4, after opening a file output by `lingui extract` in POEdit, editing it, and saving it, when I re-run `lingui extract --clean --overwrite` to update the strings, **all the changes in POEdit are removed**.

**To Reproduce**

1. Generate a lingui PO file that contains strings with explicit IDs.
2. Edit the file in POEdit. Save.
3. Run `lingui extract`.  The edits are deleted (if using `--clean --overwrite`) or new strings are generated (if just running `extract` with no options).

**Expected behavior**

Edits should be kept.

**Additional context**

I think what is going on is that since v4, lingui now adds a flag to PO files: `#, explicit-id`.  However, POEdit doesn't know how to handle this, and it removes the flag on save.  So this causes Lingui to recreate the strings fresh and remove the strings saved by POEdit (that lack a `#, explicit-id`).

- jsLingui version ``lingui --version``
4.0-next4

**Comment by thekip** [comment]
Confirmed, POEditor removes flags which could not handle. I see only one way to fix that. Move this flags to the comments, as it's done in `po-gettext` formatter. It seems POEdit preserve comments in po files.
