### ISSUE TITLE
Create example on other repos

### ISSUE THREAD

**Issue by sedubois** [lingui/js-lingui#158]
To gain visibility I think it would be super useful to demonstrate the integration of js-lingui in other popular frameworks/libs, such as https://github.com/gatsbyjs/gatsby and https://github.com/zeit/next.js.

That's easy to say for me because unfortunately I have no time to contribute pull requests! But this looks like an inspiring project and I think it might deserve to be more visible, especially now that v2 is out.

**Comment by tricoder42** [comment]
I can't agree more. I'm a bit overwhelmed by work atm, but hopefully at the end of February I could focus on this.

**Comment by morloy** [comment]
We're migrating our [website](https://www.ledgy.com) to jslingui now, but it's still a work-in-progress.

After a few hours of work I finally figured out how to integrate it with Gatsby.
If you follow the official documentation, some extra steps are necessary (instructions might be incomplete):
1. [Upgrade Gatsby to React v16](https://www.npmjs.com/package/gatsby-plugin-react-next)
2. Manually install react-dom v16: 
```
npm i --save react-dom
```
3. Create a custom `.babelrc` with the following content:
```
{
  "plugins": [
    "@lingui/babel-plugin-transform-js",
    "@lingui/babel-plugin-transform-react",
  ],
  "env": {
    "extract": {
      "presets": [
        "@babel/preset-react",
        "@babel/preset-flow",
      ]
    },
  }
}
```
4. Extracting languages requires a different version of Babel, thus run it with:
```
BABEL_ENV=extract lingui extract
```

#### Hot reloading
You can directly use the `messages.json` in Gatsby:
```
import en from '../locale/en/messages.json';

export default () => (
  <I18nProvider language="en" catalogs={{ en: { messages: en } }}>
    <App />
  </I18nProvider>
);
```

**Comment by tricoder42** [comment]
@morloy This is great stuff, thank you for sharing! I've never worked with Gatsby, but as a static site tool it always operates in development mode?

**Comment by morloy** [comment]
No, but when you build the site, I think everything gets bundled and minified with webpack. So no need to actually "compile" the `messages.json`. However, I haven't tested with complex features like plurals, etc.

**Comment by tricoder42** [comment]
The problem might be when you use variables or plurals inside translations. Then you'll probably have to use either compiled message catalog or `@lingui/loader` webpack loader which compiles catalogs on the fly.

**Comment by morloy** [comment]
We've now finished with finished the redesign of your company website using GatsbyJS and js-lingui.
Have a look at the result at [Ledgy.com](https://www.ledgy.com) and of course the [source](https://github.com/morloy/ledgy.com) to learn how to run the two together.

**Comment by tricoder42** [comment]
This is really great! I'm gonna create showcase page in docs soon. Thank you for your effort!  👍

**Comment by pcraig3** [comment]
Hey there @tricoder42, thanks for all your effort thus far! Lingui looks like a super interesting project. Specifically, we've found the locale files very easy to work with and we would love to use it more broadly. We've been experimenting with it at work and had some good results in the past, but then some not-so-good results more recently.

- We tried integrating it with Next.js recently, but couldn't figure out how to get it going. 
- I also tried hooking it into a new `create-react-app` project, using the [next](https://github.com/facebook/create-react-app/issues/3815) branch (which uses babel 7) and following along with [your tutorial](https://lingui.github.io/js-lingui/tutorials/react.html), but in the end I couldn't get the translations to show up. (I can upload the code if that would be useful to you.)

Is there a sense of when more up-to-date instructions for integration with some JS frameworks might exist, or any other pointers you could pass along?

Again, this isn't urgent and it's cool what you've done so far, but if you have any more info it would be great to hear 😄.

**Comment by dcroitoru** [comment]
I created a Gatsby starter that makes use of js-lingui:
https://github.com/dcroitoru/gatsby-starter-i18n-lingui.git

**Comment by langpavel** [comment]
Can this be closed?

**Comment by tricoder42** [comment]
You're right, the scope of this issue is too broad. Let's focus on:

- [ ] Integration with GatsbyJS (guide, link to starter)
- [ ] Integration with Create React App (this was also requested at medium.com at it basically needs to document how to use lingui without babel plugins)

... and then close this issue.

What do you mean by `migrate react-intl branch of react-starter-kit`? Do you want to write migration guide from react-intl? Does react-starter-kit uses react-intl in a specific way?

**Comment by tricoder42** [comment]
Closing this one in favor of #278, CRA example will be added as part of 3.0 release

**Comment by dreadwail** [comment]
For those who come across this thread seeking a working example with Next.js, you can find it here now:

https://github.com/zeit/next.js/tree/canary/examples/with-lingui
