### ISSUE TITLE
Complete instructions to setup with preact+vite

### ISSUE THREAD

**Issue by K1DV5** [lingui/js-lingui#1580]
**Is your feature request related to a problem? Please describe.**
I had been struggling to integrate `lingui` to an existing app that's setup with `preact` and `vite` to no success, for one full day. The official docs only talk about `react` and `vite` and when I tried to follow those, I got many errors. It was only after I found https://github.com/MatteoWebDeveloper/internationalisation-js-lingui mentioned in the issues here that I was able to get it to work.

**Describe proposed solution**
A clear example to setup `lingui` with `preact` and `vite` would be good to newcomers like me.

**Describe alternatives you've considered**
I tried finding help elsewhere on the internet but they all talk about `react`.

**Additional context**
None

**Comment by K1DV5** [comment]
Yes I saw those, but there are some nuances:
* I didn't have the `package.json` entries at https://github.com/MatteoWebDeveloper/internationalisation-js-lingui/blob/d0a106fdaa59cac2963e3e63ef0b89dce7bb8e77/package.json#L15 (aliasing `react` and `react-dom` to `preact/compat`)
* The `vite` setup doesn't say anything about `vite-plugin-babel-macros` https://github.com/MatteoWebDeveloper/internationalisation-js-lingui/blob/d0a106fdaa59cac2963e3e63ef0b89dce7bb8e77/vite.config.js#L2 
* The `vite` setup only talks about `lingui.config.ts` which, when I tried to convert to `js` (because I don't use `typescript`),
    * When the project type in `package.json` is `module`, and the file is formatted as such, lingui doesn't support it.
    * When it is in `cjs` format, lingui says `No locales defined` and `babel` doesn't recognize all `jsx` as valid.
    * Only `.linguirc` format worked.
* There may be other things I missed but these are what I remember.

**Comment by thekip** [comment]
@K1DV5 there are so many variations of setup / usage may appear in the userland. We just could not provide guide/example for every of them. The general guidelines are provided in the docs, you should adopt it for your exact project by your own. 

> The vite setup doesn't say anything about vite-plugin-babel-macros
You don't need it for `@preact/preset-vite` as well. You can pass babel plugins directly to @preact/preset-vite`. Please read a documentation of tools you are going to use.  https://github.com/preactjs/preset-vite#babel-configuration

> The vite setup only talks about lingui.config.ts which, when I tried to convert to js (because I don't use typescript),
There is ongoing work on support ESM in version 4. I believe this is already fixed in v4. Give it a try.

**Comment by K1DV5** [comment]
I didn't mean to say that you should support my special use case and I apologize if I sounded like that. What I'm saying is, even a little clue like a link to a repo such as the one I mentioned would have been nice because, as I found out, this is not an easy thing to adopt. For example:

> You don't need it for @preact/preset-vite either. You can pass babel plugins directly to @preact/preset-vite`

I tried this (from `lingui` docs, only changed `react` to `preact`) by passing
```javascript
  plugins: [
    preact({
      babel: {
        plugins: ["macros"]
      }
    }),
    lingui()
  ]
```
in `vite.config.js` plugins but I got `Uncaught SyntaxError: The requested module ...node_modules/@lingui/macro/build/index.js does not provide an export named 't'` (trying to `import { t } from '@lingui/macro'` so I think I still need `vite-plugin-babel-macros`.

And thank you for the explanation about the ESM config. I'll give it a try.

**Comment by thekip** [comment]
>  so I think I still need vite-plugin-babel-macros

`vite-plugin-babel-macros` just doing an additional babel pass with only one plugin enabled. It's not a good for build performance at all.
I don't know how `@preact/preset-vite` works, but if they declared they support babel plugins passing "macros" it should work. Otherwise need to create an issue on theirs side. 

Create a minimal repo with configuration please, i will try to have a look, how to setup it in the best way.

**Comment by K1DV5** [comment]
https://github.com/K1DV5/vite-preact-lingui-example

All I did was initialize a `preact` project from https://vitejs.dev/guide/ and follow https://lingui.dev/tutorials/setup-vite (with some changes like `.linguirc`). When I get to checking the installation like
```
npm run extract
``
Babel complains.

**Comment by thekip** [comment]
use v4. There are no sense to start a new project with v3 now. 

https://github.com/K1DV5/vite-preact-lingui-example/pull/1/files

**Comment by K1DV5** [comment]
Thanks, that seems to work perfectly. The reason I was still on v3 is because it's the latest published stable version. Anyways, thank you for your attention.

**Comment by thekip** [comment]
v4 is stable. The reason it is under the `next` is because we wantto gather feedback from users migrating from v3 before rolling out it as stable. If you start a new project - safely use v4.

**Comment by K1DV5** [comment]
Alright, I'm on it now. Thank you.
