### ISSUE TITLE
Using i18n utilities outside React but populating config from I18nProvider

### ISSUE THREAD

**Issue by ikhilko** [lingui/js-lingui#159]
Hi, I'm trying to use your library in my react-native project. I'm using redux-saga and in some situations I need to call i18n api's outside React components (e.g. in sagas to show native Alert).
So I have done configuration with I18nProvider and then use Trans, i18n.t and other things in components. And that works well! But looks like I cannot use i18n from @lingui/core telling using I18nProvider options (language, catalogues). Can you help me with it? Thanks

**Comment by tricoder42** [comment]
Hey @ikhilko,
you can create your own `i18n` core object using `setupI18n` from `@lingui/core` and pass this object as an argument to `I18nProvider`. Once you have it, you should be able to use your `i18n` object everywhere outside React context.

Does it make sense? Please try it out and tell me if it works for you

**Comment by ikhilko** [comment]
@tricoder42 yes, it works! thanks

**Comment by rssfrncs** [comment]
@tricoder42 is any of @lingui/core documented? I have a similar requirement.

**Comment by tricoder42** [comment]
There's a new tutorial for [common i18n patterns](https://lingui.github.io/js-lingui/tutorials/react-patterns.html) and documentation for [@lingui/core](https://lingui.github.io/js-lingui/ref/core.html)
