### ISSUE TITLE
[v4] fail to resolve `../package.json` after next.6

### ISSUE THREAD

**Issue by taozhou-glean** [lingui/js-lingui#1596]
getting following errors after upgrading to next.6

```
Error: ENOENT: no such file or directory, open '../package.json'
    at Object.openSync (node:fs:589:3)
    at readFileSync (node:fs:457:35)
    at Object.<anonymous> (/Users/xxx/node_modules/@lingui/cli/dist/lingui.js:6:59)
```

**Comment by lecstor** [comment]
fyi, changing `../package.json` to `./package.json` in `node_modules/@lingui/cli/dist/lingui.js` resolves this.

**Comment by taozhou-glean** [comment]
> fyi, changing `../package.json` to `./package.json` in `node_modules/@lingui/cli/dist/lingui.js` resolves this.

I think that's probably because you have a `package.json` under current path, but it's likely pulling the wrong package.json file, https://github.com/lingui/js-lingui/pull/1597 should fix it properly ;)

**Comment by lecstor** [comment]
I did think it was odd, but didn't think much more about it 😄 
thanks.
