### ISSUE TITLE
@lingui/loader `strict` should not calculate from process.env.NODE_ENV

### ISSUE THREAD

**Issue by yunsii** [lingui/js-lingui#1598]
**Describe the bug**
When I set NODE_ENV to "test", the result of [`strict`](https://github.com/lingui/js-lingui/blob/main/packages/loader/src/webpackLoader.ts#L79) is true.

After I deployed on server with Next.js, [process.env.NODE_ENV related code has been removed in client](https://github.com/lingui/js-lingui/blob/main/packages/core/src/i18n.ts#L218). It render first screen is okey, but after hydrated, render text by Plural's id instead.

**To Reproduce**
Just set NODE_ENV = "test" to build and start with `cross-env NODE_ENV=test next start`.

**Expected behavior**
Plural render correctly after hydrated.

**Additional context**
As a library under the hood, I think should not calculate any variable from process.env.NODE_ENV, let user configure it by themself.

- jsLingui version 3.17.2
- Babel version 7.19.0
- No extra configuration of babel

**Comment by yunsii** [comment]
> That's probably your case [lingui/swc-plugin#47](https://github.com/lingui/swc-plugin/pull/47)

I'm not sure that pr can resolve my question, only confirm @lingui/loader should compile message for any non dev env.

**Comment by thekip** [comment]
@yunsii have no idea how this patch should help, because `strict` in loader is not affecting message compilation. It's change only what error would be generated. 

You are not mentioned what you use in your configuration with nextjs, do you use babel + babel-macro or SWC? 

> I think should not calculate any variable from process.env.NODE_ENV, let user configure it by themself.

This is a convention which is works well. Anyway, there are no many ways to achieve that

**Comment by yunsii** [comment]
SWC plugin, I will try to create a reproduce demo later.

**Comment by thekip** [comment]
@yunsii you also have to update other lingui packages to v4, v4 swc-plugin produces code compatible with v4 core only.

**Comment by yunsii** [comment]
@andrii-bodnar @thekip Thanks, I will try it out today.

**Comment by yunsii** [comment]
@andrii-bodnar  @thekip it seems to solve this problem, the next version is recommend to use in production env for now?

**Comment by thekip** [comment]
@yunsii yes, you can use it in production. It's pretty much finished, no breaking changes are planned.
