### ISSUE TITLE
Lint Warnings

### ISSUE THREAD

**Issue by afrankel-sfdo** [lingui/js-lingui#161]
The default create react app linting rules throw warnings for the formatting of messages.js
```
./src/locale/en_US/messages.js
    Line 10:  Expected '===' and instead saw '=='  eqeqeq
    Line 10:  Expected '!==' and instead saw '!='  eqeqeq
```

**Comment by thibautRe** [comment]
Since this file is generated, I suggest ignoring the whole `./src/locale` directory in your eslint config.

I haven't tried it out, but if you add a `.eslintignore` file at the root of the repo with the following content inside, that should do it

```
./src/locale
```

**Comment by tricoder42** [comment]
Hey @afrankel-sfdo,
as @thibautRe suggests, this seems to be a viable option. The `messages.js` file is generated and minified. I guess using `==` instead of `===` is part of minification.

**Comment by afrankel-sfdo** [comment]
@thibautRe @tricoder42 thanks for the quick response, this solution makes sense, and worked for me!
