### ISSUE TITLE
convert-from json/lingui doesnt work as expected

### ISSUE THREAD

**Issue by sirpy** [lingui/js-lingui#1641]
**Describe the bug**
Having translations in json format and a new lingui config set to "po" format
Running extract --convert-from minimal doesnt copy the already translated strings
Converting from "minimal" to "lingui" works partialy, the translated strings is converted to an array of chars and there's a field "obsolete:true", sources are missing

**To Reproduce**
1. have translated messages in minimal/lingui format
2. set lingui config to use "po" format
3. run lingui extract --convert-from minimal/lingui

**Expected behavior**
Translated strings are copied to new format

**Additional context**
Converting from "minimal" to "lingui" does work as expected

- jsLingui version 4.0.0
- Macro support:
 - [x] I'm using SWC with `@lingui/swc-plugin`
 - [ ] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, NextJs, Vite)

**Comment by thekip** [comment]
Unfortunately, this functionality was completely abandoned due to lack of interest from my side (and absence of unit tests from previous contributors). 

We are happily accept PR's fixing this. Or you can do the converting as one time job manually for your codebase. Using existing formatters this should be pretty straightforward to do.

**Comment by sirpy** [comment]
@thekip can you explain how to do it manually?

**Comment by thekip** [comment]
> fs.readFile() -> oldformat.parse() -> newFormat.serialize() -> fs.writeFile() 

You can import formatters in your code as 

```ts
// pseudocode, i didn't test it 
import { formatter as createPoFormatter  } from "@lingui/format-po"
import { formatter as createJsonFormatter  } from "@lingui/format-json"
import fs from "fs/promises"

const poFormatter = createPoFormatter()
const jsonFormatter = createJsonFormatter()

async main() {
  const catalog = jsonFormatter.parse(await fs.readFile('myfile.json', "utf8"));
  await fs.writeFile('myfile.po', poFormatter.serialize(newFileConent))
  console.log('Done!')
}

main();
```

**Comment by sirpy** [comment]
same issue, it does not serialize correctly the minimal json format to any other format

**Comment by thekip** [comment]
What are you expecting as "correct"? minimal has a reduced amount of data comparing to other formats. Obviously, while converting, it will not take this from "nowhere".  

Do you use any [TMS](https://lingui.dev/tools/introduction)? If yes, it's easier to just re-export your strings from there in a proper format.

**Comment by sirpy** [comment]
When converting the minimal format to any other type, it will not keep the translation.
I did manual conversion like so:
```
const catalog = jsonFormatter.parse(fs.readFileSync(`src/language/locales/${item}/catalog.json`, 'utf8'))
    const newCatalog = {}
    Object.keys(catalog).forEach((k) => {
        newCatalog[k] = {
            translation: catalog[k],
            message: k,
            description: '',
            origin: [],
        }
    })
    const output = poFormatter.serialize(newCatalog, {})
```

Then i've encountered a new issue with the new msgids, my language files are using the previous msgids.
When running lingui extract, it doesnt seem to be using the new msg id format (hashes)
But when running the website it does show hashes instead of msg strings.
So all in all the migration process to V4 seems broken

**Comment by sirpy** [comment]
So it seems when extracting in "po" format it doesnt use hash msgid but in the UI I do see the msgid hash.
Is that the expected result? this makes it very hard to locate the missing translation

**Comment by thekip** [comment]
try this: 
```js
import { generateMessageId } from "@lingui/message-utils/generateMessageId"
const catalog = jsonFormatter.parse(fs.readFileSync(`src/language/locales/${item}/catalog.json`, 'utf8'))
    const newCatalog = {}
    Object.keys(catalog).forEach((k) => {
        newCatalog[generateMessageId(k)] = {
            translation: catalog[k],
            message: k,
            description: '',
            origin: [],
        }
    })
    const output = poFormatter.serialize(newCatalog, {})
```

**Comment by sirpy** [comment]
@thekip that wouldnt work as message id is also composed of context.
the only solution i found was to use `po` files. then copying previous translation from the json files.
also it seems that using the `lingui` format isnt working as the i8ln.load require a key-value json. dynamically loading po files seems to convert them to key value json but that doesnt happen with lingui raw json format. but that could be a vite lingui plugin issue.

**Comment by thekip** [comment]
for json files you have to use a different notation, otherwise plugin/loader will not recognize them from other not related json's. 

```js
// for other extension you have to use `?lingui` suffix
const { messages } = await import(`./locales/${language}.json?lingui`);
```

And yes, loading, minimal/lingui formats directly to `i18n.load` was never supported, as you need to compile your catalogs first. (it is not only convert `po` to `json` but also compiles ICU expressions)

**Comment by pniebrzydowski** [comment]
> And yes, loading, minimal/lingui formats directly to `i18n.load` was never supported, as you need to compile your catalogs first. (it is not only convert `po` to `json` but also compiles ICU expressions)

Do I understand correctly that there is then no way to load a translation catalog from an external source (e.g., CDN, AWS S3 bucket, separate project repository, etc) and every change in translation catalogs will require a new build?

**Comment by thekip** [comment]
@pniebrzydowski not really. Every translation catalog should be compiled before use in runtime. But this doesn't mean you need to re-build your whole application, only catalogs

You can compile catalogs and put them to an external source as compiled versions, OR you can put them as sources and compile on the fly (for example using some lambda or cloud function). Also take a look at https://github.com/lingui/js-lingui/tree/main/packages/remote-loader

**Comment by thekip** [comment]
Continuing the topic. Compiling on the fly has no official solution or tutorial. Actually `lingui compile` or bundler loaders doing many things under the hood (for example fallbackLanguages or template fallback) but if you don't need all these you simply need to generate hash for messages from its source using `@lingui/message-utils`. If you have any further questions you can ask them in our discord, we are happy to help.

**Comment by pniebrzydowski** [comment]
Thanks - with the `remote-loader` package, it appears that will only work with the JSON "minimal" format, correct?

**Comment by thekip** [comment]
The remote loader is quite abandoned, i mentioned it just as an example how it could be achieved. Here is a dedicated issue https://github.com/lingui/js-lingui/issues/1551
