### ISSUE TITLE
message hash as id (v4) for minimal format is useless

### ISSUE THREAD

**Issue by sirpy** [lingui/js-lingui#1642]
**Describe the bug**
When using minimal format the key for messages is now a message hash which makes it impossible to translate the message.
for example : ``` "8663Dz": ""```

**To Reproduce**
use minimal format with v4.0.0

**Expected behavior**
Key is the full message string

**Comment by thekip** [comment]
"minimal" json format is not standardized anyhow, so it's up to library how it should work. This is a major change of the version v4 and nothing actionable from library side. I recommend to use standartized `po` file format or you can write your [custom formatter](https://lingui.dev/guides/custom-formatter)
