### ISSUE TITLE
extractor is not exported in final build

### ISSUE THREAD

**Issue by seeden** [lingui/js-lingui#1648]
In version 4 extractor is undefined.
It is completely missing in compiled code of lingui. (it is in source code)

```ts
import { extractor } from '@lingui/cli/api';
```

**Comment by thekip** [comment]
Could you provide more details? Because I see it in compiled code

**Comment by thekip** [comment]
@andrii-bodnar i have no idea how that possible, but probably re-build and re-publishing packages should help

**Comment by thekip** [comment]
Fixed when republished with changes from v4.1. Closing it. Thanks for reporting.
