### ISSUE TITLE
vite preview isnt working

### ISSUE THREAD

**Issue by sirpy** [lingui/js-lingui#1649]
**Describe the bug**
when running vite preview the result is
`Cannot read properties of undefined (reading 'exclude')
    at config (/Users/hadar/workspace/GoodDollar/GoodProtocolUI/node_modules/@lingui/vite-plugin/dist/index.cjs:15:59)`

tested with both vite-plugin 4.0.0 and @next
removing lingui() from the plugins list works

**Comment by andrii-bodnar** [comment]
@sirpy please follow the [bug report template](https://github.com/lingui/js-lingui/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) and provide more details about the issue including steps to reproduce. Thanks!
