### ISSUE TITLE
Migration note for custom message IDs in v4

### ISSUE THREAD

**Issue by vituslehner** [lingui/js-lingui#1667]
**Is your feature request related to a problem? Please describe.**
When migrating from v3 to v4 and using custom message IDs, `lingui compile` will generate hash-based IDs in the resulting JS output file. Runtime lookups for messages fail because the custom ID can't be found within the hash-based message index.

To circumvent this, entries with custom IDs need to be marked with `#. js-lingui-explicit-id` in their PO files. I was not able to find this information in the docs.

**Describe proposed solution**
Add the flag to the documentation at an appropriate place. I may create a PR if you agree.

Please let me know if I was overlooking something. 
I think this should be stated or linked at least at the following places:
- https://lingui.dev/tutorials/react-patterns#using-custom-id
- https://lingui.dev/ref/catalog-formats#po-file-strongly-recommended
- https://lingui.dev/releases/migration-4#hash-based-message-id-generation-and-context-feature

**Comment by andrii-bodnar** [comment]
Thanks for the suggestion, at least it would be great to add this information to the migration guide.

@thekip what do you think?

**Comment by thekip** [comment]
Yes, it would be great. Also i think, for smother transition we can add a special parameter to poFormatter - "treat all ids as explicit", which will just swap logic for `#. js-lingui-explicit-id` and simplify migration for those who use only explicit ids.

**Comment by andrii-bodnar** [comment]
@vituslehner we would be happy to accept contributions to the v4 migration guide

**Comment by thekip** [comment]
Prepared: https://github.com/lingui/js-lingui/pull/1672
