### ISSUE TITLE
nextjs-swc is unusable

### ISSUE THREAD

**Issue by yunsii** [lingui/js-lingui#1673]
**Describe the bug**
First render by SSR:

`/es`
![image](https://github.com/lingui/swc-plugin/assets/18096089/c723635d-597e-4afb-8098-bfe997011862)

`/`
![image](https://github.com/lingui/swc-plugin/assets/18096089/ec12c52b-dc30-4fdb-8796-447da60bc305)

AboutText componnent do not translate completely. 

---

After change path by CSR: `/` => `/es`

![image](https://github.com/lingui/swc-plugin/assets/18096089/1305c3e7-c8d4-491c-aab9-a5c9b6465c22)

Developers component translation is still English translation. after CSR `/es` => `/` path it use Spanish translation. It looks like CSR always use previous translation. It is so ridiculous...

**To Reproduce**

https://github.com/lingui/js-lingui/tree/main/examples/nextjs-swc

**Expected behavior**

Use correct tranlation.

**Additional context**

- jsLingui version 4.1.2
- Macro support:
 - [x] I'm using SWC with `@lingui/swc-plugin`
 - [ ] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro
- Your framework you use NextJs 13.3.3

**Comment by thekip** [comment]
https://github.com/lingui/js-lingui/pull/1674

**Comment by yunsii** [comment]
Thanks for your work, the example works like a charm. By the way, when i update these deps
![image](https://github.com/lingui/js-lingui/assets/18096089/1fa3b3d0-36ed-4a0e-9007-6fddfe271f71)

i should update the usage too?

**Comment by yunsii** [comment]
https://github.com/lingui/js-lingui/blob/v4.0.0-next.7/website/docs/releases/migration-4.md
https://github.com/lingui/js-lingui/blob/main/website/docs/releases/migration-4.md
The document update too 😂

**Comment by thekip** [comment]
i don't think i've got the question. 
There are difference between v3 and v4. But i think there were no major changes between `-next.7` and final release.
