### ISSUE TITLE
Could not find a declaration file for module '@lingui/message-utils/compileMessage'

### ISSUE THREAD

**Issue by Nurtau** [lingui/js-lingui#1681]
**Describe the bug**
`core/dist/index.d.ts` does not see declaration file of`@lingui/message-utils/compileMessage`, that is why TypeScript compiler shows an error: 

```
/node_modules/@lingui/core/dist/index.d.ts(1,33): error TS7016: Could not find a declaration file for module '@lingui/message-utils/compileMessage'. '/node_modules/.pnpm/@lingui+message-utils@4.1.2/node_modules/@lingui/message-utils/compileMessage.js' implicitly has an 'any' type.
```

**To Reproduce**
1. Setup React application

> ```
>  npm create vite
> ```

2. Install Lingui packages "4.2.0":

>  ```
>    npm install --save-dev @lingui/cli @babel/core
>    npm install --save-dev @lingui/macro babel-plugin-macros
>    npm install --save @lingui/react @lingui/core
> ```

  
3. Go to /node_modules/@lingui/core/dist/index.d.ts.
4. Check its first line:` import { CompiledMessage } from '@lingui/message-utils/compileMessage';`

`index.d.ts` does not see declaration file of `@lingui/message-utils/compileMessage`

**Expected behavior**
Declaration file of `@lingui/message-utils/compileMessage` should be available, so TS compiler does not shown an error.

**Comment by thekip** [comment]
```json
"compilerOptions": {
  "skipLibCheck": true,
}
```

Please do not call TS compiler as Linter, it brings a confusion.

**Comment by Nurtau** [comment]
Thanks, it helped! Adjusted the message to avoid confusion

**Comment by thekip** [comment]
@yleflour thanks for the other solution. It might also be helpful for someone.
