### ISSUE TITLE
Clarification on "Picking a message based on a variable"

### ISSUE THREAD

**Issue by pakettiale** [lingui/js-lingui#1683]
**Is your feature request related to a problem? Please describe.**
I'm requesting clarification on the **Picking a message based on a variable** section here https://lingui.dev/tutorials/react-patterns#picking-a-message-based-on-a-variable .

With lingui v3 we were doing a lot of this to handle translations and pretty printing of enums and other things.
```tsx
import { msg } from "@lingui/macro";
import { useLingui } from "@lingui/react";

const statusMessages = {
   ['STATUS_OPEN']: t`Open`,
   ['STATUS_CLOSED']: t`Closed`,
   ['STATUS_CANCELLED']: t`Cancelled`,
   ['STATUS_COMPLETED']: t`Completed`,
}

export default function StatusDisplay({ statusCode }) {
   return <div>{statusMessages[statusCode]}</div>
}
```

The example  for v4 in docs suggest to wrap any use of `statusMessage[statusCode]` inside `i18n._` but wouldn't it be easier to do one of the following options? My primary motivation here is to reduce the amount of `i18n._` I have to sprinkle around the codebase.

**Describe proposed solution**

Solution A
```tsx
import { msg } from "@lingui/macro";
import { useLingui } from "@lingui/react";

const statusMessages = () => ({
   ['STATUS_OPEN']: t`Open`,
   ['STATUS_CLOSED']: t`Closed`,
   ['STATUS_CANCELLED']: t`Cancelled`,
   ['STATUS_COMPLETED']: t`Completed`,
})

export default function StatusDisplay({ statusCode }) {
   useLingui();
   return <div>{statusMessages()[statusCode]}</div>
}
```
Solution B
```tsx
import { msg } from "@lingui/macro";
import { useLingui } from "@lingui/react";

const statusMessages = (statusCode) => ({
   ['STATUS_OPEN']: t`Open`,
   ['STATUS_CLOSED']: t`Closed`,
   ['STATUS_CANCELLED']: t`Cancelled`,
   ['STATUS_COMPLETED']: t`Completed`,
}[statusCode])

export default function StatusDisplay({ statusCode }) {
   useLingui();
   return <div>{statusMessages(statusCode)}</div>
}
```

I would like to hear if there is something wrong with these snippets. First thing that comes to mind is that recreating the record every time `statusMessages` is called might cause performance issues with larger records.

**Comment by pakettiale** [comment]
This just came to mind to reduce unnecessary rebuilding of the record.

```tsx
import { msg } from "@lingui/macro";
import { useLingui } from "@lingui/react";

const getStatusMessages = () => ({
   ['STATUS_OPEN']: t`Open`,
   ['STATUS_CLOSED']: t`Closed`,
   ['STATUS_CANCELLED']: t`Cancelled`,
   ['STATUS_COMPLETED']: t`Completed`,
   ...
})


// following evaluates getStatusMessages only once and not ten times in one render
export default function StatusDisplay() {
   useLingui();
   const statusMessages = getStatusMessages()
   return <ul>
     <li>{statusMessages[statusCode1]}</li>
     <li>{statusMessages[statusCode2]}</li>
     <li>{statusMessages[statusCode3]}</li>
     <li>{statusMessages[statusCode4]}</li>
     <li>{statusMessages[statusCode5]}</li>
     <li>{statusMessages[statusCode6]}</li>
     <li>{statusMessages[statusCode7]}</li>
     <li>{statusMessages[statusCode8]}</li>
     <li>{statusMessages[statusCode9]}</li>
     <li>{statusMessages[statusCode10]}</li>
    </ul>
}
```

**Comment by thekip** [comment]
@pakettiale you get it right. There is nothing wrong with your snippets. The general rule is `t` should not be used in non-executable context, as stated in the docs. Then it doesn't matter would you use `msg`  macro or just wrap your definition in a function call. 

Also, i personally don't like usage of `useLingui()` with `t`. They are not linked to each other in code and it's hard to understand looking only to code why we need `useLingui()` hook and it's easy to forgot to add or remove this hook when refactoring. 

So approach with `i18n` is just more verbose and explicit.
