### ISSUE TITLE
lingui v4 with webpack5 + swc 

### ISSUE THREAD

**Issue by allroad88888888** [lingui/js-lingui#1687]
webpack+lingui+swc start error
failed to invoke `@lingui/swc-plugin` as js transform plugin at node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm

[demo](https://codesandbox.io/s/react-ts-webpack-2oqsin)

npm run serve

```tsx
import { createRoot } from "react-dom/client";
import React from "react";

const App = () => {
  return <div>demo</div>;
};

const $root = createRoot(document.getElementById("root") as Element);

$root.render(<App />);

```

- jsLingui version 4.2.0
- swc version 1.3.42
- Macro support:
 - I'm using SWC with `@lingui/swc-plugin`
.swcrc
```
{
  "$schema": "https://json.schemastore.org/swcrc",
  "jsc": {
      "target": "es2019",        
      "parser": {
          "tsx": true,
          "syntax": "typescript"
      },
      "transform": {
          "react": {
              "runtime": "automatic"
          }
      },
      "experimental": {
          "plugins": [
            [
                "@lingui/swc-plugin",{}
            ]
          ]
      }
  }
}
```

**Comment by thekip** [comment]
First Check [Compatibility Table](https://github.com/lingui/swc-plugin#compatibility)swc@1.3.42 is compatible with `@lingui/swc-plugin@4.0.0` - you have `4.0.1` 

Next, check this issue for `4.0.1`  known incompatibility https://github.com/lingui/swc-plugin/issues/61
