### ISSUE TITLE
@lingui/babel-preset-react not working in production mode

### ISSUE THREAD

**Issue by elios264** [lingui/js-lingui#169]
![capture](https://user-images.githubusercontent.com/15863852/36603438-5b7bf01a-1880-11e8-9f82-0091258d217c.PNG)

The section on the left fails to transform 
`i18n.t  'Sample'` to `i18n._("Sample")` (avoiding backticks because of github editor)

Not sure why, but switching to use the plugins directly works. 

This only fails in production :(

**Comment by ktunkiewicz** [comment]
I got the same issue. Using Webpack@3.10.0, Babel@7.0.0-beta.38 and js-lingui@2.0.4
Your fix doesn't work for me.

What I observed is that this only happens in "common" chunk (using CommonsChunkPlugin, in very basic configuration). It works fine in all other chunks.

The only difference between the develop and production build in our webpack configuration is this:
```
  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': '"production"',
    }),
    new webpack.optimize.UglifyJsPlugin({
      minimize: true,
      sourceMap: false,
      compress: {
        warnings: false,
      },
      mangle: true,
    }),
  ]
```

Couldn't find a fix. The only workaround I found is simply to find&replace all `i18n.t'(.*)'` (of course ' stands for backtick here) to `i18n._('$1')` in whole app... would be nice if someone figure this out.

**Comment by tricoder42** [comment]
Could you please try to replace preset with plugins?

**Comment by ktunkiewicz** [comment]
Hah! I found what was wrong.

Basically, you *cannot* do something like this:
```jsx
const SomeComponent = (props) => (
  <SomeOtherComponent
    label={props.i18n.t`Some text`}
  />
);
```

It has to be written like this:
```jsx
const SomeComponent = (props) => {
  const { i18n } = props;
  return (
    <SomeOtherComponent
      label={i18n.t`Some text`}
    />
  );
};
```

The babel plugin will simply not see your `i18n.t` if it is written down as `props.i18n.t`.

Should this be considered a bug or not?

PS. Changing preset to plugins doesn't make any difference.
PSS. I guess the reason why it is only visible in production builds is that in development we use the `message.json` files and the `@lingui/loader` so the `i18n.t` method is available. In production, when `message.js` file is used directly, the `i18n.t` is `undefined`. Am I correct?

**Comment by tricoder42** [comment]
Yeah, I would consider it bug, because this is annoying.

`i18n.t` is available in development only. In production, `i18n.t`, `i18n.plural` and other methods are replaced with `i18n._` which is low-level method for message formatting.

**Comment by tricoder42** [comment]
Closing in favor of #130, which is exactly the same issue.
