### ISSUE TITLE
[WIP] Create new, structured documentation

### ISSUE THREAD

**Issue by tricoder42** [lingui/js-lingui#17]
⚠️ **Work in progress**

[Documentation](https://lingui.github.io/js-lingui/)

# Website

- [ ] New homepage (based on https://date-fns.org/)
- [ ] Quick search bar
- [x] Auto build after commit to master
- [x] Make available package changelogs after release

# Content

## Tutorials

- [x] Javascript
- [x] React
- [x] CLI
- [x] Testing

## References

- [x] `lingui-i18n` - i18n for Javascript projects
- [x] `lingui-react` - React components build on top of `lingui-i18n` (resolved in #22)
- [x] `lingui-cli` and `lingui-conf`
- [x] `lingui-loader`
- [x] ICU MessageFormat

## Guides

- [x] Migrating from 0.x to 1.x
- [x] Working with pure components (`update`, `withHash` props)

## Discussions

- [ ] Performance
- [ ] Writing ICU MessageFormat by hand vs. babel-preset-lingui preprocessors
- [ ] Custom ID vs. default message for Message IDs (related #15)

**Comment by kirillku** [comment]
Thank you for a nice react tutorial. But have some troubles using cli tool.
Could you add to `lingui-cli` section, what is `_build` folder, why it is created and should it be committed?

**Comment by tricoder42** [comment]
@kirillku Absolutely, good point 👍 

In short: 
- `_build` folder contains temporary message catalogs, one per each processed source file (babel plugins operate on single file, so I can't generate one message catalog from all sources).
- it can be safely ignored as well as compiled message catalogs (`messages.js`). Only `messages.json` files should be in repository.

I'll push updated docs soon.

**Comment by Teloah** [comment]
Could you please also add a testing tutorial? Something of like this for React Intl: https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl
I'm mostly interested in testing using Jest and Enzyme.

**Comment by tricoder42** [comment]
Good point!

For now take a look at test cases for [example project](https://github.com/lingui/js-lingui/tree/master/examples/webpack-react/src/Usecases), especially [Children.test.js](https://github.com/lingui/js-lingui/blob/master/examples/webpack-react/src/Usecases/Children.test.js) shows the most common patterns.

**Comment by tricoder42** [comment]
@vonovak I'm gonna update contributor guide. Short answer:

1. Documentation uses [Sphinx](http://www.sphinx-doc.org/en/master/) and [reStructuredText](http://www.sphinx-doc.org/en/master/rest.html). It's inside `docs` directory.
2. To setup python virtualenv, run `pipenv install` inside `docs`
3. Run `make html` to build docs
4. After everychange, run `make html` to rebuild the docs. Incremental builds are much faster than first one

**Comment by tricoder42** [comment]
@vonovak Sorry, I forgot to mention `pipenv run`. Please try `pipenv run make html` inside `docs` directory. Once you have it (there might be few warnings), simply open `docs/_build/html/index.html` in your browser.

I would really like to use reStructuredText. Markdown is really nice and simple for small documents, but I like custom extensions to reStructuredText (e.g cli commands, components, etc). I could prepare docker image, but thanks to pipenv it's now very easy to install all dependencies and virtual environment. I just need to update contributing guide with correct steps.

Please let me know if it works for you!

**Comment by tricoder42** [comment]
@Teloah There's now a [testing guide](https://lingui.github.io/js-lingui/guides/testing.html)

**Comment by tricoder42** [comment]
Alright, I'm finally closing this one, because documentation is mostly complete. If you still feel there's something missing, please let me know!
