### ISSUE TITLE
Invalid dependencies have been reported by plugins or loaders for this module. 

### ISSUE THREAD

**Issue by thekip** [lingui/js-lingui#1705]
**Describe the bug**
While using `@lingui/loader` following warning appears in console 

```
./node_modules/@lingui/loader/dist/index.cjs!./src/locales/pt.po
Invalid dependencies have been reported by plugins or loaders for this module. All reported dependencies need to be absolute paths.
Invalid dependencies may lead to broken watching and caching.
As best effort we try to convert all invalid values to absolute paths and converting globs into context dependencies, but this is deprecated behavior.
Loaders: Pass absolute paths to this.addDependency (existing files), this.addMissingDependency (not existing files), and this.addContextDependency (directories).
Plugins: Pass absolute paths to fileDependencies (existing files), missingDependencies (not existing files), and contextDependencies (directories).
Globs: They are not supported. Pass absolute path to the directory as context dependencies.
The following invalid values have been reported:
 * "src/locales/en.po"
```

**Expected behavior**
Should not be any warnings

**Additional context**

- jsLingui version ``lingui --version``
- Babel version ``npm list @babel/core``
- Macro support:
  - [ ] I'm using SWC with `@lingui/swc-plugin`
  - [ ] I'm using Babel with `babel-macro-plugin`
  - [ ] I'm not using macro
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, NextJs, Vite)

**Comment by thekip** [comment]
as workaround add `<rootDir>` to your catalogs configuration

**Comment by gvillenave** [comment]
@thekip do you mean use `include: ["<rootDir>"]` in the catalogs configuration? I tried that but for me it didn't solve the issue. Using lingui 4.3.0 and nextjs 13.4.10.

**Comment by thekip** [comment]
The crucial is to have `<rootDir>` in path: `path: '<rootDir>/translates/{locale}',`
```ts
/**
 *
 * @type {import('next').NextConfig}
 */
const nextConfig = require('./next.config');

const locales = nextConfig.i18n.locales.filter((locale) => locale !== 'default');

module.exports = {
  locales,
  sourceLocale: 'en',
  catalogs: [
    {
      path: '<rootDir>/translates/{locale}',
      include: ['<rootDir>'],
      exclude: ['**/node_modules/**', '**/.next/**', '**/dist/**'],
    },
  ],
  format: 'po',
};

```

**Comment by paales** [comment]
This _seems_ to be working. I had to remove the .next directory to get it to work or something. I will report back if we encounter the error again.

**Comment by bravo-kernel** [comment]
Adding `rootDir` to [my config](https://github.com/alt3/rank-my-wallet/blob/c49ca313c19db773c9731c78b085e669b46e1292/lingui.config.js#L15) did not resolve the issue for me but could be Windows related. 

[I put up this PR for reference](https://github.com/alt3/rank-my-wallet/pull/190).

**Comment by usercao** [comment]
@bravo-kernel Thank you, this is effective on macOS, and this issue is indeed troublesome as it takes up a lot of console space.

**Comment by thekip** [comment]
I prepared a PR fixing the issue. I'm not sure that will help for Windows, i need help here as i don't have a windows machine. 

While working on that i've found interesting, not really documented, fact that if you don't prefix with `<rootDir>` in path configuration it would be interpreted from current process CWD, instead of config location as some may expect. 

Now i'm thinking is it a good idea to change this behavior to always be relative to config file, and how many users it can affect. Any thoughts?

**Comment by bravo-kernel** [comment]
@thekip I can do all tests required for Windows. I  just have no idea on how to apply your fix to my repo so I will need to investigate that first (unless I get spoonfed here)

**Comment by thekip** [comment]
@bravo-kernel you don't need to run it in your repo.  To help with this windows machine is just enough. There is a test-suite which is already failing on windows. I marked it with ["skipOnWindows"](https://github.com/lingui/js-lingui/pull/1735/files#diff-67b001df64dae7b2d3d8b53717665341aef7dda292162ccc0224ca6b17bc06e1R9) method. You can unskip it and start debugging the test suite. Usually a problem  is windows / posix path differences.
 I can help in discord if any questions.

**Comment by andrii-bodnar** [comment]
Hi @bravo-kernel, have you had a chance to check the Windows tests?

**Comment by bravo-kernel** [comment]
Just checked and I noticed two things preventing the tests from passing on Windows:

1. The directory separator used in the tests appears not to use the OS-specific directory separator
2. Some tests append Windows drive-letter to the expected paths

Details on Discord

**Comment by bravo-kernel** [comment]
For future visitors using Windows, #1735 does not solve the issue on Windows. Requires debugging by someone (skilled) using Windows, details on Discord.
