### ISSUE TITLE
optional chaining broken with typescript, vite, swc stack

### ISSUE THREAD

**Issue by moodysalem** [lingui/js-lingui#1716]
optional chaining is broken with vite, `@lingui/vite-plugin@4.2.1`, and `@lingui/swc-plugin@4.0.2`
Getting this error in the browser console, no compilation error

```
SyntaxError: missing name after . operator
```

_Originally posted by @moodysalem in https://github.com/lingui/js-lingui/issues/429#issuecomment-1607989724_

**Comment by thekip** [comment]
i'm pretty sure (95%) that you have versions misalignment. Please read [compatibility](https://github.com/lingui/swc-plugin#compatibility) section carefully and adjust your project accordingly.

**Comment by moodysalem** [comment]
I'm on `@vitejs/plugin-react-swc@3.3.2`, which is using `@swc/core@1.3.66`

```
npm ls -a


├─┬ @vitejs/plugin-react-swc@3.3.2
│ ├─┬ @swc/core@1.3.66
```

I changed to 1.3.63 it still didn't work. Changed to `1.3.62` and it worked.

**Comment by thekip** [comment]
> I changed to 1.3.63 it still didn't work. Changed to 1.3.62 and it worked.

Yes, and exactly that is written in the  [compatibility](https://github.com/lingui/swc-plugin#compatibility) section

![image](https://github.com/lingui/js-lingui/assets/1586852/0983c1df-73f9-4736-9169-8c096d4139d1)

**Comment by moodysalem** [comment]
> > I changed to 1.3.63 it still didn't work. Changed to 1.3.62 and it worked.
> 
> Yes, and exactly that is written in the [compatibility](https://github.com/lingui/swc-plugin#compatibility) section
> 
> ![image](https://user-images.githubusercontent.com/1586852/249410556-0983c1df-73f9-4736-9169-8c096d4139d1.png)

Agreed, just documenting for the next searcher, but is there a broader issue to fix? Seems rather strange that a fresh npm install is broken at the moment

**Comment by moodysalem** [comment]
> SWC Plugins is experimental feature. Unfortunately, there is little what I could do about it. They do releases quite often and quite often break backward compatibility for plugins.

Would defining peer dependencies in the swc plugin allow for better resolution or at least installation errors? Presumably if vite requires ^1.3.61 and lingui requires >=1.3.61 <=1.3.62 then npm could discover a package that works for both (idk if it actually would install the latest that works for both or just the latest and throw an error)
https://github.com/lingui/swc-plugin/blob/e127e592f3f5a7be97d4b8ae36393fdd822172aa/package.json#L32
