### ISSUE TITLE
Formatting stopped working after upgrading to v4

### ISSUE THREAD

**Issue by CookedApps** [lingui/js-lingui#1725]
**Describe the bug**
We've upgraded from lingui v3 to v4 and switched to a Vite based setup for our React 17 TypeScript app. 
After doing so and getting everything to work, formatted messages stopped rendering correctly. The messages are rendered without any formatting at all, even though the corresponding React components (for formatting) are in place. 

We are seeing these errors in the console:
`Can't use element at index '0' as it is not declared in the original translation`

We didn't change anything in the source code or the message format. So I was expecting that formatting will work fine as I didn't find any changes in the migration guide.

**To Reproduce**
React code
```tsx
import { Trans } from "@lingui/react"

export default function App() {
   return (
     <Trans id="my.cool.message">
       <b>This</b> should be bold.
     </Trans>
   );
}
```

`en/messages.json`
```json
{
  "my.cool.message": "<0>This</0> should be bold."
}
```

_Note:_ 
- We are using`@lingui/format-json` with `style: "minimal"`.
- We are using explicit IDs throughout the project.
- While switching to ESM we had to recompile the messages with `lingui compile --namespace es`
  - The generated `.mjs` files look correct and do indeed contain the corresponding `<0>...</0>` tags.

**Expected behavior**
The rendered text should be formatted properly.

**Additional context**
- jsLingui version ``4.3.0``
- Babel version ``@babel/core@7.22.5``
- Macro support:
    - I'm using Babel with `babel-macro-plugin`
- I'm using Vite with `@lingui/vite-plugin`

**Comment by thekip** [comment]
```ts
import { Trans } from "@lingui/macro"

export default function App() {
   return (
     <Trans id="my.cool.message">
       <b>This</b> should be bold.
     </Trans>
   );
}
```

**Comment by CookedApps** [comment]
@thekip Thank you, that was the solution! 

I had already tried that, but there I had imported both `@lingui/macro` and `@lingui/react`, because in many places I use `<Trans id="id" />` without children, which is not supported by macro. Have to find a way to use macro without having to change my whole codebase. For me, this is a breaking change which didn't get mentioned in the migration guide: `Trans` from `@lingui/macro` forces you to define children.

**Comment by thekip** [comment]
Typescript typings was justified in v4 to avoid such kind of issues. There is nothing changed here in terms of how it works. All hat was already true for v3, just typings itself was wrong and allowed devs to misuse the library. Now typings correctly reflect what is written in the docs. 

PS

There no sense to use macro without children. If you want to render a translation created somewhere, just use `<Trans>` from `@lingui/react`. If you need mix and match macro and non macro in the same file, just rename somesthing. 

```tsx
import {Trans as TransComp } from "@lingui/react";
import {Trans, msg} from "@lingui/macro";

const message = msg`Hello world!`;

function MyComponent() {
    return (<>
      <TransComp id={message.id} />
      <Trans>Hello world!</Trans>
    </>)
}

```
