### ISSUE TITLE
Almost every step in contributing.md fails on windows machine.

### ISSUE THREAD

**Issue by elios264** [lingui/js-lingui#173]
Hi!

I tried contributing to the repository, I'm pretty new on the matter, but I miserably failed, 
It says something about `yarn run bootstrap` but I think `contributing.md` is outdated.

and `yarn run test` and `yarn run watch` both fail on windows.

**Comment by tricoder42** [comment]
@elios264 You're right, the guide was outdated. I published updated version, please check it out and let me know if you have any more problems
