### ISSUE TITLE
React Suspense

### ISSUE THREAD

**Issue by root-io** [lingui/js-lingui#1734]
**Describe the bug**
This can fit as a bug and a feature request.
Only in production with NextJS on Vercel I often get the following errors in the console:

- https://reactjs.org/docs/error-decoder.html?invariant=418
- https://reactjs.org/docs/error-decoder.html?invariant=423
- https://reactjs.org/docs/error-decoder.html?invariant=425

I first thought it was an issue with with NextJS > 13.4.2 but then the errors have reappeared without changing anything.

I found this: https://github.com/vercel/next.js/issues/50245 and someone suggested (https://github.com/vercel/next.js/issues/50245#issuecomment-1643763767) to use the React `Suspense` feature as a fix.

`next-i18next` seems to have a `useSuspense` option.

**To Reproduce**
```tsx

export const getStaticProps: GetStaticProps = async (context) => {
  const translation = await loadCatalog(context.locale!);
  return {
    props: {
      translation,
    },
  };
};
```

**Expected behavior**
No error in production

**Additional context**

- jsLingui version `4.2.0`
- Macro support:
 - [x] I'm using SWC with `@lingui/swc-plugin` version `4.0.0`
 - [ ] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, NextJs, Vite)

**Comment by thekip** [comment]
How Lingui is related to suspense? All asynchronous loading logic is up to you. The lib doesn't trigger any suspense, the react part is completely synchronous.

**Comment by root-io** [comment]
@thekip thanks for your detailed answer, I'll continue investigate my issue, we can close this
