### ISSUE TITLE
MacroMessageDescriptor lacks values field from MessageDescriptor

### ISSUE THREAD

**Issue by AWare** [lingui/js-lingui#1736]
**Describe the bug**

The type `MacroMessageDescriptor` lacks the values field in its definition `values?: Record<string, unknown>;` which is present in `MessageDescriptor` and is strongly inferred present in https://lingui.dev/ref/macro#t 

**To Reproduce**

```tsx
import { t } from "@lingui/macro"
t({name:'someName',message:'some message {a}', values:{a:1}})
```

**Expected behavior**
values is present in the type

**Additional context**
The types in v3 allowed this.

- jsLingui version ``lingui --version`` 4.3.0
- Babel version ``npm list @babel/core`` 7.22.9
- Macro support:
 - [ ] I'm using SWC with `@lingui/swc-plugin`
 - [X] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, NextJs, Vite)
```{
	"plugins": ["macros", "@babel/plugin-transform-runtime"],
	"presets": [
		"@babel/preset-env",
		"@babel/preset-react",
		"@babel/preset-typescript",
		"@lingui/babel-preset-react"
	]
}
```

**Comment by thekip** [comment]
There was a reason for that, macro will override your values anyway. Use i18n. _ directly. There no sense in macro in your case.

**Comment by AWare** [comment]
Thanks, sorry for not noticing, I was just handling the upgrade.
