### ISSUE TITLE
Typescript warning when using <Trans id={messageId} />

### ISSUE THREAD

**Issue by mehdi-valette** [lingui/js-lingui#1748]
**Describe the bug**
Typescript warning when using `Trans` this way: `<Trans id={messageId} />`

```
TS2322: Type  { id: string; }  is not assignable to type  IntrinsicAttributes & TransProps 
Property  children  is missing in type  { id: string; }  but required in type  { children: ReactNode; } 
```

**To Reproduce**
Use the `Trans` component in the way described above.

```tsx
import { Trans, msg } from "@lingui/react"

const message = msg`This should be translated`;

export default function App() {
   return <Trans id={message.id}/>
}
```

**Expected behavior**
No warning should be raised as this is a pattern used within lingui documentation:
https://lingui.dev/tutorials/react-patterns#lazy-translations

**Additional context**

- jsLingui version 4.3.0
 - [ x] I'm using SWC with `@lingui/swc-plugin 4.0.2`
 - Vite 4.4.8

**Comment by thekip** [comment]
I'm pretty sure you messed up things.  

```ts
import { Trans, msg } from "@lingui/react"
```

`@lingui/react` doesn't export `msg`, but `@lingui/macro` do.  `Trans` exported from the `@lingui/macro` do require children, but `Trans` exported from `@lingui/react` does not.

**Comment by mehdi-valette** [comment]
You're right I mixed up the import, sorry.

This explains that, thanks 👍

So just to be sure, it means that when I have a page where I need both versions, I should import Trans from @lingui/react and @lingui/macro, using aliases to avoid conflicts?

Is there a problem with using the macro version of <Trans id="messageId" />? It appears to work fine, so I suppose there are more subtile issues with it?
