### ISSUE TITLE
Configure Lingui using a separate file

### ISSUE THREAD

**Issue by rssfrncs** [lingui/js-lingui#175]
As a developer i prefer (or have the choice) to write my configuration in a separate file instead of inside `package.json`.

Examples, .babelrc, .postcss.config.js, .eslintrc.js

**Comment by tricoder42** [comment]
Make sense.

The package responsible for loading config is [`@lingui/conf`](https://github.com/lingui/js-lingui/tree/master/packages/conf). I guess there might be 3rd party package which does exactly the same (maybe in `jest` repo) - loads config from nearest `package.json` or specific file.

**Comment by tricoder42** [comment]
This might be useful: [config resolution](https://github.com/facebook/jest/blob/master/packages/jest-config/src/resolve_config_path.js) in Jest.

**Comment by tricoder42** [comment]
This is already supported since [v2.2.0](https://github.com/lingui/js-lingui/releases/tag/v2.2.0). See [configuration docs](https://lingui.github.io/js-lingui/ref/lingui-conf.html).
