### ISSUE TITLE
Add guide how to use i18n outside React context

### ISSUE THREAD

**Issue by vonovak** [lingui/js-lingui#176]
Hi, thanks for the lib!
I'm having the following issue:

consider having: 

```js
i18n.t`Maximum of ${num} items can be selected.`
```

which gets transpiled into
```js
i18n._("Maximum of {num} items can be selected", { num: 10 })
```

My problem is that when `process.env.NODE_ENV !== "production"` evaluates to false, [body of this condition](https://github.com/lingui/js-lingui/blob/0d0aa92e334909a27ec0a38b2c99559e3c4558e5/packages/core/src/i18n.js#L172) is not executed.

The first param (`id`) of the function will be equal to "Maximum of {num} items can be selected" and because it is not a function, it will be returned [here](https://github.com/lingui/js-lingui/blob/0d0aa92e334909a27ec0a38b2c99559e3c4558e5/packages/core/src/i18n.js#L178). And thus the number will not be substituted, leaving the user with a message "Maximum of {num} items can be selected" instead of "Maximum of 10 items can be selected".
Note the issue is not present on a non production build.

**Comment by tricoder42** [comment]
Do you use compiled message catalogs? In production, there’s no need for strong substitution because messages with parameters should be functions (obtained by compiling messages using ‘lingui compile’)

5. 3. 2018 v 20:43, Vojtech Novak <notifications@github.com>:

**Comment by vonovak** [comment]
@tricoder42 thanks for quick response, that will probably be it. I do see a correct entry in `messages.js` which I got by `lingui compile`, where for the message id, there is a function. Now, it seems like the `i18n.t` function is not picking up the values from `messages.js`, is there something special I need to do to wire them up? I did not see this in the docs. Thanks.

**Comment by tricoder42** [comment]
Do you have ‘this.props.i18n.t’ in your code or ‘i18n.t’? The first variant doesn’t work at the moment (it’s not picked by transform plugin)

5. 3. 2018 v 21:23, Vojtech Novak <notifications@github.com>:

**Comment by vonovak** [comment]
the second one: i18n.t

**Comment by tricoder42** [comment]
What's your Babel config?

There's one issue when using presets, that some plugins (e.g transform-runtime) transform tagged template literals to function calls before lingui preset.

**Comment by vonovak** [comment]
My babelrc:
```js
{
  "presets": ["react-native-stage-0", "@lingui/babel-preset-react"],
  "plugins": [
    "transform-decorators-legacy",
    [
      "module-resolver",
      {
        "root": ["./js", "./jest"],
        "extensions": [".js", ".ios.js", ".android.js"],
        "alias": {
          // not relevant
        }
      }
    ]
  ]
}

```

The problem is present even if I change the template literal to `i18n._("Maximum of {num} items can be selected", { num: 10 })` (not sure if this helps).

**Comment by vonovak** [comment]
@ktunkiewicz the tutorial you linked seems to be react-specific since it talks about I18nProvider. I use the i18n.t calls outside of react components so this should work out of the box if I understand it correctly. I will try to create a repro that can be used to debug the problem.

**Comment by vonovak** [comment]
@tricoder42 so I created a reproduction available here https://github.com/vonovak/lingui-176/blob/master/App.js

you can use [expo.io/](http://expo.io/) to run it if you want but I went ahead and did some debugging to find out what went wrong.

The transpiled code is correct. I used `Trans` component with `I18nProvider` to compare the behavior of `Trans` with `i18n.t`. The problem was that when calling `i18n.t`, the message catalog was empty and thus the translation could not have been printed. Through some backtracking I found out that I needed to use `setupI18n` from `lingui-core` and then the `i18n.t` call works. It was the missing piece I was looking for to "wire them up" as I said in the previous post.

Now, my question is, why is `setupI18n` not documented? I'm not complaining here, but it would've saved me an hour of debugging. Is `setupI18n` safe to use? I use react native and I cannot rely only on the `Trans` component, I also need to get translations "outside of react". Do you plan on documenting the non-react kind of usage? I'm willing to write up docs for react native, but it would be nice to know what I do is the right way to do so.

**Comment by tricoder42** [comment]
Hey @vonovak, thanks for the example repo. I got it now.

The problem is you're using `i18n` from `@lingui/core` instead of component props. `I18nProvider` calls `setupI18n` under the hood and injects created `i18n` object into context. Using `withI18n` HOC, you can pass `i18n` object from context to component props and then use it without calling `setupI18n` manually.

**Comment by vonovak** [comment]
@tricoder42 there are cases when I need to be able to access a translation even outside of react components, how do I go about that when I do not have access to props / don't want to pass the i18n prop around? thanks.

**Comment by tricoder42** [comment]
Then your code is correct - you need to create `i18n` object using `setupI18n` manually. You should also pass it as `i18n` prop to `I18nProvider` to keep language and messages in sync.

**Comment by tricoder42** [comment]
This really needs to be documented! Adding label so I don't forget about it.

**Comment by tricoder42** [comment]
There is a new tutorial about [common i18n patterns](https://lingui.github.io/js-lingui/tutorials/react-patterns.html)
