### ISSUE TITLE
@lingui/macro Uncaught TypeError: Unable to determine current node version

### ISSUE THREAD

**Issue by Digtyarenk0** [lingui/js-lingui#1760]
**Describe the bug**
When I try to import Trans from @lingui/macro, I get warnings and an error

**Error**: 
```
index.js:44 Uncaught TypeError: Unable to determine current node version
    at versionIncluded (index.js:44:1)
    at isCore (index.js:58:1)
    at ./node_modules/resolve/lib/core.js (core.js:9:1)
    at options.factory (react refresh:6:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/resolve/index.js (index.js:2:1)
    at options.factory (react refresh:6:1)
    at options.factory (react refresh:6:1)
```

**Warnings**: 
```
WARNING in ./node_modules/babel-plugin-macros/dist/index.js 63:22-29
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/cosmiconfig/dist/loaders.js 30:18-30
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/cosmiconfig/dist/loaders.js 110:18-30
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/import-fresh/index.js 27:32-49
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/typescript/lib/typescript.js 3990:16-38
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/typescript/lib/typescript.js 7467:22-41
Critical dependency: the request of a dependency is an expression
```

**To Reproduce**
Installed packages

Dependencies:
   ```
"@lingui/macro": "^4.4.2",
     "@lingui/core": "^4.4.2",
     "@lingui/react": "^4.4.2",
```
 devDependencies:     
` "@lingui/cli": "^4.4.2",`

 Wrapped the folder in provider
 
```
import { i18n } from '@lingui/core';
import { I18nProvider } from '@lingui/react';
import { ReactNode } from 'react';

import { DEFAULT_LOCALE, DEFAULT_MESSAGES, SupportedLocale } from './locales.sups';

i18n.load(DEFAULT_LOCALE, DEFAULT_MESSAGES);
i18n.activate(DEFAULT_LOCALE);

interface Props {
  children: ReactNode;
}

export const AppI18NProvider = (props: Props) => {
  return <I18nProvider i18n={i18n}>{props.children}</I18nProvider>;
};
```

When importing
`import { Trans } from '@lingui/react';`
The app behaves correctly and without errors. But I would like to use
`import { Trans } from '@lingui/macro';`

**Additional context**

- jsLingui version ``lingui --version`` = 4.4.2
- Babel version ``npm list @babel/core`` = 7.22
- npm v = 8.19.2
- node v =  v16.18.1

babel.config.js
```
module.exports = {
    "plugins": [
        "macros",
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-proposal-nullish-coalescing-operator",
        "@babel/plugin-syntax-dynamic-import",
        "@babel/plugin-proposal-private-methods",
        "@babel/plugin-proposal-private-property-in-object",
        "@babel/plugin-syntax-flow"
    ],
    "presets": [
        [
            "react-app",
            {
                "flow": false,
                "typescript": true
            }
        ],
        "@babel/preset-flow",
        [
            "@babel/preset-env",
            {
                "targets": {
                    "esmodules": true
                }
            }
        ],
        "@babel/preset-modules",
        "@babel/preset-react",
        "@babel/preset-typescript"
    ],
    "compact": true
}
```

I also use react-app-rewired
And here are my webpack loaders
```

  const typescriptLoader = {
    test: [/\.ts?$/, /\.tsx?$/],
    loader: 'ts-loader',
    exclude: /node_modules/,
  };

  const babelLodaer = {
    test: /\.(js|jsx)$/,
    exclude: /node_modules/,
    use: {
      loader: 'babel-loader',
      options: {
        compact: true,
        presets: [
          '@babel/preset-flow',
          [
            '@babel/preset-env',
            {
              targets: {
                esmodules: true,
              },
            },
          ],
          '@babel/preset-modules',
          '@babel/preset-react',
          '@babel/preset-typescript',
        ],
        plugins: [
          'macros',
          '@babel/plugin-proposal-class-properties',
          '@babel/plugin-proposal-nullish-coalescing-operator',
          '@babel/plugin-syntax-dynamic-import',
          '@babel/plugin-proposal-private-methods',
          '@babel/plugin-proposal-private-property-in-object',
          '@babel/plugin-syntax-flow',
          isDev && require.resolve('react-refresh/babel'),
        ].filter(Boolean),
      },
    },
  };

  const laoders = [fileLoader, svgLoader, babelLodaer, typescriptLoader, cssLoader, resolveMJSLoader];
};

```
- Macro support:
 - [+] I'm using Babel with `babel-macro-plugin`

**Comment by thekip** [comment]
Please use syntax highlighting in the issues for code blocks, and create a minimal repro, i;ve never seen this error before, it seems it related to your configuration somehow.

**Comment by thekip** [comment]
It most likely your file is not processed by babel-macro-plugin and webpack is trying to bundle a macro code. I see from your example that you have a **typescript** file, where babel configuration is only for **(js|jsx)** and it seems typescript is processed by `ts-loader` which has no idea of babel macro

**Comment by Digtyarenk0** [comment]
Good guess. I tried changing the babel loader test to
`const babelLodaer = {
    test: /\.(js|jsx|tsx|ts)$/
    ...`
But the error still remains

**Comment by thekip** [comment]
As i already wrote, the problem in your configuration. I also gave you a direction to investigate: the code is not processed by babel macro plugin. Please, do troubleshooting by yourself, don't ask opensource people to do it for you.

**Comment by Digtyarenk0** [comment]
Okay, thanks for any help)
As far as I understand, this is a non-standard error, and is related to the loaders configuration in my webpack
And do I need to somehow connect ts loader and babel loader with a macro?
I also encountered an import error
`import { Trans } from '@lingui/macro';`

```
ERROR in ./src/widgets/footer/index.tsx 14:396-401
export 'Trans' (imported as 'Trans') was not found in '@lingui/macro' (possible exports: default)
```

**Comment by thekip** [comment]
your file is not processed by babel-macro-plugin. It might be because babel at all is not processing this file or because of incorrect babel configuration.  Check your loaders first. Most likely you changed only `const babelLodaer = { test: /\.(js|jsx|tsx|ts)$/ ...` and left your typescript loader configuration in place 

```js
  const typescriptLoader = {
    test: [/\.ts?$/, /\.tsx?$/],
    loader: 'ts-loader',
    exclude: /node_modules/,
  };
```

And most likely typescript loader still take precedence over babel loader. Hint: if you using babel you don't need a typescript loader at all, they are mutually exclusive

**Comment by Digtyarenk0** [comment]
Yes indeed
The presence of ts-loader caused this error
I switched babel-loader to process ts files and removed ts-loader
**Thank you very much!)**
