### ISSUE TITLE
it is bug or feature?

### ISSUE THREAD

**Issue by hhniao** [lingui/js-lingui#1766]
en/messages.json:
```
{
    "nothing":"this file it is empty"
}

i18n.activate("en")

i18n.t("Please add item {name}.", {name:i18n.t("some value")})
```
output: 
```
Please add item {name}.
```
expected: 
```
Please add item some value
```

**Comment by thekip** [comment]
Yes, this is expected in production builds. But should work in development. The message compiler (parser for ICU syntax) is stripped out from production builds, and "{name}" substitution will not work. In production you should have your "en" catalog also compiled and loaded into bundle.

**Comment by hhniao** [comment]
thanks for your reply.
