### ISSUE TITLE
Ability to mark some translations as non-removable for `lingui extract`

### ISSUE THREAD

**Issue by olalonde** [lingui/js-lingui#1767]
**Is your feature request related to a problem? Please describe.**
 
I have some translations with dynamic message IDs , e.g.:

```
i18n.t(`language.${langCode}`)
```

Since they cannot be extracted from source code, every time I run `lingui extract` , it comments out the messages in my `messages.po` file, thinking the messages were removed.

**Describe proposed solution**

Ability to mark some messages as manually entered: e.g.:

```po
#. js-lingui-manual
~ msgid "language.en"
~ msgstr "English"
```

**Comment by olalonde** [comment]
Actually, as a work around I created a `lingui-extract-hack.ts` with calls to `i18n.t`:

```typescript
import { i18n } from "@lingui/core";

// hack to prevent lingui extract from always commenting out manually added messages

i18n.t("language.en");
i18n.t("language.fr");
i18n.t("language.es");

```

**Comment by thekip** [comment]
Your "hack" is the way to do so. There are no plans to change this because it's would be out of the lingui's extractor ideology.
