### ISSUE TITLE
Translations don't work in React Native production build

### ISSUE THREAD

**Issue by mjroeleveld** [lingui/js-lingui#1773]
**Describe the bug**
I followed all the instructions carefully, but translations do not show up in my React Native production build. When connected to metro it works fine. Instead, I get the message IDs.

I did run `npm extract` and `npm compile` and the `messages.js` file does exist.

I also have polyfills and babel macro plugin installed and configured.

**To Reproduce**

```tsx
import '@formatjs/intl-locale/polyfill';
import '@formatjs/intl-pluralrules/polyfill';
import '@formatjs/intl-pluralrules/locale-data/en';

import { Trans } from "@lingui/macro"
import { i18n } from '@lingui/core'
import { Text } from 'react-native'

import englishTranslations from '../assets/locales/en/messages.js';

i18n.load("en", englishTranslations);
i18n.activate("en");


export default function App() {
    return (
      <I18nProvider i18n={i18n}>
        <Trans>This should be translated!</Trans>
      </I18nProvider>
    )
}
```

**Expected behavior**
Translations to show up.

- React Native version
`0.72.3`

- jsLingui version ``lingui --version``
`4.5.0`

- Babel version ``npm list @babel/core``
<details>
<summary>Output</summary>
├─┬ @babel/core@7.22.9
│ ├─┬ @babel/helper-compilation-targets@7.22.9
│ │ └── @babel/core@7.22.9 deduped
│ └─┬ @babel/helper-module-transforms@7.22.9
│   └── @babel/core@7.22.9 deduped
├─┬ @babel/preset-env@7.22.9
│ ├── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-bugfix-safari-id-destructuring-collision-in-function-expression@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-proposal-private-property-in-object@7.21.0-placeholder-for-preset-env.2
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-async-generators@7.8.4
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-class-properties@7.12.13
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-class-static-block@7.14.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-dynamic-import@7.8.3
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-export-namespace-from@7.8.3
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-import-assertions@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-import-attributes@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-import-meta@7.10.4
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-json-strings@7.8.3
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-logical-assignment-operators@7.10.4
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-nullish-coalescing-operator@7.8.3
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-numeric-separator@7.10.4
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-object-rest-spread@7.8.3
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-optional-catch-binding@7.8.3
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-optional-chaining@7.8.3
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-private-property-in-object@7.14.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-top-level-await@7.14.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-unicode-sets-regex@7.18.6
│ │ ├── @babel/core@7.22.9 deduped
│ │ └─┬ @babel/helper-create-regexp-features-plugin@7.22.9
│ │   └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-arrow-functions@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-async-generator-functions@7.22.7
│ │ ├── @babel/core@7.22.9 deduped
│ │ └─┬ @babel/helper-remap-async-to-generator@7.22.9
│ │   └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-async-to-generator@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-block-scoped-functions@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-block-scoping@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-class-properties@7.22.5
│ │ ├── @babel/core@7.22.9 deduped
│ │ └─┬ @babel/helper-create-class-features-plugin@7.22.9
│ │   └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-class-static-block@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-classes@7.22.6
│ │ ├── @babel/core@7.22.9 deduped
│ │ ├─┬ @babel/helper-compilation-targets@7.22.9
│ │ │ └── @babel/core@7.22.9 deduped
│ │ └─┬ @babel/helper-replace-supers@7.22.9
│ │   └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-computed-properties@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-destructuring@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-dotall-regex@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-duplicate-keys@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-dynamic-import@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-exponentiation-operator@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-export-namespace-from@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-for-of@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-function-name@7.22.5
│ │ ├── @babel/core@7.22.9 deduped
│ │ └─┬ @babel/helper-compilation-targets@7.22.9
│ │   └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-json-strings@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-literals@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-logical-assignment-operators@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-member-expression-literals@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-modules-amd@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-modules-commonjs@7.22.5
│ │ ├── @babel/core@7.22.9 deduped
│ │ └─┬ @babel/helper-module-transforms@7.22.9
│ │   └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-modules-systemjs@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-modules-umd@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-named-capturing-groups-regex@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-new-target@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-nullish-coalescing-operator@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-numeric-separator@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-object-rest-spread@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-object-super@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-optional-catch-binding@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-optional-chaining@7.22.6
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-parameters@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-private-methods@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-private-property-in-object@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-property-literals@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-regenerator@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-reserved-words@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-shorthand-properties@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-spread@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-sticky-regex@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-template-literals@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-typeof-symbol@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-unicode-escapes@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-unicode-property-regex@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-unicode-regex@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-unicode-sets-regex@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/preset-modules@0.1.6
│ │ ├── @babel/core@7.22.9 deduped
│ │ └─┬ @babel/plugin-proposal-unicode-property-regex@7.18.6
│ │   └── @babel/core@7.22.9 deduped
│ ├─┬ babel-plugin-polyfill-corejs2@0.4.5
│ │ ├── @babel/core@7.22.9 deduped
│ │ └─┬ @babel/helper-define-polyfill-provider@0.4.2
│ │   ├── @babel/core@7.22.9 deduped
│ │   └─┬ @babel/helper-compilation-targets@7.22.9
│ │     └── @babel/core@7.22.9 deduped
│ ├─┬ babel-plugin-polyfill-corejs3@0.8.3
│ │ └── @babel/core@7.22.9 deduped
│ └─┬ babel-plugin-polyfill-regenerator@0.5.2
│   └── @babel/core@7.22.9 deduped
├─┬ @graphql-codegen/client-preset@4.0.1
│ └─┬ @graphql-codegen/visitor-plugin-common@4.0.1
│   └─┬ @graphql-tools/relay-operation-optimizer@7.0.0
│     └─┬ @ardatan/relay-compiler@12.0.0
│       └── @babel/core@7.22.9 deduped
├─┬ @lingui/cli@4.5.0
│ └── @babel/core@7.22.9 deduped
├─┬ @react-native-community/eslint-config@3.0.3
│ ├── @babel/core@7.22.9 deduped
│ └─┬ @babel/eslint-parser@7.19.1
│   └── @babel/core@7.22.9 deduped
├─┬ @react-native/eslint-config@0.72.2
│ ├── @babel/core@7.22.9 deduped
│ └─┬ @babel/eslint-parser@7.22.9
│   └── @babel/core@7.22.9 deduped
├─┬ @react-native/metro-config@0.72.9
│ ├─┬ metro-config@0.76.7
│ │ └─┬ metro@0.76.7
│ │   ├─┬ @babel/core@7.22.9
│ │   │ ├─┬ @babel/helper-compilation-targets@7.22.9
│ │   │ │ └── @babel/core@7.22.9 deduped
│ │   │ └─┬ @babel/helper-module-transforms@7.22.9
│ │   │   └── @babel/core@7.22.9 deduped
│ │   ├─┬ metro-babel-transformer@0.76.7
│ │   │ └─┬ @babel/core@7.22.9
│ │   │   ├─┬ @babel/helper-compilation-targets@7.22.9
│ │   │   │ └── @babel/core@7.22.9 deduped
│ │   │   └─┬ @babel/helper-module-transforms@7.22.9
│ │   │     └── @babel/core@7.22.9 deduped
│ │   ├─┬ metro-react-native-babel-preset@0.76.7
│ │   │ └── @babel/core@7.22.9 deduped
│ │   ├─┬ metro-transform-plugins@0.76.7
│ │   │ └─┬ @babel/core@7.22.9
│ │   │   ├─┬ @babel/helper-compilation-targets@7.22.9
│ │   │   │ └── @babel/core@7.22.9 deduped
│ │   │   └─┬ @babel/helper-module-transforms@7.22.9
│ │   │     └── @babel/core@7.22.9 deduped
│ │   └─┬ metro-transform-worker@0.76.7
│ │     └─┬ @babel/core@7.22.9
│ │       ├─┬ @babel/helper-compilation-targets@7.22.9
│ │       │ └── @babel/core@7.22.9 deduped
│ │       └─┬ @babel/helper-module-transforms@7.22.9
│ │         └── @babel/core@7.22.9 deduped
│ └─┬ metro-react-native-babel-transformer@0.76.7
│   ├─┬ @babel/core@7.22.9
│   │ ├─┬ @babel/helper-compilation-targets@7.22.9
│   │ │ └── @babel/core@7.22.9 deduped
│   │ └─┬ @babel/helper-module-transforms@7.22.9
│   │   └── @babel/core@7.22.9 deduped
│   ├─┬ babel-preset-fbjs@3.4.0
│   │ └── @babel/core@7.22.9 deduped
│   └─┬ metro-react-native-babel-preset@0.76.7
│     └── @babel/core@7.22.9 deduped
├─┬ babel-jest@29.6.1
│ ├── @babel/core@7.22.9 deduped
│ ├─┬ @jest/transform@29.6.1
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ babel-plugin-istanbul@6.1.1
│ │ └─┬ istanbul-lib-instrument@5.2.1
│ │   └── @babel/core@7.22.9 deduped
│ └─┬ babel-preset-jest@29.5.0
│   ├── @babel/core@7.22.9 deduped
│   └─┬ babel-preset-current-node-syntax@1.0.1
│     ├── @babel/core@7.22.9 deduped
│     └─┬ @babel/plugin-syntax-bigint@7.8.3
│       └── @babel/core@7.22.9 deduped
├─┬ jest@29.6.1
│ └─┬ @jest/core@29.6.1
│   ├─┬ jest-config@29.6.1
│   │ └── @babel/core@7.22.9 deduped
│   └─┬ jest-snapshot@29.6.1
│     └── @babel/core@7.22.9 deduped
├─┬ metro-react-native-babel-preset@0.76.7
│ ├── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-proposal-async-generator-functions@7.20.7
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-proposal-class-properties@7.18.6
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-proposal-export-default-from@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-proposal-nullish-coalescing-operator@7.18.6
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-proposal-numeric-separator@7.18.6
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-proposal-object-rest-spread@7.20.7
│ │ ├── @babel/core@7.22.9 deduped
│ │ └─┬ @babel/helper-compilation-targets@7.22.9
│ │   └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-proposal-optional-catch-binding@7.18.6
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-proposal-optional-chaining@7.21.0
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-export-default-from@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-syntax-flow@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-flow-strip-types@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-react-display-name@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-react-jsx-self@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-react-jsx-source@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-react-jsx@7.22.5
│ │ ├── @babel/core@7.22.9 deduped
│ │ └─┬ @babel/plugin-syntax-jsx@7.22.5
│ │   └── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-runtime@7.22.9
│ │ └── @babel/core@7.22.9 deduped
│ └─┬ @babel/plugin-transform-typescript@7.22.9
│   ├── @babel/core@7.22.9 deduped
│   └─┬ @babel/plugin-syntax-typescript@7.22.5
│     └── @babel/core@7.22.9 deduped
├─┬ react-native-reanimated@3.4.1
│ ├── @babel/core@7.22.9 deduped
│ ├─┬ @babel/plugin-transform-object-assign@7.22.5
│ │ └── @babel/core@7.22.9 deduped
│ └─┬ @babel/preset-typescript@7.22.5
│   └── @babel/core@7.22.9 deduped
└─┬ react-native@0.72.3 overridden
  └─┬ @react-native/codegen@0.72.6
    └─┬ jscodeshift@0.14.0
      ├── @babel/core@7.22.9 deduped
      ├─┬ @babel/preset-flow@7.22.5
      │ └── @babel/core@7.22.9 deduped
      ├─┬ @babel/register@7.22.5
      │ └── @babel/core@7.22.9 deduped
      └─┬ babel-core@7.0.0-bridge.0
        └── @babel/core@7.22.9 deduped
</details>

- Macro support:
 - [x] I'm using Babel with `babel-macro-plugin`

- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, NextJs, Vite)

```javascript
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin', 'macros'],
};
```

**Comment by andrii-bodnar** [comment]
@vonovak could you please take a look?

**Comment by vonovak** [comment]
@mjroeleveld I didn't run the code, but please try importing the messages [like this](https://github.com/lingui/js-lingui/blob/d6501e37591da7a722ff71761e1ce82987f31492/examples/react-native/App.tsx#L12C1-L13C1). ie. use a named import.

Please let me know if that works 👍

**Comment by mjroeleveld** [comment]
@vonovak thank you, I overlooked that, it doesn't work however.

**Comment by vonovak** [comment]
@mjroeleveld sorry to hear that 😢 

I'm going to need [this](https://stackoverflow.com/help/minimal-reproducible-example) to move it forward, thank you.

**Comment by mjroeleveld** [comment]
Making a repro pointed me to the issue: the `macro` package was listed under `devDependencies` 🤦🏻

**Comment by mo6zes** [comment]
> Making a repro pointed me to the issue: the `macro` package was listed under `devDependencies` 🤦🏻

This made Plural macros work for me on an expo development build. Thanks!

Maybe change the docs which currently imply that it is okay to install it as a dev dependency:
"It's recommended to install @lingui/macro package as a production dependency rather than development one to avoid import/no-extraneous-dependencies errors in ESLint." https://lingui.dev/ref/macro
