### ISSUE TITLE
An error occurred after upgrading to the latest version of Next.js

### ISSUE THREAD

**Issue by usercao** [lingui/js-lingui#1782]
**Describe the bug**
```
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Resolving 'lingui_loader_dist_index_cjs_src_locales_en-US_index_po' in /Users/usercao/code/X/nextjs-example/.next/server for build dependencies doesn't lead to expected result '/Users/usercao/code/X/nextjs-example/.next/server/node_modules_lingui_loader_dist_index_cjs_src_locales_en-US_index_po.js', but to 'Error: Can't resolve 'lingui_loader_dist_index_cjs_src_locales_en-US_index_po' in '/Users/usercao/code/X/nextjs-example/.next/server'' instead. Resolving dependencies are ignored for this path.
<w>  at unknown 4 lingui_loader_dist_index_cjs_src_locales_en-US_index_po
```
![image](https://github.com/lingui/js-lingui/assets/13760476/e2b5d20f-6e03-4ab1-a874-dbab1b9da843)

**To Reproduce**
Just start the project and you can see the error message on the console:
```bash
yarn dev
```

**Expected behavior**
There should not be any warning output.

**Additional context**

- jsLingui version `4.5.0`
- Macro support:
 - [x] I'm using SWC with `@lingui/swc-plugin`
 
 **Here's there repo:**
[https://github.com/usercao/nextjs-example](https://github.com/usercao/nextjs-example)

**Comment by thekip** [comment]
Thanks, i will look into it.

**Comment by omattman** [comment]
Can confirm I am seeing the same issue.

**Comment by thekip** [comment]
Well. I didn't find anything suspicious in the setup, everything works as expected, but nextjs indeed shows this warning. I re-checked that all generated paths in the loader points to real files in the FS and everything seems fine. It looks they broke something inside nextjs webpack's integration. 

What i've found, that if you add a `@lingui/loader` into the webpack config it works without a warning. So, probably the issue with webpack's inline loaders notation eq: `@lingui/loader!./${locale}/index.po`

Change your next config as following: 

```ts
  webpack: (config) => {
    // other webpack settings

    config.module.rules.push({
      test: /\.po$/,
      use: {
        loader: '@lingui/loader',
      },
    });
    
    return config;
  },
```

And change loading catalogs to:

```ts
  const catalog = await import(`./${locale}/index.po`);
```

**Comment by usercao** [comment]
This is the best open source project. Thank you very much for your reply, The problem has been resolved according to your method. Do you need to update this configuration in `examples`?

**Comment by thekip** [comment]
I maybe will write a ticket on the nextjs repository, because it seems it theirs bug.

**Comment by bravo-kernel** [comment]
@thekip do you have a nextjs ticket we can track?

**Comment by thekip** [comment]
no i didn't

**Comment by bravo-kernel** [comment]
No problem, thanks for the suggested fix, works like a charm 💃
