### ISSUE TITLE
Generate message id should be url safe

### ISSUE THREAD

**Issue by yunsii** [lingui/js-lingui#1789]
**Is your feature request related to a problem? Please describe.**

If messaage id starts with `"/"`, Google crawler will visit it and get 404 http code, even if the messages in `__NEXT_DATA__`

**Describe proposed solution**

https://github.com/lingui/js-lingui/blob/40d1556a7a3c5ac67cdc125125fd398a64f28cab/packages/message-utils/src/generateMessageId.ts#L6

https://github.com/lingui/swc-plugin/blob/6f7393681744b8a491db91a8ddeca7a5eb0b6e8e/src/generate_id.rs#L11

Function `generateMessageId`(`@lingui/message-utils`) and `generate_message_id`(@lingui/swc-plugin) should remove first `"/"` at least.

Currently, I patch `@lingui/message-utils` with:

```diff
export function generateMessageId(msg: string, context = "") {
-  return hexToBase64(sha256(msg + UNIT_SEPARATOR + (context || ""))).slice(0, 6)
+  return hexToBase64(sha256(msg + UNIT_SEPARATOR + (context || ""))).replace(/\//g, '').slice(0, 6)
}
```

And patch `@lingui/swc-plugin` with:

```diff
pub fn generate_message_id(message: &str, context: &str) -> String {
  let mut hasher = Sha256::new();
  hasher.update(format!("{message}{UNIT_SEPARATOR}{context}"));

  let result = hasher.finalize();
-  return BASE64.encode(result.as_ref())[0..6].into()
+  return BASE64.encode(result.as_ref())[0..6].replace("/", "").into()
}
```

**Comment by thekip** [comment]
How google crawler is related to the json somewhere in your application?

**Comment by yunsii** [comment]
@thekip For example:
<img width="1299" alt="screenshot" src="https://github.com/lingui/js-lingui/assets/18096089/e2167b3c-9f15-48b6-b634-285d5372ca7b">

**Comment by yunsii** [comment]
![image](https://github.com/lingui/js-lingui/assets/18096089/0f8e69f5-abf1-4996-8912-ec38d67c6064)

This `translation` result is generatet after patched, Some keys will start with `"/"` before patched.

**Comment by yunsii** [comment]
![image](https://github.com/lingui/js-lingui/assets/18096089/b9d5a551-c505-4817-a96e-51d0a160cf4b)

This `translation` result is generatet after patched, Some keys will start with `"/"` before patched.

**Comment by thekip** [comment]
What message ids are doing in the links in your application?

**Comment by yunsii** [comment]
> What message ids are doing in the links in your application?

Obviously, we don't use message ids directly. Just extract and translate. I think `translation` data in `__NEXT_DATA__` embeded html will be parsed and visited by Google crawler.

**Comment by thekip** [comment]
I think you should carefully check your application. The Google crawler has no reason to read internals of your application and therefore you probably has some api or sitemap.xml which is generated incorrectly and somehow message ids from lingui leaking there. 

I don't want to change how ids are generated bringing a massive breaking change for all existing catalogs for some unclarified reason.

**Comment by yunsii** [comment]
ref: https://github.com/vercel/next.js/discussions/39377

> I think you should carefully check your application. The Google crawler has no reason to read internals of your application and therefore you probably has some api or sitemap.xml which is generated incorrectly and somehow message ids from lingui leaking there.
> 
> I don't want to change how ids are generated bringing a massive breaking change for all existing catalogs for some unclarified reason.

**Comment by yunsii** [comment]
Present situation:
https://support.google.com/webmasters/thread/217029647?hl=en&msgid=217082757
https://github.com/vercel/next.js/issues/40143
https://github.com/vercel/next.js/discussions/39377

It seems still not prevent Google crawler to follow part of web page (For example, __NEXT_DATA__ script node), I had to release two packages:

- https://github.com/yunsii/lingui-message-utils-patch
- https://github.com/yunsii/lingui-swc-plugin-patch

to make the generated message id without `"/"`.
