### ISSUE TITLE
Add support for .po file format

### ISSUE THREAD

**Issue by purepennons** [lingui/js-lingui#179]
I use [`react-intl`](https://github.com/yahoo/react-intl) first. But because of the writers requirement, we only can provide untranslated text with a complete statement. And js-lingui support rich-text formatting with component that solved my problem. However, I found another problem in my scenario.

In my scenario, writers only accept the sheet format (.csv, .xls). 

And I found a tool [`translate-toolkit` ](http://docs.translatehouse.org/projects/translate-toolkit/en/latest/guides/using_csv2po.html) that can convert `.po` files (filter out translated string) to `.csv` and convert back to `.po` files from `.xls` and `.csv` formats easily.

 Many writers only accept `.po`, `.xls` or `.csv` format. It would be nice to have a tool to convert the lingui format to `.csv` or `.po`   format.

**Comment by tricoder42** [comment]
Nothing I’m aware off yet. You can either find converter from JSON to po or we could extend Lingui to handle Po file format. The CLI already works with several formats, so the API and example implementation is there.

9. 3. 2018 v 12:22, Chiahao Lin <notifications@github.com>:

**Comment by purepennons** [comment]
Got it. Maybe implement a converter from `.json` to `.po` is easier for me at the time because of time pressure. If everything works fine, I will try to extend Lingui to handle `.po` format and send a PR.

**Comment by morloy** [comment]
At [Ledgy](https://www.ledgy.com) we used [i18next-conv](https://github.com/i18next/i18next-gettext-converter) to convert between the `.json` (minimal format) and `.po` and translate our new website from English to German.
Generating a `.po` file from js-lingui was also very handy to bootstrap the translation with the [Google Translator Toolkit](https://translate.google.com).

**Comment by tricoder42** [comment]
Released in [2.4.0](https://github.com/lingui/js-lingui/releases/tag/v2.4.0)
