### ISSUE TITLE
`lingui extract-experimental` extract different file path comment between Windows and Linux

### ISSUE THREAD

**Issue by yunsii** [lingui/js-lingui#1793]
**Describe the bug**

`lingui extract-experimental` should patch [`source-map@0.8.0-beta.0`](https://github.dev/mozilla/source-map/blob/60adcb064bf033702d954d6d3f9bc3635dcb744b/lib/util.js#L201-L203) with:

```diff
function withBase(url, base) {
+  return new URL(url, `file:///${base.replace(/\\/g, '/')}`).toString();
-  return new URL(url, base).toString();
}
```

to make the command works on Windows. And then extract po files with different file path comment:

![image](https://github.com/lingui/js-lingui/assets/18096089/941b4262-3fc7-4420-ad03-addbca2ea3d5)

**To Reproduce**

https://github.com/yunsii/lingui-examples-nextjs-swc

- patch [`source-map@0.8.0-beta.0`](https://github.dev/mozilla/source-map/blob/60adcb064bf033702d954d6d3f9bc3635dcb744b/lib/util.js#L201-L203) manually
- `lingui extract-experimental`

**Expected behavior**

Windows and Linux extract same file path comment.

**Additional context**

https://github.com/lingui/js-lingui/blob/04b7cef9876168bc376b55424ecc0b0ebde976c1/packages/cli/src/lingui-extract-experimental.ts#L57-L62

Windows esbuild bundleResult:
![image](https://github.com/lingui/js-lingui/assets/18096089/69f086a0-a5cf-4a8d-b3e2-0e6b6713e57d)

Linux esbuild bundleResult:
![image](https://github.com/lingui/js-lingui/assets/18096089/b38e5324-5aa2-4a45-a476-ad60bf4ba66c)

- jsLingui version `4.5.0`
- Macro support:
 - [x] I'm using SWC with `@lingui/swc-plugin`
 - [ ] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro

**Comment by thekip** [comment]
Try to use WSL, there no sense to continue developing under native windows. I'm not personally interested in investing time in that.

**Comment by yunsii** [comment]
> Try to use WSL, there no sense to continue developing under native windows. I'm not personally interested in investing time in that.

Yes, I have used WSL many years, this issue was found on native Windows of my colleagues. Is it inappropriate not to consider cross-system issues?

**Comment by thekip** [comment]
If even microsoft gave up supporting native windows for developers and brought a better alternative, why we should invest in that? 😅 

Anyway, if you willing, you can open a PR. i don't have access to a windows machine anywhere in my environment so it extremely time consuming for me to fix cross-platofrm bugs for native windows, but i'm opened to review and accept PRs on this.

**Comment by yunsii** [comment]
> If even microsoft gave up supporting native windows for developers and brought a better alternative, why we should invest in that? 😅

Nice idea, but I found that it seems to make PRs to [mozilla/source-map](https://github.dev/mozilla/source-map) to fix this issue, I think my colleagues use WSL to run `lingui extract-experimental` is a good solution, and it is a chance to migrate to WSL gradually.
