### ISSUE TITLE
inconsistent message from extract and macro with multiple consecutive newlines / trailing spaces

### ISSUE THREAD

**Issue by taozhou-glean** [lingui/js-lingui#1799]
**Describe the bug**

just noticed this behavior difference when multiple consecutive newlines involved.

For extract: the newlines are extracted correctly
For macro: the newlines are collapsed due to https://github.com/lingui/js-lingui/blob/04b7cef9876168bc376b55424ecc0b0ebde976c1/packages/macro/src/macroJs.ts#L31

example from tests:

catalog.test.ts (`\n\n` preserved correctly):

<img width="403" alt="image" src="https://github.com/lingui/js-lingui/assets/121891361/6b0ed70d-aaa2-40ec-b28d-899b9e868038">

macro, `\n\n` collapsed:

````
# macro/tests/js-t.ts
 {
    name: "Newlines are preserved",
    input: `
        import { t } from '@lingui/macro';
        t\`Multiline
          string\`
      `,
    expected: `
        import { i18n } from "@lingui/core";
        i18n._(
          /*i18n*/
          {
            id: "EfogM+",
            message: "Multiline\\nstring",
          }
        );
      `,
  },
  {
    name: "Newlines are preserved2",
    input: `
        import { t } from '@lingui/macro';
        t\`Multiline

          string\`
      `,
    expected: `
        import { i18n } from "@lingui/core";
        i18n._(
          /*i18n*/
          {
            id: "EfogM+",
            message: "Multiline\\nstring",
          }
        );
      `,
  },
```

- jsLingui version ``lingui --version``: 4.5.0
- Babel version ``npm list @babel/core``
- Macro support:
 - [x] I'm using SWC with `@lingui/swc-plugin`
 - [ ] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, NextJs, Vite)

**Comment by taozhou-glean** [comment]
we have to admit that normalize whitespace for jsx is unfortunate but has no choice, but I would suggest we skip normalization for macroJs ones, and just take whatever in the macro methods... which aligns with extract and matches user expectation as well

**Comment by taozhou-glean** [comment]
or at least match the behavior between extract and macro :)

**Comment by thekip** [comment]
The extract uses macro under the hood so the result should be the same. The difference might be if you use SWC plugin for macro, this way extract would you JS counterpart. 

Could you provide an example of code which works inconsistently?

**Comment by taozhou-glean** [comment]
> Could you provide an example of code which works inconsistently?

of course, the minimum example is:

```
t({message: "hello\n\nworld"})
```

from `lingui extract`, I am seeing:

```

#. js-lingui-id: DGn/t0
msgid ""
"hello\n"
"\n"
"world"
msgstr ""
"hello\n"
"\n"
"world"
```

while in compiled code, the lingui id it used to look up the message is actually from `hello\nworld` (just one new line` instead)

**Comment by thekip** [comment]
There were differences between swc / babel macro in that matter. I followed your suggestion and completely removed whitespace cleaning from JS macro. I agree, that is useless and counterintuitive. 

Babel JSX: https://github.com/lingui/js-lingui/pull/1882
Babel JS: https://github.com/lingui/js-lingui/pull/1897
SWC Port: https://github.com/lingui/swc-plugin/pull/83
