### ISSUE TITLE
lingui extract --verbose - better error handling

### ISSUE THREAD

**Issue by snegostup** [lingui/js-lingui#180]
Right now `srcFilename` is outputted **after** successful extraction. When there has been an error during extraction we can't see which file caused the error. 

I propose to output `srcFilename` before extraction and after successful extraction output "Success". Something along these lines.
```javascript
    console.log(_chalk.default.blue(`Processing ${srcFilename}`));
    var extracted = ...

    if (extracted && verbose) console.log(_chalk.default.green("Success"));
```

**Comment by tricoder42** [comment]
Sounds reasonable, interested in sending PR?
