### ISSUE TITLE
Usage with vue & vite with vite plugin

### ISSUE THREAD

**Issue by armandsar** [lingui/js-lingui#1806]
**Describe the bug**
The macro you imported from "@lingui/macro" is being executed outside the context of compilation. 
This indicates that you don't have the "babel-plugin-macros" or "@lingui/swc-plugin" configured correctly. Please see the documentation for how to configure Vite with Lingui correctly: https://lingui.dev/tutorials/setup-vite

Is the error I am facing, all of this works if I keep translation context outside .vue files, like so:
```
import { t } from '@lingui/macro';

export default {
    edit: t`Edit`,
    invite: () => t`Invite`,
    enable_access: t`Enable access`,
};
```
then I can import this new module in vue file without problem, which is hardly ideal

but as soon as even import macro I am faced with the error, and vite config is setup as per docs:

**To Reproduce**
In vue file:
```js
import { t } from '@lingui/macro';
```

```js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';
import { lingui } from '@lingui/vite-plugin';
import react from '@vitejs/plugin-react';

export default defineConfig({
    plugins: [
        laravel({
            input: 'resources/js/app.js',
            refresh: true,
        }),
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false,
                },
            },
        }),
        react({
            babel: {
                plugins: ['macros'],
            },
        }),
        lingui(),
    ],
});


```

**Expected behavior**
No error displayed or more setup instructions
**Additional context**

- jsLingui version ``4.5.0``
- Babel version ``7.23.3``
- Vite, vue.js, this is also using Inertia, not sure if this impacts anything

**Comment by thekip** [comment]
The problem here is that 

```js
react({
  babel: {
      plugins: ['macros'],
  },
}),
```

Plugin doesn't know anuthing about vue's sfc files. hence doesn't apply `babel-macro-plugin` to them.  There was similar questions already, check them out, there are some solutions proposed: 

https://github.com/lingui/js-lingui/issues/1567#issuecomment-1503761631
https://github.com/lingui/js-lingui/discussions/1730
