### ISSUE TITLE
Double Render caused by wrong assertion

### ISSUE THREAD

**Issue by michelalbers** [lingui/js-lingui#1814]
On an initial page render in next.js the i18n.locale is empty string and not undefined. Therefore the current implementation causes double renders:

https://github.com/lingui/js-lingui/blob/2afa0efb2d0cd1d47adc76e1eec9f5e57e34ae18/examples/nextjs-swc/src/utils.ts#L21

It should be:

```if (isClient && !i18n.locale) {``` instead of   ```if (isClient && i18n.locale === undefined) {```

**Comment by usercao** [comment]
![image](https://github.com/lingui/js-lingui/assets/13760476/8728cc39-e82d-48ac-9be5-68462cb65226)
```txt
I18nProvider rendered `null`. A call to `i18n.activate` needs to happen in order for translations to be activated and for the I18nProvider to render.This is not an error but an informational message logged only in development.
```
And this issue will lead to the above warning.
