### ISSUE TITLE
Examples show useEffect deps warning

### ISSUE THREAD

**Issue by root-io** [lingui/js-lingui#1830]
**Describe the bug**

Default NextJs linter complains:

```shell
Warning: React Hook useEffect has a missing dependency: 'messages'. Either include it or remove the dependency array.
```

`messages` is missing from the useEffect deps but I wanted to confirm with you adding it won't break anything.

**To Reproduce**

https://github.com/lingui/js-lingui/blob/main/examples/nextjs-babel/src/i18n.ts#L36
https://github.com/lingui/js-lingui/blob/main/examples/nextjs-swc/src/utils.ts#L31

**Expected behavior**
No warning

**Additional context**

- jsLingui version `4.7.0`
- Babel version `7.23.7`
- Macro support:
 - [ ] I'm using SWC with `@lingui/swc-plugin`
 - [x] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, NextJs, Vite)
NextJs

**Comment by thekip** [comment]
You can mute it or you can add it in the deps array, doesn't matter.
