### ISSUE TITLE
Cannot kill git pre-commit hook while lingui command is running

### ISSUE THREAD

**Issue by datafoo** [lingui/js-lingui#1833]
**Describe the bug**
It is not possible to stop a git pre-commit hook after `lingui extract --clean` has started, even after `lingui extract --clean` has finished.

**To Reproduce**
In one of my project I have the following git pre-commit hook (`.git/hooks/pre-commit`):
```bash
#!/usr/bin/env bash
#
# Git pre-commit hook

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

message()
{
  MESSAGE="$1"
  COLOR="$2"
  echo -e "${COLOR}${MESSAGE}${NC}"
}
error()
{
  message "$1" "$RED";
  exit 1
}
success() { message "$1" "$GREEN" ; }

cd "$(git rev-parse --show-toplevel)" || error "Cannot change working directory to root of Git repository!"

npm --prefix assets run extract
./assets/js/locales/normalize.sh
if npm --prefix assets run compile; then
  success "The frontend code messages have been translated."
else
  error "Commit failed due to frontend code missing translations!"
fi

if npm --prefix assets run prettier; then
  success "The frontend code is properly formatted."
else
  error "Commit failed due to frontend code formatting issues!"
fi

# ...
# several other tests
```

My `package.json` contains:

```json
{
  ...
  "scripts": {
    "extract": "lingui extract --clean ",
    ...
  },
  ...
}
```
After the hook script starts executing `npm --prefix assets run extract`, then trying to kill the process with CTRL+C does not do much as the script keeps running. I am forced to let the whole script finish or close the terminal tab which is not practical.

**Expected behavior**
CTRL+C should stop the hook script.

**Additional context**

- jsLingui version ``lingui --version``: 4.5.0
- Babel version ``npm list @babel/core``: 7.23.2
- Macro support:
 - [ ] I'm using SWC with `@lingui/swc-plugin`
 - [ ] I'm using Babel with `babel-macro-plugin`
 - [x] I'm not using macro
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, NextJs, Vite)
  `.babelrc`:
  ```json
  {
    "presets": ["@babel/preset-env", "@babel/preset-react"],
    "plugins": ["macros"]
  }
  ```

**Comment by andrii-bodnar** [comment]
You can try to catch signals like SIGINT (CTRL+C) in the main process and kill the child process:

```bash
#!/bin/bash

trap "kill -SIGINT $lingui_pid" SIGINT

# Start the extract process, storing its PID
npm --prefix assets run extract &
lingui_pid=$!
```

The `trap` command at the start of your script will kill the lingui process ID stored in the `$lingui_pid` variable. (https://www.linuxjournal.com/content/bash-trap-command)

**Comment by thekip** [comment]
Thanks for detailed investigation. Actually, lungui uses under the hood `commander` package and don't do anything extra to trap interruption signals whatsoever. 

So it's rather regular JS script which is run by node.js.  It doesn't spawn it's own child processes or call external tools. So i assume the current behaviour is just a default behaviour for long running scripts in node.
