### ISSUE TITLE
Provide some way to turn off newline collapsing

### ISSUE THREAD

**Issue by joeldouglass** [lingui/js-lingui#1834]
In our project we have blocks of markdown that will need to be translated. When extracting these blocks, Lingui collapses newlines. This makes it impossible to create a new paragraph in markdown.

Example:
 ```ts
const markdownExample = msg`# Heading 1

A paragraph

Another paragraph`;
```

is extracted to: 

```
msgstr ""
"# Heading 1\n"
"A paragraph\n"
"Another paragraph"
```

If I modify the .po file to add the extra newlines, the markdown works perfect on rendering (using react-markdown library)

```
msgstr ""
"# Heading 1\n"
"\n"
"A paragraph\n"
"\n"
"Another paragraph"
```

It would be helpful to have some way to tell Lingui to extract without reformatting or trimming the message.

**Comment by thekip** [comment]
Unfortunately, have no idea how to achieve this without breaking everything else.

**Comment by joeldouglass** [comment]
I found a workaround for the time being --

Add a variable: 

```ts
const markdownExample = msg`# Heading 1
${'_lf'}
A paragraph
${'_lf'}
Another paragraph`;
```

Then render: 

```ts
      <ReactMarkdown>
        {_(myMessage.id, { _lf: '\n' })}
      </ReactMarkdown>
```
