### ISSUE TITLE
`unraw` default export resolution error in React Native 0.73.2

### ISSUE THREAD

**Issue by estrattonbailey** [lingui/js-lingui#1836]
Hey all 👋 love the library, thanks for all the work here.

We're running into a an default export issue in our `0.73.2` app where the default import of `unraw` isn't resolved and crashes our app in production. See [GitHub issue here](https://github.com/bluesky-social/social-app/issues/2535).

Looks like `unraw` provides a [named export as well](https://github.com/iansan5653/unraw/blob/master/src/index.ts#L196), and using the patch from `patch-package` below solves our problem.

```diff
diff --git a/node_modules/@lingui/core/dist/index.mjs b/node_modules/@lingui/core/dist/index.mjs
index 9759736..881f67b 100644
--- a/node_modules/@lingui/core/dist/index.mjs
+++ b/node_modules/@lingui/core/dist/index.mjs
@@ -1,4 +1,4 @@
-import unraw from 'unraw';
+import { unraw } from 'unraw';
 import { compileMessage } from '@lingui/message-utils/compileMessage';
 
 const isString = (s) => typeof s === "string";
```

Would you be open to a PR to use the named export instead of the default?

**Comment by thekip** [comment]
aghh, hate default import/export so many pain, especially when ecosystem started switching to native ES modules.  

Thanks for reporting, i will update
