### ISSUE TITLE
Support check the translated `msgstr` as expected

### ISSUE THREAD

**Issue by yunsii** [lingui/js-lingui#1839]
**Is your feature request related to a problem? Please describe.**
After deep investigation, it seems not a simple way to check whether the translated `msgstr` as expected, for example, <0></0> can not lost, transformed expression can not broken, etc.

**Describe proposed solution**
Provide a function to check whether `msgstr` is matched to `msgid`

**Describe alternatives you've considered**
Have to create a complex function to check, but I haven't started yet.

**Comment by thekip** [comment]
It's a very broad scope which is usually already done in the [TMS](https://lingui.dev/tools/introduction).

**Comment by yunsii** [comment]
Finnally, I use `@formatjs/icu-messageformat-parser` to check.
