### ISSUE TITLE
Lingui doesn't extract msg within a msg

### ISSUE THREAD

**Issue by joeldouglass** [lingui/js-lingui#1841]
In a case where we might have a `msg` within a `msg`, Lingui skips the inner `msg` leading to a `ReferenceError: msg is not defined` at runtime.

Ex:

```jsx
<SomeComponent title={_(msg`Foo ${someFlag ? _(msg`bar`) : _(msg`baz`)}`)} />
```

Maybe there's a better way to do this?

**Comment by thekip** [comment]
As far as i remember i fixed something like that for babel version of macros, but this still an issue in SWC. 

https://github.com/lingui/swc-plugin/issues/16
https://github.com/lingui/js-lingui/pull/1436

These two issues about JSX ternary but it seems it's also applicable for JS ternary.

The workaround would be just avoiding putting ternary into the msg:

```ts
const innerMessage = ${someFlag ? _(msg`bar`) : _(msg`baz`)}
<SomeComponent title={_(msg`Foo ${innerMessage}`)} />

```

**Comment by thekip** [comment]
Should be fixed for babel macro with https://github.com/lingui/js-lingui/pull/1867
