### ISSUE TITLE
Error when aliasing Trans from '@lingui/react' in presence of macro Trans from '@lingui/macro'

### ISSUE THREAD

**Issue by kzuraniewski** [lingui/js-lingui#1844]
**Describe the bug**

Aliasing Trans import from '@lingui/react' when '@lingui/macro' is present produces the following error:

```
Uncaught ReferenceError: Trans is not defined
```

**To Reproduce**

Let's assume there is a component translating both direct text and some outside data. When aliasing runtime Trans the error is produced:

```tsx
import { Trans } from '@lingui/macro';
import { Trans as TransRuntime } from '@lingui/react'; // aliasing here so the names don't collide

const data = [msg`Foo`, msg`Bar`];

export default function App() {
   return (
      <div>
         <Trans>Direct text</Trans> // <- Uncaught ReferenceError: Trans is not defined
         {data.map(el => <TransRuntime id={el.id} />)}
      </div>
   );
}
```
From what I've tried, it happens only when runtime Trans is aliased:

```tsx
import { Trans as TransMacro } from '@lingui/macro'; // aliased macro Trans instead, error is gone
import { Trans } from '@lingui/react';
```
```tsx
// aliasing both, error is thrown by TransMacro
import { Trans as TransMacro } from '@lingui/macro'
import { Trans as TransRuntime } from '@lingui/react';
```

Although there is a workaround, no explicit error is shown when we incorrectly alias the components, making it hard to fix. I think it should be possible to name both imports freely.

**Additional context**

- jsLingui version: 4.7.0
- Babel version: 7.23.9
- Macro support:
 - [ ] I'm using SWC with `@lingui/swc-plugin`
 - [x] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro
- Using Vite with babel, config: `{ plugins: ['macros'] }`

**Comment by thekip** [comment]
Interesting, i will take a look.

**Comment by thekip** [comment]
Should be fixed for babel macro with https://github.com/lingui/js-lingui/pull/1867
