### ISSUE TITLE
Improve React syntax with useLingui

### ISSUE THREAD

**Issue by dan-dr** [lingui/js-lingui#1852]
**Is your feature request related to a problem? Please describe.**
I'm implementing lingui for my company's product, with DX being among the top priority.
The syntax when using the lingui hook is quite clunky.

First, there are 2 ways to translate (correct me if i'm wrong):
```typescript
import { t, msg } from '@lingui/macro';

// react component
() => {
  const { i18n, _ } = useLingui();
  const one = _(msg`First way to translate`);
  const two = t(i18n)`Second way to translate`;
}
```

Second, each of these ways are somewhat "special" syntax with 2 parts each (`_` and `msg`, `t` and `i18n`).

I find the DX and readability sub-par with the high quality of this library and it's tooling.

**Describe proposed solution**
Basically I'd like to do something like:
```typescript
import { useLingui } from '@lingui/macro';

// react component
...
  const { i18n, _, t } = useLingui();
  const justOneWay = t`Very Cool`;
...
```

I'm guessing the macro should transform this to:
```typescript
import { useLingui } from '@lingui/react';

const { i18n, _ } = useLingui();
const justOneWay = _({ ...message descriptor... });
```

Not sure exactly about the naming or the macro API. maybe it's better to separate the hooks
```typescript
const { t } = useTranslate()
t`String`;
↓ becomes
const { _ } = useLingui();
_({...descriptor});
```
but then you probably need to account for other use of useLingui and merge the declaration, which isn't impossible.

**Describe alternatives you've considered**
I tried to play around with a custom hook to wrap, but I don't think it's possible with the macro implementation.
neither of these hacks are possible (and probably for a good reason:
```typescript
  const t = React.useCallback(
    (literals: TemplateStringsArray, ...placeholders: any[]) => {
      return _(defineMessage(literals, placeholders));
      nor
     return t(i18n)(literals, placeholders);
    },
    [.. dependencies],
  );
```

**Additional context**
I'm not familiar with macro implementation, else I'd give it a whirl myself...

**Comment by thekip** [comment]
The current design here for a reason. Indeed, the design proposed by you is better and I even investigated to possibility to do something like that before. However, there are technical restrictions on the babel-macro side and also this kind of transpilation opens a wide variety of usages user's could do with these functions which we could not know ahead of time and it would be a big maintenance burden to handle all possible cases in transpilation. 

The current flow is much simpler, we take 1 existing node and replacing to another one. To achieve what you're proposing you need replace multiple related to each other nodes and traverse AST back and forth which is waay more complicated process.

**Comment by wentokay** [comment]
I had similar thoughts about this today and while I was trying the different suggested approaches, I noticed that this

```tsx
const Component = () => {
  useLingui();
  return <div>{t`Always updates after switching locales`}</div>;
}
```

effectively behaves the same way as

```tsx
const Component = () => {
  const { i18n } = useLingui();
  return <div>{t(i18n)`Always updates update after switching locales`}</div>
}

```

I assume this is an unexpected/unsupported behavior?

I haven't dug too deep into the lingui source yet but I assume it's because `useLingui()` is updating the i18n reference used by the macro below it with what it gets from React Context?

I don't think I'll use that approach in the long term, but we just migrated from i18next and with 300+ files to update it might be a quick and useful temporary fix while figuring out a better long term strategy.

I'm currently trying to see if there's any way to guarantee that `i18n` is a global singleton shared across our monorepo, rather than needing to inject it in every t``.

**Comment by wentokay** [comment]
Thanks for the detailed explanation.

We actually opted for a full reload after switching locales like you suggested and it's been working great for our requirements!

**Comment by dan-dr** [comment]
I'm thinking you can probably do this
```typescript
import { useLingui } from '@lingui/macro';

() => {
  const { _ } = useLingui();
  
  let a = _`Text`;
  
  let b = React.useMemo(() => { return _`B` }, [_]);
}

// transforms into
import { useLingui } from '@lingui/react';

() => {
  const { _ } = useLingui();
  
  let a = _(...descriptor...);
  
  let b = React.useMemo(() => { return _(...descriptor...) }, [_]);
}
```
by using `scope.getBinding('_')` in the macro and then traversing it's `referencePaths`, if there is a taggedtemplate call, replace it with callexpression and descriptor, and if it's an arrayexpression leave it. other uses should throw the reportUnsupportedSyntax. I'm trying to write it but can't seem to be able to run the project locally :/

**Comment by thekip** [comment]
Thanks for digging into it, firstly we are a bit restricted with what babel-macro allow us to do. Secondly we also have SWC plugin which replicate functionality and we should keep them in sync and SWC's plugins API doesn't replicate babel's API especially in part of scopes and references.  

I don't say this is not possible, I just say this would open a Pandora's box of weird cases.  Also, you need to consider that lingui supports recursive macro expanding, such as: 

```ts
t`Hello ${plural(count, {single, plural})}`
```
Any way, if you are willing to try, I can assist you in discord.

**Comment by dan-dr** [comment]
Yeah I had a decent attempt that worked the way I mentioned I wanted but nesting was an issue. check it here: https://github.com/dan-dr/js-lingui/tree/feat/improved-react-hook-syntax

I'll give it up for now, and might go with the wrapping fragment since we are only client side. feel free to close or keep open for more ideas.

**Comment by thekip** [comment]
Well, i picked it up when you finished and was able to make it work.

**Comment by thekip** [comment]
@dan-dr could you try on your project?  [Here is how to run it on your local project](https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md#using-development-version-in-your-project)

https://github.com/lingui/js-lingui/pull/1859

**Comment by thekip** [comment]
published as https://github.com/lingui/js-lingui/releases/tag/v4.8.0-next.0
