### ISSUE TITLE
a special message cant compile.

### ISSUE THREAD

**Issue by hhniao** [lingui/js-lingui#1862]
this is work
`i18n.t("Please input the {name}, e.g.: A*B/(100+5-6)", {name: i18n.t("calculate formula")})`

this not work
`i18n.t("Please input the {name}, e.g.: A*B/(100+5-6).", {name: i18n.t("calculate formula")})`

**Comment by andrii-bodnar** [comment]
@hhniao please follow the issue template while creating bug reports - https://github.com/lingui/js-lingui/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
