### ISSUE TITLE
`lingui` can be null

### ISSUE THREAD

**Issue by flashburst** [lingui/js-lingui#1864]
https://github.com/lingui/js-lingui/blob/107bd02edc26d6bb631923288db88d9036604cc8/packages/react/src/TransNoContext.tsx#L57

<img width="782" alt="image" src="https://github.com/lingui/js-lingui/assets/82953782/e4118c4a-88db-41d2-981c-98e33fbb0655">

**Comment by thekip** [comment]
Please follow the issue template while creating bug reports - https://github.com/lingui/js-lingui/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by andrii-bodnar** [comment]
#1868
