### ISSUE TITLE
Support Gatsby

### ISSUE THREAD

**Issue by flashburst** [lingui/js-lingui#1868]
**Is your feature request related to a problem? Please describe.**
Unable to use lingui/react in a gastby project

**Describe proposed solution**
`useLingui` should not return null. Or it should be handled properly with conditional logic

**Describe alternatives you've considered**
`React.createContext(null)` should be replaced with a better default context value instead of null

**Additional context**
https://github.com/lingui/js-lingui/blob/107bd02edc26d6bb631923288db88d9036604cc8/packages/react/src/TransNoContext.tsx#L57

![image](https://github.com/lingui/js-lingui/assets/82953782/1cb66f54-3f3b-4200-b23c-c4e8a0b2e3cc)

**Comment by thekip** [comment]
If lingui context is null, it means you did not wrap your React tree into Provider, what you expecting to have here?
