### ISSUE TITLE
React Fragment (`<>`) inside `<Plural>` is not working

### ISSUE THREAD

**Issue by simlmx** [lingui/js-lingui#1889]
**Describe the bug**

Using `<>...</>` inside `<Plural />` does not work.

This code:

```jsx
<Plural
  value={value}
  one={
    <>
      There is <b>1</b>.
    </>
  }
  other={
    <>
      There are <b>#</b>.
    </>
  }
/>
```

gets extracted to:
```
msgid "{value, plural, one {{0}} other {{1}}}"
msgstr ""
```

**However**, using the full `<React.Fragment>` instead of `<>` does work and the result is as expected:

```
msgid "{value, plural, one {<0>There is <1>1</1>.</0>} other {<2>There are <3>#</3>.</2>}"
msgstr ""
```

**To Reproduce**

```jsx
import { Plural } from "@lingui/macro"

export default function App() {
  const value = 3;

  return (
    <Plural
      value={value}
      one={
        <>
          There is <b>1</b>.
        </>
      }
      other={
        <>
          There are <b>#</b>.
        </>
      }
    />
  )
}

```

**Expected behavior**

The extracted messages when using `<>` are the same as when using `<React.Fragment>`

**Additional context**

```
lingui: 4.7.1
@babel/core: 7.23.9
babel-plugin-macros: 3.1.0
```

babel config:
```json
{
  "presets": ["next/babel"],
  "plugins": ["macros"]
}
```

**Comment by thekip** [comment]
This syntax is not supported and not planned. You can wrap inner branches into '<Trans>'

I will prepare a PR which will show an error message on attempt to use this syntax.

**Comment by andrii-bodnar** [comment]
@thekip what do you think about adding a rule for this case to the ESLint plugin?

**Comment by simlmx** [comment]
But I don't understand: it works fine with `<React.Fragment>` or `<span>` or any tag.

Are only `string`s supposed to be supported as arguments to `one`, `other`, etc.?

If so what is the canonical way to achieve what I'm trying to do, basically: `There is/are <b>#</b>`?

Here is another example using `SelectOrdinal`, that feels legitimate and that also works fine with `React.Fragment`:
```tsx
<SelectOrdinal
  value={value}
  other={<React.Fragment>#<sup>th</sup></React.Fragment>}
/>
```

**Comment by thekip** [comment]
Canonical way is to use Trans instead of React.Fragment

**Comment by simlmx** [comment]
Alright thanks!

By the way the only example in the documentation that uses html elements in the `one`, `other`, ... attributes of `Plural` (and not just `string`s) is in [the introduction][1] and it does not use `Trans` but `span` (which seemed more intuitive!).

[1]: https://lingui.dev/introduction
