### ISSUE TITLE
definePlural macro

### ISSUE THREAD

**Issue by wolflu05** [lingui/js-lingui#1893]
**Is your feature request related to a problem? Please describe.**
the `msg`/`defineMessage` macro is really useful to define a message and passing it down to another component which uses that translation with variables. 

This would be especially useful for plurals, as they can be defined somewhere and the translation can be used further way down in a component with the correct count. But there is no such `definePlural` helper, and since this is a macro I cannot just recreate that as a util function on my own.

**Describe proposed solution**
Add a `definePlural` macro that can be used like so:
```tsx
import { MessageDescriptor } from "@lingui/core";
import { useLingui } from "@lingui/react";

const Component = ({ translation }: { translation: MessageDescriptor}) => {
  const { _ } = useLingui();

  return <div>{_({ ...translation, values: { count: 1 } })}
}

const App = () => {
  const translation = definePlural({ one: "Delete {count} book", other: "Delete {count} books"});
  return <Component translation={translation} />
}
```

**Describe alternatives you've considered**
Use RAW plural syntax in combination with a message
```tsx
import { defineMessage } from "@lingui/macro";

const App = () => {
  const translation = defineMessage`{count, plural, one {Delete {count} book} other {Delete {count} books}}`;
  return <Component translation={translation} />
}
```

**Additional context**
/

**Comment by thekip** [comment]
Kinda hacky, but should work: 

```ts
const count = 0;
const myPluralMessageDescriptor = msg`${plural(count, { one: "Delete # book", other: "Delete # books"})}`

const App = () => {
  const { _ } = useLingui();
  return _({ ...myPluralMessageDescriptor, values: { count: 1 } })
}
```

**Comment by wolflu05** [comment]
Thank you very much for your fast reply, yes, that actually works. Thanks for telling me. 

Does this mean that under the hood when extracting the translations via macros the plural function gets replaced first and then the msg can use this? Or how does this work?

**Comment by thekip** [comment]
The macro's code encounters `msg` expression and start expanding it recursively. It works the same way how `t` macro works. 

```ts
const translation = t`Are you sure you want to delete ${plural(count, { one: "# book", other: "# books"})}`
```

The only difference between `t` and `msg` is the latest is not wrapped in `i18n.t` call, and left descriptor as is: 

```ts
// t
i18n.t({id: "", message: "...."})

// msg / defineMessage
{id: "", message: "...."}
```

**Comment by wolflu05** [comment]
Thank your very much for your help. I think we can close this then from my side, there is no separate macro needed.
