### ISSUE TITLE
.js files shipped in npm are not ES5

### ISSUE THREAD

**Issue by brunesto** [lingui/js-lingui#19]
Hi, it seems to me that the .js files shipped in npm are not ES5, so it wont work with IE11 and older
    
    $ npm install --save-dev lingui-i18n
    $ cat node_modules/lingui-i18n/lib/compile.js | grep -Hn '{ language,'
    (standard input):73:    return formattedMessage(context({ language, params, formatStyles }));

it should be  { language:language, params:params ...
And I guess there is the same problem with lingui-react

Thanks

**Comment by tricoder42** [comment]
Fixed in latest releases on npm (https://github.com/lingui/js-lingui/commit/73b6195300b881d3b6bf5383601104eafa8122a4)

**Comment by brunesto** [comment]
Thanks! just tested it on IE11 and it works fine now

**Comment by tricoder42** [comment]
Good to hear, thank you for reporting a testing!
