### ISSUE TITLE
Feature Request: Add sorting option to extract

### ISSUE THREAD

**Issue by machour** [lingui/js-lingui#190]
`extract` currently writes the messages in the order they were found while parsing the source directory.

adding a `--sort` option with the following values could be handy:

- "files": current behavior
- "message": alphabetically sorted by the source language

Maybe empty untranslated messages could be inserted at the top of the file, same way obsolete messages are currently at the bottom.

Would happily provide a PR if it's okay with you

**Comment by tricoder42** [comment]
Hey @machour, sounds good. Could you also please add corresponding config value to `lingui-conf`?

Should it be considered backward-incompatible change if we move untranslated messages to the top? I guess not, but it may be surprising when catalog will change between `lingui-cli` versions. Anyway, definitely sounds like a good idea.

Let me know if you need anything from me, I've just returned from vacation 👍

**Comment by tricoder42** [comment]
Hey, I'm closing this because message catalogs are sorted alphabetically by default since [v2.2.0](https://github.com/lingui/js-lingui/releases/tag/v2.2.0)
