### ISSUE TITLE
Escaped curly-braces doesn't preserve in development mode

### ISSUE THREAD

**Issue by thekip** [lingui/js-lingui#1901]
**Describe the bug**

Escaped placeholders still get processed as placeholder in development mode. 

**To Reproduce**

repro: https://github.com/ninesunsabiu/lingui-brace-bug/blob/main/src/App.tsx

```ts
const literalBrace = i18n._(msg`Hey '{name}'!`)
```

Rendered as `Hey !`. `{name}` treated as placeholder and replaced to empty string

**Expected behavior**
It should print `Hey {name}!`, placeholder is not processed and kept as-is. 

**Root Cause**
This happend because message get double compiled in Dev mode.

First compilation (compiled in catalog):

> `Hey '{name}`' -> `Hey {name}`

Second compilation happened for already compiled message from catalog in runtime in i18n: 
> `Hey {name}` -> `Hey <replaced to value>`

**Comment by ninesunsabiu** [comment]
Any progress updates?
