### ISSUE TITLE
selectOrdinal error

### ISSUE THREAD

**Issue by SergelenOchir** [lingui/js-lingui#1911]
```
import {selectOrdinal, t} from '@lingui/macro';

export function PluralPaymentText(count: number) {
  try {
    return t({
      message: selectOrdinal(count, {
        one: '#st payment',
        two: '#nd payment',
        few: '#rd payment',
        other: '#th payment',
      }),
    });
  } catch (err) {
    console.log(err, 'error');
    return count;
  }
}
```
version: "@lingui/core": "^4.8.0" 
this function is returning this error: _[TypeError: Cannot read property 'prototype' of undefined]_

how to fix it please help me?

**Comment by thekip** [comment]
Please follow the issue template.  And show the stacktrace of the issue.  Does just `` t`Hello` `` works?

**Comment by SergelenOchir** [comment]
> Please follow the issue template. And show the stacktrace of the issue. Does just `` t`Hello` `` works?

Yeah it works

**Comment by wcastand** [comment]
@SergelenOchir hi, what was the issue currently getting this error on plural macro
