### ISSUE TITLE
Lingui CLI extraction puts msgid as msgstr

### ISSUE THREAD

**Issue by EnablingLogic** [lingui/js-lingui#1921]
**Describe the bug**
In my application, I have a translation with ID `addToCart`. Since I use it in multiple files, I've only provided a default message once. Now, when I extract the messages, it's extracted as:

```
msgid "addToCart"
msgstr "addToCart"
```

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

`ComponentOne.tsx`
```tsx
import { i18n } from "@lingui/core"

export default function ComponentOne() {
  return i18n._("addToCart")
}
```

`ComponentTwo.tsx`
```tsx
import { i18n } from "@lingui/core"

export default function ComponentTwo() {
  return i18n._({ id: "addToCart", message: "Add to cart" })
}
```

Now run `lingui extract --overwrite --clean` with this as `lingui.config.js`:

```js
module.exports = {
  orderBy: "messageId",
  locales: [ "en", "nl", "de" ],
  fallbackLocales: {
    default: "en"
  },
  sourceLocale: "en",
  catalogs: [
    {
      path: "./locales/{locale}/messages",
      include: [ "**/**/*.ts*" ],
      exclude: [ "node_modules/**", "**/*.d.ts" ]
    }
  ],
  format: "po",
  compileNamespace: "ts"
}
```

**Expected behavior**
I expect the message to be extracted as:

```
msgid "addToCart"
msgstr "Add to cart"
```

**Additional context**

- jsLingui version ``lingui --version``: 4.8.0
- Babel version ``npm list @babel/core``: 7.24.4
- Macro support:
 - [ ] I'm using SWC with `@lingui/swc-plugin`
 - [ ] I'm using Babel with `babel-macro-plugin`
 - [x] I'm not using macro
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, NextJs, Vite): I'm using Next.js

**Comment by thekip** [comment]
I don't have a capacity to look into it right now, but can provide you with a direction: 

Here is a snippet responsible for default message: 

https://github.com/lingui/js-lingui/blob/2cb5175768f2bfc855e8f3dd1a105d59ba7d39f8/packages/cli/src/api/catalog/extractFromFiles.ts#L32-L58

You can debug it and make a PR. Thanks.

**Comment by aseerkt** [comment]
What is the expected behavior here?, should it throw error when it encounters two different messages for same ID?

**Comment by thekip** [comment]
Yes, but should ignore instances where message is not provided (take existing if any)
