### ISSUE TITLE
ReactFest talk about i18n

### ISSUE THREAD

**Issue by sedubois** [lingui/js-lingui#195]
https://www.youtube.com/watch?v=6NwgHUcom_8

Was interesting to watch even if only mentions react-intl. CLDR, ICU, IETF standards + more complex examples of how to use message format. Sorry that it's not an "issue", please close...

**Comment by tricoder42** [comment]
Thank you! I've just added a new section to docs with [talks about i18n](https://lingui.github.io/js-lingui/misc/talks-about-i18n.html). Feel free to [add more](https://github.com/lingui/js-lingui/edit/stable-2.x/docs/misc/talks-about-i18n.rst) if you know any.
