### ISSUE TITLE
Avoid flashing of the default language

### ISSUE THREAD

**Issue by fain182** [lingui/js-lingui#1951]
**Describe the bug**
As discussed in #899, using nextjs if I set the locale in the first rendering I have a bad setState() error.
The solution proposed is set the correct locale in a useEffect, that flashes the wrong language at the first rendering (and is not executed in the SSR).

How can I avoid the flashing of another language?

**Comment by thekip** [comment]
please see [nextjs example ](https://github.com/lingui/js-lingui/tree/main/examples/nextjs-babel) and repeat integration **thoroughly**
