### ISSUE TITLE
multi-line comment not formatted correctly

### ISSUE THREAD

**Issue by taozhou-glean** [lingui/js-lingui#1978]
**Describe the bug**

multi-line comment seems to be extracted missing `#.` on subsequent lines

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```tsx
 <Trans
    comment="this is a multi-line comment
    the second line"
  >
    Some text
  </Trans>
```

**Expected behavior**
```
#. this is a multi-line comment
#. the second line
#. js-lingui-id: Ot/Ga/
msgid "Some text"
msgstr "Some text"
```

actual result:

```
#. this is a multi-line comment
        the second line
#. js-lingui-id: Ot/Ga/
msgid "Some text"
msgstr "Some text"
```

**Additional context**
lingui itself seems to be able to parse this just fine, but library like crowdin will treat this message catalog file as invalid

- jsLingui version ``lingui --version``: 4.11.2
- Babel version ``npm list @babel/core``
- Macro support:
 - [x] I'm using SWC with `@lingui/swc-plugin`
 - [ ] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, NextJs, Vite)

**Comment by aseerkt** [comment]
Reproducible - https://stackblitz.com/edit/vitejs-vite-jiwzn1?file=src%2Flocales%2Fen.po
