### ISSUE TITLE
Development guidelines

### ISSUE THREAD

**Issue by snegostup** [lingui/js-lingui#198]
@tricoder42 can you provide some guidelines on how to setup environment and work on the lib? 

Right now we have [Contributing guidelines](https://github.com/lingui/js-lingui/blob/master/CONTRIBUTING.md) but it's not enough info there. 

For example when taking step `3. yarn test`, test fails with multiple errors `Could not locate module @lingui/conf...` because it hasn't been built and there's no info how to build it. I see `scripts/build/` directory and can guess that it's what should be run beforehand but there's no info which file tor run etc.

**What I'd like to see is the list of steps needed from cloning the lib to setting up everything so that one can modify, build and link it to an existing project in order to be able to test it.**

I think such guidelines will help people who want to contribute a lot.

**Comment by HriBB** [comment]
I would like to see an example of how to extract messages from outside the project root or programatically with a node script. Right now it's super tricky, because of the way babel handles preset and plugin resolution.

**Comment by tricoder42** [comment]
@snegostup Good point! I updated [contributors guide](https://github.com/lingui/js-lingui/blob/master/CONTRIBUTING.md), `lerna:boostrap` is no longer required. Also, `yarn test` no longer runs integration tests, only unit tests. If you want to run full test suite, feel free to run `./scripts/test.js` (as mentioned in contributors guide).

I've just tested all commands in fresh repo and it looks good. Let me know if it doesn't work for you.

@HriBB Could you please create a new issue for this? This would be great tutorial/guide to documentation. In short: babel preset is preferred way, but if it fails, you're better off using plugins directly (put them as much on the top as possible).

**Comment by tricoder42** [comment]
> What I'd like to see is the list of steps needed from cloning the lib to setting up everything so that one can modify, build and link it to an existing project in order to be able to test it.

Oh I forgot the most important part of your issue :)

Yeah, this would be great to document. I'm using [`yalc`](https://www.npmjs.com/package/yalc) to link builded packages against examples in [`integration.js`](https://github.com/lingui/js-lingui/blob/master/scripts/integration.js).

Please take a look. I might write it down in contributors guide later.

**Comment by snegostup** [comment]
@tricoder42 thanks! That's what I needed. Do you manually rebuild after change or is there a way to make it watch and automatically rebuild on change?

**Comment by tricoder42** [comment]
Hey @snegostup, I've just mentioned it in [contributing docs](https://github.com/lingui/js-lingui/blob/stable-2.x/CONTRIBUTING.md#using-development-version-in-your-project). You need to run `yarn release:build` (shortcut for `node ./scripts/build/`) manually.

I always create a unit test for all I need, because unit tests run in watch mode. I use `yalc` only as a final check in local project.
