### ISSUE TITLE
LinguiJS & Next.js standalone build not working

### ISSUE THREAD

**Issue by itaie01** [lingui/js-lingui#1985]
**Describe the bug**
I have been working on a relatively simple web application for the past few months. The tech stack is primarily pnpm, Next.js, and TypeScript. I had finished implementing translation with Lingui.js with both v4.10 and v4.11 as official support and recommended structure for RSC came out with v4.11.

Regardless of the version, I encountered the same issue. In standalone build mode for Next.js, translations between languages do not seem to working.

Trying to hone in on the issue, just now I cloned [this](https://github.com/lingui/js-lingui/blob/main/examples/nextjs-swc) official example/test project of Lingui.js with support for RSC in Next.js and applied the same local build commands I had been following with my project and have encountered the same issues where translations do not change when selecting a new language.

**To Reproduce**
1. Clone [this](https://github.com/lingui/js-lingui/blob/main/examples/nextjs-swc) repo.
2. Run next build (I made some minor changes to use pnpm instead of yarn but the process should be the same)
3. Copy the static folder in .next to .next/standalone/.next/server
4. Run node next/standalone/ server.js

**Expected behavior**

**Additional context**

- jsLingui version: 4.11.0
- Macro support:
 -  I'm using SWC with `@lingui/swc-plugin` v4.0.7
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, NextJs, Vite)

```js
/** @type {import('next').NextConfig} */
module.exports = {
  // i18n: {
  // this option has been replaced by the middleware in src/
  // when migrating to support app router
  // },
  typescript: {
    ignoreBuildErrors: true
  },
  output: 'standalone',
  webpack: (config) => {
    config.module.rules.push({
      test: /\.po$/,
      use: {
        loader: '@lingui/loader'
      }
    })
    return config
  },
  experimental: {
    swcPlugins: [['@lingui/swc-plugin', {}]]
  }
}
```
Note: ignoreBuildErrors is only enabled to ignore a few type issues. I don't think this should be an issue.

**Comment by thekip** [comment]
@vonovak fyi

**Comment by vonovak** [comment]
Hello and thanks for asking,
there are 2 issues:

(1) the `static` folder in `.next` should be copied to `.next/standalone/.next`, not to `.next/standalone/.next/server`

(2) nextJS's middleware seems to behave differently in standalone build, because the lingui-related code is called even for the `favicon.ico` route. I don't have time to investigate now but it seems unexpected. This https://github.com/lingui/js-lingui/pull/1987 makes debugging of this issue easier.

Does this answer the issue? 🙂 
Thank you

**Comment by itaie01** [comment]
At the moment I think it does. I'll implement these changes in my project and will report back over the next few days! Thanks for the quick response.
