### ISSUE TITLE
Monorepo: Per-package Lingui config requires `locales` key

### ISSUE THREAD

**Issue by nyadav810** [lingui/js-lingui#1986]
**Is your feature request related to a problem? Please describe.**
I have defined a `lingui.config.ts` file per package in my monorepo using Turborepo and TypeScript. The [Mono repo docs](https://lingui.dev/guides/monorepo) state that per package config `extends/overrides from root`. I would expect to not have to include the `locales` key, but the `LinguiConfig` type requires it.

**Describe proposed solution**
I should not have to specify `locales`, Lingui should pull locales from the root config unless specified in the per-package config.

**Describe alternatives you've considered**
My solution is importing the root config and defining the `locales` array as follow:

```
import type { LinguiConfig } from "@lingui/conf";

import rootConfig from "../../lingui.config";

// https://lingui.dev/ref/conf
const config: LinguiConfig = {
  locales: rootConfig.locales,
  catalogs: [
    ...
  ],
};

export default config;
```

**Additional context**

Here is the screenshot I get when I try to remove the `locales` key from per-package config altogether

<img width="548" alt="Screenshot 2024-07-29 at 1 42 16 PM" src="https://github.com/user-attachments/assets/27dd0738-15f2-4cca-8c03-47cc58224550">

**Comment by thekip** [comment]
You configuration is what exactly monorepo docs propose. There is no logic for crawling and merging configs built-in into lingui cli.

**Comment by Jack-Works** [comment]
what if I want to use it in "package.json"? I don't want to add a new file in every package because that's a lot, I hope I can do that in package.json by "lingui" field.

**Comment by vonovak** [comment]
> what if I want to use it in "package.json"? I don't want to add a new file in every package because that's a lot, I hope I can do that in package.json by "lingui" field.

Hello, hiw is it different to put multiple config files in project vs putting the config in multiple package.json files?

Just trying to understand.
Thank you

**Comment by Jack-Works** [comment]
> > what if I want to use it in "package.json"? I don't want to add a new file in every package because that's a lot, I hope I can do that in package.json by "lingui" field.
> 
> Hello, hiw is it different to put multiple config files in project vs putting the config in multiple package.json files?
> 
> Also, have you tried using just one config file? I have found that it can work depending on what your needs are.
> 
> Just trying to understand. Thank you

I'll need to add `lingui.config.js` under all workspace packages and we have 40+ packages. I don't want to add so many config files
