### ISSUE TITLE
cli/extract: throw when encountering same id with different defaults

### ISSUE THREAD

**Issue by snegostup** [lingui/js-lingui#200]
I believe such situation is unexpected and we should warn (or better error) when encountering it.
Right now it saves last extracted defaults and discards all the others.

I didn't look how to better do this but let it be here for now so we can later discuss and implement this.

**Comment by tkvw** [comment]
I think we should allow undefined; this would allow to enter the default message once and use the id only in other cases. 
Given: 
```
<Trans id="about">About</Trans>
```
and:   
```
<Trans id="about"/>
```
throws : 
```
Error: Encountered different defaults for message about
pages/about.js:8 About
pages/index.js:26 undefined
```

**Comment by tricoder42** [comment]
@tkvw The problem might be when message contains variables.

```jsx
<Trans id="about">About {section}</Trans>

// becomes
<Trans id="about" defaults="About {section}" values={{ section }} />

// but we would have just
<Trans id="about" defaults="About {section}" />
```

so, yes, this should be possible, but you just have to pass `values` manually:

```jsx
<Trans id="about" values={{ section }} />
```
