### ISSUE TITLE
Duplicate endlines are removed when using @lingui/macro

### ISSUE THREAD

**Issue by jeresig** [lingui/js-lingui#2007]
**Describe the bug**
Duplicate endlines are removed when using `@lingui/macro`.

**To Reproduce**

```tsx
import {t} from "@lingui/macro"

const a = t`some

string`;
```

If I run this through babel I get:

```
"use strict";

var _core = require("@lingui/core");
const a = _core.i18n._(
/*i18n*/
{
  id: "UyBhQr",
  message: "some\nstring"
})
```

Note that there is only a single endline.

**Expected behavior**
I would expect that all endlines (and whitespace) would be left intact!

**Additional context**
This appears to be the code in question:
https://github.com/lingui/js-lingui/blob/6d0030146cc73f457e4cdcd1837f3d8f060d16fc/packages/macro/src/macroJs.ts#L31

It appears as if this was an intentional change - but I'm unsure why? I would want to treat all whitespace (and endlines) as intentional - I'm not sure why they're being stripped here? (In our case, the multiple endlines being stripped as actually causing code to break  that was expecting multiple endlines - I could see this being a problem for whitespace, as well.) If this is useful for other folks, then maybe we could have an option for turning off the whitespace stripping?

- jsLingui version: 4.11.3
- Babel version: 7.24.5
- Macro support: I'm using Babel with `babel-macro-plugin`

**Comment by thekip** [comment]
I agree with you, that's why I changed the behavior in upcoming v5 release (you already can use it with the `next` tag), here is a changelog note https://github.com/lingui/js-lingui/blob/e7b95a87496ba26db85cbae3b135650737f40fd0/website/docs/releases/migration-5.md#changes-in-whitespaces-handling

**Comment by jeresig** [comment]
Fantastic - thanks a bunch!
