### ISSUE TITLE
Plural not defined in production mode

### ISSUE THREAD

**Issue by rmales** [lingui/js-lingui#201]
Hi,

We get an error 'ReferenceError: Plural is not defined' when our app is built in production mode. The app is based on [React Boilerplate](https://github.com/react-boilerplate/react-boilerplate) and our Babel config looks like:

    "babel": {
        "plugins": [
            "styled-components"
        ],
        "presets": [
            [
                "env",
                {
                    "modules": false
                }
            ],
            "react",
            "stage-0",
            "@lingui/babel-preset-react"
        ],
        "env": {
            "development": {
                "only": [
                    "app",
                    "internals/scripts"
                ],
                "plugins": [
                    "transform-react-jsx-source"
                ]
            },
            "production": {
                "only": [
                    "app"
                ],
                "plugins": [
                    "transform-react-remove-prop-types",
                    "transform-react-inline-elements",
                    "transform-react-constant-elements"
                ]
            },
            "test": {
                "plugins": [
                    "transform-es2015-modules-commonjs",
                    "dynamic-import-node"
                ]
            }
        }
    },

I guess this must be something to do with the Plural component not being transformed by Babel in production mode, similar to what is reported in #130 and #169.

**Comment by tricoder42** [comment]
#130 is a bit different, but you're right: `Plural` is transformed to `Trans` tag and removed from imports.

Could you please take a look how transformed code looks like around `Plural` tag? Could you also paste small snippet of how code with `Plural` looks before/after transformation? Just those few lines with `Plural`.

Also, how do you import `Plural` tag?

**Comment by rmales** [comment]
The requested snippets are below (they don't look very useful to me though, so let me know if you need anything more).

Source:
```jsx
<H2>
    <Plural
        value={this.props.projects.length}
        one="# project"
        other="# projects"
    />
</H2>
```

Compiled (but not minified):
```
}, void 0, DashboardContainer__jsx(H2_default.a, {}, void 0, DashboardContainer__jsx(Plural, {
    value: this.props.projects.length,
    one: '# project',
    other: '# projects'
}))), DashboardContainer__jsx('div', {
```

Import:
`import { Plural } from '@lingui/react';`

**Comment by tricoder42** [comment]
@rmales Yeah, it seems like the transform plugin doesn't run. There should be no `Plural` in compiled source code. What's your babel config?

**Comment by rmales** [comment]
@tricoder42 Our Babel config is in my original message. I had to remove Lingui from our app due to this issue unfortunately, so I can't easily test it now. I suspect the issue may be specific to our app as we have React Router set up to [instantiate components](https://reacttraining.com/react-router/web/api/Route/component) for some routes, and we also make extensive use of render props, which probably make the AST incomplete or difficult for the transformer to deal with.

**Comment by lecstor** [comment]
Just to note, this error can be caused by transpiling with Typescript before Babel. Setting `"jsx": "preserve"` in tsconfig resolved the issue for us (had to set up a custom tsconfig for jest tests that don't use babel though).

**Comment by rmales** [comment]
Our application uses some components that have been compiled from Typescript, so maybe that could be the cause (we don't have control over their compilation though)?

**Comment by lecstor** [comment]
If those components contain js-lingui translations and Typescript is processing the JSX, then yes, it seems it could possibly be the cause.

**Comment by tricoder42** [comment]
@rmales Indeed, when transpiling typescript, it's necessary to set `jsx: preserve` as described in [Typescript guide](https://lingui.github.io/js-lingui/guides/typescript.html).

If you're using 3rd party components which doesn't use `jsLingui`, then you should be fine. Only the components which uses `jsLingui` must be processed first with babel plugin as @lecstor pointed out.
