### ISSUE TITLE
Allow comments from translators

### ISSUE THREAD

**Issue by molokovev** [lingui/js-lingui#2011]
**Is your feature request related to a problem? Please describe.**

In our translation flow, we upload the generated CSV files to an external tool (a simple google sheet) where our UX designer, along with adding translations for one of the languages, refines the messages so to prepare them for external translators.

One important part of this refinement is adding comments to messages, so that external translators understand the context. This is very similar to the existing `comments` field, but a one that comes from an external source instead of devs.

The problem comes in when we need to import the edited CSV files back from the google sheet to the source code repository. Since the values for the `comments` field are only supposed to be extracted from source code, they cannot be imported from an external source — they will get overridden during next `lingui extract` run.

**Describe proposed solution**
Add an extra field for external comments. It will behave exactly as `translation` behaves — its value can be stored in extracted files, edited in any way (manually by devs or by anyone externally) and won't get overridden by `extract` script.

**Describe alternatives you've considered**

Translation process change:
- filling in all the comments by devs during development state;
- or sitting together with UX designer to put the comments in the code.

Lingui change:
- changing the existing `comments` field behaviour, so that it does not get extracted from the source code but "lives" in the extracted data only.

Adding additional tooling:
- storing external comments in the repo in a separate file that would be created when importing the translated values. (this is what we ended up doing now)

**Comment by thekip** [comment]
Did you try to use `translator comment`? 

```po
white-space
#  translator-comments
#. extracted-comments
#: reference…
#, flag…
#| msgid previous-untranslated-string
msgid untranslated-string
msgstr translated-string
```

https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

**Comment by molokovev** [comment]
> Did you try to use `translator comment`?
> 
> ```po
> white-space
> #  translator-comments
> #. extracted-comments
> #: reference…
> #, flag…
> #| msgid previous-untranslated-string
> msgid untranslated-string
> msgstr translated-string
> ```
> 
> https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

I have not, thanks for the tip! I missed that part since we use raw lingui format for catalogs.
This is purely a PO files feature that lingui is not aware about, from what I understand. I will give it a try now.
