### ISSUE TITLE
Language family fallback

### ISSUE THREAD

**Issue by Jack-Works** [lingui/js-lingui#2021]
**Is your feature request related to a problem? Please describe.**
Fallback locale when the translate for a string is not found.

**Describe proposed solution**

The persudo code might look like this:

```
1. If string is translated in current locale, return it.
2. Let language family be the part before `-`. (e.g. `en` for `en-US`, `zh` for `zh-CN`)
3. If string is translated in the language family, return it.
4. Find the first locale (or a configurable fallback order) that translate the string in the current language family, if it is translated, return it.
```

For example, for the following resources:

```
str1: { en: "A", en-US: "A2" }
str2: { en: "A", zh-CN: "B" }
```

```js
_("en-US", "str1") // should return A2 (step 1)
_("en", "str1") // should return A (step 3)
_("zh", "str2") // should return B
```

**Describe alternatives you've considered**

**Additional context**
In most cases, zh-CN and zh-TW users can understand each other, so allowing them fallback to each other is better than fallback to English. This might be also true for Arbric languages.

**Comment by Jack-Works** [comment]
As a referece, i18next has this feature: https://www.i18next.com/principles/fallback#fallback-to-different-languages

**Comment by garikkh** [comment]
What about the `fallbackLocales` option in configuration:

https://lingui.dev/ref/conf#fallbacklocales

**Comment by Jack-Works** [comment]
oh sorry! I thought I read the whole documentation but didn't recall this
