### ISSUE TITLE
Duplicate message entry if the same string is used in a macro msg`String` and in a React i18n._("String") 

### ISSUE THREAD

**Issue by Raphyyy** [lingui/js-lingui#2026]
**Describe the bug**
I am using Lingui for a React app.
I have some i18n text which sometimes are inside React context, that allows me to use the following 
```
import { useLingui } from "@lingui/react";
const { i18n } = useLingui();
const myI18nString = i18n._(`Test string`);
```
And rerender if language change.

I also have some i18n text that I have to use outside of React context that I do with the `msg` macro
```
import { msg } from "@lingui/macro";
const myI18nString = msg`Test string`;
```

When I run `lingui extract` I then get 2 entries `Test string` instead of just one, which cause issues with my translating tools.

**To Reproduce**

**Expected behavior**
I expect to have only one message entry in my message.po for the same string

**Additional context**

- jsLingui version : 4.7.0
- Babel version : 7.23.7
- Macro support:
 - [x] I'm using SWC with `@lingui/swc-plugin`
 - [ ] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro
    '@lingui/swc-plugin': '^4.0.8',
    '@lingui/vite-plugin': '^4.11.2',
    '@vitejs/plugin-react-swc': '^3.7.0',

**Comment by thekip** [comment]
It's expected bahaviour.

```js
import { useLingui } from "@lingui/react";
const { i18n } = useLingui();
const myI18nString = i18n._(`Test string`);
```
Here you don't use macro, and what you pass to `i18n._(..)` is an id of message not a message itself. 

```js
import { msg } from "@lingui/macro";
const myI18nString = msg`Test string`;
```
Here you do use macro, and pass a message. The macro then generating a short id from this message. 

You should avoid mixing macro and non-macro usages. Your case could be rewritten as: 

```js
import { useLingui } from "@lingui/react";
import { msg } from "@lingui/macro";

const { _ } = useLingui();
const myI18nString = _(msg`Test string`);
```

Or starting from lingui@5 (currently released in the next channel):
```js
import { useLingui } from "@lingui/react/macro";

const { t } = useLingui();
const myI18nString = t`Test string`;
```

**Comment by bhubr** [comment]
Thanks @Raphyyy for your question and @timofei-iatsenko for answering it! I stumbled upon the same issue in our codebase: a duplicate `msgid` in the same `.po` file. One comes from a string wrapped inside `<Trans>...</Trans>` (which I believe is a macro usage), the other in `i18n._(...)`.

I'm not quite sure about how I can "avoid mixing macro and non-macro usages" as you suggest.
I think that in my case:
- In the a regular `.js` file (React hook), I have to use `i18n._(...)` over the `t` macro.
- In the `.jsx` file, I should maybe replace `<Trans>that string</Trans>` with `<>{i18n._('that string')}</>`?

I hope my question is understandable 😅. If not, I'll try to reformulate or give an example! Thanks.
