### ISSUE TITLE
Unexpectedly skipped parsing of unicode values inside a string

### ISSUE THREAD

**Issue by akimovnet** [lingui/js-lingui#2028]
**Describe the bug**
In case if `<Trans>` from `@lingui/macro` with the same string is rendered twice (it happens, for example, if you use [Strice Mode](https://react.dev/reference/react/StrictMode) in React), unicode values inside a string (for example, in the string "Hyphen\u00ADation") are not parsed. It means that instead of "Hyphen­ation" with invisible soft hyphen inside, we have "Hyphen\u00ADation".

Why it happens?
In [js-lingui/packages/core/src/interpolate.ts](https://github.com/lingui/js-lingui/blob/a68fa6093caae2500a01012d15dc4a9a05aeddd5/packages/core/src/interpolate.ts#L7) there is such a regular expression to test if the string has unicode values inside:

```export const UNICODE_REGEX = /\\u[a-fA-F0-9]{4}|\\x[a-fA-F0-9]{2}/g```

and it has the `g` flag which makes this Regexp stateful. If you render the same string twice in a row, Lingui will not unescape this string a second time, because the `lastIndex` for that string will be after the Unicode symbol at that point.

And it seems like there is no reason to have the `g` flag here, since that Regexp is used only for `.test()` method which returns boolean, which means there is no need to count occurrences.

**To Reproduce**
Use StrictMode in React. Any string with unicode sequences like `<Trans>Hyphen\u00ADation</Trans>` is not parsed.

```jsx
import { StrictMode } from 'react';
import { Trans } from "@lingui/macro"

export default function App() {
   return (
     <StrictMode>
       <Trans>The unicode sequence in the word Hyphen\u00ADation is not parsed</Trans>
     </StrictMode>
   )
}
```

**Expected behavior**
`<Trans>Hyphen\u00ADation</Trans>` renders as "Hyphen­ation"

Current behavior:
`<Trans>Hyphen\u00ADation</Trans>` renders as "Hyphen\u00ADation"

**Additional context**

Tested in Linui v3.17.2, but the `g` flag in [that Regexp](https://github.com/lingui/js-lingui/blob/a68fa6093caae2500a01012d15dc4a9a05aeddd5/packages/core/src/interpolate.ts#L7) is still used in the main branch of https://github.com/lingui/js-lingui/.

**Comment by thekip** [comment]
Thanks for the report. This need to be tested in the upcoming v5 version. Despite this regexp is still there, there was changes to how messages are extracted (raw vs cooked value) and it seems this branch of code could be not used at all, but this should be proved.

**Comment by akimovnet** [comment]
@thekip Thank you, I also tested in `5.0.0-next.1`, and unfortunately the issue is still reproducible.

**Comment by thekip** [comment]
Would you be minded create a PR with the change and a test case covering this? I will happy to accept that.

**Comment by akimovnet** [comment]
Thanks, I created PR #2030. Could you please tell, will it be possible to deliver the fix to the Lingui versions 3.x, 4.x, and upcoming 5.x?

**Comment by timofei-iatsenko** [comment]
Definitely not possible for v3, but v4 and v5 is possible.
