### ISSUE TITLE
Don't report statistics for pseudo locale

### ISSUE THREAD

**Issue by alexturpin** [lingui/js-lingui#2093]
**Is your feature request related to a problem? Please describe.**
Irrelevant missing statistics output for the pseudo-locale
<img width="649" alt="image" src="https://github.com/user-attachments/assets/fb4b5d67-371c-4e9c-855b-d500aaa43495">

**Describe proposed solution**
Don't show statistics for the configured pseudo locale

**Comment by alexturpin** [comment]
Happy to send a PR for this if there is appetite / it makes sense to others

**Comment by timofei-iatsenko** [comment]
Happy to accept this
