### ISSUE TITLE
V5 plural RangeError: Incorrect locale information provided

### ISSUE THREAD

**Issue by francois-pasquier** [lingui/js-lingui#2095]
**Describe the bug**
lowercase plural use results in RangeError: Incorrect locale information provided

**To Reproduce**
- `git clone git@github.com:lingui/js-lingui.git`
- `git checkout next`
- `cd examples/nextjs-swc`

**Does not work**
```tsx
import { plural } from '@lingui/core/macro'

export default function Developers() {
  return (
    <div>
      {plural(4, {
        zero: 'Developers',
        one: 'Developer',
        other: 'Developers'
      })}
    </div>
  )
}

```

**Does work**
```tsx
import { Plural } from '@lingui/react/macro'

export default function Developers() {
  return (
    <div>
      <Plural value={4} one={'Developer'} other={`Developers`} />
    </div>
  )
}

```

**Expected behavior**
No error

**Additional context**
Plural component works out of the box, lowercase plural does not

- jsLingui version ``lingui --version`` **5.0.0-next.4**
- Macro support:
 - [x] I'm using SWC with `@lingui/swc-plugin`
- Nextjs@14.2.15

**Comment by timofei-iatsenko** [comment]
This is misusage, `plural` as you used will use a global version of i18n which is not setup in that example. You should use plural macro together with a local i18n instance. 

```jsx
import { plural } from '@lingui/core/macro'
import { useLingui } from '@lingui/react/macro'

export default function Developers() {
  const {t} = useLingui();
  return (
    <div>
      {t`Hello we have ${plural(4, {
        zero: '# Developers',
        one: '# Developer',
        other: '# Developers'
      })}`}
    </div>
  )
}
```

**Comment by francois-pasquier** [comment]
Thank you, it works indeed.

There is something broken when using it with arrow functions though.

```tsx
import { plural } from '@lingui/core/macro'
import { useLingui } from '@lingui/react/macro'

const Developers = () => {
  const { t } = useLingui()
  return (
    <div>
      {t`Hello we have ${plural(4, {
        zero: '# Developers',
        one: '# Developer',
        other: '# Developers'
      })}`}
    </div>
  )
}

export default Developers
```

This ends up with `Error: Incorrect locale information provided`

**Comment by timofei-iatsenko** [comment]
Confirming the bug, would be fixed by https://github.com/lingui/swc-plugin/pull/133
