### ISSUE TITLE
@lingui/metro-transformer depends on outdated versions of @lingui packages

### ISSUE THREAD

**Issue by monholm** [lingui/js-lingui#2096]
**Describe the bug**
The release/version workflow doesn't seem to update the workspace dependencies of @lingui/metro-transformer, meaning they are falling behind the current version. They are currently at `4.11.2`, causing multiple versions of lingui to be installed when using @lingui/metro-transformer. 

**To Reproduce**
Have a look at https://github.com/lingui/js-lingui/blob/main/packages/metro-transformer/package.json

**Expected behavior**
The version of the workspace dependencies should match the version of @lingui/metro-transformer itself.

**Comment by monholm** [comment]
@andrii-bodnar 🚀  🔥 

Is the underlying issue fixed as well, so that the versions doesn't drift again on the next release? :)

**Comment by andrii-bodnar** [comment]
@monholm, it shouldn't drift again :)

**Comment by monholm** [comment]
Awesome, thank you for the quick resolution :)

**Comment by andrii-bodnar** [comment]
@monholm, available in [v4.14.1](https://github.com/lingui/js-lingui/releases/tag/v4.14.1).
