### ISSUE TITLE
Vite 6 support

### ISSUE THREAD

**Issue by Athou** [lingui/js-lingui#2103]
**Is your feature request related to a problem? Please describe.**
Vite 6 is out. Would it be possible to add support for it in `@lingui/vite-plugin` please?

**Describe proposed solution**
Add Vite 6 to `peerDependencies` of `@lingui/vite-plugin` and see what happens.

```
  "peerDependencies": {
    "vite": "^3 || ^4 || ^5.0.9"
  },
```

**Describe alternatives you've considered**
Stay on Vite 5 for the moment.

**Additional context**
Failed renovate PR on my project caused by this: https://github.com/Athou/commafeed/pull/1613

Lingui is a joy to work with, keep up the good work!

**Comment by vonovak** [comment]
Hello and thanks for asking,
Did you try the proposed solution? If not, can you try it and report back?
Thank you 🙂
