### ISSUE TITLE
Support React 19

### ISSUE THREAD

**Issue by ptmkenny** [lingui/js-lingui#2109]
**Is your feature request related to a problem? Please describe.**
[React 19 has been released](https://react.dev/blog/2024/12/05/react-19), so it would be great for lingui to add support.  I've been using react19-rc1 for the past few weeks with lingui in my app and have experienced no problems; it may just be the peer dependency value that needs to be updated.

**Comment by andrii-bodnar** [comment]
Available in [5.1.0](https://github.com/lingui/js-lingui/releases/tag/v5.1.0)

**Comment by ptmkenny** [comment]
Thanks for the extremely fast response!
