### ISSUE TITLE
Upgrade @lingui/vite-plugin package on npm and yarn.

### ISSUE THREAD

**Issue by Illia-S-dev** [lingui/js-lingui#2110]
I would like to ask you update package @lingui/vite-plugin on npm and yarn.

Vite was updated to v6.0.3. I see here https://github.com/lingui/js-lingui/blob/main/packages/vite-plugin/package.json#L46 you have already added supporting of the latest version of vite. But the latest version of your package hasn't updated on npm and yarn.

**Comment by andrii-bodnar** [comment]
It has already been done in https://github.com/lingui/js-lingui/pull/2108, I plan to release a new version of Lingui (5.0.1) in a few hours today.

**Comment by Illia-S-dev** [comment]
Thank you so much. Just waiting.

**Comment by andrii-bodnar** [comment]
Available in [5.1.0](https://github.com/lingui/js-lingui/releases/tag/v5.1.0)
