### ISSUE TITLE
Error after adding @lingui/message-utils package in Yarn PNP.

### ISSUE THREAD

**Issue by nmoinvaz** [lingui/js-lingui#2119]
**Describe the bug**
After adding @lingui/message-utils, I get the following message when running `yarn run start`.

```
9:22:07 AM [vite] (client) error while updating dependencies:
Error: ENOENT: no such file or directory, open 'D:\x\.yarn\cache\@lingui-core-npm-5.0.0-adef44a735-ffaa4177cf.zip\node_modules\@lingui\core\dist\index.mjs'
```
I wonder if this is related to there not being an associated 5.1.0 package of @lingui/message-utils on NPM registry.

**To Reproduce**
After configuring Yarn with PNP, setup `package.json` to use the following:

```json
    "@lingui/core": "^5.1.0",
    "@lingui/message-utils": "^5.1.0",
    "@lingui/react": "^5.1.0",
```

Run `yarn run start`.

**Expected behavior**
No error.

**Additional context**

- jsLingui version 5.1.0
- Yarn PNP
- React 18
- Vite 6.0.2

P.S. sorry for the all reports.. and thanks for all your work on this great project!

**Comment by timofei-iatsenko** [comment]
I rechecked all dependencies in the packages, and it seems everything is correct on the lingui side. Please take a look on the incorrect peer dependencies warning during yarn install. Also you can try to `yarn dedupe` and investigate why `@lingui/core@5.0.0` is installed with `yarn why @lingui/core`

**Comment by nmoinvaz** [comment]
After deleting my `yarn.lock` and doing `yarn install` it seems to have fixed the problem. Thanks for suggesting it might be something like that.

**Comment by nmoinvaz** [comment]
Actually it came, back, but deleting my `.yarn` cache folder and running `yarn install` again fixed it. 🥹
