### ISSUE TITLE
`compile --strict` should not fail on missing pseudo translations

### ISSUE THREAD

**Issue by fdev** [lingui/js-lingui#2128]
**Describe the bug**
`lingui compile --strict` shouldn't fail with pseudo language missing translations.

**To Reproduce**
Having pseudo locale enabled in config `pseudoLocale: 'pseudo'` run `lingui compile --strict` to compile messages catalogs. The command will fail even when all translations are available because pseudo lang is taken into account when checking for missing translations.

**Expected behavior**
The `--strict` flag should compile succesfully when all translations are available even when I use pseudo locales for testing.

**Additional context**

This issue was previously reported in #584 and subsequently fixed in #586, unfortunately without an added test to prevent future reintroduction of this issue.

Using Lingui with NextJS 14.

```
@lingui/cli@4.11.2
@lingui/conf@4.11.2
@lingui/core@4.11.2
@lingui/loader@4.11.2
@lingui/macro@4.11.2
@lingui/react@4.14.1
@lingui/swc-plugin@4.0.8
```

**Comment by timofei-iatsenko** [comment]
Could you prepare a PR with test to fix this issue?
