### ISSUE TITLE
TypeScript type definitions

### ISSUE THREAD

**Issue by andraaspar** [lingui/js-lingui#213]
Looks like they don't exist...

**Comment by tricoder42** [comment]
Hi @andraaspar, this project uses [Flow](https://flow.org/). Feel free to send PR with Typescript type definitions, I have to clue how to create them.

**Comment by andraaspar** [comment]
Awesome! Thanks!

**Comment by tricoder42** [comment]
Thank you @huan086, this is really awesome! I've added [Typescript section](https://lingui.github.io/js-lingui/guides/typescript.html) to docs.
