### ISSUE TITLE
Encountered a declaration exception when running enzyme test with method mount

### ISSUE THREAD

**Issue by shye0000** [lingui/js-lingui#214]
Hi, in my react project, I'm trying to integrate unit tests by using jest and enzyme.

But with a component wrapped by "withI18n" in which I use `i18n.t` inside, I got an error when runing `mount` method in my test, here is the screenshot:
![image](https://user-images.githubusercontent.com/6414361/39293367-fb4ba994-4938-11e8-8a24-f09434cf4538.png)

Im really a new bee to unit test with react, is there anything wrong with my test? or should I do some extra configurations?

Thanks in advance.

**Comment by shye0000** [comment]
Hey I found a solution:
![image](https://user-images.githubusercontent.com/6414361/39296265-b99cc46c-4940-11e8-9567-cb9419e50187.png)

By wrapping the target component of the test in `I18nPorvider` resolve the error. Am I doing it in the right way?

**Comment by tricoder42** [comment]
@shye0000 Absolutely! Components using `i18n.t` or other i18n methods should be wrapped in `I18nProvider`. I'm gonna mention it in docs.

**Comment by tricoder42** [comment]
Docs added https://lingui.github.io/js-lingui/guides/testing.html, thanks!
