### ISSUE TITLE
Feature request : hash ids

### ISSUE THREAD

**Issue by nicolas-cherel** [lingui/js-lingui#223]
Since jslingui handles custom ids, is it possible that it could hash id of long translations and avoid long strings in source language id, to have a smaller payload ?

The main drawback would be that there is no way to have a sensible fallback on missing translations.

**Comment by tricoder42** [comment]
Hey @nicolas-cherel 👋 
Yes, this would be really nice! It was already suggested in #139. Please follow discussion there.

As I remember, it needs to be done in two steps: first, script goes through all files, collects messages and then releases production code with messages replaced with hash. I didn't have time to work on this though :/

**Comment by nicolas-cherel** [comment]
ho. sorry, I scanned the issue and missed that one. Thanks! For the impl, we're in sync, I'm pretty sure it would work like a charm. I'll read on the issue and try to see how to contribute.

**Comment by tricoder42** [comment]
No problem at all! I wish to spend some time on jsLingui over the weekend, so ping me if you need anything.
