### ISSUE TITLE
extract --clean

### ISSUE THREAD

**Issue by ccamusso** [lingui/js-lingui#234]
If I remove last 'Trans' component from a generic my component and run 'lingui extract --clean', the catalog  is not cleaned.

--clean option work only if if I leave at least one 'Trans' component inside my component.

I using "@lingui/cli": "^2.1.2"

**Comment by tricoder42** [comment]
@ccamusso Hey Carlo, good catch! I'm just refactoring CLI test suite so this was easy to find. Will be merged and released soon.
