### ISSUE TITLE
Missing npm packages

### ISSUE THREAD

**Issue by mi-g** [lingui/js-lingui#251]
To install js-lingui, [documentation](https://lingui.github.io/js-lingui/tutorials/react.html) specifies to install the following packages:
```
npm install -g @lingui/cli
npm install --save @lingui/react
npm install --save-dev @lingui/js.macro
npm install --save-dev @lingui/react.macro
npm install --save-dev babel-plugin-macros
```
However, both `@lingui/js.macro` and `@lingui/react.macro` are missing:
```
npm ERR! code E404
npm ERR! 404 Not Found: @lingui/js.macro@latest

npm ERR! code E404
npm ERR! 404 Not Found: @lingui/react.macro@latest
```

**Comment by tricoder42** [comment]
Sorry! I accidentally deployed docs for upcoming major release.

Docs are updated now, please refresh.

**Comment by mi-g** [comment]
I can indeed now follow the documentation to install lingui. Thanks.
