### ISSUE TITLE
@lingui/babel-preset-react missing in babel config

### ISSUE THREAD

**Issue by mi-g** [lingui/js-lingui#252]
On a very simple project, no translation is rendered and the browser console keeps telling me:
```
@lingui/babel-preset-react is probably missing in babel config, but you 
are using <Trans> component in a way which requires it.
```
and, as a probably related issue, `lingui extract` fails with:
```
SyntaxError: /home/mig/git/auth-server/src/Login.jsx: Unexpected token (8:3)
render() {
  return (
    <Trans>Login</Trans>
    ^
  )
```
`babel.rc`:
```
{
	"presets": [
		"env",
		"react",
		"@lingui/babel-preset-react"
	]
}
```
component file `Login.jsx`:
```
import React from "react";
import { Trans } from '@lingui/react';

export default class Login extends React.Component {
	render() {
		return (
			<Trans>Login</Trans>
		)
	}
}
```
app container `login-app.jsx`:
```
import React from 'react';
import ReactDOM from 'react-dom';
import { I18nProvider } from '@lingui/react'
import Login from './Login';

ReactDOM.render(
	<I18nProvider language="en">
		<Login />
	</I18nProvider>
, document.getElementById('root'));
```
`package.json`:
```
{
	"name": "auth-server",
	"version": "1.0.0",
	"scripts": {
		"build": "webpack --mode development --config webpack-config.js"
	},
	"dependencies": {
		"@lingui/react": "^2.3.0",
		"ejs": "^2.6.1",
		"express": "^4.16.3",
		"js-yaml": "^3.12.0",
		"react": "^16.4.1",
		"react-dom": "^16.4.1",
		"spdy": "^3.4.7"
	},
	"devDependencies": {
		"@lingui/babel-preset-react": "^2.3.0",
		"babel-core": "^6.26.3",
		"babel-loader": "^7.1.5",
		"babel-preset-env": "^1.7.0",
		"babel-preset-react": "^6.24.1",
		"clean-webpack-plugin": "^0.1.19",
		"html-webpack-plugin": "^3.2.0",
		"webpack": "^4.16.3",
		"webpack-cli": "^3.1.0"
	}
}
```
Do i miss something for the system to make use of `@lingui/babel-preset-react` ?

**Comment by tricoder42** [comment]
No, it seems you did everything right!

I've just created a [repository](https://github.com/tricoder42/js-lingui-issue-252) with the code from this ticket and I'm able to run `lingui extract` without any errors. I added you as a collaborator if you wan to add more files which are relevant.

**Comment by tricoder42** [comment]
I think it's because you have `babel.rc` instead of `.babelrc`. Please rename it and let me know if it helps!

Cheers

**Comment by tricoder42** [comment]
It's not supported filename either. It needs to be [.babelrc](https://babeljs.io/docs/en/babelrc) according to docs. I tried all variants (`babel.rc`, `.babel.rc`, `.babelrc`) and only the last one works. Other two throws and error you're mentioning.

**Comment by mi-g** [comment]
That was it ! Many thanks for your help.
