### ISSUE TITLE
Feature: i18nMark should accept default value

### ISSUE THREAD

**Issue by HamidAghdaee** [lingui/js-lingui#258]
I'm wondering why` i18nMark` doesn't accept a default value? why just an Id? I think it's use is similar to `defineMessages` of react-intl. 

Our use case is to create a json translations resource file from an object of key value pairs in source code.

Thanks.

**Comment by tricoder42** [comment]
Sounds reasonable. I'll think about the api, because I'm also planning to add optional `description` to `<Trans>` and `i18n.t`

Just to clarify: the message and default value must be string literal. It can't be a variable, for example this won't work:

```
const msgs = {
  msg: "Default message",
  msg2: "Another default message"
}

msgs.forEach(key => i18nMark(key, msgs[key]))
```

**Comment by HamidAghdaee** [comment]
Oh I see. That makes sense. So there's no way to do what you mentioned? turning something like this to translations:

```const msgs = {
  msg: "Default message",
  msg2: "Another default message"
}

msgs.forEach(key => i18nMark(key, msgs[key]))```

If so, I still think having `default value` added to i18nMark is useful, as is `description` by the way. But I don't think we would use it for our use case. We would probably just convert the translations JS object into json without using the extract command.

Thanks.

**Comment by tricoder42** [comment]
Not really. `lingui extract` is parsing static AST. It would have to execute the code to make this work.

What's your use case? You have a key value pairs, where key is message ID and value is default translation? From where this object comes from?

**Comment by tricoder42** [comment]
It seems like you have a "message catalog", which you would like to merge with other messages. If we could extract this object to separate file (JSON would be the best), then we might find a solution to merge it in message catalog... Still it would be very helpful to understand what are you trying to achieve. Thanks a lot!

**Comment by HamidAghdaee** [comment]
@tricoder42 you are correct.

The catalog you mentioned, for us is a catalog of 'common' translations. We want to maintain this as an object in javascript which can be type checked using TS. So that a consumer can be sure a key value pair exists for the common translation they're looking for. 

We of course also want to generate the translations json from this and feed it to jslingui context. 

which brings up a related issue:

As you know in my other issue I've opened, we ALSO want to have translations that are local to packages. What's the best way to _extend_ an instance of i18n? I would like the the root i18n instance to load the common catalog and then to have `<I18nProvider>`s under it in the react component tree which extend what's above them by adding local translations to it.

**Comment by tricoder42** [comment]
> The catalog you mentioned, for us is a catalog of 'common' translations. We want to maintain this as an object in javascript which can be type checked using TS. So that a consumer can be sure a key value pair exists for the common translation they're looking for.

Interesting! So you have sth like:

```js
const common = {
  yes: "Yes",
  no: "No"
}
```

... and then in your code, you're using `i18n._(common.yes)`, right? It's type-checked, so if you accidentally type `i18n._(common.yess)`, it will throw the error.

I don't have a solution for this now, but I'll think about it. The easiest way would be if the file had one default export of `key: default message` or list of keys. Then we could point `extract` command to load messages from this file.

> As you know in my other issue I've opened, we ALSO want to have translations that are local to packages. What's the best way to extend an instance of i18n? I would like the the root i18n instance to load the common catalog and then to have <I18nProvider>s under it in the react component tree which extend what's above them by adding local translations to it.

This is indeed related to namespaces #14. This feature should land soon, in next 3-4 weeks.

**Comment by HamidAghdaee** [comment]
@tricoder42 you got it. From my point of view I don't ever want a situation in which the developer has to maintain the integrity of both the source code and the message catalog. Either the message catalog is generated from the source code (which you've done a great job at) OR the source code can reference the catalog having a guarantee that the key value pair exists.

**Comment by tricoder42** [comment]
Hey @HamidAghdaee,
I'm working on proposal for new API which should support your use case. Could you please review [RFC](https://github.com/lingui/js-lingui/blob/next/docs/rfc/001_message_definitions.rst#messages-with-custom-ids) and tell me what you think?

In your case you could use `defineMessages`:

```jsx
import { defineMessages } from "@lingui/js.macro"

const common = defineMessages({
   yes: "Yes",
   no: "No"
}
```

**Comment by tricoder42** [comment]
@HamidAghdaee I opened #274 as a preview for comments. Your usecase is described [here](https://github.com/lingui/js-lingui/blob/09094d52dc322f6bd304ca01657bde905044f83e/docs/rfc/001_message_definitions.rst#common-catalogs)

In addition, catalogs created using `defineMessages` are type-checked by default. I'm curious what do you think. Thanks!

**Comment by FredyC** [comment]
Should the first example be more like this with backticks?

```js
import { t } from "@lingui/macro"

export const common = {
   yes: t('common.yes')`Yes`,
   no: t('common.no')`No`
}
```

**Comment by tricoder42** [comment]
@FredyC Yeah, you're right! Edited and fixed, thank you!
