### ISSUE TITLE
No need to load default language message catalog if it's extracted from source code...

### ISSUE THREAD

**Issue by HamidAghdaee** [lingui/js-lingui#259]
In the case where the message catalog is extracted totally from the source code, this json file serves no purpose at all for the default language, after all everything is in the source code itself. In order to bring down the amount of bites needed to be downloaded to the user, is it possible to not load the the default language's messages.js file? Currently this seems to throw an error.

**Comment by tricoder42** [comment]
You're right, but we still need the `messages.js` file even for source language. All messages which include any formatting (variables, plurals) are compiled to function during the build. So, the language file then actually looks like:

```js
modules.export = {
  "Hello {name}": function(a) { return ["Hello ", a("name")] }
}
```

This is actually done to reduce the size of bundle, so we don't include the message parser. Also, once we implement #139, the size will be even smaller.


You don't have to translate this file manually though! Just set [sourceLocale](https://lingui.github.io/js-lingui/ref/conf.html#sourcelocale) and this message catalog won't be checked for missing translations. MessageIDs are used as a last resort for missing translations anyway. You're still free to override these translations if you need to (In one past project we had an english text in source code, but message catalogs were edited in online service by translators and copywriters)

**Comment by tricoder42** [comment]
Closing this one. TLDR; Messages are compiled offline, so even for source language we must load compiled message catalogs.

**Comment by HamidAghdaee** [comment]
Interesting. I see what you're saying. But why is it that once I've included the messages.js file, then having code the references keys that are not in messages.js still works?

In other words:

1. I write some code.
2. I extract the files into messages.json
3. Load them via the webpack-loader.
4. Add another message in code: <Trans> my message </Trans>
5. Without extracting anything again, with the same old messages.js file, no error is thrown. The text 'my message' is displayed. This makes me think that the function being executed on translation doesn't need a key for every message in the code. 

So there may be a way to optimize here and not load even the keys for the source language?

Thanks.

**Comment by tricoder42** [comment]
1. In development, message parser is available and parses messages on the fly. This is for convenience so you don't have to run `lingui extract` after every string you add.
2. Static messages (without any variables) don't require parser. To extend my previous example, compiled message catalog would look like this:

```js
modules.export = {
  // static message
  "My Message": "My Message"

  // with variable
  "Hello {name}": function(a) { return ["Hello ", a("name")] }
}
```

Indeed, if your app would use only static messages, then we might omit loading message catalog for source language. However, we have to watch out for #139 once it gets implemented.

**Comment by HamidAghdaee** [comment]
@tricoder42 makes sense. Thanks for the explanation.
