### ISSUE TITLE
Fails to extract on Windows due to wrong path.sep used (2.4)

### ISSUE THREAD

**Issue by MartijnHols** [lingui/js-lingui#262]
**Describe the bug**
`lingui extract` returns `No locales defined!` when extracting messages on Windows. 

**To Reproduce**
Run `lingui extract` on a Windows machine in `cmd`.

**Additional context**
The issue is that `locale` returned by https://github.com/lingui/js-lingui/blob/0bb80a48d4afafb0aa8f40c3aa77743b0135aa60/packages/cli/src/api/catalog.js#L150 contains the entire path, not just the locale name. This is because `path.sep` is `\` while the result from `glob.sync` contains paths with forward slashes `/`. Replacing `path.sep` with `/` fixes this specific issue (but my extraction still fails because of a different error).

I would have made a PR if I didn't fear side-effects.

**Comment by tricoder42** [comment]
Hey @MartijnHols,
don't fear side-effects at all :) Feel free to follow [contributors guide](https://github.com/lingui/js-lingui/blob/master/CONTRIBUTING.md#contributing-the-code), the tests should back you up.

I tried to make this method platform compatible, but didn't realize `glob.sync` normalize slashes...

**Comment by tricoder42** [comment]
No worries, I'm going to release it with upcoming patch

**Comment by tricoder42** [comment]
Released in [v2.4.1](https://github.com/lingui/js-lingui/releases/tag/v2.4.1), thanks for reporting the issue!
