### ISSUE TITLE
Feature: include Polyfill language data in message catalog

### ISSUE THREAD

**Issue by tricoder42** [lingui/js-lingui#263]
- [ ] Add language data from [polyfill](https://github.com/andyearnshaw/Intl.js/) to message catalog so they're loaded automatically
- [ ] Allow exclude polyfill using `lingui compile --without-polyfill`

Related: #261

**Comment by JSteunou** [comment]
Since Intl has a [pretty good support](https://caniuse.com/#feat=internationalization) do you think it would be easier the other way ? without polyfill the default and `--with-polyfill` to add it.

It would also mitigate the breaking change.

**Comment by tricoder42** [comment]
In v3, polyfills are loaded manually.
