### ISSUE TITLE
setupI18n() versus i18n.init() or i18n.setup()

### ISSUE THREAD

**Issue by karlhp** [lingui/js-lingui#264]
I have a question regarding setupI18n().

setupI18n() returns an object which is then used respectively required in different modules for translations.

`let i18n =setupI18n({...})`

Since I use the returned i18n variable in different modules I have to create the setup in a separate module and then import it wherever required. So I am wondering why I can't just import i18n right away from @lingui/core and then call an init() method for the setup, for example:

`
import {i18n} from '@lingui/core';

i18n.init({...});

const msg = i18n._('Hello World');
`
Is there any advantage of having a separate setupI18n() function over an i18n.init() approach? I don't really care to create a separate module, just asking about the intention.

Thanks,

Karl

**Comment by tricoder42** [comment]
There still is `i18n` exported from `@lingui/core`, but it's deprecated in favor of `setupI18n`. I didn't want to export global variable. It's more flexible to export a factory (`setupI18n`) and let users to create instances by themselves. It also allows creating more than one i18n instances, e.g: when you need more than one language on the site at the same time.

What you're suggesting is a correct approach: Create a local file, e.g. `i18n.js`, when you setup your i18n instance and import it in your code where needed. It's explicit, you have full control over it and it doesn't use global var.

**Comment by karlhp** [comment]
@tricoder42, thanks, all clear!
