### ISSUE TITLE
Doc for catalogs options for js object is incorrect

### ISSUE THREAD

**Issue by dephiros** [lingui/js-lingui#269]
**Describe the bug**
For a project at work, it is not feasible at this point for us to load translation using ES6 import and for the moment, we have to load it with global js object. 
The doc gives an example of setup18n as follow:
```
import { setupI18n } from "@lingui/core"

const catalogs =  {
   en: {
      "Hello": "Hello",
      "Good bye": "Good bye"
   },
   cs: {
      "Hello": "Ahoj",
      "Good bye": "Nashledanou"
   }
}

const i18n = setupI18n({ catalogs })
```
The structure of catalogs should be:
```
const catalogs = {
  en: {
    messages: {...}
  }
}
```

**Expected behavior**
The doc should reflect the right structure of the expected object

**Comment by tricoder42** [comment]
Thanks! It just has been fixed and deployed 👍
