### ISSUE TITLE
The library make-plural has issues with CSP

### ISSUE THREAD

**Issue by akkie** [lingui/js-lingui#27]
The library `make-plural` uses a [new Function](https://github.com/eemeli/make-plural.js/blob/efa478629027e43c64c242ec61d4a793fe57de41/src/make-plural.js#L202) construct, which violates the script-src CSP rule.

Please see: https://developer.chrome.com/extensions/contentSecurityPolicy#relaxing-eval
> Evaluated JavaScript
The policy against eval() and its relatives like setTimeout(String), setInterval(String), and new Function(String) can be relaxed by adding 'unsafe-eval' to your policy:

> "content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"
**However, we strongly recommend against doing this. These functions are notorious XSS attack vectors.**

I've opened an issue upstream https://github.com/eemeli/make-plural.js/issues/10

**Comment by tricoder42** [comment]
Interesting, thanks!

I'll see if we can replace it with anything. After all, all plural rules are from CLDR repository and there's plenty of libs out there which parses CLDR data.

**Comment by tricoder42** [comment]
Probably this one, because soon I'll need more data from CLDR https://www.npmjs.com/package/cldr

**Comment by akkie** [comment]
It uses also the [new Function](https://github.com/papandreou/node-cldr/blob/4efcaa509141340c63c76dfc42e18c678b3c8195/lib/cldr.js#L833) construct. So I'm not sure if would also violate against the CSP rule.

**Comment by tricoder42** [comment]
Good point!

I need to focus on next major release coming in few days. I'll come back to this once the release is out.

Switching underlying lib won't break public API, so it can be done anytime. Although this one is a potencial security issue and should be resolved asap.

**Comment by tricoder42** [comment]
Thinking about it, this issue will be probably solved in next release.

`make-plural` will be used in browser only during development. For the production build, message catalogs are precompiled and plural rules are injected to them. I looked at one of these compiled message catalogs and there's no `new Function`, just generated plural function.

We could precompile all plural rules for development as well and remove `make-plural` completely.

**Comment by eemeli** [comment]
I replied to the upstream comment; unfortunately `new Function` is a rather core part of the make-plural compiler. But that should not stop you from being able to use the library here; the compilation really should not be a part of your runtime.

Had a quick look at how you're using make-plural atm and in the `compile-messages` branch. I'd recommend that you replace `loadLanguageData` with something like this, which should be idempotent with the [current code](https://github.com/lingui/js-lingui/blob/66b3d2/packages/lingui-i18n/src/dev/loadLanguageData.js):

```
import plurals from 'make-plural/es6/plurals'
export default (language: string) => plurals[language]
```

Apologies for not having the time to submit this as a proper PR.

**Comment by tricoder42** [comment]
@eemeli No worries, thank you for your response.

I've done something similar what you suggests only few minutes ago (https://github.com/lingui/js-lingui/commit/e3355a4df9c412219d90e8cd4d8b91a33dd4b8a9), but your version is much better! Thank you again ;)

Cheers!
