### ISSUE TITLE
CLI is silent when passed an unrecognized option

### ISSUE THREAD

**Issue by sedubois** [lingui/js-lingui#271]
**Describe the bug**
The `lingui` CLI is silent when it is passed an unrecognized option.

**To Reproduce**
`$ lingui foo`

**Expected behavior**
The CLI should display an error.

`lingui --version`: 2.4.1

**Comment by tricoder42** [comment]
Indeed, this is how `commander` works, but it should at least show a help. Here's description of issue and possible fix: https://github.com/tj/commander.js/issues/432#issuecomment-175815584

Interested in sending PR?

**Comment by sedubois** [comment]
I won't have time to send a PR but the issue is not critical so feel free to close, I just wanted to make it known.

**Comment by tricoder42** [comment]
Let’s leave it open as a known bug. Maybe someone will pick it up ;)

**Comment by dephiros** [comment]
@tricoder42 , it seems like something that I can contribute(trying to familiarize myself more with the project)
Will try to look into it and give a pull request soon!

**Comment by tricoder42** [comment]
Sounds interesting! It's a backend code so I don't mind extra dependency. Feel free to do it if you're interested 👍

**Comment by dephiros** [comment]
@tricoder42 , I am almost done with the pull request but stuck at a strange unit test failure: https://circleci.com/gh/lingui/js-lingui/2224?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
Could you help me take a look when you have a chance?
Thank you

**Comment by FredyC** [comment]
@dephiros I think you don't need to worry about that one, I've seen that failing before as well. There is something broken in general it seems. Just hold tight and @tricoder42 will surely merge it soon.
