### ISSUE TITLE
Documentation says to install Babel globally instead of locally

### ISSUE THREAD

**Issue by sedubois** [lingui/js-lingui#272]
The documentation stipulates to install babel globally, but the [Babel documentation](https://babeljs.io/docs/en/babel-cli.html) recommends against this.

I currently have issues with `babel-core` not found and I don't know if it's because of this. It would be good that the lingui docs instruct the same thing as the Babel docs, so that at least this question can be put aside as a potential source of confusion.

**Comment by sedubois** [comment]
Actually those are the docs for the Babel CLI. But I suppose the same is valid for Babel core. Otherwise my apologies for the noise...

**Comment by tricoder42** [comment]
This seems to be related to #273. It seems the packages shouldn't be installed globally.

**Comment by sedubois** [comment]
As shown in #273 I managed to run Gatsby and lingui with everything installed locally (including `@lingui/cli` and `@babel` packages. So yes, I think I would suggest to highlight this approach instead.

**Comment by tricoder42** [comment]
Ok, I'll close it in favor of #273
