### ISSUE TITLE
Lingui Extract fails with latest version of Babel

### ISSUE THREAD

**Issue by quentez** [lingui/js-lingui#275]
**Describe the bug**
Since updating to Babel `7.0.0-rc2`, `lingui extract` fails with the following error:

```
/node_modules/babel-types/lib/definitions/index.js:161
      throw new TypeError("Property " + key + " expected type of " + type + " but got " + getType(val));
      ^

TypeError: Property value expected type of string but got null
```

**To Reproduce**
Upgrade Babel to `7.0.0-rc2` in a TypeScript project.
Run `lingui extract`.

**Expected behavior**
No errors.

**Additional context**

- jsLingui version ``2.4.2``
- Babel version ``7.0.0-bridge.0``
- TypeScript project.

**Comment by tricoder42** [comment]
Thanks, I'll take a look. How the message in source looks like? Is it possible to isolate it?

**Comment by quentez** [comment]
My bad. This was a mistake on our end. I apologize for the false alarm.

**Comment by tricoder42** [comment]
No worries at all. I don't even count how many times I've found a solution right after asking a question :)

**Comment by quentez** [comment]
Haha, that for sure. We'll be more thorough next time.
Thanks again for the great project!!
