### ISSUE TITLE
Custom locale for development?

### ISSUE THREAD

**Issue by FredyC** [lingui/js-lingui#276]
**Is your feature request related to a problem? Please describe.**
Perhaps I am misunderstanding something here, but I would like to have a special locale that will be used as default/fallback and won't be 100% English correct, more like developer English. This default localization would then be used for translation to other languages and also to proper English where necessary.

Basically, what I want to avoid, is when I use incorrect English grammar in the code and somebody notices that it shouldn't be fixed in the code, but the same way as other translations are made.

**Describe the solution you'd like**
Currently when I try `lingui add-locale dev` it fails as unknown locale. I would like if this would be passing along with other commands.

**Describe alternatives you've considered**
Maybe it could be special option in configuration that would allow to specify "dev"

**Comment by tricoder42** [comment]
I guess you're working with custom IDs, right?

I'm using messages as IDs and from time to time I override message from source code:

```jsx
   <Trans>This message is in code</Trans>
```

```po
msgid  "This message is in code"
msgstr "This message is displayed on website"
```

In your project you might add locale `en-dev` (locale must be valid BCP47 and there're must be plurals defined for it). In next release this will gracefully default to `en`.

**Comment by FredyC** [comment]
I am not entirely sure what do you mean by `there're must be plurals defined for it`? I can add `en-dev` locale, that works, but you are saying it wont be working once I use plurals? In that case it's not much of a solution :)

What would be some other approach to this then? I assume I am not only developer who does not have a perfect English. It feels rather cumbersome if translator person can work with all languages, but when he need to change something in the English, he has to ask a developer?

**Comment by tricoder42** [comment]
Ah, sorry for confusion. Plurals must be defined for the language, not locale. Language is the first part before `-`. That's why `en-dev` works (it takes plurals for `en`), but `dev` doesn't (there're no plurals for `dev`).

Like I said, I'm "translating" also English dictionary, when I need to fix English copy. It's convenient also for translators that they have access to all languages. I'm not using custom IDs though.

**Comment by tricoder42** [comment]
Let me know if that works for you or reopen this issue otherwise
