### ISSUE TITLE
Cannot read property '_' of undefined

### ISSUE THREAD

**Issue by zuiidea** [lingui/js-lingui#277]
**Describe the bug**
I cloned the  [gatsby-starter-default@v2](https://github.com/gatsbyjs/gatsby-starter-default/tree/v2) and add `js-lingui` to my project.
It's  success when I running `lingui extract`, `gatsby develop `,

but when  running `npm run build` I get

```
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  15 |     <Trans>Now go build something great.</Trans>
  16 |   </p>
> 17 |   <Link to={i18n.t`/page-2`}>
     |             ^
  18 |     <Trans>Go to page 2</Trans>
  19 |   </Link>
  20 |   <div>


  WebpackError: TypeError: Cannot read property '_' of undefined

  - index.js:17 IndexPage
    lib/src/pages/index.js:17:13
```

**To Reproduce**
See [This repo](https://github.com/zuiidea/gatsby-v2-jslingui), `gatsby v2` +`lingui`.

**Expected behavior**
`npm run build` or `gatsby build` should succeed.

**Additional context**
```
lingui --version
2.4.2
```

```
$ npm list -g babel-core @babel/core
/usr/local/lib
└─┬ stylelint@9.2.0
  ├── @babel/core@7.0.0-beta.46  -> /usr/local/lib/node_modules/stylelint/node_modules/_@babel_core@7.0.0-beta.46@@babel/core
  └─┬ postcss-html@0.18.0
    └── @babel/core@7.0.0-beta.46
```

gatsby-node.js

```
exports.onCreateBabelConfig = props => {
  const { actions } = props
  ...
  actions.setBabelPreset({
    name: '@lingui/babel-preset-react',
  })
  ...
}

```

package.json

```
 ...
  "babel": {
    "presets": [
      "@babel/preset-react"
    ]
  },
  "lingui": {
    "fallbackLocale": "en",
    "sourceLocale": "en",
    "localeDir": "src/locales",
    "srcPathDirs": [
      "src"
    ],
    "format": "minimal"
  }
...
```

**Comment by tricoder42** [comment]
Hey @zuiidea,
I looked at [redux example](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-redux) in Gatsby and problem is, that for `gatsby build` you need to provide `gatsby-ssr.js` with the same wrapper element as `gatsby-browser.js`.

Another issue is to figure out how to determine active language from the page...

**Comment by zuiidea** [comment]
@tricoder42 Thank you for the detailed explanation and workaround!
