### ISSUE TITLE
Update catalogs after changing source message

### ISSUE THREAD

**Issue by niklaskorz** [lingui/js-lingui#281]
So first of all, I really enjoy the idea's behind js-lingui. A question that is left dangling in my head is what happens when I change the original message and it is used as the id, for example when there's a typo, grammar mistake or a missing word. I assume this results in the message not being translated until the translations and their ids are updated, as technically there's no translation for the id. Am I correct here or is there a smart detection that handles this case?

**Comment by tricoder42** [comment]
You're correct, right now there's no smart detection. Although good idea for improvement.

**Comment by niklaskorz** [comment]
Alright, thanks for the *very* quick answer! :)

**Comment by niklaskorz** [comment]
Feel free to close the issue unless you want to keep it as a feature request.

**Comment by tricoder42** [comment]
If you're worried about this issue, you could also use custom IDs, but I rarely find it problem.

**Comment by tricoder42** [comment]
I'll close it for now, but we'll probably open it later. It's the second time I hear about this feature.

**Comment by FredyC** [comment]
Yea, this is basically a reason why I was asking for custom locale (#276) so I don't need to worry about english in the code to be crap and let someone else to deal with it. I still need to check on ideas @tricoder42 put in there, but hopefully it will work out  :)
