### ISSUE TITLE
unmet peer dependency "babel-core@6.x || ^7.0.0-0"

### ISSUE THREAD

**Issue by sedubois** [lingui/js-lingui#286]
**Describe the bug**
My project uses `@lingui/cli` 2.5.0, but I get this when installing all packages with `yarn`: ` @lingui/cli@2.5.0" has unmet peer dependency "babel-core@6.x || ^7.0.0-0"`. However, AFAIK there is no such thing as `babel-core` with version `^7.0.0-0` (the package changed to `@babel/core`).

**Additional context**
- jsLingui version 2.5.0

**Comment by tricoder42** [comment]
Yes, there is, that's the latest version of `babel-core` which serves as a bridge between `babel-core` and `@babel/core`

See this [readme](https://github.com/babel/babel-bridge) where it is explained.

What babel version do you use? 6 or  7?

**Comment by tricoder42** [comment]
Hmm, anyway, this seems to be upstream issue: https://github.com/babel/babel-bridge/issues/5

We have to live with it for now.

**Comment by tricoder42** [comment]
It was fixed in upstream and fix in lingui will be released with next version
