### ISSUE TITLE
Suggestion: Merging files coming from translation process

### ISSUE THREAD

**Issue by FredyC** [lingui/js-lingui#292]
**Is your feature request related to a problem? Please describe.**
I've noticed that catalogs are ordered by id when extracting. However, localization tools are apparently doing it also (at least POEdit and Loco) and each has its own opinion on how to sort it :) This creates a rather awful mess when diffing.

**Describe the solution you'd like**
It's definitely a good thing to have deterministic output from the extraction process. One way might be to introduce CLI command for merging catalogs that came from a translator so it can be ordered the same way. 

**Describe alternatives you've considered**
There is already merging and ordering function exposed in API of cli package so it's certainly possible to handle this in userland when some 3rd party tool is used that changes order.

**Comment by FredyC** [comment]
Also, I just realized that sorting objects in JavaScript is not exactly bulletproof as there are no guarantees to have the same order on different machines. At least that's what documentation says. Personally, I have never encountered issues with that so it might not be that serious with current runtime environments.

**Comment by tricoder42** [comment]
What about this:
- new messages (not included in `prevCatalog`) are placed on the top of catalog
- previous messages, which aren't obsolete, are kept in the same order
- obsolete messages are placed at the end of catalog

I believe we should add another configuration. Right now messages are sorted alphabetically, but when you translate a page of static text, it handy to have it sorted by origin.

**Comment by tricoder42** [comment]
Another option, always run `lingui extract` after downloading messages from 3rd party service. Translations will be merged and order of messages will be consistent. I believe this should be default workflow no matter how we implement sorting.

**Comment by FredyC** [comment]
> Another option, always run lingui extract after downloading messages from 3rd party service. Translations will be merged and order of messages will be consistent. I believe this should be default workflow no matter how we implement sorting.

That doesn't feel right. I mean why would anyone want to **extract** when they want to _only merge_ translations? Source code would be probably unchanged in that moment. It would make much more sense to have a separate command for managing translations coming from 3rd party.

> What about this:
> 
>     new messages (not included in prevCatalog) are placed on the top of catalog
>     previous messages, which aren't obsolete, are kept in the same order
>     obsolete messages are placed at the end of catalog

Obsolete messages make sense to be at the end, but giving some priority to new messages inevitably means that next time those will be shifted down and created another sort of havoc when diffing changes.

**Comment by tricoder42** [comment]
The thing is we don't know how external service is going to sort messages. To avoid rewrites, we need to either stick to local sorting of remote one.

If we take CLI as the source of truth, you need to download messages and then run extract only to resort messages.

The other way round, if you intend to keep the sorting from remote service, always first extract and then download message catalogs. Even there're no changes, you're basically downloading order of messages.

Regarding placing new messages on the top: they won't be shifted now, because order of existing messages is preserved. They will be, however, pushed down after you download translations from external service, which is unfortunately inevitable.

**Comment by FredyC** [comment]
I don't have a problem using Lingui sorting mechanism, not at all. It's just I don't want to be running expensive extract process when the only thing that has changed is a translation, most likely for one language on top of that. If there would be an actual merging process that takes new catalog, merges it into a current catalog and then sorts the result, it would be working quite nicely I think.

> Regarding placing new messages on the top: they won't be shifted now, because order of existing messages is preserved. They will be, however, pushed down after you download translations from external service, which is unfortunately inevitable.

```
A new message
B new message
A old message
C old message
```

After another run, it would be like this or am I missing something? It would be causing unnecessary shifts in files. I would rather keep it like it is now with everything sorted A-Z. That way new messages will naturally appear somewhere in middle and old ones won't be touched.

```
A new message
A old message
B new message
C old message
```

**Comment by tricoder42** [comment]
Interesting food for thought. Let me get back to this after I finish work on new `localeDirs`.

Also, you're obviously right with the sorting of new messages 👍

**Comment by FredyC** [comment]
I guess I don't care about this that much anymore :)
