### ISSUE TITLE
@lingui/loader compatibility issue with webpack 4

### ISSUE THREAD

**Issue by chochihim** [lingui/js-lingui#297]
**Describe the bug**
Inline loader usage described in https://lingui.js.org/guides/dynamic-loading-catalogs.html#loading-of-message-catalogs does not work with webpack 4 as webpack now handles JSON file natively. Please refer to discussion and workaround in https://github.com/webpack/webpack/issues/6572

Maybe we need to update the doc?

**Comment by tricoder42** [comment]
Hey @chochihim, you're right. I noticed that while ago but didn't have time to update docs... Do you think that hack is stable enough to include it in loader? Or should be simply encourage using loader in webpack config? That isn't possible for create-react-app users...

**Comment by JSteunou** [comment]
not a big fan of black magic. Explicit import is good and let people add webpack rules by extensions / name / path if wanted.

**Comment by tricoder42** [comment]
> doc can be updated with chained loader `@lingui/loader!json-loader!./locale/messages.json`

Actually we need it other way round, sth like `@lingui/loader!js-loader`, but I don't think such loader exists... Anyway, it's fixed for now. I'll take a look at webpack if I can figure out how to add a public API as described here https://github.com/webpack/webpack/issues/7057#issuecomment-381883220

Thanks for reporting and additional info!

**Comment by tricoder42** [comment]
Released in [v2.6.0](https://github.com/lingui/js-lingui/releases/tag/v2.6.0)
