### ISSUE TITLE
Add JavaScript dateFormat & numberFormat function

### ISSUE THREAD

**Issue by JSteunou** [lingui/js-lingui#299]
**Is your feature request related to a problem? Please describe.**

For a usage outside of react, in javascript `i18n` contains `t, plural, select, selectOrdinal` but no `dateFormat` nor `numberFormat` helpers like react components.

Using `date` from core works, but it requires to create a function with current language before being able to use it. If you don't have the need for cached formatter this is tedious.

This is just sugar, but nice sugar :)

**Describe the solution you'd like**

```js
i18n.dateFormat('2018-08-29', {weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'})
```

**Describe alternatives you've considered**

```js
import {date} from '@lingui/core'

date(i18n.language, {weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'})('2018-08-29')
```

**Comment by tricoder42** [comment]
Sounds good! I don't know why it's not included already.

Interested in sending PR?

**Comment by JSteunou** [comment]
I would but I have very limited bandwidth so do not wait for me :(

**Comment by JSteunou** [comment]
:+1: :beer:

**Comment by JSteunou** [comment]
Thank you a ton @tricoder42 !
