### ISSUE TITLE
Localization in monolingual projects

### ISSUE THREAD

**Issue by tricoder42** [lingui/js-lingui#305]
**Is your feature request related to a problem? Please describe.**
I have a project which probably stays in English for very long time (target market US and Canada). I still need to localize several things:
- plurals - writing `{count === 1 ? <span>Singular</span> : <span>Plural</span>}` is ugly to say at least. In English it's not such a problem, but if the project were in Czech it would be bigger hassle.
- date/number formats

**Describe the solution you'd like**
Ideally, the API should be very similar to multi-language API, so it's easy to migrate the project to use full features internationalization when the time comes:

Setup i18n - load language data:

```jsx
import { makePlural, makeNumber } from "@lingui/react-lite"
// import language data that you need
import pluralRules from "@lingui/react-lite/en/plurals"
import numberFormats from "@lingui/react-lite/en/number"

const Plural = makePlural(pluralRules)
const NumberFormat = makeNumber(numberFormats)

export { Plural, NumberFormat }
```

Use it:

```jsx
import { Plural } from "./i18n"

<Plural value={count} one={<span>Singular</span>} other={<span>Plural</span>} />
```

Future compatibility - if we decide later in the future that we actually need to support multiple languages, it should be as easy as swapping imports (and providing Trans tags, which aren't needed in monolingual apps):

```jsx
// this is changed
import { Plural } from "@lingui/react"

// this should stay the same
<Plural value={count} one={<span>Singular</span>} other={<span>Plural</span>} />
```

**Describe alternatives you've considered**
I guess only viable alternative is writing it by hand: `{count === 1 ? <span>Singular</span> : <span>Plural</span>}`. Setting up the full i18n machinery only for a single language seems to be an overkill.

**This is more RFC than actual feature request. I feel it might help me a lot, but not sure if it should be released as a library. I just needed to get it out of my head to focus on real work 🙃**

**Comment by FredyC** [comment]
I don't understand the issue at hand. How is situation different if you have only a single language? You mean like you don't want to include I18nProvider and do an actual runtime localization? I don't see how is that a problem really. Is it worth introducing a different package and API just for that?

**Comment by tricoder42** [comment]
Yeah, I18n provider isn't necessary at this point, because it manages active language and catalogs. This is mostly about formatting messages (Plurals), numbers and dates.

The package is different, but the API should be the same. That's the only benefit over doing `{count === 1 ? <span>Singular</span> : <span>Plural</span>}` every time I need it. Also, this example is in English, in Czech it would be more complex and I would probably create a custom component/function anyway to handle 3 plural forms.

**Comment by ghostd** [comment]
Why not use Intl API for this? (maybe with polyfill since [Intl.PluralRules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/PluralRules#Browser_compatibility) is pretty new...)

**Comment by FredyC** [comment]
> Yeah, I18n provider isn't necessary at this point, because it manages active language and catalogs. This is mostly about formatting messages (Plurals), numbers and dates.

I can understand that, but is it really worth it to have a different code with the same API just to save some _performance_ by not using Provider? Personally, I would rather use final approach even if there wouldn't be any localization happening so I don't need to revisit it later and change it "real thing".

**Comment by tricoder42** [comment]
Full internationalization adds extra step to development and build (extracting, compiling). It might not be necessary if you're 95% sure the project won't be translated. That's what I want to avoid.

The other difference is: `Plural` from `@lingui/react` is basically a macro, transformed into `Trans` component at build step. `Plural` from `@lingui/react-lite` would be real component with runtime rendering. So, the API looks similar, but in monolingual app it's simple 

`Component => value => plural form => message`,

while in internationalized app it's 

`Component => generate message => extract => compile => value => pluralForm => message`

I'm just trying to lower barrier as much as possible. Otherwise most project will stick to good old: `You have 42 message(s)` format :)

@ghostd Intl API would definitely be used for Number/Date formatting. I didn't know about PluralRules, I'm going to check it out.

**Comment by ghostd** [comment]
@tricoder42 out of topic: maybe we could use Intl.PluralRules to replace the makePlurales function embedded into the catalogs.

**Comment by FredyC** [comment]
Ok, I understand now, it makes sense, haven't considered extraction/compilation would be needed as well.

What about pluralizing props and other strings out of react tree? Will there be like `@lingui/core-lite` package too ? :) Seems like overkill kinda, but some people not using React might want this featue too.

**Comment by tricoder42** [comment]
@ghostd Honestly, I don't trust Intl.PluralRules that much. Pluralization function is a very tiny function, extracted from the CLDR definition. Replacing it with Intl.PluralRules seems like very small optimization with lot of potential problems. But as I said, I've just learned it exists :) I have to take a look at it first.

@FredyC Yeah, I was thinking about it too. After all, React components are just wrappers around core functions... I'm still not convinced about the name of packages though

**Comment by FredyC** [comment]
Is it actually necessary to have a separate package? I mean current `@lingui/react` has no `Plural` or `NumberFormat` export. Without Babel touching it, they can be executed as regular components as you have described above. This would make it even easier later when you want to start translating, you will just add the plugin and done.

The Trans component is a bit more complicated as it already has an implementation, but basically, it should fallback to the text in the code without any Babel transformation right?

Am I missing something here? I mean the Babel does the magic and as long as it works without it, there is no need for extra packages.

**Comment by tricoder42** [comment]
You're right. Especially NumberFormat and DateFormat components works the same way.

You don't need Trans component in monolingual app, so that shouldn't be a problem. Otherwise, Trans component would simply return children.
