### ISSUE TITLE
Support Babel 7

### ISSUE THREAD

**Issue by alesn** [lingui/js-lingui#307]
The 'final' Babel 7.0.0 has been released (Babel 7 is out of beta stage). Lingui CLI & Babel plugins don't work with Babel 7. (babel-bridge, which was used as temporary solution until Babel 7 'final' is released, pulls in Babel 6 dependencies and breaks babel plugins, which depend on Babel 7)
Lingui CLI & Babel plugins @ version 2.0.8, which used to work with Babel 7 betas don't work with the final Babel 7.0.0 either, so we need to get proper support for Babel 7 without babel-bridge so that projects on Babel 7 can use lingui

**Comment by tricoder42** [comment]
Hey @alesn, do you know if there's a recommended way to support both versions of Babel?

**Comment by alesn** [comment]
Unfortunately, I don't know. From the bit of research I did, it seems this would be something that is quite specific to the actual case of a particular library / package. From experience what other packages did - they released a new version branch that works strictly only with the new version - Babel 7. Babel 6 remains supported only on their previous releases' version branch (which depending on the size / popularity of the package may still get some updates back-ported from the main version running on Babel 7)

**Comment by tricoder42** [comment]
> babel-bridge, which was used as temporary solution until Babel 7 'final' is released, pulls in Babel 6 dependencies and breaks babel plugins, which depend on Babel 7

This is weird. babel-bridge (babel-core@7.0.0-bridge.0) doesn't have any babel 6 [dependencies](https://github.com/babel/babel-bridge/blob/master/package.json).

Are you sure it's babel-bridge which pulls babel core in?

**Comment by tricoder42** [comment]
I've just updated [webpack-react-babel-7](https://github.com/lingui/js-lingui/tree/master/examples/webpack-react-babel-7) from RC to stable Babel 7.

If I run `lingui` globally, I get an error because some other global package probably uses Babel 6. 

However, when I run **local lingui** from `./node_modules/.bin/lingui`, it works as expected.

Feel free to reopen with more info if you still have problems with Babel 7.

**Comment by alesn** [comment]
Sorry, it was a different 'babel-bridge' npm package. Installing specifically babel-core@7.0.0-bridge.0 works

**Comment by FredyC** [comment]
Um, why is bridge still needed with Babel 7 released? Is that going to be like that till you drop support for v6 completely? Quite frankly it's giving me a headache. 

With the bridge in place, things are rather broken with Storybook or [CRA using typescript](https://github.com/wmonk/create-react-app-typescript/issues/382). Once I remove the bridge, everything works as smoothly as before. I've browsed through several issues now and there is so much moving parts it's impossible to figure a solution that would work in all scenarios :(

**Comment by tricoder42** [comment]
I agree that Babel 7 should be default, but I would like to support Babel 6 for some time. Not sure how long. We should definitely figure out a better way to support both versions.

**Comment by FredyC** [comment]
It's a good thing that Lingui@3 can introduce various breaking changes and support Babel 7 only :) Just kidding, but it's worth considering imo. I can understand that you would want Babel 6 users to get hands-on macros sweetness. In an ideal world, you would be able to maintain V3 along with V4 which would ditch Babel 6 completely.
