### ISSUE TITLE
React - Using <Trans> with object properties

### ISSUE THREAD

**Issue by Peping** [lingui/js-lingui#31]
I haven't had much luck doing
```es6
const component = (props) => {<Trans>Hello {props.user}</Trans>);
```
it always renders `Hello undefined`. However if I change it to 
```es6
const component = ({user}) => (<Trans>Hello {user}</Trans>);
```
I get `Hello Foo`, which is the output I expected in the first case. Is this a bug that's easy to fix? I'll be happy to PR if you point me in the right direction.

**Comment by tricoder42** [comment]
This isn't bug, it's known [limitation](https://lingui.gitbooks.io/js/content/ref/react.html#variables-inside-components) (Link to new docs, but it's also mentioned in [old one](https://github.com/lingui/js-lingui/wiki/Ref:-React#variables-inside-components))

However, this should at least raise an error or warning in console.

**Comment by Peping** [comment]
Now that you mention it I do remember seeing it in the docs. I'll look into what I can do to make this happen.

**Comment by tricoder42** [comment]
I think we could support object properties:

Before:
`<Trans>Hello {props.user}</Trans>`

After:
`<Trans id="Hello {props_user}" values={{ props_user: props.user }} />`

We could also convert constants: 

Before:
`<Trans>Hello {props.user}</Trans` 

After:
`<Trans id="Hello {0}" values={{"0": 42}} />`

I don't know if we should support anything else (like function calls). What do you think?

**Comment by tricoder42** [comment]
It's this line: https://github.com/lingui/js-lingui/blob/next/packages/babel-plugin-lingui-transform-react/src/index.js#L224

All we need is calculate name, instead of `exp.name`.

If you want to explore AST tree, great tool for it is [astexplorer.net](https://astexplorer.net/#/gist/a144c515a90d0ed102d2e3983d8137bd/0a23e59ef456d5357d0a41f28360dbfd8d98c40d)

**Comment by Peping** [comment]
I think it's technically possible and definitely useful in some situations. The only problem I see is with generating parameter keys. 

`<Trans>You rolled {Math.floor(Math.random() * 6 + 1)}</Trans>`
turns into
<Trans id="You rolled {???}" values={{"???": Math.floor(Math.random() * 6 + 1)}} />

The first time I used parametrized messages in Lingui it felt so much like React that I forgot there was a babel layer taking the whole contents of my `<Trans>` and parsing it. It's just so natural™ to do everything you're used to in your run-off-the-mill React component. 

The main question in my mind is what do we do with `???`.

**Comment by tricoder42** [comment]
We could treat it as *positional argument* instead of *named argument*.

`<Trans id="You rolled {0}" values={{"0": Math.floor(Math.random() * 6 + 1)}} />`

**Comment by Peping** [comment]
That's probably a good idea for constants and complex expressions. For simple expressions like `name` or `object.name` we could do named arguments.

**Comment by tricoder42** [comment]
Originally, I wanted to keep messages as clean as possible, so I would rather do:

```jsx
const value = Math.floor(Math.random() * 6 + 1)
<Trans>You rolled {value}</Trans>
```

rather than

```jsx
<Trans>You rolled {Math.floor(Math.random() * 6 + 1)}</Trans>
```

but that's just my taste :)

However, argument name is useful also for translator who gets a small hint what the argument might be. 🤔

**Comment by tricoder42** [comment]
I agree to use *positional arguments* for constants and complex expressions, while *named arguments* for variables and object properties.

What about `messages[0].title`? :) Go for `messages_0_title`? Then we can go deeper: `messages[props.featured].title`, which would be like `messages_props_featured_title` and that's probably over the line :/

**Comment by tricoder42** [comment]
I tried to generate name from expression, and it works:

```js
      // src/index.js
      import generate from 'babel-generate'

      ...
 
      // line 236
      if (t.isIdentifier(exp) || t.isMemberExpression(exp)) {
        const name = generate(exp).code  // generate JS from AST
        const key = t.isIdentifier(exp) ? exp : t.stringLiteral(name)
        nextProps.text += `{${name}}`
        nextProps.values[name] = t.objectProperty(key, exp)
```

```jsx
<Trans>Hello {props.name}</Trans>
// becomes
<Trans id="Hello {props.name}" values={{ "props.name": props.name }} />
```

It could literally works with *any* expression (the if condition just need to match other cases like `CallExpressions`, etc)

However, I don't think it's a good idea in general case. Ideally, all *static* values could be used as named arguments (variables, object properties, array indexes), while *dynamic* values (function calls) should be used as positional arguments. The reason is that we don't know if function is pure:

```js
<Trans>1st roll {random()}, 2nd roll {random()}</Trans>

// This won't work! random() in translation is called only once
<Trans id="1st roll {random()}, 2nd roll {random()}" values={{ "random()": random() }} />

// Now it works
<Trans id="1st roll {0}, 2nd roll {0}" values={{ "0": random(), "1": random() }} />
```

Problem is with object properties. ES6 introduces getters and they might have potentially side effects:

```js
const props = {
  get random() {
    return Math.random()
  }
}

<Trans>1st roll {props.random}, 2nd roll {props.random}</Trans>
// and we're screwed again, props.random getter is called only once
<Trans id="1st roll {props.random}, 2nd roll {props.random}" values={{ "props.random": props.random }} />
```

It's probably safer to use positional arguments everywhere except for simple identifiers. It has predictable behavior in all cases and if user wants to have variable name in translation, they'll know how to achieve it.

@Peping What do you think?

**Comment by Peping** [comment]
Agreed. I'm right there with you.  Stick with named arguments for simple identifiers, positional arguments for any other expression.

**Comment by tricoder42** [comment]
Fixed in `next` branch, I'll release it with upcoming major release:

```js
<Trans>
  Property {props.name},
  function {random()},
  array {array[index]},
  constant {42},
  object {new Date()}
  everything {props.messages[index].value()}
</Trans>;
```

```js
<Trans id="Property {0}, function {1}, array {2}, constant {3}, object {4} everything {5}" values={{
  0: props.name,
  1: random(),
  2: array[index],
  3: 42,
  4: new Date(),
  5: props.messages[index].value()
}} />;
```

Thanks for suggestions! 👍
