### ISSUE TITLE
Can't pluralize in Polish

### ISSUE THREAD

**Issue by sedubois** [lingui/js-lingui#316]
**Describe the bug**
I didn't manage to get Polish pluralization working although it works in English and French, am I missing some configuration?

<img width="323" alt="screen shot 2018-09-09 at 13 05 30" src="https://user-images.githubusercontent.com/4217871/45263380-0f6d0400-b431-11e8-9fe9-71ca8c0f6afa.png">

<img width="329" alt="screen shot 2018-09-09 at 13 05 03" src="https://user-images.githubusercontent.com/4217871/45263376-ffedbb00-b430-11e8-90f1-32af16f4985a.png">

**To Reproduce**
See https://github.com/sedubois/lingui-and-styledjsx-debug

- jsLingui version 2.6.1
- Babel version 6.26.3

**Comment by tricoder42** [comment]
You have a wrong placeholder in translation:

```diff
- "{value, plural, one {# article} other {# articles}}": "{0, plural, one {# artykuł} few {# artykuły} other {# artykułów}}"
+ "{value, plural, one {# article} other {# articles}}": "{value, plural, one {# artykuł} few {# artykuły} other {# artykułów}}"
```

**Comment by sedubois** [comment]
Wonderful, this works, even for 22, 23, 24... 🎉 `"{value, plural, one {# artykuł} few {# artykuły} many {# artykułów}}"`

<img width="324" alt="screen shot 2018-09-09 at 13 27 34" src="https://user-images.githubusercontent.com/4217871/45263576-23663500-b434-11e8-959c-a4c908831487.png">

https://github.com/sedubois/lingui-and-styledjsx-debug/tree/27baeb698b21442d44ab1bdf506de27ff54e5d20

**Comment by tricoder42** [comment]
Good point, `other` plural form is used only for decimal numbers: http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#pl
