### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by HamidAghdaee** [lingui/js-lingui#317]
**Describe the bug**
We noticed this error being reported in our production bundle in great frequency with js-lingui. Unfortunately we haven't been able to reproduce it locally but I have isolated it to the presence of a component using js-lingui translations. 

**To Reproduce**
We are using very basic and minimal js-lingui configuration. 
The one thing I can think of is: we're nesting an I18nProvider in another. Like this:

This is to provide local i18n context at a more granular level. 
```
 <I18nProvider language={language} catalogs={catalogs} >
        //...somewhere deeper, in another component
        <I18nProvider language={language} catalogs={catalogs}>
           <Trans>foo</Trans>
        </I18nProvider>
 </I18nProvider>
```
**Expected behavior**
No exception thrown.

**Additional context**

- jsLingui version ``lingui --version``: 2.6.1
- Babel version ``npm list babel-core`` 7.0.0-bridge.0
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.):

```
// THERE ARE 4 DIFFERENT BABEL_ENV OPTIONS:
// =======================================
// 1. BABEL_ENV=browser - standard environement targeting browsers*, preserves ES modules
// 2. BABEL_ENV=node - targeting latest stable node.js, for jest testing which runs in node
// 3. BABEL_ENV=build-lib - same as "browser" but compiles ES modules into commonjs
// 4. BABEL_ENV=build-es - same as "browser" but doesn't rename imports to target src
//
// *last 2 versions of browsers + IE11

const {
  PREFIXES,
  PROD_BROWESRS,
  DEV_BROWSERS
} = require('./constants.stratus.js');

module.exports = function(api) {
  const babelEnv = api.env();

  // basic global presets
  const presets = ['@babel/preset-react', '@babel/preset-typescript'];
  // basic global plugins
  const plugins = [
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-object-rest-spread',
    '@babel/plugin-syntax-dynamic-import'
  ];

  const browsers =
    process.env.NODE_ENV === 'production' ? PROD_BROWESRS : DEV_BROWSERS;
  // environment preset for browsers

  const browserPresetEnv = (compileModules = false) => [
    '@babel/preset-env',
    {
      targets: {
        browsers
      },
      modules: compileModules ? 'commonjs' : false
    }
  ];
  // environment preset for node
  const nodePresetEnv = [
    '@babel/preset-env',
    {
      targets: {
        node: 'current'
      }
    }
  ];

  if (babelEnv === 'browser' || babelEnv === 'build-es') {
    presets.push(browserPresetEnv());
  }
  if (babelEnv === 'node') {
    presets.push(nodePresetEnv);
    plugins.push('babel-plugin-dynamic-import-node');
  }
  if (babelEnv === 'build-lib') {
    presets.push(browserPresetEnv(true));
  }
  // when NOT building&publishing packages, let's turn
  // import { Button } from @cloudlare/component-button
  // to
  // import { Button } from @cloudlare/component-button/src/index
  // for seamless developer experience
  if (babelEnv === 'browser' || babelEnv === 'node') {
    plugins.push(
      [
        'transform-rename-import',
        {
          original: `(@cloudflare/(${PREFIXES.join('-|')}-)(?!.*src/index).*$)`,
          replacement: '$1/src/index'
        }
      ],
      [
        'transform-react-fela-display-name',
        {
          reactFelaPackageRegEx: '(@cloudflare/style-container|react-fela)',
          functionNameRegEx:
            '(createComponent(WithProxy|Styles)?|applyTheme|withRenderer|applyStaticStyles|createStyledComponent)$'
        }
      ]
    );
  }

  presets.push('@lingui/babel-preset-react');

  return { presets, plugins };
};
```

**Comment by FredyC** [comment]
Would be useful if you can create a repo with small reproduction, ideally with source maps enabled and coupled with the code. Bugs like this are probably impossible to figure out just like that.

**Comment by HamidAghdaee** [comment]
@FredyC I hear ya. I'd love to do that. Unfortunately I haven't been able to reproduce it yet. I do know that in vast majority of cases it happens on chrome browsers on windows machines in the context of components using https://github.com/Pomax/react-onclickoutside

**Comment by FredyC** [comment]
I cannot imagine how Lingui would be even remotely relevant to using react-onclickoutside. During runtime, the Lingui does a very little job. It certainly is not touching any DOM nodes so it's a most likely issue somewhere else.

**Comment by tricoder42** [comment]
@HamidAghdaee What kind of messages do you use inside react-onclickoutside? Trans component with inline elements?

**Comment by kv9991** [comment]
This bug is still happens. In logs I can see users that have this error (~0.25%)
One time I saw this error by myself and I took a screenshot

<img width="429" alt="Screenshot 2020-10-08 at 19 17 09" src="https://user-images.githubusercontent.com/16166451/95485877-f978f700-099a-11eb-84a7-9b28d46e4094.png">

I'm using:
"@lingui/cli": "2.9.2",
"@lingui/core": "2.9.2",
"@lingui/macro": "2.9.2",
"@lingui/react": "2.9.2",
"@lingui/babel-preset-react": "2.9.2",

Usually I do `import { Trans } from "@lingui/macro"` or `import { t } from "@lingui/macro"`
This exact error was created by `Trans` component

**Comment by FredyC** [comment]
@kv9991 I don't think anyone here has the capacity to fix the problem in V2 given it's even a problem to finish V3 😅 So unless you can reproduce it with V3, then you can essentially forget about it or fix it yourself.

Sorry if I sound harsh, just stating how it is.

**Comment by tricoder42** [comment]
As stated above, please create a repository or codesadbox with an example. There's been lot of changes in v3, also please try that. Reopen if the problem persists

**Comment by snih** [comment]
@kv9991 maybe [this info](https://github.com/lingui/js-lingui/issues/1079) will be helpul for you
