### ISSUE TITLE
babel-plugin-lingui-extract-messages doesn't work when targeting IE 11

### ISSUE THREAD

**Issue by akkie** [lingui/js-lingui#32]
If I add the browser `ie 11` to my [babel-preset-env](https://github.com/babel/babel-preset-env) config, then I get some errors if I try to build my application:

```
[info] Module build failed: TypeError: ...: Cannot read property 'reduce' of undefined
[info]     at collectMessage (...\node_modules\babel-plugin-lingui-extract-messages\lib\index.js:24:27)
```

I'm not sure if this has to do with js-lingui or if it's an issue from another component.

**Comment by tricoder42** [comment]
Thank you for bug report!

Unfortunately, I'm not able to replicate it. There's major release coming in next few days, could you please try it?

```sh
npm install --save lingui-react@next
npm install --save-dev babel-preset-lingui-react@next
npm install --global lingui-cli@next
```

And then run: `lingui extract`

`babel-plugin-lingui-extract-messages` is no longer part of `babel-preset-lingui-react`. It's add manually by CLI when running `lingui extract` (the reason is performance - messages shouldn't be extracted on every babel build).

Moreover, `babel-plugin-lingui-extract-messages` warns about edge cases which would case the bug you've just described.

**Comment by akkie** [comment]
OK. Will test it if the new version is released.

> the reason is performance - messages shouldn't be extracted on every babel build

Could it not test if the catalog is up-to-date based on a timestamp cached for every catalog. So that  the catalog gets automatically built if something has changed?

**Comment by tricoder42** [comment]
That could work, but still you need a catalog only when extracting messages for translators, not for development. Also, having babel plugin added in `lingui extract` has another advantage, that it works also for projects which can't edit the babel config.

**Comment by tricoder42** [comment]
@akkie I've just published new major version, could you please try if the bug is still there.

There're few backward incompatible changes covered in [Migration guide](https://lingui.gitbooks.io/js/content/guides/migration-1.html). Most of changes are low-level api, only few affects [react](https://lingui.gitbooks.io/js/content/guides/migration-1.html#react-api)

**Comment by tricoder42** [comment]
I've just tried following `.babelrc` config:

```json
{
  "presets": [
    [
        "env", 
        {
            "targets": {
                "browsers": ["ie 11"]
            }
        }
    ],
    "react",
    "lingui-react"
  ]
}
```

in [tutorial repository](https://github.com/lingui/tutorial-lingui-react/tree/master/recommended), but I still get no error.

Closing now, feel free to reopen when you have more info.

**Comment by akkie** [comment]
I try to migrate to 1.0.1, but for me it's not really clear how a catalog should look like. Previously we had message files in the form:
```
{
  "key": "value"
}
```

But now we have a catalog in the form:
```
type Catalog = {
  messages: Messages,
  languageData: {
    // required in production
    plurals: Function
  }
}
```

Does this mean that the files are now structured like this:
```
{
  "messages": {
    "key": "value"
  }
}
```

If yes, then [this](https://lingui.gitbooks.io/js/tutorials/react.html) part of the documentation is outdated.

**Comment by tricoder42** [comment]
Yes, good catch, sorry for mistake.

It should be:

```js
<I18nProvider language="en" catalogs={{ en: { messages } }} development={dev}>
```

(just wrap messages in dictionary)

However, it's better to load compiled message catalogs during development, so it works exactly as in production:

```js
import catalog from 'locale/en/messages.js'

const App = () => (
  <I18nProvider language="en" catalogs={{ en: catalog }} development={dev}>
    ...
  </I18nProvider>
)
```

You can compile catalog with `lingui compile`. (I guess we could add webpack loader to handle compilation automatically.)

**Comment by tricoder42** [comment]
Tutorial fixed in https://github.com/lingui/js-lingui/pull/36

**Comment by akkie** [comment]
It's a bit confusing sometimes you use:

```
import catalog from 'locale/en/messages.js'
```

and sometimes:

```
import messages from 'locale/cs/messages.json'
```

**Comment by tricoder42** [comment]
I went through docs and it's consistent now.

Recommended way is `import catalog from 'locale/en/messages.js`. 

The other way is supported for backward compatibility and when you can't/don't want to compile messages. I should probably remove it from docs completely, so it's less confusing.

**Comment by akkie** [comment]
Yes, I think it's better to remove it or to explain the difference between the two file formats.

JSON: Source file from which the catalog will be built
JS: Compiled message catalog

Anyway, I cannot get the lib to work. Is it normal that the compiled format has the form:
```
{
  l: {},
  m: {}
}
```
?

**Comment by tricoder42** [comment]
My apologies! I was fixing every little detail before the major release and I forgot to document the most important part: `unpackCatalog` from `lingui-i18n`

The message catalog is "minified"  and need to be unpacked before loaded:

```js
import { unpackCatalog } from 'lingui-i18n'
import catalog from 'locale/cs/messages.js'

const App = () => (
  <I18nProvider language="cs" catalogs={{ cs: unpackCatalog(catalog) }} development={dev}>
    <Inbox />
  </I18nProvider>
)
```

I've updated [tutorial](https://lingui.gitbooks.io/js/tutorials/react.html#loading-translated-messages) in https://github.com/lingui/js-lingui/pull/37

Also, take a look at example how to load messages with [webpack](https://lingui.gitbooks.io/js/guides/webpack-dynamic-loading.html). It looks way cleaner.

**Comment by akkie** [comment]
Thanks :+1: 

> Also, take a look at example how to load messages with webpack. It looks way cleaner.

Yea, I use this in a similar manner.


If I compile my German messages file, then the compiled catalog contains only the English variant.

My source file contains as example:
```
{
  "This field is required": "Dies ist ein Pflichtfeld",
}
```

The compiled catalog contains then:
```
{
  "This field is required": "This field is required",
}
```

It seems that it uses the key also as value.

**Comment by tricoder42** [comment]
I see. I was able to replicate this error by using old-style message catalog. Format of message catalog have changed as stated in migration guide (https://lingui.gitbooks.io/js/content/guides/migration-1.html#cli). 

All you need is run `lingui extract`. It will merge translations from previous catalog (even if it's in old format) and generate a new one.

Finally, `lingui compile` should work as expected.

After running `lingui extract`, the message catalog should look like this:

```json
{
  "msg.heading": {
    "translation": "Ukázková aplikace",
    "defaults": "Application Example",
    "origin": [
      [
        "test/fixtures/App.js",
        5
      ]
    ]
  },
  "Example of <0>react-trans</0> usage.": {
    "translation": "Příklad použití <0>react-trans</0>.",
    "origin": [
      [
        "test/fixtures/App.js",
        7
      ]
    ]
  },
  ...
}
```

**Comment by akkie** [comment]
Sorry, I should better double check the documentation :wink: 

Can it be the case that `lingui extract` doesn't work with flow?

```
SyntaxError: .../src/apis/I18nAPI.js: Unexpected token, expected , (15:29)
  13 |    * @returns The message catalog for the given language.
  14 |    */
> 15 |   async fetchCatalog(language: string): Promise<Object> {
     |                              ^
  16 |     const catalog = await import(
  17 |       /* webpackMode: "lazy", webpackChunkName: "i18n-[index]" */
  18 |       `locale/${language}/messages.js`);
```

**Comment by tricoder42** [comment]
I'm using flow as well without any issues. `lingui-cli` only extends your `.babelrc` config, but I guess you use `react` plugin, which adds support for flow syntax.

Is `fetchCatalog` class method? Standalone functions must have `function` keyword after `async`:

```js
async function fetchCatalog (language: string) {
   ...
}
```

without `function`, I'm getting the same error:

```
SyntaxError: /Users/tricoder/Projects/lingui/lingui-web/src/lingui/locale/ui/I18nLoader/I18nLoader.js: Unexpected token, expected => (9:13)
   7 | import { selector } from 'lingui/locale'
   8 |
>  9 | async fetchx (language: string) {
```

**Comment by akkie** [comment]
> Is fetchCatalog class method? Standalone functions must have function keyword after async:

Yes, it's a class method.

> but I guess you use react plugin, which adds support for flow syntax.

I use [neutrino.js](https://neutrino.js.org/) which does all the magic.

Any idea for a workaround?

**Comment by tricoder42** [comment]
Isolate `I18nApi` component, so it doesn't have any translations in it and then ignore it using [`srcPathIgnorePatterns`](https://lingui.gitbooks.io/js/content/ref/cli.html#srcpathignorepatterns-array) config:

```json
{
  "lingui": {
    "srcPathIgnorePatterns": [
      "/node_modules/",
      "I18nApi.js$"
    ]
}
```

Please update to latest lingui-cli@**1.0.3**. I fixed pattern matching so it excludes also files, not only directories.

Does it work for you as a temporary workaround? I don't have any translations inside `I18nLoader` component, it only takes care of loading translations.

**Comment by akkie** [comment]
I use flow also in react components, so your proposal won't work. I've created a `i18n` env in babel which adds the necessary presets and plugins.

```
"env": {
"i18n": {
  "plugins": [
    "transform-class-properties",
    "transform-es2015-classes",
    "transform-object-rest-spread",
    "syntax-dynamic-import"
  ],
  "presets": ["react"]
  }
}
```

Then I can execute `cross-env BABEL_ENV=i18n lingui extract`.

I'll ask in the [Neutrino.js Slack Channel](https://neutrino-slack.herokuapp.com/) if there is a way to execute third party commands with the generated babel configuration.

**Comment by akkie** [comment]
@tricoder42 Is it intended that the `origin` entry in the `messages.json` points multiple times to the same line in the same file?

An example:
```json
{
  "Dashboard": {
    "translation": "Dashboard",
    "origin": [
      [
        "src\\components\\MainMenu\\MainMenu.jsx",
        86
      ],
      [
        "src\\components\\MainMenu\\MainMenu.jsx",
        86
      ],
      [
        "src\\components\\MainMenu\\MainMenu.jsx",
        86
      ],
      [
        "src\\components\\MainMenu\\MainMenu.jsx",
        86
      ],
      [
        "src\\components\\MainMenu\\MainMenu.jsx",
        86
      ]
    ]
  },
...
}
```

**Comment by tricoder42** [comment]
No, that's definitely bug.

**Comment by tricoder42** [comment]
Fixed in https://github.com/lingui/js-lingui/pull/39, lingui-cli@**1.0.4**
