### ISSUE TITLE
Using nested objects in format attribute

### ISSUE THREAD

**Issue by madebyherzblut** [lingui/js-lingui#320]
**Describe the bug**

The React components (`NumberFormat`, `DateFormat`) allow to pass strings, object literals and variables as `format` but no `MemberExpression` like `someGlobalConfig.format`. This may be useful for global locale definitions and the like. 

```
SyntaxError: Format can be either string for buil-in formats, variable or object for custom defined formats.
```

I think the solution is to add `t.isMemberExpression(expr)` to the [transformer.js](https://github.com/lingui/js-lingui/blob/master/packages/babel-plugin-transform-react/src/transformer.js#L225-L241) but I am not familiar enough with the code to make the fix work.

**To Reproduce**
```js
// Example
import { NumberFormat } from "@lingui/react"

const someConfig = { format: { digit: 4 } }

export default function App() {
   return <NumberFormat value="1" format={someConfig.format} />
}
```

```js
// packages/babel-plugin-transform-react/test/index.js
expect(
  transformCode(
    "<Trans><NumberFormat value={value} format={config.nestedKey.format} /></Trans>"
  )
).not.toThrow();
```

**Additional context**
- jsLingui version ``2.6.1``
- Babel version ``6.25.0``

**Comment by tricoder42** [comment]
Hey @madebyherzblut,
good point!

I think we could make it even more general at allow any expression: function call, member expression, array indexing, whatever:

```jsx
// This works:
<Trans><NumberFormat value={value} format="percent" /></Trans>
// ↓ ↓ ↓ ↓ ↓ ↓
// <Trans id="{value, number, percent}" />

// This works as well:
<Trans><NumberFormat value={value} format={{ numDigits: 2 }} /></Trans>
// ↓ ↓ ↓ ↓ ↓ ↓
// <Trans id="{value, number, format_0}" formats={{ format_0: { numDigits: 2 } }} />

// This is new:
<Trans><NumberFormat value={value} format={config.nestedKey.format} /></Trans>
// ↓ ↓ ↓ ↓ ↓ ↓
// <Trans id="{value, number, format_0}" formats={{ format_0: config.nestedKey.format }} />
```

Expressions inside messages are handled in the same way:

https://github.com/lingui/js-lingui/blob/401569f7dae5d3f3f88931fbf8f7da0bf25b5944/packages/macro/test/fixtures/t/actual.js#L9-L15

↓ ↓ ↓ ↓ ↓ ↓

https://github.com/lingui/js-lingui/blob/401569f7dae5d3f3f88931fbf8f7da0bf25b5944/packages/macro/test/fixtures/t/expected.js#L19-L29

**Comment by tricoder42** [comment]
Closed, since the `NumberFormat` and `DateFormat` are no longer macros.
