### ISSUE TITLE
Allow nested JSON messages

### ISSUE THREAD

**Issue by charliedavison** [lingui/js-lingui#322]
**Is your feature request related to a problem? Please describe.**
Allow nested JSON as messages

**Describe the solution you'd like**
As far as I can tell, the --minimal format flag only accepts a flat structure.

My current translation files are in the format:

```
{
    "SystemArea1": {
         "Label_1": "Hello world"
    }
    "SystemArea2": {
        "Label_1": "Another message"
     }
}
````

**Describe alternatives you've considered**
I've had to flatten them to work with Lingui. This works but causes unnecessary bloat in the translation file.

I may have missed something but can't see a way of doing this at the moment.

**Comment by tricoder42** [comment]
Hi @charliedavison,
no, this is not supported at the moment.

If you're interested, feel free to write another file format, e.g: `json-nested`. I believe this should be pretty easy. Take a look at existing formats here https://github.com/lingui/js-lingui/tree/master/packages/cli/src/api/formats

Just a note: Compiled catalog is always a flat json. There's an planned improvement to minify message IDs #139 though.

**Comment by charliedavison** [comment]
Thanks for the clarification.

I may well take a look at this one then and submit a PR.
