### ISSUE TITLE
Getting TypeError when using `i18n.t` in constructor

### ISSUE THREAD

**Issue by kirillku** [lingui/js-lingui#323]
**Describe the bug**
After updating to the latest version started to get `TypeError: i18n.t is not a function` in production mode (in development mode everything works fine). Looks like when `i18n.t` is used in constructor method, it didn't transpilled to the correct format by the babel plugin.

**To Reproduce**

```
import { withI18n } from "@lingui/react"

class Example extends React.Component {
  // this gives error in production
  constructor(props) {
    super(props)
    this.state = { text: props.i18n.t`Text` }
  }

  // this way also don't work
  state = { text: this.props.i18n.t`Text` }

  render() { ... }
}

export default withI18n()(Example)
```

- jsLingui version ``lingui --version``: `2.7.0`
- Babel version ``npm list babel-core``: `babel-core@7.0.0-bridge.0`
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.):
```json
{
  "presets": [
    "@babel/preset-react",
    "@babel/preset-flow",
    "@babel/preset-env",
    "@lingui/babel-preset-react"
  ],
  "plugins": [
    "styled-components",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-syntax-dynamic-import"
  ]
}
```

**Comment by tricoder42** [comment]
Hey @kirillku,
this is limitation of plugin. You need to use standalone `i18n` identifier, not member expression:

```js
// This will work
i18n.t`Message`

// This won't work
props.i18n.t`Message`

// Neither this
this.props.i18n.t`Message`
```

**Comment by kirillku** [comment]
Hey @tricoder42 ,
Thanks for a quick answer, I didn't know that. But did it only to simplify the example. It's used like this in the code:
```javascript
constructor(props) {
  super(props)
  const { i18n } = props

  this.state = {
    priorityOptions: [
      { key: 'normal', value: false, text: i18n.t`Normal` },
      { key: 'high', value: true, text: i18n.t`High` }
    ]
  }
}
```

**Comment by tricoder42** [comment]
Hmm, interesting. Could you please try to remove babel preset and replace it with plugins in front of other plugins?

```diff
{
  "presets": [
    "@babel/preset-react",
    "@babel/preset-flow",
    "@babel/preset-env",
-    "@lingui/babel-preset-react"
  ],
  "plugins": [
+   "@lingui/babel-plugin-transform-js",
+   "@lingui/babel-plugin-transform-react",
    "styled-components",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-syntax-dynamic-import"
  ]
}
```

**Comment by kirillku** [comment]
Tried this way, still the same error

**Comment by tricoder42** [comment]
Could you please create a repo with minimal example? That speeds up debugging a lot. Thanks 👍

**Comment by kirillku** [comment]
Was not able to reproduce on new repo, so closing the issue
