### ISSUE TITLE
Unknown option "pseudoLocale" was found

### ISSUE THREAD

**Issue by MartinCerny-awin** [lingui/js-lingui#329]
Add pseudoLocale into the valid option values.

```
Validation Warning:

  Unknown option "pseudoLocale" with value "ps-locale" was found.
  This is probably a typing mistake. Fixing it will remove this message.

See https://lingui.github.io/js-lingui/ref/conf.html for a list of valid options
Added locale en.
```

**Comment by tricoder42** [comment]
What version of CLI do you have? The option seems to be there:

https://github.com/lingui/js-lingui/blob/v2.7.0/packages/conf/src/index.js#L32

**Comment by MartinCerny-awin** [comment]
Yes, u are right I was using old CLI. I was originally using CLI in the project and then I switched to the global one, which was outdated.
