### ISSUE TITLE
Make @lingui/cli run against a specific directory

### ISSUE THREAD

**Issue by mschipperheyn** [lingui/js-lingui#330]
**Is your feature request related to a problem? Please describe.**
I have a project with lots of server side code and scripts. Running `lingui extract` against the project directory creates errors because it cannot process all scripts correctly. Also, I want the `locale` directory to be placed in a specific directory, not the root 

**Describe the solution you'd like**
I would like to be able to run `lingui extract` with the following customization options:
- directories to process for lingui language keys, could be multiple 
- directory where the `locale` directory will be placed (`--output`)

**Describe alternatives you've considered**
I considered running `lingui extract` in a target directory, but when you want to process multiple sub directories against the root, that doesn't work

**Additional context**

**Comment by sedubois** [comment]
Have you seen this?

https://lingui.js.org/ref/conf.html#srcpathdirs
https://lingui.js.org/ref/conf.html#localedir

**Comment by mschipperheyn** [comment]
RTFM, right. Sorry, thanks
