### ISSUE TITLE
Improve quickstart documentation

### ISSUE THREAD

**Issue by tricoder42** [lingui/js-lingui#331]
Here're my notes from [Building X with JavaScript series](https://www.youtube.com/watch?v=Q3qcL8GGQsA)

- add quickstart guide - tutorial is too verbose and README doesn't say much. In fact, do we have any positive feedback for the React tutorial? I'm thinkng about rewriting it from scratch, but I would like to figure out how to merge/simplify tutorials for various environments, if it's possible.

- [29:36](https://youtu.be/Q3qcL8GGQsA?t=29m36s) - this part breaks my heart 💔. The reason why he copies `id` and `values` might be either because he's speedcoding or simply because he expects such API from working with react-intl. I think we should a) add docs how to use Lingui without macros/plugins b) make it more clear in docs what's macro and how it looks under the hood or remove it from tutorial completely

- prefer local installation of `@lingui/cli`, related #273 

- ~mention peer dependencies in tutorial (cross-link to `@lingui/cli` reference)~ It's actually there, as the 3rd and last step of installation

- write all imports in code examples

- `other` plural form shouldn't be considered as a default one. In fact, it shouldn't be the only required form, because some languages (Polish, Russian) use `other` plural form for decimal numbers, while `one`, `few`, `many` for integers

- [1:15:02](https://youtu.be/Q3qcL8GGQsA?t=1h15m2s) add note how to figure out plural rules for target language.

## Other nice-to-haves:

- add warnings about missing plural forms in development
- upgrade to Babel 7, which should be the default version and provide steps how to use the lib with babel 6.

**Comment by yamalight** [comment]
Aside from a few issues with next.js / babel compat - the experience was actually pretty good. If I wasn't trying to read / code as fast, I'd probably have way less issues 😄 So, awesome work 👍 

Few notes from my side on the issue itself:
1. Very short (ideally - one pager) getting started that shows off as many features as possible would be amazing!
2. While you do have info about @lingui/cli peer deps in the docs for the @lingui/cli itself - in the react tutorial I was going through there's no mention of it.
3. Would be neat to show that other languages might have different pluralization forms right in your docs - kinda like you did with multiple lang translations in react tutorial. This would clear up _a lot_ (at least for me) 🤔

**Comment by FredyC** [comment]
Yea, it's probably not a good idea to show "transpiled" code that styled same as input code. Sometimes I am going through examples only as well and don't bother reading the sauce :)

Ultimately, I think it might be a good idea to have some live demo of working localized app, ideally, some split view that shows app on one side and an actual code on another side.

I am even thinking it could be interesting to provide own fork of react-scripts for CRA which would include all necessary setup of Babel and stuff. It would be great for a quick start and a user can do a proper setup later when he gets hang of it without throwing away any code. It's a bit problematic for TypeScript though because there are a `react-scripts-ts` and these cannot be mixed together obviously. Another approach is to utilize `react-app-rewired` and create a rewire module with the setup. This one can be universal and used in a long term.

**Comment by yamalight** [comment]
I've already asked on twitter, but gonna ask here as well - feel free to kill this message if it's a bit too offtopic 😃 

Why did you opted for using babel-macros _with_ react components instead of pure react components that wouldn't require additional babel setup? 🤔

**Comment by tricoder42** [comment]
You can use it, actually. It's documented very poorly though. In [reference documentation](https://lingui.js.org/ref/react.html#trans) there's one paragraph with examples:

```jsx
<Trans id="Hello World" />;

<Trans
  id="Hello {name}"
  values={{ name: 'Arthur' }}
/>;

// number of tag corresponds to index in `components` prop
<Trans
  id="Read <0>Description</0> below."
  components={[<Link to="/docs" />]}
/>;

<Trans
  id="Today is {today, date, short_date}"
  values={{ today: new Date() }}
  formats={{
    short_date: {
      year: "numeric",
      month: "long",
      day: "numeric"
    }
  }}
/>;
```

Basically, when you only use `Trans` component and you don't use `children` of `Trans` component, then you don't need macros or plugins. You still need plugins for extraction, but if you decide to skip that too and write everything manually, it's your choice... Just should probably consider another i18n at that point, because you'll miss most of LinguiJS features :)

---

Basically, I didn't want to spend ages writing messages in ICU message format. I did it in one project using react-intl and a) once I started using plurals, it was easy to make a mistake and b) I was very limited in how can I use components inside messages.

I just wanted to write:

```jsx
<Trans>
      See all <Link to="/unread">unread messages</Link>{" or "}
      <a onClick={markAsRead}>mark them</a> as read.
</Trans>
```

and let the library generate this code for me:

```jsx
<Trans 
  id="See all <0>unread messages</0> or <1>mark them</1> as read." 
  components={[<Link to="/unread" />, <a onClick={markAsRead} />]}
/>
```

and this message for translator:

```
See all <0>unread messages</0> or <1>mark them</1> as read.
```

I like how the code stays clean and readable, it's easy to navigate and I'm not limited at all what I'm using inside translated messages. Also, it's super easy to add translations to existing projects. Just add `Trans` tag everywhere. This freedom simply justifies the "hassle" of adding one plugin. Moreover, `macros` is becoming very popular plugin (create-react-app 2.0 will have it) so soon it won't be a problem at all.

There're other benefits that I didn't foresaw at the beginning, like that I can extract/compile messages and remove message parser from runtime bundle. I have few more ideas how to reduce the size of compiled message catalog and how to add required polyfills/formats in more automated way, we just need some time to get there.

**Comment by yamalight** [comment]
Oooh, I see. That definitely should be documented better. I'd even argue that should be a default in tutorial and the macros stuff should be in "advanced" version of tutorial 🤔

**Comment by tricoder42** [comment]
Well, that's just sad 😄 

For me, writing:

```
<Trans 
  id="See all <0>unread messages</0> or <1>mark them</1> as read." 
  components={[<Link to="/unread" />, <a onClick={markAsRead} />]}
/>
```

is just more advanced than:

```
<Trans>
      See all <Link to="/unread">unread messages</Link>{" or "}
      <a onClick={markAsRead}>mark them</a> as read.
</Trans>
```

...because I need to learn the API and I need to learn the message format.

On the other hand, if I use macros, I don't have to learn anything (except plurals mayb), because I already know JSX.

Imagine if the `macros` plugin and CLI worked out of the box and you didn't spend an hour to set it up? I would rather focus on making the installation and user onboarding right, than recommending more complex variation.

As I said, creat-react-app will soon have macros bundled, next.js have [official example](https://github.com/zeit/next.js/tree/canary/examples/with-babel-macros) using macros, so once other frameworks will catch up, it'll be much easier to beginners. Also the annoying babel 6/7 situation is making things a bit harder :/

**Comment by yamalight** [comment]
While the syntax might be familiar to the user - I'd say anything that requires any additional config is "advanced" and anything that "just works" (tm) is basic.
But maybe that's just my perception 🤔

**Comment by tricoder42** [comment]
No, I agree with that too. That's my intention with the whole library - get internationalization with minimum effort. Unfortunately, right now the "just works" approach simply doesn't work in all cases for several reasons, but I hope that soon we'll get to the point that it'll be as easy as using JSX. Nobody thinks about writing `React.createElement('div', props, children)` nowadays and it's considered as an advanced usage.
