### ISSUE TITLE
Rendering with id and default value

### ISSUE THREAD

**Issue by tkvw** [lingui/js-lingui#337]
In my staging environment I want to wrap my translations with a span, so the translator can hover the text to see which translation key needs to be used. 
I've checked the `defaultRender` and `render` methods and this could do the trick, but I need access to the message id and the default message, this is not passed through. 

My suggestion would be to pass it through when a `Component` is used in the render methods, ie: 
``` ({id,default,translation}) => translation```
Any thoughts?

**Comment by tricoder42** [comment]
Hey @tkvw,
I've just added it here https://github.com/lingui/js-lingui/pull/336/files#diff-a816132abb19e775c5baceb11630f839R76, but I'm planning it release it with v3.

If you're in a hury, feel free to send a PR. It's a quick fix here https://github.com/lingui/js-lingui/blob/master/packages/react/src/Render.js#L36 and I could release it on Monday/Tuesday.

**Comment by tkvw** [comment]
Wow, that was quick :+1: :smile: I'll check it out, thanks!

**Comment by tricoder42** [comment]
I had exactly the same usecase in my mind yesterday when I was refactoring `Trans` component. This could work as an in-context editor. You would have a expandable sidebar with a list of all messages on the page. Then we just need a local server which will communicate with sidebar and we can even edit/save messages from the website 👌

**Comment by tkvw** [comment]
I cloned master, but the tests are failing on my `ubuntu 18.04` machine, is this to be expected? It's probably some locale issue, but inconvenient. 

Example error: 
```
  ● NumberFormat › should render using the first recognized locale

    expect(received).toEqual(expected)

    Expected value to equal:
      "42.000,00 €"
    Received:
      "€ 42,000.00"

      135 |       languageContext("en", ["unknown-locale", "de-DE"])
      136 |     ).find("Render")
    > 137 |     expect(node.text()).toEqual("42.000,00 €")
          |                         ^
      138 |   })
      139 |
      140 |   it("should render translation inside custom component", function() {

      at Object.<anonymous> (packages/react/src/DateFormat.test.js:137:25)
```

**Comment by tricoder42** [comment]
You might be using Node without `--full-icu` (see https://github.com/lingui/js-lingui/blob/master/CONTRIBUTING.md#setup-local-environment). Unfortunately I don't know how this works in Ubuntu. Feel free to create a PR and let CI do the work.

Maybe try to set `NODE_ICU_DATA=./node_modules/full-icu` if it helps

**Comment by tricoder42** [comment]
@bjrn If you want to backport it to v2, please send a PR. It should be easy fix by adding `id` prop here https://github.com/lingui/js-lingui/blob/master/packages/react/src/Render.js#L36. Thanks!

**Comment by tricoder42** [comment]
I'm closing it in favor of `next` branch and upcoming v3 release. Feel free to send a PR if you want to backport it to v2.
