### ISSUE TITLE
Write a tutorial using LinguiJS with React

### ISSUE THREAD

**Issue by tricoder42** [lingui/js-lingui#350]
This is a [HactoberFest](https://hacktoberfest.digitalocean.com/) issue! Read the [contest details](https://hacktoberfest.digitalocean.com/details) for more info.

## Before you begin

- Confirm that you're working on this issue so I can add [👩‍💻assigned](https://github.com/lingui/js-lingui/issues?q=is%3Aopen+is%3Aissue+label%3A%F0%9F%91%A9%E2%80%8D%F0%9F%92%BBassigned) label.
- Use `next` branch as a base for your PR. This feature should be released in upcoming [v3](https://github.com/lingui/js-lingui/issues/334).
- Read the [contribution guide](https://github.com/lingui/js-lingui/blob/master/CONTRIBUTING.md) for info how to setup project, run tests and use development version of packages
- Join us on [gitter](https://gitter.im/lingui/js-lingui) to get support

## Starting point

- Use the [existing tutorial](https://lingui.js.org/tutorials/react.html) to learn about LinguiJS
- Use [create-react-app](https://github.com/facebook/create-react-app) to bootstrap example project. You should use create-react-app v2.
- Install `@lingui/react` and add `@lingui/cli @lingui/macro` as development dependencies

## Content

- You might use [existing tutorial](https://lingui.js.org/tutorials/react.html) as a starting point but feel free to provide your own example.
- **(optional)** The challenge is that existing tutorial is written for LinguiJS v2, but the new tutorial should be for v3. If you feel ambitious, checkout [migration guide](https://lingui.js.org/next/releases/migration-3.html) for the list of changes. Otherwise, feel free to write the tutorial for LinguiJS v2 and I'll rewrite examples afterwards. No big deal at all!
- **(optional)** Don't worry about formatting! The documentation uses [reStructuredText](http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html). It's very similar to Markdown. If you find it confusing, focus on content and I'll fix the markup once it's finished.
- The tutorial should cover following topics:
  - Installation
  - Project setup (`i18n` manager, `I18nProvider`)
  - `Trans` component for messages, including how to use variables and inline tags
  - Translation of props using `i18n` manager (accessed through `I18n` render prop component or `withI18n` hoc)
  - Pluralization using `Plural`
  - Date/Number formatting using `DateFormat` and `NumberFormat`
  - Working with CLI (adding locales, extracting, compiling)
  - Loading catalogs into app (either directly or using `@lingui/loader` webpack loader)

## Additional requirements

It might be beneficial if you have some experience with `react-intl` or any internationalization library. I believe for the best result you shouldn't be too much familiar with `LinguiJS`. The tutorial should be for the first time users and for that reason it's hard for me to write it.

This is a very long task, so it might take several hours to finish it. Feel free to reach me at [gitter](https://gitter.im/lingui/js-lingui) anytime.

**Comment by t04glovern** [comment]
I'm keen to give this one a shot! I haven't used LinguiJS and figure this might be a good opportunity to learn.

**Comment by tricoder42** [comment]
I've just realized that writing the tutorial for v3 might be much easier that I thought. There's already an [example project](https://github.com/lingui/js-lingui/tree/next/examples/react/src). It doesn't use create-react-app, but all new features from upcoming v3. All examples are basically in the main [App.js](https://github.com/lingui/js-lingui/blob/next/examples/react/src/App.js) file. The v3 prerelease is already published on NPM under `next` tag (`npm install @lingui/cli@next`, etc). Might be worth taking a look, because v3 fixes a lot of issues with CRA.

**Comment by t04glovern** [comment]
Cheers, I'll check it out! Is there a time-box on the task before it's likely to be re-assigned? I don't intend to take long, but would be good to also not rush it :) If I do run into any roadblocks, I'll be sure to make sure the task is re-assigned

**Comment by khaoptimist97** [comment]
@tricoder42 Thank you for this awesome library. I have a question regarding Actived Language. How do I get the current language being actived in my app?

**Comment by ShaneMckenna23** [comment]
I can work on this issue over the weekend. I spent this week implementing react-intl into an application at work so its fresh in my mind!

**Comment by tricoder42** [comment]
@ShaneMckenna23 Thanks, that would be great!

@t04glovern No worries, thank you for the effort anyway 👍 

@khaoptimist97 You can access `i18n.language`. `i18n` object you can get either using `withI18n` HOC or [`I18n`](https://lingui.js.org/ref/react.html#component-I18n) render-prop component.

**Comment by stereobooster** [comment]
<details>
  <summary>`I18nLoader` for v3</summary>

```js
import React from "react";
import { I18nProvider } from "@lingui/react";
import { setupI18n } from "@lingui/core";

const i18n = setupI18n();

export class I18nLoader extends React.Component {
  state = {
    catalogs: {},
  }

  loadCatalog = async (language) => {
    const catalog = await import(
      /* webpackMode: "lazy", webpackChunkName: "i18n-[index]" */
      `@lingui/loader!locale/${language}/messages.json`)

    this.setState(state => ({
      catalogs: {
        ...state.catalogs,
        [language]: catalog
      }
    }))
  }

  componentDidMount() {
    this.loadCatalog(this.props.language)
  }

  shouldComponentUpdate(nextProps, nextState) {
    const { language } = nextProps
    const { catalogs } = nextState

    if (language !== this.props.language && !catalogs[language]) {
      this.loadCatalog(language)
      return false
    }

    return true
  }

  render () {
    const { children, language } = this.props
    const { catalogs } = this.state

    // Skip rendering when catalog isn't loaded.
    if (!catalogs[language]) return
    
    i18n.loadAll(catalogs);
    i18n.activate(language);
    return <I18nProvider i18n={i18n}>{children}</I18nProvider>;
  }
}

```

</details>

**Comment by stereobooster** [comment]
Done https://github.com/stereobooster/react-lingui-example
