### ISSUE TITLE
Typescript type definitions for @lingui/core

### ISSUE THREAD

**Issue by tricoder42** [lingui/js-lingui#351]
This is a [HactoberFest](https://hacktoberfest.digitalocean.com/) issue! Read the [contest details](https://hacktoberfest.digitalocean.com/details) for more info.

## Before you begin

- Confirm that you're working on this issue so I can add [👩‍💻assigned](https://github.com/lingui/js-lingui/issues?q=is%3Aopen+is%3Aissue+label%3A%F0%9F%91%A9%E2%80%8D%F0%9F%92%BBassigned) label.
- Use `next` branch as a base for your PR. This feature should be released in upcoming [v3](https://github.com/lingui/js-lingui/issues/334).
- Read the [contribution guide](https://github.com/lingui/js-lingui/blob/master/CONTRIBUTING.md) for info how to setup project, run tests and use development version of packages
- Join us on [gitter](https://gitter.im/lingui/js-lingui) to get support

## Description

**Provide [Typescript](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) type definitions for `@lingui/core`**

Core exports few types from [`i18n.js`](https://github.com/lingui/js-lingui/blob/next/packages/core/src/i18n.js) using [Flow](https://flow.org/en/) type checker. I recently learned that it's possible to [publish](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) Typescript declaration files. This would be great for Typescript users.

## Task

Provide declaration file for [`i18n.js`](https://github.com/lingui/js-lingui/blob/next/packages/core/src/i18n.js) module and add it to `package.json`

## Additional info

I have no experience with Typescript at all. Any suggestions about publishing or testing are welcome!

**Comment by tricoder42** [comment]
I see. I would rather do it the other way round (e.g. [flow-to-typescript](https://github.com/bcherny/flow-to-typescript/tree/recursive-descent)) or manually for now. I don't have much spare time either. Learning Typescript and rewrite/maintain the repo might be too much at the moment. Let's review this option next month when I should be more available.

**Comment by FredyC** [comment]
Sure, other way around can work too, I wasn't able to find that tool you have. If it works, it would probably easiest route instead of maintaining separate typescript files manually. If it can generate quality typings, why not use it for a whole repo, not just a core one?

Btw, TypeScript is not really that different from the Flow, at least syntactically speaking. I know it sounds bit scary, been there too. It looks like something completely different from what you know, perhaps it's not even JavaScript? :D Trust me, it's not like that and you would be surprised how smooth experience it is.

Doesn't matter, it was just my opinion. Since this is not a priority right now and we are both busy, perhaps someone else would be able to saddle this beast :)

**Comment by kalabhairava** [comment]
I'll take a stab at this.

**Comment by tricoder42** [comment]
@kalabhairava Great! Thanks a lot! Just to be clear: only provide typings based on Flow types. Either manually or automated using conversion tool. Please don't rewrite the whole library to Typescript 🙈

**Comment by kalabhairava** [comment]
I'm having trouble setting up the environment.

The step `nvm install -s v8.11.4 --with-intl=full-icu` is failing with 
```
gyp:  --with-intl=full-icu not found (cwd: /home/manjunathad/.nvm/.cache/src/node-v8.11.4/files) while trying to load  --with-intl=full-icu
Error running GYP
nvm: install v8.11.4 failed!
```
Any leads on fixing that?

When I run `yarn test` on `node v10.5.0`, I see a bunch of failures.

Thanks!

**Comment by FredyC** [comment]
@kalabhairava Are you sure you can run NVM like this? I am not Windows, so I am not sure how that works. I guess you will have more luck filling an issue at NVM repo.

**Comment by tricoder42** [comment]
@kalabhairava What shell do you use? There's related issue in nvm repo: https://github.com/creationix/nvm/issues/1719

**Comment by tricoder42** [comment]
Just leaving it here for futures reference https://github.com/dmtrKovalenko/material-ui-pickers/pull/674

**Comment by Shermayster** [comment]
@kalabhairava are you started working on this? Maybe I can help you?

**Comment by kalabhairava** [comment]
@Shermayster, my apologies :disappointed: 

I'm caught up with a lot of work since the last few weeks, so I wasn't able to take a look at this issue. Please remove the `assigned` label, so that others can pick it up if they want. If it is still open after a weeks, I can take it up.

My apologies again :disappointed:

**Comment by chaselal** [comment]
The documentation suggests this work is already done.

https://github.com/lingui/js-lingui/commit/f789af1de083b5fe81c8662036eb0aead74f6ed5#diff-4cf0ca2c328ede20791c3f181ed03586R11
```
`Jeow Li Huan <https://github.com/huan086>`_ wrote type definition for ``@lingui/core``
```

Am I missing something?

**Comment by LStAmour** [comment]
You can install types with `npm install --save-dev @types/lingui__core` or `yarn add -D @types/lingui__core`: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/lingui__core

Also `npm install --save-dev @types/lingui__react` or `yarn add -D @types/lingui__react`: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/lingui__react

And `npm install --save-dev @types/lingui__macro` or `yarn add -D @types/lingui__macro`: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/lingui__macro

Any issues with the types can be reported here: https://github.com/huan086/lingui-typings/issues?utf8=✓&q=is%3Aissue+

The PRs against the @types repo can be found at: https://github.com/DefinitelyTyped/DefinitelyTyped/pulls?q=is%3Apr+lingui+is%3Aclosed

A PR for this project to support TS extraction is at https://github.com/lingui/js-lingui/pull/228/files

**Comment by tricoder42** [comment]
`next` branch was rewrite in typescript, so `core` and `react` packages include auto-generated definition files. Checkout #334 for info about pre-release.
