### ISSUE TITLE
Feature request: Linting step to find unmarked strings

### ISSUE THREAD

**Issue by agwells** [lingui/js-lingui#357]
First I'd like to say, I love LinguiJS! I was originally going to use React-Intl, and found it so verbose that I started working on a wrapper library to use it more efficiently. And then I came across LinguiJS, and was very pleased to find that it already does pretty much everything I was thinking of!

That said, the one remaining thing I'd love to have, is a linter to scan my code and look for strings that I've forgotten to tag with `<Trans>` or `t`. I find that this is one of the most common minor bugs I encounter, when working with internationalized programs.

Example:

```javascript
export default function MyComponent({i18n}) {
  return (
    <ul>
      <li><Trans>This one is marked</Trans></li>
      <li>This one is not</li>
      <li><input type="submit" value={i18n._(t`This one is marked`)} /></li>
      <li><input type="submit" value="This one is not." /></li>
    </ul>
  );
}
```

Expected results from linter:

```
Warning: Uninternationalized strings!
line 5:       <li>This one is not</li>
                  ^
line 7:       <li><input type="submit" value="This one is not." /></li>
                                              ^
```

However, it seems like there's one big hurdle in this. How can a script tell which strings are human-readable, translatable messages, and which are non-translatable things, like URLs and CSS class names?

So, I'd love to hear from anyone who has a good idea on how to approach that problem. :)

I'm thinking perhaps something like, provide an annotation to explicitly indicate that a string is not transatable (sort of the reverse of `i18nMark()`). And then make some educated guesses, like assume that a string is non-translatable if:

1. It contains no letters
2. It's in `snake_case`, `SCREAMING_SNAKE_CASE`, `kebab-case` etc
3. Maybe a list of JSX element attributes that can be ignored (`style`, `className`, `id`, etc)
4. It looks like a URL
5. etc...

The idea would be (as with all linting) that it wouldn't be 100% accurate, but that it would be able to spot enough missed strings to be useful, without getting so many false positives as to be useless.

**Comment by FredyC** [comment]
> However, it seems like there's one big hurdle in this. How can a script tell which strings are human-readable, translatable messages, and which are non-translatable things, like URLs and CSS class names?

Yea, that's exactly the reason why nobody has done yet. I suppose it would require some machine learning whatnot to be reliable.

Instead, you can have a look at [pseudo localization](https://lingui.js.org/tutorials/cli.html#pseudolocalization) which kinda helps, although it still needs a human eye.

**Comment by agwells** [comment]
@FredyC Thanks for the feedback! I'm actually already using Lingui's pseudo-localization feature, and I agree, it's very useful for manually checking for missing language strings. Particularly for dynamic stuff that might be missed in static code analysis.

> Yea, that's exactly the reason why nobody has done it yet. I suppose it would require some machine learning whatnot to be reliable. When you say linter, it's kinda expected it to be 100% solution and not a guessing machine.

Strictly speaking, if it's 100% accurate it's a _validator_, not a _linter_. ;) A linter checks for "bad code", which may include definite bugs, but can also include valid syntax that is likely (but not guaranteed) to be a mistake. But the terminology doesn't matter so much, for the sake of discussion I'd be happy to call it a "code checker" or whatnot.

I did some more searching yesterday and found a couple of existing tools for finding unmarked UI strings in JS projects. I didn't find anything usable with a Lingui/React project written in English, but it does show some strategies others have tried.

- [eslint-plugin-m6web-i18n](https://github.com/M6Web/i18n-tools/tree/master/packages/eslint-plugin-i18n) and [i18n-lint](https://jwarby.github.io/i18n-lint/) both basically check for (unmarked) string literals between HTML/JSX tags, or in some of their attributes.

- Another approach is the VS Code plugin [kiwi-linter](https://github.com/nefe/kiwi-linter), which just highlights unmarked non-Latin string literals in your code, and helps to quickly mark them. The non-Latin part is not useful for me: but the idea of an IDE plugin that highlights un-i18n-marked string literals, that idea seems like it could be useful for noticing UI strings I forgot to mark for i18n.

**Comment by tricoder42** [comment]
@agwells Wow, `kiwi-linter` looks great.

I was thinking about it and we could check children & whitelist of html props if they contain string. Maybe even check if that string is a natural language using NLP libs (https://github.com/spencermountain/compromise), but that would only work for english and supported languages.

I have no idea how to check other props, especially for custom components.

If you want to dig into this, I'm happy to test it or provide feedback. 

I was also thinking about writing a codemod which traverses your codebase and adds Trans components (i18n._ calls) where necessary. This is very similar to linter, because the hardest part is to find our what strings should be translated.
