### ISSUE TITLE
Optimize build with webpack

### ISSUE THREAD

**Issue by dephiros** [lingui/js-lingui#362]
**Is your feature request related to a problem? Please describe.**
At the company I am currently working at, we are trying to figure out a way to load translation strings more efficiently(only load what is used + user language)

**Describe the solution you'd like**
I am not familiar enough with webpack to know exactly what need to be developed(plugin, loader) but the general solution is:
- For each webpack entrypoint, load only what is used by comparing the metadata generated by jsLingui json with what files are included in the final bundle
- Generate separate bundles for each language

**Additional context**
If this does not result in code but some general directions, I would love to contribute

**Comment by dephiros** [comment]
Thank you @tricoder42 , I will keep looking into this and report back if I make any progress

**Comment by kompot** [comment]
This is basically the main reason we are trying to move away from `react-intl`.
We have 200kb+ (unzipped) language bundles already and there are not getting any smaller.

In case someone has time to tackle this, I guess he/she might take some clues from
https://github.com/webpack-contrib/i18n-webpack-plugin

Also this this approach should remove runtime calls for lots/most translations that do not have parameters.

**Comment by pristas-peter** [comment]
Hi, I did the second part (locales per chunks) in my personal react-intl-extract-webpack-plugin. You can check the implementation here:
https://github.com/pristas-peter/react-app/tree/master/packages/react-intl-extract-webpack-plugin

**Comment by tricoder42** [comment]
Closing in favor of #503.

Thank you @pristas-peter, I'll definitely check it out!
