### ISSUE TITLE
How to use this library with create-react-app?

### ISSUE THREAD

**Issue by segmentationfaulter** [lingui/js-lingui#364]
Since using this library requires me to install some babel plugins, which I cannot do while using `create-react-app` unless I eject. So how can I use this project with `create-react-app`?

**Comment by FredyC** [comment]
Have a look at [create-app-rewired](https://github.com/timarney/react-app-rewired) which helps to do exactly that. However, note that it's not working for CRA 2.x and it's uncertain it will ever work.

**Comment by tricoder42** [comment]
@segmentationfaulter You should use `@lingui/macro` because `babel-plugin-macros` is already included in Create React App v2. 

You can follow [tutorial](https://lingui.js.org/tutorials/react.html), but skip the step when adding plugin to babel config.

**Comment by mschipperheyn** [comment]
What if you don't want to use `@lingui/macro` because you have a lot of components built using `@lingui/react`? Can you still use create-react-app? I'm getting constant errors:

using `withI18n` and `i18n.t('ui.key')`Default`

```
TypeError: a.map is not a function
zip
node_modules/@lingui/core/cjs/core.development.js:170
  167 | };
  168 | 
  169 | var zip = function zip(a, b) {
> 170 |   return a.map(function (item, index) {
  171 |     return [item, b[index]];
  172 |   });
  173 | };
```

I have latest CRA and . babelrc

```
{
  "presets": ["@lingui/babel-preset-react"],
  "plugins": ["@babel/plugin-proposal-export-default-from"]
}
```

**Comment by FredyC** [comment]
@mschipperheyn Why not just find & replace that import? Nothing else changes as far as I know.

**Comment by tricoder42** [comment]
@mschipperheyn 

1. Custom .babelrc doesn't work with CRA by default
2. You need a plugin to make `i18n.t` work. That's the reason you're getting those errors.

You still can use LinguiJS without macro and plugins, but you have to write message format manually.
