### ISSUE TITLE
Object spread in <Trans> causes an error in "lingui extract"

### ISSUE THREAD

**Issue by agwells** [lingui/js-lingui#368]
**Describe the bug**
Let me preface this by saying, this is a fairly small bug, with a few different possible workarounds. But it looks like it may be an easy fix.

I was trying to do [lazy translation](https://lingui.js.org/tutorials/react-patterns.html#lazy-translations), but I wanted to support not just static strings, but also strings with placeholders (and potentially also plurals). So, instead of using `i18nMark()` (which only accepts static strings), I used the `t` macro to tag the language strings, and passed the resulting object in to the component that would render it. Because the string may have different sorts of fields depending on whether it has a placeholder, plural, etc, I used object spread syntax to turn them all into props: `<Trans {...myLangString} />`.

This evaluates and runs fine in dev, but it causes `lingui extract` to crash, with the error message:

```
node_modules/@lingui/babel-plugin-extract-messages/index.js:110
          var key = item.name.name;
```

**To Reproduce**

Here's a (very contrived) minimal example of the problem. Save the following file, and run `lingui extract` over it.

```javascript
import React from 'react';
import { Trans } from '@lingui/react';
import { t } from '@lingui/macro';

const adminName = 'Aaron';
const myTranslatedString = t`Please lazy-translate this, ${adminName}`;

export default function App() {
  return (
    <div>
      <Trans {...myTranslatedString} />
    </div>
  );
}
```

**Expected behavior**

`lingui extract` should not crash when it encounters this syntax. It should either silently ignore it, or possibly print a warning message like it does when it encounters a `<Trans>` tag that has no `id` prop.

**Additional context**

Fortunately there are several workarounds to this problem:

1. If your lazy-translated strings don't contain HTML, use `i18n._()` instead of `<Trans>`.
2. If your lazy-translated strings are just static string literals without placeholders or plurals, use `i18nMark()` instead of `t` or `plural()`.
3. Manually enumerate all the expected props from your lazy-translated strings: `<Trans id={myString.id} defaults={myString.defaults} values={myString.values} />`
4. Copy `<Trans>` to a local variable with a different name, and use that instead: `const NoExtractTrans = Trans; return <NoExtractTrans {...myString} />`
5. Add the file to your `srcPathIgnorePatterns` lingui config setting.

- jsLingui version: 2.7.0
- Babel version: 
```
└─┬ react-scripts@2.0.4
  ├── babel-core@7.0.0-bridge.0 
  └─┬ jest@23.6.0
    └─┬ jest-cli@23.6.0
      ├─┬ jest-config@23.6.0
      │ └─┬ babel-core@6.26.3 
      │   └─┬ babel-register@6.26.0
      │     └── babel-core@6.26.3 
      └─┬ jest-runtime@23.6.0
        └── babel-core@6.26.3 
```
- Your Babel config: Create React App 2.0.4

**Comment by agwells** [comment]
It looks like the problem is that JSX object spread is represented in Babel's AST as an "attribute" that has no "name" node under it. So the `.reduce` call that tries to gather up data about all the `<Trans>` tag's props, needs to do something like `if (!item.name) return acc;`

Unfortunately I don't have time to test this out right now.

**Comment by tricoder42** [comment]
Hey @agwells, unfortunately you can't use object rest spread operator on Trans component. What you can do, however, is to pass message descriptor to `id` prop:

```
<Trans id={myTranslatedString} />
```

Trans component is mostly a facade for `i18n._` which accepts message descriptors as documented.

Please let me know if it solves your problem.

Object rest spread operator isn't supported because it's hard to find out at built time the content of object (in general case).

**Comment by tricoder42** [comment]
I'm gonna leave this open, because the error message should be better and more descriptive.
