### ISSUE TITLE
Any way to add line breaks for translation?

### ISSUE THREAD

**Issue by ziyafenn** [lingui/js-lingui#370]
Hi there! Thanks for the amazing framework!

I wonder if there is any way i could add line breaks to my `i18n._(t``);` component that it also appears correctly on the .po files?

The thing is when i add `${'\n'}` inside  `(t``);` the line break appears as {0} and it is not clear if it's a line break or just a variable. + It is also not best solution, as the same sentence without line break will appear as a new translation.

Inside `<Trans>` i can use {"\n"}, but those do not appear on the .po files.

Thanks a lot!

**Comment by tricoder42** [comment]
Hey @ziyafenn,
yes, this was fixed in #324, but it's scheduled for release in 3.0 which might take some time. I'm currently at React Conf, but I might try to backport it and release in 2.x next week.

Looking at it now, I'll leave this open, because #324 fixes only newlines in JSX, but I haven't considered the usecase with template literals.

**Comment by ziyafenn** [comment]
hey @tricoder42 
actually, i don't have an issue with the rendering new lines inside `<Trans>`. For me, it does somehow render new lines. Same goes for `i18n._(t``);`.

My issue is actually to display those new lines in .po editor so translator knows that he should also add those new lines in translation.

For example, in Poedit if you would add a new line break with **Enter**, you'd see that it adds `\n` to the translation. But they are not rendered in React Native. I'd love to see it working in both ways. That .po editor recognizes `\n` from the RN code and RN respectively recognizes the `\n` from .po editor. 

Thanks and have fun in React Conf!

**Comment by efstathiosntonas** [comment]
Hey folks, sorry for digging this from the grave, I use react-native and I agree with @ziyafenn. 

How to add a new line in this string? 

```tsx
import { msg } from "@lingui/macro";
import { useLingui } from "@lingui/react";

 const { _ } = useLingui();

<Text style={styles.subtitle}>
          {_(
            msg`Looks like you found a bug for us!\n\nPlease click the button below to re-load the app.`
          )}
        </Text>
```

**Comment by thekip** [comment]
Hey, i'm aware of this problem and already prepared a fix which is merged in the next branch and would be included in the next major version. Unfortunately untill now all macro trying to "normalize" line breaks and spaces by completely removing them from the input. 

One of the workarounds could be 

```js
const BR = "\n\n";
msg`Looks like you found a bug for us!${BR}Please click the button below to re-load the app.`
```
