### ISSUE TITLE
Element attributes that require a translated string show warnings due to proptype being an object.

### ISSUE THREAD

**Issue by wilkinsonjack1993** [lingui/js-lingui#375]
**Describe the bug**
I am trying to create a search bar using the material UI searchbar which has a placeholder attribute. This placeholder attribute has a propType of string, however I want to pass it a translatable string using the pattern outlined [here](https://lingui.js.org/tutorials/react-patterns.html#id2). I have tried using the i18n method in order to create a string only translation but it does not seem to be working as expected for me. It could be that I have miss understood the documentation...

**To Reproduce**
The simplest version of the app would look something like below. I am trying to make the 'Search' placeholder translatable depending on the locale. The warning given in the console is: 

> Warning: Failed prop type: Invalid prop `placeholder` of type `object` supplied to `SearchBar`, expected `string`.

```
import { t } from '@lingui/macro'
import { I18n } from '@lingui/react'
import SearchBar from 'material-ui-search-bar'

export default function App() {
render() {
   return (
               <I18n>
                  {({ i18n }) => (
                    <SearchBar placeholder={i18n._(t('search.bar.placeholder')`Search`)}/>
                   )}
                </I18n>
                )
}}
```

**Expected behavior**
Maybe I am missunderstanding the documentation, but it seems to suggest that the i18n method will return a string that can be passed in as an attribute.

**Comment by tricoder42** [comment]
@wilkinsonjack1993 You're correct, it's supposed to work like that. I tried your example but didn't get the same error. I suppose your App component is wrapped in I18nProvider, right?

What version of LinguiJS and Babel do you use?

**Comment by wilkinsonjack1993** [comment]
Hi @tricoder42, 

Thanks for getting back to me. I did a refactor of the component that I was using to load the local and pass it into the I18nProvider and it seems to work perfectly now. No idea what I changed exactly to fix it but I think it's safe to assume that this was an error on my side and not with the lingui library. 

Thanks for your help - I'll close off the issue :)
