### ISSUE TITLE
Neutrino: Template literals do not work when targeting IE 11

### ISSUE THREAD

**Issue by akkie** [lingui/js-lingui#38]
If I target the browser `ie 11` in my `babel-preset-env` config, then the translation which are based on template literals do not work. I think it's because `babel-preset-env` pulls in `transform-es2015-template-literals`. It generates then code like this:

```
var _templateObject = _taggedTemplateLiteral(['This field is required'], ['This field is required']),
    _templateObject2 = _taggedTemplateLiteral(['Valid email required'], ['Valid email required']);

var defaultMessages = exports.defaultMessages = function defaultMessages(i18n) {
  return {
    isRequired: i18n.t(_templateObject),
    isEmail: i18n.t(_templateObject2)
  };
};
```

Without the `transform-es2015-template-literals` plugin, it creates code like:
```
const defaultMessages = i18n => ({
  isRequired: i18n._('This field is required'),
  isEmail: i18n._('Valid email required')
});
```

If I'm right then you transform also template literals t function calls, but now the `transform-es2015-template-literals` comes first and your transformation cannot be processed.

**Comment by tricoder42** [comment]
Is `lingui-react` the last preset in your `.babelrc`?

**Comment by akkie** [comment]
It's currently the only plugin. The other plugins will be added by neutrino.

**Comment by tricoder42** [comment]
Could you please give me more info how you configure neutrino? Where do you add `lingui-preset`?

I'm thinking about creating `neutrino-preset-lingui` and adding required presets.

**Comment by akkie** [comment]
This is for the 0.x version of lingui. But the config is mostly the same for the project I'm currently working on. 

https://github.com/setusoft/silhouette-play-react-seed/blob/master/app-ui/.neutrinorc.js

https://github.com/setusoft/silhouette-play-react-seed/blob/master/app-ui/.babelrc

**Comment by tricoder42** [comment]
What if you change `neutrino-preset-react` config:

```js
const path = require('path');

module.exports = {
  use: [
    ['neutrino-preset-react', {
      babel: {
        presets: [
          ['babel-preset-env', {
            targets: {
              browsers: [
                'last 1 Chrome versions',
                'last 1 Firefox versions'
              ]
            }
          }],
          'lingui-react'
        ]
      }
    }],
    'neutrino-webpack.js',
    'neutrino-sass.js',
    ...
  ]
}
```

instead of adding `lingui-react` to `.babelrc`?

**Comment by tricoder42** [comment]
Another option might be using `lingui-transforms-js` and `lingui-transform-react` plugins directly. Plugins run before presets, so that would work too. But I consider both options as a workaround. This should be easier.

**Comment by akkie** [comment]
```
presets: [
  'lingui-react',
  ['babel-preset-env', {
```

This works for me. But You're right. This should be easier.

**Comment by tricoder42** [comment]
That's interesting. Presets should be in reverse order (first preset at the bottom). So I would expect, that you need to put `lingui-react` below `env`.

I need to figure out how to deal with frameworks like create-react-app or neutrino.

**Comment by tricoder42** [comment]
Closing for now.

I'm gonna add info about integrations to docs.

**Comment by tricoder42** [comment]
Added section about integrations https://lingui.gitbooks.io/js/guides/integrations.html
