### ISSUE TITLE
Build starts failing when integrating with a Babel 6 preact project

### ISSUE THREAD

**Issue by chinchang** [lingui/js-lingui#384]
**Describe the bug**
When I add @babel/core and babel-core/@bridge packages to my preact app (on Babel 6), the build starts failing with:

```
Module build failed: Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you are migrating from Babylon/Babel 6 or want to use the old decorators proposal, you should use the 'decorators-legacy' plugin instead of 'decorators'.
```

**To Reproduce**

I have a minimal project setup with preact-cli here -> https://github.com/chinchang/preact-lingui/

This is the specific commit to integrate lingui -> https://github.com/chinchang/preact-lingui/commit/1b61f18a02ec0760019dc878873fb0a15759555e

If you start the app with `yarn start`, it fails with above-mentioned error.

**Additional context**
- jsLingui version ``lingui --version``: 2.7.0
- Babel version ``npm list babel-core``: ├── babel-core@7.0.0-bridge.0
├─┬ jest@21.2.1
│ └─┬ jest-cli@21.2.1
│   └─┬ jest-runtime@21.2.1
│     └── babel-core@6.26.3
└─┬ preact-cli@2.2.1
  └─┬ babel-register@6.26.0
    └── babel-core@6.26.3
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.) - Using preact-cli which has this config -> https://github.com/developit/preact-cli/blob/master/src/lib/babel-config.js

**Comment by FredyC** [comment]
I think you should communicate this within Preact repo as a configuration for Babel 7 is not related to Lingui really.

**Comment by chinchang** [comment]
@FredyC I was not sure where to ask this but since Lingui explicitly mentions supporting apps with Babel 6 also, I thought about asking here.

**Comment by FredyC** [comment]
Well, it supports Babel 6, but at the moment you've installed that bridge, you have essentially updated to Babel 7. Please sort this out with Preact or try my advice above.

**Comment by tricoder42** [comment]
@chinchang Indeed, it looks like misconfigured babel.

1. I don't understand why you add `lingui` environment to you Babel config

https://github.com/chinchang/preact-lingui/blob/1b61f18a02ec0760019dc878873fb0a15759555e/.babelrc#L8

Lingui doesn't need specific configuration. It's enough to add `babel-plugin-macros`.

2. Once you add @babel/core and babel-core/bridge, you use Babel 7. It looks like preact preset still uses Babel 6, so you need to remove `@babel/core` and bridge and use Babel 6 in you project as well.

Hope it helps

**Comment by tricoder42** [comment]
If anyone has the same problem, here's the PR which fixes problems described above: https://github.com/chinchang/preact-lingui/pull/1

**Comment by chinchang** [comment]
@tricoder42 I added babel environment for `lingui extract` to work. Otherwise it wasn't able to parse JSX as there is no global babel environment available. I guess you added `babel-preset-preact` instead, in babelrc for the same reason, correct?
All is working in your PR now. Thank you very much for your help :)

**Comment by tricoder42** [comment]
I understand your motivation but you can't create babel environments just like that. Babel environment must be supported by the library (e.g `jest` uses `test` env) and in that case it's always documented.

Lingui doesn't use Babel environments at the moment. In the future, it'll use the standard `production` and `development`, but when it happens, it'll land in docs first.

Glad it works now! Cheers 👍
