### ISSUE TITLE
Documentation: All catalogs including sourceLocale must be compiled. Default messages aren't available in production.

### ISSUE THREAD

**Issue by yalishizhude** [lingui/js-lingui#388]
**Describe the bug**
`@lingui/core/cjs/core.production.min.js` Found a bug in this file.

```
i18n._('My name is {name}', {name: 'yalishizhude'}) 
//  as expected, it should be  'My name is yalishizhude'.
// but in fact it is 'My name is {name}'
```

**To Reproduce**
**Remember, must use the production js,development is ok.**
```
import { setupI18n } from '@lingui/core';
const i18n = setupI18n();
i18n._('My name is {name}', {name: 'yalishizhude'}) 
```

**Expected behavior**
My name is yalishizhude

**Additional context**
My name is {name}

- jsLingui version ``2.7.0``
- Babel version ``6.26.0``
- framework you use (Create React App)

**Comment by tricoder42** [comment]
This might be similar issue as in https://github.com/lingui/js-lingui/issues/385. Could you please try to load compiled catalog with translated messages?

```js
import { setupI18n } from '@lingui/core';

// change location to your source catalog
import catalogEn from '@lingui/loader!locale/en/messages.po'

const i18n = setupI18n();
i18n.load({ en: catalogEn })
i18n._('My name is {name}', {name: 'yalishizhude'}) 
```

**Comment by yalishizhude** [comment]
Yes, I have my own catalogs.The almost full code as follows:
```
// i18nFactory.ts
import { Catalogs, setupI18n } from '@lingui/core';

export default (catalogs: Catalogs) => {
  const i18n = setupI18n({
    catalogs
  });
  return i18n;
};
```

```
// i18n.ts
import en from '../locale/en';
import zh from '../locale/zh';
import factory from './i18nFactory';

export default factory({ en, zh });
```

```
// en.ts
const en = {
  ...
  'rule.same': '{srcFieldName} is different from {destFieldName}',
  ...
}
```

I cannot precompiled the catalogs, because as the codes show, `srcFieldName` and `destFieldName` are dynamic decided by variables(some logic or some requests' response, something like this), not static.

**Comment by tricoder42** [comment]
@yalishizhude That's fine. You need to compile catalogs especially for messages with formatting.

Use `lingui extract` to get message catalogs and then `lingui compile` to get final js module. Don't write it manually.

Let me know if it helps

**Comment by yalishizhude** [comment]
It doesn't work though I tried two diffrent ways~
1. I follow the plugin's instruction to add configuration to package.json like this:
![image](https://user-images.githubusercontent.com/3870098/48462627-df1c5a00-e813-11e8-9eb4-4ef6b83865ae.png)
Then I compile my project.Nothing changed.
2. I follow the setup guide and installed some packages,added scripts.
But it showed error:

![image](https://user-images.githubusercontent.com/3870098/48462707-2a366d00-e814-11e8-9118-abd5cfda9bee.png)

**Comment by tricoder42** [comment]
1. You don't need to change you Babel config

2. There's actually bug in `compat.js` file, I'll release fix soon. It also means you have mismatch in you babel-core version. 

    What version of `babel-core` and `@babel/core` do you have installed? Please run `yarn list babel-core @babel/core` and paste the output here, thanks

**Comment by yalishizhude** [comment]
![image](https://user-images.githubusercontent.com/3870098/48533577-0d676b80-e8e0-11e8-8d9d-24b2e654e6cb.png)

**Comment by professorplumb** [comment]
We are experiencing the same issue in a production environment.

Development:
```
> i18n._({id: "All {count} and we'll watch them fall", values: {count: 43}})
"All 43 and we'll watch them fall"
```

Production:
```
> i18n._({id: "All {count} and we'll watch them fall", values: {count: 43}})
"All {count} and we'll watch them fall"
```

This happens regardless of what we do with the catalogs: whether they're compiled or completely blank (`{}`), and whether or not the string appears in the catalog.  (If it doesn't, it should be returned as-is with the interpolation performed, unless I misunderstand.)

**Comment by tricoder42** [comment]
> If it doesn't, it should be returned as-is with the interpolation performed, unless I misunderstand.

That's the problem. Since the messages with formatting are compiled offline, when the message is missing, it can't be interpolated. In development, the messages are compiled on the fly, but in production the parser is removed from bundle.

**Comment by szewczykmira** [comment]
I'm quite confused right now - is this bug fixed or not? I also encounter it. I've checked and I have translations for selected language and it still doesn't interpolate variables.

**Comment by professorplumb** [comment]
The base issue - that language catalogs need to be compiled in a production setting in order for interpolations to work - has not been "fixed".  If I understand @tricoder42 correctly, this is intended behavior and won't be changed.

You can either set up your environment so that catalogs are compiled before being deployed to production, or (what we did) use [@lingui/loader](https://lingui.js.org/ref/loader.html) to have webpack compile them.

**Comment by ppozniak** [comment]
Leaving here in case someone has the same problem.
For me it was caused by using `setupI18n`, but not setting the default value there.
```
const catalogs = { } // your catalogs here 
export const i18n = setupI18n({ catalogs, language: 'en' });

<I18nProvider
            i18n={i18n}
            language={sessionConfig.locale || DEFAULT_LOCALE}
            catalogs={catalogs}
          >
```

**Comment by josh-stevens** [comment]
I think the documentation was unclear on how to do this. I didn't realize I needed a catalog for my source locale, I thought it would just fallback to using that when the locale was not set. Indeed it does fallback to using that, the only thing it fails to do is interpolate variables. Finally fixed my own issues when I added an `en` catalog and added it as `sourceLocale`/`fallbackLocale` in my linguirc

**Comment by tricoder42** [comment]
Indeed, this needs to be documented. It's common misconception.

In short:
- There're no default messages in production. They're stripped to save the bundle size. If message is missing translation, it's replaced with default one at compile time.
- All catalogs (including sourceLocale) must be compiled. This is especially important for messages with formatting.

Feel free to add it to docs and send a PR 👍 We probably need a new page in `Guides`, but I'm not sure if it should be `Message catalogs` or `Building the app for production`

**Comment by hjylewis** [comment]
This is definitely one of the more confusing things about this library for new users.

While documentation will certainly help, I'm curious what the motivation is for having the runtime compiler format default-messages in development which hides issues that will occur in production. I could be overlooking a reason why the runtime compiler in development is necessary.

This sets developers up for a surprise when their broken code was "working" in development but now is actually broken in production.

Should the development experience more reflect production? Or at least should there be more red flags/warnings in case the developer messes-up loading the catalogs?

**Comment by tricoder42** [comment]
> While documentation will certainly help, I'm curious what the motivation is for having the runtime compiler format default-messages in development which hides issues that will occur in production. I could be overlooking a reason why the runtime compiler in development is necessary.

This is good point, actually. My motivation was easier setup, but now it's hard to detect if the setup is completed before the production deployment.

I'm in favor of removing implicit runtime parser in development mode.

**Comment by hjylewis** [comment]
Sounds good. I created an issue #519 to track this work.

**Comment by tricoder42** [comment]
Closed as stale https://github.com/lingui/js-lingui/pull/543#issuecomment-720136511
