### ISSUE TITLE
Message catalog for locale "en" not loaded.

### ISSUE THREAD

**Issue by hundsim** [lingui/js-lingui#391]
**Describe the bug**
No translations are showing up, and I'm getting the warning:
>Message catalog for locale "en" not loaded.

**To Reproduce**
I've followed the Get started guide and upon running `yarn extract` we can see that lingui recognizes the two translated strings I've created. I have run `yarn compile` as well.

Catalog statistics:
┌──────────┬─────────────┬─────────┐
│ Language │ Total count │ Missing │
├──────────┼─────────────┼─────────┤
│ en       │      2      │    0    │
│ sv       │      2      │    0    │
└──────────┴─────────────┴─────────┘

```
import { Trans } from '@lingui/macro'

render() {
   return <Trans>home.startNew</Trans>
}
```

**Expected behavior**
The translation should be displayed.

**Additional context**
create-react-app v2.0

**Comment by ghostd** [comment]
Hi,

Did you extract then compile your catalogs? How do you load them? Can you paste your loading code please?

**Comment by hundsim** [comment]
@ghostd Thanks, good catch. I didn't understand that manual loading of translations was necessary. 

For posterity, this is how I solved it:

`import catalogSv from './locales/sv/messages.js'
import catalogEn from './locales/en/messages.js'
const catalogs = { sv: catalogSv, en: catalogEn }

return (
  <I18nProvider
    language={locale}
    catalogs={catalogs}
  >
    <App/>
  </I18nProvider>
)
`
