### ISSUE TITLE
Reuse of component

### ISSUE THREAD

**Issue by huan086** [lingui/js-lingui#393]
**Is your feature request related to a problem? Please describe.**
When using `<Trans><p>Paragraph 1</p><p>Paragraph 2</p></Trans>`, we get the first `<p>` converted to `<0>` and the 2nd converted to `<1>`. It looks like the translator will be restricted to only two paragraphs of text.

**Describe the solution you'd like**
It would be nice if we could collapse similar components to the same index, and allow the index to be used multiple times. That is, the above would become `<0>Paragraph 1</0><0>Paragraph 2</0>`

**Describe alternatives you've considered**
Using newlines: drawback is that it isn't the same thing as paragraph, thus the styling on `p` doesn't get applied

**Additional context**
None

**Comment by tricoder42** [comment]
It's hard to tell in general case if the components can be collapsed, but we could add an exception for built-in tags (`p`, `br`, anything tag in lower-case letters) when elements have the same props:

```js
<Trans><p>Paragraph 1</p><p>Paragraph 2</p></Trans>
// ↓ ↓ ↓ ↓ ↓ ↓ ↓ 
<Trans id="<0>Paragraph 1</0><0>Paragraph 2</0>" components={[<p />]} />
```

Interested in sending a PR?

**Comment by huan086** [comment]
Not so soon. Will need some time to read and understand the code again. You have been so active in developing this! 😄

**Comment by tricoder42** [comment]
@huan086 I'm closing this as it isn't very urgent, but feel free to reopen when you have a PR. In `next` version the `components` prop of `<Trans>` tag has changed and now it's possible to name the tags:

```js
<Trans><p>Paragraph 1</p><p>Paragraph 2</p></Trans>

// Before
<Trans id="<0>Paragraph 1</0><1>Paragraph 2</1>" components={[<p />, <p />]} />

// Now it could be
<Trans id="<p>Paragraph 1</p><p>Paragraph 2</p>" components={{p: <p />}} />
```
