### ISSUE TITLE
Validated plural rules and warn about missing ones

### ISSUE THREAD

**Issue by FredyC** [lingui/js-lingui#397]
**Describe the bug**
When plural for some language is not translated yet or missing particular form for a given value, the empty string is returned

**To Reproduce**

```jsx
import { Trans } from "@lingui/react"

export default function App() {
   return <Plural value={booksNum} other="# books" />
}
```

Have this extracted with `en` as a sourceLanguage, then switch to eg. `cs`.

**Expected behavior**
For `booksNum < 5` I would expect that `other` form will be used as a fallback if one/few is missing in translation. When the `booksNum >= 5` it works correctly and result is `5 books` even with `cs` locale.

**Comment by tricoder42** [comment]
I noticed this behavior as well. I'm not sure if `other` should be considered as a fallback. Some languages use `other` form for decimal numbers and `many` as a fallback for integers (Polish, Russian).

What about raising error in development to catch missing message early? It should be also checked during `lingui compile --check` to avoid runtime errors.

**Comment by FredyC** [comment]
Well, I am not sure if it should be really considered an error. I definitely would not like for this to be blocking deployment because we are missing eg. Japanese translation for a single sentence :)

I am mostly coming from the fact, that `other` is only required prop in `Plural`, at least based on current TypeScript definition. Thus it felt like a good fallback variant.

How are other translation frameworks solving that? I've been using react-intl briefly in the past and I don't really recall.

**Comment by FredyC** [comment]
I guess it wouldn't be a that bad thing, after all, being able to check if all translations are present, including all plural forms. As long as it would be under `--check` thus not preventing compilation it would be possible to leave the decision in hands of upper management if they want to release now with something missing or rather ensure a translation.

PS: I don't know anything about Japanese, it was a just wild guess more on the point that it might be hard to get a translation without some Japanese person.

**Comment by tricoder42** [comment]
As there's no easy way to determine "fallback" rule, let's simply raise validation warning/error when message is missing:

1. In macro, validate plural rules based on `linguiConfig.sourceLocale` value.
2. In `lingui compile --check`, validate plural rules for each locale. This will be tricky, as we need to parse message and find plural formatters. On the other hand, we need to parse message anyway to check there're no syntax errors.
3. In loader, validate plural rules for specific locale (similar to `lingui compile --check`)
4. Finally in core, show warning about missing plural rule. This is a fallback warning for anyone who doesn't use macros.

**Comment by FredyC** [comment]
Whoa, this has been here for 2 years now, but I guess it's still valid. I mean I got used to writing proper plural translations since I am doing those for myself. But I can imagine if I decide on more languages later that will be translated somewhere else, it would be handy to have a tool to check it.

PS: You should probably configure Stale bot to ignore "triage: accepted" labels ;)

**Comment by tricoder42** [comment]
Hey @FredyC, feel free to send the PR if you still find it valid 👍 

Even accepted issues might become "stale" when author looses interest. The point is to get rid of issues which nobody has time to finish/close

**Comment by FredyC** [comment]
Well, it's not immediate pain for sure and I don't really have a capacity right now. But I would appreciate it if you can keep it around in case somebody else gets interested in it.

**Comment by tricoder42** [comment]
Well, nobody found it interesting in two years. If someone had a similar need, they can always find it or create a new issue. No big deal.

**Comment by amorphius** [comment]
I have the same issue with Russian translation of `other`. So should I stop using lingui.js because of poor support?

**Comment by FredyC** [comment]
> So should I stop using lingui.js because of poor support?

Or you can open a new issue with necessary details and perhaps even contribute a solution :) You know, such comments toward people that are doing something for free are really rude. Have you paid for the support?

**Comment by amorphius** [comment]
> > So should I stop using lingui.js because of poor support?
> 
> Or you can open a new issue with necessary details and perhaps even contribute a solution :) You know, such comments toward people that are doing something for free are really rude. Have you paid for the support?

I don't. But if this product (even free) doesn't satisfy my needs I have absolute right not to use it, correct?

**Comment by FredyC** [comment]
> But if the product (even free) doesn't satisfy my needs I have absolute right not to use it, correct?

Sure, and you have also an absolute right to stay silent about it and move along. Screaming "this is bad, I am going away" is useful how exactly? I would recommend you trying to contribute to open-source software to get the feeling of how depressing it is when someone says you are doing a bad job in your spare time.

**Comment by amorphius** [comment]
You're right, sorry. I'm not using this library in my spare time but on the paid work so probably that's why I don't feel thankful because it's just my job.
