### ISSUE TITLE
I18n._ calls with variables not properly translated in production

### ISSUE THREAD

**Issue by webdevbe** [lingui/js-lingui#398]
**Describe the bug**
I found that several translation entries in my application are not properly translated. It happens in entries where text and variables are mixed as can be seen in the code below. Surprisingly, this does work when running a local dev server, but not when checking in prod.

**To Reproduce**
I tried creating a minimal reproducing example, without luck. 
These are a couple of strings that I found that weren't translated properly.

```
pdf.text(40, 168, i18n._(t`Generated by ${user.name} on ${generationDate}`))
pdf.text(20, 20, i18n._(t`Appname - ${title.toUpperCase()} ${subtitle}`))
i18n._(t`A value for ${obj.name} is required`)
i18n._(t`Upload date: ${moment(new Date()).format(dateFormat)}`)
```

**Expected behavior**
I would expect the validation to take place and instead of outputting {0}, the value should be shown.

**Additional context**
- Currently, I didn't translate anything yet. I created a catalog for English language, but I'm using the fallback mechanism that takes the entry key. 

- The catalog is definitely loaded, as other text is translated.

- jsLingui version ``2.7.1`
- Babel version ``7.0.0-bridge.0``
- Framework: React
- jsLingui config: 
```
{
   "localeDir": "src/locales/",
   "srcPathDirs": ["src/"],
   "format": "minimal"
}
```

If any more information is required, let me know.

Thanks!

**Comment by tricoder42** [comment]
Hey @webdevbe, do you load compiled message catalogs? What file with messages do you import?

**Comment by webdevbe** [comment]
Yes, I import the compiled catalog (.js) with `import catalogEn from './locales/en/messages.js'`

**Comment by tricoder42** [comment]
Could you please create a repository with minimal example so I can check it?

**Comment by webdevbe** [comment]
I tried it, but as described in the ticket, I wasn't able to reproduce it in that example. I can try again though. In the meanwhile, are there any debugging steps I can follow to check where it fails? Or do you maybe already have some ideas what it could be?

**Comment by tricoder42** [comment]
If it works in development, but not in production, it usually means there's a problem with compiled catalogs. That could also mean the catalogs aren't loaded properly. How do you load the `catalogEn`? Is it similar to this?

```js
import { setupI18n } from '@lingui/core'
import catalogEn from './locales/en/messages.js'

const i18n = setupI18n()
// mind the `en` key
i18n.load({ en: catalogEn })
i18n.activate('en')
```

Finally, don't forget to activate the target language (even if it's the default one, `en`)

**Comment by webdevbe** [comment]
It wasn't currently this, I had
```
import { I18nProvider } from '@lingui/react'
import catalogEn from './locales/en/messages.js'


const catalogs = { en: catalogEn }

ReactDOM.render(
  <I18nProvider language='en' catalogs={catalogs}>
    <Router ...props />
  </I18nProvider>,
  document.getElementById('content')
)
```

So I changed to 
```
import { I18nProvider } from '@lingui/react'
import { setupI18n } from '@lingui/core'
import catalogEn from './locales/en/messages.js'

const catalogs = { en: catalogEn }
const i18n = setupI18n()
i18n.load({ en: catalogEn })
i18n.activate('en')

ReactDOM.render(
  <I18nProvider language='en' catalogs={catalogs}>
    <Router ...props />
  </I18nProvider>,
  document.getElementById('content')
)
```

But unfortunately no luck. I'll investigate the compiled catalogs now.

**Comment by webdevbe** [comment]
**Fixed it!** 

I was indeed wrong with loading the catalog. The reason why your previous info didn't work for me, is because I had set up the i18n object in a separate file. Implementing the activating behaviour there, solved the issue.

Thanks a lot for your help!
