### ISSUE TITLE
Should messages.js be referenced in production or can strings be dynamically loaded?

### ISSUE THREAD

**Issue by ripern** [lingui/js-lingui#399]
@tricoder42 In https://github.com/lingui/js-lingui/issues/163 you wrote
> In production you need alway reference `messages.js` (compiled catalog). There's a webpack loader to make things easier, which allows you to reference `messages.json` and the file is compiled to `messages.js` on-the-fly.
> This is not only about language data (e.g. plurals). In production, the message parser isn't available (because it's slow and large) and compiled catalog contains messages compiled to functions.

I might be misunderstanding something but why do you first state that in production you need to reference messages.js and then in the sentence after mention that there is a webpack loader which allows you to NOT have to reference messages.js directly?  I have used the latter way in dev but had problems with it in production, so just looking for an answer to if the dynamic loading should be used in production or not.

Cheers

_Originally posted by @ripern in https://github.com/lingui/js-lingui/issues/163#issuecomment-439434030_

**Comment by tricoder42** [comment]
Hey @ripern,
both in production and development, you can't *dynamically* load messages at runtime. Right now you have to load messages from external file.

You need to load *compiled* messages. It's recommended to load compiled messages even in development to have the same environment as in production.

To load compiled messages, either reference them directly (`messages.js`) or compile catalog (`messages.json`) on the fly using webpack loader.

```js
// Good
import catalogEn from "locales/en/messages.js"

// Better (you don't have to run `lingui compile` manually)
import catalogEn from "@lingui/loader!locales/en/messages.json"

// Wrong (can't load messages dynamically at runtime)
const catalogEn = {
  source: "Translation"
}
```

Does it make sense?

**Comment by ripern** [comment]
Yes it makes sense. I'm now using `import catalogEn from "locales/en/messages.js"` and letting build server run `lingui compile`.

Then it would probably be nice with a section discussing this before linking to, https://lingui.js.org/guides/dynamic-loading-catalogs.html, because currently when reading https://lingui.js.org/tutorials/react.html and seeing "Let’s deal with language switching later… but if you’re still curious, take a look at example with Redux and Webpack." it feels like the way to do language switching is to load stuff dynamically (even though I know it's just an example).

**Comment by tricoder42** [comment]
Yeah, good point!. `dynamic loading catalogs` section will go away completely in next version. The API is much simpler.

Alright, closing this. Cheers 👍
