### ISSUE TITLE
t and Trans behaviour is inconsistent

### ISSUE THREAD

**Issue by stereobooster** [lingui/js-lingui#404]
**Describe the bug**

Assume there is no fallbackLocale. And we have following code

```js
i18n._(t("component.name")`Your name`)

<Trans id="component.name1">
  Your name
</Trans>
```

After compiling it will be

```js
b._({id:"component.name",defaults:"Your name"})

i.a.createElement(m.Trans,{id:"component.name1"}))
```

First one preserve default in source code, but second one not.

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```js
import { Trans } from "@lingui/react"

export default function App() {
return [
i18n._(t("component.name")`Your name`),
<Trans id="component.name1">
  Your name
</Trans>
}]
```

**Expected behavior**

I expect them to behave consistently either both remove default from compiled version or both leave it

**Additional context**

- jsLingui version ``2.7.1``
- Babel version 
├─ babel-core@7.0.0-bridge.0
├─ babel-register@6.26.0
│  └─ babel-core@6.26.0
└─ jest-runtime@22.4.4
   └─ babel-core@6.26.0
- Your Babel config CRA `"react-scripts": "2.0.0-next.a671462c"`

I can provide reproducible example if required

Related: https://github.com/lingui/js-lingui/issues/396, https://github.com/lingui/js-lingui/issues/383

**Comment by vractal** [comment]
I believe i'm facing some testing problems regarding this issue. Trans component gets weird behaviour and shows id instead of defaults in snapshots, while t works as it's suposed.
