### ISSUE TITLE
Extract with keys

### ISSUE THREAD

**Issue by stereobooster** [lingui/js-lingui#405]
**Is your feature request related to a problem? Please describe.**

Given following code:

```js
<Trans id="LinguiJS.example"/>
```

and config

```
{
  "localeDir": "src/locales/",
  "srcPathDirs": ["src/"],
  "format": "po",
  "fallbackLocale": "en",
  "sourceLocale": "en"
}
```

`yarn extract` will produce

```
#: src/Home.js:19
msgid "LinguiJS.example"
msgstr "LinguiJS.example"
```

**Describe the solution you'd like**
Is there a way to output empty string? Because id can be differentiated from default value

```
#: src/Home.js:19
msgid "LinguiJS.example"
msgstr ""
```

**Describe alternatives you've considered**
none

**Additional context**
I would expect that `yarn compile --strict` will fail if there is any empty string in default locale, and this way it is easy to track that all keys have at least default translation.

On the other side how you distinguish between ids and default values with `i18n._` or `t`-macro. So maybe we need configuration for Lingui to say if we use keys or defaults (case with keys and defaults easy to distinguish).

**Comment by ripern** [comment]
For some reason, `yarn extract` for me will produce what you want. Is it still working the same unwanted way for you?
Both `<Trans id="LinguiJS.example"/>` and `<Trans id="LinguiJS.example">Hello</Trans>`
will generate
```
msgid "LinguiJS.example"
msgstr ""
```

**Comment by ripern** [comment]
Actually I was missing
```
"fallbackLocale": "en",
"sourceLocale": "en"
```
in config, and after adding them I get what you get in en/messages.po
but not in the other language files (there msgstr is empty). I'm guessing that is by design.

**Comment by tricoder42** [comment]
You should use `sourceLocale` only when you use messages as IDs. With custom keys you should omit this config.
