### ISSUE TITLE
TypeError: Cannot read property 'locales' of undefined

### ISSUE THREAD

**Issue by ackvf** [lingui/js-lingui#410]
I have a React application where I generate a PDF using `pdfmake`. However, inside the pdf script, I cannot use React components and I am getting issues with `number` and `date`.

This is my React component
```
import makePDF from './makePDF';

const ApplicationSummaryScreen = ({ i18n }) => {
  function download(application) {
    makePDF(application, i18n).download();
  }

  return (
    <Query>
      {data => (
        // data review here
        <button onClick={() => download(data)}>Download PDF</button>
      )}
    </Query>
  )
}

export default withI18n()(ApplicationSummaryScreen);
```

Now in `makePDF.js` I cannot use React components, but regular functions instead.
```
export default function makePDF(data, {t, number}) {

  console.log(
    number(data.property_verified_value, {
      style: 'currency',
      currency: 'EUR',
      minimumFractionDigits: 0,
    })
  )
  // ... other pdf code
}
```
which gives this error
```
core.development.js?264a:446 Uncaught TypeError: Cannot read property 'locales' of undefined
    at number$$1 (core.development.js?264a:446)
```
However, binding the functions to the i18n object fixes the issue
```
export default function makePDF(data, i18n) {
	const t = i18n.t;
	const number = i18n.number.bind(i18n);
  // ...
}
```

I have also tried using the lingui functions via import `import { t, number } from '@lingui/macro';`, but that gives even stranger results (object, instead of a string):
```
"{
 "id": "0,number,number0",
 "formats": {
  "number0": {
   "style": "currency",
   "currency": "EUR",
   "minimumFractionDigits": 0
  }
 },
 "values": {
  "0": "300000.00"
 }
}"
```

**Expected behavior**  

Expected is that destructuring `{t, date, number}` from `i18n` just works, especially when binding is not mentioned in docs.

**Additional context**

- jsLingui version ``lingui --version`` 2.7.0

**Comment by ackvf** [comment]
I wonder, would this avoid the error? Simply removing the destructuring.

```
export default function makePDF(data, i18n) {

  console.log(
    i18n.number(data.property_verified_value, {
      style: 'currency',
      currency: 'EUR',
      minimumFractionDigits: 0,
    })
  )
  // ... other pdf code
}
```

In retrospect, the pattern above kind of resembles `console.log.bind(console)` problem.

**Comment by tricoder42** [comment]
Yes, you're correct. This is normal behavior in JavaScript — value of `this` depends on how method is called, not where the method is defined.

**Comment by ackvf** [comment]
@tricoder42 So I suppose the general advice here is "don't reassign i18n methods, including destructuring"?
Do you think this advice could make it in the FAQ or somewhere? Or perhaps, people can google it here...

**Comment by tricoder42** [comment]
This isn’t related to Lingui. It’s a common JavaScript pitfall which is already documented elsewhere
