### ISSUE TITLE
Developer experience report

### ISSUE THREAD

**Issue by stereobooster** [lingui/js-lingui#412]
**What and why**: I feel like authors don't see the context of some tickets I posted. So my idea is to explain the background behind those tickets and our travel in adapting Linguijs.

**Setup**: we (our team) use CRA2 unejected + React 16.6 + Linguijs 2.7.1.

## Flow

The first issue is that [Flow types doesn't work](https://github.com/lingui/js-lingui/issues/348). [I tried to fix it](https://github.com/lingui/js-lingui/pull/395) but haven't finished. So we end up doing this:

`.flowconfig`:

```ini
[ignore]
.*/node_modules/@lingui/
```

And in source files:

```js
// $FlowFixMe
import { Trans } from "@lingui/macro";
```

## Translation keys

Before I will continue we need to agree on some terminology about translation keys.

### Synthetic keys

When you use some synthetic strings for keys. For example:

```
name_of_view.form.name_of_field
name_of_view.form.name_of_field.hint
name_of_view.form.name_of_field.placeholder
name_of_view.error.missing_input
general.error.unknown
```

**Pros**: you can prevent collisions, you can add some semantics in the name and this way help translators
**Cons**: you need manually support consistency of keys, you need to check if you already have a key for given string or you need to create one, you need naming rules, you need to come up with keys, you can argue about naming on code reviews (because that what developers do). You need to make sure you provide defaults otherwise untranslated keys can go to production

In terms of Linguijs

```js
<Trans id="general.from" />
i18n._(t("general.from")``)
<Plural
  id="confirmationPage.duration.value"
  value={booking.duration}
/>
// I didn't find a way to put id in plural
```

### Defaults as keys

When you use some default text (from mockups) as keys. For example:

```
Credit card number
The number in the front of your card
XXXX XXXX XXXX XXXX XXXX
Please provide all required fields
Unknown error happened, try refresh page
```

**Pros**: you don't need naming rules, very easy to name things. Defaults always present.
**Cons**: some text can be confusing without context, like `XXXX XXXX XXXX XXXX XXXX` in given example, but there are comments generated by Lingui, which can be used as context, also it is possible to use in context editor and something like storybook, styleguidist, cosmos to solve this.

In terms of Linguijs

```js
<Trans>From</Trans>
i18n._(t`From`)
<Plural
  value={booking.duration}
  one="1 hour"
  other="# hours"
/>
i18n._(plural({
  value: value,
  one: "1 hour",
  other: "# hours"
}))
```

### Synthetic keys + Defaults

Combination of approaches above.

**Pros**: Defaults always present.
**Cons**: same as synthetic keys and you will have repeating defaults

In terms of Linguijs:

```js
<Trans id="general.from">From</Trans>
i18n._(t("general.from")`From`)
<Plural
  id="confirmationPage.duration.value"
  value={booking.duration}
  one="1 hour"
  other="# hours"
/>
// I didn't find a way to put id in plural
```

## First try - Synthetic keys + Defaults

Our first concern was to make sure we will not deliver untranslated strings to production, so we want to have at least defaults, that is why we chose `Synthetic keys + Defaults`.

The first discovery is that defaults are not supported for gettext files, which is officially recommended. After some experimenting, we discovered that it works with Linguijs format.

```js
{
  "localeDir": "src/locales/",
  "srcPathDirs": ["src/"],
  "format": "lingui",
  "fallbackLocale": "en"
}
```

Later we discovered that it will work with po files if we add `sourceLocale`

```js
{
  "localeDir": "src/locales/",
  "srcPathDirs": ["src/"],
  "format": "po",
  "fallbackLocale": "en",
  "sourceLocale": "en"
}
```

But also this raises the concern, that [it would be nice to add `#, fuzzy` tag for new translations](https://github.com/lingui/js-lingui/issues/383#issuecomment-435217183).

And we discovered that [some macros treat defaults differently](https://github.com/lingui/js-lingui/issues/404).

## Second try - Synthetic keys

After some time we decided that holding defaults in the source is very cumbersome, and we agreed to use keys alone and always provide defaults in `po` file. [Extract script treats keys as defaults](https://github.com/lingui/js-lingui/issues/405), so we would need to check that defaults are provided during code reviews.

## Third try - Defaults

After poking around we thought that we gonna try Defaults and provide context for translators via different means.

Taking into account how much edge cases we found I believe that this is the way authors use the library.

It generally seems to provide nice developer experience, but with some caveats.

### Silent errors

We use a singleton instance of `i18n` which is available everywhere but initialized with locale and translations only after React Router kicks in. See [example here](https://github.com/stereobooster/react-lingui-example/blob/7831da93d8c6802dce1b87ce10785b3badace143/src/App.js#L8-L29). It means that if the developer will access `i18n.language` or `i18n._` at JS evaluation time (before React) it will silently fail, for example, this is wrong

```js
class App extends Component<{}> {
  errorMessage = i18n._(t`Error`); // this is wrong, i18n is not initialised yet
}
```

Instead, it should be:

```js
class App extends Component<{}> {
  errorMessage = () => i18n._(t`Error`);
}
```

So it would be nice if `i18n` would throw an error in development mode if it is not initialized yet and people try to use it, to amplify the error.

### Babel transform 

Methods which expect babel transform are confusing. We use macros (because we use unejected CRA), but sometimes by accident, we use methods which are meant to be used with transform, for example:

```js
i18n.plural({})
```

This code works fine in development but fails in production. I understand why this happens, but this is very easy to miss.

## PS

Developer experience with macros and default values as keys is dope 👍, but other setups can be a bit hard and confusing. 

You can extract some action items from it if you like, or just close it after reading.

**Comment by tricoder42** [comment]
Hey @stereobooster,
thank you for bringing this up! I'm sorry for lack of attention, but I was very busy in last month.

- Translation keys - this is a really nice summary! It would be great include it in docs, because it contains a lot of valuable info.

- First try - Syntatic keys + Defaults - yeah, the bugs are annoying. I'll take a look.

- Silent errors - In some cases this can't be solved, e.g for defaultProps. It's usually solved using *lazy translations*, when you mark the text for translation but translate it later:

```js
class App extends Component<{}> {
  errorMessage = i18n.lazy(t`Error`); // not implemented, just example

  render() {
    return <div>{i18n._(this.errorMessage)}</div>
  }
}
```

As I said, the problem is with defaultProps when the default prop is lazily translated message, while regular prop is already translated string:

function Message({ msg }) {
  // which one should we use now?
  return msg // for regular props
  return i18n._(msg) // for lazy translation
}

Message.defaultProps = {
   msg: i18n.lazy(t`Hello`) // should be lazy
}

To avoid this problem I'm thinking about this solution:

1. When the catalogs aren't loaded, always return lazy translation. Lazy translation is basically a function, which returns the actual translation when called.
2. When the catalogs are loaded, return translation.

Something like this:

```
function lazy(msg) {
  function translate(values) {
    return i18n._(msg, values)
  }
  
  // serialize function to translated string
  // only works for messages without parameters (values)
  translate.toString = translate

  return translate
}

function Message({ msg }) {
  // msg is either a string (translated message) or a lazy translation and it'll be serialized to string 
  return <div>msg</div>
}

Message.defaultProps = {
   // translation *before* catalogs are initialized, return lazy translation
   msg: i18n._(t`Hello`)
}
```

I have to experiment with this approach a bit, but it seems to work for simple cases. When the message actually needs any parameters, it has to be evaluated inside function and can't be set as a default prop.

- Babel transform - This is the reason I want to use only macros in v3. Plugins might be convenient, but they're more error-prone.

Again, thank you for your patience! I'll do my best to groom the backlog this week.

**Comment by stereobooster** [comment]
No pressure. I'm open source maintainer myself. I know how hard can it be. 

> the problem is with defaultProps

Let's distinguish two cases:

**Static bundles** when we have

```
main.en.js
chunk1.en.js
main.cs.js
chunk1.cs.js
```

**Dynamically loaded translations**

```
main.js
chunk1.js
i18n.en.js
i18n.cs.js
```

So for static bundles `defaultProps` will work, right? Because translation function will be "compiled away". 

But for dynamically loaded translations at the moment of evaluation of JS, there is chance that we don't know current language and we don't have catalogs yet. I thought that simple solution would be:

```js
  _(
    id: string | Object,
    values: Object = {},
    { defaults, formats = {} }: MessageOptions = {}
  ) {
   if (process.env.NODE_ENV === "development") {
     if(this._language === undefined) {
       throw new Error("used before initialised");
     }
   }

//...

  get language(): string {
     if (process.env.NODE_ENV === "development") {
       if(this._language === undefined) {
         throw new Error("used before initialised");
       }
     }
    return this._language
  }
```

So when developer writes

```js
class App extends Component<{}> {
  errorMessage = i18n._(t`Error`); // will throw an error, unless there is SSR where catalog is evaluated first

  render() {
    return <div>{this.errorMessage}</div>
  }
}
```

and instead developer forced to write

```js
class App extends Component<{}> {
  errorMessage = t`Error`;

  render() {
    return <div>{i18n._(this.errorMessage)}</div>
  }
}
```

or 

```js
class App extends Component<{}> {
  errorMessage = i18n.lazy(t`Error`);

  render() {
    return <div>{this.errorMessage}</div>
  }
}
```

**Comment by tricoder42** [comment]
@stereobooster You're right! That should be initial approach to fix this. I was thinking too far ahead, how to handle it automatically.

I'm gonna write down extended roadmap to #344 later this week because few good idea popped up in last few weeks.

Thank you for your feedback! 👍

**Comment by stereobooster** [comment]
One more twist.

Let's assume we added check in development `if (process.env.NODE_ENV === "development") {`. Now when people try to use language before it was setted it will throw. And error message clearly explains what the problem, users understand it and can fix it.

But then they switched to dynamic import and `React.lazy`, so language get setted before components load. So code like this will not throw:

```js
const message = i18n._("adsasd")

// React component
export default function () {
  return <div>{message}</div>
}
```

Or one more case, assume we need to use language in Redux reducers. Theoretically we can't because it is global mutable variable.

And there is one easy solution to this problem, which some developers will not like. Prohibit (at application level, not at library level) to use `activateLocale` more than once e.g. to change language we will need to reload page. Controversial, but on the other side how often user do it? Zero or one time per session, right?

The benefit is that `i18n.language` becomes immutable (it setted once and never changes during application run). We can use `i18n.language` in reducers and `i18n._` at evaluation level.

---

I think we need series of articles in documentation about those kind of things. Like, how to select key scheme, why switching language with reload makes developers life easier, how to organise Developer-Translator workflow. I believe this will remove a lot of struggle

**Comment by tricoder42** [comment]
> I think we need series of articles in documentation about those kind of things. Like, how to select key scheme, why switching language with reload makes developers life easier, how to organise Developer-Translator workflow. I believe this will remove a lot of struggle

💯 Yes! That's exactly what I'm planning once I finish v3.

> And there is one easy solution to this problem, which some developers will not like. Prohibit (at application level, not at library level) to use activateLocale more than once e.g. to change language we will need to reload page. Controversial, but on the other side how often user do it? Zero or one time per session, right?

That's fine. I mentioned it in my talk at [React Conf](https://www.youtube.com/watch?v=soAEB7ltQPk&index=27&list=PLPxbbTqCLbGE5AihOSExAa4wUM-P42EIJ&t=0s) that this limitation could actually solve lot of problems and as you said: in practice you don't change language too often.

> Or one more case, assume we need to use language in Redux reducers. Theoretically we can't because it is global mutable variable.

Why not? You just need to dispatch action everytime language changes. On the other hand I wouldn't store language in Redux store, because it's already in I18n object.

---

What do you think about "implicit lazyness" I described here: https://github.com/lingui/js-lingui/issues/363#issuecomment-445532587?

**Comment by tricoder42** [comment]
Hey @stereobooster, this really looks great!

I can't spend much time before the holidays, but I scheduled day off at work so I can work on Lingui next week.

It would be great to eliminate as much choices as possible, but the problem is that everyone has a slightly different usecase. Having this overview and guide would help users to pick the best option for them. Really nice idea 👍

**Comment by stereobooster** [comment]
I want to repeat there is no pressure from my side. I already using the library and it works for me. I just want to make it better, so I share my ideas. I do not expect it will get priority.

Other idea is to implement this logic as JS library, so it can be reused for frontend and CLI. And create CLI application (`lingui doctor`?) which would be able to detect some answers based on project (`package.json` and `.linguirc`, like if React is present etc).
