### ISSUE TITLE
No messages extracted outside of react

### ISSUE THREAD

**Issue by diegolacarta** [lingui/js-lingui#415]
No messages get extracted when using:

```
import i18n from './utils/i18n'
import {t} from '@lingui/macro';

i18n._(t`hello`)
```

They get extracted when using it like:
```
i18n._("hello")
```

They also get extracted as expected when using a react component:

```
import {Trans} from '@lingui/react';

<Trans>Hello</Trans>
```

any ideas?

**Comment by diegolacarta** [comment]
"@lingui/cli": "2.7.2",
    "@lingui/loader": "2.7.2",
    "@lingui/macro": "2.7.2",
"@lingui/react": "2.7.2",

**Comment by tricoder42** [comment]
Could you please also post your Babel config? Do you have `babel-plugin-macros` enabled?

**Comment by diegolacarta** [comment]
```
{
  "env": {
    "local": {
      "presets": ["@babel/preset-react", "@lingui/babel-preset-react"],
      "plugins": [
        ["@babel/plugin-syntax-dynamic-import"],
        ["macros"],
        [
          "emotion",
          {
            "sourceMap": true,
            "autoLabel": true
          }
        ],
        [
          "react-intl",
          {
            "messagesDir": "./i18n/messages/",
            "extractSourceLocation": true
          }
        ]
      ]
    }
  }
}
```

react-intl in there just while transitioning away from it

**Comment by tricoder42** [comment]
That looks good. Could you also please show how babel transforms the file with i18n? `babel src/file.with.i18n.js`

Finally, does extract work for `Trans` imported from `@lingui/macro` package?

**Comment by tricoder42** [comment]
There's also an example repo with js-macros (no React): https://github.com/lingui/js-lingui/tree/master/examples/vanilla-js Maybe it would help you find the root cause.

**Comment by diegolacarta** [comment]
> That looks good. Could you also please show how babel transforms the file with i18n? `babel src/file.with.i18n.js`
> 
> Finally, does extract work for `Trans` imported from `@lingui/macro` package?

I'm using typescript, following the setup from https://github.com/lingui/js-lingui/blob/master/docs/guides/typescript.rst

I could debug at which point babel plugin is not doing what it should, or if you could point me into where to look that'd help

Trans doesn't work when imported from @lingui/macro:
`<Trans>random text</Trans>`
...
```
> Missing message ID, skipping.
> <Trans>random text</Trans>
```

**Comment by tricoder42** [comment]
Right, so now we now the macros doesn't work.

It would be great to see how transpiled source code looks like. Unfortunately I don't use Typescript, but maybe you run TS before Babel?

**Comment by diegolacarta** [comment]
Also not even this works:
```
import { setupI18n } from '@lingui/core';
import { t } from '@lingui/macro';
const i18n = setupI18n()
i18n._(t`Hello`)
```

**Comment by diegolacarta** [comment]
This is the final code after building with webpack:

Original:
```
import {setupI18n} from '@lingui/core'
import {t} from '@lingui/macro'

const i18n = setupI18n()
i18n._(t`Hello`)
```

Transpiled:
```
! function(e) {
    function r(r) {
        for (var n, i, l = r[0], f = r[1], c = r[2], a = 0, s = []; a < l.length; a++) i = l[a], o[i] && s.push(o[i][0]), o[i] = 0;
        for (n in f) Object.prototype.hasOwnProperty.call(f, n) && (e[n] = f[n]);
        for (p && p(r); s.length;) s.shift()();
        return u.push.apply(u, c || []), t()
    }

    function t() {
        for (var e, r = 0; r < u.length; r++) {
            for (var t = u[r], n = !0, l = 1; l < t.length; l++) {
                var f = t[l];
                0 !== o[f] && (n = !1)
            }
            n && (u.splice(r--, 1), e = i(i.s = t[0]))
        }
        return e
    }
    var n = {},
        o = {
            0: 0
        },
        u = [];

    function i(r) {
        if (n[r]) return n[r].exports;
        var t = n[r] = {
            i: r,
            l: !1,
            exports: {}
        };
        return e[r].call(t.exports, t, t.exports, i), t.l = !0, t.exports
    }
    i.m = e, i.c = n, i.d = function(e, r, t) {
        i.o(e, r) || Object.defineProperty(e, r, {
            enumerable: !0,
            get: t
        })
    }, i.r = function(e) {
        "undefined" != typeof Symbol && Symbol.toStringTag && Object.defineProperty(e, Symbol.toStringTag, {
            value: "Module"
        }), Object.defineProperty(e, "__esModule", {
            value: !0
        })
    }, i.t = function(e, r) {
        if (1 & r && (e = i(e)), 8 & r) return e;
        if (4 & r && "object" == typeof e && e && e.__esModule) return e;
        var t = Object.create(null);
        if (i.r(t), Object.defineProperty(t, "default", {
                enumerable: !0,
                value: e
            }), 2 & r && "string" != typeof e)
            for (var n in e) i.d(t, n, function(r) {
                return e[r]
            }.bind(null, n));
        return t
    }, i.n = function(e) {
        var r = e && e.__esModule ? function() {
            return e.default
        } : function() {
            return e
        };
        return i.d(r, "a", r), r
    }, i.o = function(e, r) {
        return Object.prototype.hasOwnProperty.call(e, r)
    }, i.p = "\x3c!-- server-replace:PUBLIC_PATH --\x3e/";
    var l = window.webpackJsonp = window.webpackJsonp || [],
        f = l.push.bind(l);
    l.push = r, l = l.slice();
    for (var c = 0; c < l.length; c++) r(l[c]);
    var p = f;
    u.push([39, 1]), t()
}({
    39: function(e, r, t) {
        e.exports = t(40)
    },
    40: function(e, r, t) {
        "use strict";
        t.r(r);
        var n = t(38);
        Object(n.setupI18n)()._({
            id: "Hello"
        })
    }
});
```

**Comment by diegolacarta** [comment]
I just tried changing my .linguirc to:
```
{
   "localeDir": "src/locales/",
   "srcPathDirs": ["src/"],
   "format": "po",
   "extractBabelOptions": {
      "plugins": ["@babel/plugin-syntax-dynamic-import", "macros"]
   }
}
```

Adding "macros" it now extracts the message, but doesn't translate it

**Comment by diegolacarta** [comment]
and then finally adding:
"presets": ["@babel/preset-react", "@lingui/babel-preset-react"],

to .linguirc seems to make everything work as expected.

I thought it would picks up my .babelrc from the proyect

**Comment by tricoder42** [comment]
Interesting. What's your project structure? Do you have `.babelrc` right next to the `package.json`? And how do you run the `lingui extract` command?

**Comment by diegolacarta** [comment]
yes, .babelrc is at same level as package.json, and I run lingui extract via npm script: `npm run extract-locales`

**Comment by tricoder42** [comment]
Could you please share minimal example so I can take a look? It should work as you described, pick the config from `.babelrc`

**Comment by diegolacarta** [comment]
will try to reproduce when I find some time

**Comment by ianmartorell** [comment]
I'm having the same issue with `lingui extract` not picking up strings from ``i18n._(t`...`)``. I'm importing `t` from `@lingui/react`, since my project is on React Native and macros don't work (`babel-plugin-macros` tries to import Node standard modules `path`, `os` and `fs`, should it actually work?). The docs don't mention anything about using lingui without macros though, is it possible? This  error is also thrown when I try to use either ``i18n._(t`...`)``, `` i18n.t`...` `` or `i18n._('...')`:

```
TypeError: undefined is not an object (evaluating '_setupI18n.i18n._')
```

Any help is much appreciated.  🙏

**Comment by Hotell** [comment]
I'm facing similar issue. The whole extraction behaves very weird/doesn't work.

**Versions:**

```ts
$ yarn list --depth 0 --pattern @lingui
yarn list v1.13.0
├─ @lingui/babel-plugin-extract-messages@2.8.3
├─ @lingui/babel-plugin-transform-js@2.8.3
├─ @lingui/babel-plugin-transform-react@2.8.3
├─ @lingui/cli@2.8.3
├─ @lingui/conf@2.8.3
├─ @lingui/core@2.8.3
├─ @lingui/macro@2.8.3
└─ @lingui/react@2.8.3
```

- We're using typescript with babel7 , so types are just stripped away, that definitely shouldn't be the cause of this issue
- it's a monorepo project

**config:**

```js
const config = {
  compileNamespace: 'es',
  format: 'minimal',
  localeDir: 'public/locale',
  srcPathDirs: ['src'],
};

module.exports = config;
```

```ts
import React from 'react'
import {Trans} from '@lingui/macro'

// Missing message ID, skipping. <Trans>Continue</Trans>
const App = () => <div><h1>hello</h2><button><Trans>Continue</Trans></button></div>

// Works -> {
  "continue": ""
}
const App = () => <div><h1>hello</h2><button><Trans id="continue">Continue</Trans></button></div>
```

## Additional bugs:

- `Plural` doesn't work with `id`

```ts
import React from 'react';
import { Plural } from '@lingui/macro';

// works
const App = () => {
  return (
    <div>
      /* WORKS ->  
        "{count, plural, one {At least # lower-case letter} other {At least # lower-case letters}}": "{count, plural, one {At least # lower-case letter} other {At least # lower-case letters}}"
      */
      <Plural
        one="At least # lower-case letter"
        other="At least # lower-case letters"
        value={count}
      />
      /* doesn't! 
        it even removes valid translation when run with --clean flag
      */
      <Plural
        id="validator.lowerCase"
        one="At least # lower-case letter"
        other="At least # lower-case letters"
        value={count}
      />
    </div>
  );
};
```

**Comment by tricoder42** [comment]
Hey @Hotell, what's your babel config? It seems you're mixing macros with plugins. You should use either one and not mix them together.

**Comment by tricoder42** [comment]
Ideally please create a repository with minimal example so we can debug the issue quickly.

**Comment by Hotell** [comment]
> what's your babel config? 

```js
 const presets = [
    [
      '@babel/preset-env',
      {
        useBuiltIns: 'entry',
        corejs: 2,
        // Do not transform modules to CJS
        modules: IS_TEST ? 'commonjs' : false,
        loose: true,
      },
    ],
    '@babel/preset-react',
    '@babel/preset-typescript'
  ]

  /** @type {import('babel').BabelConfigOptions['plugins']} */
  const plugins = [
    '@babel/plugin-syntax-dynamic-import',
    ['@babel/plugin-proposal-class-properties', { loose: true }],
    ['@babel/plugin-proposal-object-rest-spread', { loose: true }],
    'macros',
  ]
```

> It seems you're mixing macros with plugins. You should use either one and not mix them together.

I'm not sure I follow

**Comment by Hotell** [comment]
Also `Plural` gets caught when used from `@lingui/react`

**Comment by Hotell** [comment]
> Ideally please create a repository with minimal example so we can debug the issue quickly.

I wished I'd have time for that hah. That's a non trivial request when taking into consideration the size of the project...

**Comment by tricoder42** [comment]
> Also Plural gets caught when used from @lingui/react

If you use macros, definitely don't import `Plural` from `@lingui/react`.

In LinguiJS 2.x (current version), there're two ways how to transform components into ICU MessageFormat - plugins and macros:

**Plugins**:
- add `@lingui/babel-plugin-transform-{js,react}` to `.babelrc`
- import `Trans`, `Plural` and other components from `@lingui/react`
- this approach is deprecated and removed in LinguiJS 3.x

**Macros**:
- add `macros` to `.babelrc`
- import `Trans` and other components from `@lingui/macro`
- preferred and the only supported since LinguiJS 3.x

It seems you're using the second option, `macros`. I just misinterpreted the dependencies.

> I wished I'd have time for that hah. That's a non trivial request when taking into consideration the size of the project...

Well, the problem is somewhere in your configuration. If you look into [`examples`](https://github.com/lingui/js-lingui/tree/master/examples), you'll find working projects. The only way to figure out the problem is create a repository with one file, your babel config and install LinguiJS dependencies. If you don't have time, then I can't help you, sorry.

**Comment by Hotell** [comment]
I'm using `@lingui/macro` with v2 solely. It doesn't work with `Plural` -> strangely enough id does when `Trans` "low level" ICU is used directly `<Trans id={ '{count, plural, one {At least # lower-case letter} other {At least # lower-case letters}}' } />`

I'm gonna try to use v3 and get back here with results ( if there will be any )

In the meantime I appreciate your time and help ✌️.

Cheers

**Comment by tricoder42** [comment]
Unfortunately, the v3 isn't production ready yet :/ See #334 

I'll try to setup the repo this evening. I'm suspicious that it's either Typescript related (LinguiJS uses TypeScript 2.x, not Babel preset) or related to some babel plugins.

**Comment by Hotell** [comment]
> Unfortunately, the v3 isn't production ready yet :/ See #334
> 
> I'll try to setup the repo this evening. I'm suspicious that it's either Typescript related (LinguiJS uses TypeScript 2.x, not Babel preset) or related to some babel plugins.

I appreciate your efforts Tomas, but it's open source... In my experience it should be consumer responsibility to provide demo which simulates described "bug", not the authors. Our time as maintainers is very precious. So please don't waste your time on creating repro. I'll do it, when I find some time today...

cheers 👍

**Comment by tricoder42** [comment]
I know, you’re right. I’m just open-source junkie - when I see a problem I can’t resist solving it. If I weren’t super busy at work right now, I would already start working on it ;)

Let me know if I can further help or clarify something.

Cheers

**Comment by Hotell** [comment]
Hmm so, I've converted weback js/flow/react example to typescript with latest versions of deps. Looks like works there (attached) Check `Form` within `Children.tsx`.

- There are some type errors because 3rd party definitions are not correct... 
- I didn't tried tests ( not important at the moment )
- I might submit PR with this example, WDYT ?

Everything works, hmm. Looks like I don't have `@lingui/babel-plugin-transform-{js,react}` within dependencies at work (as it's not properly stated in the docs ?)


[webpack-react-typescript.tar.gz](https://github.com/lingui/js-lingui/files/3330674/webpack-react-typescript.tar.gz)

>  I’m just open-source junkie - when I see a problem I can’t resist solving it 
I know, been there, don't that. don't do that :D

**Comment by Hotell** [comment]
so after adding `"@lingui/babel-preset-react": "2.8.3",` `Plural` macro works. 

- strange thing is that CLI won't crash when that plugin is missing 👀

**Comment by Hotell** [comment]
Ups so I found the real culprit. 
**`lingui` CLI doesn't work within monorepo...** 

It won't find root  `babel.config.js`. That's why it was behaving so strange all along...

No idea how to solve this situation...

**Comment by Hotell** [comment]
What lingui cli needs to support is:

```
babelOptions: {
    rootMode: 'upward',
  },
```

**Comment by Hotell** [comment]
HA! so actually that's supported already :D 👍 

```
const config = {
extractBabelOptions: {
    rootMode: 'upward',
}
}
```

**Comment by tricoder42** [comment]
Great, I'm glad you've figured it out.

So what's the summary? You have a monorepo, each package has it's own `.babelrc` or they all use the root `babel.config.js`? I'm just asking so I can include it in docs.

Cheers 👍

**Comment by Hotell** [comment]
Yes, one `babel.config.js` within root.

-> `lingui.config.js` within root
-> `lingui.config.js` per package(app) which extends/overrides from root

✌️

![image](https://user-images.githubusercontent.com/1223799/60440575-6557a600-9c15-11e9-8c8e-64b1745a6cac.png)

![image](https://user-images.githubusercontent.com/1223799/60440596-6f79a480-9c15-11e9-8ab0-cf5e5e03744e.png)

**Comment by mschipperheyn** [comment]
I have a monorepo with react and vanilla js using @lingui 2.8.3. No messages are extracted from the vanilla js files.

All my `t` and `Trans` imports are based on `@lingui/macro`.

Any ideas?

Root config
```
const config = {
	compileNamespace: 'cjs',
	format: 'po',
	fallbackLocale: 'pt',
	sourceLocale: 'pt',
	extractBabelOptions: {
		plugins: ['@babel/plugin-syntax-dynamic-import', 'macros'],
		presets: [
			'@lingui/babel-preset-js',
			'@babel/preset-react',
			'@lingui/babel-preset-react',
		],
		rootMode: 'upward',
	},
};

module.exports = config;
```

package config 
```
const rootConfig = require('../../lingui.config');

const config = {
	...rootConfig,
	localeDir: './src/shared/locale',
	srcPathDirs: [
		'src/shared',
		'src/server/modules',
		'../common-lib/src',
	],
};

module.exports = config;
```

**Comment by maktouch** [comment]
Hey @Hotell, 

Just to confirm, did you make this work in a monorepo, in which Components are being translated? 

I'd love to replicate what you did and when I get it working, I'll help @tricoder42 with the documentation.

I'm currently facing a similar problem with monorepos, I can get everything to work except Lingui, and it's crucial to the developer's experience.

**Comment by gpolanco** [comment]
> Hey @Hotell,
> 
> Just to confirm, did you make this work in a monorepo, in which Components are being translated?
> 
> I'd love to replicate what you did and when I get it working, I'll help @tricoder42 with the documentation.
> 
> I'm currently facing a similar problem with monorepos, I can get everything to work except Lingui, and it's crucial to the developer's experience.

I have the same problem, any solution for monorepos?

**Comment by clehene** [comment]
I was able to get the extraction working in a monorepo setup. 
We have multiple applications and shared `common-ui` component library built with rollup.js.
In our case the problem was that we were configuring babel plugins directly through rollup rather than `.babelrc`

I was puzzled about how lignui actually works and then realized it uses `.babelrc` so once I had that (using `macros` plugin) the extraction worked.

Now there's a bigger / more interesting problem remaining.
The component library will have its own catalog and it's unclear what's the right way to get that loaded.

Each app has a global provider:

```typescript tsx
          <I18nProvider
            language={i18nStore.language}
            catalogs={i18nStore.catalogs}>
            <MainContainer />
          </I18nProvider>
```

But then somewhere deeper in `MainContainer` we use a component that comes with its own catalog.
Not sure f `I18nProvider` can be nested, or what's the right way to handle that at component level.

**Comment by cezarneaga** [comment]
Hi Cosmin @clehene ,

did you get this to work somehow? i have the same situation. component library in monorepo. not sure how to get it to work.
thanks,
Cezar
ps: @tricoder42 any input on this?

**Comment by clehene** [comment]
Hey @cezarneaga. Yes we built an adapter. Likely suboptimal, but it works. 
We can contribute it as a helper to lingui-js. Meanwhile I'm posting the code here

```typescript
import { I18nProvider, withI18n, withI18nProps } from '@lingui/react';
import * as React from 'react';

import catalogRo from '../locales/ro/messages.js';
import catalogEn from '../locales/en/messages.js';

/**
 *
 * Similar to Lingui JS `withI18n` but wraps component with an i18n adapter
 * that:
 *  * picks the `language` parameter from the provided `i18n` instance
 *  * changes the i18n catalog to the wrapped component's (internal) one
 *
 * embed-ui        provider(lang1, catalog1) ->
 *  adapter => new provider(lang1, catalog2)
 *
 * TODO use defaults if instance not provided (we'll fail with undefined otherwise
 * TODO load catalog dynamically
 * TODO merge catalog message instead of override?
 *
 * @param Component to wrap
 */

export const withI18nAdapter: <P extends object>(
  Component: React.ComponentType<P>
) => React.ComponentClass<
  Pick<P & withI18nProps, Exclude<keyof P, keyof withI18nProps>>
> = <P extends object>(Component: React.ComponentType<P>) =>
  withI18n()((props: P & withI18nProps) => {
    const language = props.i18n?.language ?? 'en';
    return (
      <I18nProvider language={language} catalogs={catalogs}>
        <Component {...(props as P)} />
      </I18nProvider>
    );
  });
const catalogs = { ro: catalogRo, en: catalogEn };

```

**Comment by tricoder42** [comment]
New version has been released. Please check if the problem persist in the new version.

**Comment by cezarneaga** [comment]
> Hey @cezarneaga. Yes we built an adapter. Likely suboptimal, but it works.
> We can contribute it as a helper to lingui-js. Meanwhile I'm posting the code here

Thanks! would like to try the v3 and see if this is still needed.

**Comment by clehene** [comment]
Is the new behavior documented somewhere? I'd like to track that and change our code if that works.

**Comment by clehene** [comment]
@cezarneaga does 3 work properly? Can we remove the adapter?

**Comment by semoal** [comment]
> @cezarneaga does 3 work properly? Can we remove the adapter?

On v3.x, practically you don't need withI18n for anything, macros work out of the box for example:

```js
t`some translate`
```

and if you need i18n instance, you can directly import it from core
```js
import { i18n } from "@lingui/core"
```

I'll try to find some time tomorrow to build a sample mono-repo with lingui 3 and multiple catalogs 👍🏻

**Comment by clehene** [comment]
That's great. How does it work with shared components libraries. 

In our case we have 

* ui-1 - catalog-ui-1
* ui-2 - catalog-ui-2
* shared-components - catalog-shared-components

There are going to be different instances / catalogs. How do these get reconciled?

**Comment by semoal** [comment]
> That's great. How does it work with shared components libraries that contain catalogs?
> 
> In our case we have 
> 
> * ui-1 - catalog-ui-1
> * ui-2 - catalog-ui-2
> * shared-components - catalog-shared-components
> 
> There are going to be different instances / catalogs. How do these get reconciled?

They get merged by locale internally, you have more information in lingui website on configuration section.

Tomorrow I'll expand this a lit

**Comment by ThulinaWickramasinghe** [comment]
Hi @semoal !

I'm facing a problem similar to this [which I've explained on a different issue](https://github.com/lingui/js-lingui/issues/1157#issuecomment-2782030874).  I found this issue later. But I can't understand the reason for not needing withI18n anymore. We still need to wrap the components with a provider as per the documentation. Shouldn't we?



> > [@cezarneaga](https://github.com/cezarneaga) does 3 work properly? Can we remove the adapter?
> 
> On v3.x, practically you don't need withI18n for anything, macros work out of the box for example:
> 
> t`some translate`
> and if you need i18n instance, you can directly import it from core
> 
> import { i18n } from "@lingui/core"
> I'll try to find some time tomorrow to build a sample mono-repo with lingui 3 and multiple catalogs 👍🏻
