### ISSUE TITLE
Upgrade Flow

### ISSUE THREAD

**Issue by nickluger** [lingui/js-lingui#416]
**Upgrade Flow to latest version**
The newest version of Flow (`flow-bin`) is causing many type errors. The version defined here is 
` "^0.79.1"`, whereas the most current Flow version is `"^0.89.0"`, a gap of ten versions. 

I had no Flow errors using `0.86.0` on my side.

Maybe its time to upgrade?

**Comment by tricoder42** [comment]
Honestly I'm thinking about striping flow completely and potentially moving to Typescript.

`flow-bin` is only a development dependency, so it shouldn't affect your own codebase. If there're any new type errors, I'm not going to fix them probably.

If you wish to fix them, feel free to send a PR.
