### ISSUE TITLE
Flow: I18nProviderProps required language property

### ISSUE THREAD

**Issue by MartinCerny-awin** [lingui/js-lingui#418]
I am passing i18n property to I18nProvider and this object contains language property. I do not want to specify language property again on I18nProvider. Everything works correctly if I do not do so, but flow complains about `property ``language`` is missing in  props`

Possible solutions
1) Change language in I18nProviderProps to optional https://github.com/lingui/js-lingui/blob/master/packages/react/src/I18nProvider.js#L11 
2) create second I18nProviderProps https://github.com/lingui/js-lingui/blob/master/packages/react/src/I18nProvider.js#L9-L18, where i18n is required and language would be again optional. Both types would be used as union type.

The second approach seems safer as the language would be required when i18n is not used.

Which approach is more preferable? 

- jsLingui version 2.7.2

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ server/render.jsx:46:8

Cannot create I18nProvider element because property language is missing in props [1] but exists in
I18nProviderProps [2].

     server/render.jsx
     43│
     44│   const app = (
     45│     <Provider store={store}>
 [1] 46│       <I18nProvider i18n={i18n}>
     47│         <StaticRouter location={req.url} context={{}}>
     48│           <div>
     49│             <Head />
     50│             <App routes={routes} />
     51│           </div>
     52│         </StaticRouter>
     53│       </I18nProvider>
     54│     </Provider>
     55│   );
     56│
```

**Comment by tricoder42** [comment]
I completely trust your judgement and I would go for 2). I'm converting the codebase to Typescript anyway, which will be published in v3. Not sure if it's worth it to fix flow typings at this point.

Thanks for suggestion though, feel free to send a PR if you want to fix it in v2. 👍
