### ISSUE TITLE
Cannot import default instance of I18n

### ISSUE THREAD

**Issue by akkie** [lingui/js-lingui#42]
The documentation states :
> lingui-i18n still exports the default instance of I18n class, this remains unchanged:
```import i18n from 'lingui-i18n'```

But if I try to import it in my tests I get the warning:
```
"export 'default' (imported as 'i18n') was not found in 'lingui-i18n'
```

Same if I try to import the instance in the application itself.

Importing `setupI18n` works as expected.

```
import { setupI18n } from 'lingui-i18n';

const i18n = setupI18n();
```

**Comment by tricoder42** [comment]
Just to clarify, `import i18n from 'lingui-i18n'` throws the error, right?

There's a test case, that default export is defined. Looking at both ES and CommonJS dist files, there's default in both.

I tried:

```js
import i18n from 'lingui-i18n'

describe('i18n import', function () {
  it('should exist', function () {
    expect(i18n).toBeDefined()
  })
})
```

and it works.

- What version of lib do you have?
- What's your environment? Babel, Webpack, Neutrino?

**Comment by akkie** [comment]
Maybe it's because of this [issue](https://github.com/webpack/webpack/issues/706).

Also see: https://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default

**Comment by tricoder42** [comment]
Yes, that's *"correct"*.

In babel, you can use: `import i18n from 'lingui-i18n` (btw it's the same as `import { default as i18n } from 'lingui-i18n'`).

In Node.JS, you have to use `const i18n = require('lingui-i18n').default`, because the whole export looks like:

```js
module.exports = {
   default,
   setupI18n,
   unpackCatalog
}
```

I can't use `module.exports = exports["default"];` because then we would miss `setupI18n` and `unpackCatalog`

**Comment by tricoder42** [comment]
I was thinking about dropping this default export completely, so we get rid of one global object, but that's another topic. I'll check if there's nothing we can do about mixing default and named exports.

**Comment by tricoder42** [comment]
Closing, unfortunately this is common caveat when mixing named and default exports.

I've added named `i18n` export and recommend use it to avoid confusion. Default export will be removed in 2.0.

```js
// ES
import { i18n } from 'lingui-i18n'

// CommonJS
const i18n = require('lingui-i18n').i18n
```
