### ISSUE TITLE
Extract + convert-from doesn't work as expected

### ISSUE THREAD

**Issue by gothy** [lingui/js-lingui#420]
**Describe the bug**
Expected to transform from lingui format to minimal.

**To Reproduce**
Using 2.7.2 version, having an existing setup with default "lingui" format.
```yarn extractTrans --convert-from lingui --format minimal```
gives a warn on the `--format` param and does absolutely nothing to the existing `/locale/<lang>/messages.json` files

**Expected behavior**
`/locale/<lang>/messages.json` files are being converted to "minimal" format.

**Additional context**
I've started using lingui at version 2.7.0 and the default format was "lingui".
The docs say the same, "lingui" is the default.
But there's a section in migration guide 1.x -> 2.x that says "minimal" is the new default format for 2.x version. This is confusing.
Checking out the source code in the master branch gave me an impression that `--convert-from` arg is not used at all during the extraction. 

- jsLingui version 2.7.2
- Babel version babel-core@7.0.0-bridge.0
- Your Babel config 
```json
{
  "presets": ["next/babel", "@zeit/next-typescript/babel"],
  "plugins": [
    "macros",
    [
      "module-resolver",
      {
        "root": ["./"],
        "extensions": [".js", ".jsx", ".ts", ".tsx"],
        "alias": {
          "components": "./components",
          "constants": "./constants",
          "pages": "./pages",
          "styles": "./styles",
          "utils": "./utils",
          "static": "./static"
        }
      }
    ]
  ]
}
```

**Comment by stovmascript** [comment]
I have a similar (maybe the same) problem. I'm trying to convert messages to `po` format after using the `lingui` format from the start. When I set `"format": "po"` in the config and run `npm run extract -- --convert-from lingui`, the files get converted, but are missing all of the translations.

Here's a small repro: https://github.com/stovmascript/lingui-extract-repro with 4 messages.

**Comment by JonesN3** [comment]
It looks to be like the `convert-from` option is broken since v2.3, and in all versions where gettext/po is supported. I ended up writing a script to do the conversion manually.
