### ISSUE TITLE
Interpolation breaking if variable is surrounded by single quotes

### ISSUE THREAD

**Issue by hatton** [lingui/js-lingui#421]
**Describe the bug**
Interpolated variables surrounded by single quotation marks are treated as literal text.

**To Reproduce**

If I compile
```typescript
msg = i18n._(
        t`There is already a ${folderKind} with the name or code '${value}'.`
      );
```
then messages.js has:

```javascript
"There is already a {folderKind} with the name or code '{value}'.":
function(a){return["There is already a ",a("folderKind")," with the name or code {value}."]}
```

Note that "value" has lost its surrounding single quotes and has not been identified as an interpolated value.

One workaround is to use double quotes instead:
```typescript
msg = i18n._(
        t`There is already a ${folderKind} with the name or code "${value}".`
      );
```

which compiles to: 

```javascript
"There is already a {folderKind} with the name or code \"{value}\".":
function(a){return["There is already a ",a("folderKind")," with the name or code \"",a("value"),"\"."]}
```

- jsLingui version 2.7.2
- Babel version babel-core@7.0.0-bridge.0
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)

```json
          {
            loader: "babel-loader",
            options: {
              presets: [
                "@babel/preset-typescript",
                "@babel/preset-react",
                "@lingui/babel-preset-react",

                [
                  "@babel/preset-env",
                  {
                    targets: {
                      // else we get regeneratorRuntime is not defined
                      browsers: ["chrome 61"] // set to match whatever chromium electron is using
                    }
                  }
                ]
              ],
              plugins: [
                "babel-plugin-macros",
                ["@babel/plugin-proposal-decorators", { legacy: true }],
                ["@babel/plugin-proposal-class-properties", { loose: true }]
              ]
            }
          }
```

**Comment by tricoder42** [comment]
Hi @hatton, thank you. I can confirm this is a bug. `extract` works fine, but `compile` is a problem. Interested is sending a PR?

**Comment by hjylewis** [comment]
Try using `''` double apostrophes i.e.
```
"There is already a ${folderKind} with the name or code ''${value}''."
```

The [ICU MessageFormat](http://userguide.icu-project.org/formatparse/messages#TOC-Quoting-Escaping) actually uses `'` as escape characters hence why the text in-between is treated as literal text.

Instead, a pair of apostrophes `''` will be converted to a single one `'`
> A pair of ASCII apostrophes always represents one ASCII apostrophe, similar to %% in printf representing one %, although this rule still applies inside quoted text. ("This '{isn''t}' obvious" → "This {isn't} obvious")
