### ISSUE TITLE
Nested variable translations inside a Trans tag

### ISSUE THREAD

**Issue by pybuche** [lingui/js-lingui#426]
**Is your feature request related to a problem? Please describe.**
Hi,
I cannot figure out what is the best option for me, when I have a translated sentence that carries variable word that has to be translated too.

**Describe the solution you'd like**
Let's say I have something like:
```javascript
import { Trans } from "@lingui/react"

export default function App({ city }) {
   return <Trans>Welcome to {city}</Trans> // `city` being a city name that has to be translated depending on the language you are using
}
```

And I expect the result to be:
```
en: Welcome to London!
fr: Bienvenue à Londres!
```

**Describe alternatives you've considered**
Currently, the only way I found to do it is to use the "outside of React translation" described [here](https://lingui.js.org/tutorials/react-patterns.html#translations-outside-react-components):
```javascript
import { Trans } from "@lingui/react"
import { i18n } from "./App"

export default function App({ city }) {
   return <Trans>Welcome to {i18n._(city)}</Trans>
}
```
`city` being a city name that has to be translated depending on the language you are using.
But it doesn't seem very convenient. 
Is there a better way to do it?

Thanks!

**Comment by tricoder42** [comment]
Hi @pybuche,
this is difficult. For a start, you should create translations for each city. It means the app won't automatically translate the city name (unless you connect to the 3rd party translation service and query the translation at runtime):

```js
const cities = {
  london: t`London`,
  paries: t`Paris`,
  // ...
}
```

Then, what you're doing is actually right. I'm afraid there's no better way.

Tricky thing is that some languages (e.g. Czech) have several grammatical cases, so to be 100% precise, you should provide that information as well and let translators to `select` the proper case:

```js
import { Trans } from "@lingui/react"
import { i18n } from "./App"

export default function App({ city }) {
   return <Trans>Welcome to {i18n._(city, { case: `locative`)}</Trans>
}
```

and then the translation will look like this:

```po
msgid: "London"
msgstr: "{select, case, locative { Londýně } other { Londýn }}" # other cases omitted 
```

I'm afraid there's not much we can do in library to support this pattern, so I'm gonna close this, but feel free to keep discussion. Cheers! 👍

**Comment by pybuche** [comment]
Alright, thanks for your answer!
I agree that it looks difficult, still it seems to me that this is a pattern that can be quite common for large international websites :/

I'm OK with the solution, and anyway I can't see a better option, even with synctactic sugar from a new feature for lingui.

**Comment by pybuche** [comment]
@tricoder42 I tried to implement your solution.

It's fine, but I'm a bit embarrassed about the "define city names in your code" thing.
Currently, I have 2 inputs for my catalogs:
- both french & english catalogs, simple JSON format 
- an SQL table for all my database data that has to be translated

When I initiate my App and my `I18nProvider`, I simplify use this function:
```javascript
import fr from 'conf/locale/fr/messages.json';
import en from 'conf/locale/en/messages.json';

const buildCatalog = translations => ({
    fr: {
        ...fr,
        messages: {
            ...fr.messages,
            ..._.mapValues(translations, 'fr'),
        },
    },
    en: {
        ...en,
        messages: {
            ...en.messages,
            ..._.mapValues(translations, 'en'),
        },
    },
});
```
`translations` being the database translation data.

BUT. Now we not talking about simple strings anymore. I noticed that every "more complex" translation key is transformed into a function (maybe through babel plugin). 
So I have no way to add a row in my SQL table like:
```
                                         en                                    |                    fr                 
{0, select, genetive {London's} other {London}}  | {0, select, genetive {Londres} other {Londres}}
``` 
right?

I could obviously add these keys to my `messages.json`, but then I'd lose the ability to use `--clean` CLI option...
Do you have a better solution for me?

Thanks!
