### ISSUE TITLE
Error in compiling catalog

### ISSUE THREAD

**Issue by martino87r** [lingui/js-lingui#431]
**Describe the bug**
While compiling a simple catalog I'm getting:

```
WARNING in ./src/locales/en/messages.js (./node_modules/@lingui/loader!./src/locales/en/messages.js)
Module build failed (from ./node_modules/@lingui/loader/index.js):
TypeError: Cannot read property 'split' of null
    at createCompiledCatalog (/node_modules/@lingui/cli/api/compile.js:134:30)
    at Object.exports.default (/node_modules/@lingui/loader/index.js:37:41)
 @ ./src/locales lazy ./node_modules/@lingui/loader ^\.\/.*\/messages\.js$ namespace object ./en/messages.js
 @ ./src/js/internalization.js
 @ ./src/js/Root.jsx
 @ ./src/js/router.jsx
 @ multi babel-polyfill ./src/js/router

```

**To Reproduce**
Compile the attached catalog with default settings
[messages.po.txt](https://github.com/lingui/js-lingui/files/2748080/messages.po.txt)

**Expected behavior**
Generated catalog should work out of the box

**Additional context**
Using the lazy variant

- jsLingui version ``lingui --version`` 6.5.0
- Babel version ``npm list babel-core`` 6.26.3 
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)

https://github.com/iroy2000/react-redux-boilerplate

**Comment by martino87r** [comment]
Seems that the loader doesn't work with `po` files but only the older `json` format

**Comment by martino87r** [comment]
No idea why/how but it's working now, closing the issue

**Comment by blasterbug** [comment]
I don't think this should be close, cause it's an actual problem and I just run into it...

**Comment by semoal** [comment]
Feel free to open another issue with your versions, case etc, If we can reproduce the problem, 100% i will help :)
