### ISSUE TITLE
How do you add a link to a t() style message identifier?

### ISSUE THREAD

**Issue by mschipperheyn** [lingui/js-lingui#435]
**Describe the bug**
I use `@lingui/macro`. I can't seem to get a html tag into a translated text element

**To Reproduce**

```
import { Trans, t } from "@lingui/macro"

export default function App() {

    const termsURL = (
		<Link to="/termos" target="_ blank">
			<Trans id="ui.terms" />
		</Link>
	);
    const label = i18n._(t('ui.terms.accept')`I accept the ${termsURL}`);
    return label; // contrived. Label would normally be a label to a component
}
```

This results in: `I accept the [object Object]`

**Expected behavior**
I would expect to be able to include HTML 

As a temporary work around I used 
```
const termsURL = (
		<React.Fragment>
			<span>{i18n._(t('ui.terms.accept')`I accept the `)}</span>
			<ALink to="/termos" target="_ blank">
				<Trans id="ui.terms" />
			</ALink>
		</React.Fragment>
	);
```
but that only works if you can formulate the text in such a way that the link is at the end. Which is not always possible.

**Additional context**
- jsLingui version 2.7.2
- Babel version 7.2.0

**Comment by tricoder42** [comment]
Hi @mschipperheyn,
I'm afraid that's not possible with current implementation. `i18n._` only returns a plain string, while `<Trans>` component can handle inner components.

What about:
```js
<Trans id="ui.terms.accept">
   I accept the <Link to="/termos" target="_ blank">terms</Link>.
</Trans>
```

You could even translate the link to terms and conditions to point it to localized document:

```js
<Trans id="ui.terms.accept">
   I accept the <Link to={i18n._(t('ui.terms.url')`/termos`)} target="_ blank">terms</Link>.
</Trans>
```


The full example would be:
```js
import { Trans, t } from "@lingui/macro"

export default function App() {

    const label = (
	<Trans id="ui.terms.accept">
           I accept the <Link to="/termos" target="_ blank">terms</Link>.
        </Trans>
    );

    return label; // contrived. Label would normally be a label to a component
}
```
