### ISSUE TITLE
NumberFormat (currency) different text on server and client

### ISSUE THREAD

**Issue by tresko** [lingui/js-lingui#436]
**Describe the bug**
I use Next.JS and when I format currency, the NumberFormat component returns different text on a client and a server.

```Warning: Text content did not match. Server: "€ 10" Client: "€10"```
```Warning: Text content did not match. Server: "US$ 10" Client: "$10"```

**To Reproduce**
```
import {NumberFormat} from '@lingui/react'

export default function App() {
   <NumberFormat
        value={10}
        format={{currency: 'USD', style: 'currency', minimumFractionDigits: 0, maximumFractionDigits: 2}}
     />
}

export default function App1() {
   <NumberFormat
        value={10}
        format={{currency: 'EUR', style: 'currency', minimumFractionDigits: 0, maximumFractionDigits: 2}}
     />
}
```

**Expected behavior**
Formatted text must be the same on a server and a client.

**Additional context**

- jsLingui version: 2.7.2
- Babel version: 7.2.2
- Babel config 
```
{
  "presets": [
    "next/babel",
    "@lingui/babel-preset-react",
    "@zeit/next-typescript/babel"
  ],
  "env": {
    "development": {
      "plugins": ["inline-dotenv"]
    },
    "production": {
      "plugins": ["transform-inline-environment-variables"]
    },
    "test": {
      "presets": [["next/babel", { "@babel/preset-env": { "modules": "commonjs" } }]],
      "plugins": ["babel-plugin-import-remove-resource-query", "babel-plugin-dynamic-import-node"]
    }
  },
  "plugins": [
    "babel-plugin-macros",
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-optional-chaining",
    [
      "styled-components",
      {
        "ssr": true,
        "preprocess": false,
        "fileName": true,
        "displayName": true
      }
    ],
    [
      "module-resolver",
      {
        "root": ["./"],
        "alias": {
          "src": "./src",
          "locale": "./locale",
          "static": "./static",
          "pages": "./pages",
          "tests": "./tests",
          "__mocks__": "./__mocks__"
        }
      }
    ]
  ]
}

```

**Comment by tresko** [comment]
I think that I use the default (small-icu).

**Comment by tricoder42** [comment]
You might be missing the locale data. Could you please try with `full-icu` if it resolves the problem?

**Comment by tresko** [comment]
I installed [full-icu](https://www.npmjs.com/package/full-icu) and run the server with  `node --icu-data-dir=./node_modules/full-icu server/app.js`, but this doesn't resolve the problem.

**Comment by tresko** [comment]
@tricoder42 I installed Node v10.15.0 and everything works perfectly. I think, that we can close this issue.

**Comment by tresko** [comment]
Previous Node version was v9.11.1.

**Comment by tricoder42** [comment]
Thanks for the info! Let's keep it open until we mention it in docs.

**Comment by eliseumds** [comment]
I'm using [sebastian-software/lean-intl](https://github.com/sebastian-software/lean-intl) as a polyfill and it works great, but ideally we wouldn't even need it. I just opened an [issue on react-intl](https://github.com/yahoo/react-intl/issues/1234) suggesting that users become able to suppress hydration warnings. Maybe it makes sense for js-lingui too.
