### ISSUE TITLE
Throwing error when using lingui cli with nps

### ISSUE THREAD

**Issue by AOHUA** [lingui/js-lingui#439]
**Describe the bug**
When using nps to run the script, throwing error:
TypeError: Cannot read property 'includes' of undefined

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

inside package-scripts.json 
```
i18n: {
      addLocale: 'lingui add-locale',
      extract: 'lingui extract --clean',
      compile: 'lingui compile',
 },
```
when running scripts with [nps](https://github.com/kentcdodds/nps), throwing error:
TypeError: Cannot read property 'includes' of undefined

**Expected behavior**
Should be able to execute the script

**Additional context**

- jsLingui version `2.7.2`
- Babel version `7.0.0-bridge.0`
- React-native `0.57.6`

**Comment by tricoder42** [comment]
Closed by #441, thank you @AOHUA ⚡️⚡️⚡️
