### ISSUE TITLE
Android bug with NumberFormat : Can't find variable Intl 

### ISSUE THREAD

**Issue by guillaumeLamanda** [lingui/js-lingui#442]
**Describe the bug**
I have a bug with number formating on Android (React-Native). I have the following error : `Can't find variable Intl`. 
I have tried react component (`NumberFormat`) and js way `i18n.number`. 

**Expected behavior**
Formatted number on Android, like it work on iOS. 📱 

I made a minimal snack reproduction of this here : https://snack.expo.io/@glamanda/lingui-android-bug-on-rn 

The lingui project is verry nice, thanks for your work 👏

**Comment by vonovak** [comment]
hi! this is a problem with your react native environment, check out the `Note` in the docs: https://lingui.js.org/tutorials/react-native.html

**Comment by tricoder42** [comment]
@guillaumeLamanda Please let me know if the `Note` in docs by @vonovak doesn't work for you. I'm closing this otherwise.

Cheers 👍

**Comment by guillaumeLamanda** [comment]
Hi all, and thanks for the help !
I have read the note, unfortunally, I was not able to use a custom javascript core because I use standelone app with expo. 
Anyway, I made it work using [intl](https://www.npmjs.com/package/intl), so I am able to use latest release of lingui. 💯 
I updated my snack if someone is struggling on it like I was. 😄 
https://snack.expo.io/@glamanda/lingui-android-with-intl-polyfill

**Comment by lucasriondel** [comment]
@guillaumeLamanda you saved my day. works like a charm (I was having issues with `react-intl` in my react-native app, but it's all gone now !

**Comment by yzalvov** [comment]
The most straightforward way found
```bash
npm install intl
```
```js
import 'intl';
import 'intl/locale-data/jsonp/en'; // or any other locale you need
```

Thanks to [hfossli](https://github.com/hfossli) ([source](https://stackoverflow.com/a/41935101/10234952))

**Comment by fbaralle** [comment]
> The most straightforward way found
> 
> ```shell
> npm install intl
> ```
> 
> ```js
> import 'intl';
> import 'intl/locale-data/jsonp/en'; // or any other locale you need
> ```
> 
> Thanks to [hfossli](https://github.com/hfossli) ([source](https://stackoverflow.com/a/41935101/10234952))

Thanks a lot!! It works just fine with this simple import.

**Comment by alexalannunes** [comment]
> > The most straightforward way found
> > ```shell
> > npm install intl
> > ```
> > 
> > 
> > ```js
> > import 'intl';
> > import 'intl/locale-data/jsonp/en'; // or any other locale you need
> > ```
> > 
> > 
> > Thanks to [hfossli](https://github.com/hfossli) ([source](https://stackoverflow.com/a/41935101/10234952))
> 
> Thanks a lot!! It works just fine with this simple import.

wowwwwww!
Thanks!

**Comment by alexalannunes** [comment]
> The most straightforward way found
> 
> ```shell
> npm install intl
> ```
> 
> ```js
> import 'intl';
> import 'intl/locale-data/jsonp/en'; // or any other locale you need
> ```
> 
> Thanks to [hfossli](https://github.com/hfossli) ([source](https://stackoverflow.com/a/41935101/10234952))

Wowwwwwwww
!Thanks!!!

**Comment by gregdburns** [comment]
It seems like this code could be improved by only loading intl if the Intl object doesn't exist:

`if (typeof Intl === 'undefined') {
  require('intl')
  require('intl/locale-data/jsonp/en')
}`

I'd be curious if anyone sees any potential issues with this.   In this case, it would avoid performance overhead if the Intl object did exist (i.e. iOS).

**Comment by tricoder42** [comment]
@gregdburns Sounds reasonable. Would you like to send a PR to documentation so others can easily find it? [react-native](https://github.com/lingui/js-lingui/edit/next/docs/tutorials/react-native.rst) tutorial might be a good place

**Comment by gryzzly** [comment]
We were able to solve this by updating `android/app/build.gradle` like this:

```
// commented out:
// def jscFlavor = 'org.webkit:android-jsc:+'
// added:
def jscFlavor = 'org.webkit:android-jsc-intl:+'
```

**Comment by SrBrahma** [comment]
> We were able to solve this by updating `android/app/build.gradle` like this:
> 
> ```
> // commented out:
> // def jscFlavor = 'org.webkit:android-jsc:+'
> // added:
> def jscFlavor = 'org.webkit:android-jsc-intl:+'
> ```

This works, but adds 6MiB to the app size (but have all the languages). Does the import option have a smaller app size? I really believe that it does, but just want a confirmation.

**Comment by SrBrahma** [comment]
> > The most straightforward way found
> > ```shell
> > npm install intl
> > ```
> > 
> > 
> > ```js
> > import 'intl';
> > import 'intl/locale-data/jsonp/en'; // or any other locale you need
> > ```
> > 
> > 
> > Thanks to [hfossli](https://github.com/hfossli) ([source](https://stackoverflow.com/a/41935101/10234952))
> 
> Wowwwwwwww
> !Thanks!!!

This intl lib is discontinued, and its last update was on 2016. I think I will stick to the jscFlavor solution.

**Comment by istvan-szilagyi** [comment]
If you don't want to install any package, there is **jscFlavor** variable in the **app/build.gradle**, change that to the following from:

```
def jscFlavor = 'org.webkit:android-jsc:+'
```
to:

```
def jscFlavor = 'org.webkit:android-jsc-intl:+'
```

This way Intl will be included in the JSC.
