### ISSUE TITLE
SSR: Loading i18n bundles on demand, but SSR locale should be loaded sync

### ISSUE THREAD

**Issue by mschipperheyn** [lingui/js-lingui#443]
**Is your feature request related to a problem? Please describe.**
It's more of a 'Not sure if this is possible' / documentation question.

**Describe the solution you'd like**
I use SSR and want to dynamically load locales. I understand about 
```
const catalog = await import(/* webpackMode: "lazy", webpackChunkName: "i18n-[index]" */
		`@lingui/loader!../locale/${locale}/messages.po`);
```

Since the server side rendered bit knows the "current locale", which may vary per user, I want that current locale to be sync loaded instead of async loaded. 

On the React side, I think I'm covered. The SSR HTML gets rendered with the default locale available since the server is a single chunk and whatever chunks are needed are loaded on the fly at the front.

However, I also use `import { setupI18n } from '@lingui/core';` to set up i18n for vanilla javascript `i18n`.
So, here, I'm not sure how to proceed. Since the vanilla javascript `i18n` function is used as a direct import by a number of components. My gut feeling is that I should be able to use `/* webpackMode: "lazy", webpackChunkName: "i18n-[index]" */`@lingui/loader!../locale/${locale}/messages.po`);` in a sync way, using a different `webpackMode`, just not exactly sure how.

**Describe alternatives you've considered**
This is what I have now. 
```
import { setupI18n } from '@lingui/core';

let _i18n = null;

export const loadCatalog = async locale => {
	try {
		const messages = await import(/* webpackMode: "lazy", webpackChunkName: "i18n-[index]" */
		`@lingui/loader!../locale/${locale}/messages.po`);
		// load new catalog
		if (!messages) throw new Error(`Missing messages ${locale}`);
		_i18n.load({
			[locale]: messages
		});
	} catch (err) {
		console.log(`Error loading ${locale}`);
	}
};

const initialize = (locale, messages) =>
	setupI18n({
		language: locale,
		catalogs: {
			[locale]: messages
		},
		missing: (locale, id) => {
			console.warn(`Missing translation ${locale}, ${id}`);
			return id;
		}
	});

function getI18n() {
	if (!_i18n) {
		const initialLocale =
			(typeof window === 'undefined'
				? global.initialLocale
				: window.initialLocale) || 'en';
		const messages = require(`../locale/${initialLocale}/messages`);
		_i18n = initialize(initialLocale, messages);
	}
	return _i18n;
}

export const i18n = getI18n();
```

**Additional context**
Using `Razzle@next` as a basis for my application.
```
"@lingui/core": "^2.7.2",
"@lingui/react": "^2.7.2",

"@lingui/babel-preset-react": "^2.7.2",
"@lingui/cli": "^2.7.2",
"@lingui/loader": "^2.7.2",
"@lingui/macro": "^2.7.2", 
```

**Comment by SleepWalker** [comment]
@mschipperheyn You can convert async imports into sync `require` for node, but it won't work with react, which expects the same tree for the first rendering on server and browser side. So if you want to wait for locales to be loaded on server side, you should do the same on browser side too.

To achieve this you can use something like [react-jobs](https://github.com/ctrlplusb/react-jobs), but the problem is, that this package maintained not that active or directly use [react-async-bootstraper](https://github.com/ctrlplusb/react-async-bootstrapper). The core feature of such libs is that they allow you pre-render your react tree and wait till all async actions will be complete and only render an app.

Another one alternative is to wait till React team will release new version of react, that supports async server rendering (this may take a year).

**Comment by chrischen** [comment]
I haven't tested this yet, but what about using @loadable/components and @loadable/server and then doing the catalog loading in the lazy-loaded component? @loadable should already handle lazy loading while maintaining the SSR/client aspects for you.

**Comment by mschipperheyn** [comment]
I already use `react-async-bootstrapper` so that might be the way to go for me.

**Comment by BramDecuypere** [comment]
@mschipperheyn did you get lingui to work? 
We are currently using gatsby and I'm running into the same issues.

**Comment by mschipperheyn** [comment]
@BramDecuypere I have not had more time to look into this.

**Comment by revskill10** [comment]
I'm using React Suspense for data fetching. Is there any example/guiding to lazy load lingui with Suspense ?

**Comment by max-mykhailenko** [comment]
@mschipperheyn Is it possible to generate several compiled files in different formats. One for SSR with es export, another with window.i18n for client side render?

**Comment by mschipperheyn** [comment]
@max-mykhailenko I never looked at that option. But the docs should be able to point that out.

**Comment by max-mykhailenko** [comment]
I resolve this very easily, dynamic import on client side and simple import for SSR.

**Comment by tricoder42** [comment]
@max-mykhailenko Does it mean this issue can be closed?

**Comment by max-mykhailenko** [comment]
@tricoder42 I'm not an author of the issue, but workaround for my case at least exist.
