### ISSUE TITLE
Can't add Haitian (ht) or Māori (mi)

### ISSUE THREAD

**Issue by aaronshaf** [lingui/js-lingui#445]
```
yarn run add-locale ht
```

Result:

```
Unknown locale: ht.
```

**Comment by aaronshaf** [comment]
Perhaps the make-plural function needs to be wrapped? Compare: https://github.com/messageformat/messageformat/blob/master/packages/messageformat/lib/plurals.js

**Comment by tricoder42** [comment]
As described in make-plural https://github.com/eemeli/make-plural/issues/11, CLDR is missing plural rules for Maori and Haitian. The wrapper would solve the problem as a temporary solution until these languages are added to CLDR.

Do you know what plural rules these languages use? If so, feel free to send a PR. I believe we could have just an object of locale data for each locale and if the locale code doesn't exists in CLDR, we would pull own config.

**Comment by aaronshaf** [comment]
It'd be nice to have a fallback for these situations that doesn't break the whole build (especially in scenarios where we support dozens of other languages).

**Comment by makenosound** [comment]
I’ve bumped into this same issue today too (also for Maori) and it would definitely be nice to have a mechanism for specifying additional custom locales.
