### ISSUE TITLE
How will Lingui react if adding a language using a translation management tool

### ISSUE THREAD

**Issue by ripern** [lingui/js-lingui#446]
In the translation management tool Weblate that I'm using it's possible to add translation for a new language. At the end of [this paragraph](https://docs.weblate.org/en/latest/formats.html#adding-new-translations) in Weblate docs it's mentioned that sometimes the format supports adding a new language without a specific file. However, I'm using the gettext monolingual PO format so Weblate suggests a **.pot** file.
from config:
![image](https://user-images.githubusercontent.com/515357/51908572-80a25900-23ca-11e9-9d27-56b86f4e5267.png)

1. How do I retrieve a .pot file from Lingui?
2. How will Lingui react if there's suddently a new messages.po under src/locales/.. ?  Is add-locale command still needed and if yes, will it handle not overwriting?

Cheers

**Comment by tricoder42** [comment]
1. There's no way to get `.pot` file at the moment. I plan it for next release though. Right now the best thing is to get the plain message catalog without any translations (i.e. add a new locale, which you'll never translate)
2. `add-locale` just creates a new directory with empty `messages.json` or `message.po` file. If you create it manually, there's no difference. When you run `extract`, the catalogs will be merged.
