### ISSUE TITLE
Next React example: loads default locale needlessly?

### ISSUE THREAD

**Issue by osdiab** [lingui/js-lingui#447]
**Describe the bug**
Maybe I'm misunderstanding how `activate` and `willActivate`  are supposed to work, but it seems that the example code will load the `defaultLocale` strings no matter what, even if the page load is for a different locale. That doesn't break anything but it seems inefficient.

**To Reproduce**
1. Clone the repo
1. In the example project, add in the `loadCatalog` function a single line, `alert(locale)`, to alert whenever a locale is loaded.
1. Run example project
1. Navigate to a page that uses a language that is not the default language in that project.
1. `alert` gets called twice, once for each language, although the default language shouldn't be necessary.

**Expected behavior**
I don't think loading the default language should be necessary, which would prevent unnecessarily doing that remote call.

**Additional context**

- jsLingui version ``lingui --version`` 3.0.0-3
- Babel version ``npm list babel-core`` 7.2.2
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.) N/A

**Comment by tricoder42** [comment]
Absolutely, it shouldn't be called twice. This is unstable API which will be most probably redesigned before publishing v3 beta.

Thank you for the report, I'll take a look!
