### ISSUE TITLE
Don't transform сyrillic to unicode by cli command `compile`

### ISSUE THREAD

**Issue by dimensi** [lingui/js-lingui#449]
The compile command transforms all Cyrillic text into Unicode sequences, which greatly increases the size of the code.
![image](https://user-images.githubusercontent.com/11390039/52171654-bbf9aa80-2771-11e9-9205-93813caf222f.png)

english text 9kb, russian 40kb.
![image](https://user-images.githubusercontent.com/11390039/52171635-67562f80-2771-11e9-96b5-6fc791d0d16c.png)

If i keep my text in cyrillic, file size will be 10 kb
![image](https://user-images.githubusercontent.com/11390039/52171668-e8adc200-2771-11e9-9cdf-9967e566c8db.png)

- jsLingui version ``2.7.3``
- Babel version ``7.0.2``

**Comment by tricoder42** [comment]
Hey @dimensi,
this seems to be upstream issue: https://github.com/babel/babel/issues/4909

I think we could at least force UTF-8 characters in message catalogs. Want to take a look and submit a PR?

**Comment by dimensi** [comment]
@tricoder42 
Honestly, I was already thinking about pr, but I didn’t figure out where the code in general gets the text and is saved. So no matter how much I want, I can’t provide pr (

**Comment by dimensi** [comment]
@tricoder42 https://babeljs.io/blog/2016/11/16/6.19.0

**Comment by dimensi** [comment]
@tricoder42, I try set this property, it's not help.

**Comment by dimensi** [comment]
@tricoder42 I read the entire issue of the link you gave. Unfortunately, only 7 versions of babel-generator can fix this. Need add
```
{ minified: true,
jsescOption: {
      minimal: true
    }
}
```

**Comment by dimensi** [comment]
My temporary solution
```
const fs = require('fs')
const path = require('path')

const pathToFile = path.join(__dirname, 'src/locales/ru/messages.js');

const file = fs.readFileSync(pathToFile, 'utf8')

const r = /\\u([\d\w]{4})/gi

fs.writeFileSync(pathToFile, file.replace(r, function (match, grp) {
  return String.fromCharCode(parseInt(grp, 16))
}))

```

**Comment by dimensi** [comment]
@tricoder42 any news?

**Comment by tricoder42** [comment]
The only news related to this issue is that the next version of LinguiJS is going to use Babel 7. I really don't know how to solve it in Babel 6.

**Comment by max-mykhailenko** [comment]
Also have this problem. How I can help to fix it?

**Comment by max-mykhailenko** [comment]
waiting for this!

**Comment by tricoder42** [comment]
@max-mykhailenko Reading comments above, isn't it already fixed in Babel 7? Have you tried the latest LinguiJS version?

**Comment by max-mykhailenko** [comment]
@tricoder42 Oh, I found that yesterday you released 3.0. Is the problem fixed there?

**Comment by tricoder42** [comment]
Please try to upgrade and check. There's also a codemod which makes the upgrade much easier. Unforutnately I don't have any source code with cyrillic

**Comment by max-mykhailenko** [comment]
@tricoder42 May I ask to send me link to codemod?

**Comment by tricoder42** [comment]
Alright, feel free to open a new issue with updated info if the problem still persists
