### ISSUE TITLE
Ability to cut defaults text

### ISSUE THREAD

**Issue by dimensi** [lingui/js-lingui#450]
Now at the moment when we use a custom `id` together with `defaults` text, it helps a lot with `lingue extract`, we thus immediately collect `sourceLocale`, which is very cool, but since in production we later load these languages separately, there is no sense in defaults text , because `sourceLoce` already counts as `defaults` text, but it continues to occupy space in our production build code.

It would be cool if it were possible to remove `defaults` text for production, but it remained in the code for lingue extract.

**Comment by tricoder42** [comment]
This should already work. Here's the [test case](https://github.com/lingui/js-lingui/blob/master/packages/macro/test/fixtures/jsx-trans-production/actual.js) and [transformed output](https://github.com/lingui/js-lingui/blob/master/packages/macro/test/fixtures/jsx-trans-production/expected.js).

Could you please post an example of the code and the transformed output? Do you use macros or plugin?

**Comment by dimensi** [comment]
https://e2f451e4-9fb3-46b2-afb3-97e722c7a6ec.ws-eu0.gitpod.io/
![image](https://user-images.githubusercontent.com/11390039/52216546-8820a100-28a7-11e9-8eaa-39b7c0ca710e.png)
![image](https://user-images.githubusercontent.com/11390039/52216568-966ebd00-28a7-11e9-8727-80889e5ef3aa.png)

**Comment by tricoder42** [comment]
Is it a production build? The default message is only removed when NODE_ENV is set to production.

**Comment by tricoder42** [comment]
Cleaning issues. Feel free to reopen if you have more info.
