### ISSUE TITLE
bash: lingui: command not found...

### ISSUE THREAD

**Issue by omrllm** [lingui/js-lingui#455]
**Describe the bug**

I'm following your guide on the docs and I'm stuck at `lingui extract` in the [extracting messages](https://lingui.js.org/tutorials/react.html#extracting-messages) section but any `lingui` command doesn't work anyway.

In the root of my folder I have .linguirc:

```
{
   "localeDir": "src/locales/",
   "srcPathDirs": ["src/"],
   "format": "po",
   "sourceLocale": "en"
}
```

package.json:

```json
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@lingui/react": "^2.7.3",
    "react": "^16.8.1",
    "react-dom": "^16.8.1",
    "react-scripts": "2.1.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "add-locale": "lingui add-locale",
    "extract": "lingui extract",
    "compile": "lingui compile"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "@babel/core": "^7.2.2",
    "@lingui/cli": "^2.7.3",
    "@lingui/macro": "^2.7.3",
    "babel-core": "^7.0.0-bridge.0",
    "babel-plugin-macros": "^2.5.0"
  }
}

```

**Expected behavior**

`lingui` should work; `npm run extract` and `npm npm run add-locale` work just fine.

**Additional context**

- jsLingui version ``lingui --version`` doesn't work
- Babel version ``npm list babel-core``:

```
├── babel-core@7.0.0-bridge.0 
└─┬ react-scripts@2.1.5
  ├── babel-core@7.0.0-bridge.0  deduped
  └─┬ jest@23.6.0
    └─┬ jest-cli@23.6.0
      ├─┬ jest-config@23.6.0
      │ └─┬ babel-core@6.26.3 
      │   └─┬ babel-register@6.26.0
      │     └── babel-core@6.26.3 
      └─┬ jest-runtime@23.6.0
        └── babel-core@6.26.3 

```

- Create React App

**Comment by cipix2000** [comment]
This is not a lingui issue. If you want to call lingui directly from the CLI you should install it globally (https://yarnpkg.com/lang/en/docs/cli/global/).

Otherwise use 
`yarn extract`
 or 
`./node_modules/.bin/lingui`

**Comment by omrllm** [comment]
Otherwise you can type inside the app folder `npm run` and the command that you want, like `npm run extract` or `npm run compile` instead of `lingui extract` or `lingui compile`.
