### ISSUE TITLE
Plural translation not working with React and po file

### ISSUE THREAD

**Issue by ghost** [lingui/js-lingui#456]
**Describe the bug**

I am not able to translate text using Plural component.

**To Reproduce**

Plural component (from "@lingui/react") is used as this : 
```
<Plural
        value={maxLength - value.length}
        _0="Maximum characters reached"
        one="# character remaining"
        other="# characters remaining"
      />
```
And the po file using `lingui extract` looks like this : 
```
#: src/components/CharacterController/CharacterController.tsx:5
msgid "{0, plural, =0 {Maximum characters reached} one {# character remaining} other {# characters remaining}}"
msgstr ""
```
So I would expect translation to work if I complete it this way : 
```
#: src/components/CharacterController/CharacterController.tsx:5
msgid "{0, plural, =0 {Maximum characters reached} one {# character remaining} other {# characters remaining}}"
msgstr "{0, plural, =0 {Taille maximum atteinte} one {# caracère restant} other {# caractères restants}}"
```

**Expected behavior**
I would expect my text to be properly translated in french.

**Additional context**
- jsLingui version ``2.7.2``
- Babel version ``7.0.0-bridge.0``
- Using Create React App with lingui React package

**Comment by Hotell** [comment]
I was facing similar issues although with `Plural` from `@lingui/macro` 👉 https://github.com/lingui/js-lingui/issues/415#issuecomment-505874642

Make sure you have  `@lingui/babel-preset-react` installed and set within presets within your babel config. That solved my problem


<p>
   <Plural
      id="Inbox.messagesCount"
      value={messagesCount}
      one="There's # message in your inbox"
      other="There're # messages in your inbox"
   />
</p>

**Comment by tricoder42** [comment]
Hey @ghostd, new version 3.x was published recently. Please check if you problem persist in the new version and feel free open new issue with updated example.
