### ISSUE TITLE
Why to use WithI18n instead of i18n object directly

### ISSUE THREAD

**Issue by LFDMR** [lingui/js-lingui#46]
Hi,
I encounter a problem when I use WithI18n, I got the following messages:
``` javascript
./src/App1/routes/Home/components/HomeView.js
Module build failed: SyntaxError: Unexpected token, expected ; (6:45)

  4 | import './HomeView.scss'
  5 | 
> 6 | export const HomeView = WithI18n()({ i18n }) => {
    |                                              ^
  7 |   return (
  8 |     <div>
  9 |       <h3><Trans>Welcome App 1!</Trans></h3>

 @ ./src/App1/routes/Home/index.js 1:0-45
 @ ./src/App1/routes/index.js
 @ ./src/App1/main.js
```

The code is 
``` javascript
import React from 'react'
import { WithI18n, Trans } from 'lingui-react'

export const HomeView = WithI18n()({ i18n }) => {
  return (
    <div>
      <h3><Trans>Welcome App 1!</Trans></h3>
      <img
           src="/static/logos/logo_client.png"
           alt={i18n.t`Logo client`}
           />
    </div>
  )
}

export default HomeView
```

My configuration is:
```
├─┬ babel-preset-lingui-react@1.0.1
│ ├── babel-plugin-lingui-transform-js@1.0.1
│ └── babel-plugin-lingui-transform-react@1.0.1
├─┬ lingui-cli@1.0.4
│ ├── babel-plugin-lingui-extract-messages@1.0.2
│ ├─┬ lingui-conf@0.8.1
├─┬ lingui-i18n@1.1.0
│ └── lingui-formats@1.0.1
├── lingui-react@1.0.2
```
And I use Redux with [this starter kit](https://github.com/davezuko/react-redux-starter-kit)

So I tried `import i18n from 'lingui-i18n'` and everything works.

So why one should use WithI18n ?

**Comment by tricoder42** [comment]
`I18nProvider` uses different instance of `i18n`. When you change language either in `I18nProvider` or `i18n` instance, it won't affect the other.

In your example, you're missing one parenthesis:

```js
export const HomeView = WithI18n()(({ i18n }) => {
//                                ^ parenthesis here 
  return (
    <div>
      <h3><Trans>Welcome App 1!</Trans></h3>
      <img
           src="/static/logos/logo_client.png"
           alt={i18n.t`Logo client`}
           />
    </div>
  )
})  // and here

export default HomeView
```

Maybe it's more readable to decorate default export:

```js
export const HomeView = ({ i18n }) => {
  return (
    <div>
      <h3><Trans>Welcome App 1!</Trans></h3>
      <img
           src="/static/logos/logo_client.png"
           alt={i18n.t`Logo client`}
           />
    </div>
  )
}

export default WithI18n()(HomeView)
```

**Comment by LFDMR** [comment]
So I tried doing this:
```javascript
      <h3><Trans>Welcome App 1!</Trans></h3>
      <h3>{i18n.t`Welcome App 1`}</h3>
```
The first got translated but not the second

Then I tried using the render part of Trans
```javascript
<Trans render={({ translation }) =>
       <img
         src="/static/logos/logo_client.png"
         alt={translation}
         />}>
       Logo client
</Trans>
```
And this worked for the inline translation.

So I wonder how to make something like this work:
```javascript
const getTitle = () => (
    "Welcome App 1!"
  )

  return (
      <h3><Trans>{getTitle()}</Trans></h3>
  )
```
I would have thought to use i18n.

**Comment by LFDMR** [comment]
I tried your version it renders, but unfortunately it does not translate

**Comment by tricoder42** [comment]
> The first got translated but not the second

```js
      <h3><Trans>Welcome App 1!</Trans></h3>
      <h3>{i18n.t`Welcome App 1`}</h3>
```

The first has extra exclamation mark. What about this?

```js
      <h3><Trans>Welcome App 1!</Trans></h3>
      <h3>{i18n.t`Welcome App 1!`}</h3>
```

> Then I tried using the render part of Trans

```js
<Trans render={({ translation }) =>
       <img
         src="/static/logos/logo_client.png"
         alt={translation}
         />}>
       Logo client
</Trans>
```

Yes, that's possible too. I usually prefer `i18n.t` syntax, but sometimes this might work better.

> So I wonder how to make something like this work:

```js
const getTitle = () => (
    "Welcome App 1!"
  )

  return (
      <h3><Trans>{getTitle()}</Trans></h3>
  )
```

Unfortunately, this is not possible. Expressions are not evaluated at compile time, so `<Trans>{getTitle()}</Trans>` would result in message `{0}` and interpolated value of `getTitle()` (so the text would be static, untranslated).

**Comment by LFDMR** [comment]
> So I wonder how to make something like this work:
```javascript
const getTitle = () => (
    "Welcome App 1!"
  )

  return (
      <h3><Trans>{getTitle()}</Trans></h3>
  )
```
I found a way:
```javascript
export const HomeView = () => {

  const getTitle = (useCase) => {
    return (
      {
        foo: <Trans>Welcome App 1!</Trans>,
        bar: <Trans>Hello App 1!</Trans>
      }[useCase]
    )
  }

  return (
      <h3>{getTitle('foo')}</h3>
  )
}
```

**Comment by tricoder42** [comment]
Yes, no problem with that. I still wonder why `i18n.t` doesn't work for you.

> I tried your version it renders, but unfortunately it does not translate

Having this example:

```js
export const HomeView = ({ i18n }) => {
  return (
    <div>
      <h3><Trans>Welcome App 1!</Trans></h3>
      <img
           src="/static/logos/logo_client.png"
           alt={i18n.t`Logo client`}
           />
    </div>
  )
}

export default WithI18n()(HomeView)
```

*Welcome App 1* gets translated, but *Logo client* doesn't? 
Could you please paste your message catalog?

**Comment by LFDMR** [comment]
Yes exactly, same case for the  `{i18n.t'Welcome App 1!'}` with the exclamation mark added.

About that I got a problem with unpackCatalog, I was about to create a new issue.
To make things works I used a quick workaround
So my catalog is like this
```
{
  "Welcome App 1!": "Hi",
  "Logo client": "test"
}
```
And my I18nProvider is like this
```javascript
<I18nProvider language="en" catalogs={{ en: { messages: messages }}}>
      <App store={store} routes={routes} />
    </I18nProvider>
```

**Comment by tricoder42** [comment]
Sounds like a regression. I'll take a look.

Thank you! 👍

**Comment by tricoder42** [comment]
Unfortunately, I'm not able to replicate this bug. There's also an integration [test case](https://github.com/lingui/js-lingui/blob/master/packages/example-usecase/src/Usecases/ElementAttributes.test.js), which isn't failing.

Could you please paste here:
1. Your message catalogs
2. File with `I18nProvider`
3. Component with `WithI18n`

Do you have it in public repository somewhere?

**Comment by LFDMR** [comment]
Yes, I made one, you can find it [here](https://github.com/LFDMR/test-lingui)

You just `yarn install` then `yarn start`
open `localhost:3000`

And you should see _Hi_ and _Welcome!_
The first is from Trans the second from i18n.

**Comment by tricoder42** [comment]
That's awesome! Thank you.

I found the root cause: Tagged template literals were converted to function calls by babel before lingui-react processed them. This is caused by `transform-runtime` plugin, which runs before any presets. If you remove it from webpack and babel config, the translation works fine.

I think you don't need `transform-runtime` if you already have `babel-preset-env` and you put `import "babel-polyfill"` to your `main.js`. `transform-runtime` is useful for libraries, but for apps is `babel-polyfill` enough ([more info](https://codersmind.com/babel-polyfill-babel-runtime-explained/))

Also, if you already have .babelrc in root repository, I would recommend to remove babel config from webpack, so you can keep it in one place only.

**Comment by LFDMR** [comment]
Yes it works. Thank you !

**Comment by tricoder42** [comment]
Cool. Glad it works 👍 

So the last thing in this issue is to document *Why to use WithI18n instead of i18n object directly*.

**Comment by FredyC** [comment]
On the note of the subject, I made a discovery of how to do that. It's a MobX based solution which feels the easier for me, but it can be surely tackled with various other approaches. They key point here is to have a i18nProvider to re-render everything when language changes.

```
import { Catalog, setupI18n } from '@lingui/core'
import { I18nProvider } from '@lingui/react'
import { observable } from 'mobx'
import { Observer } from 'mobx-react'
import React from 'react'

export const i18n = setupI18n()

const currentLanguage = observable.box('') // setting default language here won't work, it's too soon

export const I18nManager: React.SFC = ({ children }) => (
  <Observer>
    {() => (
      <I18nProvider language={currentLanguage.get()} i18n={i18n}>
        {children}
      </I18nProvider>
    )}
  </Observer>
)

export async function changeLanguage(lang: string) {
  await loadCatalog(lang)
  i18n.activate(lang)
  currentLanguage.set(lang)
}

export async function loadCatalog(lang: string) {
  let catalog: Catalog
  if (process.env.NODE_ENV !== 'production') {
    catalog = await import(
      /* webpackMode: "lazy", webpackChunkName: "i18n-[index]" */
      `@lingui/loader!./locale/${lang}/messages.json`
    )
  } else {
    catalog = await import(
      /* webpackMode: "lazy", webpackChunkName: "i18n-[index]" */
      `./locale/${lang}/messages.ts`
    )
  }
  i18n.load({ [lang]: catalog })
}
```

Now you use `import { i18n } from '...'` anywhere in your app. When you want to change the language, just call `changeLanguage`. Similar functionality could be done if you are loading & merging catalogs based on code splitting.
