### ISSUE TITLE
Macros don't work with ts-loader.

### ISSUE THREAD

**Issue by chrischen** [lingui/js-lingui#460]
**Describe the bug**
<Trans>Some Text</Trans> is empty if no `defaults` prop is set.
I'm not totally sure if this is a babel-plugin-macros issue or an issue with lingui.

**To Reproduce**
Use ts-loader in webpack before passing to babel-loader.

Initialize with <I18nProvider> with no props.
```
import { Trans } from "@lingui/macro"



export default function App() {
   return <>
      <Trans>Some Text</Trans> // -> Is empty
      <Trans defaults="default text">Some Text</Trans> // -> `default text` shows
   </>;
}
```

**Expected behavior**
I Expect `Some Text` to render in the absence of a translation.

**Additional context**

- jsLingui version ``lingui --version`` 2.7.4
- Babel version ``npm list babel-core`` 7.3.3
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)
`
{
  "plugins": [
    "@loadable/babel-plugin",
    "@babel/plugin-syntax-dynamic-import",
    "react-hot-loader/babel",
    "emotion",
    "macros"
  ]
}
`
Using an almost fresh instance of ReactQL boilerplate.

Also getting this notice in console.
`@lingui/babel-preset-react is probably missing in babel config, but you are using <Trans> component in a way which requires it. Either don't use children in <Trans> component or configure babel to load @lingui/babel-preset-react preset. See tutorial for more info`

** UPDATE **
I've confirmed that the macro is not working, as the react element is equivalent to calling <Trans> from "@lingui/react". I'm not sure why it's not working, but I feel like it should at least give better errors that the macro isn't working.

**Comment by chrischen** [comment]
I managed to fix it by migrating from ts-loader to babel's support for typescript via @babel/preset-typescript.

**Comment by tricoder42** [comment]
Hey @chrischen, the macros only work with babel right now. There's an [ongoing effort](https://github.com/kentcdodds/babel-plugin-macros/issues/94) to bring macros to TS as well

Feel free to update the macro docs and send a PR or there's even a dedicated guide to using [LinguIJS in Typescript](https://github.com/lingui/js-lingui/blob/master/docs/guides/typescript.rst) projects.

**Comment by chrischen** [comment]
I was using both babel and ts-loader for webpack. I think i can maybe help update the docs with my solution, which was to get rid of ts-loader.
