### ISSUE TITLE
Pseudolocalization fails with exact or offsetting plurals

### ISSUE THREAD

**Issue by redbugz** [lingui/js-lingui#462]
**Describe the bug**
When using exact or offsetting plurals, pseudolocalization fails with an error:
```Error: Can't parse message. Please check correct syntax: "{mēśśàĝēśĆōũńţ, ƥĺũŕàĺ, =0 {Ţĥēŕē'ŕē ńō mēśśàĝēś} one {Ţĥēŕē'ś # mēśśàĝē ĩń ŷōũŕ ĩńƀōx} other {Ţĥēŕē'ŕē # mēśśàĝēś ĩń ŷōũŕ ĩńƀōx}}"```

**To Reproduce**
- Enable pseudolocalization in config
- Add exact or offsetting plurals as documented https://lingui.js.org/ref/message-format.html
- Run `npm run compile`

```
import { Plural } from "@lingui/macro"

export default function App() {
   return <Plural
          value={messagesCount}
          _0="There're no messages"
          one="There's # message in your inbox"
          other="There're # messages in your inbox"
        />
}
```

**Expected behavior**
The plural strings are correctly pseudolocalized

**Additional context**
Appears to be similar to #427, the regex for plurals is tricky to get right

- jsLingui version `2.7.4`
- Babel version `babel-core@7.0.0-bridge.0`
- Create React App

**Comment by redbugz** [comment]
It appears to also fail on DateFormat:
```<Trans>
          Last login on <DateFormat value={lastLogin} />.
        </Trans>```

Now it's a runtime error:
```core.development.js:143 Uncaught TypeError: formatters[type] is not a function
    at ctx (core.development.js:143)
    at LastLoginOnLastLoginDate (messages.js:1)```

<img width="724" alt="image" src="https://user-images.githubusercontent.com/63466/53416694-3db7af00-3991-11e9-81f1-b907ee141201.png">

**Comment by redbugz** [comment]
It also fails on `Select` and `SelectOrdinal`

**Comment by redbugz** [comment]
Could a parser like https://github.com/yahoo/intl-messageformat-parser be used instead of the regex for this purpose? would that make it more robust?

**Comment by olafura** [comment]
I also get a similar error for:
```
i18n._(t`${date(moment(startDate).add(days, 'days').toDate(), {weekday: 'long', day: 'numeric', month: 'long'})}`)`
```
```
msgid "{0,date,date0}"
```

**Comment by MartinCerny-awin** [comment]
I will have a look if I can reproduce this issue

**Comment by tricoder42** [comment]
I believe this is the same bug as #743
