### ISSUE TITLE
Allow pseudolocalization to generate longer strings using `extend` or other options

### ISSUE THREAD

**Issue by redbugz** [lingui/js-lingui#463]
**Describe the solution you'd like**
When using the `pseudoLocale` option, consider using the `extend` and/or `append` and `prepend` options of `pseudolocale` to generate longer strings to help simulate longer languages.

**Additional context**
Pseudolocalization can help developers find layout/clipping/wrapping problems and other issues with longer strings before those longer strings come back from the translators. It would be nice to be able to simulate longer languages than the sourceLocale.

**Comment by MartinCerny-awin** [comment]
I can probably add this functionality to the pseudolocalization library that js-lingui is using

**Comment by tricoder42** [comment]
@MartinCerny-awin Thanks! Definitely go for it
