### ISSUE TITLE
Trans macro results in undefined tag with nested HTML in Preact

### ISSUE THREAD

**Issue by chinchang** [lingui/js-lingui#466]
**Describe the bug**
Undefined tag on the page when using lingui `Trans` macro on nested HTML in a **Preact** app.

**To Reproduce**
Demo: https://codesandbox.io/s/n00p94kz9m
Using `Trans` macro on nested HTML.

Example:
```
import { Trans } from "@lingui/macro"

export default function App() {
   return <Trans>This won't be <span>rendered</span></Trans>
}
```

**Expected behavior**
The nested HTML should have rendered.

**Additional context**
Works fine with react.

- jsLingui version 2.7.4
- Babel version ``npm list babel-core``: 6.26.3
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.): `{ preset: ['preact-cli/babel'], plugins: ['macros']}`

**Comment by ppozniak** [comment]
Noticed the same issue after starting to use `preact-compat`.
The final result of it is `<undefined></undefined>`

**Comment by chinchang** [comment]
I believe it is because of the lack of fragments support in preact 8, which might be required in case of nested HTML. Seems to be working fine with Preact X.
Again, just a guess.

**Comment by tricoder42** [comment]
I have to idea to be honest.

Maybe there's sth specific to `preact` for rendering children/elements. The function for formating elements is in [format.js](https://github.com/lingui/js-lingui/blob/master/packages/react/src/format.js).

I'm not plannig to support Preact anytime soon, as I want to focus on #334.

I'm gonna close this for now. If you figure out the problem, write tests with preact and provide docs how to use LinguiJS with preact, I would be happy to review and merge it 🙏

**Comment by softionsrl** [comment]
Not sure about Preact X, but on Preact 8 using `render` seems to alleviate the issue:

```jsx
import { Trans } from "@lingui/macro"

export default function App() {
   return <Trans render="span">This won't be <span>rendered</span></Trans>
}
```
