### ISSUE TITLE
Correct type for I18n HOC?

### ISSUE THREAD

**Issue by smeevil** [lingui/js-lingui#467]
Hi there,

I'm trying to figure out the correct type for the I18n HOC but it seems to elude me.
Could someone point me in the right direction to replace the 'any' type with the correct one ?

Much obliged :)
Gerard.

```tsx
 <I18n>
  {({i18n}: {i18n: any}): JSX.Element => (
    <Button title={i18n._("Show me!")} onPress={this.handleOnPress}/>
  )}
</I18n>
```

**Comment by cJayyy** [comment]
I would suggest using [@types/i18n](https://www.npmjs.com/package/@types/i18n).

**Comment by smeevil** [comment]
It turned out I was using the i18n imported from @lingui/react while it should have been from @lingui/core...

All is well in the world again :)
