### ISSUE TITLE
How to ignore test files

### ISSUE THREAD

**Issue by dephiros** [lingui/js-lingui#469]
**Is your feature request related to a problem? Please describe.**
- We recently have test that include `Trans` or `t`. Is there a way to exclude `*.test.js(x)*` files from being extracted? I see `srcPathIgnorePatterns` options but that is for folder and not files?

**Describe the solution you'd like**
A way to exclude files that match some patterns

**Describe alternatives you've considered**
Right now, the work around is create a variable that reference by `Trans` or `t`

**Additional context**

**Comment by tricoder42** [comment]
`srcPathIgnorePatterns` are used as regular expressions, so you can match files with them.

**Comment by simlmx** [comment]
In version `4.7.1` I have used something like this successfully:
```javascript
catalogs: [
  {
    ..
    exclude: ['**/*.test.+(tsx|jsx|js|ts)']
  }
]
```
