### ISSUE TITLE
How to use unpackCatalog

### ISSUE THREAD

**Issue by LFDMR** [lingui/js-lingui#47]
Hi I have a problem with unpackCatalog

My catalog is
```
{
  "Welcome App 1!": {
    "translation": "Hi",
    "origin": [
      [
        "src/App1/routes/Home/components/HomeView.js",
        10
      ]
    ]
  },
  "Logo client": {
    "translation": "Best client",
    "origin": [
      [
        "src/App1/routes/Home/components/HomeView.js",
        14
      ]
    ]
  }
}
```

And when I use `unpackCatalog(messages)` I get:
```
{
    "languageData": {}
}
```
The key messages got undefined.

**Comment by tricoder42** [comment]
First you need to compile your catalog using `lingui compile` and then import the generated js file instead of json catalog.

`unpackCatalog` isn't documented very well. I'll add more info to docs.

Let me know if it helps.

**Comment by LFDMR** [comment]
Yes it works !  :+1:

**Comment by tricoder42** [comment]
Closing, as `unpackCatalog` is removed in upcoming major release 2.x
