### ISSUE TITLE
Special handling of Fragment in Plural component

### ISSUE THREAD

**Issue by huan086** [lingui/js-lingui#470]
**Is your feature request related to a problem? Please describe.**
`<Plural>` attributes `one`, `other` and others require that we wrap everything in `<span>`. The localized ICU message becomes `{num, plural, other {<0>There are <1/> items</0>}}`, which is confusing to localize because I'll have to remember to always start and end with `<0>`

**Describe the solution you'd like**
It would be nice to handle `<>` and `<Fragment>` as special case, removing them from ICU message, and adding them back if necessary when rendering. ICU message thus looks like `{num, plural, other {There are <0/> items}}`

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by tricoder42** [comment]
Doesn't it work that way already? Someone on gitter said few days ago that he wrapped message in `<>` fragment. I'm not sure if `React.Fragment` would work as well, but if you're interested, do you want to send a PR?

If yo checkout `next` branch, it could be achieved in macro package here:

https://github.com/lingui/js-lingui/blob/next/packages/macro/src/icu.ts#L83-L105
