### ISSUE TITLE
Compile translation for prod

### ISSUE THREAD

**Issue by brumeregan** [lingui/js-lingui#471]
Hi,
I need some help/advice.
I don't want use compile cli within the project, how can I achieve that all translations with values turn to functions as in dev mode?
For now I created wrapper with precompiled languageData for needed translations and dynamically create catalog with needed LanguageData and as a message I inserting translation.json. But it simply an object without functions..
Any suggestion how can I make it works?

**Comment by dephiros** [comment]
@brumeregan ,
I am a bit unclear about your question so I will try my best:
- If you don't want to use `compile cli` and use webpack, you can use the jslingui webpack loader: https://www.npmjs.com/package/@lingui/loader
- If you don't want the message to be compile at all and just want jsLingui to work with string as in DEV, there is a few tricks that you can do to ship the dev mode to prod: https://gitter.im/lingui/js-lingui?at=5c49dee00a491251e34ae08b or https://gitter.im/lingui/js-lingui?at=5c49e9b37a0f4d5b19ff5742

**Comment by tricoder42** [comment]
`@lingui/loader` is probably what you want.
