### ISSUE TITLE
Performance issues with formatters

### ISSUE THREAD

**Issue by cipix2000** [lingui/js-lingui#472]
**Is your feature request related to a problem? Please describe.**

Lingui takes a lot of time to create number and date formatters, showing in the profiles consuming 25% to 85% of render time. 

This is due to repeatedly creating Number and Date formatters: https://github.com/lingui/js-lingui/blob/master/packages/core/src/formats.js#L31  and https://github.com/lingui/js-lingui/blob/master/packages/core/src/formats.js#L20 , which is a very expensive operation (at least in some browsers - I we tested this in Chrome)

**Describe the solution you'd like**
We'd like to have a API to provide custom number/date formatter so we can use memoized formatters. This is also in the wishlist for Lingui 3, as I can see. 

**Describe alternatives you've considered**

As a temporary solution until we get a proper one we did this: https://github.com/SectorLabs/js-lingui/pull/6 in our fork of lingui

**Comment by queicherius** [comment]
@tricoder42 

This is actually quite a big deal, especially for sites that display a lot of formatted numbers. Reusing the formatter is ~27x faster than recreating it. I recently ran into this issue as well ([small blog post for context](https://blog.david-reess.de/posts/hBEx9w-on-number-formatting-and-performance)) and as a result had to write my own `<NumberFormat />` components for the time being.

**Comment by tricoder42** [comment]
Indeed, this needs to be improved. Thank you @cipix2000 for reporting.

As @cipix2000 said, I want to fix formatters in v3. I want to have an API where you can specify your own formatters (e.g. to use date-fns instead of NumberFormat). As part of this refactoring, I'll make sure the formatter itself is memoized.

I'm not going to fix it in current version, but if anyone were interested I'm happy to review the PR and release a patch/minor.

**Comment by semoal** [comment]
I worked on a solution to this without any external dependency.

The first render of `number("en", 1000)`, will work as normally, but the next (except if the value changes) will be cached in a Map.

I did some testing and passed from 279ms 10000 runs, to a median of 20-30ms 👍🏻 

I'll create the pull request this evening
