### ISSUE TITLE
Reference Error : macro_1 is not defined.

### ISSUE THREAD

**Issue by Noitham** [lingui/js-lingui#473]
**Describe the bug**
I've been trying to set up linguiJS on my app but I get "macro_1 is not defined" error when trying to compile it.
It's a React Native App using TS.

**To Reproduce**
Follow all the installation process.

npm run extract
 -try with a msgstr for test
npm run compile
All seems to work at this point. I get my locales folder with both messages.po and messages.js. There's also a _build folder in it.

examplefile.tsx
```
import { t, Trans } from "@lingui/macro";
import { I18nProvider } from "@lingui/react";

import catalogES from "../../locales/es/messages.js";

const catalogs = { es: catalogES };

export default function App() {
   return <I18nProvider language="es" catalogs={catalogs}>
          ....
          ....
              <Text style={styles.boldText}><Trans>Test</Trans></Text>
         </I18nProvider>
}
```

I've also tried with

```
                                  <I18n>
                                        {({ i18n }) => (
                                            <Button onPress={() => {
                                                this.props.navigation.navigate("Email", { passwordview: "login" });
                                            }} title={i18n._(t`mark messages as read`)}/>
                                        )}
                                    </I18n>
```

But the same result.

**Additional context**

The error I get is:

Reference Error : macro_1 is not defined.

This is how the file inside my dist folder looks

examplefile.js
```
var macro_1 = require("@lingui/macro");
var react_1 = require("@lingui/react");
var messages_js_1 = __importDefault(require("../../locales/es/messages.js"));
var catalogs = { es: messages_js_1.default };

import catalogES from "../../locales/es/messages.js";

const catalogs = { es: catalogES };

export default function App() {
   return (<react_1.I18nProvider language="es" catalogs={catalogs}>
          ....
          ....
              <react_native_1.Text style={styles.boldText}><macro_1.Trans>Test</macro_1.Trans></react_native_1.Text>
         </react_1.I18nProvider>);
}
```

- jsLingui version ``2.7.4``
- Babel version

 ```+-- babel-core@7.0.0-bridge.0
`-- jest@23.6.0
  `-- jest-cli@23.6.0
    +-- jest-config@23.6.0
    | `-- babel-core@6.26.3
    `-- jest-runtime@23.6.0
      `-- babel-core@6.26.3
```

- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)

```
module.exports = function(api) {
    api.cache(true);

    const presets = ["module:metro-react-native-babel-preset", "module:react-native-dotenv"];
    const plugins = ["jest-hoist", "macros"];

    return {
        presets,
        plugins,
    };
};
```

I've runned the following commands too:
```
npm install --save-dev @types/lingui__core  # types for @lingui/core
npm install --save-dev @types/lingui__react  # types for @lingui/react
npm install --save-dev @types/lingui__macro  # types for @lingui/macro
```

**Comment by Noitham** [comment]
Solved issue by switching to Babel TS support, can be closed.

**Comment by ovidius72** [comment]
I'm having a similar issue when i upload the app in release mode. I see the error is y.i18n.t is undefined and y.i18n.t is not a function. Don't know what the y is.
While developing it works fine in the Android Emulator Device and in the physical device.
Any suggestion?
Thanks

**Comment by bullfrognz** [comment]
@Noitham Could you please be more elaborate on what you mean by 'switching to Babel TS support'? I am experiencing the same error and my project is setup to use typescript. Thanks

**Comment by ovidius72** [comment]
@bullfrognz I solved using this `babel.config.js` file:

```
module.exports = {
  presets: ['module:metro-react-native-babel-preset', '@lingui/babel-preset-react'],
  plugins: ['macros']
};
```

install the following dev dependencies:
- "@babel/core": "^7.4.0",
- "@babel/runtime": "^7.4.2",
- "@lingui/babel-preset-react": "^2.7.4",
- "@lingui/cli": "^2.7.4",
- "@lingui/loader": "^2.7.4"
- "@lingui/macro": "^2.7.4"
- "babel-plugin-macros": "^2.5.1",

**Comment by bullfrognz** [comment]
@ovidius72 Thank you for sharing your configuration but unfortunately the error still appears I use the NumberFormat component from @lingui/macro package. Would you please share your tsconfig file? Appreciate the help!

**Comment by ovidius72** [comment]
this is my tsconfig: 
```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "isolatedModules": true,
    "jsx": "react",
    "lib": ["es6"],
    "strictNullChecks": true,
    "resolveJsonModule": true,
    "moduleResolution": "node",
    "module": "commonjs",
    "noEmit": true,
    "strict": true,
    "target": "esnext"
  },
  "exclude": [
    "./node_modules/*",
    "/locale/**",
    "config",
    "babel.config.js",
    "metro.config.js",
    "jest.config.js"
  ],
  "include": [
    "./src/**/*",
    "./typings/**/*.d.ts"
  ]
}
```
I haven't used the NumberFormat so far, so I can't tell if it will work.

**Comment by nogrethumphrey** [comment]
> Solved issue by switching to Babel TS support, can be closed.



> @ovidius72 Thank you for sharing your configuration but unfortunately the error still appears I use the NumberFormat component from @lingui/macro package. Would you please share your tscon

> @Noitham Could you please be more elaborate on what you mean by 'switching to Babel TS support'? I am experiencing the same error and my project is setup to use typescript. Thanks


In webpack configuration,there is no need to use ts-loader.Just use babel-loader is enough.In babel.config.js,add the TypeScript support for babel.    "@babel/preset-typescript". Then babel will be able to handle typescript and macros.

**Comment by kopax-polyconseil** [comment]
I have the same issue when trying to configure `react-native-web` and an ejected `create-react-app` to support Web in [our React Native project](https://github.com/pass-culture/pass-culture-app-native/tree/jest-web). So far, jest cannot use lingui, I keep having this error.

I have tried every advices here, none did work

Any clue why this error keep happening ?

**Comment by kopax-polyconseil** [comment]
@ryan-zheng-teki I am still stuck trying to configure our test, I've opened an issue with reproduction [here](https://github.com/lingui/js-lingui/issues/1092)

So far, I already configured @babel/preset-typescript in the webpack configuration, I am already using babel-loader, I use the babel-plugin-macros. I don't get why but the macro doesn't get properly loaded.

- https://github.com/pass-culture/pass-culture-app-native/blob/jest-web/babel.config.js
- https://github.com/pass-culture/pass-culture-app-native/blob/jest-web/web/config/webpack.config.js#L365

Any clue on how to configure the macros for typescript?

**Comment by Patricknew** [comment]
> @lingui/babel-preset-react

For anyone else looking at this thread, "@lingui/babel-preset-react" has been deprecated from V3. Now it's `macros`.
Reference: https://github.com/lingui/js-lingui/blob/1293412c5dcc565636403443788a5b5d4ca206c1/website/docs/releases/migration-3.md#pluginspresets
