### ISSUE TITLE
allow empty translations, setupI18n not working with I18nProvider

### ISSUE THREAD

**Issue by whytspace** [lingui/js-lingui#475]
Hi,

I don't know if I'm using this correctly, but basically I want to allow translators to leave *translations empty*.
Since my original translation (en) is very likely to change I use IDs only and want to leave the translation completely up to the translators/translation (`po`) files.
When calling "lingui compile" all empty `msgstr`s from the `po` file will automatically be replaced by the IDs. That makes it impossible to leave them empty.

I already looked at https://github.com/lingui/js-lingui/issues/423, but the missing() function never gets called. Seems logically to me since the function is defined at run time, not at compile time.

**Example**

index.js
```
import { setupI18n } from "@lingui/core";
import { I18nProvider } from "@lingui/react";

export default I18n = function() {
const i18n = setupI18n({
    catalogs,
    language: language,
    missing: args => { // never called :(
      console.warn(args);
      return "";
    }
  });

  return <I18nProvider i18n={i18n}>{children}</I18nProvider>;
}
```

component.js:
```
import { Trans } from "@lingui/react"

export default function Dashboard() {
   return <Trans id="dashboard.title" description="Title of dashboard page" />
}
```

locales/**en**/messages.po
```
#. Title of dashboard page
#: src/Dashboard.js
msgid "dashboard.title"
msgstr "My Dashboard"
```

locales/**de**/messages.po
(deliberately left empty by the translator)
```
#. Title of dashboard page
#: src/Dashboard.js
msgid "dashboard.title"
msgstr ""
```

lingui.config.js
```
module.exports = {
  localeDir: "src/locales/",
  srcPathDirs: ["src/"],
  format: "po",
  // sourceLocale: "en", // do not extract anything
  // fallbackLocale: "", // do not fall back
  // pseudoLocale: "pseudo-LOCALE",
};
```
See example here: https://codesandbox.io/s/lpxk7pvw9l
Switch language. "DE" version always shows id instead of nothing.

**Expected behavior**
Allow translations to be compiled to an empty string (maybe by using callback) or make missing() callback work in order to define custom behavior.

- jsLingui version: 2.7.4
- Babel version: babel-core@7.0.0-bridge.0
- Your Babel config: Create React App

**Comment by jorendemaeyer1996** [comment]
Also got the same issue, anyone?

**Comment by en-davidh** [comment]
Is there a solution to this yet? Using version `2.8.3`. Issue is still the same.

I'm just looking for a way to let my translators decide whether to provide a translation in their language or not. If there is any workaround I can try, please let me know.

**Comment by tricoder42** [comment]
Hey @en-davidh, what if you set `fallbackLocale: "en",`? Doesn't it solve your problem? That way you can leave the translation empty, and it's filled with english translation, instead of ID.

**Comment by en-davidh** [comment]
hi @tricoder42. Thanks for the response.

The thing is, that I do not want to fall back to the english version. I want to be able to deliberately set the translation to an empty string.

I tried adding a callback to the `missing` prop on `I18nProvider` but it is never called, since `lingui compile` does not leave any entries "missing". I think this issue could be solved if there was a callback function that lets me modify each entry when running the `lingui compile` command.

**Comment by tricoder42** [comment]
@en-davidh Alright, in that case it's definitely new feature.

Could you please post a short example, how the callback would look like? I guess we could also leave the untranslated messages empty if `sourceLocale` isn't set (in such case, IDs are used).

**Comment by en-davidh** [comment]
it could either be a callback or just a simple flag in config.




Taking a closer look at the source code of `@lingui/cli/lingui-compile.js.flow` I noticed that (on line 91) it calls the `createCompiledCatalog` function with `strict: false`.
```js
const compiledCatalog = createCompiledCatalog(
  locale,
  messages,
  false, // <---- strict
  options.namespace || config.compileNamespace,
  config.pseudoLocale
)
```
I do not know the intention of this parameter but if I change it to `true` it basically does what I need. Relevant code of that function (from `@lingui/cli/api/compile.js.flow`):
```js
export function createCompiledCatalog(
  locale: string,
  messages: CatalogType,
  strict: boolean = false,
  namespace: string = "cjs",
  pseudoLocale: string
) {
  
  // ...

  const compiledMessages = R.keys(messages).map(key => {
    let translation = messages[key] || (!strict ? key : "") // <---- `messages[key]` is `undefined`, so if strict was `true` it would not use the key instead. 
    if (locale === pseudoLocale) {
      translation = pseudoLocalize(translation)
    }
    return t.objectProperty(t.stringLiteral(key), compile(translation))
  })

  // ...
}
```


**So if there was a way to set the `strict` flag via config I guess that would solve the problem.**

Otherwise it could also be a callback that is called from within into the `createCompiledCatalog` function.
```js
  // ...
  const compiledMessages = R.keys(messages).map(key => {
    let translation = messages[key] || (!strict ? key : "")

    // new
    translation = typeof options.transformTranslation === "function" ? options.transformTranslation(translation, messages[key], locale, strict, pseudoLocale) : translation;

    if (locale === pseudoLocale) {
      translation = pseudoLocalize(translation)
    }
    return t.objectProperty(t.stringLiteral(key), compile(translation))
  })
  // ...
```

and in your config config file:
```js
module.exports = {
  // ...
  const transformTranslation = (
    translation: string,
    message: string,
    locale: string,
    strict: boolean,
    pseudoLocale: string,
  ) =>  {
      return locale !== pseudoLocale ? message : translation;
  }
}
```

**Comment by en-davidh** [comment]
Just one more thing I wanted to mention: It seems strange to me that there is a `missing` property on `I18nProvider` but it is never called, since there is no way of setting entries `missing` in a compiled catalog (it always falls back to the id)

**Comment by en-davidh** [comment]
On a second thought, I think that a callback solution might be more flexible than the simple flag.
Using a callback I could implement a way of differentiating between strings that were **deliberately translated as empty** (eg "") and really **missing entries** (not yet extracted/compiled).

It even allows implementing certain *magic keywords* for the translators to use. (eg "<EMPTY>")

**Comment by brettmathe** [comment]
Is there a reason why this feature won't be added?  I also need to intentionally leave certain messages blank.

**Comment by thekip** [comment]
@brettmathe could you provide me with more details about your usecase? I probably could help you with a solution with current code.
