### ISSUE TITLE
Remove opencollective dependency

### ISSUE THREAD

**Issue by mschipperheyn** [lingui/js-lingui#480]
**Describe the bug**
`opencollective` dependency is still part of `@lingui/cli`. It forces the inclusion of `babel/polyfill` 6.23.0, which creates problems in mono repo's with different versions of core-js

**Expected behavior**
`opencollective` from `@lingui/cli` was indicated as removed. But it isn't

**Additional context**

- jsLingui version 2.7.4

**Comment by tricoder42** [comment]
Fixed in `next`
