### ISSUE TITLE
passing strings to Helmet

### ISSUE THREAD

**Issue by cezarneaga** [lingui/js-lingui#485]
Hi lingui people 👋,

experimenting if i can move easyname.com to Lingui. i am getting stuck here:

i need to pass a string to Helmet(react-helmet) and i have this: 
```
title={i18n._(t('common.titleSingle')`Pass for
 <code className="code-sticker txtcolor--tolerance">${state.data.user}</code>`
)}
```
but in this case <code> part is treated as string not markup.
does `t` support something like:

```
title={i18n._(t('common.titleSingle', {
  values: {name: <code className="code-sticker txtcolor--tolerance">state.data.user</code>
})`Pass for {name}`
)}
```

or, is there an alternative?
thanks!
Cezar

**Comment by couds** [comment]
Hi @cezarneaga 

I'm doing this to get it working. I hope this help

```jsx
<I18n>
  {({ i18n }) => (
    <Helmet>
      <title>
        {i18n._(t`Hireflix`)}
      </title>
    </Helmet>
  )}
</I18n>
```

**Comment by cezarneaga** [comment]
i was thinking about it all wrong.
