### ISSUE TITLE
Semi scrambled text to find problems with translations

### ISSUE THREAD

**Issue by olafura** [lingui/js-lingui#488]
This project is doing it for linux apps:
https://github.com/hadess/gettext-pseudolocale

It references:
https://github.com/combatwombat/Lunicode.js

This might be a nice debug feature.

**Comment by tricoder42** [comment]
There's already pseudolocalization in LinguiJS - https://lingui.js.org/tutorials/cli.html?highlight=pseudolocalization#pseudolocalization

The documentation could be definitely better though.

Feel free to send a PR if you would like to improve it! Thank you 🙏
