### ISSUE TITLE
One default message for multiple keys

### ISSUE THREAD

**Issue by filipcro** [lingui/js-lingui#490]
**Is your feature request related to a problem? Please describe.**
I have many forms in my application. Some of them have email field. Now if I want to specify a default message and custom key I need to use `<Trans id="auth.email">Email</Trans>` every time.

If i use `<Trans id="auth.email">Email</Trans>`, I can't use `<Trans id="auth.email" />` anymore because extract command will throw error:
```
Error: Encountered different defaults for message auth.email
src/components/auth/ForgottenPasswordForm.js:27 undefined
src/components/auth/LogInForm.js:36 Email
(...)
```

**Describe the solution you'd like**
I'd like that once default not-undefined value is specified, it overrides all `undefined` ones. This will simplify translations and minimize code repetition.

**Comment by tricoder42** [comment]
Hi @filipcro, thank you for reporting. Indeed, there's a bug on this line:

https://github.com/lingui/js-lingui/blob/df10717743f38c3bb4336c54327d211729b4a11b/packages/cli/src/api/extract.js#L25

Would you like to send a PR? Thank you 🙏

**Comment by filipcro** [comment]
Sure, I'll fix it.
