### ISSUE TITLE
Interpolation doesn't work on fallback locale in production mode

### ISSUE THREAD

**Issue by ppozniak** [lingui/js-lingui#491]
Connected to:
https://github.com/lingui/js-lingui/issues/385

**Describe the bug**
Given I'm using webpack in production mode and    "fallbackLocale": "en" is set in .linguirc
Given a trans component with some variable:
```javascript
<Trans> Hello {name} </Trans>
```
When using i18nProvider and `setupI18n`
```javascript
const catalogs = { en: enCatalog };
export const i18n = setupI18n({ catalogs, language: DEFAULT_LOCALE });

// ===
// Please note language is dynamic here, as it's taken from session config
      <I18nProvider
            i18n={i18n}
            language={sessionConfig.locale || DEFAULT_LOCALE}
            catalogs={catalogs}
          >
```
When language is set to existing catalog (en), everything works fine.

But when language is set to non existing catalog (let's say **es**), then interpolation won't work and "Hello {name}" will be rendered.

**Expected behavior**
It should interpolate strings, even if given catalog doesn't exists (given that **fallbackLocale** is set)

**Additional context**

- jsLingui version 2.7.4
- Babel version babel-core@7.0.0-bridge.0 + "@babel/core": "7.3.4",
- Your Babel config
```javascript
{
  "presets": ["@lingui/babel-preset-react", "@babel/preset-env", "@babel/preset-react"],
  "plugins": [
    "@babel/plugin-syntax-export-default-from",
    "@babel/plugin-proposal-class-properties",
    "babel-plugin-jsx-control-statements",
    "macros",
    "react-hot-loader/babel",
    [
      "module-resolver",
      {
        "root": ["./src"],
        "alias": {
          // Aliases here
        }
      }
    ]
  ]
}
```

**Comment by tricoder42** [comment]
Hi @ppozniak,
unfortunatelly this is "expected". Since the messages are compiled at build time, there's no runtime parser and you can't format messages (e.g. default ones) at runtime.

Next version will probably support optional runtime parsing.
