### ISSUE TITLE
Placeholders are shown in the build version

### ISSUE THREAD

**Issue by AOHUA** [lingui/js-lingui#493]
**Describe the bug**
I tried to set up lingui with create-react-app 2.0 following the document [here](https://lingui.js.org/tutorials/setup-cra.html)

However, when I run dev server it works fine, but after I build the project and host it with http-server, all the placeholders are displayed  on the page instead of the translations.

For example that I have messages as below:
`
msgid "Edit {a} and save to reload."
msgstr "Edit {a} and save to reload."
`

`
const a = 'abc';
<Trans>
       Edit {a} and save to reload.
  </Trans>
`

it should show `Edit abc and save to reload.` but it shows `Edit {a} and save to reload.` instead.
**To Reproduce**

```
import React from 'react';
import logo from './logo.svg';
import { I18nProvider } from '@lingui/react'
import { Trans } from '@lingui/macro';
import './App.css';
const a = 'abc';
function App() {
  return (
    <I18nProvider>
      <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          <Trans>
            Edit {a} and save to reload.
          </Trans>
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Hello
        </a>
      </header>
    </div>
    </I18nProvider>
  );
}

export default App;
```

**Expected behavior**
It should show the translation instead of the placeholder.
**Additional context**

- jsLingui version: `6.7.0`
- Babel version: `babel-core@7.0.0-bridge.0`
- Create React App

**Comment by AOHUA** [comment]
This issue disappeared after I reinstalled node modules.

**Comment by josh-stevens** [comment]
I noticed this happen locally a week ago. I saw this issue and reinstalled my node modules and it seemed to resolve itself. But it came up again in our deployment environment.

I will do a little more investigating to see why this might be coming up in our environment. I really like the way this library works compared to other intl libraries so I'd rather not switch out if I can help it.
