### ISSUE TITLE
Invariant Violation: "Minified React error #130;

### ISSUE THREAD

**Issue by cezarneaga** [lingui/js-lingui#495]
**Describe the bug**
everything works fine in development. crashes mysteriously on production builds.

Can't really repro, but i cansay that i dont have wrong exports and imports correspondents.
same code worked before lingui so cannot understand what could be so messed up. 

- jsLingui version  2.7.4
- Babel version 
```├── babel-core@7.0.0-bridge.0
└─┬ webpack-monitor@1.0.14
  └─┬ babel-core@6.26.3
    └─┬ babel-register@6.26.0
      └── babel-core@6.26.3```

- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)
```module.exports = {
  presets: ['react-app'],
}```

tried everything in babel changes also.
thanks
C

**Comment by tricoder42** [comment]
Please share at least code snippet which fails, otherwise I really can't help. There were several issues with production build, so try to search them.
