### ISSUE TITLE
How to build i18n for React outside `src`?

### ISSUE THREAD

**Issue by benel** [lingui/js-lingui#496]
Thank you for this great tool.

A student of mine used your tool and library to internationalize a Web-Extension implemented with React. She used the [recommended settings for React](https://lingui.js.org/tutorials/setup-cra.html#install):

```json
{
  "localeDir": "src/locales/",
  "srcPathDirs": ["src/"],
  "format": "po",
  "sourceLocale": "fr"
}
```

However, I'm a bit puzzled by the path of generated files:

    src/locale/_build/
    src/locale/**/*.js

I first thought about a misunderstanding in settings. But it seems to be [documented that way for git exclusions](https://lingui.js.org/guides/excluding-build-files.html#git).

Am I missing anything? Is there a way to let Linguijs build the files outside `src/`?

**Comment by tricoder42** [comment]
Hi @benel,
files are build inside `localeDir`, but that will also move the message catalog files. So with `localeDir` set to `locales/` you'll get:

```
locales/
   _build/
      ...
   en/
      messages.json
      messages.js
   fr/
      messages.json
      messages.js
src/
   ...
```

**Comment by benel** [comment]
Thank you @tricoder42!
 
If I understand rightly, I could have: 
- `src` for my existing source files,
- `build` for my existing builded files,
- `locales` with both LinguiJS source files (`.po`) and LinguiJS build files (`.js` and `.json`),

but there is no way to put LinguiJS source files in `src/locales` and LinguiJS build files in `build/locales`, right?

Is it already a suggested (or planned) feature?

**Comment by tricoder42** [comment]
Yeah, you're right.

It's probably related to #326, but this usecase wasn't considered. I'll keep it in mind, once I resume work on that PR. Feel free to add any feedback on suggestions there.

Thank you 👍

**Comment by OnkelTem** [comment]
So does this all mean that documentation is misleading regarding the appropriate location of the `locale` dir? It recommends to use just `locale` in the project root, but CRA will never be able to include anything outside of `src`, which means the the default location of must be `src/locale`, right?
