### ISSUE TITLE
RelativeDateTime component

### ISSUE THREAD

**Issue by queicherius** [lingui/js-lingui#50]
First off, thanks for this project. It's pretty much exactly what I wished for while being significantly smaller than other implementations.

```js
const date = new Date(new Date() - 30 * 1000)
magic(date) -> '30 seconds ago'
```

Is there any way (now or planned) to format a date as a relative time string? Or is there another preferred way of dealing with these - I am thinking about a custom component and translation messages?

Or to word it differently, if you think that its best dealt with with a custom component, would you be interested to have something like that in the docs?

**Comment by tricoder42** [comment]
Hello,
yes I'm thinking about it. For now it might be enough to create custom component in your project.

I need to solve a related problem before implementing it in jsLingui or other package: How to release localized 3rd party components. Sth like namespacing for localized messages (#14). 

`react-intl` suffers few problems with FormatRelative - you can't change wording of messages and you have to load messages provided by library even when you're not using FormatRelative component. It's few bytes for one component, but I imagime we would like to add more components with predefined translations, so you could just import them in your project without need to translating them on your own.

It would be definitely great to mention it in docs. Probably section like *Releasing localized components* or something similar.
