### ISSUE TITLE
Message files splitting

### ISSUE THREAD

**Issue by tricoder42** [lingui/js-lingui#503]
It seems that one unsolved problem in JavaScript internationalization is automatic splitting of message files, similar to code splitting.

I would like to tackle this problem in v3 and figure out, what API changes we need to make to get it done.

Related issues: https://github.com/lingui/js-lingui/issues/474 https://github.com/lingui/js-lingui/issues/362

---

Code splitting creates main bundle with loader and then smaller chunks, which can be loaded separately. We know, what modules are included in each chunk (webpack stats data) and we know, what messages are included in each module (origin of message in lingui catalogs). Therefore we can determine what messages are included in each chunk and generate message files for each chunk.

As with code splitting, even locales need to have main bundle, which will include locale specific data like plural rules, date/number formats, etc.

The only question is, how to load chunks of message files.

Webpack handles loading of code chunks automagically (== I have no idea how it works). When we type `import "module"` and the module isn't loaded yet, webpack automatically loads the correct chunk.

We can't do that with locales. Usually, we would write `import "locale/en.json"`, but that would load whole catalog. In fact, we need just `import "locale/en.acf422.json"`, but that filename is generated automatically. We probably need to hook into webpack require and when chunk `xyz` is loaded, then locale `locale/en.xyz.json` must be loaded as well.

Finally, the last piece in puzzle - once we have locale chunks loaded automatically, we need to load them into Lingui object.

---

**Notes**

While trying to figure out how to load message catalog automatically with code chunk, I discovered [`next-client-pages-loader`](https://github.com/zeit/next.js/blob/canary/packages/next/build/webpack/loaders/next-client-pages-loader.ts) from Next.js, which injects some extra code to generated chunk.

We need to either override default webpack require or call another require before/after chunk is loaded, so adding extra code to generted bundle might be related.

---

Checklist:

- [ ] Generate locale files for each chunk
- [ ] Figure out, how to hook into webpack's require and load locale chunk along with code chunks
- [ ] Figure out how to feed loaded locale chunks into Lingui

**Comment by theKashey** [comment]
1. ✅Extract messages from the source code.
2. ✅Build the app
3. Add plugin, tap on the compilation emit, to analyze how modules are distributed in chunks ( stat.json)
4. Form the same "chunks" from translated messages, these translations-per-chunks could be added into webpack emit as well.
5. Add another plugin, to hook into `__webpack_require__.e`(requireEnsure) (like `mini-css-extract-plugin` does) to load translation the translation chunk next to the code chunk.

**Comment by theKashey** [comment]
* selected for development :)

**Comment by maleetz** [comment]
Could this be as simple as modifying the `compile` process to emit modules per catalog + automatically generated modules containing translations that are shared between catalogs? After that point, webpack could handle bundling it correctly with the application and we wouldn't need a plugin at all.

Assumptions:

- Catalogs are defined by user to specify "entry points". Users would then include `locales/en/[catalog].js` into their application.
- A single PO file is used to manage all translations (This may be different that the current RFC for catalogs, in which case perhaps we could support both with a different name for this case)

An example:

### Configuration
./locales/en/messages.po
```
#: packages/A/ComponentA.tsx:1
msgid "A"
msgstr "A"

#: packages/B/ComponentB.tsx:1
msgid "B"
msgstr "B"

#: packages/A/ComponentA.tsx:2
#: packages/B/ComponentB.tsx:2
msgid "AB"
msgstr "AB"
```

./package.json
```
{
   "lingui": {
      "catalogs": {
         "packages/A",
         "packages/B"
      }
   }
}
```

### Compiled
./locales/en/[chunk-id]/messages.js
```
modules.export = {
  messages: {
    "AB": "AB"
  }
};
```

./locales/en/A/messages.js
```
const { messages } = require('../[chunk-id]/messages.js');

modules.export = {
  messages: {
    ...messages,
    "A": "A"
  }
};
```

### Usage
Then an application using both A + B packages could do the following:
```
import A from './locales/en/A/messages.js'
import B from './locales/en/B/messages.js'
import { combineCatalogs } from '@lingui/core'

export combineCatalogs(A, B);
```

The application could also lazy load A/B messages as needed.

**Comment by renchap** [comment]
Still valid I think :)

**Comment by semoal** [comment]
Probably this feature could be a nice one on a 3.1.0 of lingui, @tricoder42 if you have some time to open other issue to write a little roadmap of 3.1.0, I could help as much as I can 👍🏻

**Comment by tricoder42** [comment]
@semoal I've just created a milestone and added two new possible features.

This issue isn't trivial because it depends on the framework. I would start with Next.js because it's closer to me. Just clarify — we're talking about splitting the compiled catalog, not the source one. We can already split the source catalog using `catalogs` attribute and, to be hones, even one large source catalog isn't an issue. The problem is when you send such large catalog to the client, which potentially might explode the bundle size.

It would be great, if we could split the catalog based on generated chunks, but I have no idea how to hook into Webpack. @ScriptedAlchemy mentioned *module federation* [yesterday](https://github.com/lingui/js-lingui/issues/508#issuecomment-718383443).

**Comment by hectorcoronado** [comment]
Hi @tricoder42, jr. dev here, so bear with me please. I'm working with two different repos, both are React-based, but one is an app with redux, whereas the other is a component library without redux that other apps leverage. Both make extensive use of the `<Trans />` component, as well as the `_t()` macro in order to translate strings. I've been able to code-split/dynamically load catalogs in in the app by following the [docs](https://lingui.js.org/guides/dynamic-loading-catalogs.html) and making a slight modification such that the catalog is made available to the redux store (the `updateCatalog` action does that):

`I18nLoader.js` in the app:

```javascript
import React, {Component} from 'react';
import {connect} from 'react-redux';
import {I18nProvider} from '@lingui/react';

import {getI18n} from '../../configurei18n';
import {updateCatalog} from '../../actions/settingActions.js';

const i18n = getI18n();

export class I18nLoader extends Component {
  state = {
    catalogs: {},
    language: this.props.language,
  };

  loadCatalog = async (language) => {
    const catalog = await import(
      /* webpackMode: "lazy", webpackChunkName: "i18n-[index]" */
      `../../locales/${language}/messages.js`
    );
    i18n.load({[language]: catalog});
    i18n.activate(language);
    this.props.updateCatalog(catalog);
    this.setState((state) => ({
      catalogs: {
        ...state.catalogs,
        [language]: catalog,
      },
    }));
  };

  componentDidMount() {
    this.loadCatalog(this.props.language);
  }

  shouldComponentUpdate(nextProps, nextState) {
    const {language} = nextProps;
    const {catalogs} = nextState;

    if (language !== this.props.language && !catalogs[language]) {
      this.loadCatalog(language);
      return false;
    }

    return true;
  }

  render() {
    const {children} = this.props;
    const {catalogs, language} = this.state;

    // skip rendering if catalog is not loaded
    if (!catalogs[language]) return null;

    return (
      <I18nProvider i18n={i18n} language={language} catalogs={catalogs}>
        {children}
      </I18nProvider>
    );
  }
}

const mapStateToProps = ({appSettings}) => {
  return {
    language: appSettings.language,
  };
};

export default connect(mapStateToProps, {updateCatalog})(I18nLoader);

```

...and `configureI18n.js`/the rest of the app wherever we're using `_t()` gets access to the catalog/outside of React-land via the store:

```javascript
import {setupI18n} from '@lingui/core';

import {store} from './configureStore';
import memoize from 'lodash/memoize';

// load language strings
const getI18n = memoize(
  () => {
    let getStore = store.getState();
    let useLang = getStore.appSettings.language;
    let catalog = getStore.appSettings.catalog;
    let getStrs = setupI18n({
      language: useLang,
      catalogs: {[useLang]: catalog},
    });

    return getStrs;
  },
  () => store.getState().appSettings.language
);

export {getI18n};
```

I have thus far been unable to recreate the same effect in the non-redux component library; everything in React dynamically loads properly, but not in the `_t()` macro. I have tried the following approaches:

* instead of making the catalog available via redux, make it available in `localStorage`, then getting it in the component library's `configureI18n.js` file and passing it into the `setupI18n` function there. This fails silently.
* doing the same as the previous bullet point, but instead of passing the catalog directly to the `setupI18n` function, setting that function to an `i18n` variable, then calling `i18n.load(lang, catalogFromLocalStorage)`. I get a `Message catalog for locale "es_MX" not loaded.` (for example) warning. 
* make the `getI18n` function async and dynamically load the catalog in the component library's `configureI18n.js`/`setupI18n()`. This fails with an `I18n.load is not a function` error coming from the `<I18nLoader />` component.

There's something I'm not getting here, clearly, and I'm wondering if you could please provide some insight?

**Comment by semoal** [comment]
Hi @theKashey , since we have right now version 3.X.X. really clean, we released some interesting new features and some hot-fixes so probably the next milestones are reasonably clean. 

If you can provide some details of what you got, I'm open to help you or start working on it. This feature will be amazing.

**Comment by semoal** [comment]
> There's something I'm not getting here, clearly, and I'm wondering if you could please provide some insight?
Feel free to open another issue if you found something not working correctly 👍🏻

**Comment by theKashey** [comment]
@semoal - all I've got is in the comment above. The general idea is to extract "translations" in the same way some CSS-in-JS do a static extraction, producing CSS files from js ones.
The only difference that such files have to pull translation from the other source and (optional) support runtime language selection.

**Comment by micahbule** [comment]
Any particular update on this if we can already do this or if there's any existing workaround?

**Comment by JSteunou** [comment]
until having it all automatic hooked on build split feature from webpack or other builders, could it be possible to add this feature through a naive implementation with *namespace* concept. On every call to Trans / t adding a *namespace* parameter which will be used to split the catalogue files. 

To avoid boilerplate maybe some configuration could be added to automatically set this namespace for all files in some folder.

Loading the appropriate catalogue would still be manual though but nothing too difficult nor painful...

What do you think?

**Comment by semoal** [comment]
It's a good idea if you want to collaborate @JSteunou, we're open to collaborations.

**Comment by JSteunou** [comment]
My hands are full but if at some point we are in the need of this feature at work I might sell it to be able to work on it on work time. But that could take years because the todo list is already huge so if someone want to tackle it before, go.

**Comment by SanichKotikov** [comment]
Hi,

Is there any way to extract messages separately for different pages(folders)? For example, I have next project structure:

```
/src
  /_common
  /page1
  /page2
  /...
```

and I want to get next jsons (with messages):

```
/locales
  /_common
    /en.json
    /fr.json
  /page1
    /en.json
    /fr.json
  /page2
    /en.json
    /fr.json
```

**Comment by JSteunou** [comment]
nooo stale bot please keep it up keep it up :)
