### ISSUE TITLE
Using renderToString with components

### ISSUE THREAD

**Issue by Skippidar** [lingui/js-lingui#506]
When i need to use translation in function - i use ```renderToString(<Trans>Some string</Trans>)``` but it's not translated, just outputs "as is".

Is it possible to make it using translations or should I use i18n._(t``Some string``)? The problem is that i have to add withI18n and pass proptypes to start using it (adding renderToString() is just simplier, as i think)

**Comment by tricoder42** [comment]
You definitely also need to add `<I18nProvider>` around the `<Trans>` tags and load catalogs in it. Otherwise the Trans tags can't actually translate, so it simply returns default message.

I guess for you the easiest might be to import `i18n` directly and then call `i18n._` on it:

```js
import { i18n } from "./i18n.config" // your file with setupI18n call

const translation = i18n._("Some string")
```
