### ISSUE TITLE
How to use dynamic key

### ISSUE THREAD

**Issue by zxs2162** [lingui/js-lingui#507]
**Describe the bug**
When using dynamic key, the value does not work

**To Reproduce**
In message resource file, we  have below definition:

firstTiltle: 'First Title',
secondTitle:'Second title'

```
import { Trans } from "@lingui/react"

let myKey = 'firstTitle'

//Below will echo :First Title 
export default function Work() {
   return <Trans id={myKey}></Trans>
}

//Below will echo :firstTiltle 
export default function NotWork() {
   return <div>{i18n.t`${myKey}`}</div>
}
```

**Expected behavior**
i18n.t should support dynamic variable.

**Additional context**

- jsLingui version ``lingui --version``
2.7.4
- Babel version ``npm list babel-core``
7.0.0
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)
umijs

**Comment by tricoder42** [comment]
You should use [`i18n._`](https://lingui.js.org/ref/core.html#I18n._) instead.

```js
i18n._(myKey)
```

**Comment by zxs2162** [comment]
Thx. It works.
