### ISSUE TITLE
Remove implicit runtime parser in development mode

### ISSUE THREAD

**Issue by hjylewis** [lingui/js-lingui#519]
**Is your feature request related to a problem? Please describe.**
There is a confusing inconsistency between development and production mode that conceals user error during set up. See the thread in #388 for more details.

**Describe the solution you'd like**
Remove the default runtime parser in development mode

**Comment by hjylewis** [comment]
@tricoder42 Should we go ahead and make the API change documented [here](https://github.com/lingui/js-lingui/issues/342#issuecomment-424687026)? Rename `i18n.messageFormat` and export `icu` to its own package? =

**Comment by tricoder42** [comment]
I would start with removing conditional development blocks from core:

https://github.com/lingui/js-lingui/blob/e9fead052517ba1deda4e3491a9389d12f93437c/packages/core/src/i18n.ts#L164-L168

That way the app will break in development if it's misconfigured.

---

I'm not sure about the API from linked issue. Alternative might be compiling messages when they're loaded, so the core always works with compiled messages:

```js
import { setupI18n } from "@lingui/core"

function loadCatalog(locale) {
  // load compiled catalog
  return import(`@lingui/loader!./locales/${locale}.po`).then(catalog =>
    i18n.load(locale, catalog)
  )
}

export const i18n = setupI18n()
i18n.on("activate", loadCatalog)
```

or fetch raw messages and compile them after:

```js
import { setupI18n } from "@lingui/core"
import { compile } from "@lingui/messageFormat"

function loadCatalog(locale) {
  // load compiled catalog
  return fetch('/api/messages?lang=en').then(catalog =>
    const compiledCatalog = compile(catalog)
    i18n.load(locale, compiledCatalog)
  )
}

export const i18n = setupI18n()
i18n.on("activate", loadCatalog)
```

In both cases the compilation happens outside `core`. I would like to remove as much features as possible from core. However, if you think it's worth it in this case, I'm open to any suggestions.

**Comment by hjylewis** [comment]
I'm down to keep the compilation outside of `core` that way `core` can always expect compiled messages. 

Maybe compiling (runtime and cli) can add metadata like `__js_lingui: { compiled: true }` that can be checked for when messages are loaded that way it can fail and provide useful error messages when a user tries to load uncompiled messages.

**Comment by hjylewis** [comment]
Actually, this is more complicated than I thought since the cli compiler does more than just compile messages to function. Namely, it also resolves default and fallback messages.

My guess is there are already inconsistencies between the implicit runtime parser and the cli one (fallback locale isn't respected) and I'm worried more will develop over time which will lead to confusion. I think more thought will have to be put into how runtime parsing should be supported.

Maybe I'll just remove the runtime parse for now and we can figure out runtime parsing later if there's a valid usecase?

**Comment by tricoder42** [comment]
You're right, the CLI actually builds message catalogs by resolving translations, fallbacks and defaults and then compiles it. Runtime parse would just compile it, leaving building message catalog up to user.

> Maybe I'll just remove the runtime parser for now and we can figure out runtime parsing later if there's a valid usecase?

Sounds good to me. First, let's make production/development runtime consistent and then we can figure out how to support other usecases (e.g. raw catalogs, etc).

Thanks 👍

**Comment by ThiefMaster** [comment]
Is removing this really a good idea? During development I *really* do not want to have to bother compiling message dictionaries for stuff to work. I don't think there is any way in create-react-app based app to automatically rebuild the english/source locale, so it would require developers to run an extra tool just for translatable strings to work.

Would supporting runtime compilation in both dev and prod have any significant disadvantages (such as having to include huge libraries)?

Because the beauty of gettext-style translations (with the english message being the msgid) is that with no translations built you get the strings from the code. This is especially nice because it means you do not have to extract all the time after adding new strings (as long as your are fine with the occasional untranslated string). You just extract whenever you want to ask people to update translations.

**Comment by tricoder42** [comment]
> During development I really do not want to have to bother compiling message dictionaries for stuff to work. I don't think there is any way in create-react-app based app to automatically rebuild the english/source locale, so it would require developers to run an extra tool just for translatable strings to work.

The webpack loader compiles catalogs automatically. If you don't use it, then you need to run extract after each update, but there was an open PR to add a watch mode.

> Would supporting runtime compilation in both dev and prod have any significant disadvantages (such as having to include huge libraries)?

That was the main reason why I removed them initially.

> Because the beauty of gettext-style translations (with the english message being the msgid) is that with no translations built you get the strings from the code. This is especially nice because it means you do not have to extract all the time after adding new strings (as long as your are fine with the occasional untranslated string). You just extract whenever you want to ask people to update translations.

This works perfectly on the backend, but in frontend code you ideally want to remove any unnecessary text. If we keep the language defaults even in production, then we'll ship twice as much text. Lingui resolves defaults during compile process on build.

**Comment by tricoder42** [comment]
Closed as stale https://github.com/lingui/js-lingui/pull/543#issuecomment-720136511
