### ISSUE TITLE
Warning when using psuedolocaliation with non-compiled .po files

### ISSUE THREAD

**Issue by aleccool213** [lingui/js-lingui#521]
**Describe the bug**

We manually import our language catalogs using in a Next.JS app. We want to use psuedo-localization. I read the [documentation](https://lingui.js.org/tutorials/cli.html#pseudolocalization) and it requires that we use the `compile` command. I tried to perform this workflow without the `compile` command only to get this warning in console and that pseudo-localization was not working.

```
./src/locales/pseudo-LOCALE/messages.po
TypeError: Cannot read property 'split' of null
```

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

1. Setup linguijs with React

```
import { Trans } from "@lingui/react"

export default function App() {
   return <Trans>This should be translated!</Trans>
}
```

2. Add the correct config var:

```
{
   "fallbackLocale": "en",
   "format": "po",
   "localeDir": "src/locales/",
   "sourceLocale": "en",
   "srcPathDirs": ["src/"],
   "pseudoLocale": "pseudo-LOCALE"
}
```

3. Run the application

This is how we load languages:

```
const catalog = (await import(`../locales/${language}/messages.po`)).default;
...
<I18nProvider catalogs={{ [language]: catalog }} language={language}>
...
```

**Expected behavior**

- Should not give warning

**Additional context**

Lingui Versions:
    "@lingui/cli": "2.8.3",
    "@lingui/loader": "2.8.3",
    "@lingui/macro": "2.8.3",
    "@lingui/react": "2.8.3",

Babel versions:
    "@babel/core": "7.4.5",

- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.):

```
module.exports = {
  plugins: [
    // Enable babel macros for LinguiJS: https://lingui.js.org/tutorials/setup-react.html
    [require.resolve('babel-plugin-macros')],
  ],
```

**Comment by nickmask** [comment]
Did you ever figure this out? Having the same issue.

**Comment by aleccool213** [comment]
@nickmask No :(

**Comment by VinSpee** [comment]
@nickmask the workaround is running `yarn lingui compile` and making this change:

```diff
-const catalog = (await import(`../locales/${language}/messages.po`)).default;
+const catalog = (await import(`../locales/${language}/messages.js`)).default;
```

With that being said, I'd love to have this working in dev too with a raw `.po`
