### ISSUE TITLE
Support for custom message catalog loader

### ISSUE THREAD

**Issue by cdsanchez** [lingui/js-lingui#522]
**Is your feature request related to a problem? Please describe.**
Hello! Great work on js-lingui, looks great so far! We use a custom message catalog format that we would like to continue using as the canonical source of translations in our project. js-lingui, however, does not currently have the option to allow me to use a custom message catalog format.

**Describe the solution you'd like**

I would like js-lingui's configuration to support providing the name of a JS module that would implement the [`TranslationsFormat`](https://github.com/lingui/js-lingui/blob/d2bf647da62b7b10d2295e1236581cdf6e425d96/packages/cli/src/api/types.js#L39) type. js-lingui would then use this implementation for loading translations in my application.

This would allow me to write an implementation of `TranslationsFormat` for my application that can convert between js-lingui's "raw" message catalog representation and my custom representation.

I would be willing to add this functionality to js-lingui as a PR with tests and documentation updates.

**Describe alternatives you've considered**

One alternative would be to do a translation of my message catalog files to one of the formats that js-lingui supports during build-time. This introduces a few more moving parts into my build, and while possible, might be tricky to get right in terms of live/hot reload workflows as it is a "push" type mechanism, vs. the proposed "pull" mechanism.

**Comment by tricoder42** [comment]
Hey @cdsanchez, that's great suggestion!

I think we could reuse the `format` option in config, which would receive either function or path to module:

```json
{
  "format": "my-translation-format"
}
```

or

```js
module.exports = {
  "format": require("my-translation-format")
}
```

What do you think?

**Comment by tricoder42** [comment]
Btw if you want to work on it, could you please use `next` branch as a base?

**Comment by cdsanchez** [comment]
Thanks @tricoder42.

Cool! Yes, that config option is pretty close to what I have in my local fork.

To summarize the options that will be available in my PR:

Valid values for `config.format` may be:
1. A built-in formatter name ('po' etc)
1. An ES module name in which the specified module provides a default export of an object that satisfies the `TranslationFormat` shape
1. A JS object implementing the `TranslationFormat` shape directly

In order to support a `"format": require("my-format")` syntax, there would be an additional case where we would support a JS object of the same shape as the result of `require`, which we would unwrap to access the `default` export property. I'll leave this one 'til last since I think option 2 (above) provides equivalent functionality, but I think it should be easy enough to add.

And yes, I'm planning to do this work, so I'll go ahead and rebase onto the `next` branch.
