### ISSUE TITLE
lingui extract crashes with unhelpful error message with accidental default import

### ISSUE THREAD

**Issue by ljani** [lingui/js-lingui#523]
**Describe the bug**
I accidentally had imported `Trans` as a default import from `@lingui/macro` and when I tried to run `lingui extract`, it crashed with obscure error message. As this was my and probably others' first interaction with `lingui`, I'd say it definitely should provide a better developer experience.

**To Reproduce**

```jsx
import Trans from "@lingui/macro"

export default function App() {
   return <Trans>This should be translated!</Trans>
}
```

And then run `lingui extract`, which prints the following:

```
ui ❯❯❯ npm run lingui-extract                                                                                                                   npm WARN lifecycle The node binary used for scripts is C:\local\bin\node.exe but npm is using C:\Program Files\nodejs\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> ui@0.1.0 lingui-extract C:\ui
> lingui extract

C:\ui\node_modules\@lingui\cli\api\compat.js:56
        throw e;
        ^

TypeError: Cannot read property 'name' of undefined
    at C:\ui\node_modules\@lingui\babel-plugin-extract-messages\index.js:81:51
    at Array.forEach (<anonymous>)
    at PluginPass.ImportDeclaration (C:\ui\node_modules\@lingui\babel-plugin-extract-messages\index.js:80:27)
    at newFn (C:\ui\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (C:\ui\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (C:\ui\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (C:\ui\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (C:\ui\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitMultiple (C:\ui\node_modules\@babel\traverse\lib\context.js:85:17)
    at TraversalContext.visit (C:\ui\node_modules\@babel\traverse\lib\context.js:144:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ui@0.1.0 lingui-extract: `lingui extract`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ui@0.1.0 lingui-extract script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ljani\AppData\Roaming\npm-cache\_logs\2019-06-18T05_35_03_838Z-debug.log
```

**Expected behavior**
It should not crash, but provide a helpful error message, which tells you you're accidentally using the default export instead of the named export.

**Additional context**

- jsLingui version ``lingui --version``: `2.8.3`
- Babel version ``npm list babel-core``: `babel-core@7.0.0-bridge.0`
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.): `create-react-app`

**Comment by tricoder42** [comment]
Hi @ljani, thank you! We could definitely improve troubleshooting.

In `next` version it shows an error `Unknown macro default`, which we could definitely improve:

https://github.com/lingui/js-lingui/blob/07a5cb77ddd2400cfe0e9c827dc7d91435059afd/packages/macro/src/index.ts#L12-L14

Feel free to send a PR - either improve error message in next version or backport it to master. It shoudl be pretty straightforward.
