### ISSUE TITLE
I want to write lingui-express-middleware

### ISSUE THREAD

**Issue by nodkz** [lingui/js-lingui#524]
I want to write `lingui-express-middleware` with TypeScript but if you accept this package to your monorepo I'll start to do it with plain JavaScript.

I want to fork https://github.com/i18next/i18next-express-middleware, keeping the same configuration features.

Thoughts?

**Comment by nodkz** [comment]
Or maybe already exists express middleware for linguajs?

**Comment by tricoder42** [comment]
Hi @nodkz,
thank you for yout interest! In general I'm trying to minimize the amount of packages in this monorepo.

What about adding it to [lingui](https://github.com/lingui) GitHub organization? I could add you as a maintainer/contributor. What do you think?

I'm looking at the source code of `i18next-express-middleware` I would like to add language detection to LinguiJS in near future, but I don't have exact plans. I guess the best approach would be clone the repo, replace i18next with LinguiJS and if I ever get to replacing language detector, I would send a PR.

**Comment by nodkz** [comment]
@tricoder42 great!

Now I'm working on https://github.com/nodkz/lingui-express-middleware 
When it will be ready I'll ping you for repo transferring.

But also I'm working under integration with Fluent, so when I got a complete working solution I'm also ping you. Did somebody write a Fluent format for Lingui or not?

**Comment by tricoder42** [comment]
I don't think so, but that would be actually great!

Thank you for your contribution! 👍
