### ISSUE TITLE
official solution for language switcher

### ISSUE THREAD

**Issue by landsman** [lingui/js-lingui#526]
Hi guys,

I am looking for official tutorial how to get array/object of added locales.
Manually added my custom array to `package.json` is generated warnings:

```
● Validation Warning:

  Unknown option "supportedLangs" with value ["cs", "en"] was found.
  This is probably a typing mistake. Fixing it will remove this message.

See https://lingui.js.org/ref/conf.html for a list of valid options
```

**Config:**
```
{

  "lingui": {
    "supportedLangs": [
      "cs",
      "en"
    ],
    "fallbackLocale": "cs",
    "format": "po",
    "localeDir": "src/locales/",
    "srcPathDirs": [
      "src/"
    ],
    "srcPathIgnorePatterns": [
      "/node_modules/",
      "locales",
      "events",
      "data",
      "polyfils",
      "scss"
    ]
  }

}
```

I do not want to create another static file with this definition. There is missing some clear dynamic solution in my eyes. Am I right or I just mistaken and there is some doc about this?

**Comment by tricoder42** [comment]
Hi,
this will be solved in `next` version, where locales are defined in config:

```js
{
  "locales": ["en", "cs"]
}
```

See #334 for more info.

As for now, you should create a separate file manually with runtime config and read values from there.
