### ISSUE TITLE
doc: not working link to rendering reference

### ISSUE THREAD

**Issue by landsman** [lingui/js-lingui#527]
I wanted to send PR with fix but I can not find the right article:
https://github.com/lingui/js-lingui/blob/master/docs/ref/macro.rst#render

**Comment by tricoder42** [comment]
Right article for what? Could you be more specific please?

**Comment by landsman** [comment]
For not working link: https://github.com/lingui/js-lingui/blob/master/docs/ref/rendering-translations

**Comment by tricoder42** [comment]
Ah, interesting. The link should point to this section: https://github.com/lingui/js-lingui/blob/master/docs/ref/react.rst#rendering-of-translations

**Comment by landsman** [comment]
@tricoder42 but this is not react doc I think. This is vanilla-js solution, right?

**Comment by tricoder42** [comment]
Not really, rendering of translations is related to React.
