### ISSUE TITLE
Feature: Could we extend/inherit existing locale to new locale?

### ISSUE THREAD

**Issue by just4fun** [lingui/js-lingui#528]
**Is your feature request related to a problem? Please describe.**

My app supports Singapore market at the beginning, so I created **en** locale for it. These days we were asked to support another market, Australia, which will use English as well, but the content is a little different. Instead of creating new locale like **en_AU** and copy and paste all translations from **en**, then do according changes on translations base on requirement, is there any way to import/require/extend existing **en** locale into **en_AU**, and only provide different translations in latter one with merge/deep merge?

**Describe the solution you'd like**

In Rails i18n, we could do like following

```bash
/config
  /locales
    /en.rb
    /en_AU.rb
```

```ruby
# en.rb
LOCALE_EN = {
  en: {
    shared: {
      meta: {
        title: 'en title'
      }
    }
  }
}
```

```ruby
# en_AU.rb
require_relative 'en.rb'

{
  'en_AU': LOCALE_EN[:en].deep_merge(
    shared: {
      meta: {
        title: 'AU title'
      }
    }
  )
}
```

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by tricoder42** [comment]
Yes, this is one of planned features, see #280 

If you'd like to move it forward, feel free to send a PR. Use `next` branch as a base.

**Comment by just4fun** [comment]
@tricoder42 thanks for the information.
