### ISSUE TITLE
[next] Add typescript definitions to package bundle

### ISSUE THREAD

**Issue by nodkz** [lingui/js-lingui#533]
If we look at the latest packages, eg https://unpkg.com/@lingui/cli@3.0.0-6/
we don't see typescript definitions there.

Need to 
- add `declaration: true` to `tsconfig.json`
- add `types: "path/to/index.d.ts"` to `package.json`

As a working package with build-in typescript definitions, you may look at
- https://unpkg.com/mongodb-memory-server-core@5.1.5/
- https://github.com/nodkz/mongodb-memory-server

**Comment by tricoder42** [comment]
[react](https://github.com/lingui/js-lingui/blob/next/packages/react/package.json#L6) package already have correct `types` in `package.json`. It's just missing in `cli` and `macro` (and possibly others). Type definitions are generated next to build files.

**Comment by smeevil** [comment]
The Macro ones would be very welcome :)

**Comment by tricoder42** [comment]
Types should be exported in all packages in latest pre-release (check #334 for latest status). I've tested especially types for `macros`.

Feel free to reopen and send a PR using `next` as a base if problem persists.
