### ISSUE TITLE
[next] How to obtain all catalogs for server according to `lingui.config.js`?

### ISSUE THREAD

**Issue by nodkz** [lingui/js-lingui#535]
Under working on [lingui-express-middleware](https://github.com/nodkz/lingui-express-middleware) I met with a problem of obtaining current locales/catalogs.

### Reguar solution

Just require compiled files:

```js
const catalogs = {
  ru: require('../locales/ru/messages'),
  en: require('../locales/en/messages'),
  kk: require('../locales/kk/messages'),
};
app.use(lingui(catalogs));
```

BUT users may not have compiled files. Also in DEV mode need to create an additional watcher which observe changes in `locales` folder and re-compile locales. Also we should require all locales manually (command `yarn add-locale` does change server code).

### Proposed solution

Provide a built-in method eg. `loadCatalogs` for obtaining compiled catalogs according to `lingui.config.js`:

```js
const catalogs = loadCatalogs();
app.use(lingui(catalogs));
```

```js
import { getConfig } from '@lingui/conf';
import { getCatalogs } from '@lingui/cli/api';
import { Catalogs } from '@lingui/core';

export default function loadCatalogs(): Catalogs {
  const conf = getConfig();
  const catalogsData = getCatalogs(conf);
  const catalogs = {};
  catalogsData[0].locales.forEach((lc) => {
    catalogs[lc] = {
      messages: catalogsData[0].getTranslations(lc, conf),
      // localeData: how to obtain?
    };
  });
  return catalogs;
}
```

Example code:
https://github.com/nodkz/lingui-express-middleware/tree/master/examples/simple

With `loadCatalogs` method we can provide better dev experience, simplify initial server configuration.

Currently, this method compiles catalogs on start. Maybe firstly it should load compiled files (if it already exists). But I don't see any problem if it compiles them once on server start.

This method should be added to the `conf` package without `babel-core` dependency. Current my solution uses `cli` package which forced to use babel-core 😭

**Comment by tricoder42** [comment]
This could work 👍  You can get compiled messages as well, either by using webpack loader or extracting the logic from [`createCompiledCatalog`](https://github.com/lingui/js-lingui/blob/7e3f578f68005b7e728adbf314d274dc8a51d3fb/packages/cli/src/api/compile.ts#L126). I guess we could split the function into two: 1) compile messages and 2) write them to file. In your case you would only use the first part.

Just a note: This will only work in server-side environments (SSR, mobile). In browser you don't have access to lingui config.

**Comment by tricoder42** [comment]
Hey @nodkz, are you still interested in tackling this task? If so, feel free to reopen and send a PR using `next` branch as a base. I believe if you want to access `lingui.config.js` you need to write a custom macro (which has access to fs).  You'll need to take into account also new [`catalogs` config](https://js-lingui-git-next.lingui-js.now.sh/ref/conf.html#catalogs)

That macro could expand into individual requires, sth like:

```
import { i18n } from "@lingui/core"
import { allCatalogs } from "@lingui/macro"
 
// You write...
i18n.load(allCatalogs())

// And the macro is transformed into...
// ↓ ↓ ↓ ↓ ↓ ↓

i18n.load({
  ru: require('../locales/ru/messages'),
  en: require('../locales/en/messages'),
  kk: require('../locales/kk/messages'),
})
```
