### ISSUE TITLE
i18n._('key',...) Does not filter out component position tags.

### ISSUE THREAD

**Issue by Gerrel** [lingui/js-lingui#536]
I have a react app and want to use the Trans component and i18n side by side.
The [Trans] component formats the text properly and removes the tags, but [i18n._] does not.

I have the following PO file.
msgid "welcome"
msgstr "Hi <0>{name}</0>, welcome to Lingui!"

Using Trans it works proper.
```
<Trans id="welcome"
        values={{ name: props.name }} />
```
RESULT: Hi Developer, welcome to Lingui!

Using i18n._ it does not.
```
i18n._('welcome', { name: name });
```
RESULT: Hi <0>Developer</0>, welcome to Lingui!
EXPECTED: Hi Developer, welcome to Lingui!

Dependencies:
 "@lingui/react": "^2.8.3",
Dev:
 "@babel/core": "^7.4.5",
 "@lingui/cli": "^2.8.3",
 "@lingui/macro": "^2.8.3",
 "@types/lingui__core": "^2.7.0",
 "@types/lingui__macro": "^2.7.3",
 "@types/lingui__react": "^2.8.0",
  "babel-core": "^7.0.0-bridge.0"

**Comment by tricoder42** [comment]
Hi @Gerrel, you're right, this isn't supported at the moment. I'm not even sure how we should tackle this problem. `react` package uses `core` under the hood, so it's first translated with tags and in `react` package the tags are replaced with components.

At this point the easiest way would be a wrapper around `i18n._` call, which removes tag where it's necessary. Running it everywhere might affect performance (benchmark needed?).

Anyway, I'm not planning to implement such feature, so if you'd like then feel free to send a PR 👍 

Cheers

**Comment by Gerrel** [comment]
Could not find it in the docs...
Is there an option to escape the composition tags like in the case I want to use the following text?
```
msgstr "Hi <0>{name}</0>, welcome to Lingui! and in react you can style the variable surrounded with <0></0>"
```
The result output is now: Hi Developer</0>, welcome to Lingui! and you can style the variable surrounded with <0>

**Comment by tricoder42** [comment]
I guess the regexp is too gready. Usually you don't write `<` or `>` if you treat them as text but rather `&lt;` and `&gt;`

**Comment by Gerrel** [comment]
ah yes I can work with that, thanks!
