### ISSUE TITLE
babel-runtime being bundled alongside @babel/runtime-corejs2

### ISSUE THREAD

**Issue by wilsonpage** [lingui/js-lingui#540]
**Describe the bug**

I'm writing a NextJS app and using `@lingui/react`. After inspecting my bundle I noticed I'm bundling both `@babel/runtime-corejs2` which seem to have duplicate content.

<img width="511" alt="Screenshot 2019-07-10 at 17 03 31" src="https://user-images.githubusercontent.com/1020551/60985280-1c020780-a335-11e9-9e0d-a231804d22af.png">

How can I prevent Lingui from bundling this additional `babel-runtime`?

**Comment by tricoder42** [comment]
Hey @wilsonpage, it seems that one package is `@babel/runtime-corejs2` (Babel 7.x) and the other one is `babel-runtime` (Babel 6.x). I'm afraid there isn't much we can do, these are completely different packages. Lingui v3 is going to use Babel 7 by default which should solve this problem (see #537).

**Comment by wilsonpage** [comment]
Gotcha. Any rough idea when `v3` will be available to try?

**Comment by tricoder42** [comment]
The pre-release is available (see #334), but the date of final release is still unclear.
