### ISSUE TITLE
withI18nProps doesn't expose i18nHash.

### ISSUE THREAD

**Issue by FabianMeul** [lingui/js-lingui#547]
**Describe the bug**
`withI18nProps` describes one prop: `i18n`.
It should also describe the `i18nHash` prop, that is placed on the WrappedComponent inside the `withI18n` HoC.

**To Reproduce**
n/a

**Expected behavior**
`withI18nProps` should be 

```
type withI18nProps = {
  i18n: I18nType;
  i18nHash: string; // This prop is currently missing
}
```

**Additional context**

- jsLingui version `2.8.3`
- Babel version `7.5.5`

**Comment by tricoder42** [comment]
Hi @FabianMeul,
thank you for the report but `withI18n` HOC is removed completely in v3 and I don't plan to fix any issues in v2. If you wish, feel free to send a PR and I'll publish a patch release.
