### ISSUE TITLE
Use ES6 modules vs require

### ISSUE THREAD

**Issue by moodyjmz** [lingui/js-lingui#549]
I would like to use this with Polymer/Lit-Element, using require makes a build process in the middle of dev needed. Basically, have to drop their dev servers out and make one using web pack.

It would be cool if the project used es6 modules throughout as it would widen the base where this can be easily used.

**Comment by tricoder42** [comment]
Hey @moodyjmz, sounds good! Do you know how to configure Rollup to create ES6 modules? Would you like to take a look and send a PR? I would help you to navigate through build scripts.

**Comment by moodyjmz** [comment]
@tricoder42 I'm not familiar with Rollup, I'll have a look though and if I can I'll do it.

**Comment by tricoder42** [comment]
Hey @moodyjmz, have you been able to figure out how to create ES6 modules with Rollup?

**Comment by ckknight** [comment]
You can compile ECMAScript modules by putting `"compileNamespace": "es"` in `.linguirc`

https://lingui.js.org/ref/conf.html#std:config-compileNamespace

**Comment by tricoder42** [comment]
@moodyjmz Please try @ckknight suggestion and reopen if you problem persists.
