### ISSUE TITLE
[V2] Migrate to new context api

### ISSUE THREAD

**Issue by NSLS** [lingui/js-lingui#556]
**The problem:**
Since v3 release is a little bit delayed and the new context API and hooks are out for quite some time now, I feel frustrated that with all the other libraries I can use hooks to get something out of context, but with lingui v2 I still have to decorate my component.

**The solution:**
Because v3 will bring some breaking changes and will most likely take an additional time to make it stable, I think that it would be nice to migrate v2 to the new context API and make a `useLingui` hook available for all the current users.

**Additional info**
We have also tried to migrate to the current v3 release, but unfortunately we couldn't make it work and it's just too raw for production usage.

If you accept this idea I could spend some time and make a PR for this feature.

**Comment by tricoder42** [comment]
Hey @NSLS,
migrating to new context API is a breaking change, so we should bump the major version anyway.

There are only few missing breaking changes which should be included in v3. I believe the best approach would be finish missing features and move anything what isn't breaking to consecutive releases.

I've just come back from vacation, so let me review what's missing in v3 and I'll get back to you.

**Comment by NSLS** [comment]
Ok, I got your point.

I will try to have a look on what's missing or broken in the current state of v3 and provide some feedback in the appropriate issues

**Comment by oceantume** [comment]
@ignatevdev I know this is an old thread, but I found it while looking around for a way to replace the `withI18n` with a hook so I figured I'd add a comment with the solution I came up with.

Using the new context api and a special provider component that receives the i18n instance via withI18n, I was able to reproduce the same behaviour as the hoc in a hook instead. Here's the full solution : https://github.com/lingui/js-lingui/issues/390#issuecomment-673168776
