### ISSUE TITLE
Divide locale file into chunks

### ISSUE THREAD

**Issue by mxsxs2** [lingui/js-lingui#558]
**Is your feature request related to a problem? Please describe.**
The problem I have is the file size of the translation files. I have a very large project with a large amount of text which are in 7 different locales. This causes a long loading time for the site.

**Describe the solution you'd like**
Is it possible to chunk the localisation files? It would be great if a component could have a localisation file and for fallback there could be a common localisation file (as it is now).

**Describe alternatives you've considered**
I was thinking to dynamically import a locale for a component with ``` await import(`@lingui/loader!locales/${locale}/${component}/message.po`) ```. The issue with this approach is I cannot use `extract-locale` as that extracts into one big file.

I considered SSR or preload as well but I would prefer not to use them.

**Comment by tricoder42** [comment]
This is already supported in `next` branch, see #326. More sophisticated approach is under development in #503.
