### ISSUE TITLE
Cannot extract messages from compiled code

### ISSUE THREAD

**Issue by harryy2510** [lingui/js-lingui#559]
**Describe the bug**
I've compiled code with babel in cjs. I am trying to extract messages from compiled code.

- Case 1

If I'm using 
```
import {t} from '@lingui/macro';

<Grid>{t`Country`}</Grid>
```

compiled code looks like

```
_react2.default.createElement(_Grid.default, {},
  /*i18n*/
  {
    id: "Country"
  }
```

- Case 2
and if i use

```
import {Trans} from '@lingui/macro';

<Trans>Country</Trans>
```

compiled code looks like
```
react2.default.createElement(_react.Trans, {
      id: "Country"
})
```

When I am trying to extract messages, then Case 1, message gets extracted but in Case 2 message is not extracted.

**To Reproduce**
I will try upload sample code soon

**Expected behavior**
Either while building code, macro should introduce  /*i18n*/ comment in Trans component which I think is the key to extract messages.

- jsLingui version `2.8.3`
- Babel version `7.0.0-bridge.0`
- .babelrc

```
{
  "presets": [
    "@babel/env",
    ["react-app", { "absoluteRuntime": false, "flow": false, "typescript": true }]
  ],
  "plugins": [],
  "sourceType": "unambiguous"
}
```

**Comment by tricoder42** [comment]
It's hard to tell without an example. Feel free to explore working `examples` in this repository
