### ISSUE TITLE
date macro not working when used inside t macro

### ISSUE THREAD

**Issue by jbojcic1** [lingui/js-lingui#560]
**Describe the bug**
I have a message with a date that I need to translate outside of the React component, so based on https://lingui.js.org/ref/macro.html#jsmacro-t I tried using `i18n._(t`Today is ${date(name)}`)`, but it's not working. I am getting `Danas je [object Object]` in the result.

**To Reproduce**
1. Create react app with Create React App.
2. Add lingui-js and set it up so you can use translations outside the components as described here: https://lingui.js.org/tutorials/react-patterns.html#translations-outside-react-components
3. outside of the React component do:
```
import { date } from '@lingui/macro';
import { i18n } from './i18n';
...
const today = new Date();
const msg = i18n._(t`Today is ${date(today)}`);
```
then render msg in the component:
```
{msg}
```
Sandbox example  - https://codesandbox.io/s/linguijs-playground-5gk1u

**Expected behavior**
Date should be normally localized.

**Additional context**

- jsLingui version `2.8.3`
- I am using React app generated with Create React App

**Comment by semoal** [comment]
> **Describe the bug**
> I have a message with a date that I need to translate outside of the React component, so based on https://lingui.js.org/ref/macro.html#jsmacro-t I tried using `i18n._(t`Today is ${date(name)}`)`, but it's not working. I am getting `Danas je [object Object]` in the result.
> 
> **To Reproduce**
> 
> 1. Create react app with Create React App.
> 2. Add lingui-js and set it up so you can use translations outside the components as described here: https://lingui.js.org/tutorials/react-patterns.html#translations-outside-react-components
> 3. outside of the React component do:
> 
> ```
> import { date } from '@lingui/macro';
> import { i18n } from './i18n';
> ...
> const today = new Date();
> const msg = i18n._(t`Today is ${date(today)}`);
> ```
> 
> then render msg in the component:
> 
> ```
> {msg}
> ```
> 
> Sandbox example - https://codesandbox.io/s/linguijs-playground-5gk1u
> 
> **Expected behavior**
> Date should be normally localized.
> 
> **Additional context**
> 
> * jsLingui version `2.8.3`
> * I am using React app generated with Create React App

Did you find any solution mate? I'm having the same problems.

```jsx
i18n._(number(payload.value, {
        style: "percent",
        maximumFractionDigits: 2,
        minimumFractionDigits: 2,
}))
```

For example, this is causing for me [ObjectObject]

**Comment by jbojcic1** [comment]
@semoal unfortunately I didn't. I tried to debug the issue a bit and it seems that date macro is not returning the proper icu message format. For example if I do:

`const messageDesc = date(today)`

I am getting:
```
{
  id: "today,date",
  values: { today: ... }
}
```

If I then change id to `"{today, date}"` it seems to work fine. I trued to look into the code a bit but I don't understand babel macros nor icu message format enough.

js macros code:
https://github.com/lingui/js-lingui/blob/eb3540c04a6920da8bcdb36be3ff7db38899b72b/packages/macro/src/js.js
is where transformation to message descriptor happens

**Comment by uqee** [comment]
same here, `number` also doesn't work:

```javascript
t`Number is ${number(n)}`
```

transforms to

```json
{
  "id": "Number is {0}",
  "values": {
    "0": {
      "id": "n,number",
      "values": {
        "n": 123
      }
    }
  }
}
```

**Comment by uqee** [comment]
hmm, looks like if `date` and `number` are imported from `@lingui/core` instead of `@lingui/macro`, it works

**Comment by uqee** [comment]
and `plural` from `@lingui/macro` doesn't work either, but when imported from `@lingui/core` it's actually non-existent there (i.e. undefined), but being properly handled by macros :) also, typescript types want numbers to be strings, which is incorrect

**Comment by uqee** [comment]
i guess, we should just migrate to lingui v3 soon

**Comment by igorDolzh** [comment]
You could import `t` before `number` or `date` (It is a hack)
I made a fix for this https://github.com/lingui/js-lingui/pull/621

**Comment by tricoder42** [comment]
Hey guys, please use `i18n.number` and `i18n.date` instead of macros. `date` and `number` macros were removed in v3. That should solve your issue. The other half (#621) is solved as well.
