### ISSUE TITLE
What are pros and cons of using default generated id over a specified one?

### ISSUE THREAD

**Issue by sidoshi** [lingui/js-lingui#561]
I really like that we don't have to specify the id for each piece of text. But I want to be sure about the benefits each approach provides before making a decision. I couldn't find this documented anywhere so thought this is a good place to ask.

**Comment by tricoder42** [comment]
I've opened [Kialo discussion](https://www.kialo.com/what-to-use-as-message-ids-in-internationalization-25159) to explore this topic. Please check all arguments and feel free to enter discussion.
