### ISSUE TITLE
Possible to update activated language without I18nProvider

### ISSUE THREAD

**Issue by arosendorff** [lingui/js-lingui#567]
Is there a way to change the active language, and generate a component update, without making any changes to the component that houses the I18nProvider? I am using [redux-sagas](https://github.com/redux-saga/redux-saga), and I want to change the active language within the sagas.

From what I can see, it seems the only way to update all translations is via the I18nProvider. Thus I am using its ref and calling `ref.linguiPublisher.update({language: newLanguageCode})` but this feels like a very hacky solution.

I am using `setupI18n()` and passing the generated `i18n` class into the `I18nProvider`, but calling `i18n.active(newLanguageCode)` doesn't trigger a re-render. Is there any other way of doing this, or must I use the `ref.linguiPublisher` method?

**Comment by tricoder42** [comment]
This issue might be already solved in v3 (check #334, only pre-release available at the moment). You can call `i18n.activate('locale')` and `I18nProvider` will be updated automatically.
