### ISSUE TITLE
Add zero to plural macro

### ISSUE THREAD

**Issue by CWBudde** [lingui/js-lingui#573]
**Is your feature request related to a problem? Please describe.**
In the german language there is often not only a dedicated distinction between one and other, but also for zero.

**Describe the solution you'd like**
In order to improve the wording it would be usefull to add a 'zero' section similar to 'one' and 'other'

**Describe alternatives you've considered**
I'm not that deep into js-lingui, but maybe there already is a different macro to check whether the value is zero or not.

**Comment by tricoder42** [comment]
Hey @CWBudde, according to CLDR, official plural rules are just `one` and `other` for [german language](http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#de).

Lingui uses CLDR rules, so the only option is to use `=0` exact rule:

```
<Plural value={colunt} _0="Zero in german" one="..." other="..." />
``
