### ISSUE TITLE
[object Object] on a standard Trans in selects

### ISSUE THREAD

**Issue by mschipperheyn** [lingui/js-lingui#574]
**Describe the bug**
I get [object Object] on some standard `<Trans id="ui.foo">Foo</Trans>` renders. 

This happens only in some cases, and it seems to occur on Selects. 
The id is in the po file and compiled to js.

I've tried downgrading to 2.7.4 which didn't help.

**To Reproduce**

https://codesandbox.io/s/boring-glitter-i847j

**Expected behavior**
Display js file or default.

**Workaround**
Replacing the Trans in question with an `i18n._(t('ui.xyz')`XYZ`)` resolves the issue. I will update the code sandbox with this.

**Additional context**

- jsLingui version 2.7.4 | 2.8.3
- Babel version 7.5.5
- Your Babel config (e.g. `.babelrc`)

**Comment by keerpawan** [comment]
I'm getting the same [object] [object] issue, but my use case is different.
I have an array 
const x = [{text: <Trans>Hello</Trans>}]
In the render I have:
x.map((val) => <Trans>{val.text}</Trans>);

**Comment by keerpawan** [comment]
> I'm getting the same [object] [object] issue, but my use case is different.
> I have an array
> const x = [{text: Hello}]
> In the render I have:
> x.map((val) => {val.text});
> 
> Seems to work here: https://codesandbox.io/s/lingui-map-om8d0
> 
> So not sure why it does that in my app

Looks like i had an issue where my <Trans> was getting converted to an object. 🤦‍♂

This is my first time using lingui, so still learning

**Comment by keerpawan** [comment]
I suspect, our issues are related... the select box must be converting the <trans> -> type object, which strips out the $$typeof: Symbol(react.element)

**Comment by mschipperheyn** [comment]
Yes, the example does offer a workaround. So, hopefully, you'll be able to use that and move forward.

**Comment by wpq0** [comment]
FWIW, here's my work around https://codesandbox.io/s/silly-keller-475lp:
```
<Select name="test">
      <Trans id="ui.select" render={<option value=""></option>}>Select something</Trans>
      <Trans id="ui.one" render={<option value="1"></option>}>One</Trans>
      <Trans id="ui.two" render={<option value="2"></option>}>Two</Trans>
</Select>
```

**Comment by grayhound** [comment]
Issue is old, but still here's my workaround. Just user "renderToString"

```
import { renderToString } from 'react-dom/server'

<select>
<option>{renderToString(<Trans>String to translate</Trans>)}</option>
</select>
```

This will also help with some props for input, for example:
import { renderToString } from 'react-dom/server'

```
<input type="text" placeholder={renderToString(<Trans>String to translate</Trans>)} />
```

**Comment by tricoder42** [comment]
Hey @mschipperheyn, unfortunately this isn't related to Lingui as React itself doesn't allow `<option>` to have React elements. See https://github.com/lingui/js-lingui/issues/655#issuecomment-621637390

This would cause the same problem:

```jsx
        <select>
          <option>Text</option>
          <option>
            <p>Element</p>
          </option>
        </select>
```

We have to use `i18n._` or `t` macro here
