### ISSUE TITLE
3.0 various issues

### ISSUE THREAD

**Issue by ixrock** [lingui/js-lingui#575]
Hello! 
When LinguiJS 3.x are planned to be released?
I just tested version: `^3.0.0-7` with my webpack/react/typescript project and found some issues.

## Configuration
**.linguirc**
```
{
  "locales": ["en", "ru"],
  "sourceLocale": "en",
  "fallbackLocale": "en",
  "compileNamespace": "cjs",
  "format": "po",
  "extractBabelOptions": {
    "plugins": [
      "@babel/plugin-syntax-dynamic-import"
    ]
  },
  "catalogs": [
    {
      "path": "./locales/{locale}/messages",
      "include": "./client"
    }
  ]
}
```
**.babelrc**
```
{
  "plugins": [
    "macros",
    "@babel/plugin-transform-runtime"
  ],
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ]
}
```
**package.json**
```
    "@babel/core": "^7.5.5",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/preset-react": "^7.0.0",
    "@babel/runtime": "^7.5.5",
    "@lingui/cli": "^3.0.0-7",
    "@lingui/loader": "^3.0.0-7",
    "@lingui/macro": "^3.0.0-7",
    "@lingui/react": "^3.0.0-7",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "webpack": "^4.39.3",
    "webpack-cli": "^3.3.8",
    "webpack-dev-server": "^3.8.0",
```

## Issues

1) Incorrect types definitions in for `@lingui/macro`, it's not possible to import, for example: `import {Trans} from "@lingui/macro"`.

_Current workaround:_
I kept types from `2.x` version installed and I've added this to my `tsconfig.json`:
```
    "paths": {
      "@lingui/macro": [
        "node_modules/@types/lingui__macro"
      ]
    }
```
___

2) I have to install manually `fs-extra` npm package to be able to use `lingui extract`
Maybe it should be not in `devDependencies`?
___

3) For some reasons I can't use defined `i18n` name variable in my module like:

```
// File: i18n.ts
export const i18n = setupI18n();

// Used in: app.tsx
import {i18n} from "./i18n"
<I18nProvider i18n={i18n}>...</I18nProvider>
```

I see a lot of bugs like this:
```
Module parse failed: Identifier 'i18n' has already been declared (8:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/ts-loader/index.js
```

_Current workaround:_
Rename variable, I use `var _i18n` atm.
___

4) Incorrect work of `missing` function:
```
export const _i18n = setupI18n({
  missing: (message, id) => {
    console.warn('Missing localization:', message, id);
    return id;
  }
});
```
`id` contains translated text
`message` actually contains current locale
p.s. param names are taken from `missing` interface definition
___

5) Parametrized call ```i18n._(t`Some text ${param}`)```
will always trigger `missing` callback even if there is translated texts in catalog.
___
6) `plural` and other helpers from `@lingui/macro` not available.
___
7) Untranslated plurals with `fallbackLocale` doesn't work ?

English catalog (source): `{allItemsCount, plural, one {# item} other {# items}}`
Russian catalog: `{allItemsCount, plural, one {# элемент} few {# элемента} many {# элементов}  other {# элементов}}`

Problems: 
- if I skip `few` in the plural and the number will match it I see empty string (instead of `other` option)
- if i skip it fully in `ru` catalog then I see raw template in English instead of parsed plural value (expected matching `one` to `one` and  `other` to `few`, `many` and `other` for this case).

**Comment by tricoder42** [comment]
Hey @ixrock, thanks for a report! I've just fixed tests in `next` branch. Would you like to start fixing issues you've found and send a PR?

**Comment by ixrock** [comment]
@tricoder42 I have no idea how to fix it or where to start.. :)
I tried to run tests in `next` branch and this is what I've got:

```
Summary of all failing tests
 FAIL  packages/core/src/dev/compile.test.ts
  ● compile › should compile custom format for locale=fr and locales=null

    expect(received).toEqual(expected) // deep equality

    Expected: "0,1"
    Received: "0.1"

       96 |       function() {
       97 |         const number = prepare("{value, number}", locale, locales)
    >  98 |         expect(number({ value: 0.1 })).toEqual(expectedNumber)
          |                                        ^
       99 | 
      100 |         const percent = prepare("{value, number, percent}", locale, locales)
      101 |         expect(percent({ value: 0.1 })).toEqual(expectedPercent1)

      at Object.toEqual (packages/core/src/dev/compile.test.ts:98:40)

  ● compile › should compile custom format for locale=fr and locales=fr-CH

    expect(received).toEqual(expected) // deep equality

    Expected: "0,1"
    Received: "0.1"

       96 |       function() {
       97 |         const number = prepare("{value, number}", locale, locales)
    >  98 |         expect(number({ value: 0.1 })).toEqual(expectedNumber)
          |                                        ^
       99 | 
      100 |         const percent = prepare("{value, number, percent}", locale, locales)
      101 |         expect(percent({ value: 0.1 })).toEqual(expectedPercent1)

      at Object.toEqual (packages/core/src/dev/compile.test.ts:98:40)

 FAIL  packages/react/src/Trans.test.tsx
  ● Trans component › should render custom format

    expect(received).toEqual(expected) // deep equality

    Expected: "1,00 €"
    Received: "€1.00"

      114 |       />
      115 |     )
    > 116 |     expect(translation).toEqual("1,00 €")
          |                         ^
      117 |   })
      118 | 
      119 |   describe("rendering", function() {

      at Object.toEqual (packages/react/src/Trans.test.tsx:116:25)


Test Suites: 2 failed, 21 passed, 23 total
Tests:       3 failed, 12 skipped, 189 passed, 204 total
Snapshots:   41 passed, 41 total
```

**Comment by tricoder42** [comment]
That's interesting, seems like the formatting doesn't work.

Have you tried latest `next`? I've just fixed all tests yesterday.
Do you use yarn or npm?
What OS and node version you have?

**Comment by ixrock** [comment]
Yes, I did git checkout to `next` branch and ran `yarn`.
Node v10.16.3, MacOS 10.15 (Catalina)

**Comment by tricoder42** [comment]
@ixrock It seems you're missing the ICU data.

Try to run `NODE_ICU_DATA=./node_modules/full-icu yarn test` or enable full-icu support in node directly as described in [contributing docs](https://github.com/lingui/js-lingui/blob/master/CONTRIBUTING.md#setup-local-environment)

**Comment by tricoder42** [comment]
Hey @ixrock, I think all your issues are fixed in  latest pre-release. Please check it out and let me know if problems persist.
