### ISSUE TITLE
Detect locale

### ISSUE THREAD

**Issue by tricoder42** [lingui/js-lingui#577]
User's locale should be detected automatically if possible, but also allow customization. The approach should work both on server and in browser and it should follow guidelines for [multilingual sites](https://support.google.com/webmasters/answer/182192?hl=en&ref_topic=2370587)

## Proposal

Websites which serve different content for each locale (e.g. Wikipedia) will always use just URL to detect the current locale.

Locale-adaptive apps (i.e. same content, but UI is internationalized, like GitHub, Twitter, Facebook) should detect locale from following sources:

On server, detect locale from:

1. URL (subdomain `en.example.com`, path `example.com/en/` or search param `example.com?l=en`). This is useful even for locale-adaptive apps for search engines, i.e. user's will always use `example.com` and customize locale through user's profile or cookies, but search engine will be advised to follow `example.com/?l=en` to crawl site in specific locale.
2. Cookie (for user's overrides)
3. [HTTP Accept-Language header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language)

In browser, detect locale from:

1. `<html lang>` attribute (if set by server). 

This should be the only option for server-side rendered pages. For client-side rendered pages, there are other options:

2. URL (same motivation as above)
3. Cookie (for user's overrides)
4. [navigator.language](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language) 

## Implementation

Each _detector_ `<please insert better name>` should be just a plain function returning a locale or null (if not found):

```
type Detector<Config extends {}> = (config: Config) => string | null

// just an example with pseudocode
function detectFromCookie({ name, expiration }) {
  if (typeof window !== "undefined") {
    // server side code
    if (has cookie) {
      return req.cookie[name]
    }
  } else {
    // client-side code
  }
}
```

Then we can chain them together to get the first match:

```
const locale = detect(
  detectFromURL(),
  detectFromCookie({ cookieName: "locale" }),
  detectFromRequest()
)
```

## Resources

- [Guide - Detecting active locale in LinguiJS] - I've started writing draft of guide, it's available in [`nxt/detect-locale`](https://raw.githubusercontent.com/lingui/js-lingui/6f58868e7dbb50fddb444c251bf963f5d2b9ecab/docs/guides/active-locale.rst) branch. Feel free to use it or throw it away, I just needed to figure out a possible approach.
- [fluent-langneg](https://github.com/projectfluent/fluent.js/tree/master/fluent-langneg) - once we have a list of requested locales, we might compare it with list of available locales to get the best match. Probably only useful when detecting locale from `navigator.language` or `Accent-Language` header.
- [i18next/language-detector](https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/index.js) includes several strategies to detect locale. The implementation seems to be tighly coupled to i18next, but it could definitely serve as an inspiration.

## Checklist

- [ ] Create a new package `@lingui/detect-locale` or find existing solution in JS ecosystem.
- [ ] Document how to detect locale in different kind of apps (static vs locale-adaptive, SSR vs CSR)

**Comment by FredyC** [comment]
We have been using https://github.com/fabulator/locales-detector. It's nice because it can be configured in various ways. Especially transformers are super useful. I am not so sure there is a need for a dedicated Lingui tool for detection. I mean each app has different needs. What about recommending one instead?

```js
  const resolver = new LocaleResolver(
    [new DETECTORS.NavigatorDetector()],
    [new TRANSFORMERS.LanguageOnlyTransformer()],
  )
  const languages = resolver.getLocales()
```

**Comment by tricoder42** [comment]
Pefect, that's what I meant with:
> ... or find existing solution in JS ecosystem.
> Document how to detect locale in different kind of apps (static vs locale-adaptive, SSR vs CSR)

**Comment by tricoder42** [comment]
I checked `locales-detector` briefly and it lacks detecting locale from cookie, from HTTP header and detecting from URL only supports SearchParams. Plus it weights 2.2kb. The first two detectors (cookie, HTTP header) are *must* for SSR, detecting from other parts of URL is nice to have, unless the author of this PR needs it :) 

I would rather find a different one or write it from scratch by copy-pasting relevant bits from various libs (I guess this problem was already solved 100 times).

Just to make it clear: this component should be completely optional. You'll be able to plug in your locale detector as long as it returns a single `locale`. So you're free to use your example 👍

**Comment by hjylewis** [comment]
I'm interested in taking a look at this. To clarify the detectors we would want would be:

* URL
	* Server-Side
	* Client-Side
* Cookie
	* Server-Side
	* Client-Side
* HTTP Accept-Language header (Just SSR)
* <html lang> attribute (Just CSR)
* navigator.language (Just CSR)

The desired library would provide these detectors and some sort of resolver (maybe a wrapper of fluent-langneg) that picks a locale from the detectors return values?

**Comment by tricoder42** [comment]
I consider `HTTP Accept-Language` header and `navigator.language` as a same kind of locale detector, each for different context (SSR vs CSR). So, I would update your classification to this:

- URL
  - client-side
  - server-side
- Cookie
  - client-side
  - server-side
- System preferences
  - HTTP Accent-Language (server-side)
  - `navigator.language` (client-side)

`html lang` is tempting and easy to do, but in Next.js you pass current locale directly in `getInitialProps`, which are serialized, so you don't really need it. I'm not sure if there's any valid usecase, but feel free to skip it if you don't need it in your project.

> The desired library would provide these detectors and some sort of resolver (maybe a wrapper of fluent-langneg) that picks a locale from the detectors return values?

Yes please! All detectors are simple functions which return a `string | null` where string is detected locale and null if the detector hasn't found anything. So the resolver might be simple function which calls detectors until one of them returns an non null result. I guess the default order could be:

1. URL
2. Cookie
3. System-preferences
4. Default locale

Again, since all detectors are pure function, it should be fairly easy to define your own order or completely different behavior.

Detected locale is then passed to `fluent-langneg` to return the "best match".

What do you think?

**Comment by hjylewis** [comment]
Sounds good. I have a question since I'm not as familiar with SSR:

Unless I'm mistaken, the user will have to explicitly pass the HTTP request to the URL, Cookie, and System Preferences detectors for SSR. Unlike CSR, the request (used to get the URL/cookie/headers) is not global like `document.cookie` or `document.location`. 

Because of that, is it worth combining the CSR and SSR detectors? They're going to have different interfaces i.e. `detectFromUrl(request)` vs `detectFromUrl()`.

**Comment by semoal** [comment]
I can work on this, if anything you considered relevant for the V3 release @tricoder42 just let know I can help you

**Comment by tricoder42** [comment]
@semoal This is definitely nice-to-have, not essential feature for v3 release. Also, it would be great to figure out how the library could work when used in Next.js project, because they're working on locale detection on their own https://github.com/vercel/next.js/discussions/17078

I guess a new package (e.g. `@lingui/detect-locale`) would be the best — optional yet ready to be integrated into LinguiJS.

**Comment by semoal** [comment]
Assign this to me Tomáš, i've already started working on it 👍🏻
