### ISSUE TITLE
Usage in NodeJS and less dependency on macros

### ISSUE THREAD

**Issue by HommeSauvage** [lingui/js-lingui#580]
I have a node project that's done in a serverless architecture. I'm not intending to add webpack or any builders. However, because lingui is my main translation library in most of my front end projects, I wanted to use it in the backend too.

The only problem is that it's not easy to use the extract command, so using `i18n._({ id: 'text' })` is not detected and won't get extracted. Is there a way to use extract without using macros? Maybe an extractor that scans for strings rather than rely on macros like [i18next scanner](https://github.com/i18next/i18next-scanner).

**Comment by bfelbo** [comment]
@HommeSauvage We're in the same situation. Did you find a solution?

**Comment by newash** [comment]
For me `i18n._(/*i18n*/ { id: 'text' })` did the trick.
(see the note before https://lingui.js.org/ref/macro.html#t)

**Comment by tricoder42** [comment]
Indeed, adding `/* i18n */` does the trick. The CLI doesn't depend on macros. Feel free to browse [test cases](https://github.com/lingui/js-lingui/tree/next/packages/babel-plugin-extract-messages/test/fixtures), documentation is being updated at the moment.
