### ISSUE TITLE
[v3] t('id')`message` is not working

### ISSUE THREAD

**Issue by alexkuz** [lingui/js-lingui#583]
It seems that in new version ``` t('id')`message` ``` is not parsed by macros - I get `t is not defined` error as a result.

I noticed that tests are also missing this format.

`lingui extract` also fails generating files from it, giving the same record for all instances:
```
msgid "{0}"
msgstr "{0}"
```

**Comment by alexkuz** [comment]
looking at tests, seems like it is processed by macros after all, which generates `'{0}', { 0: t('id') }`, where `t`is undefined indeed, and default `message` is vanished)

**Comment by tricoder42** [comment]
Hey @alexkuz, what branch are you testing? In upcoming release the `t('id')'message'` is obsolete in favor of `defineMessage({ id: 'id', message: 'message' })`. There was too many variants to handle that I rather added another macro to add metadata (id, description) to message.

**Comment by alexkuz** [comment]
Ah, I see. I'm using `3.0.0-7`.
I guess I'll just use ```t'id'```, for brevity

Is this the shortest way to use it in a component?
```ts
  const { i18n } = useLingui();
  
  const appTitle =  i18n._(t`app.title`);
```

**Comment by tricoder42** [comment]
Yeah, in `3.0.0-7` it is.
