### ISSUE TITLE
`compile --strict` should skip missing pseudo translations

### ISSUE THREAD

**Issue by danielchabr** [lingui/js-lingui#584]
**Describe the bug**
`lingui compile --strict` shouldn't fail with pseudo language missing translations

**To Reproduce**
Having pseudo locale enabled in config `pseudoLocale: 'pseudo'` run `lingui compile --strict` to compile messages catalogs. The command will fail even when all translations are available because pseudo lang is taken into account when checking for missing translations

**Expected behavior**
the `--strict` flag should compile succesfully when all translations are available even when I use pseudo locales for testing

**Additional context**
- jsLingui version ``lingui --version`` 2.8.3
- Babel version ``npm list babel-core`` 7.0.0-bridge.0
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.) custom config

**Comment by tricoder42** [comment]
It has just been released in [2.9.0](https://github.com/lingui/js-lingui/releases/tag/v2.9.0).
