### ISSUE TITLE
Make catalog file line number references optional

### ISSUE THREAD

**Issue by MarttiR** [lingui/js-lingui#587]
**Problem description**
Having line numbers in catalog files creates a *lot* of merge conflicts in a GitFlow-ish workflow when multiple developers are working on the same codebase. The same conflicts happen in each language catalog file and each one must be manually merged twice: first when merging feature branches to develop, and once more when merging to master.

**Preferred solution**
There should be an option to turn off the line numbers from catalog output.

**Alternatives considered**
This could be accomplished by using the `minimal` format, but it would also strip the `obsolete` info, which is needed for development. The PO format also includes line numbers, so it would create the same amount of conflicts.

**Comment by tricoder42** [comment]
Hey @MarttiR! What if the `extract` command would resolve merge conflicts in catalog automatically in the same way how `yarn` does it?

Message references and sources would be extracted from the existing codebase and translations would be loaded from the current branch. Ideally we could use the latest translation in merge in case if both `develop` and `feature` branch has updates in translations.

What do you think? Willing to work on it and send a PR?

**Comment by MarttiR** [comment]
@tricoder42 I suppose that would be a step forward, but unless `extract` can parse a file that contains git conflict markers, it would still require manual steps from the developers (at least `git checkout --ours`) before the `extract` command could run at all. Any new translations merged in would be lost at that step, or they would have to be manually recovered from the feature branch. I think a git merge driver would work better in that regard.

However, it would be a lot easier to implement a configuration option that is checked when adding line number references to serialized translation objects.

**Comment by dcorb** [comment]
This feature will be really useful, please consider to merge it. We came up with a workaround:
In a `removeOrigin.js ` file:
```
const fs = require("fs");

function removeOrigin(path) {
  let messages = JSON.parse(fs.readFileSync(path));
  Object.keys(messages).forEach(function(key) {
    delete messages[key].origin;
  });
  fs.writeFileSync(path, JSON.stringify(messages, null, 2));
}

removeOrigin("translations/en/messages.json");
removeOrigin("translations/fi/messages.json");
console.log("✅ Translations' origin removed");
```

Then, as npm script:
`"compile-lingui": "lingui extract clean && node translations/removeOrigin.js && lingui compile"`

**Comment by tricoder42** [comment]
It has just been released in [2.9.0](https://github.com/lingui/js-lingui/releases/tag/v2.9.0).

**Comment by joshhunt** [comment]
Is it correct that this option is not available for PO files (yet?)? There is currently no way to configure lingui to include line numbers/origins in PO files?

**Comment by tricoder42** [comment]
@joshhunt Not yet, but it's available in v3 (pre-release). It's not documented (yet), but I've definitely merged it https://github.com/lingui/js-lingui/blob/next/packages/conf/src/index.ts#L58

**Comment by landsman** [comment]
@MarttiR is it same with https://github.com/lingui/js-lingui/issues/720 ?
