### ISSUE TITLE
Suggestion: Use JSON.parse for message catalogues instead of JS object literals

### ISSUE THREAD

**Issue by osartun** [lingui/js-lingui#601]
Even though it sounds counter intuitive plain JS objects take longer to process than putting them into a string and calling `JSON.parse` on it.

> Because the JSON grammar is much simpler than JavaScript’s grammar, JSON can be parsed more efficiently than JavaScript. This knowledge can be applied to improve start-up performance for web apps that ship large JSON-like configuration object literals […].
> As long as the JSON string is only evaluated once, the JSON.parse approach is much faster compared to the JavaScript object literal, especially for cold loads.

_Source: https://v8.dev/blog/cost-of-javascript-2019#json_
_Video explaining it short and simple: https://www.youtube.com/watch?v=ff4fgQxPaO0_

**Is your feature request related to a problem? Please describe.**
Lingui's message catalogues are embedded as plain JS object literals. The more translations are added to a project the larger these catalogues become.

**Describe the solution you'd like**
I believe it can reduce an app's initialization time if Lingui applies this `JSON.parse` approach to its catalogues.

**Comment by tricoder42** [comment]
Hey @osartun, as long as it doesn't make public API more complex, I'm not against it. Would be great to see a benchmark before we start optimizing things.

Anyway, feel free to submit a PR agains `next` branch. If you'd like to release it asap before v3, please backport it to `master` branch as well.

In case of any questions, feel free to ask!

**Comment by osartun** [comment]
@tricoder42 Thanks for the quick response

Unfortunately I don't think I'll take this on myself anytime soon. So, if anyone else wants to tackle this I'd appreciate it.

**Comment by tricoder42** [comment]
If anyone interested tackling this, feel free to reopen
