### ISSUE TITLE
`render` in `Trans` should be a renderProp

### ISSUE THREAD

**Issue by theKashey** [lingui/js-lingui#607]
**Describe the bug**
Let's pick example from the docs
```js
<Trans render={({ translation }) => <Icon label={translation} />}>
```

What it is "expected" to be? It's _ducks_ like a render prop, so it would __just__ render an `Icon` with `translation`

What it is? `React.createElement(render, { translation: value })`, so it would be a new, unique `Element` __every render__.

The bug is: that's just not usable at all. It shall be render prop, and could be it, without any breaking compatibity.

**To Reproduce**

<Trans render={({ translation }) => <Icon label={translation} />}>

**Expected behavior**

Should not remount internal component every render

Both v2 and v3 are affected.

** Proposed fix **

https://github.com/lingui/js-lingui/blob/next/packages/react/src/Trans.tsx#L77
```js
  // Component: (props) => <a title={props.translation}>x</a>
  return React.createElement(render as React.ElementType<TransRenderProps>, {
    id,
    translation,
    message
  })
```
👇👇👇👇
```js
  // Component: (props) => <a title={props.translation}>x</a>
  return render({
    id,
    translation,
    message
  })
```

**Comment by tricoder42** [comment]
Hey @theKashey, good catch. Could you please create PR with this change agains `next` branch? The branch is stable again and ready for contributing.

**Comment by theKashey** [comment]
Sure

**Comment by semoal** [comment]
is not introduced this yet? I can do a pr
