### ISSUE TITLE
export declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by iCasper1979** [lingui/js-lingui#609]
I am using the I18nLoader HOC and @lingui/loader loading message.json crashes with this error. 
The error appears here:

/***/ "../node_modules/@lingui/loader/index.js!./locales/de/messages.json":
/*!*****************************************************************!*\
  !*** ../node_modules/@lingui/loader!./locales/de/messages.json ***!
  \*****************************************************************/
/*! no static exports found */
/***/ (function(module, exports) {
/* eslint-disable */export default{
...

**.linguirc**
{
	"localeDir": "src/locales/",
	"srcPathDirs": ["src/"],
	"format": "minimal",
	"compileNamespace": "es",
	"fallbackLocale": "de",
	"sourceLocale": "de",
}

.babelrc
{
	"presets": 
		[
			"@lingui/babel-preset-react",
			[
				"@babel/preset-env", {
					"useBuiltIns": "usage",
					"corejs": 3,
					"debug": false,
					"targets": {
						"esmodules": true
					}
				}
			],
			"@babel/preset-react",
		],
	"plugins": [
		["macros"],    
		["dynamic-import-node"],              
		["transform-class-properties"], 
		["@babel/plugin-syntax-dynamic-import"], 
		["@babel/plugin-proposal-class-properties", { "loose" : false }], 
		["@babel/plugin-proposal-decorators", { "legacy": true }],
		["react-hot-loader/babel", { "safetyNet": false }],
		["@babel/plugin-transform-modules-commonjs", {
			"allowTopLevelThis": true,
			"loose": true,
		}],
		["@babel/plugin-transform-runtime", {
			"absoluteRuntime": false,
			"corejs": { version: 3, proposals: true },
			"helpers": true,
			"regenerator": true,
			"useESModules": true,
			"version": "^7.7.7"
		}],
	],
}

webpack config:
module.exports = {
	mode: 'development',
	entry: [
		commonPaths.contentBasePath + "/index.js",
		'webpack-hot-middleware/client'
	],
	context: commonPaths.contentBasePath, // -> src
	//devtool: 'cheap-module-source-map',
	devtool: 'inline-source-map',
	devServer: {
		contentBase: './dist',
		hot: true,
	},
	optimization: {
		splitChunks: {
			chunks: 'async',
			minSize: 30000,
			maxSize: 0,
			minChunks: 1,
			maxAsyncRequests: 6,
			maxInitialRequests: 4,
			automaticNameDelimiter: '~',
			automaticNameMaxLength: 30,
			cacheGroups: {
				vendors: {
					test: /[\\/]node_modules[\\/]/,
					priority: -10
				},
				default: {
					minChunks: 2,
					priority: -20,
					reuseExistingChunk: true
				}
			}
		}
	},
	module: {
		rules: [
			loaders.CSSLoader,
			loaders.JSLoader,
			loaders.SVGLoader,
			//loaders.ESLintLoader,
			loaders.FileLoader,
			loaders.HTMLLoader
		]
	},   
	plugins: [
		new CleanWebpackPlugin(),
		new Dotenv(),
		new HtmlWebpackPlugin({
			title: 'Frida is hot',
			inject: true,
			filename: './index.html',
			template: '../public/index.html',
			showErrors: true
		}),
		new webpack.HotModuleReplacementPlugin(),
		new webpack.NoEmitOnErrorsPlugin(),
		//new BundleAnalyzerPlugin(),
		new webpack.ProvidePlugin({
			$: 'jquery',
			jQuery: 'jquery',
			'window.jQuery': 'jquery',
			'window.moment': 'moment',
			'moment': 'moment',
		}),
	],
	output: {
		path: commonPaths.outputPath, // -> dist
		filename: '[name].bundle.js',
		//chunkFilename: '[name].bundle.js',
		// important for dev-middleware
		publicPath: "/", // -> dist
	},
	// only for hot-loader
	resolve: {
		alias: {
			'react-dom': '@hot-loader/react-dom',
		},
	},
}

**Comment by tricoder42** [comment]
Sorry, I can't help you here. Try to compare your config with working ones in `examples` directory.

Good luck 👍

**Comment by meldafert** [comment]
The problem seems to be the `"compileNamespace": "es"` option in `.linguirc`.
This outputs the compiles lang files as esmodules (with top-level export), which are then fed into webpack as if they were cjs.

To fix this, just use `"compileNamespace": "cjs"` or remove the option as `"cjs"` is the default.

This option appears to be ignored in lingui-loader versions before 2.8.0, but now it is expected behaviour.
