### ISSUE TITLE
Type safety / provability regarding interpolation

### ISSUE THREAD

**Issue by jbreckmckye** [lingui/js-lingui#614]
I'd like to know that messages using interpolation are type safe / provable, inasmuch as they can only use variables provided in the scope the message is used. I'm wondering how I can do that with LinguiJS.

I'll describe what I've tried so far.

Initially I had a crude (partial) solution to this problem using the JSX macros. I could use a `<Trans>` component that pulled all the variables it needed into its body. My IDE or TS language service could tell if any of those vars would be missing. Then, in the translation file, the message ID would list all the variables available to the translator.

Although the tooling wouldn't tell if the translator was using a variable that's not available (as far as I can tell), it would be easy to check via visual inspection.

I'll demonstrate what I mean with some example code.

The TSX file might look like this

```tsx
const messageCount = 6

<Trans>
   You have this many messages {messageCount} {notMessageCount} <- IDE warning here
</Trans>
```

And the PO file could look like this

```po
#: Component.tsx:123
msgid "User inbox message {messageCount}"
msgstr "User inbox message in French, {messageCount} {somethingTotallyDifferent}" <- can spot this in code review
```

**The problem**

That works OK, but it has two shortcomings:

1. It still relies on a person eyeballing the translations during code review and checking that a translation doesn't refer to any vars not in the message ID. Unless there's LinguiJS tooling I'm missing somewhere?
2. The IDs aren't very stable. If I change the fallback text, `extract` thinks it's a whole new translation. If I'm using `extract --clean` it will wipe the old translations entirely. Either way it creates some fiddling in the PO files, which isn't ideal.

I kinda have a workaround where I don't use the fallback text, I just provide a semistructured `<Trans>` content so that ID changes will be limited to when I add new vars. e.g.

```tsx
<Trans>
   Message count
   {messageCount} {userName}
   <SelectOrdinal ... />
</Trans>
```

...which then gives me stable IDs and a way to see in the PO file if an interpolation is missing. But it's not quite ideal.

**What I'd really, really like**

...is if we could encode the input variables of a translation in the translation file, and introspect the syntax of a given translation to see that it can't do anything weird. If we could give `<Trans>` elements stable IDs that don't change when altering the input variable signatures of the translations, that would be ideal.

For instance, if I could write

```tsx
<Trans id="stable_id" values={{ messageCount, userName}}>
   fallback content <RichText>...</RichText>
</Trans>
```

and have a PO file encode that somehow, like

```po
msgid "stable_id {messageCount, userName}"
...
```

Something like this might be plausible with Fluent - you can get the AST of a particular translation and possibly build tooling around that, but it would be a fair bit of effort, and I really like a lot of Lingui's features.

Can I get the level of type safety I crave with a Lingui based project? I am working in a domain where missing text / legal terms could be a serious issue.

**Comment by tricoder42** [comment]
Hey @jbreckmckye, thanks for you suggestion. Not sure if we should clutter runtime code with this. We could actually use an upcoming `lingui check` #724 to validate placeholders agains the source string. It would require exporting this information to catalogs. Also, many localization management tools validate placeholders, e.g. Transifex.

**Comment by tricoder42** [comment]
Hey @jbreckmckye, if you're still interesting in validating placeholders, please send a PR. Adding a new command `lingui check` which performs various validations is a way to go in my opinion. Feel free to create just a base of check command and add your validation (i.e. placeholders in source locale and target locale match)
