### ISSUE TITLE
I18nProvider's language and i18n.language property can differ from each other 

### ISSUE THREAD

**Issue by karolinakuzniewicz** [lingui/js-lingui#618]
**Describe the bug**
While setting up the `I18nProvider` with language and i18n as a props and switching the language, the `I18nProvider.language` will be updated while the `I18nProvider.i18n.language` will still contain the init value. Shouldn't the `i18n` instance rely on `I18nProvider.language` current value and update on its change?

**To Reproduce**
```
import { I18nProvider } from "@lingui/react";

// imported module from other file
const i18n = setupI18n({ catalogs: translations, language: defaultLocale });

export default function App() {
   return <I18nProvider catalogs={catalogs} i18n={i18n} language={locale}>{children}</I18nProvider>
}
```

**Expected behavior**
`I18nProvider` will update its `language` and `i18n.language` property on language change, that `I18nProvider` and `i18n` module will share the same locale context. It sounds unreasonable that this two properties may differ from each other at the same moment and should be updated at the same time, without updating the `I18nProvider.language` prop and `i18n.language` instance.

**Comment by FredyC** [comment]
I suppose this is no longer issue since `I18nProvider` is accepting `i18n` instance only. I suggest closing this.

**Comment by tricoder42** [comment]
Indeed, this should be already fixed in v3. New version should be released within few weeks. Thank you for raising an issue and sorry for late response
