### ISSUE TITLE
Extract fails when files do not have import from 'lingui-react'

### ISSUE THREAD

**Issue by felipeko** [lingui/js-lingui#62]
Hi, i'm setting up lingui on my project, but i wont need i18n for all files, but i get the following errors when using extract on the project:
![image](https://user-images.githubusercontent.com/472649/29432829-6b79064e-8373-11e7-8563-17e9b5e399e5.png)

Individual files that import {Trans} work fine. Is there any way to just ignore files without import and keep extracting others?

Thanks.

**Comment by tricoder42** [comment]
This shouldn't been happening after latest release of CLI (lingui-cli@1.0.5) and extract plugin (babel-plugin-lingui-extract-messages@1.0.3). I'll take a look

You can also ignore individual files or patterns with `srcPathIgnorePatterns` option as a temporary fix (see https://lingui.gitbooks.io/js/ref/cli.html#srcpathignorepatterns-array).

**Comment by mcongy** [comment]
Using latest release (lingui-cli@1.0.5) and extract plugin (babel-plugin-lingui-extract-messages@1.0.3).

Issue still persists.

**Comment by tricoder42** [comment]
I'm not able to reproduce this bug.

It's the very same error? Could you please paste the file which causes this error?

**Comment by felipeko** [comment]
Any simple file can cause this, for example:
```
import React from 'react'

class LinguiErrorTest extends React.Component {
  render() {
    return <div>:(</div>
  }
}
```

Using extract gives me:
![image](https://user-images.githubusercontent.com/472649/29540096-2faa39b6-86a3-11e7-87af-eb2fb8029337.png)

**Comment by tricoder42** [comment]
Fixed in latest releases:

babel-plugin-lingui-extract-messages@1.0.5
babel-plugin-lingui-transform-react@1.0.4
babel-preset-lingui-react@1.0.3
lingui-cli@1.1.0
