### ISSUE TITLE
Use modern React Context

### ISSUE THREAD

**Issue by ckknight** [lingui/js-lingui#622]
**Describe the bug**
@lingui/react is using the legacy-styled React context, which leads to warnings in Strict Mode.

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```
import * as React from 'react';
import { I18nProvider, Trans } from "@lingui/react"

export default function App() {
  return (
    <React.StrictMode>
      <I18nProvider language="en" catalogs={{en:{}}} missing="🚨">
        <Trans>This should be translated!</Trans>
      </I18nProvider>
    </React.StrictMode>
  )
}
```

The console will have a warning akin to
```
Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: I18n, I18nProvider, WithI18n

Learn more about this warning here: https://fb.me/react-legacy-context
```

**Expected behavior**
No warning within the console

**Additional context**

- jsLingui version `2.9.1`
- Babel version `babel-core@7.0.0-bridge.0` and `@babel/core@7.8.4`
- Your Babel config (e.g. `.babelrc`) or framework you use: Create React App

----
This should be fixable by requiring React 16.6.0 or greater and using `React.createContext` or by leveraging a package like https://www.npmjs.com/package/mini-create-react-context

**Comment by tricoder42** [comment]
Next version (in `next` branch) already uses new context. It just waits until final release.

**Comment by nikneb** [comment]
Still getting the same error. Is this fixed?
"@lingui/react": "^2.9.1",
"react": "^16.13.0",
