### ISSUE TITLE
Migrate from 2.x to 3.x? But the latest release is v2.9.1

### ISSUE THREAD

**Issue by stekovinbranturry** [lingui/js-lingui#626]
I'm trying to upgrade lingui in my project from v1.x to the latest. Here is a doc about migrate to v3.x https://lingui.js.org/releases/migration-3.html . But the latest release is actually v2.9.1. So I guess it's not able to migrate to v3.x for now?

**Comment by tricoder42** [comment]
Hey @stekovinbranturry, please upgrade to 2.x for now. The 3.x release is long overdue but not finihsed yet. If you want to follow latest updates, please check #334
