### ISSUE TITLE
I always get "Missing message ID, skipping." when the id is not filled out

### ISSUE THREAD

**Issue by capaj** [lingui/js-lingui#628]
**Describe the bug**
I tried adding js-lingui to this boilerplate: https://github.com/leebenson/reactql

and right out of the gate, I run into this:
```
> 4house-fe-web@4.5.0 extract /home/capaj/work-repos/4house/4house-fe-web
> lingui extract

Missing message ID, skipping.
<Trans>
        <h3>Top stories from Hacker News</h3>
      </Trans>
Missing message ID, skipping.
<Trans>Hi from ReactQL</Trans>
Catalog statistics:
┌──────────┬─────────────┬─────────┐
│ Language │ Total count │ Missing │
├──────────┼─────────────┼─────────┤
│ cs       │      0      │    0    │
│ en       │      0      │    0    │
```

**To Reproduce**
check out: https://github.com/capaj/reactql
and try adding jslingui

**Expected behavior**
extraction adds `<Trans>` even whem missing id fields

- jsLingui version ``lingui --version``: 2.9.1
- Babel version ``npm list babel-core``: babel-core@7.0.0-bridge.0
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)
```
{
          exclude: /node_modules/,
          test: /\.(j|t)sx?$/i,
          use: [
            {
              loader: 'babel-loader',
              options: {
                cacheDirectory: true,
                presets: ['@babel/typescript', '@babel/react'],
                plugins: [
                  'macros',
                  ['@babel/proposal-class-properties', { loose: true }],
                  '@babel/proposal-object-rest-spread',
                  '@babel/plugin-syntax-dynamic-import',
                  '@babel/plugin-proposal-optional-chaining',
                  'react-hot-loader/babel',
                  'emotion'
                ]
              }
            }
          ]
        }
```

**Comment by nvdnvd00** [comment]
I have the same issue

**Comment by tricoder42** [comment]
Hey @capaj, I can't find any mention about Lingui nor i18n in the repo. It must be misconfigured, because I'm not getting similar warnings... Feel free to checkout next-js example in `examples/next-js` directory. It uses Lingui, Typescript, but with Next.js

**Comment by ThaNico** [comment]
Hi, I ran into a similar issue and this link is high in the search results so I thought I'd share how I fixed it

I auto imported the Trans element and it got imported from "lingui/react", not from "lingui/macro" as shown in the tutorial
After switching the import then my Trans element without id was not ignored anymore

`import { Trans } from '@lingui/macro';`
