### ISSUE TITLE
Lingui JS auto Translation JSON file

### ISSUE THREAD

**Issue by dananw** [lingui/js-lingui#630]
**Is your feature request related to a problem? Please describe.**
any auto-translation for lingui jS?

**Describe the solution you'd like**
i create a tools for simply Translation JSON file from lingui to other languages.

https://auto-translation.now.sh/

**Comment by tricoder42** [comment]
Pretty good! I'm gonna feature it in LinguiJS docs as soon as I finish v3. Great stuff 👍

**Comment by tricoder42** [comment]
Added to `next` branch. Thank you 👍
