### ISSUE TITLE
willActivate is not a function

### ISSUE THREAD

**Issue by nmoinvaz** [lingui/js-lingui#633]
**Describe the bug**
When trying to use the `i18n.willActivate` function Javascript reports a function not found error. This function is mentioned in the migration docs [here](https://lingui.js.org/releases/migration-3.html) and also on this third-party blog [post](https://dev.to/stereobooster/i18n-of-react-with-linguijs-1-24oi).

**To Reproduce**
Attempt to use willActivate as mentioned in the migration docs for 3.0.

```
const i18n = setupI18n()
i18n.willActivate(locale => {
  /* webpackMode: "lazy", webpackChunkName: "i18n-[index]" */
  return import(`@lingui/loader!./locales/${locale}/messages.po`)
})
```

**Expected behavior**
I noticed that migration docs are the only place where this function is mentioned. So I am wondering how can I accomplish the same thing if this function is no longer available in latest versions of 3.0.

**Additional context**

- jsLingui version ``3.0.0-9``
- Babel version ``babel-core@7.0.0-bridge.0``
- Create React App

**Comment by tricoder42** [comment]
Hi @nmoinvaz, sorry for confusion, migration docs aren't updated yet. You can take a look at [`Create React App` example](https://github.com/lingui/js-lingui/blob/next/examples/create-react-app/src/i18n.config.js) and [`Next.js` example](https://github.com/lingui/js-lingui/blob/next/examples/next-js/utils/i18n.ts). 

In short, `willActivate` was removed. `didActivate` was replaced by `i18n.on('change', callback)`
