### ISSUE TITLE
Add formatOptions.origin to PO format

### ISSUE THREAD

**Issue by tricoder42** [lingui/js-lingui#634]
Working on reference documentation for configuration I've found that `formatOptions.origins` is missing in `@lingui/conf` package (probably due to wrong merge). Moreoever, even the original [commit](https://github.com/lingui/js-lingui/commit/b1a109aa30f3fc3d8279cf978cd56528f7ca197a) adds this feature to `lingui` format only and not PO format. 

This feature removes origin lines (e.g. `App.js:3`) from message catalogs which is useful to avoid unnecessary merge conflicts.

Tasks:

- [x] Add `formatOptions` to `@lingui/conf` package
- [x] Check that both `lingui` and `po` formats use `formatOption.origins`
- [x] If possible, write tests to cover cases with and without this option.

Additional info:

- Use `next` branch as a base
- Use original [commit](https://github.com/lingui/js-lingui/commit/b1a109aa30f3fc3d8279cf978cd56528f7ca197a) as a reference.

**Comment by kirillku** [comment]
Should it be `formatOptions.origin` (as in the issue) or `formatOptions.origins` (as in the reference commit)?

**Comment by tricoder42** [comment]
@kirillku My bad, please keep `formatOptions.origins` from the reference commit.

**Comment by tricoder42** [comment]
Fixed by @kirillku in 8d4af154. Thank you again 🙏
