### ISSUE TITLE
Cannot add country locale such as pt_BR

### ISSUE THREAD

**Issue by felipeko** [lingui/js-lingui#64]
Hi, it's usual for some countries to have their own sub locale inside a language. 

lingui-cli does appear to support this at the moment. Is it possible to add support?

Thanks again! And good job on the library!

**Comment by tricoder42** [comment]
Hey @felipeko! Thank you for your interest in thin project.

It should be relatively easy to add support for country locales. I tried to add en_US and it really fails on `Unknown locale(s): en_US`.

As far as I understand, language (`en`) defines plural rules and other possible language features (like text direction), while country defines date and number formats, right?

**Comment by felipeko** [comment]
Yes, i think that's right. The messages can also be different from country to country.

**Comment by tricoder42** [comment]
Fixed in latest releases:

lingui-cli@1.1.0
lingui-i18n@1.2.1
lingui-react@1.0.4
