### ISSUE TITLE
RFC: Better approach to I18nProvider and i18n instance

### ISSUE THREAD

**Issue by FredyC** [lingui/js-lingui#649]
_Note: In the end, I realized I am probably making a too big fuss about this, but it's sort of good summarization that I don't want to just throw away_

## Summary of behavior (as of 3.0.0-10)

The `@lingui/core` exports the `i18n`. There is no need to call `setupI18n` in most cases. The migration docs are [currently misguiding in that](https://js-lingui-git-next.lingui-js.now.sh/releases/migration-3.html#removed-i18nprovider-declarative-api).

With `@lingui/macro` and use of `t` macro, this works correctly and the exported instance is used.

However, when we try to use `Trans` component (or its siblings), we get a failure that `I18nProvider` needs to be used. It's a fairly inconsistent approach.

![image](https://user-images.githubusercontent.com/1096340/79129313-4b9ede00-7da5-11ea-8fb5-1d69a75a6021.png)

### Is the `I18nProvider` needed?

It's a thin wrapper around React Context to pass down the `i18n` instance which can be consumed by `useLingui` hook. That alone can be easily achieved in userland, no need to have that in a library.

It also includes side effects subscribing to `i18n` configuration changes to re-render components that are accessing the context. That makes `I18nProvider` somewhat useful, but still hardly warrants for mandatory use. Especially if the app is ok with **full reload on language changes**.

Furthermore, there is no opt-out from that behavior. It's unlikely to be a problem given that full reload would follow.

### What about testing?

It's a known fact that global objects are problematic for any kind of testing that runs the app code. It means that every test has to reset that object to avoid flakiness.

However, is it a problem for localization purposes? I mean if your tests want to refer to elements by a text, it's probably better to have those stable, either ID or default message. You don't need translations in that kind of test.

You might probably want to test out logic around the switching languages, but that might better be handled in E2E tests. Same for testing different translations if, for example, some language text isn't making button unclickable.

So, in my opinion, there is no need to have separate `i18n` instance for each test. It would only slow it down without any sort of benefit.

### What's up with the [runtimeConfigModule](https://js-lingui-git-next.lingui-js.now.sh/ref/conf.html#runtimeconfigmodule)

It can be considered as the first line of a customized experience if you want to use it to export `i18n` from a different location or even completely custom instance working differently. The macros are taking advantage of this just fine, but `I18nProvider` requires to implicitly pass that instance in the props making it somewhat awkward.

## The problem - An optional `I18nProvider`

For cases where a dynamic locale switching is not a requirement, the `I18nProvider` shouldn't be needed at all. That would make things much simpler when entering the Lingui world. 

In practice, though, that's more problematic because `useLingui` cannot be called conditionally. It can accept optional prop to basically disable it and grab global `i18n` instance exported from `@lingui/core` and all is well. However, there is no way to easily configure such behavior.

When using a custom `i18n` (through `runtimeConfigModule`) it shouldn't be required to use the `I18nProvider` either. However, the config cannot be read in runtime (as I already attempted at #648). 
Furthermore, if `useLingui` would fallback to default `i18n` implicitly, it's an error trap. Suddenly, there are two different instances used and the developer is not warned about it.

### Solution 1 - Do nothing

Ok, I assume this is gonna win. Ultimately, the biggest drawback here is that everyone has to use `i18nProvider` no matter what. The side effect of re-rendering could be made optional with a prop in case it's unwanted behavior. It's less smooth but bearable.

### Solution 2 - Opt-in to default

Helps, to avoid the awkward part when we need to pass global `i18n` into the `I18nProvider` which doesn't make much sense to a newcomer. At the same time, it keeps warning in case you want to use a custom `i18n` but forget to pass it into the `I18nProvider`.

```jsx
<I18nProvider withDefault>...</i18nProvider>
```

### Solution 3 - `getI18n` macro

@tricoder42 [suggested](https://github.com/lingui/js-lingui/pull/648#pullrequestreview-392020069) to write a simple macro.

```js
import { getI18n } from "@lingui/macro"

const i18n = getI18n()
// Transformed into:
// const i18n = require("i18nModule")
```

However, I don't think that solves anything, because `useLingui` is _hidden_ inside compiled Lingui code and any macro wouldn't run there.

### Solution 4 - Injected `i18n`

Since `Trans` (and friends) are macros, it's fairly easy to read `runtimeConfigModule` there and adjust behavior of actual `Trans` component from `@lingui/react`. It could accept `i18n` directly (along with injected import).

### Solution 5 - Macro Provider

Similar to no. 4 and builds on top of no. 2 where we would just use `I18nProvider` in the tree as a macro, it would read config and adjust its behavior accordingly.

Reference #334

**Comment by tricoder42** [comment]
I've just realized that you can also use `I18nProvider` to set `defaultRender` prop https://github.com/lingui/js-lingui/blob/d052f20a1f2d55501c4b42b02bb419211d9714c9/packages/react/src/I18nProvider.tsx#L52-L57

**Comment by FredyC** [comment]
@tricoder42 That means what actually? :) It's probably very rarely used, hardly warrants as a main reason to require the use of `I18nProvider` imo ;)

**Comment by tricoder42** [comment]
Just a note it's not only for `i18n` instance. It was added for react-native support, where you need to wrap all strings in `<Text>` component.

**Comment by dimaqq** [comment]
+1 to update the migration docs, it took me a while to come up with sane setup...

It was even worse because `t` and/or `Trans` macro inject `i18n` which is not the same as the global `i18n` so that:

Following doesn't compile (attempt to redefine `i18n`):
```js
import { setupI18n, Messages } from "@lingui/core";
import { t, Trans } from "@lingui/macro";

const i18n = setupI18n();
i18n.load(...);
i18n.activate(...);

export const x = t`xx`;
```

Following compiles but doesn't work correctly, because `Trans` uses instance from provider, and `t` uses an injected global instance:
```js
// i18n.ts
import { setupI18n, Messages } from "@lingui/core";
const i18n = setupI18n();
i18n.load(...);
i18n.activate(...);

export default i18n;


// index.tsx
import i18n from "./i18n";

ReactDOM.render(<I18nProvider i18n={i18n}><Comp/></I18nProvider>);


// Comp
import { t, Trans } from "@lingui/macro";

const Comp = () => {
  const msg = t`one`;
  return <div>
    <p><Trans>two</Trans><p>  # OK
    <p>{ msg }</p>  # Not translated!
  </div>
};
```

**Comment by tricoder42** [comment]
As I understand, the problem is using an "extra" `I18nProvider` (the problem section in OP is actually a suggested solution). Given how many libraries use global provider and they all deal with it somehow (including tests) I don't see any value in finding alternative solution.

However, if you come up with alternative solution, feel free to post it. It'll require probably different macros, rewrite the `@lingui/react` package and figure out all usecases.
