### ISSUE TITLE
Children of <option> can't be React elements

### ISSUE THREAD

**Issue by nmoinvaz** [lingui/js-lingui#655]
**Describe the bug**
When using a `<select>` element instead of a `<ul>` element to switch the language, it does not translate dropdown text properly.

**To Reproduce**
Use the following code in `LocaleSwitcher.js`.

```
import * as React from "react"

import { locales, activate } from "./i18n.config"
import { Trans } from "@lingui/react";
import "./LocaleSwitcher.css"

export function LocaleSwitcher() {
  return (
    <select className="LocaleSwitcher" onClick={(locale) => activate(locale) }>
      {Object.keys(locales).map((locale) => (
        <React.Fragment>
        <Trans id={locales[locale]}/>
        <option key={locale}><Trans id={locales[locale]}/></option>
        </React.Fragment>
      ))}
    </select>
  )
}
```

**Expected behavior**
I expect the text in the dropdown to be translated. Notice that the first `<Trans>` element is translated but not the `<Trans>` element in the `<option>` tag - instead it shows `[object Object]` for each item in the dropdown.

![image](https://user-images.githubusercontent.com/1364432/79173707-3c239300-7dad-11ea-99b8-879b7d743583.png)

- jsLingui version ``3.0.0-10``
- Create React App

**Comment by nmoinvaz** [comment]
Also when using the dropdown, reselecting a language that was previously loaded dynamically results in a `TypeError: Cannot convert undefined or null to object` in the call to `i18n.load`.

**Comment by tricoder42** [comment]
Hey @nmoinvaz, could you please create a repository with minimal example so I test it quickly? Cheers 👍

**Comment by nmoinvaz** [comment]
See `nmoinvaz/js-lingui` branch `bugs/locale-switch-select`.

**Comment by nmoinvaz** [comment]
This is similar to #574.

**Comment by tricoder42** [comment]
Yeah, it seems for some reason the children of `<option>` are being converted to string, which means  we can't use `<Trans>` macro/component here. You need to use `i18n._` directly:

```js
<option key={locale}>{i18n._(locales[locale])}</option>
```

We should write it down in documentation as a known problems, but I'm afraid there's nothing else we can do about it.

It's not even related to Lingui - this is the same problem:

```jsx
        <select>
          <option>Text</option>
          <option>
            <p>Element</p>
          </option>
        </select>
```

`Text` is rendered correctly, but `Element` is not.

**Comment by nmoinvaz** [comment]
I can't seem to get create-react-app example working at all. I had to set the `value` on the `option` element. and use `e.target.value` to get past errors, but language strings are not updating.
```
    <select className="LocaleSwitcher" onClick={(e) => activate(e.target.value)}>
      {Object.keys(locales).map((locale) => (
        <option key={locale} value={locale}>{i18n._(locales[locale])}</option>
      ))}
    </select>
```

**Comment by tricoder42** [comment]
As mentioned in https://github.com/lingui/js-lingui/issues/655#issuecomment-621637390, this is a feature of React. Not related to Lingui
