### ISSUE TITLE
[next] Refactor extraction stats output

### ISSUE THREAD

**Issue by FredyC** [lingui/js-lingui#656]
Currently, stats are commented out due to the complexity of multiple catalogs. 

https://github.com/lingui/js-lingui/blob/03ce90086a698e0cc030d188c0a7e2cb4d0b787b/packages/cli/src/lingui-extract.ts#L49

We can discuss here how it should look like to be actually useful. Alternatively, it might be worth to keep extract command simple with some short summarization and instead add a new command that would output stats based on eg. catalog name.

**Comment by semoal** [comment]
Uh, I tough that the script wasnt working properly, because I was used to see the stats.
Whats the problem? I could work on it, after the codemod

**Comment by FredyC** [comment]
AFAIK it was commented out because of a change in how catalogs work. I don't really know specifics.

**Comment by tricoder42** [comment]
Yes, now with multiple catalogs it's a bit more complex to calculate the stats. I didn't have time to fix it.

Regarding the UI, I guess we could display the overal stats as before. Not sure if stats per catalog would be anyhow helpful

**Comment by semoal** [comment]
> Yes, now with multiple catalogs it's a bit more complex to calculate the stats. I didn't have time to fix it.
> 
> Regarding the UI, I guess we could display the overal stats as before. Not sure if stats per catalog would be anyhow helpful

Tomáš I can work on it if you give me some guidelines, we are close enough to do some little corrections to the codemod so I can do it in parallel.

I'll write some docs on the website about the codemod an his usage in the migration-3.rst if you're agree with =)

**Comment by tricoder42** [comment]
> Tomáš I can work on it if you give me some guidelines, we are close enough to do some little corrections to the codemod so I can do it in parallel.

Well, you need to calculate stats for each catalog, combine them together and then print to console. I don't think it's complex or difficult, I just didn't have time to tackle it.

https://github.com/lingui/js-lingui/blob/bcc37800c57638022bfe492b4ba58011ebe37879/packages/cli/src/lingui-extract.ts#L34-L49

As I mentioned before I don't know if we should print stats for each catalog or just the totals. I belive the totals could be enough. I've always used stats to check missing translations

> I'll write some docs on the website about the codemod an his usage in the migration-3.rst if you're agree with =)

Absolutely! Go ahead 👍

**Comment by semoal** [comment]
Alright, lgtm I'll start later on
