### ISSUE TITLE
[next] Refactor pseudolocale

### ISSUE THREAD

**Issue by FredyC** [lingui/js-lingui#657]
I never used pseudo localization so I am not sure how it's supposed to work, but it's currently commented out from extract command. This should be fixed before V3 comes out otherwise it's a breaking change.

https://github.com/lingui/js-lingui/blob/03ce90086a698e0cc030d188c0a7e2cb4d0b787b/packages/cli/src/lingui-extract.ts#L42

**Comment by tricoder42** [comment]
Pseudolocalization creates a catalog in another locale where all translations (or ids) and passed through `pseudolocale` function. I think the only missing piece here is add an extra locale at runtime and catalogs should handle the rest. This happens in `createCompiledCatalog`, so when you run `lingui compile`

**Comment by tricoder42** [comment]
Closed in #741. Thanks @laszbalo
