### ISSUE TITLE
[next] Misleading migration guide regarding `i18n.load` and importing compiled catalogs

### ISSUE THREAD

**Issue by lucasecdb** [lingui/js-lingui#663]
**Describe the bug**

I'm getting a TypeScript error when using the method `i18n.load`. Probably something in my messages catalog is wrong, or the typings for the `CompiledMessage` type is incorrect. Here is the full error (I omited my catalog definition to reduce clutter):

```
51:19 Argument of type 'my catalog here' is not assignable to parameter of type 'Record<string, CompiledMessage>'.
  Property '"Are you sure you want to delete this model? {0} and {1} associated with it."' is incompatible with index signature.
    Type '(string | string[])[]' is not assignable to type 'CompiledMessage'.
      Type '(string | string[])[]' is not assignable to type '(string | [string, string?, (string | Object)?])[]'.
        Type 'string | string[]' is not assignable to type 'string | [string, string?, (string | Object)?]'.
          Type 'string[]' is not assignable to type 'string | [string, string?, (string | Object)?]'.
            Type 'string[]' is not assignable to type 'string'.
    49 |   const i18n = setupI18n()
    50 |
  > 51 |   i18n.load('en', enMessages)
       |                   ^
```

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```tsx
import { Trans } from '@lingui/macro'
import React from 'react'

export default function App() {
  const value1 = 1
  const value2 = 2

  return (
    <Trans>
      Are you sure you want to delete this model?{' '}
      {i18n._(
        plural(value1, {
          one: "There's # note",
          other: "There're # notes",
        })
      )}{' '}
      and{' '}
      {i18n._(
        plural(value2, {
          one: '# template',
          other: '# templates',
         })
       )}{' '}
       associated with it.
     </Trans>
  )
}
```

The above code will be compiled to this catalog

```js
module.exports = {
  messages: {
    'Are you sure you want to delete this model? {0} and {1} associated with it.': [
      'Are you sure you want to delete this model? ',
      ['0'],
      ' and ',
      ['1'],
      ' associated with it.',
    ],
    '{0, plural, one {# template} other {# templates}}': [
      ['0', 'plural', { one: ['#', ' template'], other: ['#', ' templates'] }],
    ],
    "{0, plural, one {There's # note} other {There're # notes}}": [
      [
        '0',
        'plural',
        {
          one: ["There's ", '#', ' note'],
          other: ["There're ", '#', ' notes'],
        },
      ],
    ],
  }
}
```

**Expected behavior**

I expected the typings for the `i18n.load` function to properly handle all cases for the macros compiled message.

**Additional context**

I'm using the following configuration:

```jsonc
// .linguirc.json
{
  "sourceLocale": "en",
  "locales": ["en", "pt"],
  "catalogs": [
    {
      "path": "src/locales/{locale}/messages",
      "include": ["src/"],
      "exclude": ["**/node_modules/**"]
    }
  ],
  "format": "po"
}
```

**Comment by tricoder42** [comment]
It seems you're passing default import directly to i18n. You should only pass `messages`:

```diff
import enMessages from "./locale/en/messages.js"

- i18n.load('en', enMessages)
+ i18n.load('en', enMessages.messages)
```

Snippet from Next.js example:

https://github.com/lingui/js-lingui/blob/b3c10f2452a0efc085c1bf4289241b3e7cebd943/examples/next-js/utils/i18n.ts#L7-L11


I noticed the migration docs have this wrong... Feel free to send PR if you have time. I might get to it later this week. All changes should be trivial in this file: https://github.com/lingui/js-lingui/blob/next/docs/releases/migration-3.rst

**Comment by lucasecdb** [comment]
I'm actually only passing the `messages` export. This is how I imported it:

```tsx
import { messages as enMessages} from './locales/en/messages'
```

Sorry for not including it in the issue description :-/

**Comment by lucasecdb** [comment]
If you want to take a look, I have my PR with the upgrade from `v3.0.0-5` to `v3.0.0-11` opened [here](https://github.com/cramkle/cramkle/pull/101).

**Comment by lucasecdb** [comment]
I just figured out what was wrong with my typings. It wasn't because I was importing the `messages`, but because I was missing the `--typescript` flag in the `lingui compile` command. I didn't read the migration docs fully, but I suspect it's also missing there.

Anyway, the PR that adjusted the docs to use the `messages` property of the catalog was merged, so I think we can close this.
