### ISSUE TITLE
Lingui extract cause allocation failure in prod env

### ISSUE THREAD

**Issue by GitDeluxe** [lingui/js-lingui#679]
**Describe the bug**
In production environement when I run ` lingui extrat && lingui compile` . I get this fatal error that indicate some allocation failure . 

```
WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:
  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3
<--- Last few GCs --->
[51628:00000114E67A7F70]    83545 ms: Scavenge 1368.7 (1439.6) -> 1358.3 (1443.1) MB, 25.6 / 0.0 ms  (average mu = 0.178, current mu = 0.053) allocation failure
[51628:00000114E67A7F70]    90427 ms: Mark-sweep 1371.3 (1443.1) -> 1348.0 (1440.1) MB, 6664.9 / 0.0 ms  (average mu = 0.161, current mu = 0.144) allocation failure scavenge might not succeed
<--- JS stacktrace --->
==== JS stack trace =========================================
    0: ExitFrame [pc: 000003A47D0DC5C1]
    1: StubFrame [pc: 000003A47D093770]
Security context: 0x02af65f9e6e9 <JSObject>
    2: visitQueue [00000229B76A4669] [C:\workspace\quoslive\client\node_modules\@babel\traverse\lib\context.js:~90] [pc=000003A47D4D738C](this=0x017dcfe49cc1 <TraversalContext map = 0000025DBC5B2719>,queue=0x017dcfe49d21 <JSArray[1]>)
    3: /* anonymous */ [0000020CEF38BC89] [C:\workspace\quoslive\client\node_module...
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7E455F04A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+5114
 2: 00007FF7E453A0C6 node::MakeCallback+4518
 3: 00007FF7E453AA30 node_module_register+2032
 4: 00007FF7E47C20EE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF7E47C201F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF7E4CE2BC4 v8::internal::Heap::MaxHeapGrowingFactor+9556
 7: 00007FF7E4CD9C46 v8::internal::ScavengeJob::operator=+24310
 8: 00007FF7E4CD829C v8::internal::ScavengeJob::operator=+17740
 9: 00007FF7E4CE0F87 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF7E4CE1006 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF7E489CDB7 v8::internal::usine::NewFillerObject+55
12: 00007FF7E4932CC6 v8::internal::WasmJs::Install+29414
13: 000003A47D0DC5C1
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! quos_frontend@1.0.0 extract: `lingui extract`
npm ERR! Exit status 134
```
**Environement**

Prod environement :

WindowsServer 2016 RAM 8G0 CPU Xeon 2,4G
   node 10.1.3
  @lingui/react ^2.8.3 ,   
   react 16.8.6
   @babel/core":  ^7.6.4 ,
   @babel/preset-env":  ^7.5.5 ,
   @babel/preset-react":  ^7.0.0 ,

In local environement it work like a charm 

Windows 10 , intel core i7 , 8Go RAM , 
      node 13.1.0 , 

 devDependencies
 
    @lingui/react ^2.8.3 ,  react 16.8.6 
    @babel/core": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/preset-react": "^7.0.0",
    "@lingui/cli": "^2.8.3",
    "@lingui/macro": "^2.8.3",
    "autoprefixer": "^9.6.1",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^10.0.2",
    "babel-loader": "^8.0.6",
    "babel-plugin-macros": "^2.6.1",

**Expected behavior**
When i run ` lingui extract && lingui compile`

I would get this output 

``

[BABEL] Note: The code generator has deoptimised the styling of C:\project\client\dist\main.js as it exceeds the max of 500KB.
Catalog statistics:
┌──────────┬─────────────┬─────────┐
│ Language │ Total count │ Missing │
├──────────┼─────────────┼─────────┤
│ en       │     226     │   225   │
│ fr       │     227     │   222   │
└──────────┴─────────────┴─────────┘

(use "npm run add-locale <locale>" to add more locales)
(use "npm run extract" to update catalogs with new messages)
(use "npm run compile" to compile catalogs for production)
Compiling message catalogs…
Done!
``

Can anyone help . do you also have this kind of problem ?

**Comment by Pa22** [comment]
The same problem for me.

**Comment by GitDeluxe** [comment]
@Pa22 I fix the problem by simply run only ` lingui compile` with my message.json commited in the project . it worked like a charm .
I can close the issue .

**Comment by Pa22** [comment]
How did you get your meesage.json for all your projects text while you didn't extract lingui?

**Comment by h2dthien** [comment]
Saw this today. Can work around it with a good old `--max_old_space_size=8192` but it's strange, my repo is pretty small, not even 100 files and 30 translations

**Comment by thekip** [comment]
@h2dthien if you can profile and find what exactly bloating heap, or you can share code (privately) to allow us to profile issue it would be great. Without reproducing issue it's impossible to fix it.

**Comment by h2dthien** [comment]
@thekip Hey thanks! I can definitely do so! Let me retract our sensitive data, and send you the project. Is that ok?

**Comment by h2dthien** [comment]
So I really don't know a thing about perf, but so far I have tried:

```sh
npx --node-options="--inspect" lingui extract --clean --overwrite
```

This gives an OOM, with the following profile:

<details>
<summary>Screenshot</summary>

<img width="1264" alt="image (1)" src="https://user-images.githubusercontent.com/122243953/216871504-26664665-9b1a-475e-84a4-2fd8d49fbf67.png">
</details>

Then I tried:

```sh
npx --node-options="--inspect --max_old_space_size=8192" lingui extract --clean --overwrite 
```

This succeeds! But the profile looks almost identical:

<details>
<summary>Screenshot</summary>

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/122243953/216871573-213b762e-f977-494e-b8fd-e28b69e18794.png">
</details>

**Comment by thekip** [comment]
@h2dthien here is similar issue https://github.com/lingui/js-lingui/issues/1405 with a full repo linked. I will try to investigate there, probably it's the same problem.
