### ISSUE TITLE
v3: source lang file is not updated during extraction

### ISSUE THREAD

**Issue by gothy** [lingui/js-lingui#688]
**Describe the bug**
If you've an id for your translation and change the source lang string in the code, it doesn't get updated in the /locale/<source lang>/messages.po file after extract.

**To Reproduce**
Here's a repro repo
https://github.com/gothy/lingui-v3-source-issue

1. Clone and have a look at https://github.com/gothy/lingui-v3-source-issue/blob/master/locale/en/messages.po

2. Run `yarn extractTrans`.

3. The "welcome.title" string is still in `/locale/en/messages.po`, equal to `Welcome to <0>Next.js!</0>` the same.

```jsx
<Trans id="welcome.title">
  Welcome toooo <a href="https://nextjs.org">Next.js!</a>
</Trans>
```

**Expected behavior**
`/pages/index.jsx` file should be processed and new message(with "toooo") should be extracted to messages.po file

**Additional context**

- jsLingui version ``lingui --version`` 3.0.0-11
- Babel version ``npm list @babel/core`` @babel/core@7.9.6
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)

**Comment by pniebrzydowski** [comment]
Have you tried running it with the [Ovrewrite Flag](https://js-lingui-git-next.lingui-js.now.sh/ref/cli.html#cmdoption-extract-overwrite) `--overwrite`?

**Comment by semoal** [comment]
You need to use `--overwrite` flag in that case.
Example:
![2020-11-05 12 49 54](https://user-images.githubusercontent.com/22656541/98237635-79c45500-1f65-11eb-9c00-fde067671fd6.gif)
