### ISSUE TITLE
[Next]: Error: Invalid locale ** (missing plural rules)!

### ISSUE THREAD

**Issue by AOHUA** [lingui/js-lingui#689]
**Describe the bug**
Not able to run `compile` for some languages

**To Reproduce**
Add 'ma' or 'ta' in the configuration
Try to run `lingui compile`

**Expected behavior**
It should generate the messages.js file

**Additional context**
I used create-react-app to init the project.

How to config the plural rules?

- jsLingui version ``next``
- Babel version ``6.26.3``

**Comment by tricoder42** [comment]
Right now lingui uses plurals defined in https://github.com/eemeli/make-plural which parses CLDR plural rules. `ma` and `ta` locales are missing even in [CLDR repository](https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html) so there isn't much we can do about it :/

Unfortunatelly I don't know these locales. I guess the only option is to find the locale which is the most similar to `ma` or `ta` (i.e. similar plural rules) and then use `-ma` or `-ta` suffix.
