### ISSUE TITLE
TS error: Argument of type 'MessageDescriptor' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by capaj** [lingui/js-lingui#691]
**Describe the bug**
TS problem occurs on line 4: `Argument of type 'MessageDescriptor' is not assignable to parameter of type 'string'.`

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```ts
import { t } from '@lingui/macro'
import { i18n } from '../i18n'

i18n._(t`Succesfully removed from favorites`, {
        locationName
      })
```

**Expected behavior**
the typing is correct

**Additional context**

- jsLingui version ``lingui --version`` 2.9.1
- Babel version ``npm list @babel/core``
```
npm list @babel/core
4house-fe-web@4.5.0 /home/capaj/work-repos/4house/4house-fe-web
├── @babel/core@7.9.6 
└─┬ @graphql-codegen/typescript@1.13.5
  └─┬ @graphql-codegen/visitor-plugin-common@1.13.5
    └─┬ @graphql-toolkit/relay-operation-optimizer@0.10.6
      └─┬ relay-compiler@9.1.0
        └── @babel/core@7.9.6  deduped
```

- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)

**Comment by tricoder42** [comment]
Hey @capaj, thanks for bug report. This seems to be related to previous version. If you want to fix that, feel free to send PR agains `master`. I believe this should be already fixed in Lingui v3.
