### ISSUE TITLE
Some documentation on lingui.js.org appears to be for the unreleased version 3.x

### ISSUE THREAD

**Issue by toolness** [lingui/js-lingui#692]
It appears as though the documentation on [lingui.js.org](https://lingui.js.org/index.html) may be for a version of Lingui that hasn't yet been publicly released.

For example, as a relatively new user of Lingui, here's some things I found confusing:

* There's a section on [migration from 2.x to 3.x](https://lingui.js.org/releases/migration-3.html) which is confusing because [npm currently thinks the latest version of @lingui/core is 2.9.1](https://www.npmjs.com/package/@lingui/core).  This made me wonder if I was reading documentation from the future.

* #687 explains API inaccuracies in the [React tutorial](https://lingui.js.org/tutorials/react.html) that don't work for 2.9.1 but _do_ seem to be following [breaking changes introduced in the 3.x API]( https://github.com/lingui/js-lingui/issues/687#issuecomment-628254437).

* The macro documentation mentions a macro called [`defineMessage()`](https://lingui.js.org/ref/macro.html#definemessage) which doesn't appear to exist in version 2.9.1 of the package on NPM.

I'm just getting up to speed on things but it looks like there are actually two very important branches for this project, `master` and `next`.  As far as I can tell, `master` is the latest released version of lingui on npm (2.9.1), while `next` is the bleeding-edge 3.x version.  It seems like the documentation published at lingui.js.org is from the `next` branch, _not_ the `master` branch, which seems counter-intuitive since 2.9.1 is the version that folks who install via npm are on today.

I guess ideally the website would serve _all_ versions of the documentation at different URLs, like e.g. Django does, but since that's potentially a lot of work... should the docs at lingui.js.org be publishing docs that represent the latest version on npm, i.e. from the `master` branch instead of `next`?

**Comment by tricoder42** [comment]
Hey @toolness, thanks for raising this issue.

Docs from `master` branch is deployed to https://lingui.js.org (I've just re-deployed them).
Docs from `next` branch is deployed to https://js-lingui-git-next.lingui-js.now.sh/ (You can find more info about v3 in #334)

You're right, that some parts of v3 documentation are available in master. Since this realease is taking reaally long time, I've sync it with master several times.

I hope this clarifies things a bit. I'll take a look at #687 later today.

**Comment by telpochyaotl** [comment]
I had this exact same experience yesterday, thanks @toolness for creating this ticket.

As far as I understand v3 will be released soon, but it still would help new users if https://js-lingui-git-next.lingui-js.now.sh/tutorials/setup-cra.html described how to install v3. Presently you follow that guide and end up with 2.9.1 version installed and the rest of the tutorials don't fully work.

**Comment by tricoder42** [comment]
Indeed, the versions got mixed up. I'm working on new documentation, so it's gonna be fixed very soon.
