### ISSUE TITLE
Typescript error for <Trans /> from `@lingui/react` without children

### ISSUE THREAD

**Issue by turbothinh** [lingui/js-lingui#700]
**Describe the bug**
The Lingui 3 migration document says 
> If you used <Trans> component without children, then keep the import from @lingui/react
but apparently it doesn't work, at least with Typescript.

**To Reproduce**
1. This show typescript error "Type 'string' is not assignable to type 'Element | null'.ts(2605)
"
```
import { Trans } from "@lingui/react"

export default function App() {
   return <Trans id="msgId" />
}
```

2. Export this with `lingui export` works, adding translation to `en/message` works too but switching to other language shows raw key instead of `en` translation as a fallback.
"
```
import { Trans } from "@lingui/macro"

export default function App() {
   return <Trans id="msgId" />
}
```

**Expected behavior**
Using `<Trans id="msgId />` from `@lingui/react` without children works.
Use `<Trans id="msgId />` from `@lingui/macro` without children uses `en` translation as fallback instead of key.

**Additional context**
1. Error with `@lingui/react`
![image](https://user-images.githubusercontent.com/14198542/83029815-65ce0c00-a033-11ea-8fd3-536d8fd2d8e9.png)

2. lingui.config.js
```
module.exports = {
  locales: ['en', 'de', 'da', 'no', 'fr'], // Available locales
  fallbackLocale: 'en', // Default locale
  sourceLocale: 'en', // Add default value to English
  catalogs: [
    {
      path: '<rootDir>/locale/{locale}/messages',
      include: ['<rootDir>'],
      exclude: ['**/node_modules/**'],
    },
  ],
  format: 'minimal' // Use json as format to store trans
};
```

- jsLingui version `3.0.0-11`
- Framework: nextjs

**Comment by tricoder42** [comment]
Thanks for report. This seems to be related to upstreadm issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20544. Fixed in 585e3b2
