### ISSUE TITLE
Custom id for t macro Typescript

### ISSUE THREAD

**Issue by turbothinh** [lingui/js-lingui#701]
**Is your feature request related to a problem? Please describe.**
In Lingui 2, I can do **t('msgId')``**, but it is no longer possible with Lingui 3 in Typescript.

**Describe proposed solution**
Allow to use `t` macro with custom id in Lingui 3

**Comment by tricoder42** [comment]
In v3 there's a [`defineMessage` macro](https://js-lingui-git-next.lingui-js.now.sh/ref/macro.html#definemessage)

**Comment by alesn** [comment]
Is there a serious enough reason that what could in v2 be written as:
t('msgId')`text`
in v3 has to be written as:
i18n._(defineMessage({ id: 'msgId', message: 'text' }))
? 
This for every single message with an id ... Count the additional number of characters that have to be written and decreased readability of code

**Comment by tricoder42** [comment]
It was difficult to figure out api which would work for `t`, `plural` (and other macros), custom ids and also comments. `t('msgId')'text'` is simple, but then you need to figure out how to add translators comments and how to support other macros.

I understand the `defineMessage` macro isn't enough. I think we could use the same api of `defineMessage` with `t`:

```
t({
  id: 'msgId,
  message: 'text'
})


t({
  id: 'msgId,
  message: 'text',
  comment: 'description for translators'
})


t({
  id: 'msgId,
  message: plural(value, { one: '...', other: '...' })
})
```

Even though it's more verbose than the previous format, it's flexible enough to accomodate all usecases. `defineMessage` would be used for "lazy" translations, `t({ ... })` for immediate translations.

What do you think, @alesn?

**Comment by alesn** [comment]
@tricoder42 
Yes, I see. I'm now migrating to v3 and already came across places, where comments for translators are essential too ... The simple format `t('msgId')'text'` was at its limits like that in v2. 

The format you propose is probably the best we can get ... Both flexible, yet keeping the verbose-ness of it within some reasonable limits.

**Comment by tricoder42** [comment]
@tricoder42 This is often requested feature. I've created a new issue for it #800 . If you want, feel free to send a PR
