### ISSUE TITLE
custom plurals format not compatible with any translation tool

### ISSUE THREAD

**Issue by zsolt-dev** [lingui/js-lingui#703]
There seems to be no translations tools working with linguijs right now.

In order for lingui to gain traction, it needs to work nice with translation tools. Problem is lingui custom plurals format.

For example, this is a response from webtranslateit.com customer support:

>  this library uses its own way for declaring plurals, which is a shame since Gettext already has its own way of declaring plurals since years and years.
> 
> Unfortunately, it is very difficult for translation tools to extract these embedded plural forms and display them nicely in different text areas. I don't think this is something that should be done, because these embedded plurals can be complex and the translation tools would have to glue them back in the segment.

**Comment by tricoder42** [comment]
Hey @zsolt-dev, this library doesn't use a custom plurals format nor custom message format. It uses ICU MessageFormat. What webtranslateit refers to is a gettext message format, which is a different one.

If you want to add support for gettext then take a look at #677

**Comment by zsolt-dev** [comment]
@tricoder42 thanks for response.

Any good on-line tools for translation that works with lingui? Something that plays nice with plurals, like this:
<img width="971" alt="image" src="https://user-images.githubusercontent.com/18726534/83948955-4009e980-a821-11ea-99fd-4e7097342294.png">
