### ISSUE TITLE
v3 t macro not working?

### ISSUE THREAD

**Issue by ojii** [lingui/js-lingui#707]
I'm trying to use the `t` macro from `@lingui/macro@3.0.0-11` in a create react app, but it doesn't seem to actually display the translated value. 

To reproduce, see https://github.com/ojii/lingui-v3-t-macro-example

I expect both h1 and h2 to show the same value, but only the one using the `<Trans>` macro works, the one using `t` just shows the message id.

**Comment by tricoder42** [comment]
Interesting. What if you move `Message` and `Switcher` components to a separate file? Does it fix the issue?

**Comment by amankkg** [comment]
I had a similar issue and I guess it's due to async loading of translations. I used `useLingui` hook and during next update of a component `t` macro also shows valid translation

**Comment by ljani** [comment]
I think I'm seeing the same problem. To me, it looks like the string is translated twice. Once without the correct instance and second time with the correct instance, but with wrong key (eg. `Show 10`):

```js
i18n._(
  /*i18n*/
  _lingui_core__WEBPACK_IMPORTED_MODULE_1__["i18n"]._("Show {i}", {
    i: i
  }));
```

Thus, static texts work fine for me.

**Comment by ljani** [comment]
Production bundle seems to differ, it only returns `Show`, but in the correct translated language though. In development it always returns English `Show 10` as the key is not found.

**Comment by telpochyaotl** [comment]
I am using "next" and i have the same issue... from react, if I output `<div>{t`whatever`}</div>`  it doesn't get translated, but `<Trans>whatever</Trans>` does ...

**Comment by telpochyaotl** [comment]
After looking at documentation and source code, and trying things out, i got this to work. 

Using an approach like this:

`
const WatchLocale = ({ children }) => {
  const { i18n: lingui } = useLingui();
  // Skip render when locale isn't loaded                                                                                       
  if (!lingui.locale) {
     return null;
  }
  // Force re-render when locale changes.                                                                                       
  // Otherwise string translations (ie: t`Macro`) won't be updated.                                                             
  return <Fragment key={lingui.locale}>{children}</Fragment>;
};
const AppI18nProvider = ({ children }) => {
  useEffect(() => {
   activate('en-US');
  }, []);
  return (
    <I18nProvider i18n={i18n}>
      <WatchLocale>
        {children}
      </WatchLocale>
    </I18nProvider>
  );
};
`
So i think this is not necessarily a blocker, though the reported behavior is true. It can be worked around.

**Comment by tricoder42** [comment]
@telpochyaotl Actually, in latest pre-release I made this behavior opt-out.

https://github.com/lingui/js-lingui/blob/f44ecdd7b6f47f1230262c73a3020e128820b162/packages/react/src/I18nProvider.tsx#L64-L71

**Comment by telpochyaotl** [comment]
> @telpochyaotl Actually, in latest pre-release I made this behavior opt-out.
> 
> https://github.com/lingui/js-lingui/blob/f44ecdd7b6f47f1230262c73a3020e128820b162/packages/react/src/I18nProvider.tsx#L64-L71

Thank you so much, i will take a look at this to see what the implications of your change and statement are 👍

**Comment by ljani** [comment]
I was able to produce my issue with wrong translations. Here's a repro:
https://github.com/ljani/lingui-707

Running `npm start` and checking the dev tools shows these lines at least for me:
```text
Key1: Hello index.js:9
Translated1: Ahoj index.js:11
Key2: My name is Bar index.js:16
Translated2: My name is Bar index.js:18
My name is Bar index.js:21
```

Notice how the second one is not translated. [The documentation states that the `t` macro should return `MessageDescription`](https://js-lingui-git-next.lingui-js.now.sh/ref/macro.html#jsmacro-t), which will be translated by `i18n` in turn, but it does not do that.

Should I open a new issue?

**Comment by tricoder42** [comment]
@ljani It seems you're using v3, but lot of your code looks like v2. Could you please check the latest docs and create-react-app example in `next` branch (`examples/create-react-app`)? It was just updated to latest version in #769 so you might find some answers there

**Comment by ljani** [comment]
Are the docs published somewhere? I've been following the examples in https://js-lingui-git-next.lingui-js.now.sh/ref/macro.html

**Comment by tricoder42** [comment]
Yeah, that's the correct link. Lot of changes were published only few minutes ago, but looking at this page there're still outdated sections. I'll take a look later today

**Comment by ljani** [comment]
Oh, looking at the examples, you're not supposed to use `setupI18n` anymore? That's what got me confused as [this page](https://js-lingui-git-next.lingui-js.now.sh/ref/core.html) talks about `setupI18n` a lot.

**Comment by tricoder42** [comment]
`setupI18n` is optional now. If you use it, you should set `runtimeConfigModule` https://js-lingui-git-next.lingui-js.now.sh/ref/conf.html#runtimeconfigmodule, but unless you need something special, you're better off using the default `i18n` from `@lingui/core`

**Comment by ljani** [comment]
Great, many thanks for the clear up!

**Comment by avalladaresm** [comment]
> I am using "next" and i have the same issue... from react, if I output `<div>{t\`whatever`}` it doesn't get translated, but`whatever` does ...



> @telpochyaotl Actually, in latest pre-release I made this behavior opt-out.
> 
> https://github.com/lingui/js-lingui/blob/f44ecdd7b6f47f1230262c73a3020e128820b162/packages/react/src/I18nProvider.tsx#L64-L71

@tricoder42 I saw you reply to telpochyaotl but I don't understand what you meant with "I made this behavior opt-out." I'm having the same issue. I'm generating a translation message in a helper function, outside a functional component. But when I use a macro to display the text in JSX as 
```
<div>
  {t({ 
    id: "ProfileForm.FieldRequired", 
    message: "Required field"
  })}
</div>
```
no matter what the current locale is, "Required field" is always displayed, and if I remove the message property, "ProfileForm.FieldRequired" is displayed. 

If I put this, it works as expected with each locale but that's not what I need in my use case:
```
<Trans id="ProfileForm.FieldRequired"></Trans>
```
Any idea on how to fix it? Thank you!

**Comment by avalladaresm** [comment]
> > I am using "next" and i have the same issue... from react, if I output `<div>{t\`whatever`}` it doesn't get translated, but`whatever` does ...
> 
> > @telpochyaotl Actually, in latest pre-release I made this behavior opt-out.
> > https://github.com/lingui/js-lingui/blob/f44ecdd7b6f47f1230262c73a3020e128820b162/packages/react/src/I18nProvider.tsx#L64-L71
> 
> @tricoder42 I saw you reply to telpochyaotl but I don't understand what you meant with "I made this behavior opt-out." I'm having the same issue. I'm generating a translation message in a helper function, outside a functional component. But when I use a macro to display the text in JSX as
> 
> ```
> <div>
>   {t({ 
>     id: "ProfileForm.FieldRequired", 
>     message: "Required field"
>   })}
> </div>
> ```
> 
> no matter what the current locale is, "Required field" is always displayed, and if I remove the message property, "ProfileForm.FieldRequired" is displayed.
> 
> If I put this, it works as expected with each locale but that's not what I need in my use case:
> 
> ```
> <Trans id="ProfileForm.FieldRequired"></Trans>
> ```
> 
> Any idea on how to fix it? Thank you!

Fixed it! Since the project I'm working on was last updated 8 months ago by the owner, he was calling the `i18n` config as (maybe in an old version it worked this way?)
```
import { setupI18n } from "@lingui/core";
export const i18n = setupI18n();
```
changed it to (after updating the library to the latest version)
```
import { i18n as i18n_config } from "@lingui/core";
export const i18n = i18n_config;
```
and the `t()` macro started working fine in a JSX file.

Thanks!

**Comment by NaifAlqahtani** [comment]
> same i18n activation code

@jiakuan can you elaborate please?
