### ISSUE TITLE
Plan to make the core library-agnostic

### ISSUE THREAD

**Issue by Ugzuzg** [lingui/js-lingui#708]
**Is your feature request related to a problem? Please describe.**

I'm trying to create a [library for vue.js](https://github.com/Ugzuzg/vue-lingui) using `@lingui/core`. The main two issues I have are
- [the parts parser code](https://github.com/lingui/js-lingui/blob/next/packages/react/src/format.ts) is inside `@lingui/react` and will [have to be duplicated.](https://github.com/Ugzuzg/vue-lingui/blob/master/src/components/Trans.vue#L6-L46);
- babel configuration can't be reconfigured. I was hoping to be able to extract some strings at least from `<script>` tag from vue, as it is just javascript. Obviously the parser will not work with templates in its current from.

**Comment by tricoder42** [comment]
Hey @Ugzuzg,

> the parts parser code is inside @lingui/react and will have to be duplicated

Sure, let's move it to separate package. Or maybe would be enough to move it to `core` pacakge?

> babel configuration can't be reconfigured. I was hoping to be able to extract some strings at least from <script> tag from vue, as it is just javascript. Obviously the parser will not work with templates in its current from.

Could you please provide more details? What exactly do you need and what solution do you suggest?

**Comment by Ugzuzg** [comment]
> Or maybe would be enough to move it to core pacakge?

`core` sound like the right place for this.

> Could you please provide more details? What exactly do you need and what solution do you suggest?

I haven't worked with babel at all, but as I understand, vue extracts javascript and passes it through babel, so it is possible to make the `t` macro work with vue by specifying the vue plugins in babel. `Trans` macro won't work, though, as it is react specific.
