### ISSUE TITLE
@lingui/cli v3 extract extracts no messages

### ISSUE THREAD

**Issue by kub1x** [lingui/js-lingui#709]
**Describe the bug**
When I run `yarn lingui extract` the po files gets created in the correct location, but they contain no messages, only header lines. 

**To Reproduce**
* This is a Expo (react-native) project. 
* Using `@lingui/react` for `useLingui` hook only. 
* Using only macros, no `@lingui/react` components.

```
import { Trans, t } from "@lingui/macro"

export default function App() {
   return (<View>
     <Trans>Tohle přelož!</Trans>
     <Button title=t`Zavřít` />
   </View>)
}
```
Running command `yarn lingui extract` with following output: 
```
yarn run v1.22.4
$ /<my project dir>/node_modules/.bin/lingui extract
(use "yarn lingui extract" to update catalogs with new messages)
(use "yarn lingui compile" to compile catalogs for production)
Done in 0.74s.
```
Po files are created, but contain only header lines as follows: 
```
$ cat assets/locale/cs.po 
msgid ""
msgstr ""
"POT-Creation-Date: 2020-06-19 15:20+0200\n"
"Mime-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: @lingui/cli\n"
"Language: cs\n"
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"PO-Revision-Date: \n"
"Last-Translator: \n"
"Language-Team: \n"
"Plural-Forms: \n"
```

**Expected behavior**
Messages should be extracted into po files. Extraction worked with v2 cli. 

**Additional context**
- jsLingui version `yarn lingui --version`
```3.0.0-13```

- Babel version `npm list @babel/core`
```
├── @babel/core@7.10.2 
└─┬ babel-preset-expo@8.2.1
  ├─┬ @babel/preset-env@7.9.6
  │ ├─┬ @babel/plugin-proposal-nullish-coalescing-operator@7.8.3
  │ │ └── @babel/core@7.9.6  extraneous
  │ ├─┬ @babel/plugin-proposal-object-rest-spread@7.9.6
  │ │ └── @babel/core@7.9.6  extraneous
  │ ├─┬ @babel/plugin-proposal-optional-catch-binding@7.8.3
  │ │ └── @babel/core@7.9.6  extraneous
  │ ├─┬ @babel/plugin-proposal-optional-chaining@7.9.0
  │ │ └── @babel/core@7.9.6  extraneous
  │ ├─┬ @babel/plugin-transform-async-to-generator@7.8.3
  │ │ └── @babel/core@7.9.6  extraneous
  │ └─┬ @babel/plugin-transform-modules-commonjs@7.9.6
  │   └── @babel/core@7.9.6  extraneous
  └─┬ metro-react-native-babel-preset@0.56.4
    ├─┬ @babel/plugin-proposal-class-properties@7.8.3
    │ └── @babel/core@7.9.6  extraneous
    └─┬ @babel/plugin-transform-flow-strip-types@7.9.0
      └── @babel/core@7.9.6  extraneous
```

- Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)
```
$ cat babel.config.js 
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['macros'],
  };
}
```

- This is my `.linguirc`
```
{
   "locales": [ "cs", "en", "de", "pl" ],
   "catalogs": [
    {
      "path": "assets/locale/{locale}",
      "include": [ "js", "App.js" ],
    },
   ],
   "format": "po",
   "sourceLocale": "cs"
}
```

- my lingui stuff versions: 
```yarn list --pattern @lingui
yarn list v1.22.4
├─ @lingui/babel-plugin-extract-messages@3.0.0-13
├─ @lingui/cli@3.0.0-13
├─ @lingui/conf@3.0.0-13
├─ @lingui/core@3.0.0-13
├─ @lingui/macro@3.0.0-13
└─ @lingui/react@3.0.0-13
```

I am aware v3 is not in production. Does that mean extraction don't work yet? https://github.com/lingui/js-lingui/issues/334

I have seen this bug, but it seems to be related to v2 and react components. 
https://github.com/lingui/js-lingui/issues/415

Thanks in advance

**Comment by tricoder42** [comment]
Hey @kub1x,
this might be bug that `@lingui/cli` doesn't correctly recognize yoru babel config. What if  you have a simple static file instead of function, e.g:

```
// .babelrc
{
    "presets": ['babel-preset-expo'],
    "plugins": ['macros'],
}
```

**Comment by kub1x** [comment]
@tricoder42 You're absolutely right! Changing babel config from module to JSON did the trick. Thank you very much.

**Comment by kub1x** [comment]
Sadly after some time I tried to run `yarn lingui extract` again now with lingui v3.0.0 and JSON form of `.babelrc` but with no result again. `.po` files get created, but contain no extracted messages, only headers. I'm reopening as it is exactly the same symptoms as before. Only this time I see a nice table at the end, stating nothing got extracted. 
```
% yarn lingui extract --verbose
yarn run v1.22.10
$ /.../lingui-noextract-repro/node_modules/.bin/lingui extract --verbose
Extracting messages from source files…
Catalog statistics for assets/locales/{locale}/messages: 
┌─────────────┬─────────────┬─────────┐
│ Language    │ Total count │ Missing │
├─────────────┼─────────────┼─────────┤
│ en (source) │      0      │    -    │
│ cs          │      0      │    0    │
└─────────────┴─────────────┴─────────┘

(use "yarn lingui extract extract" to update catalogs with new messages)
(use "yarn lingui extract compile" to compile catalogs for production)
✨  Done in 1.07s.
```

I did try to put content of `.babelrc` into `.linguirc`'s `extractBabelOptions` property. Same result. 

Here is the **repro repository**. Just clone and run `yarn`, `yarn lingui extract` and look into `assets` directory. 
**https://github.com/kub1x/lingui-noextract-repro**

This might be some stupid thing, but I feel like I've been looking everywhere.

**Comment by tricoder42** [comment]
Missing trailing slash in your `include` paths. Without slash the path is treated as a file, not directory

```diff
{
   "locales": [ "cs", "en", "de", "pl" ],
   "catalogs": [
    {
      "path": "assets/locale/{locale}",
-      "include": [ "js", "App.js" ],
+      "include": [ "js/", "App.js" ],
    },
   ],
   "format": "po",
   "sourceLocale": "cs"
}

**Comment by kub1x** [comment]
@tricoder42 Did you try it after the fix? It didn't help for me. Still no messages gets extracted. There is also one message in `App.js` that wouldn't be affected by the config error you mentioned. I've pushed the `js/` fix in the repro repo and thank you for the catch. But it is not fixed.

**Comment by tricoder42** [comment]
You're right, the root cause is that there're multiple paths. I've already fixed the bug and waiting for CI #803. Will release soon

**Comment by kub1x** [comment]
@tricoder42 confirmed. That did it. Thanks!

**Comment by tricoder42** [comment]
@kub1x Released in [3.0.3](https://github.com/lingui/js-lingui/releases/tag/v3.0.3). Cheers 👍

**Comment by mediaxtend** [comment]
@tricoder42, the extraction also fails with only one path (using `.linguirc` of [documentation](https://lingui.js.org/tutorials/setup-cra.html#install), for example): `"include": ["src"]`.
If I change it for `"include": ["src/"]`, translations are correctly extracted.
I'm using:
- Lingui 3.0.3
- CRA 4.0

**Comment by tricoder42** [comment]
This is mistake in docs. Directories must always end with slash
