### ISSUE TITLE
Comments inside Trans blocks result in JSXEmptyExpressionError

### ISSUE THREAD

**Issue by Serban-PLT** [lingui/js-lingui#710]
**Describe the bug**
Hi! Not sure if a bug or by design, but when including a comment in a `<Trans>` block it gets parsed as empty JSX and throws the following error:

```
@lingui/macro: Property value of ObjectProperty expected node to be of a type ["Expression","PatternLike"] but instead got "JSXEmptyExpression" Learn more: https://www.npmjs.com/package/@lingui/macro
```

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```
import { Trans } from "@lingui/macro"

export default function App() {
   return (
      <Trans>
        {/* comment which results in the above error */}
        words to translate
       </Trans>
  )
}
```

**Expected behavior**
I would have expected either ignoring the comment silently or if possible a clearer definition of why the error is occurring. I appreciate though it's possible comments can't be read by the interpreter.

- jsLingui version ``lingui --version``
```
    "@lingui/babel-preset-react": "^2.8.3",
    "@lingui/cli": "^2.8.3",
    "@lingui/macro": "^2.8.3",
    "@types/lingui__macro": "^2.7.3",
```
- Babel version ``npm list @babel/core``
```
    "babel-core": "^7.0.0-bridge.0",
```

**Comment by tricoder42** [comment]
Hey @Serban-PLT, comments aren't probably supported yet. If you want to implement them, there's a huge [list of test cases](https://github.com/lingui/js-lingui/blob/next/packages/macro/test/jsx-trans.ts) for Trans macro. Just add yours and then provide implementation in [macroJsx.ts](https://github.com/lingui/js-lingui/blob/next/packages/macro/src/macroJsx.ts)

**Comment by tricoder42** [comment]
Also, please use `next` branch as a base.

**Comment by tricoder42** [comment]
Comments are actually supported already in v3:

https://github.com/lingui/js-lingui/blob/2d9e124b91f1ba7a65e9f997a3ba952679c6c23a/packages/macro/test/jsx-trans.ts#L332-L342
