### ISSUE TITLE
Trans element always passes children as an array

### ISSUE THREAD

**Issue by ckknight** [lingui/js-lingui#715]
**Describe the bug**
When using the `<Trans>` element with a nested element, the `children` prop for that nested element is always an array, even when it wouldn't otherwise be.

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```
import * as React from "react";
import { Trans } from "@lingui/macro"

function X({ children }) {
  React.Children.only(children)
  return null;
}

export default function App() {
   return <Trans><X>Hello!</X></Trans>
}
```

**Expected behavior**
`children` should be passed to the `X` component as a single `"Hello!"` string.

**Actual behavior**
`children` is being passed to the `X` component as a single-element `["Hello!"]` array.

**Additional context**

- jsLingui version ``lingui --version``: 2.9.1
- Babel version ``npm list @babel/core``: @babel/core@7.7.0
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.): create-react-app

**Comment by tricoder42** [comment]
Interesting, thank you! I believe there should be a simple if-block to deal with this edge case. Could you send a patch either agains `next` branch or both `master` and `next` (in case you want to backport it to v2)? I guess all changes should be made in https://github.com/lingui/js-lingui/blob/next/packages/react/src/format.ts file.

**Comment by aohua** [comment]
Hi @ckknight, are you sure that you are getting ["Hello!"] instead of "Hello"? I can reproduce the issue, however, it is because of [React.Children.onlyChild throws on text child](https://github.com/facebook/react/issues/1104).

**Comment by tricoder42** [comment]
Hey @ckknight, new version 3.x was released which changed rendering of translations inside Trans component. Please check if the problem persists.
