### ISSUE TITLE
More convenient way to translate React properties

### ISSUE THREAD

**Issue by joonazan** [lingui/js-lingui#716]
In my app there are a lot of properties that need to be translated. Putting `<I18n>{({ i18n }) =>` in front of every one seems like a lot of clutter to me. I am not familiar with Babel. Could I use it to make a code transformation that automatically adds those?

Also, I can't figure out how to translate @react-navigation/bottom-tabs at all. You can only translate one thing with one i18n but the i18n tag is not allowed between the tab navigator and its child. So currently I'm able to translate just one tab.

**Comment by tricoder42** [comment]
Hey @joonazan, in Lingui v3 (currently available only as a prerelease) you can use `t` macro `<img alt={t'Translated image caption'} src={...} />`. Unfortunately it's a breaking change and can't be backported back to v2.
