### ISSUE TITLE
Use modern React Context #2

### ISSUE THREAD

**Issue by nikneb** [lingui/js-lingui#718]
Getting the error in Strict mode:

```
Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: I18nProvider

```

And getting the same error for: I18n  and WithI18n
 
 Is this fixed?
"@lingui/react": "^2.9.1",
"react": "^16.13.0",

_Originally posted by @nikneb in https://github.com/lingui/js-lingui/issues/622#issuecomment-668140916_

**Comment by tricoder42** [comment]
Hey @nikneb,
as mentioned in linked issue:

> Next version (in next branch) already uses new context. It just waits until final release.

Unfortunately it can't be backported to 2.x because it's a breaking change. If you want to try 3.x you need to use pre-release, because the final version still isn't available.
