### ISSUE TITLE
Variables not being substituted in production build

### ISSUE THREAD

**Issue by FSM1** [lingui/js-lingui#719]
**Describe the bug**
Some interpolated string variables aren't being rendered in the production build, but render correctly when running the development server.

**To Reproduce**
```
import { t, Trans } from "@lingui/macro";

export default function App() {
  const {
    ...
    CONTRACT_DURATION,
    ...
  } = useContext(...);
   return <Trans>Buy ${CONTRACT_DURATION}-Day Mining Revenue Contract</Trans>
}
```

**Expected behavior** - This works when running the CRA dev server
![image](https://user-images.githubusercontent.com/12774278/89955640-c7197a80-dc33-11ea-89bb-77c07a000e8e.png)

**Actual behaviour** - This is the result in the production build
![image](https://user-images.githubusercontent.com/12774278/89955728-f03a0b00-dc33-11ea-8cf4-87bb8e3bf820.png)

**Additional context**
This happens with a number of other simple variables substitutions on the page, some originating from context variables, others coming from component state (`const [orderTotal, setOrderTotal] = useState<number>(0)`)
![image](https://user-images.githubusercontent.com/12774278/89955911-54f56580-dc34-11ea-9db9-4c95827e4491.png)

- jsLingui version 2.9.1
- Babel version @babel/core@7.10.5
- CRA with typescript

**Comment by nathanforce** [comment]
Hello,

I'm seeing a similar issue but within my `jest` tests instead of `production`.  After the macro is parsed there is no `values={}` prop passed to `<Trans />`.

**Comment by nathanforce** [comment]
> Hello,
> 
> I'm seeing a similar issue but within my `jest` tests instead of `production`. After the macro is parsed there is no `values={}` prop passed to `<Trans />`.

For me the issue was related to my components be transpiled by `ts-jest` before the macro was able to handle them.

**Comment by FSM1** [comment]
This doesnt seem to be the case in my instance. The values prop is being passed in to `<Trans>` correctly. 

This is the production build (where the substitution doesn't work):
![image](https://user-images.githubusercontent.com/12774278/90322474-e4608880-df54-11ea-8b83-9d1fee3dcd70.png)

The same <Trans> component in the development build:
![image](https://user-images.githubusercontent.com/12774278/90322500-5769ff00-df55-11ea-9c88-a2349be86f0d.png)

**Comment by FSM1** [comment]
Additionally, just tested with lingui 3 and still receiving the same results.

**Comment by khmm12** [comment]
@FSM1 Do your catalogs contain the translation? In development lingui creates missing catalogs values on the fly.

**Comment by FSM1** [comment]
@khmm12 by catalog, do you mean the `.PO` file or the generated `messages.js` file?

Either case, while I am not sure what fixed the issue in my case, but something in this commit fixed the issue: https://github.com/carboclan/dapp.honeylemon.market/commit/cfd5b4a3c0d74e39f60d41b8d721ad01263788ed

**Comment by khmm12** [comment]
@FSM1 

> by catalog, do you mean the .PO file or the generated messages.js file?

`messages.js` in that case. Compiled lingui catalog is `messages` + `localeData`. 

> Either case, while I am not sure what fixed the issue in my case, but something in this commit fixed the issue: carboclan/dapp.honeylemon.market@cfd5b4a

[This line](https://github.com/carboclan/dapp.honeylemon.market/commit/cfd5b4a3c0d74e39f60d41b8d721ad01263788ed#diff-c6107620ccd3ed63b6fdd205c81f76dcR13) fixed the issue in your case since you use v3 version where `load` has been splitted into `load` and `loadLocaleData` [(Migration guide)](https://js-lingui-git-next.lingui-js.now.sh/releases/migration-3.html#removed-i18nprovider-declarative-api). 

To find a reason for v2 version, needs to check what imported catalog contains.
