### ISSUE TITLE
using a wrapper arround js-lingui

### ISSUE THREAD

**Issue by herzaso** [lingui/js-lingui#72]
In order to remove dependency on the i18n package, I tried making a single-point-of-entry file for i18n.
Something along the lines of:
```javascript
import {withI18n, Trans} from 'lingui-react'

export {
	Trans,
	withI18n
}
```

However, this resulted in two problems:
1. lingui-cli didn't collect any massage (using `lingui extract`)
2. I got a warning 

> lingui-react preset is probably missing in babel config...

although lingui-react is not missing in babel config file (without the wrapping file, the warning is gone).
Also, all strings were seen as empty in the application.

Is this unsupported? Am I doing it wrong?

**Comment by tricoder42** [comment]
Hi @herzaso,
unfortunately, this is not possible yet. Babel plugin (for transforming and extracting) is looking from `Trans` component from `lingui-react` package, so if import it from different place, it won't find it.

Could you please explain your usecase? What do you mean by `i18n package` and why are you trying to remove it?

**Comment by herzaso** [comment]
At the moment, lingui looks like a promising package. However, since there are few maintainers and the traction from the community is not that high, there is a risk in using it for large applications.

In an effort to mitigate that risk, I thought about wrapping the i18n utilities, so I would be able to take control in the future if needs be without having to change my entire application.

**Comment by tricoder42** [comment]
I understand your concerns. I'm using this library in my project, so it won't go away anytime soon.

However, if I got hit by a tram accidentally and wouldn't be able to transfer ownership of this repo to other maintainer, you could still fork it, release it under your namespace (e.g: `@herzaso/lingui-react` or even different name) and then just search&replace all occurrences of `lingui-react`, right? As long as the API stays the same (as your example suggests), it's just a matter of renaming imports.

I mean, we could add `packageName` option to all babel plugins, but I really don't want to complicate things at this point so much.

Anyway, I appreciate your feedback! 👍

**Comment by herzaso** [comment]
My example was simplified for the sake of making an argument.
In a large scale application, I'm not sure that a simple search and replace method would cut it.

Either way, it's your call...

**Comment by tricoder42** [comment]
If you wish to take initiative on this, the steps to implement such feature are follows:

1. Add new config to `lingui-conf`, sth like:

  ```js
  // default value 
  {
    "lingui": {
      "transformPackageName": {
        "react": "lingui-react",
        "js": "lingui-i18n"
      }
    }
  }
  ```

2. Update `babel-plugin-transform-lingui-react` to read this config and check for `Trans` component from custom package. Right now it only checks for `lingui-react` package.

3. That's all! Right now there's no checking for imports in `lingui-i18n`. I need to figure out, how to make it work.

**Comment by herzaso** [comment]
Sorry @tricoder42 , I was preoccupied with other things.
Do you want me to issue a PR for this feature or did you just mention these steps so I could make the adjustments on my environment?

**Comment by tricoder42** [comment]
No worries! I was thinking about PR. You would have to fork both libs to make local adjustments, which seems to be suboptimal.

Cheers! 👍

**Comment by herzaso** [comment]
Sorry @tricoder42 , I couldn't find how to pass the option validation (jest), and I don't have much time to work on it :(

**Comment by tricoder42** [comment]
Alright, let's close it for now and open it later when the time comes.Thank you anyway!

Right now I'm trying to figure out easier development setup and catalog namespaces so I could add support for code splitting...
