### ISSUE TITLE
Is possible to kill localization row numbers?

### ISSUE THREAD

**Issue by landsman** [lingui/js-lingui#720]
I really love this tool!
There is just one thing which make me nervous in every code review in my team - comments in locale files.

**Example:** 
```
#: src/components/footer.jsx:30
#: src/components/header.jsx:35
#: src/components/header.jsx:96
msgid "menu.link.blog"
msgstr "Blog"
```

Every single change in files: footer.jsx, header.jsx, header.jsx will make change in localization file too, because number of the row with translate will be changed.

Is somehow posible to disable these comments in localization files please?

**Comment by tricoder42** [comment]
Hey @landsman,
I'm afraid this feature is only available in pre-release of v3: https://js-lingui-git-next.lingui-js.now.sh/ref/conf.html#formatoptions (from #661).

For now you could run `sed` after extract: `yarn extract; find locales -type f -name "*.po" -exec sed -i '' '/^#:/d' {} +`

**Comment by landsman** [comment]
@tricoder42 thank you for reply and workaround solution! 
So, these comments is not required for correct work of Lingui, right?

**Comment by tricoder42** [comment]
Definitely not now
