### ISSUE TITLE
`lingui extract` command prints possibly misleading messages

### ISSUE THREAD

**Issue by amankkg** [lingui/js-lingui#727]
**Is your feature request related to a problem? Please describe.**
Not really a problem, more like a UX issue. 

After `lingui extract` command finishes there is a message which is likely to be irrelevant due to user's different script configuration. The message is:

```sh
(use "npm run extract" to update catalogs with new messages)
(use "npm run compile" to compile catalogs for production)
```

**Describe proposed solution**
Print a message without assuming that there are user-defined npm scripts at all:
```sh
(run "lingui extract" command to update catalogs with new messages)
(run "lingui compile" command to compile catalogs for production)

# OR

(use "npx lingui extract" to update catalogs with new messages)
(use "npx lingui compile" to compile catalogs for production)
```
And, if Yarn is used then it should be `use "yarn lingui ...` appropriately. This is being detected already.

**Describe alternatives you've considered**
Not printing this block at all

**Additional context**
I have a project with junior developers and such messages can be misleading to them. Now I have to document this so they know that in our setup these two operations use different script names.

Here is my scripts section
```json
"scripts": {
  "locales:extract": "lingui extract",
  "locales:build": "lingui compile",
  "locales:dev": "onchange \"src/**/*.{ts,tsx}\" -- npm run locales:extract"
}
```

**Update:** proposed a solution with `npx`, added my scripts configuration which leads to irrelevant suggestions message

**Comment by tricoder42** [comment]
Hey @amankkg, what command you use to run `lingui`? CLI tries to detect it and show appropriate help message (see https://github.com/lingui/js-lingui/blob/next/packages/cli/src/api/help.ts). We could tweak it to provide accurate command.

> Print a neutral to npm scripts message, e.g. run "lingui extract" ... and run "lingui compile"...

That might be confusing as well, because `lingui` isn't global. Or do you mean `npm run "lingui extract"`?

> Not printing this block at all

I don't consider it as viable alternative. I like helpful suggestions of `git` CLI and I would like to provide them as well.

**Comment by amankkg** [comment]
Here is my scripts section
```json
"scripts": {
  "locales:extract": "lingui extract",
  "locales:build": "lingui compile",
  "locales:dev": "onchange \"src/**/*.{ts,tsx}\" -- npm run locales:extract",
  etc...
}
```
and when I run `locales:extract` script I see this message
```sh
(use "npm run extract" to update catalogs with new messages)
(use "npm run compile" to compile catalogs for production)
```
> Or do you mean `npm run "lingui extract"`?

No, my suggestion is to not pre-assume that there is a specific npm script for any lingui command. Other option might be a message like `(use "npx lingui extract" to ...)`.

> CLI tries to detect it and show appropriate help message. We could tweak it to provide accurate command.

OK. As I can see now there are few templates for these commands: `npm run compile|extract`, `yarn compile|extract` and `yarn lingui compile|extract` and my use case from above doesn't fit any of these, right?

**Comment by tricoder42** [comment]
Yeah, exactly. Looking at your `scripts` there's no way to make it work for everyone. Let's keep it open for a while and think it through. Changing help texts isn't a breaking change so we can do it anytime.

**Comment by tricoder42** [comment]
As I mentioned before, there's no way to detect how commands are configured inside `package.json`. I guess we could improve help messages by user configurable commands:

```json
{
   "cliCommandsHelp": {
     "extract": "npm locales:extract",
     "compile": "npm locales:build"
   }
```

and optionally disabling these help messages completely:

```json
{
   "cliCommandsHelp": null
}
```

If you like the idea, feel free to send a PR

**Comment by semoal** [comment]
![Screenshot 2020-11-05 at 13 17 15](https://user-images.githubusercontent.com/22656541/98240141-45eb2e80-1f69-11eb-8ac0-8fd5cf973b08.png)
I've built a solution that searches the indicated commands in the package.json and indicates the correct one to run, if any found fallback to the standard usage (yarn or npm extract/compile)

**Comment by tricoder42** [comment]
That sounds awesome 👍
