### ISSUE TITLE
"Trans is not defined" error when using only Plural

### ISSUE THREAD

**Issue by vitexikora** [lingui/js-lingui#73]
Lingui fires "Uncaught (in promise) ReferenceError: Trans is not defined" in a component that doesnt use Trans, only Plural (it is likely transformed?). But when I supply Trans, my linter is on fire (its not used) ...
I have to stick with: 
```js
import { withI18n, Trans, Plural } from 'lingui-react' // eslint-disable-line no-unused-vars 
```
in every component...

lingui-react 1.1.0
anyway, great job on the repo!

**Comment by tricoder42** [comment]
What version of `babel-preset-lingui-react` or `babel-plugin-lingui-transform-react` do you have?

**Comment by tricoder42** [comment]
Nevermind, I see the bug. Sorry, this is shameful 😳

**Comment by tricoder42** [comment]
Alright, false alarm. I can't reproduce it. There's also test case for it.

So, what version of babel-preset-lingui-react or babel-plugin-lingui-transform-react do you have?

**Comment by vitexikora** [comment]
Ups, I am very sorry, I didn't have the plugin `lingui-transform-react` included in `.babelrc`, only the preset... Wondering, that it had still otherwise worked 😮

**Comment by tricoder42** [comment]
That's interesting... plugin is part of preset, so you shouldn't include it manually unless you have a reason to do so. Could you please share your `.babelrc` config?

**Comment by vitexikora** [comment]
```js
{
    "plugins": [
        "transform-decorators-legacy",
        "transform-class-properties",
        "transform-es2015-classes",
        "transform-proto-to-assign",
        "transform-runtime",
        "lingui-transform-react", // <- this line is new
        "syntax-dynamic-import"
    ],
    "presets": [
        "react",
        "es2015",
        "lingui-react",
        "stage-0",
    ]
}
```
however, before doing so, I also ran a `npm up lingui-react --save` which updated my lingui from 1.1.0 to 1.1.1
