### ISSUE TITLE
Make the Babel extractor to support all the file extensions that Babel supports

### ISSUE THREAD

**Issue by laszbalo** [lingui/js-lingui#739]
**Is your feature request related to a problem? Please describe.**
Hi, it would be really great, if Lingui's extractor could extract the messages from .mjs files. Since Lingui's is using Babel for that, why not to add support for all the [default extensions Babel](https://babeljs.io/docs/en/babel-core#default_extensions) supports?

**Describe proposed solution**
Make the Babel extractor to use the `@babel/core`'s read-only `DEFAULT_EXTENSION` array to determine which files to extract messages from.

**Describe alternatives you've considered**
Only use the `.js`, `.jsx` subset of the default extensions.

**Comment by tricoder42** [comment]
Hey @laszbalo, sounds good! Feel free to send a PR 👍 

PS: I'm gonna review the other PRs of yours today. I've just got back from vacation and I'm kinda busy

**Comment by laszbalo** [comment]
No worries. Just take your time. Hope it was a good one.

**Comment by tricoder42** [comment]
Closed by #740
