### ISSUE TITLE
Plural prop "zero" does not work as expected

### ISSUE THREAD

**Issue by vitexikora** [lingui/js-lingui#74]
Given
```js
const resultCount = 0
```
This component:
```js
<Plural
    value={resultCount}
    zero={`Nenalezen žádný koncert`}
    one={`Nalezen jeden koncert`}
    few={`Nalezeny ${resultCount} koncerty`}
    other={`Nalezeno ${resultCount} koncertů`}
/>
```
renders `Nalezeno 0 koncertů`

While this component:
```js
<Plural
    value={resultCount}
    _0={`Nenalezen žádný koncert`}
    one={`Nalezen jeden koncert`}
    few={`Nalezeny ${resultCount} koncerty`}
    other={`Nalezeno ${resultCount} koncertů`}
/>
```
renders `Nenalezen žádný koncert`

Tested only in dev environment, lingui-react 1.1.0.

+ followup slightly related question: 
How to get React elements into plural? 
eg. `Nalezeno <span className={cls.highlight}>{resultCount}</span> koncertů`

**Comment by tricoder42** [comment]
Unfortunately, Czech language doesn't have `zero` plural category. See the official [cldr page](http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#cs)

So, the second example is actually correct!

Answer to follow up - the same way as you use React elements for singular:
```js
<Plural
    value={resultCount}
    _0={<Trans>Nenalezen <strong>žádný</strong> koncert</Trans>}
    one={<Trans>Nalezen jeden koncert</strong>}
    few={<Trans>Nalezeny <span className={cls.highlight}>${resultCount}</span> koncerty</Trans>}
    other={<Trans>Nalezeno <span className={cls.highlight}>${resultCount}</span> koncertů</Trans>}
/>
```

Feel free to reopen if you had more questions 👍

**Comment by tricoder42** [comment]
By the way, you can combine also other i18n components, like Plural, Select, Trans. See the [test case](https://github.com/lingui/js-lingui/blob/master/packages/babel-plugin-lingui-transform-react/test/fixtures/nested-components/actual.js).
