### ISSUE TITLE
Catalog statistics in json format

### ISSUE THREAD

**Issue by ccamusso** [lingui/js-lingui#746]
Hi,
It would be very useful if the 'lingui extract' command could create a json file with inside catalog statistics info

Carlo

---

- [ ] Add `--stats <file>` option to `lingui-extract.ts` command. If it's present, write catalog stats as a JSON at the end of `extract` command
- [ ] Add documentation to CLI reference guide (`docs/ref/cli.rst`)

**Comment by tricoder42** [comment]
Hi Carlo,
sure, that sounds reasonable. What about adding flag `--stats <file>` to `extract` command? Please use `next` branch as a base for your PR. Let me know if I can help with anything.

**Comment by ccamusso** [comment]
Ok

**Comment by tricoder42** [comment]
Hey @ccamusso, are you working on this issue or should I mark it as open for contributors?

**Comment by ccamusso** [comment]
I haven't started, I'd like to but I think I'll be able to work on it
