### ISSUE TITLE
Review create-react-app setup guide

### ISSUE THREAD

**Issue by ahmedosama5200** [lingui/js-lingui#748]
Edit by @tricoder42:

Installation instructions for create-react-app projects are obsolete. They need to be updated to reflect latest changes in Lingui v3 and create-react-app.

- [ ] Setup LinguiJS in fresh create-react-app
- [ ] Update https://github.com/lingui/js-lingui/blob/next/docs/tutorials/setup-cra.rst

--- 

Original post by @ahmedosama5200:

In the official docs [here](https://lingui.js.org/tutorials/setup-cra.html#install), It referes to create-react-app version 2 and that we need to install `@babel/core` and `babel-core@bridge`.
Do we still need to install them with version 3.4

**Comment by ahmedosama5200** [comment]
It seems like the documentation hasn't been touched in a long time

**Comment by tricoder42** [comment]
@ahmedosama5200 You're right, that page hasn't been updated. If you have experience with CRA 3.4, could you please try it without `@babel/core` and `babel-core@bridge`? If everything works, please send a PR with update docs. Thanks!

**Comment by ahmedosama5200** [comment]
I don't understand. There are a lot of open issues. Is the project not well maintained. It's really worth your time. This is the only complete react i18n solution that has this small size.

**Comment by tricoder42** [comment]
I'm gradually working through them but as a solo maintainer I need all the help available. Me personally, I don't use create-react-app, but rather Next.js so I can't really help with fixing CRA example. If you're CRA user, go ahead and send a PR. I'm happy to answer any questions you have

**Comment by semoal** [comment]
@tricoder42 Assign to me this Tomáš, I'll review the CRA setup, some days ago i've built a setup with redux and cra to another issue, so probably i could take a look to the documentation

**Comment by tricoder42** [comment]
@semoal Go ahead. Thanks a lot! Feel free to ditch original setup guide completely, create a fresh CRA project, add Lingui and then document your steps. So far there's just Next.js project inside `examples` directory.

**Comment by tricoder42** [comment]
I believe this is fixed in #769
