### ISSUE TITLE
pluralize(id, config) Broken

### ISSUE THREAD

**Issue by fny** [lingui/js-lingui#752]
**Describe the bug**
```jsx
<I18n>
 {({i18n}) => 
    i18n.plural('id', { value: 1 one: "one", other: "other" })
 )}
</I18n>
```

Error:

```
TypeError: Cannot read property 'toString' of undefined
I18n.plural
node_modules/@lingui/core/cjs/core.development.js:191
  188 | 
  189 | var diff = value - offset;
  190 | var diffAsString = number(locales, format)(diff);
> 191 | var translation = pluralForms[value.toString()] || // exact match
      | ^  192 | pluralForms[i18n.pluralForm(diff, type)] || // plural form
  193 | other; // fallback
  194 | return translation.replace("#", diffAsString);
```

- jsLingui version ``lingui --version`` 2.9.2
- Babel version ``npm list @babel/core`` @babel/core@7.11.6
- Create React App

**Comment by fny** [comment]
Also i18n is not extracting these.

**Comment by tricoder42** [comment]
Hi @fny, this issue seems to be fixed in v3. I've just add plurals to `next-js` example (see 669caf2c) and both `<Plural>` component and `plural` macro work as expected.

I don't have resources to help you with v2, but if you send a PR I'm happy to merge it and release a patch.
