### ISSUE TITLE
React "two children with same key" warning from `<Trans>` macro

### ISSUE THREAD

**Issue by agwells** [lingui/js-lingui#757]
**Describe the bug**
When using the `<Trans>` macro, if the language string contains two instances of the same variable, _and_ that variable's value is a JSX element, Lingui generates two sibling elements with the same `key` prop. This causes React to complain, because the `key` prop is required to be unique for sibling elements.

**To Reproduce**
Here is a Storybook story that reproduces the issue:

```
import React from 'react';
import { Trans } from '@lingui/macro';
import { storiesOf } from '@storybook/react';
import { I18nProvider } from '@lingui/react';

const foo = <span>bar</span>;

storiesOf('lingui', module).add('two children with the same key', () => (
  <I18nProvider language="en">
    <Trans>
      {foo} {foo}
    </Trans>
  </I18nProvider>
));
```

**Expected behavior**
The story displays "bar bar" when viewed in the browser, with no warnings or errors in the JS console.

**Actual behavior**
The story displays correctly in the browser, but it generates React elements with the same key of `0`, and React prints a warning about that to the JS console:

```
Warning: Encountered two children with the same key, `0`. Keys
should be unique so that components maintain their identity across
updates. Non-unique keys may cause children to be duplicated
and/or omitted — the behavior is unsupported and could change in a
future version.
    in Render (created by Trans)
    in Trans (created by I18n)
    in I18n (created by WithI18n)
    in WithI18n (at lingui.stories.tsx:10)
    in I18nProvider (at lingui.stories.tsx:9)
    in storyFn
    in ErrorBoundary
```
When the rendered components are viewed using the React Dev Tools browser plugin, I can see this hierarchy of components:

* `WithI18n`
    * `I18n`
        * `Trans`
            * `Render`
                * `span key="0"`
                * `span key="0"`

**Additional context**
- jsLingui version 2.9.2
- Babel version 7.9.0
- Create React App (react-scripts 3.4.3)

**Comment by tricoder42** [comment]
Hi @agwells, yeah this might be probably bug. Could you please confirm it's hapenning also in v3 (it's in pre-release)?

**Comment by semoal** [comment]
I can confirm that is also happening on v3, i'll take a look

**Comment by tricoder42** [comment]
Thank you @semoal. I think it must be somewhere in `formats.ts` file (`@lingui/react` package), but there's an `index` set as a key here

https://github.com/lingui/js-lingui/blob/fe1be25f5ad2801c51122c0516c81882c3645a33/packages/react/src/format.ts#L67-L76
Maybe instead of using the `index` from translation which placeholders doesn' thave, we should simply create a unique id inside the forloop...

**Comment by semoal** [comment]
> Thank you @semoal. I think it must be somewhere in `formats.ts` file (`@lingui/react` package), but there's an `index` set as a key here
> 
> https://github.com/lingui/js-lingui/blob/fe1be25f5ad2801c51122c0516c81882c3645a33/packages/react/src/format.ts#L67-L76
> 
> 
> Maybe instead of using the `index` from translation which placeholders doesn' thave, we should simply create a unique id inside the forloop...

Yes, absolutly I'll fix this

**Comment by agwells** [comment]
Thanks!
