### ISSUE TITLE
Hacktoberfest wrong count due ineligible repository

### ISSUE THREAD

**Issue by semoal** [lingui/js-lingui#758]
Hi @tricoder42, 

to hacktoberfest count the pull request, you need to add to github topic the hacktoberfest tag or `hacktoberfest-accepted` on the pull requests mate.

I don't care too much about the hackaton, but some users probably yes.

<img width="481" alt="Screenshot 2020-10-14 at 14 01 41" src="https://user-images.githubusercontent.com/22656541/95986152-d2e90f00-0e25-11eb-8077-cfe6bca02b59.png">
<img width="691" alt="Screenshot 2020-10-14 at 14 01 44" src="https://user-images.githubusercontent.com/22656541/95986141-d086b500-0e25-11eb-9db8-70e8f02caaba.png">

**Comment by tricoder42** [comment]
Thanks! I've added repository topic. Could you please confirm it is working?

**Comment by semoal** [comment]
Yes, now it's working properly i close the issue mate
