### ISSUE TITLE
[V3] Lingui compile always returns exit code 1

### ISSUE THREAD

**Issue by lucax88x** [lingui/js-lingui#766]
https://github.com/lingui/js-lingui/blob/00cefac13d06b59c1bcace153be2d84a1c54560f/packages/cli/src/lingui-compile.ts#L117

**Comment by lucax88x** [comment]
Should this line be one line below?

Otherwise this is inside forEach and will never retun true.

Infact, the compile always exits with code 1;

**Comment by tricoder42** [comment]
@lucax88x Good point! I had to missed that during a review. Could you please send a patch?

**Comment by ThiefMaster** [comment]
This was super fast :D I was just about to open an issue/PR about this as well.
