### ISSUE TITLE
[V3] Migration should be done with a codemod?

### ISSUE THREAD

**Issue by semoal** [lingui/js-lingui#774]
**Is your feature request related to a problem? Please describe.**
I found after writing the documentation there are several steps to migrate a large application:
- [x] NumberFormat and DateFormat components were removed. Use `date` and `number` formats from @lingui/core package instead.
- [x] Change import of components to `macro` from `react` package
- [X] plural parameters changed:
```diff
- plural({ value, one: "# book", other: "# books" })
+ plural(value, { one: "# book", other: "# books" })
```
- [x] i18n.t(), i18n.plural(), i18n.select() and i18n.selectOrdinal() methods are removed and replaced with macros.
- [X]  Rename `I18nProvider.defaultRender` prop to `I18nProvider.defaultComponent`
- [x]  Macros don't need to be wrapped inside `i18n._`: `i18n._(t'Message')` => `t'Message'`

### To not implement:

 - `setupI18n` can be safely removed and `i18n` can be imported from `@lingui/core` (if `setupI18n` has some parameters, I would leave it for user to handle it), **this is a easily migration for the end user so probably it's not the worth time to implement a codemod to this**

**Describe proposed solution**
I propose to write a codemod for do all this migration with a just 

```bash
npx codemod lingui-v2-to-v3
```

the user only should migrate his i18n setup from a declarative API to the new `i18n.load`, and `i18n.activate` 

What do you think @tricoder42? Probably I could get it working tomorrow or the next, with this and the documentation finished we'll have a good adoption.

**Comment by tricoder42** [comment]
Well, this would be huge improvement and it would definitely easy the transition from v2 to v3. If you have spare time in your hand, feel free to do so. There're few more changes which you haven't mentioned:

- [ ] Rename `I18nProvider.defaultRender` prop to `I18nProvider.defaultComponent`
- [ ] Macros don't need to be wrapped inside `i18n._`: `i18n._(t'Message')` => `t'Message'`
- [ ] `setupI18n` can be safely removed and `i18n` can be imported from `@lingui/core` (if `setupI18n` has some parameters, I would leave it for user to handle it)

Thank you for working on this!

**Comment by semoal** [comment]
I've already got 2/7 (in 1 hour or less), it's my first time with codemods and AST, i'll try to give it some time tomorrow!

**Comment by tricoder42** [comment]
You're awesome! No rush, there's plenty of time

**Comment by semoal** [comment]
Only have pending the `i18n.t(), i18n.plural(), i18n.select() and i18n.selectOrdinal() methods are removed and replaced with macros` task, once I got this done I'll execute the migration to some large projects I have on my company with lingui! Let it go 🚀 

<img width="836" alt="Screenshot 2020-10-22 at 14 05 31" src="https://user-images.githubusercontent.com/22656541/96870062-a27e2200-1470-11eb-880b-de33801b0116.png">

**Comment by tricoder42** [comment]
Amazing 👏  This is something I tried few years back and failed. Great job 🙇

**Comment by semoal** [comment]
https://github.com/lingui/codemods, could you push something to this repo @tricoder42, so I can do a fork and push the OFFICIAL `lingui-codemod` CLI 👍🏻

**Comment by tricoder42** [comment]
@semoal I've invited you as a collaborator. Let me know if it enables write access for you

**Comment by semoal** [comment]
> @semoal I've invited you as a collaborator. Let me know if it enables write access for you

Perfect mate, i've pushed the actual code CLI + Github Actions + V2-to-V3 transform :)

Pending to prepare is the publish method, i've run yarn link and used in some internal applications and worked pretty fine, anyways i'll keep taking some infomration

**Comment by semoal** [comment]
@tricoder42 successfully migrated a project with:
```sh
All done.
Results:
0 errors
155 unmodified
0 skipped
319 ok
Time elapsed: 13.716seconds
```

319 files, using macros, jsx, react, practically all the cases, with date, plurals..

Only had to create a i18n.js, copy from create-react-app example, change .linguirc and all working 👍🏻 

I'm pretty happy about this, we'll make the migration super easy

**Comment by tricoder42** [comment]
This is incredible. It'll definitely make the migration easier. Also great that you have just a huge repository to test it on. Well dome 👏

**Comment by tricoder42** [comment]
I believe we can close this as the `@lingui/codemods` package is managed in it's [own repository](https://github.com/lingui/codemods/).

Thanks again @semoal, this is a really helpful tool!
