### ISSUE TITLE
[V3] Trans is eating up parent component

### ISSUE THREAD

**Issue by lucax88x** [lingui/js-lingui#776]
**Describe the bug**
I think that screenshots will explain my issue better..

this 
![Screenshot_2020-10-22_18-15-20](https://user-images.githubusercontent.com/6294464/96900999-00236600-1493-11eb-8d16-b7034e72eee9.png)

renders to
![Screenshot_2020-10-22_18-15-46](https://user-images.githubusercontent.com/6294464/96901032-0b769180-1493-11eb-89d6-254024ee50fb.png)

but

this
![Screenshot_2020-10-22_18-14-13](https://user-images.githubusercontent.com/6294464/96901046-12050900-1493-11eb-85a0-8c4783aa8fc6.png)
renders to
![Screenshot_2020-10-22_18-14-33](https://user-images.githubusercontent.com/6294464/96901082-19c4ad80-1493-11eb-8aaa-e6fb560b2e72.png)

So, it's, somehow, eating the anchor element, wtf?

I am using the Trans from @lingui/macro.

**Expected behavior**
It shouldn't eat parent components

**Additional context**
It's a nextjs app with TS4 and node 14

- jsLingui version 3.0.20
- Babel version 7.7.7
- .babelrc

```json
{
  "env": {
    "production": {
      "presets": ["next/babel", "@emotion/babel-preset-css-prop"],
      "plugins": ["emotion", "macros"]
    },
    "development": {
      "presets": ["next/babel", "@emotion/babel-preset-css-prop"],
      "plugins": [["emotion", { "sourceMap": true }], "macros"]
    }
  }
}
```

**Comment by tricoder42** [comment]
It's not eating it. I believe when `Link` sees a component as a child, it doesn't wrap it in `<a>` tag. What library it is?

**Comment by tricoder42** [comment]
Also, to test my hypothesis, what is rendered when you add `<strong>Register</strong>` as a child?

**Comment by lucax88x** [comment]
I am such an idiot, I am sorry for wasting your time.

**Comment by tricoder42** [comment]
Not a big deal, this will confuse more people. I wonder if it really happens because the child of `<Link>` is a `<Trans>` component or if it's because `<Trans>` component wraps the translation in a `<React.Fragment>`.

What router library do you use? Is it the `react-router-dom`?

**Comment by tricoder42** [comment]
Could you maybe try this simple test in your app? I wonder what will `<Link>` render in both cases:

```js
function TransFragment() {
  return <>Translation</>
}

function TransString() {
  return "Translation"
}

function Test() {
  return (
    <>
      <Link><TransFragment /></Link>
      <Link><TransString /></Link>
    </>
  )
}
```

**Comment by lucax88x** [comment]
No, it's Link from nextjs.

Let me try this one.

**Comment by lucax88x** [comment]
They both render a string.

The point is another one.

If Link has a text, it will render an anchor with text, otherwise it will just render the children component, weird stuff.

Not your problem.
Infact, it was quite impossible that a child component like Trans could eat a parent, but I was wondering maybe the macro was doing something wrong.. but no, Link fault.

**Comment by tricoder42** [comment]
> No, it's Link from nextjs.

Not sure what version you use, but `Next.js` recommends to always use `<a>` as a child of `<Link>`. In fact, there several props to handle cases when child component renders `<a>` on it's own: https://nextjs.org/docs/api-reference/next/link

Anyway, glad we get to the bottom of this 👍
