### ISSUE TITLE
Babel macros do not works with TS "import type" before the macro import

### ISSUE THREAD

**Issue by renchap** [lingui/js-lingui#777]
**Describe the bug**

When using `import type { … } from "@lingui/react"` before `import { Trans } from "@lingui/macro"` the macro does not use an import for `Trans`.
This results in an obscure `Uncaught ReferenceError: Trans is not defined` error.

Note: I can reproduce this with Lingui 2, not with Lingui 3, but I think this should be fixed as the error message is not explicit at all and finding out what is happening is painful.

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```ts
import * as React from "react"

import type { withI18nProps } from "@lingui/react"
import { Trans } from "@lingui/macro"

export const Comp = () => <Trans>Foo</Trans>
```

This gets transpiled by Babel to:

```ts
"use strict";

var _interopRequireWildcard = require("@babel/runtime/helpers/interopRequireWildcard");

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.Comp = void 0;

var React = _interopRequireWildcard(require("react"));

var Comp = function Comp() {
  return /*#__PURE__*/React.createElement(Trans, {
    id: "Foo"
  });
};

exports.Comp = Comp;
```

Note that it is using `Trans` and not importing `@lingui/react` at all.

If you comment the `import type` line it works as expected.

If you have a standard `@lingui/react` import *before* the `import type`, it works fine. If you add it after, it fails the same way as above.

I think the macro wrongly detects the `import type` as a normal import, and tries to add the needed export (here `Trans`) to the import list, which is then removed from the final output by Babel as this is TS specific and needs to be trimmed from the final output.

**Additional context**

- jsLingui version ``lingui --version``: 2.9.2
- Babel version ``npm list @babel/core``: 7.12.3
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)
```json
{
  "presets": [
    "@babel/preset-typescript",
    "@babel/preset-react",
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "corejs": 3
      }
    ]
  ],
  "plugins": [
    [
      "babel-plugin-styled-components",
      {
        "ssr": false,
        "transpileTemplateLiterals": true,
        "minify": true,
        "displayName": false
      }
    ],
    "lodash",
    "macros",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-proposal-class-properties",
    [
      "@babel/plugin-transform-runtime",
      {
        "regenerator": false
      }
    ]
  ]
}
```

**Comment by tricoder42** [comment]
Hey @renchap, thanks for the report. Could you please try:
- the pre-release version of v3 LinguiJS (even on some small example, e.g. the one from `examples/next-js` in `next` branch)?
- any other macro? Just to confirm this is specific to LinguiJS and not an upstream issue of `babel-plugin-macros`

**Comment by renchap** [comment]
I just tested with v3 and I see the same issue. But in my v3 upgrade branch it does not happen anymore as I am no longer importing any type because `withI18n` has been replaced by `useLingui` everywhere.

I am not sure on how to test with another macro, do you have any example?

**Comment by semoal** [comment]
Tomorrow I'll take a look to this I guess what's the problem

**Comment by tricoder42** [comment]
I tried to fix it, but wasn't successful so far:
- I tried to add missing export types afec2dcfa4d
- I tried other macros (`preval.macro`) and it works fine
- It's not related to type import. You could import anything from `@lingui/macro` and `@lingui/react` packages in the same file to get this errror
- I also tried an alias for `Trans` macro, doesn't help

Looking at the `@lingui/macro`, it imports some stuff from `@lingui/react`, but it's not circular import issue (`@lingui/react` doesn't import anything from `@lingui/react`)

**Comment by semoal** [comment]
I found the issue, i'll push a pull request asap :)

**Comment by semoal** [comment]
Tested successfully with `yarn link @lingui/macro` with the new changes, and we get the expected result, correctly imported the @lingui/react with the correct `Trans` component!

Was easier than I expected ^^

**Comment by tricoder42** [comment]
@semoal Nice work 🥇
