### ISSUE TITLE
Support for React v17

### ISSUE THREAD

**Issue by fny** [lingui/js-lingui#789]
Just wanted this to be on everyone's radar.

**Comment by tricoder42** [comment]
Hey @fny, please provide more information. What changes are in React 17? How does it affect Lingui? What components needs to be changed to suppoprt React 17? And finally, please provide the PR will required changes.

**Comment by semoal** [comment]
React 17 doesnt include any breaking chances, its compatible out of the box. We'll need too add that version range to accepted peer dependencies

**Comment by tricoder42** [comment]
Closed in 5f78a7104

**Comment by tricoder42** [comment]
Released in [3.0.1](https://github.com/lingui/js-lingui/releases/tag/v3.0.1). Consider donating using [OpenCollective](https://opencollective.com/js-lingui) to support development and maintanence of this project 👍

**Comment by fny** [comment]
Just signed up as a donor. We'll definitely give more once we start
bringing in revenue. Cheers! 🍻
