### ISSUE TITLE
Lingui Macro TS Error

### ISSUE THREAD

**Issue by FSM1** [lingui/js-lingui#792]
**Describe the bug**
React app fails to build when importing the Trans macro.

**To Reproduce**
Create React App Typescript with the use of <Trans> macro causes a compile failure:

```
/node_modules/@lingui/macro/index.d.ts
TypeScript error in .../node_modules/@lingui/macro/index.d.ts(1,13):
'=' expected.  TS1005

  > 1 | import type { ComponentType, ReactNode } from "react"
      |             ^
    2 | import type { MessageDescriptor } from "@lingui/core"
    3 | import type { TransRenderType, TransRenderProps } from "@lingui/react"
    4 | 
```

**Expected behavior**
The app should compile

**Additional context**
Changing index.d.ts file to use `import {} from ...` instead of `import type {} from ...` resolves the issue.

The change to index.d.ts was made in [4502fc9](https://github.com/lingui/js-lingui/commit/4502fc9be128ae2aeb8fd653b7ee9da84fe7aa11)

Using @lingui/macro@3.0.0-13 resolves the compilation error.

- jsLingui version ``lingui --version`` - 3.0.0
- Babel version ``npm list @babel/core`` - @babel/core@7.12.3
- Create React App Typescript
- @lingui/macro version: 3.0.0

**Comment by tricoder42** [comment]
Hi @FSM1, it's hard to guess where's the problem when you don't provide a repository or codemod with failing code.

I've just checked [`examples/create-create-app`](https://github.com/lingui/js-lingui/tree/main/examples/create-react-app) updated to latest versions of everything and the app works fine. Please check if there're any differences in configuration with your project.

**Comment by artyomtrityak** [comment]
An issue is in new `import type ...` syntax.
I think `@babel/core@7.9` required

**Comment by PuuTheBear** [comment]
Had the same issue this was caused by using Typescript 3.7.5 and lingui 3.4.0
