### ISSUE TITLE
Write .pot file

### ISSUE THREAD

**Issue by ThiefMaster** [lingui/js-lingui#793]
**Is your feature request related to a problem? Please describe.**
Translation tools (Transifex, weblate, etc.) usually use a .pot file as an input file to load strings.
This is almost like a normal .po file but the msgstr is always empty.

**Describe proposed solution**
Add a command to create/update a pot file. The path to it should be customizable

**Describe alternatives you've considered**
While the english .po file could in theory be used, it would be nicer if there was a way to explicitly write a .pot file. Also, one may put the english .po file on gitignore since having it under version control is yet another source for annoying merge/rebase conflicts.

**Comment by tricoder42** [comment]
Hey @ThiefMaster, please stick to the issue template when requesting a new feature — Describe your problem and suggested solution.

**Comment by ThiefMaster** [comment]
updated ;)

**Comment by tricoder42** [comment]
Sounds good! I've been thinking about it for a while but never actually get a chance to code it...

> The path to it should be customizable

There's already config for `catalogs`. What about if the `.pot` file location is based on catalog location? Or do you want to customize it completely? We definitely need a path per catalog.

**Comment by ThiefMaster** [comment]
I was thinking of a cli argument but per catalog seems like a good idea..

Maybe something like this?

```js
"path": "<rootDir>/src/locales/{locale}/messages",
"pot": "<rootDir>/src/locales/messages.pot",
```

**Comment by tricoder42** [comment]
It would be great if the `template` argument was optional or completely unnecessary.

There're two patterns of catalog paths (see [docs](https://lingui.js.org/ref/conf.html#examples) for more info):
- single path `locales/{locale}/messages`
- multiple paths (`{name}` acts like a glob pattern) `components/{name}/locale/{locale}`

I believe in both cases we could simply replace `\{locale\}.*$` with `messages.pot`. That way we would endup with:
- `locales/messages.pot` in the first case
- `components/{name}/locale/messages.pot` in the second case

What do you think? If that won't be enough, we could add `template` parameter, but I think in the first iteration this could work.

**Comment by ThiefMaster** [comment]
Sounds like a good idea!

**Comment by tricoder42** [comment]
Cool, go for it! Let me know if you need to help with anything

**Comment by ThiefMaster** [comment]
Thinking about this again, did you mean that you would write *both* the locale file *and* the template the same run?

If yes, there's one big disadvantage: I'd prefer to not have lingui write the .po files at all, but instead export the pot file to a translation tool and import the po files from there. Since there's a very good chance that different tools format po files differently (wrapping longer lines etc), it would be a mess in the git diff.

FWIW, tools like python-babel have different commands: You always [extract](http://babel.pocoo.org/en/latest/cmdline.html#extract) messages first (this always creates a `.pot` file), and then you use [init](http://babel.pocoo.org/en/latest/cmdline.html#init) or [update](http://babel.pocoo.org/en/latest/cmdline.html#update) to create/update the .po files for specific locales from the template.

**Comment by tricoder42** [comment]
Yeah, my initial thought was that we simply write `pot` and all `po` files, but I see your point.

I think we could handle both in one command, but we could make configurable how the `po` files are generated. Right now it simply updates all files locally. Other option could be set `pot` file to external service and download individual `po` files:

It would be great to have `extract` and `update`  (or `sync`) commands, but that would require another major bumb. Not sure if it's worth it at this point.

**Comment by ThiefMaster** [comment]
extract/update could stay as they are right now, while adding new `extract-template` and `sync-template` commands implementing this behavior..

Anyway, maybe a command to just create a template would be the best way to start - after all, when using an external tool, that's all you need :)

**Comment by tricoder42** [comment]
You also need a command, which dowloads all locales from external too, right? How do you handle that?

**Comment by ThiefMaster** [comment]
weblate pulls/pushes directly from git (so you'd update the pot file and commit/push it)
transifex has a cli that does it (it may also have git integration, not sure)

**Comment by tricoder42** [comment]
Ah, cool! Yeah, then creating `pot` file might be enough. So, let's create a command `lingui extract-template` or `lingui template`? Whatever you find the best

**Comment by ThiefMaster** [comment]
What do you think about `lingui extract --template`?

**Comment by tricoder42** [comment]
`--template` is an option, so I would expect the command to create all `po` files and *also* `pot` file. If you're ok with it, then I agree.

**Comment by ThiefMaster** [comment]
hm, `--template-only` then?

**Comment by tricoder42** [comment]
I don't know to be honest :) I don't have much experience designing command line interfaces. I guess `--template-only` is fine. At least it's explicit 👍

**Comment by ThiefMaster** [comment]
in the end i went for `lingui extract-template` since it felt cleaner
