### ISSUE TITLE
Add config option for formatOptions - origins - lineNumbers: true / false

### ISSUE THREAD

**Issue by alesn** [lingui/js-lingui#805]
The issue is described in https://github.com/lingui/js-lingui/issues/587

The current state is there is an option in Lingui configuration "origins", which enables / disables including file paths -and- line numbers of origin in the catalog. Origins provide some context information for the translator but at the same time, especially line numbers change regularly. The file part of the origin doesn't change that much and is the part that gives context to translation. My proposal is - if there is some use for keeping line numbers in origins for someone, to add an option to 'origins' - something like 'lineNumbers: true/false" (possibly making false the default). If there isn't really need to keep the line numbers in 'origins', to remove them. What do you think?

**Comment by nathanforce** [comment]
I'd also like to keep origins but remove line numbers.  In our case the line numbers are incorrect and they don't offer much other than noise in PRs.

**Comment by semoal** [comment]
Released right now with 3.8.0! :)

**Comment by timonbimon** [comment]
A question: I tried setting lineNumbers to false which works great for the default (english) translation messages, but doesn't for the second (German) messages.po file? There I get a bunch of "empty" origins (see below). Any ideas how to also get the origins (without line numbers) in the second messages.po file?

![image](https://user-images.githubusercontent.com/14793026/124761622-455cca80-df32-11eb-90b6-829724b97350.png)
![image](https://user-images.githubusercontent.com/14793026/124761643-48f05180-df32-11eb-9abe-0bc2620150d1.png)

**Comment by alesn** [comment]
@timonbimon: Are you using the latest version of Lingui? This was happening in a previous version but it's working fine for me in the latest

**Comment by timonbimon** [comment]
Thanks updating helped indeed! Sorry for the noise!
