### ISSUE TITLE
Extract Command Appears Broken

### ISSUE THREAD

**Issue by fny** [lingui/js-lingui#811]
**Describe the bug**

--overwrite isn't working.

**To Reproduce**

I add a translation.

```
defineMessage({ id: 'DashboardPage.greenlight_pass', message: 'Greenlight Pass' })
```

Then I run

```
 npx lingui extract --overwrite --clean
```

The message has been added to the messages.json dictionary.

```
"DashboardPage.greenlight_pass": "Greenlight Pass",
```

I then modify the message.

```
defineMessage({ id: 'DashboardPage.greenlight_pass', message: 'Greenlight Pass 2'   })
```

And I run:

```
 npx lingui extract --overwrite --clean
```

Messages.json is unchanged.

- jsLingui version: 3.0.1
- Babel version @babel/core@7.12.3
- Your Babel config (e.g. `.babelrc`) or framework you use: CRA v4

**Comment by semoal** [comment]
This is a known issue, https://github.com/lingui/js-lingui/issues/616, you can work on it if you have some time =) 👍🏻

**Comment by tricoder42** [comment]
Indeed, there're multiple issues with `--override`.

Another related issue is #688

**Comment by semoal** [comment]
@fny can't reproduce this issue, can you provide a minimal repo?
I've tried with po and minimal and works as intended

![2020-11-05 12 45 24](https://user-images.githubusercontent.com/22656541/98237199-d2472280-1f64-11eb-9423-b5f1a7c814a0.gif)
