### ISSUE TITLE
Message Diffs

### ISSUE THREAD

**Issue by fny** [lingui/js-lingui#813]
**Is your feature request related to a problem? Please describe.**

Say I have a component `<Trans id="SplashPage.sign_in">Click Here to Sign In</Trans>`

I go through the workflow with extract and add a translation to all my other languages. Later on, we decide to change the text to something similar `<Trans id="SplashPage.sign_in">Sign In</Trans>`.

It would be lovely for Lingui to report a list of which keys require updating.

**Describe proposed solution**

One of these two seems like a good fit.

1. Add a `lingui diff` command which lists the keys that need to be updated based on an extract
2. Add this into lingui extract as an additional column (Language, Total count, Missing, Changed)

I'd require some guidance for the exact implementation details, but I'd be happy to help write it.

**Describe alternatives you've considered**
Just changing the key and running Lingui extract.

**Additional context**

**Comment by tricoder42** [comment]
As far as I know Transifex does it. I expect that this is handled by localization management software. Not sure if it's worth to add it to the CLI. Once the localization starts to grow, you'd like to separate developers and translators and use a dedicated localization management service.

**Comment by fny** [comment]
Understood. Given there's so much you guys have left to fix, I do agree that it doesn't make sense to add this as another thing to maintain.
