### ISSUE TITLE
Translation services accepting ICU?

### ISSUE THREAD

**Issue by vonovak** [lingui/js-lingui#82]
hi! I understand that I can get the catalog from `lingui` and send that to translation, as outlined [here](https://lingui.gitbooks.io/js/tutorials/react.html#loading-translated-messages), however, not many translation services work with ICU message format. ~~Can somebody point me to tools that work on Mac and are able to convert ICU to XLIFF, which is the translation industry standard?~~

Can somebody point me to translation services that accept (ie. are able to translate) ICU?

the [ICU website](http://userguide.icu-project.org/locale/resources) mentions `genrb` but I'm not sure it's available on mac.

also see https://github.com/yahoo/intl-messageformat/issues/106

thanks!

**Comment by tricoder42** [comment]
I'll take a look at possible options. As far as I understand it, ICU MessageFormat is format of messages, while XLIFF is format of a message catalog.

Here's similar issue https://github.com/yahoo/babel-plugin-react-intl/issues/7

**Comment by jamuhl** [comment]
We now fully support icu format at https://locize.com (and plan to extend based on your feedback / demand):

- highlighting
- validation
- machine translations
- plural conversion between source and target language
- prettify of your icu strings

<img width="1152" alt="screen shot 2017-10-29 at 14 12 00" src="https://user-images.githubusercontent.com/977772/32144336-9f3063ec-bcb7-11e7-8608-32bce526f186.png">


Your feedback would be very welcome - also if someone could provide us with a file react-intl extracts we could look into supporting that for importing (beside xliff, json, ...)

**Comment by tricoder42** [comment]
@vonovak Hi, sorry I miss the update of your question.

There're many mature services online which support ICU message format:

- [Crowdin](https://blog.crowdin.com/2016/11/09/icu-syntax-in-crowdin/)
- [PhraseApp](https://phraseapp.com/docs/guides/working-with-phraseapp/icu-message-format/)

Feel free to reopen if you had more question!

**Comment by Hotell** [comment]
I would reopen this issue.

Current version of lingui doesn't export valid getext nor json, when `Plural` -> `ICU` is used within codebase.

I've pinged PhraseApp folks. They're telling me that they support ICU but on the other hand, they have basically no idea, what format is supported regarding ICU (JSON/po).  Their docs doesn't mention anything related to ICU ->  `.po`  nor `.json` support this format. (https://phraseapp.com/docs/guides/formats/)

I would appreciate ( and I guess anyone new coming to this library ) to get some info regarding Translation services compatibility.

**Related:**
- https://github.com/lingui/js-lingui/issues/529

Thanks

**Comment by jamuhl** [comment]
@Hotell you can give https://locize.com a try...you can import / export both .json or .po -> also it should take the extracted file from jslingui as source - if there should be changes meanwhile just send us a file over to support@locize.com and we will check that so import gets updated to latest.

**Comment by tricoder42** [comment]
> Current version of lingui doesn't export valid getext nor json, when Plural -> ICU is used within codebase.

Why the exported PO file isn't valid? Is it because ID is missing as you described in other issue or the file itself isnt' syntactically valid?

---

[Transifex](https://docs.transifex.com/localization-tips-workflows/plurals-and-genders) and [Crowdin](https://support.crowdin.com/icu-message-syntax/), two biggest localization management platforms which I know, seem to support both PO files and ICU MessageFormat.
