### ISSUE TITLE
Configure the @lingui/core name in the macro

### ISSUE THREAD

**Issue by arcanis** [lingui/js-lingui#822]
**Is your feature request related to a problem? Please describe.**

I'm abstracting Lingui behind an intermediary layer, to eases maintenance (should we need to switch to a later version, we can make sure we can do this incrementally by simply updating our own layer). Unfortunately, `@lingui/macro` seems to hardcode imports to the `@lingui/core` package, meaning that Lingui still "leaks" into the consumer code. It works on typical installs due to incorrect hoisting, but fails on stricter environment like Plug'n'Play.

**Possible solution 1 (preferred)**

Use `require.resolve('@lingui/core')` instead of hardcoding `@lingui/core`.

**Possible solution 2**

Allow to configure somehow the import names. For instance I currently do something like this:

*@mypackage/i18n/macro.js*
```ts
module.exports = require(`@lingui/macro`);
```

I could do this instead:

*@mypackage/i18n/macro.js*
```ts
module.exports = require(`@lingui/macro`).custom({
  coreModule: `@mypackage/lingui/core`),
});
```

**Comment by tricoder42** [comment]
Hey @arcanis, you can configure them using [`runtimeConfigModule`](https://lingui.js.org/ref/conf.html#runtimeconfigmodule). Does it solve your problem?

**Comment by tricoder42** [comment]
Feel free to reopen if [`runtimeConfigModule`](https://lingui.js.org/ref/conf.html#runtimeconfigmodule) doesn't help

**Comment by arcanis** [comment]
Hey @tricoder42! This was exactly what I was looking for, thanks 👍
