### ISSUE TITLE
@lingui/loader! Not working as advertised (typescript?)

### ISSUE THREAD

**Issue by Bertg** [lingui/js-lingui#830]
**Describe the bug**

Using dynamicActivate (async import) of pre compiled files works. 
Prefixing ```@lingui/loader!``` to the import path fails hard.

**To Reproduce**

I have set up lingui (v3.0.3) with Typescript. 

.tsconfig
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": false,
    "jsx": "react",
    "baseUrl": "src"
  },
  "include": ["src"]
}
```

.linguirc
```json
{
   "locales": ["en", "nl"],
   "sourceLocale": "en",
   "catalogs": [{
      "path": "<rootDir>/locales/{locale}/messages",
      "include": ["<rootDir>/**"],
      "exclude": ["**/node_modules/**"]
   }],
   "pseudoLocale": "en-fo",
   "rootDir": ".",
   "format": "po"
}
```

.bablerc
```json
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    "@babel/preset-typescript"
  ],
  "plugins": [
    ["@babel/plugin-transform-runtime",
    {
      "regenerator": true
    }],
    "macros"
  ]
}
```

I have a function ```buildDynamicActivate```

```ts
const buildDynamicActivate = (i18n: any) => async (locale: string) => {
  const { messages } = await import(`../../locales/${locale}/messages`);
  i18n.load(locale, messages);
  i18n.activate(locale);
};
```

This works fine, but when I introduce ```@lingui/loader!```

```ts
const buildDynamicActivate = (i18n: any) => async (locale: string) => {
  const { messages } = await import(`@lingui/loader!../../locales/${locale}/messages`);
  i18n.load(locale, messages);
  i18n.activate(locale);
};
```

the runtime throws this error.

```
Unhandled Promise Rejection: Error: Module build failed (from ./node_modules/@lingui/loader/index.js):
TypeError: Cannot read property 'locale' of null
    at Object._default (/app/node_modules/@lingui/loader/index.js:70:35)
```

**Expected behavior**

Page not to crash, and compilation to happen on the fly as advertised.

**Additional context**

Not that the structure of this app is

```
ROOT/
  locales/
    en/...
  src/
    utils/
      dynamic_activate.ts
```

This is possibly related to #642

**Comment by semoal** [comment]
Yes, looks a bug with normalizePath, Ill take a look this night

**Comment by semoal** [comment]
Alright found the issue, file extension is mandatory 👍🏻 :

```js
const buildDynamicActivate = (i18n: any) => async (locale: string) => {
  const { messages } = await import(`@lingui/loader!../../locales/${locale}/messages`);
  i18n.load(locale, messages);
  i18n.activate(locale);
};
```

to:

```js
const buildDynamicActivate = (i18n: any) => async (locale: string) => {
  const { messages } = await import(`@lingui/loader!../../locales/${locale}/messages.po`);
  i18n.load(locale, messages);
  i18n.activate(locale);
};
```

I'll try to see if i can do the error a bit more descriptive

**Comment by semoal** [comment]
![Screenshot 2020-11-06 at 22 53 33](https://user-images.githubusercontent.com/22656541/98418333-ed0fb900-2082-11eb-9131-8e9cb5553462.png)

Okay, added this, the problem is webpack adds .js to imports that doesn't include extension, so the catalog was being searched with .js instead of catalog extension (.po|.json)

**Comment by Bertg** [comment]
Amazing! That did it. I swore I tried the as well... anyway.

As a followup...

I'm noticing HMR being triggered when a change happens to the PO file, but the translations remain the same.
Obviously the translations should get reloaded at that time.

Is there already a way of doing this? (or should i create a feature request for this?)

**Comment by Bertg** [comment]
An other followup...

The loader doesn't seem to work for pseudoTranslations:

```
Unhandled Promise Rejection: Error: Cannot find module './en-fo/messages.po'
```

```ts
{
   "locales": ["en", "nl"],
   "sourceLocale": "en",
   "pseudoLocale": "en-fo",
  // ...
}

**Comment by tricoder42** [comment]
@Bertg Yes, please. Unfrotunately there're multiple issues with pseudolocalization as I didn't manage to migrate it to v3 properly
