### ISSUE TITLE
Github Discussions

### ISSUE THREAD

**Issue by MartinCerny-awin** [lingui/js-lingui#833]
I find slightly confusing that there are two discussion services - Spectrum and Gitter. I think it would be better to unify it by introducing third one 🙄  GitHub Discussions. It is for example used by react-hook-form https://github.com/react-hook-form/react-hook-form/discussions

I think it is better to have everything at one place. Gitter looks slightly more active for lingui community, but I find it confusing that there are no channels and it is impossible to know if any answer has be solved or not.

**Comment by tricoder42** [comment]
Yes, that would be great, bu it seems to be still in beta. Do you know how to applied?

**Comment by semoal** [comment]
I posted on a public discussion in Vercel repo where @becca is proppsing internally some repos.
Its still closed but with some luck we'll get it sooner than expected

**Comment by MartinCerny-awin** [comment]
Adding link https://github.com/vercel/vercel/discussions/3874#discussioncomment-123748 so anybody who is interested can like it and maybe we get it sooner

**Comment by tricoder42** [comment]
Perfect, thank you both! I like GitHub discussions since I saw them first time, I just didn't understand how to enable it :) It's gonna be much better than Gitter and Spectrum.

**Comment by semoal** [comment]
Looks they enabled It Tom, could you check It?

**Comment by tricoder42** [comment]
Yes it does! Awesome https://github.com/lingui/js-lingui/discussions

Thank you guys for working on this! 🚀
