### ISSUE TITLE
Edge case may leave I18nProvider un-rendered

### ISSUE THREAD

**Issue by Bertg** [lingui/js-lingui#834]
**Describe the bug**

When translation are loaded async and out of react render loop it is possible that ```I18nProvider``` never renders.

**To Reproduce**

```tsx
import { i18n } from "@lingui/core";
import { detect, fromStorage, fromNavigator } from "@lingui/detect-locale";
import { I18nProvider } from "@lingui/react";
import { t } from "@lingui/macro";

const getDefaultLocale = () => {
  return detect(fromStorage("lang"), fromNavigator(), () => "en") as string;
};


const buildDynamicActivate = (i18n: any) => async (locale: string) => {
  const { messages } = await import(`../../locales/${locale}/messages.po`);
  i18n.load(locale, messages);
  i18n.activate(locale);
};

const activateLocale = buildDynamicActivate(i18n);
i18n.loadLocaleData("en", { plurals: en });
activateLocale(getDefaultLocale());

export App = () => {
  render (
    <I18nProvider>
      <span>{t`A translation`}</span>
    <I18nProvider/>
  )
}
```

In our code base this, more often than not yield a blank page.

This is due to this piece of code in https://github.com/lingui/js-lingui/blob/8979aaf81e5f839a8406d3ac7516205113944c39/packages/react/src/I18nProvider.tsx

```tsx
React.useEffect(() => {
  const unsubscribe = i18n.on("change", () => setContext(makeContext()))
  return () => unsubscribe()
}, [])

const renderKey = forceRenderOnLocaleChange && i18n.locale
if (forceRenderOnLocaleChange && !renderKey) return null
```

It is perfectly possible that the ```i18n.activate``` call occurs after the render key is calculated, but before React invokes the function defined in the ```useEffect``` hook. 

It took quite some time to figure this out, as it is very unexpected for a Provider Node like this to refuse to render. Further more this is no warning or default placeholder text at all.

**Expected behavior**

* The ```I18nProvider``` should never get stuck in a not rendering state
* There should be a warning or error (console or on screen) for the developer to show what is happening

**Additional context**

- jsLingui version 3.0.3

I fixed this in our source code in a very ugly but reliable way: 

```tsx
import React, { useEffect, useState } from "react";
import { I18nProvider as LinguiI18nProvider } from "@lingui/react";

export const I18nProvider = ({ children }: { children: React.ReactNode }) => {
  const [f, setRefreshValue] = useState(0),
    forceRefresh = () => setRefreshValue((i) => i + 1);

  useEffect(() => {
    const unsubscribe = i18n.on("change", () => {
      forceRefresh();
    });
    //
    // It is possible that i18n.activate gets called between this component being rendered,
    // and the first time this effect is called.
    // In that case, we just want to be sure and trigger a refresh just once
    //
    if (f === 0) {
      forceRefresh();
    }
    return () => unsubscribe();
  }, [f]);

  return <LinguiI18nProvider i18n={i18n}>{children}</LinguiI18nProvider>;
};

**Comment by tricoder42** [comment]
Hey @Bertg, I noticed few glitches but couldn't figure out what's the problem.

> There should be a warning or error (console or on screen) for the developer to show what is happening

Definitely 💯 agree with this. Especially when it can be disabled, it would be useful to show a user what option they have.

> The I18nProvider should never get stuck in a not rendering state

Can't we simplify it to this? `forceRefresh` inside effect is called only when `f === 0`, which is inital state. It's not called otherwise. This version might potentialy cause re-render, but it would be just a vdom re-render, not a browsers' re-paint:

```jsx
export const I18nProvider = ({ children }: { children: React.ReactNode }) => {
  const [f, setRefreshValue] = useState(0),
    forceRefresh = () => setRefreshValue((i) => i + 1);

  useEffect(() => {
    const unsubscribe = i18n.on("change", () => {
      forceRefresh();
    });

    forceRefresh();

    return () => unsubscribe();
  }, []);

  return <LinguiI18nProvider i18n={i18n}>{children}</LinguiI18nProvider>;
};
```

Then we don't need the counter, just any random hash.

**Comment by semoal** [comment]
> Hey @Bertg, I noticed few glitches but couldn't figure out what's the problem.
> 
> > There should be a warning or error (console or on screen) for the developer to show what is happening
> 
> Definitely 💯 agree with this. Especially when it can be disabled, it would be useful to show a user what option they have.
> 
> > The I18nProvider should never get stuck in a not rendering state
> 
> Can't we simplify it to this? `forceRefresh` inside effect is called only when `f === 0`, which is inital state. It's not called otherwise. This version might potentialy cause re-render, but it would be just a vdom re-render, not a browsers' re-paint:
> 
> ```js-jsx
> export const I18nProvider = ({ children }: { children: React.ReactNode }) => {
>   const [f, setRefreshValue] = useState(0),
>     forceRefresh = () => setRefreshValue((i) => i + 1);
> 
>   useEffect(() => {
>     const unsubscribe = i18n.on("change", () => {
>       forceRefresh();
>     });
> 
>     forceRefresh();
> 
>     return () => unsubscribe();
>   }, []);
> 
>   return <LinguiI18nProvider i18n={i18n}>{children}</LinguiI18nProvider>;
> };
> ```
> 
> Then we don't need the counter, just any random hash.

https://github.com/lukeed/uid we could use this lukeed lib to generate a fast hash to remove the counter

**Comment by Bertg** [comment]
I think a final solution might not need a force refresh. 
I'll work on a PR later today/tonight. 

The only issue I foresee is that this issue can not be easily replicated in a test.

**Comment by tricoder42** [comment]
Yeah, I feel your pain. I've spend several hours refreshing browser and trying figure out why it doens't work as it was supposed to work...

Any improvement here is appreciated. The way how Lingui works, if you try to render the app *before* the messages are loaded, you get a broken/empty page. We could make it somehow configurable and allow users to render text placeholder (sth like skeleton). But still, this should be opt-in. For server-side rendered pages the skipped initial render isn't a problem if we handle it correctly.
