### ISSUE TITLE
@lingui/loader does not work with pseudo locale

### ISSUE THREAD

**Issue by Bertg** [lingui/js-lingui#838]
**Describe the bug**

@lingui/loader does not work with pseudo locale

**To Reproduce**

.linguirc
```ts
{
   "locales": ["en", "nl"],
   "sourceLocale": "en",
   "catalogs": [{
      "path": "<rootDir>/locales/{locale}/messages",
      "include": ["<rootDir>/**"],
      "exclude": ["**/node_modules/**"]
   }],
   "pseudoLocale": "en-fo",
   "rootDir": ".",
   "format": "po"
}
```

```ts
const buildDynamicActivate = (i18n: any) => async (locale: string) => {
  const { messages } = await import(`@lingui/loader!../../locales/${locale}/messages.po`);
  i18n.load(locale, messages);
  i18n.activate(locale);
};

buildDynamicActivate(i18n)('en-fo'); // load pseudo translations
```

**Expected behavior**

Pseudo locale is loaded

**Additional context**

This is related to #830 and #836

- jsLingui version 3.0.3

**Comment by MartinCerny-awin** [comment]
I think there were some changes and you need to include pseudoLocale string in locales array

```
{
   "locales": ["en", "nl", "en-fo"],
   "sourceLocale": "en",
   "catalogs": [{
      "path": "<rootDir>/locales/{locale}/messages",
      "include": ["<rootDir>/**"],
      "exclude": ["**/node_modules/**"]
   }],
   "pseudoLocale": "en-fo",
   "rootDir": ".",
   "format": "po"
}
```

Documentation will get updated with #836

**Comment by tricoder42** [comment]
@Bertg Does it solve your problem when you add pseudoLocale to your `locales` as @MartinCerny-awin suggests?

**Comment by Bertg** [comment]
@tricoder42 No it doesn't.

The error does disappear, but the strings are not pseudo localised. (They are just english).

So I investigated a bit further:

I noticed a ```locales/en-fo/messages.po``` file getting created after running the extract command.
WhenI added a translation to this file, it would get pseudo localised 

This get me to think about fallbacks, so I added this: 

```
"fallbackLocales": {
  "default": "en"
}
```

And 🎊 it worked!

I guess this is because ```en-fo``` is not a valid language code, and the CLDR Parent Locale is not found (have not confirmed this).

**Opinion:** 

The pseudo locale logic should "just work". It feels weird to have to add it to the ```locales``` or ```fallbackLocales``` logic.

Instead of allowing the user to choose a single pseudo language, and having to configure it, lingui should have a strong opinion on how to do this.

Also (unrelated) should the ```sourceLocale``` not automatically be considered the ```fallbackLocales/default``` ?

**Suggestion: **

Any locale ending in ```$pseudo``` (ex: ```en-GB$pseudo```, or something similar) should be pseudo translated. 
This way there is no need for the developer to opt-in at the configuration level and any of the languages can be used as the base for pseudo translations.

**Comment by MartinCerny-awin** [comment]
The reason why you can specify any locale to be pseudolocation is that some users might have some validation checks. It is also easier to check valid locale in browsers. 

You are right about default locale. Previously we were using translations from sourceLocale. It was not correct as it expects keys to be translation. I need to update documentation specifying that fallback needs to be added for pseudolocation locale.

The benefit of having PO file is that users can add translation and it is going to be pseudolocalized as they want. I think this bigger benefit over hassle having PO file with empty translations.

The suggestion about locale ending in `$pseudo` would mean that there is less configuration, but it would also mean that it is not possible to use valid locale for pseudolocation.

**Comment by Bertg** [comment]
I'm going to push on this issue a bit more:

> The suggestion about locale ending in $pseudo would mean that there is less configuration, but it would also mean that it is not possible to use valid locale for pseudolocation.

I just don't understand why this would be valuable. What is the use case for this feature exactly? 
My suggestion can still be compatible with that use case as well, if a developer would choose to configure it that way.

> The benefit of having PO file is that users can add translation and it is going to be pseudolocalized as they want.

100% agree. But it should be optional. I think that - in the vast majority of cases - the default behaviour would be good enough.
Also it can create confusion about what actually will be seen once compiled. In the pseudo PO file I might write this translation: "†hIś Iš čöół" but it will not be compiled like that.

**Comment by MartinCerny-awin** [comment]
> I just don't understand why this would be valuable. What is the use case for this feature exactly?
> My suggestion can still be compatible with that use case as well, if a developer would choose to configure it that way.

How would it be compatible if you have naming convention that locale has to end with $pseudo?

> "PO files" But it should be optional.

If you think it would be beneficial, then I think you can feel free to add this functionality. From my perspective it would be unnecessary complicating the functionality and the code. Currently there is one place where we call pseudolocalization which makes is simple for maintenance. 

> In the pseudo PO file I might write this translation: "†hIś Iš čöół" but it will not be compiled like that.

My plan is to add a way to specify that some text should not be pseudolocalized. For example if you write "%%†hIś Iš čöół%%" then it would be compiled as "†hIś Iš čöół"

**Comment by Bertg** [comment]
> How would it be compatible if you have naming convention that locale has to end with $pseudo?

Any locale ending in `$pseudo` would be pseudo localised. Any locale that is in the list of pseudo localised languages, would also be localised. Basically we add the `$pseudo`behaviour to the current system.

I want to emphasise that the `$pseudo` is a placeholder solution, it can be anything else (ex: "~en-GB")

> Currently there is one place where we call pseudolocalization which makes is simple for maintenance.

I have not seen that part of the code yet. I don't want to make things to complicated :)

> For example if you write "%%†hIś Iš čöół%%" then it would be compiled as "†hIś Iš čöół"

Seems very reasonable

**Comment by MartinCerny-awin** [comment]
I have tagged this issue is going to be closed with my documentation changes.

Feel free to do implement less configuration pseudolocale, but I think adding fallbackLocales is not difficult and provides greater flexibility for the users. 

> Any locale that is in the list of pseudo localised languages, would also be localised. Basically we add the $pseudobehaviour to the current system.

Your idea about supporting multiple pseudolocalization could be achieved by switching string to array, which would not be too complicated. On the other side, I do not think it is common to have multiple pseudolocalizations in the app. Let me know if I am wrong.
