### ISSUE TITLE
Documentation proofreading

### ISSUE THREAD

**Issue by tricoder42** [lingui/js-lingui#85]
# Happy Hacktoberfest! 

**Working on your first Pull Request?** You can learn how from this *free* series [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)

## Problem

There's a new [documentation](https://lingui.github.io/js-lingui/). However, I'm not a native english speaker and the documentation really needs some external proofreading.

List of pages:

- **Tutorials**
  - [x] React (@BitYog)
  - [x] CLI (@BitYog)
- **Guides**
  - [x] How plurals work (@ayushgangrade)
  - [x] Dynamic loading of translations (@ayushgangrade)
- **API references**
  - [x] React (@Andrew565)
  - [x] CLI (@Andrew565)
  - [x] Configuration (@Andrew565)
- **Releases**
  - [x] Migration from 0.x to 1.x (@Andrew565)

## How-to

All documentation is in `docs` folder. It's build using Sphinx Document Generator and uses [reStructuredText](http://www.sphinx-doc.org/en/stable/rest.html).

If you want to build documentation locally, you need to have Python installed.

1. Install [`pipenv`](https://docs.pipenv.org/) tool:

```sh
pip install pipenv
```

2. Install project dependencies

```sh
pipenv install
```

After making any changes, simply run `make html` inside `docs` folder.

```sh
cd docs
make html
```

## Support

Need a help? Ping me on [gitter](https://gitter.im/lingui/js-lingui). I live in **Europe/Prague UTC+2** timezone and most of the time I answer questions on gitter instantly.

**Comment by Andrew565** [comment]
Getting started on this now. :)

**Comment by ayushgangrade** [comment]
@tricoder42 I'm also helping !

**Comment by tricoder42** [comment]
@Andrew565 @ayushgangrade Wow, that was fast! You're awesome, thanks!

I added list of pages to issue description if you would like to split the work.

**Comment by Andrew565** [comment]
Thanks @tricoder42, I'll get started with the Migration, work bottom-up.

**Comment by ayushgangrade** [comment]
Cool! I'll start working on the guides! @Andrew565

**Comment by ayushgangrade** [comment]
@Andrew565 I did some edits for the guides. I'll try to find fixes and additions for tutorials now. Not just grammar edits, more content too!

**Comment by Andrew565** [comment]
That's it for the API docs, and the last I'm going to be working on this for now. Let me know if any tweaks are needed.

Good luck with your project here, it looks really good. I'll definitely be recommending it to my team when we get around to implementing i18n.

**Comment by tricoder42** [comment]
@Andrew565 Thank you very much, you really helped me a lot! I'm gonna merge all PRs on 1st October. 🎉 

Ping me anytime if you need some help when implementing i18n.

**Comment by BitYog** [comment]
Hey, @tricoder42. I can help with the React and CLI docs. I'm a native English speaker.

**Comment by BitYog** [comment]
Hey @tricoder42. I've done the required changes and created a pull request.

**Comment by tricoder42** [comment]
@BitYog Thank you very much! Looks awesome! 🎉

**Comment by BitYog** [comment]
Thanks. I'm a first timer in open source, and I absolutely loved your work
and the way you quickly replied. BTW, got any GitHub tips?

**Comment by tricoder42** [comment]
@BitYog You mean tips for using GitHub or for interesting projects at GitHub?

For the first, I'm afraid I don't know any secret tips :) I always have to google how to add commits to someone else PR, which is the most advanced thing I've ever done on GitHub :D 

Interesting projects at GitHub: depends on what domain are you interested in. I enjoy how some people manage their projects, like @kentcdodds, @erikras, @kennethreitz (I surely forgot somebody).

**Comment by BitYog** [comment]
Hey,
Are you really merging all the PRs on 1st Oct?

**Comment by tricoder42** [comment]
@BitYog I think I should to count them for #Hacktoberfest. I couldn't find the exact rules online and DigitalOcean didn't replied to one of my tweets.

Rules says:
> To get a shirt, you must make four pull requests between October 1–31 in any timezone.

I hope they'll list all PRs on GitHub from October 1st to October 31st.

**Comment by BitYog** [comment]
👍👍👍

**Comment by kennethreitz** [comment]
Let me know if you run into any pipenv issues!

**Comment by tricoder42** [comment]
@Kennethreitz I [do](https://github.com/kennethreitz/pipenv/issues/773https://github.com/kennethreitz/pipenv/issues/773) ;) Thanks for great tool!

**Comment by BitYog** [comment]
Merging our PRs today???

**Comment by tricoder42** [comment]
I’ll merge it tonight, I’m afk right now

1. 10. 2017 v 9:27, Yog Mehta <notifications@github.com>:

**Comment by jenniferkaplannyc** [comment]
@tricoder42 Do you still need help with this? If so I'm happy to help once the pull requests have been merged.

**Comment by tricoder42** [comment]
@jenniferkaplannyc So far it's all reviewed and merged. I'm gonna add more sections to documentation this month. I'll let you know if you were still interested!

@Andrew565 @ayushgangrade @BitYog Thank you guys for great work!
