### ISSUE TITLE
t macro does not work with message descriptor

### ISSUE THREAD

**Issue by Snaptags** [lingui/js-lingui#857]
**Describe the bug**
Using this example from the documentation only the template literal text is being extracted.
Lingui ignores `message2`:
```
#: path/to/file.tsx:2
msgid "Today is Monday"
msgstr "Today is Monday"
```

**To Reproduce**
minimal code sample:

```
import { t } from "@lingui/macro";

const message1 = t`Today is Monday`;
const message2 = t({
  id: "msg.hello",
  comment: "Greetings at the homepage",
  message: `Hello Monday`,
});

```

**Expected behavior**
I'd expect both texts to be extracted to the po file:

```
#: path/to/file.tsx:2
msgid "Today is Monday"
msgstr "Today is Monday"

#. Greetings at the homepage
#: path/to/file.tsx:3
msgid "msg.hello"
msgstr "Hello Monday"
```

**Additional context**

- jsLingui version 3.1.0
- Babel version 7.12.3
- Your Babel config: Create React App 4

**Comment by semoal** [comment]
https://github.com/lingui/js-lingui/pull/846 Already fixed there, we'll release this afternoon Markus.

**Comment by Snaptags** [comment]
Perfect, sorry, must have missed that issue :-(
