### ISSUE TITLE
Add babel-macros for React

### ISSUE THREAD

**Issue by tricoder42** [lingui/js-lingui#86]
# Happy Hacktoberfest!

## Problem

babel-macros defines a standard interface for libraries that want to use compile-time code transformation. Once there're macros for most common tasks (css-in-js, preval, i18n), [create-react-app](https://github.com/facebookincubator/create-react-app/issues/2730) will adopt this plugin, which makes additional extensions of CRA apps much easier.

## How-to

Issue is marked as challenging, because we need to figure out how to convert `babel-plugin-lingui-transform-*` plugins to `babel-macros`. Also, `babel-macros` are still a new concept.

1. Take a look at [`babel-plugin-lingui-transform-react`](https://github.com/lingui/js-lingui/tree/master/packages/babel-plugin-lingui-transform-react/test/fixtures) test cases to see what transformations are supported. Ignore optimization of imports, as it's not needed with macros.

2. For each i18n component (`Trans`, `Plural`, ...) write a macro which transforms the code in the same way as babel plugin. For example, `Trans` component is transformed in this way:

```js
// before
<Trans>Hello world</Trans>
// after
<Trans id="Hello World" />
```

```js
// before
<Trans>Hello {name}</Trans>
// after
<Trans id="Hello {name}" params={{ name: name }} />
```

```js
// before
<Trans>Read <a href="">the docs</a>.</Trans>
// after
<Trans id="Read <0>the docs</0>." components=[<a href="" />] />
```

All transformations are covered in [tests](https://github.com/lingui/js-lingui/tree/master/packages/babel-plugin-lingui-transform-react/test/fixtures)

3. Create example using babel-macros. There's an [example-usecase](https://github.com/lingui/js-lingui/tree/master/packages/example-usecase) which uses plugin. Feel free to copy it and simply replace plugins with macros.

## Support

Need a help? Ping me on [gitter](https://gitter.im/lingui/js-lingui). I live in **Europe/Prague UTC+2** timezone and most of the time I answer questions on gitter instantly.

**Comment by kentcdodds** [comment]
Awesome issue @tricoder42!

If anyone wants to take this up but you're new to writing babel plugins/working with ASTs then [read this](https://babeljs.io/blog/2017/09/11/zero-config-with-babel-macros) and look at the resources at the bottom :)

Good luck. This looks like a lot of fun!

**Comment by mlabrum** [comment]
Hey,

I've got a working solution for creating a macro form of `babel-plugin-transform-react` 
https://github.com/mlabrum/js-lingui/tree/feature/macro/packages/react-macro

once https://github.com/lingui/js-lingui/pull/184 has landed I'll rebase it and submit it for a PR

Cheers :D

**Comment by tricoder42** [comment]
@mlabrum Awesome! I'm currently on vacation, so I have only limited time for review, but I'm excited that you're working on this. Kudos! 👍

**Comment by kentcdodds** [comment]
:tada:
