### ISSUE TITLE
Function `t` macros do not extract template strings

### ISSUE THREAD

**Issue by Snaptags** [lingui/js-lingui#861]
**Describe the bug**
You cannot use template strings with the t function:
```
t({message: `template`})
```
results in
```
msgid "undefined"
msgstr "undefined"
```

**Expected behavior**
```
msgid "template"
msgstr "template"
```

**Additional context**

- jsLingui version 3.2.1
- Babel version 7.12.3
- Your Babel config: Create React App

**Comment by semoal** [comment]
Same occurs with defineMessage macro, what should we do here? @tricoder42

**Comment by Snaptags** [comment]
Thanks, Sergio. Just wanted to add this remark after trying to find a workaround using defineMessage :-)

**Comment by tricoder42** [comment]
The problem is that neither macro handles template string.

```js
// This workds
t({message: t`template`})

// Also this
t({message: "template"})

// This doesn't work
t({message: `template`})
```

I'm already working on the fix. Meanwhile please use these workaround ☝️

**Comment by Snaptags** [comment]
Nice! Works for me :-)

**Comment by MartinCerny-awin** [comment]
It is is also not possible to use `components` for `t` function. 

```
i18n._(
   t({
        id: 'testID',
        components: [<a href="" />],
      })
    ),
```

It this supposed to work? In documentation it is specified that `t` is equivalent for <Trans> https://lingui.js.org/tutorials/react-patterns.html?highlight=i18n%20_#element-attributes-and-string-only-translations

**Comment by tricoder42** [comment]
@MartinCerny-awin This definitely isn't possible. `t` macro and the whole *lowercase* macros family only returns strings. You must use `Trans` and other capitalized macros if you want to use components.

`t` - function - strings only
`Trans` - React component - renders string or components

**Comment by amankkg** [comment]
@tricoder42 I wonder if this behavior is as expected:

```ts
// src/that/file.ts
import {t} from '@lingui/macro'

// ...

const nonComponentFn = (error?: any, message?: string) => {
  const helperText = error
    ? message
      ? t({id: message}) // this gets extracted as `undefined`
      : t`error` // this gets extracted as expected
    : undefined

  return {helperText}
}

/ ...
```
Extracted output
```po
#: src/that/file.ts:24
msgid "undefined"
msgstr ""
```
AFAIU, such `t` calls should not be extracted

**Comment by tricoder42** [comment]
Yeah, you're right. It shouldn't get extracted. Would you like to send a PR? This could be easy but grateful fix

**Comment by amankkg** [comment]
@tricoder42 sure, I'll take a look
