### ISSUE TITLE
Improve the extract plugin so it throws a warning/error when it tries to extract message with `undefine` id.

### ISSUE THREAD

**Issue by semoal** [lingui/js-lingui#863]
Also we should improve the extract plugin so it throws a warning/error when it tries to extract message with `undefine` id.

_Originally posted by @tricoder42 in https://github.com/lingui/js-lingui/pull/862#issuecomment-726652017_

**Comment by semoal** [comment]
I close this, because already does it. https://github.com/lingui/js-lingui/blob/main/packages/babel-plugin-extract-messages/src/index.ts#L134

**Comment by tricoder42** [comment]
Yeah, but that's only `Trans` macro. I guess we simply need to copy the same working to lines 162 https://github.com/lingui/js-lingui/blob/2bf9ebf64f9227d9e13222f368f369a54d6417fe/packages/babel-plugin-extract-messages/src/index.ts#L159-L163 and 195: https://github.com/lingui/js-lingui/blob/2bf9ebf64f9227d9e13222f368f369a54d6417fe/packages/babel-plugin-extract-messages/src/index.ts#L192-L196

the bug in js macro caused that `undefined` got extracted. That shouldn't happen, i.e. if `id` is `undefined`, we shouldn't extract any message but rather show a warning.
