### ISSUE TITLE
TypeScript error when loading messages

### ISSUE THREAD

**Issue by Snaptags** [lingui/js-lingui#865]
**Describe the bug**
I am using the code sample from https://lingui.js.org/guides/testing.html to render a I18nProvider for testing. TypeScript complains about the messages object imported:
```
  Type '(a: any) => any[]' is not assignable to type 'CompiledMessage'.
```
It works in the production code where I import messages dynamically using "await import"

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```
import { i18n } from "@lingui/core";

import { messages } from "../locale/en/messages";

i18n.load("en", messages);
```

**Expected behavior**
Accept the imported messages.

**Additional context**
- jsLingui version 3.2.1
- Babel version 7.12.3
- TypeScript version 4.0.5
- Your Babel config: Create React App

**Comment by Snaptags** [comment]
Just adding that to the CompiledMessage type in i18n.d.ts solves the problem, but I'm not quite sure that's the best way to solve it 😄 
```
export declare type CompiledMessage = string | Array<string | Array<string | (string | undefined) | Record<string, unknown>>> | ((a: any) => any[]);
```

**Comment by semoal** [comment]
Hm, and why messages are a function signature? did you extracted the messages?

**Comment by semoal** [comment]
https://github.com/lingui/js-lingui/pull/765 I believe I fixed this issue

**Comment by Snaptags** [comment]
Yes I extracted and compiled the messages. The resulting JavaScript file includes a function for any message containing placeholders of any kind:
```
    "Welcome {0}!": function (a) {
      return ["Welcome ", a("0"), "!"];
    },
```

**Comment by semoal** [comment]
The types from @types, are for lingui 2.x, since Lingui was written in Flow. Lingui 3.0 has a full rewrite with ts and provides his own types.

```
js
    "Welcome {0}!": function (a) {
      return ["Welcome ", a("0"), "!"];
    },
```

This case isn't covered on our compiledMessage type, i'll add it asap! Thanks Markus for pointing it out

**Comment by tricoder42** [comment]
The type is missing because there shouldn't be any fucntions in compiled catalog. This format has been changed in 3.x, now it should be:

```json
{ 
  "Welcome {0}!": ["Welcome ", ["0"], "!"]
}
```

@Snaptags What version of @lingui packages you have? Could you please run `yarn list | grep @lingui` and post the output? Also, what's the output of `yarn lingui --version`?

When I look at compiled catalogs inside `next.js` directory I see the correct, new format (arrays, instead of functions).

**Comment by Snaptags** [comment]
Sorry, my bad. I did not run `lingui compile` in my test project and kept using the v2.x `messages.js` files 😢 We can close this issue then?

**Comment by tricoder42** [comment]
Yes. Glad it works 👍
