### ISSUE TITLE
Unable to use certain country-Language combinations

### ISSUE THREAD

**Issue by telpochyaotl** [lingui/js-lingui#876]
**Describe the bug**
Unable to compile and load certain locales, such as 'en-GB', 'es-MX', 'es-ES', where 'en-US' and 'fr-CA' work correctly.

In earlier pre-release 3.x (next) version of lingui, I was able to define, extract and compile/load locales such as 'en-GB' and 'es-MX', 

As of v 3.1.2, these locales can be defined and extracted but compiling or trying to dynamically load them generates the following error:

`Compiling message catalogs…
/project/node_modules/@lingui/cli/api/catalog.js:218
        return catalogs[locale][key].translation;
                               ^

TypeError: Cannot read property 'whatever message' of undefined
    at getTranslation (/project/node_modules/@lingui/cli/api/catalog.js:218:32)
    at getMultipleFallbacks (/project/node_modules/@lingui/cli/api/catalog.js:244:18)
    at Catalog.getTranslation (/project/node_modules/@lingui/cli/api/catalog.js:250:9)
    at /project/node_modules/@lingui/cli/api/catalog.js:204:23
    at XWrap.f (/project/node_modules/ramda/src/mapObjIndexed.js:39:16)
    at XWrap.@@transducer/step (/project/node_modules/ramda/src/internal/_xwrap.js:17:17)
    at _arrayReduce (/project/node_modules/ramda/src/internal/_reduce.js:18:34)
    at _reduce (/project/node_modules/ramda/src/internal/_reduce.js:60:12)
    at mapObjIndexed (/project/node_modules/ramda/src/mapObjIndexed.js:38:10)
    at Object.f2 [as mapObjIndexed] (/project/node_modules/ramda/src/internal/_curry2.js:34:14)
`

**To Reproduce**
This can be reproduce in lingui's `create-react-app`:
1 - upgrade package.json to use lingui 3.2.1 and do `npm install`
2 - edit `lingui.config.js` and add `es-MX` to the `locales` array
3 - `npm run extract` and observe messages are extracted, all missing for new locale
4 - `npm run compile` and watch the error

`
Compiling message catalogs…
/git/js-lingui/examples/create-react-app/node_modules/@lingui/cli/api/catalog.js:218
        return catalogs[locale][key].translation;
                               ^

TypeError: Cannot read property 'Date formatter example:' of undefined
...
`

**Expected behavior**
As this was previously working in earlier (pre release `next`) version of lingui, extraction, compilation and loading of catalogs of these locales should be possible.

**Additional context**
It is worth noting that this problem does not exist with locales such as 'en-US', 'fr-CA', 'fr-FR', 'cs-CS' but it does with 'en-GB', 'es-ES', 'es-MX', etc.

One aspect of the problem is the fact that all the `msgstr` of the newly extracted file are empty, if all are translated then the problem goes away, so somehow the fallback or source locale strings are not used in these cases.

I Really want to thank you for such a great library, please advise in correcting this issue.

Again, Thank you!

- jsLingui version ``3.2.1``
- Babel version ``─┬ react-scripts@4.0.0
  ├── @babel/core@7.12.3 
  ├─┬ @svgr/webpack@5.4.0
  │ ├── @babel/core@7.12.3  deduped
  │ └─┬ @svgr/plugin-jsx@5.5.0
  │   └── @babel/core@7.12.3  deduped
  ├─┬ babel-jest@26.6.3
  │ ├─┬ @jest/transform@26.6.2
  │ │ └── @babel/core@7.12.3  deduped
  │ └─┬ babel-plugin-istanbul@6.0.0
  │   └─┬ istanbul-lib-instrument@4.0.3
  │     └── @babel/core@7.12.3  deduped
  ├─┬ babel-preset-react-app@10.0.0
  │ └── @babel/core@7.12.3  deduped
  ├─┬ jest@26.6.0
  │ └─┬ @jest/core@26.6.3
  │   └─┬ jest-config@26.6.3
  │     └── @babel/core@7.12.3  deduped
  └─┬ workbox-webpack-plugin@5.1.4
    └─┬ workbox-build@5.1.4
      └── @babel/core@7.12.3  deduped``

**Comment by semoal** [comment]
This is already fixed, look #869 we'll release a new version in a few days

**Comment by telpochyaotl** [comment]
Thank you for the quick reply @semoal , another problem i see which could have served as a workaround and it doesn't seem to be fixed with #869 is the fact that conf's `fallbackLanguageMigration` is ignoring any configured fallbackLocales from user configuration and overriding it with the parent languages configuration, if it wasn't ignoring one could define the default fallback language and the issue would not take place... I hope this makes sense and you can consider it. Thank you again!

**Comment by semoal** [comment]
> Thank you for the quick reply @semoal , another problem i see which could have served as a workaround and it doesn't seem to be fixed with #869 is the fact that conf's `fallbackLanguageMigration` is ignoring any configured fallbackLocales from user configuration and overriding it with the parent languages configuration, if it wasn't ignoring one could define the default fallback language and the issue would not take place... I hope this makes sense and you can consider it. Thank you again!
> 

Hm thats also fixed, with the current version fallbackLocales were ignored if cldr found. On the new version if fallbackLocales are defined, take preference over cldr

**Comment by semoal** [comment]
We released 3.2.2 give it a try mate
