### ISSUE TITLE
Unhandled Rejection for locales configuration

### ISSUE THREAD

**Issue by shubhamyedage** [lingui/js-lingui#880]
**Describe the bug**
I am facing one issue after extracting regrading `unhandled rejection`. The issue is related to the config file that's what I can say after a little digging. Here is how my config looks like,

> module.exports = {
>   locales: ['en-US', 'en-GB', 'es-MX', 'es-ES'],
>   catalogs: [
>     {
>       path: 'src/locales/{locale}',
>       include: ['src'],
>     },
>   ],
>   format: 'po',
>   sourceLocale: 'en-US',
>   fallbackLocales: { default:  'en-US' },
>   orderBy: 'messageId',
> };

But when I provide `locales: ['en', 'es', 'en-US', 'en-GB', 'es-MX', 'es-ES']` I wont get that error anymore.
The error snippet is here,
![image](https://user-images.githubusercontent.com/18259468/99962120-9b229f00-2db5-11eb-9ec6-48c993ea8e85.png)
Any help will be deeply appreciated.

**To Reproduce**
Do `lingui extract` with the following configuration. Most important part is locales.

```
module.exports = {
  locales: ['en-US', 'en-GB', 'es-MX', 'es-ES'],
  catalogs: [
    {
      path: 'src/locales/{locale}',
      include: ['src'],
    },
  ],
  format: 'po',
  sourceLocale: 'en-US',
  fallbackLocale: 'en-US',
  orderBy: 'messageId',
};

```

**Expected behavior**
Ideally, it should accept locales provided.

**Additional context**
I did go through the [BCP47](https://tools.ietf.org/html/bcp47) coding standard URL, but couldn't get much of it. All locales seem to be there in the CLDR repository.

- jsLingui version ``lingui --version 3.2.1``

**Comment by semoal** [comment]
Update to latest version please, we fixed this issue on 3.2.3, the problem is CLDR locales is returning `en-US` to "en", so if you don't define that locale, was failing, but it's already fixed
