### ISSUE TITLE
MessageDescriptor['id'] should not be possibly undefined

### ISSUE THREAD

**Issue by uqee** [lingui/js-lingui#882]
Hi, guys, first of all, thanks for the awesome library!

Seems like there's a minor issue in typings, though. I mean, `MessageDescriptor['id']` shouldn't be possibly undefined: [link to the code](https://github.com/lingui/js-lingui/blob/main/packages/core/src/i18n.ts#L32). Started to reproduce in `@types/lingui__core@3`.

**Comment by tricoder42** [comment]
Hi @uqee, well it can be undefined:

```
defineMessage({
  // id is autogenerated, it'll be "Hello {name}"
  comment: "Just a comment",
  message: `Hello ${name}`
})
```

I guess we could improve it by making a separate type for `SourceMessageDescriptor` (i.e. which appears in source code and might have id undefine) and `MessageDescriptor` (i.e. which comes from compiled catalog and always have undefined id), but I'm not sure if it's worth it and how much changes it'll require.

By the way, you don't need `@types/lingui__core@3` or any type package. Types are bundled with all @lingui packages.
