### ISSUE TITLE
Plural numbers TypeScript error 

### ISSUE THREAD

**Issue by MartinCerny-awin** [lingui/js-lingui#883]
```
  Property '_0' does not exist on type 'IntrinsicAttributes & { value?: string | number | undefined; } & TransProps & ChoiceOptions<ReactNode> & { children?: ReactNode; }'.

52             _0="There're no messages"
               ~~
```

Typescript does not allow to specify number on Plural component. 

```
          <Plural
            value={messagesCount}
            offset={1}
            _0="There're no messages"
            one="There's # message in your inbox"
            other="There're # messages in your inbox"
          />
```

I tried to have a look how to fix it, but couldn't figure it out. 

TypeScript version: 4.1.2
Lingui: 3.2.3

**Comment by semoal** [comment]
I'll fix this later, so tomorrow version Will be fixed

**Comment by semoal** [comment]
Looks like something changed internally in Typescript 4.1.2, in the future this could be a template literal type, but meanwhile to provide compatibility to 4.x.x typescript this workaround will work.
https://codesandbox.io/s/react-typescript-playground-forked-becf6?file=/src/index.tsx

**Comment by semoal** [comment]
https://github.com/lingui/js-lingui/issues/770 was fixed here, but something changed on Typescript 4.1.0 :/

**Comment by MartinCerny-awin** [comment]
Also I can see we have format prop in documentation https://lingui.js.org/ref/macro.html?highlight=plural#jsxmacro-Plural I do not see this one in typescript. Is it still available?

**Comment by tricoder42** [comment]
> Also I can see we have format prop in documentation https://lingui.js.org/ref/macro.html?highlight=plural#jsxmacro-Plural I do not see this one in typescript. Is it still available?

It is supported in core, but not sure about the `macros` (I can't find any specific reference for `format` prop). Could you please try it?

**Comment by MartinCerny-awin** [comment]
I have tried and the extracted string is same with format and without format. I will remove it from the documentation then.
