### ISSUE TITLE
Typescript error with TransProps values not existing

### ISSUE THREAD

**Issue by roypearce** [lingui/js-lingui#885]
**Describe the bug**
I should be able to pass `values` into the `Trans` component, but the typescript for `values` does not exist.

```
TS2322: Type '{ id: string; values: { myVal1: string; myVal2: string; }; }' is not assignable to type 'IntrinsicAttributes & TransProps & { children?: ReactNode; }'.
  Property 'values' does not exist on type 'IntrinsicAttributes & TransProps & { children?: ReactNode; }'.
```

**To Reproduce**
```
import { Trans } from '@lingui/macro';
...
<Trans id="my.id" values={{ myVal1: 'Hi', myVal2: 'Jon' }} />
```

**Expected behavior**
Expect `TransProps` to have `values` defined

- jsLingui version 3.2.3

**Comment by tricoder42** [comment]
Hi @roypearce,
macros aren't designed to receive values. Usually, you would provide a default message which uses variables:

```jsx
import { Trans } from '@lingui/macro';
...
<Trans id="my.id">This is the {myVal1} message {myVal2}</Trans>
```

which would be transformed into real component from `@lingui/react`:

```jsx
import { Trans } from '@lingui/react';
...
<Trans id="my.id" message="This is the {myVal1} message {myVal2}" values={{ myVal1: 'Hi', myVal2: 'Jon' }} />
```

Note the `message` in this case will be removed from production bundle. It's only used for extraction and development.

So, if you want to pass variables manually, you should use `Trans` from `@lingui/react` package.

**Comment by roypearce** [comment]
Thanks for that information @tricoder42 it's helpful in trying to understand where the responsibilities lie with the different projects.

When you say 
> Note the message in this case will be removed from production bundle. It's only used for extraction and development.
Does this apply to the message used with the `@lingui/macro` `Trans` component as well or is that only for `@lingui/react`'s `Trans` component?

**Comment by tricoder42** [comment]
Well, macros are transformed into Trans components both in production and development. That's how macros work.

`message` and `comment` props are removed from production bundles to save space. `message` is used only as a fallback when translation is missing and this all happens at the compile step. In production bundle you'll see only `<Trans id="my.id  values={{ myVal1: 'Hi', myVal2: 'Jon' }} />`
