### ISSUE TITLE
Using development version in Contributing file is outdated

### ISSUE THREAD

**Issue by MartinCerny-awin** [lingui/js-lingui#886]
Recently we have removed `scripts/release.js` file, but CONTRIBUTING.md file with description how to use development version in your project did not get updated.

https://github.com/lingui/js-lingui/blob/main/CONTRIBUTING.md#using-development-version-in-your-project

When I try to run `yarn release --dev` I get
```
$ node ./scripts/release.js --dev
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/Volumes/sites/lingui/scripts/release.js'
```

**Comment by semoal** [comment]
Yess, good point Martin I'll create a pr later

**Comment by semoal** [comment]
Done! Thanks Martin for notifying
