### ISSUE TITLE
Lingui Extract Erases All Messages when JSON is Invalid

### ISSUE THREAD

**Issue by fny** [lingui/js-lingui#888]
**Describe the bug**

Lingui overwrites messages.json if the messages.json is invalid on lingui extract.

**To Reproduce**

Run `lingui extract` with minimal output. Fill in values for one of the locales, and then make the json invalid (e.g.. drop a comma). Run `lingui extract` again. All of the messages will now be blank.

**Expected behavior**

Lingui should crash with an error that says the messages file is invalid json.

**Comment by semoal** [comment]
The error is in the codebase but is not correctly cached...
https://github.com/lingui/js-lingui/blob/main/packages/cli/src/api/formats/minimal.ts#L36

This function must throw an exception to step all the thread and don't overwrite the messages if something fails.

**Comment by semoal** [comment]
😱  Released 3.3.0 with this fix/feature introduced!

```
npx update-by-scope @lingui
```
