### ISSUE TITLE
Difference between SelectOrdinal and Plural

### ISSUE THREAD

**Issue by MartinCerny-awin** [lingui/js-lingui#892]
Could we please clarify what is the difference between SelectOrdinal and Plural. In the documentation it says

> selectOrdinal macro is similar to plural but instead of using cardinal plural forms it uses ordinal forms:

with this example:

```
<SelectOrdinal
    value={count}
    one="1st"
    two="2nd"
    few="3rd"
    other="#th"
/>
```

I do not understand why we couldn't use Plural to do the same.

```
<Plural value={count} one="1st" two="2nd" few="3rd" other="#th" />
```

these two Componets are extracted into

```
"{count, plural, one {1st} two {2nd} few {3rd} other {#th}}": "",
"{count, selectordinal, one {1st} two {2nd} few {3rd} other {#th}}": "",
```

**Comment by tricoder42** [comment]
Because plurals rules are different. English doesn't have `two` and `few` plural forms, only `one` and `other`.

In Czech is very similar:

```
{count, plural, one {auto} few {auta} other {aut}} // e.g. "1 auto", "2 auta", "5 aut"
{count, selectordinal, other {auto}} // e.g. "1. auto", "2. auto", "5. auto"
```

**Comment by MartinCerny-awin** [comment]
I am still confused. They both have the same props and they look to me that they are doing the same thing. Is it just different name for the same thing?

Why couldn't we do it the other way around?

```
{count, selectordinal, one {# auto} few {# auta} other {# aut}} // e.g. "1 auto", "2 auta", "5 aut"
{count, plural, other {#. auto}} // e.g. "1. auto", "2. auto", "5. auto"
```

**Comment by semoal** [comment]
Probably the confusion is generated because the typescript types.

SelectOrdinal only accepts one|two|other, and plural accepts any of offset|zero|one|few|many|other?

Actually we're using Plural props as SelectOrdinal props but probably this is wrong.

**Comment by MartinCerny-awin** [comment]
It is also in documentation 
SelectOrdinal https://lingui.js.org/ref/macro.html?highlight=selectordinal#jsxmacro-SelectOrdinal
Plurals https://lingui.js.org/ref/macro.html?highlight=selectordinal#id1

**Comment by tricoder42** [comment]
Yeah, the api is the same. They both should actually accept the same props. The only difference is how `value` is mapped to plural form. Imagine this pseudocode:

```js
function plural(value, forms) {
  const rule = cardinalPluralForm(value)
  return forms[rule]
}


function selectOrdinal(value, forms) {
  const rule = ordinalPluralForm(value)
  return forms[rule]
}
```

If we could somehow set the types based on runtime values, then we could use:

```js
type PluralProps = CardinalPluralForms['cs'] // 'cs' is active locale
// { one: string, few: string, other: string }

type SelectOrdinalProps = OrdinalPluralForms['cs']
// { other: string }

// However, in English it would be different
type PluralProps = CardinalPluralForms['en']
// { one: string, other: string }

type SelectOrdinalProps = OrdinalPluralForms['en']
// { one: string, two: string, few: string, other: string }
```

Compare [Czech plural rules](https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html#cs) and [English plural rules](https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html#en). There're `ordinal` and `cardinal` categories (and we don't even cover `range` plural rules).

Unfortunately, we can't either do that in Typescript or it would be pretty complex, so both function has the same props which cover all possible plural rules across all locales.

**Comment by MartinCerny-awin** [comment]
It makes sense now. I think it might be better to use PluralOrdinal instead of SelectOrdinal, but it is probably not worth a breaking change. Thanks for the explanation.

**Comment by tricoder42** [comment]
The names of macros are derived from ICU formatters, e.g. `{value, plural, ...}`, `{value, selectOrdinal, ...}` etc. I can't change the format and I thought that it'll be easier to remember to use the same names. But I got confused by it few times as well...
