### ISSUE TITLE
Module not found: Can't resolve 'fs' on monorepos

### ISSUE THREAD

**Issue by SebasG22** [lingui/js-lingui#894]
**Describe the bug**
I'm trying to make some guides to use `lingui JS` in a monorepo with Nx but the docs are unclear about that.
The problem is that when you want to import a component that is in a shared library and use the `<Trans>` `lingui JS` fails with the following errors:
```
Failed to compile
../../node_modules/@lingui/conf/index.js:22:0
Module not found: Can't resolve 'fs'
null
This error occurred during the build process and can only be dismissed by fixing the error.
```

```
error - ../../node_modules/@lingui/conf/index.js:22:0
Module not found: Can't resolve 'fs'
null
Locale data for locale "es" not loaded. Plurals won't work correctly.
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely
 forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at InboxMessages
    at Index
    at I18nProvider (C:\Users\SebasG\Documents\nx-linguijs\node_modules\@lingui\react\cjs\react.development.js:46:19)
    at CustomApp (C:\Users\SebasG\Documents\nx-linguijs\dist\apps\inbox-mail\.next\server\pages\_app.js:192:3)
    at AppContainer (C:\Users\SebasG\Documents\nx-linguijs\node_modules\next\dist\next-server\server\render.js:23:748)
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot
 to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:
1. There is a setup guide in this repo, that contains the steps to reproduce the bug with a deep level of detail.
https://github.com/SebasG22/nx-linguijs

**Expected behavior**
This behavior should not be happening in a monorepo, because the idea is to share components and also be able to use lingui to make the i18n process less painful.

**Additional context**

- jsLingui version ``lingui --version``
- Babel version ``npm list @babel/core``
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)

**Comment by sodhisaab** [comment]
@SebasG22 I am sure you were able to fix it 😄 could you please share your solution?

Thank you 🙏🏼

**Comment by ldaverio** [comment]
> @SebasG22 I am sure you were able to fix it 😄 could you please share your solution?
> 
> Thank you 🙏🏼

Yes, I would be interested, too :) Have been spending hours on the issue 😅

**Comment by SebasG22** [comment]
Hey @sodhisaab @ldaverio ,

Unfortunately, I had no luck finding the error that generates Lingui on an Nx monorepo.
Internally a library was written to replace Lingui in react apps. Sometime later we migrated to i18next for NextJS apps and it is working fine.
https://www.i18next.com/
