### ISSUE TITLE
Forward compatibility with React 16

### ISSUE THREAD

**Issue by tricoder42** [lingui/js-lingui#90]
# Happy Hacktoberfest!

**Working on your first Pull Request?** You can learn how from this *free* series [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)

## Problem

React 16 was released this week and one of many features are [new render return types: strings](https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html#new-render-return-types-fragments-and-strings).

In React <16 all text nodes needs to be wrapped in element:

```js
// This is not allowed:
const TextComponent = () => "Text only"

// This works:
const TextComponent = () => <span>Text only</span>
```

However, sometimes we need to render text inside different element. In react-native there isn't even any `<span>`, but `<Text>` component instead.

As a workaround, all i18n components support `render` prop:

```js
<Trans render={<Text styles={...} />}>Text only</Trans>

// renders
<Text styles={...}>Text only</Text>
```

In React 16, components are allowed to return text:

```js
// This is works in React 16:
const TextComponent = () => "Text only"
```

So, if i18n components return text only, we don't need to use `render` prop anymore!

```js
// Instead of
<Trans render={<Text styles={...} />}>Text only</Trans>

// …we can write:
<Text styles={...}><Trans>Text only</Trans></Text>
```

However, switching to text rendering by default would break `jsLingui` for React 15.x.

## Solution

Default rendering component can be set in `I18nProvider` using `defaultRender` prop:

```js
// example, render all translations in <Text> component
<I18nProvider defaultRender={Text}>
    <App />
</I18nProvider>
```

Let's support text rendering by setting `null` value to `defaultRender` prop:

```js
// example, return string from i18n components
<I18nProvider defaultRender={null}>
    <App />
</I18nProvider>
```

Now, users can still use `jsLingui` with React 15, but opt-in for React 16 behavior with this simple change.

# How-to

Checkout branch `react16`, which has updated dependencies and tools.

1. Rendering of all components is done in [Render](https://github.com/lingui/js-lingui/blob/master/packages/lingui-react/src/Render.js) component. You can see in `render()` method, that first it checks `render` prop, then `linguiDefaultRender` value (which is `defaultRender` passed through context) and finally it falls back to `span`. Alter the code to use `span` only if both `render` and `linguiDefaultRender` are undefined.

2. Add if condition to return `value` directly if `render` constant is `null`.

3. Add [unit tests](https://github.com/lingui/js-lingui/blob/master/packages/lingui-react/src/Render.test.js)

## Support

Need a help? Ping me on [gitter](https://gitter.im/lingui/js-lingui). I live in **Europe/Prague UTC+2** timezone and most of the time I answer questions on gitter instantly.

**Comment by annuhdo** [comment]
Ooh could I take this up for Hacktoberfest?

**Comment by tricoder42** [comment]
@annuhdo Absolutely! Marking issue as assigned. Thank you very much! ✨
