### ISSUE TITLE
Strugling with React examples

### ISSUE THREAD

**Issue by ivandotv** [lingui/js-lingui#900]
**Describe the bug**

I'm struggling to implement some examples from the:
https://lingui.js.org/tutorials/react-patterns.html#id2
It seems that `import { I18n } from "@lingui/react"` renderProp component doesn't exist anymore.

Is there a way to implement the below code, possibly without using `HOC`

**To Reproduce**

```js
import { useState, useEffect } from 'react'
import { t, Trans } from '@lingui/macro'
import { useRouter } from 'next/router'

const languages = {
  en: t`English`,
  es: t`Spanish`
}

const locales = Object.keys(languages)

export function Switcher() {
  const [locale, setLocale] = useState(router.locale.split('-')[0])

  return (
    <select value={locale} onChange={(evt) => setLocale(evt.target.value)}>
      {locales.map((locale) => {
        return (
          <option value={locale} key={locale}>
            <Trans id={languages[locale]}>{languages[locale]}</Trans>
          </option>
        )
      })}
    </select>
  )
}
```

**Expected behavior**
Text in the `<option>` element should be translated.
Instead, I get `[object object]`

- jsLingui version: 3.2.3
- Babel version: 7.12.9
- Your Babel config: Next.js

**Comment by semoal** [comment]
https://github.com/lingui/js-lingui/issues/655#issuecomment-621637390

This is a duplicated of this issue. This is not a problem itself of lingui, it's a React problem.

You can use directly t`` macro from `@lingui/macro` package
