### ISSUE TITLE
Documentation/clarifications for server side rendering

### ISSUE THREAD

**Issue by max-mykhailenko** [lingui/js-lingui#901]
Can't understand the correct way to use Lingui with SSR after updating to v3.

First of all I know that a lot of requests can be received in the same time, but you remove `setup18n` and now i18n is a singleton for all simultaneously requests. Is it correct (possible some macros magic fix this, but from docs can't understand)?

Next question is keeping `import { i18n } from "@lingui/core"` but not using it. Do we really need it?
<img width="738" alt="image" src="https://user-images.githubusercontent.com/1213198/101279693-a1a91180-37cc-11eb-98b1-b01a12cce51f.png">

**Comment by semoal** [comment]
I start from the end. You're right you don't need that import internally will use that instance, so just use macros. (If you want to create a pr to fix the docs are welcome =) )

About the first question, `setupI18n` is not removed, you can still use it if you need some extra config, that returns a i18n instance that can be used anywhere. But in the 99% cases you can use the default `{ i18n } from '@lingui/core'`

**Comment by max-mykhailenko** [comment]
@semoal thank you for your fast response. I'll create fix for this and for next section
<img width="717" alt="image" src="https://user-images.githubusercontent.com/1213198/101288144-9b7f5900-37fd-11eb-8ca4-eb779cbfcc18.png">
As I saw in types we should pass messages, but not catalogs
<img width="636" alt="image" src="https://user-images.githubusercontent.com/1213198/101288155-acc86580-37fd-11eb-9e81-fd009bee0c8e.png">

**Comment by semoal** [comment]
Perfect, thanks you very much!

**Comment by khmm12** [comment]
Hey @semoal 👋

> About the first question, setupI18n is not removed, you can still use it if you need some extra config, that returns a i18n instance that can be used anywhere. But in the 99% cases you can use the default { i18n } from '@lingui/core'.

How does it work on concurrent environments? 

Before it was possible to create as many instances as you want and use them isolated from each other. Now it became impossible without CLS on server-side. 

Yeah it's possible to get rid of macroses and live without them, but loose a syntax sugar and extracting of messages via CLI.

**Comment by seeden** [comment]
@semoal can you answer https://github.com/lingui/js-lingui/issues/901#issuecomment-773242945 I would like to know this answer too and I have no idea how to fix it without my own "t``" macro

**Comment by max-mykhailenko** [comment]
In my case I just always import i18n instance from React Context. For generating i18n I use setupI18n method. As I saw it works good. Looks like it’s not a singletone at every time used correct language. 

Of course will be better to have better way to do that. 

@khmm12 how did you solve it in your case?

**Comment by khmm12** [comment]
@max-mykhailenko 

Well, there are 2 different issues: a) wrong lingui instance on server-side due to concurrency, b) stale translations on client-side due to lack of granular subscriptions.

a) Wrong lingui instance on server-side (and isomorphic applications of course) I solved via AsyncLocalStorage + Proxy + lingui runtimeConfigModule.

<details>

<summary>example</summary>

```ts
/** @/utils/lingui.ts */

import { AsyncLocalStorage } from 'async_hooks'
import invariant from 'tiny-invariant'
import { i18n as baseI18n, I18n } from '@lingui/core'
import Language from '@/enums/language'
import createI18n from '@/utils/lingui-factory'

const storage = new AsyncLocalStorage<I18n>()

export const i18n = /* #__PURE__ */ createTrap(baseI18n, getLingui)

export function withLanguage<T>(language: Language, cb: () => T): T {
  const i18n = createI18n(language)
  return storage.run(i18n, cb)
}

export function getLingui(): I18n {
  const context = storage.getStore()
  invariant(context, 'You forgot to wrap `withLanguage`')
  return context
}

/**
 * It returns instance where all methods are proxied to dynamic `to`.
 */

function createTrap<T extends object>(from: T, to: () => T): T {
  const traps = [
    'get',
    'set',
    'has',
    'deleteProperty',
    'getPrototypeOf',
    'defineProperty',
    'getOwnPropertyDescriptor',
    'ownKeys'
  ] as const

  return new Proxy<T>(
    from,
    Object.fromEntries(
      traps.map(trap => [
        trap,
        (_target: I18n, ...args: unknown[]) => Reflect.apply(Reflect[trap], undefined, [to(), ...args])
      ])
    )
  )
}

```

```js
/** lingui.config.js **/ 

module.exports = {
  runtimeConfigModule: ['@/utils/lingui', 'i18n']
}

```

</details>

This is what I use for a small microservice which generates thousands of pdf. It can be easily adapted for a isomorphic react app. You just need a function which picks lingui instance either from a local storage on server-side or from a global/module variable on client-side.

b) What to do with stale translations due to lack of granular subscriptions I still have no idea ☹️. Reload a whole react tree is not a solution IMO.

**Comment by cah4a** [comment]
@khmm12 
I think I have a better solution:

```js
import { setupI18n } from '@lingui/core'

export default function App() {
    const i18n = useMemo(setupI18n, [])
    
    return (
        <I18nProvider i18n={i18n}>
             {/* .... */}
        </I18nProvider>
    )
}
```

The `setupI18n` function will create a fresh instance of i18n for every page, so there won't be concurrency issues.

**Comment by khmm12** [comment]
@cah4a 

It's a good solution while you don't use `t` macros together with something similar to react-ssr-prepass or streaming.

**Comment by cah4a** [comment]
@khmm12 Thanks for the clarification!

I think something like `const {_} = useI18n()` will work good instead of `t` macros
