### ISSUE TITLE
How to use Lingui with separate translations?

### ISSUE THREAD

**Issue by VladMokrousov** [lingui/js-lingui#904]
Hi, documentation does not describe what the index.js file should be when we put translation messages for each component in it directory. We should put a translation of one of the components into messages like this i18n.load('en', messages). But how we can connect the other translations?
Thank you in advance and sorry for my English :)

**Comment by semoal** [comment]
I'm not sure what you mean

messages.js will be something like this (after running lingui compile): 

```

module.exports= { "messages": { "Message": "Message" } }

```

You need to import that file, that will contain all the translations of your entire application, or the translations that you defined in .linguirc

**Comment by VladMokrousov** [comment]
I use @lingui/loader and this function

```
export async function dynamicActivate(locale: string) {
   const { messages } = await import(`@lingui/loader!./locales/${locale}/messages.json`)
   i18n.load(locale, messages)
   i18n.activate(locale)
}
```
So only one component translation stored in messages. Can i put into messages translate for all components?

**Comment by semoal** [comment]
Sure! That's how it works.

Internal default configuration:

```
{
 "catalogs": [{
   "path": "<rootDir>/locale/{locale}/messages",
   "include": ["<rootDir>"],
   "exclude": ["**/node_modules/**"]
 }],
 "compileNamespace": "cjs",
 "extractBabelOptions": {},
 "fallbackLocales": {},
 "format": "po",
 "locales": [],
 "orderBy": "messageId",
 "pseudoLocale": "",
 "rootDir": ".",
 "runtimeConfigModule": ["@lingui/core", "i18n"],
 "sourceLocale": "",
}
```

As you can see catalogs means files extracted from your source files, `include` is looking to your rootDir project, so any file using macro functions, or Trans component will be extracted to `<rootDir>/locale/{locale}/messages`

**Comment by semoal** [comment]
Feel free to take a look to repository examples, and if you find a bug feel free to open a new issue!
Thanks for using Lingui!

**Comment by VladMokrousov** [comment]
Sergio, I'll try to explain it better. I have a project structure like this

> components/
> ├── RegistrationForm/
> │   ├── locale/
> │   │  ├── en.json
> │   │  └── cs.json
> │   ├── RegistrationForm.test.js
> │   └── RegistrationForm.js
> └── LoginForm/
>     ├── locale/
>     │  ├── en.json
>     │  └── cs.json
>     ├── LoginForm.test.js
>     └── LoginForm.js

I use @lingui/loader and would like show Czech translation on the site. In index.js i use somthing like this
```
async function dynamicActivate() {
  const messages = await import(`@lingui/loader!./components/RegistrationForm/locale/cs.json`)
  i18n.load('ru', messages.messages)
  i18n.activate('ru')
}
dynamicActivate()
```
In this case i added on the site translation for RegistrationForm component. How i can add translations for RegistrationForm and LoginForm component?

**Comment by semoal** [comment]
You can use `catalogsMergePath` in configuration file to merge catalogs to one file when compiled.

**Comment by VladMokrousov** [comment]
Thank you very much!

**Comment by tricoder42** [comment]
In fact, you could even use `{name}` placeholder to match all components:

```json
{
 "catalogs": [
	 {
	   "path": "<rootDir>/components/{name}/locale/{locale}/messages",
	   "include": ["<rootDir>/components/{name}"],
	   "exclude": ["**/node_modules/**"]
	 },
 ],
 "catalogsMergePath": "<rootDir>/locales/{locale}/messages",
 "format": "po",
 "locales": ["es", "en", "ru"]
}
```

checkout the docs https://lingui.js.org/ref/conf.html#catalogs

**Comment by VladMokrousov** [comment]
Yeah, Tomáš, but i have a little bit more difficult structure of the project :)

**Comment by VladMokrousov** [comment]
Hmm, strange, but catalogsMergePath doesn't work
![er](https://user-images.githubusercontent.com/24979591/101429220-5eba7b80-393d-11eb-8b05-eb76eba14030.jpg)

**Comment by tricoder42** [comment]
What version of LinguiJS do you use?

**Comment by semoal** [comment]
I think it's an issue with actual 3.2.3, because we were using catalogsMergePath?: string, and i think jest validator when some type is optional is not working properly.
Ill fix this in the open pr about compilerOptions

**Comment by VladMokrousov** [comment]
Yeah, version 3.2.3

**Comment by stefanbugge** [comment]
Maybe I am misunderstanding something, but my experience is that setting the `catalogsMergePath` option results in no compile output at all. 
Looking into `lingui-compile.ts` I correctly see catalogs being merged to a variable `mergedCatalogs` but after that the variable is not used to produce any output.
https://github.com/lingui/js-lingui/blob/main/packages/cli/src/lingui-compile.ts#L83

**Comment by gramalinbechtel** [comment]
> https://github.com/lingui/js-lingui/blob/main/packages/cli/src/lingui-compile.ts#L83

Is this issue addressed. catalogsMergePath doesn't output to a compiled file

**Comment by semoal** [comment]
> > https://github.com/lingui/js-lingui/blob/main/packages/cli/src/lingui-compile.ts#L83
> 
> 
> 
> Is this issue addressed. catalogsMergePath doesn't output to a compiled file

No, it doesn't. Feel free to create one and we'll work on fixing this for the next iteration

**Comment by gramalinbechtel** [comment]
> > > https://github.com/lingui/js-lingui/blob/main/packages/cli/src/lingui-compile.ts#L83
> > 
> > 
> > Is this issue addressed. catalogsMergePath doesn't output to a compiled file
> 
> No, it doesn't. Feel free to create one and we'll work on fixing this for the next iteration

Any fix for this issue? catalogsMergePath doesn't output to a compiled file @semoal

**Comment by Dozalex** [comment]
Little off top, but If anyone has problems with "exclude" option, it might save time: `**` is required in "exclude" (just `<rootDir>/src/ignored/` doesn't work)

it works
```json
  "catalogs": [
    {
      "path": "<rootDir>/src/languages/{locale}/messages",
      "include": [
        "<rootDir>"
      ],
      "exclude": [
        "**/<rootDir>/src/ignored/**",
        "**/node_modules/**"
      ]
    }
  ],
```
