### ISSUE TITLE
Support id and comment in `plural` macro

### ISSUE THREAD

**Issue by MartijnHols** [lingui/js-lingui#913]
Just like the `t` macro, it would be great if `plural` also accepted an id and comment.

**Describe proposed solution**
To be able to specify an id and comment in plural:
```
plural({
  id: 'fileSelection.tooMany',
  value: maxFiles,
  one: 'You can only select # file.',
  other: 'You can only select # files.',
})
```

**Describe alternatives you've considered**
Adding the id and comment props to the existing options param seems less clean to me, especially when this is already the syntax available in `t`. Should be possible with a function overload.

Related issue: #800

**Comment by tricoder42** [comment]
Sure, it could simplify the syntax a bit. Feel free to send a PR. It would be great if you could also update `select` and `selectOrdinal` macros to accept `id` and `comment`.

Just to document the current alternative:

```js
t({
  id: 'fileSelection.tooMany',
  message: plural({
     value: maxFiles,
     one: 'You can only select # file.',
     other: 'You can only select # files.',
   })
})
```

**Comment by MartijnHols** [comment]
Ah I was unaware that was the alternative; couldn't find it in the docs or any issues but I might not have used the right search criteria. I quite like that, but I agree that a merged version may be slightly simpler.
