### ISSUE TITLE
runttimeConfigModule fails silently

### ISSUE THREAD

**Issue by ivandotv** [lingui/js-lingui#916]
**Describe the bug**
When using `runttimeConfigModule` user never knows if it's working or not. I have encountered this problem and wrote about it in #914 

**To Reproduce**
Pass in invalid values.
```js
 runtimeConfigModule: ['fake-path', 'wrongGlobalName']
```

**Expected behavior**
The error should be reported if the path is invalid.

**Additional context**

- jsLingui version: 3.2.3
- Babel version: 7.12.9
- Your Babel config: Next.js

**Comment by semoal** [comment]
Perfect, do you want to create a pull request or should we leave it open for someone?
