### ISSUE TITLE
Plural 0 doesn't seem to work.

### ISSUE THREAD

**Issue by aaronpropst** [lingui/js-lingui#917]
## Describe the bug
When I call plural(0..  I get the other string despite a 'zero' property being defined.

## To Reproduce 
using CRA:

index.js:
```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';

import { i18n } from '@lingui/core'
import { I18nProvider } from '@lingui/react'
import {en} from "make-plural/plurals";
import { plural } from '@lingui/macro';

i18n.load('en', {});
i18n.loadLocaleData({
    "en": {plurals: en},
});
i18n.activate('en');

const getPlural = (i) => plural(i, {
  zero: "Learn No React",
  one: "Learn One React",
  other: "Learn all the Reacts!"
});

ReactDOM.render(
  <React.StrictMode>
    <I18nProvider i18n={i18n}>
      <div>0 {getPlural(0)}</div>
      <div>1 {getPlural(1)}</div>
      <div>10 {getPlural(10)}</div>
    </I18nProvider>
  </React.StrictMode>,
  document.getElementById('root')
);
```
### Result
0 Learn all the Reacts!
1 Learn One React
10 Learn all the Reacts!

### Expected
0 Learn No React
1 Learn One React
10 Learn all the Reacts!

### Versions
- jsLingui version: 3.3.0
- Babel version: @babel/core@7.12.3 
- Your Babel config: Create React App

**Comment by nakkamarra** [comment]
English does not have a zero-th case. This is described [in the lingui docs](https://lingui.js.org/guides/plurals.html):

`Funny fact for non-english speakers: In English, 0 uses plural form too, 0 books.`

**Comment by aaronpropst** [comment]
Ah, ok, thanks!  So I guess my issue is with linguists and/or make-plural.  : )

I still have a use case for alternative messaging for zero cases.

I hacked that support onto my plural objects like so:

```js
import { i18n } from '@lingui/core'
import { I18nProvider } from '@lingui/react'
import {en} from "make-plural/plurals";
import { plural } from '@lingui/macro';

const alsoZero = (fn) => (n,ord) => n === 0 ? "zero" : fn(n,ord);

i18n.load('en', {});
i18n.loadLocaleData({
    "en": {plurals: alsoZero(en)},
});
i18n.activate('en');
```

It'll use the zero case if the developer specified one, failing over to 'other' if they didn't.   I think it'll work for my purposes.  I wouldn't be surprised if it fails for some advanced usage I don't yet understand though.

Thanks Again!
