### ISSUE TITLE
@lingui/detect-locale@3.3.0 npm package missing esm/index.js file

### ISSUE THREAD

**Issue by EYHN** [lingui/js-lingui#918]
**Describe the bug**
The `@lingui/detect-locale` module, the latest version currently published to npm, there is `"exports.import": "./esm/index.js"` in `package.json` but the file is missing.

This will cause the webpack build to fail and prompt.
```
Module not found: Error: Can't resolve '@lingui/detect-locale' in 'xxx/xxx'
```

**To Reproduce**
```
npm install @lingui/detect-locale@3.3.0
```

Thanks for your great work.

**Comment by semoal** [comment]
You're right mate, I'll fix this asap
