### ISSUE TITLE
i18n._ returns any in typescript

### ISSUE THREAD

**Issue by gitschwifty** [lingui/js-lingui#921]
**Describe the bug**
The type definitions for Lingui @ 3.3.0 have i18n._() returning an any value, rather than a string.

**To Reproduce**
Caught with [@typescript-eslint/no-unsafe-assignment](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unsafe-assignment.md) turned on. Any element expecting a string throws a lint error if passed the return value from i18n._(t`Some string`)

```
import { withI18n } from "@lingui/react"
import { t } from '@lingui/macro';

export default function App() {
   return <img alt={i18n._(t`An image`)} />
}
```

**Expected behavior**
For i18n._ to return a string, matching up with the external type definitions for 2.x. If it's supposed to return something other than a string sometimes, a union type rather than any.

**Additional context**
The type definition files, @lingui/core/cjs/i18n.d.ts
```
export declare class I18n extends EventEmitter<Events> {
...
    _(id: MessageDescriptor | string, values?: Object | undefined, { message, formats }?: MessageOptions | undefined): any;
...
}
```

@lingui/core/cjs/context.d.ts (after investigating and determining that i18n._ returns the result from interpolate in context)
```
export declare function interpolate(translation: CompiledMessage, locale: string, locales: Locales, localeData: Object): (values: Object, formats?: Object) => any;
```

Here's a patch I made using patch-package to keep the string return behavior for now as well.
```
diff --git a/node_modules/@lingui/core/cjs/i18n.d.ts b/node_modules/@lingui/core/cjs/i18n.d.ts
index 06a4bfe..bd83e16 100644
--- a/node_modules/@lingui/core/cjs/i18n.d.ts
+++ b/node_modules/@lingui/core/cjs/i18n.d.ts
@@ -46,7 +46,7 @@ export declare class I18n extends EventEmitter<Events> {
     load(allMessages: AllMessages): void;
     load(locale: Locale, messages: Messages): void;
     activate(locale: Locale, locales?: Locales): void;
-    _(id: MessageDescriptor | string, values?: Object | undefined, { message, formats }?: MessageOptions | undefined): any;
+    _(id: MessageDescriptor | string, values?: Object | undefined, { message, formats }?: MessageOptions | undefined): string;
     date(value: string | Date, format?: Intl.DateTimeFormatOptions): string;
     number(value: number, format?: Intl.NumberFormatOptions): string;
 }
```

Possible fix: setting the return type of the function that context returns to string, and the return type of the function that interpolate returns to string as well. This falls through to change i18n._ to return a string as well, and at the least it doesn't cause any type errors (ran lint:types), shouldn't change behavior at all since it's just specifying the return type of the function. I'll attach a PR in a second, if this is unexpected behavior it shouldn't be a major change, I tried to figure out how to do it by typing formatMessage within interpolate's returned function, but I don't know enough about the internals to figure that out at the moment.

Lines 61-80 in @lingui/core/cjs/context.ts
```
function context({ locale, locales, values, formats, localeData }) {
  const formatters = defaultFormats(locale, locales, localeData, formats)

  const ctx = (name: string, type: string, format: any): string => {
    const value = values[name]
    const formatted = formatters[type](value, format)
    const message = isFunction(formatted) ? formatted(ctx) : formatted
    return Array.isArray(message) ? message.join("") : message
  }

  return ctx
}

export function interpolate(
  translation: CompiledMessage,
  locale: string,
  locales: Locales,
  localeData: Object
) {
  return (values: Object, formats: Object = {}): string => {
```

- jsLingui version 3.3.0
- Babel version 7.12.3
- Babel config
```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    "@lingui/babel-preset-react"
  ]
}
```

**Comment by gitschwifty** [comment]
Error I received when running npm i, fixed by adding blank lingui.js in cli but not of sure the root cause
```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/.../js-lingui/node_modules/@lingui/cli/lingui.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/.../js-lingui/node_modules/@lingui/cli/lingui.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

**Comment by semoal** [comment]
I18n._ is not reccomended usage in v3. Check lingui/codemods repository for the newer methods of doing things.

**Comment by gitschwifty** [comment]
Just for clarification, this part in codemods?
```
* Macros don't need to be wrapped inside i18n._: i18n._(t'Message') => t'Message'
* i18n._(t``), i18n._(plural``), i18n._(select``) and i18n._(selectOrdinal``)
```

Definitely is nicer than using i18n._, must have missed that change in the 2.x->3.x migration guide. Thank you mate!

**Comment by semoal** [comment]
Yes! You don't need i18n._ practically for anything, you can directly import the macros and use them. :)
