### ISSUE TITLE
Are catalogs not meant to be persisted in a store?

### ISSUE THREAD

**Issue by iampava** [lingui/js-lingui#927]
**1. Describe the bug**
Storing the locale catalogs inside a MobX store leads to warnings in the console.

![image](https://user-images.githubusercontent.com/11327761/103475681-1feed880-4db8-11eb-960a-727d2b9a9d59.png)

**2. To Reproduce**
Created a sample project here: https://codesandbox.io/s/nice-smoke-vffru. Open the console and see that the warning messages are there.

If however we don't make them observable - (navigate to **i18nStore.js** and comment the code below)

```
makeObservable(this, {
  catalogs: observable,
  language: observable
});
```
the warnings will disappear.

**3. Additional context**
I went down the rabbit hole and tracked the issue to the `formatMessage` function inside `@lingui/core/cjs/core.development.js`. It seems that these lines here are accessing an out-of-bounds index which leads to the MobX warning.

```
var _token = _slicedToArray__default['default'](token, 3),
    name = _token[0],
    type = _token[1],
    format = _token[2];
```

- jsLingui version `3.3.0`
- Babel version `latest`
- CreateReactApp Babel Config by using CodeSandbox

**Comment by semoal** [comment]
Whats the main objetive to save catalogs there?

**Comment by iampava** [comment]
To be honest we don't do anything special with them. We only noticed these warning after updating to v3 so didn't pay much attention to whether or not they should be observables in the past.

**Comment by semoal** [comment]
There's no reason to store catalogs on that store because they're static and they could be really big. So we can't help so much here mate =)
