### ISSUE TITLE
Extract is finding 0 messages for typescript project using tsc, not babel

### ISSUE THREAD

**Issue by teebszet** [lingui/js-lingui#928]
**Describe the bug**
Can't seem to extract messages from `.ts` files within the project.
Docs say lingui v3 works with typescript out of the box, but I'm not seeing that.

Possibly to do with my project not depending on babel? I don't have a .babelrc file because I use `tsc` to build and dev

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```
import gql from 'graphql-tag';                                                              
import { i18n } from '@lingui/core';                                                        
                                                                                            
export default gql`                                                                         
  enum ClaimStateTranslated {                                                               
    ${i18n._('ClaimState.Draft', null, { defaults: 'Draft' })}                              
    ${i18n._('ClaimState.Lodged', null, { defaults: 'Lodged' })}                            
    ${i18n._('ClaimState.Active', null, { defaults: 'Active' })}                                                         
  }                                                                                         
`; 
```

**Expected behavior**
Expect the messages to be extracted.

**Additional context**

- jsLingui version `3.3.0`
- Babel version `none`
- Your Babel config `none`

**Comment by semoal** [comment]
Could you share your tsconfig?

**Comment by semoal** [comment]
Once i re-read the docs i understood that the problem is the documentation. To make Lingui to work you need `babel-plugin-macros`, so babel is required.

The out of the box meaning is that you don't need to install extra dependencies to handle types, because they are already inside of the library.

**Comment by teebszet** [comment]
Yeah, I think the tricky part is I was able to extract using the same dependencies and syntax before I moved project to typescript and using lingui 2.x.x

I read the docs and thought this might be fixed upgrading to lingui v3, but it didn't help.

Still struggling to find the correct syntax where I don't have to use @lingui/macro and `t` as that is what I had before converting to typescript.

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "outDir": "dist",
    "sourceMap": true,
    "strict": false,
    "noUnusedLocals": true,
    "noFallthroughCasesInSwitch": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "src/**/*.test.ts",
    "src/node_modules"
  ],
  "ts-node": {
  }
}
```

```
~$ npm ls babel-plugin-macros
project-name
├─┬ @lingui/cli@3.3.0
│ └── babel-plugin-macros@2.8.0 
└── UNMET PEER DEPENDENCY babel-plugin-macros@3.0.1 

npm ERR! peer dep missing: babel-plugin-macros@^2.4.2, required by @lingui/cli@3.3.0
npm ERR! peer dep missing: babel-plugin-macros@^2.5.1, required by @lingui/macro@3.3.0
```

**Comment by teebszet** [comment]
in case anyone else needs to extract translations from .ts files without using @lingui/macro, you need to add `/*i18n*/` on each line like this:

```
export default gql`                                                                         
  enum ClaimStateTranslated {                                                               
    ${/*i18n*/i18n._('ClaimState.Draft', null, { defaults: 'Draft' })}                              
    ${/*i18n*/i18n._('ClaimState.Lodged', null, { defaults: 'Lodged' })}                            
    ${/*i18n*/i18n._('ClaimState.Active', null, { defaults: 'Active' })}                                                         
  }                                                                                         
`; 
```

**Comment by amirqasemi74** [comment]
> in case anyone else needs to extract translations from .ts files without using @lingui/macro, you need to add `/*i18n*/` on each line like this:
> 
> ```
> /*i18n*/ i18n._('ClaimState.Draft', null, { message: 'Draft' });
> ```
> 
> or from my original example:
> 
> ```
> export default gql`                                                                         
>   enum ClaimStateTranslated {                                                               
>     ${/*i18n*/i18n._('ClaimState.Draft', null, { message: 'Draft' })}                              
>     ${/*i18n*/i18n._('ClaimState.Lodged', null, { message: 'Lodged' })}                            
>     ${/*i18n*/i18n._('ClaimState.Active', null, { message: 'Active' })}                                                         
>   }                                                                                         
> `; 
> ```
> 
> and you can't supply first param of `i18n._` like `{id: '', message: ''}` as described in migration v2 to v3 docs. `lingui extract` won't pick this up unless you use the v2 syntax

this is a clean solution. i think cli should support extraction without babel macros
