### ISSUE TITLE
Warnings for compilerBabelOptions other than empty.

### ISSUE THREAD

**Issue by mjpieters** [lingui/js-lingui#935]
**Describe the bug**
When using anything other than `compilerBabelOptions: {}` in my lingui configuration, I am issued a warning.

**To Reproduce**

create a lingui configuration file with

```json
{
    "compilerBabelOptions": {
      "minified": false
    },
    "locales": ["en"]
}
```

and run `npm run extract`, to be served with:

```none
● Validation Warning:

  Unknown option "compilerBabelOptions.minified" with value false was found.
  This is probably a typing mistake. Fixing it will remove this message.

Documentation: https://lingui.js.org/ref/conf.html
● Validation Warning:

  Unknown option "compilerBabelOptions.minified" with value false was found.
  This is probably a typing mistake. Fixing it will remove this message.

Documentation: https://lingui.js.org/ref/conf.html
```

`npm run compile` produces the same message, albeit just once.

**Expected behavior**

The configuration is correct, and should not result in a warning.

**Additional context**

- jsLingui version ``lingui --version``: 3.3.0

I suspect the `defaultConfig` definition in `@lingui/conf` needs updating, it currently sets `compilerBabelOptions` to an empty object. If I set it to the default from https://lingui.js.org/ref/conf.html#compilerbabeloptions, the warnings are gone.

**Comment by semoal** [comment]
We use `jest-validate` to validate the config is valid, but probably is not understaing well the `Record<string, unknown>`
