### ISSUE TITLE
Detecting message only with i18._

### ISSUE THREAD

**Issue by amirqasemi74** [lingui/js-lingui#937]
I have Nestjs application. I was using lingui@2.9.2 as well without babel macros and Lingui cli could detect messages like this 
and it was extracting them into .po files:
`i18n._("some message");`

But after upgrading to lingui@3 it can't detect the pattern  unless using it with macros:
```i18n._(t`some message`);```
and the problem it make is that Nestjs use `tsc` to compile files and macros not transpile and solve this is complicated i think or impossible.

I there any way to use Lingui with typescript without using macros and only `i18n._("some message");` like in version 2?

**Comment by semoal** [comment]
https://github.com/lingui/js-lingui/issues/928
Here you have a similar issue. Probably could be a good idea to use babel instead of tsc directly. :)

**Comment by amirqasemi74** [comment]
The problem is that using babel in Nestjs instead of tsc in not straightforward and have issues.
I think providing some configuration can be good to support it as you was supporting in version 2

**Comment by amirqasemi74** [comment]
any idea?

**Comment by semoal** [comment]
You have on the issue that i attached the solution without babel. Is using a comment to help @lingui know where are the translations
