### ISSUE TITLE
Snowpack plugin to transform dictionaries on the fly

### ISSUE THREAD

**Issue by amankkg** [lingui/js-lingui#944]
There is an original discussion https://github.com/lingui/js-lingui/discussions/924

TL;DR I have working plugin by the link in discussion above and I'd like to move it to LinguiJS repo

Any thoughts? I'll create a branch soon

**Comment by semoal** [comment]
https://github.com/lingui/js-lingui/pull/947
Related pr

**Comment by ljani** [comment]
I wonder what changes would be needed to use the Snowpack plugin without `babel`/`babel-plugin-macros`, since many snowpack users try to avoid `babel` usage to gain better performance? Sure, there's `i18n._`, but it's not really typesafe and [`i18n.t` was removed in 3.0](https://lingui.js.org/releases/migration-3.html#plugins-presets). I think tagged templates would have made sense with Snowpack.

**Comment by semoal** [comment]
> I wonder what changes would be needed to use the Snowpack plugin without `babel`/`babel-plugin-macros`, since many snowpack users try to avoid `babel` usage to gain better performance? Sure, there's `i18n._`, but it's not really typesafe and [`i18n.t` was removed in 3.0](https://lingui.js.org/releases/migration-3.html#plugins-presets). I think tagged templates would have made sense with Snowpack.

Could you open another issue related to this? It's more complex that just a simple plugin to dynamic compile catalogs =)

**Comment by amankkg** [comment]
> I wonder what changes would be needed to use the Snowpack plugin without `babel`/`babel-plugin-macros`, since many snowpack users try to avoid `babel` usage to gain better performance? Sure, there's `i18n._`, but it's not really typesafe and [`i18n.t` was removed in 3.0](https://lingui.js.org/releases/migration-3.html#plugins-presets). I think tagged templates would have made sense with Snowpack.
> 
> 

In my case described here #924 we're using babel macros for other libraries too, even this way one can get better performance comparing to CRA, I believe

However, I haven't researched other scenarios actually. Any ideas or knowledge sharing in #924 is appreciated

**Comment by semoal** [comment]
We'll release this the next tuesday :)

**Comment by semoal** [comment]
Failed to publish the package due permissions issue, I'll speak with @tricoder42 if he can publish it manually.
