### ISSUE TITLE
Documentation typos

### ISSUE THREAD

**Issue by goozo** [lingui/js-lingui#949]
**Describe the bug**
In the react docs (https://lingui.js.org/tutorials/react.html) there are multiple instances of the incorrect contraction `there're` this isn't correct English, it should be "there are", "there're" does not exist.
**To Reproduce**

visit these urls: 

https://lingui.js.org/tutorials/react.html#beware-of-zeroes
https://lingui.js.org/tutorials/react.html#beware-of-zeroes
(multiple instances on the page)

**Expected behavior**
"there're" should be written as "there are"

**Comment by semoal** [comment]
> @goozo Can I work on this issue?

Go for it! :)

**Comment by 96RadhikaJadhav** [comment]
@semoal Can you please review my PR. Please let me know if any other changes required.
