### ISSUE TITLE
Vanilla JavaScript/TypeScript improvements

### ISSUE THREAD

**Issue by ljani** [lingui/js-lingui#951]
**Is your feature request related to a problem? Please describe.**
[Snowpack](https://www.snowpack.dev/) is an emerging [[1],[2]] build tool for web frontends. It focuses on build performance by using [`esbuild`](https://esbuild.github.io/) and additionally by avoiding transpilation with [`babel`](https://babeljs.io/). Thus, many Snowpack users try to avoid usage of `babel` in their development pipeline.

As `lingui` relies heavily on [`babel-plugin-macros`](https://github.com/kentcdodds/babel-plugin-macros), it would be nice to see an alternative, type-safe API without `babel-plugin-macros` to be used with for example Snowpack.

**Describe proposed solution**
- The first thing that came to my mind is using [tagged templates](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates). `lingui` used to support them (with `i18n.t`), but [the support was removed in v3](https://lingui.js.org/releases/migration-3.html#plugins-presets). I'm not sure why they were removed, or if there are any challenges to them, but I wonder if they could be revived?

**Describe alternatives you've considered**
- There's the low-level `i18n._`, but it's not very type-safe. It's easy to forget the parameters.
- One can [add `babel` to Snowpack](https://www.npmjs.com/package/@snowpack/plugin-babel), however it has some performance hit on building and generally many Snowpack users try to avoid it.
- I wonder if I could implement my own tagged templates on top of `i18n._`.
- Is it possible to write [an esbuild plugin](https://esbuild.github.io/plugins/) similar to `babel-plugin-macros`?

**Additional context**
See also: https://github.com/lingui/js-lingui/discussions/924, https://github.com/lingui/js-lingui/issues/944, https://github.com/lingui/js-lingui/pull/947

[1]: https://osawards.com/javascript/2020
[2]: https://2020.stateofjs.com/en-US/technologies/build-tools/

**Comment by amankkg** [comment]
I like the `... write an esbuild plugin` option but it will add yet another snowpack related package, given #947

Anyway, good to have alternative solutions since there are many other use cases people work with, e.g. one can just use typescript plugin without esbuild or babel at all.

**Comment by villasv** [comment]
Came here from #989 and just wanted to voice my support for this part of the proposal:

> The first thing that came to my mind is using tagged templates. lingui used to support them (with i18n.t), but the support was removed in v3.

Having to adopt babel just for the sake of macros was really painful.

> There's the low-level i18n._, but it's not very type-safe. It's easy to forget the parameters.

This is what I tried initially and was willing to forsake the typing (perhaps even make a PR improving it), but as said in #989, it won't produce a catalog when running `lingui extract`.
