### ISSUE TITLE
Macro `Plural` are not extracted correctly with `component` prop

### ISSUE THREAD

**Issue by chuyik** [lingui/js-lingui#959]
**Describe the bug**
If marco `<Plural>` is passed with `component` prop, this prop will also be extracted to message catalog.

**To Reproduce**

```tsx
import { Plural } from "@lingui/macro"

export default function App() {
  const count = 1
  const Div = ({ children }) => <div>{children}</div>

  return (
    <Plural
      id="message"
      value={count}
      _0="No messages"
      one="# message"
      other="# messages"
      component={Div}
    />
  )
}
```

This code will extracts incorrect message like follows:

```json
{
  "message": {
    "translation": "{count, plural, =0 {No messages} one {# message} other {# messages} component {{Div}}}",
    "message": "{count, plural, =0 {No messages} one {# message} other {# messages} component {{Div}}}",
    "extractedComments": []
  }
}
```

Please notice that ``component {{Div}}`` is appended to `message.translation` and `message.message`.

**Expected behavior**
The `component` prop should be ignored.

**Additional context**

- jsLingui version `3.4.0`
- Babel version `@babel/core@7.12.10`

**Comment by semoal** [comment]
Released 3.5.0
