### ISSUE TITLE
Documentation on t in react common patterns is incorrect

### ISSUE THREAD

**Issue by control-flow** [lingui/js-lingui#965]
**Describe the bug**
In my understanding the example in the react tutorial section of the API documentation is incorrect.

```
import { I18n } from "@lingui/react"
import { t } from "@lingui/macro"

export default function ImageWithCaption() {
   return (
      <I18n>
         {({ i18n }) => (
            <img src="..." alt={i18n._(t`Image caption`)} />
         )}
      </I18n>
   )
}
```

The `t` macro is resolved to `i18._(msg)` during compile step. The documentation in the macro section seems to be correct (https://lingui.js.org/ref/macro.html#t).

**To Reproduce**
* Setup default app by follow the instructions.
* Create a standard react app with the following code

```
import React from 'react';

import { i18n } from '@lingui/core';
import { defineMessage, t } from '@lingui/macro';
import { I18nProvider } from '@lingui/react';

import { messages as messagesEN } from './locales/en/messages.js'

i18n.load('en', messagesEN)
i18n.activate('en')

function App() {
  return (
    <I18nProvider i18n={i18n}>
      <div>{i18n._(t`incorrect`)}</div>
      <div>{i18n._(defineMessage({ message: `correct`}))}</div>
    </I18nProvider>
  );
}

export default App;
```

* Run compile and have a look into the main chunk:
```
children: [
    Object(i.jsx)("div", {
    children: a.i18n._(a.i18n._("incorrect")),
    }),
    Object(i.jsx)("div", { children: a.i18n._({ id: "correct" }) }),
],],
```

**Expected behavior**
Since `t` is compiled to `i18n._` it should never be wrapped by `i18n._` as the documentation suggests. 

Did I miss something here?

**Comment by semoal** [comment]
Yes, we have some sections of the documentation still doing the things like version 1. 
Thanks for opening the issue, we'll look into it mate
