### ISSUE TITLE
Changelog is broken with 3.5.0 release

### ISSUE THREAD

**Issue by chuyik** [lingui/js-lingui#968]
**Describe the bug**
Hi there, Thanks for the release! I found that Changelog is not rendered correctly with these release,
I think it's the problem with the text `<Select /> pseudolocalization`, as the quotes are not escaped.

3.5.0: https://github.com/lingui/js-lingui/blob/ad08fa2c5c3a3b5ed9098c5719a09b8b7bb5ef5b/CHANGELOG.md
3.4.0: https://github.com/lingui/js-lingui/blob/1dbc26cd8fe323fb511f0903ddbf7d2ffd7e6994/CHANGELOG.md

**Comment by semoal** [comment]
Yes, just saw i corrected it on releases page  https://github.com/lingui/js-lingui/releases
