### ISSUE TITLE
Mention in the docs that non BCP-47 locales are possible. For example Brazilian Portuguese .

### ISSUE THREAD

**Issue by capaj** [lingui/js-lingui#982]
**Is your feature request related to a problem? Please describe.**
Can linguijs support Brazilian Portuguese ? According to the docs it does not.
In https://lingui.js.org/ref/conf.html#locales it says that locales `Each locale must be a valid BCP-47 code.`
but looking at https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html
there's only `European Portuguese`.

**Describe proposed solution**
Not sure-maybe we can say that `pt-br` is also allowed and plurals will get used from `pt`?
**Describe alternatives you've considered**

**Comment by semoal** [comment]
Does plurals change from pt to pt-br?

**Comment by capaj** [comment]
no, but if you're suggesting I use just `pt` in my `lingui.config` that won't work, because we want to support `pt-pt` as well, which is that european portugese. Obviously both of these need to have their own message catalog.

**Comment by semoal** [comment]
But just asking, I'm not sure about this:
```json
{
 "locales": ["pt-br", "pt-pt"]
}
```

```js

  import { i18n } from "@lingui/core"
  import { pt } from 'make-plural/plurals'

  i18n.loadLocaleData('pt-br', { plurals: pt })
  i18n.loadLocaleData('pt-pt', { plurals: pt })

```

I think this should work, and if doesn't, must work.

**Comment by capaj** [comment]
Oh yeah, that works, I just forgot to use `kebabCaseLang`
`i18n.activate(kebabCaseLang)` instead `i18n.activate(lang)` as have the languages in Graphql enum and those don't support dashes.

Anyway I'll keep this open, because IMHO the documentation should be amended to say something like:
```
Each locale should be a valid BCP-47 code. If you use a string that is not a BCP-47, make sure to use a BCP-47 when defining plurals in 18n.loadLocaleData(). 
For example: i18n.loadLocaleData('pt-br', { plurals: pt })
```
