### ISSUE TITLE
lingui/core plurals doesn't work in production

### ISSUE THREAD

**Issue by alexeiapostol** [lingui/js-lingui#984]
**Describe the bug**
it seems that ` i18n.loadLocaleData` is doesn't work in production, reason why plurals doesn't work too

**To Reproduce**

```
index.js file

import { I18nProvider } from "@lingui/react";
import { i18n } from "@lingui/core";
import { en } from 'make-plural/plurals';
import translate from "./translate.json";


i18n.loadLocaleData({
  "en-US": { plurals: en },
});

i18n.load("en-US", translate);
i18n.activate("en-US");

...

    <I18nProvider i18n={i18n}>
      <App />
    </I18nProvider>
```

```
app.js file

import { useLingui } from "@lingui/react";

function App() {
  const { i18n } = useLingui();

  return (
    <div>
      {i18n._({ id: "resultCount", values: { count: 1 } })}
    </div>
  );
}
```

```
trnslation.json

{"resultCount":"{count, plural, zero {Found no entries.} one {Found one entry.} other {Found # entries.}}"}

```
**Expected behavior**
In both production and development environments  App component should render `Found one entry.`, but in production, is returned json key value (`{count, plural, zero {Found no entries.} one {Found one entry.} other {Found # entries.}}`)`

**Additional context**

- jsLingui version ``^3.5.1``
- It was used latest version of `Create React App` for reproducing this bug

**Comment by semoal** [comment]
What's this?
```
{i18n._({ id: "resultCount", values: { count: 1 } })}
```

**Comment by semoal** [comment]
Take a look to create-react-app example in the examples/ folder and check how syntax plural works..

**Comment by alexeiapostol** [comment]
I'm using i18n_ instead of macros ([@lingui/macro - Reference](https://lingui.js.org/ref/macro.html))

and I'm using this
```
import { i18n } from "@lingui/core/cjs/core.development";
```

because simple `import { i18n } from "@lingui/core";` doesn't work with plurals in production mode

**Comment by alexeiapostol** [comment]
what is difference between these two files?

```
if (process.env.NODE_ENV === "production") {
  module.exports = require("./cjs/core.production.min.js")
} else {
  module.exports = require("./cjs/core.development.js")
}
```
