### ISSUE TITLE
Have a way to do extraction when not using babel or react

### ISSUE THREAD

**Issue by capaj** [lingui/js-lingui#989]
**Is your feature request related to a problem? Please describe.**
I have a TS file(not a TSX file) with an arbitrary string and I would like to localize it. I actually have hundreds of files like that and a the moment I cannot use extraction, because extraction needs babel macro or at least a JSX <Trans /> component.

**Describe proposed solution**
Ideally I can import `t` from '@lingui/core' and use that one for translation and extraction can pick it up too.
At the moment there is no such export.

**Describe alternatives you've considered**
I can write my own tagged template literal and fork the `@lingui/cli` extraction of messages, but lingui should have this usecase covered IMHO

**Comment by semoal** [comment]
https://github.com/lingui/js-lingui/issues/951
Also related to this, we're discussing it internally how to resolve for this situations

**Comment by villasv** [comment]
Any pointers at the work one would have to accomplish to add support for `i18n._` message extraction?

**Comment by villasv** [comment]
From what I gathered looking at the [babel-plugin-extract-messages](https://github.com/lingui/js-lingui/blob/c567ea4c40f6e5b6f00f2930bdc9388e4b95dc9f/packages/babel-plugin-extract-messages/src/index.ts), it looks like messages are found thanks to the /*i18n*/ comments inserted by the `t` macro (or the `Trans` tag).

Looks like [a while back](https://github.com/lingui/js-lingui/commit/b5a11f4fa97f92b50b8d91a15ce7f0a961ec151c#diff-9317c05f72203559bc3788fb80d76d19f38b457e50c35c430463d964574eec90) it would extract messages from `i18n._` calls.
