### ISSUE TITLE
Plural tags failing to be transformed after updating Webpack & React

### ISSUE THREAD

**Issue by vitexikora** [lingui/js-lingui#99]
Basically I just updates some of my deps (webpack 2->3, React 15.6->16, and some loaders) and after trying to run the project I am getting errors like this:

```js
ERROR in ./src/components/common/GalleryItem.js
Module build failed: SyntaxError: D:/webs/czvirtuosi_presentation/src/components/common/GalleryItem.js: Missing fallback argument 'other'.

  29 |               {photoCount > 0 && (
  30 |                 <p>
> 31 |                   <Plural value={photoCount} one={`${photoCount} fotografie`} few={`${photoCount} fotografie`} other={`${photoCount} fotografií`} />
     |                   ^
  32 |                 </p>
  33 |               )}
  34 |             </header>
```

Every plural, each with an other props. Importing like this:
```js
import { withI18n, Trans, Plural } from 'lingui-react'
```

How to solve this ASAP? I tried some more combinations of props, reinstalling the babel preset, reinstalling whole lingui, nothing helped, I am using the lastest version.

**Comment by tricoder42** [comment]
What's your `.babelrc` please?

**Comment by tricoder42** [comment]
Try adding plugins instead of preset:

```json
{
  "presets": [
    // other plugins *above* lingui
    "lingui-transform-js",
    "lingui-transform-react",
  ]
}
```

This usually helps when you have `transform-runtime` plugin, but I would need to see your `.babelrc` to be sure.

**Comment by vitexikora** [comment]
.babelrc variants that I tried without getting any results:
```json
{
  "plugins": [
    "transform-decorators-legacy",
    "transform-class-properties",
    "transform-es2015-classes",
    "transform-runtime",
    "lingui-transform-react",
    "syntax-dynamic-import",
    "react-hot-loader/babel"
  ],
  "presets": [
    "env",
    "react",
    "lingui-react",
    "stage-0",
  ],
  "env": {
    "test": {
      "plugins": [
        "dynamic-import-node"
      ]
    }
  }
}
```
```json
{
  "plugins": [
    "transform-decorators-legacy",
    "transform-class-properties",
    "transform-es2015-classes",
    "transform-runtime",
    "lingui-transform-react",
    "syntax-dynamic-import",
    "react-hot-loader/babel"
  ],
  "presets": [
    "react",
    "es2015",
    "lingui-react",
    "stage-0",
  ]
}
```
```json
{
  "plugins": [
    "transform-decorators-legacy",
    "transform-class-properties",
    "transform-es2015-classes",
    "transform-runtime",
    "syntax-dynamic-import",
    "react-hot-loader/babel"
  ],
  "presets": [
    "react",
    "es2015",
    "lingui-react",
    "stage-0",
  ]
}
```

**Comment by vitexikora** [comment]
Tried this, no help, same error:
```json
{
  "plugins": [
    "transform-decorators-legacy",
    "transform-class-properties",
    "transform-es2015-classes",
    "transform-runtime",
    "syntax-dynamic-import",
    "react-hot-loader/babel",
    "lingui-transform-js",
    "lingui-transform-react"
  ],
  "presets": [
    "env",
    "react",
    "stage-0",
  ],
  "env": {
    "test": {
      "plugins": [
        "dynamic-import-node"
      ]
    }
  }
}
```

**Comment by tricoder42** [comment]
I've added minimal test project to branch [`regression-99`](https://github.com/lingui/js-lingui/tree/regression-99/examples/regression-99), but I can't get the same error. Could you please try to clone this repo, checkout `regression-99` branch and run `npm start` inside `examples/regression-99` directory?

If it doesn't help, have you tried to turn it off and on again? :) In terms of Node.js it's `rm -rf node_modules && npm install`... I know it sucks, but sometimes it helps...

If it doesn't help either, could you please share your webpack config?

**Comment by vitexikora** [comment]
the minimum project was missing babel-core, so I installed it, however the error is there...
```js
ERROR in ./src/Regression.js
Module build failed: SyntaxError: D:/webs/js-lingui/examples/regression-99/src/Regression.js: Missing fallback argument 'other'.

   5 |   return (
   6 |     <div>
>  7 |       {photoCount > 0 && <Plural value={photoCount} one="One" other="Other" />}
     |                          ^
   8 |     </div>
   9 |   )
  10 | }

 @ ./src/index.js 15:18-41
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.js
webpack: Failed to compile.
```

what could it be? nodejs version?

**Comment by tricoder42** [comment]
I have Node.js v8.5.0, what's your version?

**Comment by vitexikora** [comment]
Yeah, that was it....
Just deployed it also on the server, which has node@v8.1.1, and it also works. My machine has ancient 4.4.7 (which is now in maintenance), so Im updating...
Still its weird that it worked before, but thats not important now.

Thanks a lot for assistance!

**Comment by vitexikora** [comment]
So I can finally confirm this, after installing node v8.6.0 the problem disappeared. 
It is likely worth reflecting in project dependencies, to save time anybody else, who would stumble upon this (currently there is node >4.0).
