### ISSUE TITLE
CLI - Extract [files...] arguments ignored

### ISSUE THREAD

**Issue by donocode** [lingui/js-lingui#998]
**Describe the bug**
Using `lingui extract file1.js file2.js` is expected to extract messages only from the two files provided, this does not appear to be the case as when providing file arguments all files are processed anyway. In the docs this argument is presented https://lingui.js.org/ref/cli.html#extract.

This was mentioned in #966 but the conversation never addressed it

**To Reproduce**
1. Run extract and provide one or more file path arguments e.g. `lingui extract file1.js`.
2. See all files are processed by `extract`

**Expected behavior**
As mentioned in the docs https://lingui.js.org/ref/cli.html#extract it should only extract messages from files (or directories) passed as args

**Additional context**
I checked the source and it looks like these file arguments are ignored completely as `program.args` is never referenced https://github.com/lingui/js-lingui/blob/main/packages/cli/src/lingui-extract.ts

- jsLingui version ``3.5.3``

**Comment by semoal** [comment]
Yes, actually it's a regression, i'll check it as soon as possible.

**Comment by semoal** [comment]
Released on 3.7.2. Thanks for reporting this issue mate.

**Comment by donocode** [comment]
Thanks for the speedy fix!
